Fix typeahead to avoid generating new backend request on each keypress.
grafana/grafana pull request #10596
Opened 2018-01-23 20:04 UTC by jameswestover

In the query editor window when you start typing in the field, tag value, tag key, or measurement fields it sends an individual request to the influx backend for each and every key that you press.

If you have a large tag set on the backend Influx instance, these queries are very expensive and can cause the influx backend to tip over at times.

This change implements a half second wait when typing before sending the request to a backend.

2018-01-23 20:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=10596) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=10596) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=10596) it.</sub>

2018-01-24 14:37 UTC, torkelo requested changes
Might be cleaner using the lodash debounce method? wonder what the optimal wait time is 
 https://lodash.com/docs/4.17.4#debounce

2018-01-24 17:43 UTC, jameswestover commented
Updated it to use the lodash debounce method. I was wondering about that optimal time as well. 500 milliseconds works well for a user experience when I was testing it out locally.

2018-01-25 19:54 UTC, jameswestover reviewed
Changed to debounce.

2018-01-26 08:27 UTC, merged

2018-01-26 13:34 UTC, jameswestover commented
@torkelo Will this change be back ported to the next 4.x release?

2018-01-26 13:46 UTC, torkelo commented
no, only security fixes are at this point. We are very close to v5 beta (next week)

2018-01-29 07:39 UTC, torkelo commented
had to revert this as it caused the initial showing of dropdowns to be delayed which felt really bad. 

https://github.com/grafana/grafana/issues/10646

https://github.com/grafana/grafana/commit/cd2161e7966fd05daed843ee5e45cac78b335d13

2018-01-29 07:39 UTC, torkelo commented
Can you come up with a solution that wont effect initial load?

2018-01-29 14:48 UTC, jameswestover commented
Yeah, I'll take a look.

2018-02-09 15:21 UTC, torkelo commented
this was fixed by adding leading: false to debounce method, fixed in https://github.com/grafana/grafana/pull/10861