[WIP] Add 'created' time to annotation database
grafana/grafana pull request #11333
Opened 2018-03-22 01:26 UTC by ryantxu

This adds a `created` column to the annotations table and lets you sort by it.

See #11328

2018-03-22 13:36 UTC, daniellee commented
My thoughts:

- Adding created and updated columns is totally reasonable. :heavy_check_mark: 
- Search by userId :heavy_check_mark: 
- Search for user created annotations -> would prefer not to use a comparison with zero. Adding a type field would be better. :heavy_check_mark: 
- Can you explain the reasoning behind sorting? Don't really understand the use case for it.

2018-03-22 13:51 UTC, ryantxu commented
Great -- I will improve the pull request and ping you when it is worth looking at.

Sorting:  We are using the annotations to have mechanical engineers comment and highlight information in historical data.  I want to see these comments in a list of who created them when.  Think of this as a commenting system where I want to see recent comments.

I will remove sorting from this issue to keep things simple.  For now I can have the client select 1000 values and sort in the client, but it does feel appropriate to include in the API.  I would recommend the same syntax and feature for the dashboards API too 😃

2018-03-22 20:04 UTC, ryantxu commented
ok @daniellee, I think it is ready for review.

This is my first attempt at go (not counting a painful attempt at a influx patch), so I'm just stabbing in the dark.  It seems to work though!

2018-03-23 10:55 UTC, torkelo commented
Like the  change to ms epoch and the migration, was a mistake on my end to do second epochs

2018-03-23 21:26 UTC, bergquist commented
@ryantxu For future ref. don't update the Changelog in the PR. Whoever merges to PR is responsible for that. I'll make sure to update our contributing.md

2018-04-04 10:10 UTC, daniellee requested changes

2018-04-04 10:10 UTC, daniellee commented on pkg/services/sqlstore/migrations/annotation_mig.go
> +	updateEpochSql := "UPDATE annotation SET epoch = (epoch*1000)"
To be on the safe side, should be something like this:

```sql
UPDATE annotation SET epoch = (epoch*1000) where epoch < 9999999999
```

2018-04-04 10:10 UTC, daniellee commented on pkg/services/sqlstore/migrations/annotation_mig.go
> +	mg.AddMigration("Convert existing annotations from seconds to miliseconds", new(RawSqlMigration).
spelling: milliseconds

2018-04-09 10:50 UTC, ryantxu commented
@daniellee good catch with annotations!  I think i have made the requested changes.  I have not done much testing with the API though, so good to wait if 5.1 is on its way out :)

2018-04-09 11:09 UTC, torkelo commented
looks good. 

1) Think for the graphite format cmd.When is in seconds so needs to be multipled by 1000 here https://github.com/grafana/grafana/blob/master/pkg/api/annotations.go#L166

2018-04-14 15:23 UTC, daniellee approved these changes

2018-04-14 15:25 UTC, daniellee commented
Looks good to me - I think we will include it in the 5.2 release.

2018-04-20 15:17 UTC, merged