[WIP]Permission list UX
grafana/grafana pull request #11422
Opened 2018-03-28 14:28 UTC by Ijin08

Fixes #10747

<img width="1052" alt="skarmavbild 2018-03-28 kl 16 25 11" src="https://user-images.githubusercontent.com/23470681/38035548-ef39435a-32a4-11e8-9280-0951318ac2aa.png">

2018-03-29 04:10 UTC, torkelo commented
this needs to be rebased on master (please have daniel or someone help you with that)

2018-03-29 16:34 UTC, marefr requested changes
Code looks good :+1: 

* When adding a user or team permission the avatar is missing. Refreshing the page and the avatar are rendered correctly.
* /pkg/api/folder_permission.go should also have the 
UserAvatarUrl and TeamAvatarUrl populated.
* Icons for admin, editor, viewer should be bigger. I barely see them now. Not exactly sure what was decided regarding which icons to use but would be nice with different icons for viewer and editor.
* Documentation of permissions probably needs updated image. Also http api for folder and dashboard permissions needs to be updated with UserAvatarUrl ,TeamAvatarUrl and TeamEmail. 

Docs can wait until this has been merged I suppose.

2018-04-04 13:59 UTC, marefr requested changes
I pushed some backend changes so that correct team avatar is returned (default if no team email set).

You've fixed my earlier change request partially, i.e. works for user, but not for teams. Size of icons are applies to disabled rows, but not role permissions.

2018-04-04 13:59 UTC, marefr commented on public/app/core/components/Permissions/DisabledPermissionsListItem.tsx
> +          <i style={{ width: '25px', fontSize: '1.5rem' }} className="gicon gicon-shield" />
Would be nice with a specific gicon-class name for this in scss if not already exists. Seems like this style is needed as well in PermissionListItem.tsx (when there are no avatar).

2018-04-04 13:59 UTC, marefr commented on public/app/core/components/Permissions/PermissionsListItem.tsx
> +  console.log(item);
Remove

2018-04-04 13:59 UTC, marefr commented on public/app/stores/PermissionsStore/PermissionsStore.ts
> +    setUser(userId: number, userLogin: string, userAvatarUrl: string) {
Same is needed for setTeam. When you add a new team permission the team avatar is not rendered

2018-04-06 07:55 UTC, Ijin08 commented
@marefr The viewer and editor icons aren't 100% decided yet. Will talk with Trent about them.

2018-04-07 08:05 UTC, marefr approved these changes
Nice! Approving this, but won't merge until the icons have been sorted out.

One question/concern if we should sort permessions or not. Seems to be sorted now by time they as added, see screenshot:

![image](https://user-images.githubusercontent.com/1668778/38452760-08eb6050-3a4b-11e8-858e-7bc6174fa4f5.png)

2018-04-09 07:09 UTC, Ijin08 commented
@marefr Yes they should be sorted: role-team-user. I guess the roles should be sorted admin-editor-viewer. And teams and roles alphabetically. 

@torkelo your thoughts on this?

2018-04-09 07:38 UTC, torkelo commented
yes, should be sorted like you suggest.

2018-04-09 07:43 UTC, marefr commented
@Ijin08 @torkelo I guess there's an edge case when having inherited permissions, or not? Feels natural for me that the inherited ones are displayed first and then the others. Both sorted according to suggested. Don't know if this makes sense, but something to discuss/think of.

2018-04-09 07:45 UTC, torkelo commented
yea, inherited should be first, I agree

2018-04-13 12:37 UTC, marefr approved these changes
Great work :+1:

2018-04-13 12:45 UTC, marefr requested changes
Would like to have some tests of the PermissionStore (if possibly) to make it more clear what the expected sort order are.

2018-04-16 19:53 UTC, marefr approved these changes

2018-04-17 07:39 UTC, merged

2018-04-17 07:40 UTC, marefr commented
Awesome work @Ijin08 :+1: