docs: adds provisioning examples for all datasources
grafana/grafana pull request #11423
Opened 2018-03-28 15:43 UTC by bergquist

closes #11363

2018-03-29 16:08 UTC, marefr requested changes
Overall looks good. Some typos as pointed in comments. Think that link to *Configure datasource with provisioning* for all data sources from the provisioning page would be nice.

Some general thoughts that we should fix later/create issue for: We document all the settings you can do in UI for each data source, but not what their equivalent in JSON/yaml are.

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/elasticsearch.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/graphite.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/influxdb.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/mysql.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/opentsdb.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/postgres.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/postgres.md
> +      sslmode: "disable" # disable/require/verify-ca/verify-full
Nice!

2018-03-29 16:08 UTC, marefr commented on docs/sources/features/datasources/prometheus.md
> +Here are some examples of how you can configure the Cloudwatch datasource using configuration.
typo

2018-04-09 12:58 UTC, bergquist commented
ping @marefr

2018-04-09 15:31 UTC, marefr requested changes
You fixed another typo that I didn't spot :+1: But I was referring to another one. See comment on elasticsearch which are needed for all data source docs.

2018-04-09 15:31 UTC, marefr commented on docs/sources/features/datasources/elasticsearch.md
>  Here are some examples of how you can configure the Cloudwatch datasource using configuration.
That fix was nice, didn't spot that :smile: 

But I was referring to the *Cloudwatch* reference. Must be changed for all data sources except Cloudwatch. Maybe we can skip the name of the data source and just use *configure this datasource for provisioning* or similar?

2018-04-13 13:27 UTC, marefr approved these changes

2018-04-13 13:36 UTC, merged