bound the esc key to exit timepicker
grafana/grafana pull request #11430
Opened 2018-03-29 07:17 UTC by Ijin08

fixes #11332

2018-03-29 08:51 UTC, marefr requested changes
Basically, it works to close the time picker with escape when opened. Have no feedback on code, looks good.

If I'm in view/edit mode of a panel, open timepicker and then escape I would expect the timepicker to be closed and still have view/edit mode, but right now it closes timepicker and edit/view mode - **needs to be fixed**.

However I agree on the comment in #11332 :
> in 4x you could close the picker by clicking anywhere not in the popup. In 5x it stays open until you hit either 'apply' or the range button again.

Would be **nice to fix this now as well (if possible)**, if not we should create a new issue for that.

2018-03-29 09:56 UTC, Ijin08 commented
Thanks for feedback!

About the comment there is an issue already: #10757

2018-03-29 11:36 UTC, marefr commented
Okay. Would like that issue to be part of some milestone at least. Can discuss it with team...

2018-03-29 15:52 UTC, marefr requested changes
Earlier problem with going into edit/view mode is fixed :+1: 

Found another issue. Included animated gif below but you can't see when I press the esc key. However, if you open the timepicker and click on the time it will close which is good. However if I now go in to edit/view mode and press escape the time picker shows up. Think you need to publish an event from timepicker when it's closing so that you can sync the state (closed/open) in keybindingSrv.ts.

![image](https://user-images.githubusercontent.com/1668778/38098913-85d07516-3379-11e8-98a3-da3dd94efc96.png)

2018-04-04 12:59 UTC, marefr requested changes
It works as expected, but I would like some changes of the code.

2018-04-04 12:59 UTC, marefr commented on public/app/features/dashboard/timepicker/timepicker.ts
> +    this.$rootScope.appEvent('escTimepicker');
This looks weird. The timepicker should not care about if esc or any other key is pressed. We want the timepicker to be as dumb as possible and only care about it's internal functionality.

2018-04-04 12:59 UTC, marefr commented on public/app/features/dashboard/timepicker/timepicker.ts
>        this.isOpen = false;
Here we probably want to emit appEvent that timepicker is closed, i.e. `timepicker-closed`. I think a function closeDropdown would be nice where bot `this.isOpen = false;` and the appEvent is emited. Then you can call this function at the end of `setRelativeFilter` and `applyCustom`.

2018-04-04 12:59 UTC, marefr commented on public/app/features/dashboard/timepicker/timepicker.ts
> +    this.$rootScope.appEvent('escTimepicker');
See comment above about timepicker-closed

2018-04-04 12:59 UTC, marefr commented on public/app/features/dashboard/timepicker/timepicker.ts
> +    this.$rootScope.appEvent('escTimepicker');
See comment above about `timepicker-closed`

2018-04-04 12:59 UTC, marefr commented on public/app/features/dashboard/timepicker/timepicker.ts
>    }
Here we probably want to emit appEvent that timepicker is opened, i.e. `timepicker-opened`.

2018-04-04 12:59 UTC, marefr commented on public/app/core/services/keybindingSrv.ts
> +    $rootScope.onAppEvent('escTimepicker', () => {
Handle `timepicker-closed` and `timepicker-opened` events here instead

2018-04-04 23:00 UTC, marefr approved these changes

2018-04-05 13:11 UTC, merged