Respect dashboard timezone setting when doing CSV export (issue #10497)
grafana/grafana pull request #11453
Opened 2018-04-01 09:10 UTC by svet-b

This should fix https://github.com/grafana/grafana/issues/10497

This is my first PR for Grafana, so apologies if I haven't got something right. In that context, a couple of notes:
- I'm not quite sure why my edits to `file_export.ts` got "pretty-formatted" and split over multiple lines like that. Is it possible it was the pre-commit script? Should I try to revert to the original (single-line) formatting?
- I ended up naming the boolean flag `utc`, as the export-data modal seemed to take issue with the camel case in `isUtc`, and I figured that `isutc` in on balance more confusing than just`utc`.
- The existing tests were all based on CSV exports using unix timestamps only, so this change would not have made a difference. Therefore I haven't updated the tests - and I also haven't written new ones. I can add tests if that would be desirable. Though figured I'd get this out sooner rather than later and get feedback.

2018-04-02 05:49 UTC, torkelo requested changes
Thanks for contributing and making Grafana better! this looks like it needs some minor changes and unit tests :)

2018-04-02 05:49 UTC, torkelo commented on public/app/plugins/panel/graph/module.ts
> +      templateHtml: '<export-data-modal data="seriesList" utc="isUtc"></export-data-modal>',
you do not need to send this flag like this, the ExportDataModalCtrl can inject the dashboardSrv and get the current dashboard and check timezone that way.

2018-04-02 05:49 UTC, torkelo commented on public/app/features/dashboard/export_data/export_data_modal.ts
> +        fileExport.exportSeriesListToCsvColumns(this.data, this.dateTimeFormat, this.excel, this.utc);
not sure isUtc is the best parameter name, we might want to add support for many different timezones, so sending a timezone paramater is probably more future proof ('utc', 'local', etc)

2018-04-03 04:12 UTC, svet-b commented
Thanks @torkelo for the pointers - both make a lot of sense. In particular, agree it's good to keep it flexible for future implementation of timezones other than local and UTC (which is something we'd be very interested in having :) ). I'm on holiday this week but will take a look and update next week.

2018-05-08 14:03 UTC, torkelo commented
closing this due to lack of updates, can reopen again if there is more changes.

2018-05-08 14:03 UTC, closed without merging