settings icons fix
grafana/grafana pull request #11572
Opened 2018-04-12 08:46 UTC by Ijin08

added styling to fontawesome icons so they have same size as the other icons

<img width="207" alt="skarmavbild 2018-04-12 kl 10 42 38" src="https://user-images.githubusercontent.com/23470681/38666206-af01c4ba-3e3e-11e8-994a-af56f356091b.png">

2018-04-13 12:57 UTC, marefr requested changes
Code looks good. Seem to be some inconsistencies regarding height of menu item/icon positioning. Seems like the permissions link is the only one higher than the others. Personally to me it looks like the versions and permissions icons not are aligned vertically with text.  See screenshots below. 

![image](https://user-images.githubusercontent.com/1668778/38735955-b5758fd8-3f2a-11e8-8ba6-93be7f2d8bbe.png)

![image](https://user-images.githubusercontent.com/1668778/38735946-b15f3a7a-3f2a-11e8-8be6-f4248f49daf0.png)

2018-04-16 12:37 UTC, Ijin08 commented
@marefr I know, the problem here is the fontawesome icon that has white space beneath it so it gets pushed up. I am not sure how to push it down.

2018-04-16 15:15 UTC, marefr commented
Tried to make it a little better:
![image](https://user-images.githubusercontent.com/1668778/38817880-9be4b6b8-4199-11e8-81df-6e6aeea949e5.png)

@bulletfactory @Ijin08 what do you think?

2018-04-16 20:01 UTC, marefr approved these changes

2018-04-17 07:22 UTC, merged