Added requests/sec(throughput)
grafana/grafana pull request #11694
Opened 2018-04-23 10:06 UTC by flopp999

https://github.com/grafana/grafana/issues/9630

2018-04-23 10:39 UTC, bergquist requested changes

2018-04-23 10:39 UTC, bergquist commented on public/app/core/utils/kbn.ts
> +        { text: 'requets/sec (rps)', value: 'rps' },
This conflicts with reads/sec

2018-04-24 06:31 UTC, flopp999 commented on public/app/core/utils/kbn.ts
> +        { text: 'requets/sec (rps)', value: 'rps' },
I have now changed from rps to reqps

2018-04-24 19:30 UTC, bergquist approved these changes

2018-04-24 19:30 UTC, bergquist commented
Thank you for contributing!

2018-04-24 19:30 UTC, merged

2018-04-24 20:42 UTC, mjtrangoni commented on public/app/core/utils/kbn.ts
> +        { text: 'requets/sec (rps)', value: 'reqps' },
@bergquist This should be `request` instead of `requets`