fixed so user who can edit dashboard can edit row
grafana/grafana pull request #11699
Opened 2018-04-23 15:47 UTC by Ijin08

fixes #11466

2018-04-23 16:02 UTC, torkelo commented
looks great, just needs an update to the unit test

2018-04-23 17:37 UTC, marefr requested changes
Failing test needs to be fixed. Otherwise looks good

2018-04-24 08:32 UTC, marefr requested changes
Really good :+1: Have some tiny requests left, see comments.

2018-04-24 08:32 UTC, marefr commented on public/app/features/dashboard/specs/DashboardRow.jest.tsx
> +    dashboardMock.meta = { canEdit: true };
I suggest to initialize the dashboardMock in one assignment, like this:

```javascript
dashboardMock = { 
  toggleRow: jest.fn(),
  meta: { 
    canEdit: true 
  }
};
```

2018-04-24 08:32 UTC, marefr commented on public/app/features/dashboard/specs/DashboardRow.jest.tsx
> +    dashboardMock.meta.canEdit = false;
Naming of test should be changed to reflect possibility to edit instead of having role viewer.

2018-04-24 12:57 UTC, marefr approved these changes

2018-04-24 12:57 UTC, merged

2018-04-24 13:00 UTC, marefr commented
Great work @Ijin08 :+1: