fix XSS vulnerabilities in dashboard links
grafana/grafana pull request #11813
Opened 2018-05-03 13:07 UTC by alexanderzobnin

This PR fixes XSS vulnerabilities in dashboard link components. This happens when you put html with XSS as a link title, like `<img src='' onerror=alert("XSS") />` in 
Panel -> General -> Drilldown / detail link -> Title or 
Dashboard -> Links -> Tooltip

2018-05-03 18:18 UTC, 1Jesper1 commented
Hello, good to see a PR. I found this vulnerability when I typed XSS in the Drilldown / detail link in the title field. After filling in the title field the dashboard field was automatically filled with the same value (XSS). When adding the detail link and hovering over the information icon, the XSS was also executed.

2018-05-04 09:38 UTC, 1Jesper1 commented
Yes, this PR fixes it.

2018-05-04 15:19 UTC, marefr requested changes
Code looks good and it fixes XSS problems with link titles and tooltips. 

Would be nice with some XSS tests for the link_srv though.

I tried and added `javascript:alert('XSS')` to the url (for absolute url's) and clicking such a link executes the javascript. Don't know if we should create a separate issue for that or try to solve it in this. What do you think?

2018-05-04 19:47 UTC, alexanderzobnin commented
I think we can cover several XSS issues by this PR.

2018-05-08 09:27 UTC, marefr approved these changes

2018-05-08 09:28 UTC, merged

2018-05-14 20:05 UTC, 1Jesper1 commented
Good to see this issue fixed! When will this be rolled out?

2019-01-28 05:04 UTC, noasand commented
The same vulnerability also occurs in the following places:

1. Dashboard > Add Panel > Text Panel > Set Options -> Mode(html) & Content(<script>alert('XSS');</script>)
2. Dashboard > Add Panel > Table Panel > Set Column Styles > Check Render value as link > set Url(javascript:alert('XSS'))
3. Dashboard > Dashboard Settings > Set dashboard name(TEST<script>alert('XSS')</script> > Save dashboard and go back to dashboard home > Edit any panel > Add link, in General > Write the 'TEST' on the dashboard blank

And, these vulnerabilities are currently registered as CVE.
(CVE-2018-18623, CVE-2018-18624, CVE-2018-18625)

How can I get help to fix it?

2019-01-28 08:58 UTC, marefr commented
@noasand for 1) will be fixed in next major release by #4117. 2) and 3) Please open a new issue. Thanks

2019-01-28 23:04 UTC, noasand commented
Thank you!
 
-----Original Message-----
From: "Marcus Efraimsson"<notifications@github.com>
To: "grafana/grafana"<grafana@noreply.github.com>;
Cc: "noasand"<noasand@naver.com>; "Mention"<mention@noreply.github.com>;
Sent: 2019-01-28 (월) 17:58:45
Subject: Re: [grafana/grafana] fix XSS vulnerabilities in dashboard links (#11813)
 
@noasand for 1) will be fixed in next major release by #4117. 2) and 3) Please open a new issue. Thanks
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.