Singlestat value: vertical alignment fix
grafana/grafana pull request #12004
Opened 2018-05-20 18:33 UTC by mammuthus

There is a problem with vertical alignment of Singlestat value - it's a bit lower then it has to be.
This hack fix it.

Before:
![before](https://user-images.githubusercontent.com/1700286/40282241-07b734b0-5c75-11e8-8dbb-209b1ea377d8.jpg)

After:
![after](https://user-images.githubusercontent.com/1700286/40282245-10ca389a-5c75-11e8-81a6-f0f2d74cff48.jpg)

2018-05-20 18:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=12004) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=12004) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=12004) it.</sub>

2018-05-24 15:20 UTC, Ijin08 requested changes
Hey!
This looks good and visually it will be an improvement.
But I don't think the old code for centering is necessary to keep.
If you could look into that it would be great.

2018-05-24 16:44 UTC, mammuthus commented
Fix was made - the old code removed. I will appreciate if you check it.

2018-05-25 07:20 UTC, Ijin08 approved these changes

2018-05-28 12:38 UTC, torkelo commented
This seems to improve the positioning for super small panels that are only 2 grid units high, with higher panels I think the 10px bottom padding makes the positioning of the text feel off center.

2018-05-29 12:11 UTC, merged

2018-06-01 14:36 UTC, towolf commented
@torkelo this made many of our Singlestat panels not fit the text anymore, which fit before:
![image](https://user-images.githubusercontent.com/345210/40846369-b3be2960-65b9-11e8-897b-b79d378c074a.png)

That means, where 70% fit fine before, now I have to reduce size to 40% to make it fit:
![image](https://user-images.githubusercontent.com/345210/40846417-daa3ea9c-65b9-11e8-957e-97951f21b3d6.png)

2018-06-04 13:47 UTC, torkelo commented
@towolf thanks for the heads up, I reverted this change, https://github.com/grafana/grafana/commit/829af9425f4e1f6d0d3cea9f8d5fa78e46bc4a2c