save-modal save button
grafana/grafana pull request #12047
Opened 2018-05-24 07:30 UTC by Ijin08

added two spans to button to switch between, 
added class to succes-btn, 
created function that switch span and add class

fixes #11963

2018-05-24 13:58 UTC, torkelo requested changes

2018-05-24 13:58 UTC, torkelo commented on public/app/features/dashboard/save_modal.ts
> +    let saveButton = document.querySelector('#saveButton');
use ng-class in html template , example ng-class="{'btn--processing': ctrl.isSaving}" 

And the class needs to be more generic so it works for all types & themes, not sure if that is possible or just ticky. Also need a way to cancel isSaving state when errors happen. I wonder how we can do that without adding ugly try catch, and how we can make this more more reusable in other places.

2018-06-07 10:19 UTC, marefr requested changes
I can still click on *Saving...* and that triggers multiple calls for saving a dashboard.

Regarding Torkel's comment on error handling it looks like it's automatically solved since the save modal are closed on network error which is fine I guess.

2018-06-07 15:08 UTC, marefr commented on public/app/features/dashboard/save_modal.ts
> +        ng-disabled="ctrl.saveForm.$invalid"
Did you try `ng-disabled="ctrl.saveForm.$invalid || ctrl.isSaving"`? Haven't tried it, but if that works I think you can remove the extra spans below and some logic in the controller.

2018-06-07 15:09 UTC, marefr commented on public/app/features/dashboard/save_modal.ts
> +    myBtn.disabled = true;
This feels ugly - possible to use my suggested solution instead?

2018-06-12 09:53 UTC, marefr approved these changes
Great :+1:

2018-06-12 09:54 UTC, merged