alerting: show alerts for user with Viewer role
grafana/grafana pull request #12129
Opened 2018-06-01 10:49 UTC by alexanderzobnin

This PR fixes #11167. Also, a little fix for the test, it was wrong - without _OrgId_ specified for user _HandleAlertsQuery()_ always returns an emty set of alerts (even for Editor role), because dashboard's OrgId=1.

2018-06-01 13:08 UTC, marefr commented
@alexanderzobnin please remove the changelog update - we always update changelog after merge

Please rebase/squash to one commit as well

2018-06-01 13:11 UTC, alexanderzobnin commented
Ok, sure.

2018-06-04 08:45 UTC, marefr requested changes
Need to change this to viewer: https://github.com/grafana/grafana/blob/master/pkg/api/alerting.go#L82

Maybe also provide permission as property in GetAlertsQuery like search.Query does it to remove some logic for sqlstore layer.

Besides this it looks good.

2018-06-04 09:36 UTC, alexanderzobnin commented
@marefr not sure about Permission field, I need time to figure out how it works with search.

2018-06-04 09:54 UTC, marefr approved these changes

2018-06-04 09:54 UTC, merged

2020-08-25 15:35 UTC, marefr commented
@Filipe777 this is for the alert list panel used in dashboards.

2020-11-09 19:23 UTC, carlossmartini commented
In version 7.2.1 I'm having the same issue where I can't see the alert icon on the side bar when a user has viewer role.  Any changes on this over the past 2 years?