fixed so panel title doesn't wrap and
grafana/grafana pull request #12142
Opened 2018-06-04 09:46 UTC by Ijin08

carrot doesn't appear outside panel when panel is thin

fixes 11074

![longtitle](https://user-images.githubusercontent.com/23470681/40910648-f80a9600-67ec-11e8-8052-6e34ba95610d.png)

2018-06-04 16:28 UTC, marefr requested changes
The panel error message icon is positioned of, see screenshot below:

![image](https://user-images.githubusercontent.com/1668778/40929429-f2c8e290-6824-11e8-9088-cb2a96942a0c.png)

Seems like alerting icons positioning is off now. Verified in chrome, firefox and IE11. See screenshots below.

**Before:**
![image](https://user-images.githubusercontent.com/1668778/40929333-b849f3de-6824-11e8-84ac-b75018e2c985.png)

**After:**
![image](https://user-images.githubusercontent.com/1668778/40929337-bc43d338-6824-11e8-92de-d94803e7c00e.png)

Besides this it looks good. Also verified that phantomjs rendering still works.

2018-06-05 07:27 UTC, Ijin08 commented
Latest push:
<img width="689" alt="skarmavbild 2018-06-05 kl 09 24 18" src="https://user-images.githubusercontent.com/23470681/40961356-9fc1d588-68a2-11e8-95ce-ec2b89fc3861.png">

2018-06-07 09:40 UTC, marefr requested changes
Have a look at he comment and let me know what you think/push those changes and then we're good to merge this :+1:

2018-06-07 09:40 UTC, marefr commented on public/sass/pages/_dashboard.scss
> +  max-width: calc(100% - 28px);
Changing to 48px or similar pushes the down arrow icon more to the left and adds some space to the right - I think it looks better - what do you think?

2018-06-07 11:56 UTC, Ijin08 commented
@marefr decreased max-width to -38. I think it is enough, what do you think?
<img width="293" alt="skarmavbild 2018-06-07 kl 13 55 26" src="https://user-images.githubusercontent.com/23470681/41098118-983d90d6-6a5a-11e8-98fc-b82a0c764252.png">

2018-06-07 12:05 UTC, marefr commented
What, my updated comment disappeared??? I intended to also suggest to add a special rule if alert rule is defined to make more space for the arrow down icon:

```scss
.panel-title-text {
  ..
  max-width: calc(100% - 38px);
  ...

  .panel-has-alert & {
    max-width: calc(100% - 58px);
  }
  ...
}
```

2018-06-07 14:16 UTC, marefr approved these changes
Awesome :heart:

2018-06-07 14:20 UTC, merged