enhance error message if phantomjs executable is not found
grafana/grafana pull request #12198
Opened 2018-06-07 13:24 UTC by marefr

Fixes #11868 

if arm build, explain that phantomjs is not included by default in arm builds. If not explain that phantom js isn't installed correctly.

This was the best I could come up with using the existing error page. Please note that the error details section not are displayed if the environment setting of a build = production.

**If arm architecture:**
![image](https://user-images.githubusercontent.com/1668778/41101993-02e5cfa6-6a66-11e8-8e9f-1dbc15a85068.png)

log:
```
INFO[06-07|15:07:39] Rendering                                logger=rendering path="d-solo/RFCYwTSmz/testdata-graph-panel-last-1h?orgId=1&panelId=4&from=1528372675566&to=1528376275566&width
=1000&height=500&tz=Europe%2FStockholm"                                                                                                                                                       
EROR[06-07|15:07:39] executable not found                     logger=rendering executable=/home/marcus/go/src/github.com/grafana/grafana/tools/phantomjs/phantomjs                            
EROR[06-07|15:07:39] Rendering failed - PhantomJS isn't included in arm builds per default logger=context userId=1 orgId=1 uname=admin error="PhantomJS not installed/setup correctly"        
EROR[06-07|15:07:39] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/RFCYwTSmz/testdata-graph-panel-last-1h status=500 remote_addr=[::1] time_ms=4 size=1937 referer=  
```

**If not arm architecture:**
![image](https://user-images.githubusercontent.com/1668778/41101994-0674f2fa-6a66-11e8-8532-21721badd69c.png)

log:
```
INFO[06-07|15:10:08] Rendering                                logger=rendering path="d-solo/RFCYwTSmz/testdata-graph-panel-last-1h?orgId=1&panelId=4&from=1528372675566&to=1528376275566&width
=1000&height=500&tz=Europe%2FStockholm"                                                                                                                                                       
EROR[06-07|15:10:08] executable not found                     logger=rendering executable=/home/marcus/go/src/github.com/grafana/grafana/tools/phantomjs/phantomjs                            
EROR[06-07|15:10:08] Rendering failed - PhantomJS isn't installed correctly logger=context userId=1 orgId=1 uname=admin error="PhantomJS executable not found"                                
EROR[06-07|15:10:08] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/RFCYwTSmz/testdata-graph-panel-last-1h status=500 remote_addr=[::1] time_ms=3 size=1913 referer=                                  
```

2018-06-07 16:04 UTC, xlson requested changes
I was hoping for someone a bit less angry (a yellow warning or something like that). But this is probably fine.

2018-06-07 16:04 UTC, xlson commented on pkg/api/render.go
> +		if strings.HasPrefix(runtime.GOARCH, "armv") {
I think you need to check against `arm`, not `armv`.

See: https://golang.org/doc/install/source#environment

2018-06-07 16:04 UTC, xlson commented on pkg/api/render.go
> +			c.Handle(500, "Rendering failed - PhantomJS isn't included in arm builds per default", err)
I'd change "included in arm builds" to "included in arm build". Technically we have several arm builds, but for the end user running into this problem only one of them is relevant.

2018-06-07 18:09 UTC, torkelo commented
I think it would be ideal if the error message was actually inside an image. The thinking is that the render service would always return an image, so if used in alerting you would get an image that tells you that something went wrong in rendering the image, instead of having to search through logs. But maybe not a good idea, or tricky to do generically (so the error message can be different), maybe 1-3 pre generated error images would also work. 

thoughts?

2018-06-08 08:51 UTC, xlson commented
I like that idea. We would probably have to use pre-generated images but that doesn't sound like a bad idea to me.

2018-06-12 11:33 UTC, marefr commented
I think I like that idea, but could be tricky. I agree with Torkel that it would be hard to include error message in image why you probably still need to dig into the logs to find the actual problem. 

What would these 1-3 pre generated images be for?
* Rendering not **installed/setup?**
* Rendering timeout?
* Rendering failure?

The easiest thing would be to have only one general pre generated image saying that rendering failed :)

2018-06-15 11:22 UTC, torkelo commented
I think 3 images at a minimum. 

* Rendering not installed/setup
* Rendering timeout
* Rendering failed

2018-06-25 08:30 UTC, bergquist commented
I think this is good enough for 5.2

We can create a new issue for improving this once this has been released.

2018-06-25 14:07 UTC, marefr commented
Decided that this is enough for 5.2

2018-06-25 14:27 UTC, merged