(prometheus) get label name/value from series API
grafana/grafana pull request #12251
Opened 2018-06-13 05:09 UTC by mtanda

instant query doesn't return all label name/value of dashboard time range.
So, change to use series API.

https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers

2018-07-26 09:55 UTC, davkal requested changes
Very useful addition! 

Small implementation issue: We're trying to be less reliant on angular services, and hence want to prevent their leakage into plugin submodules. Could you add a function to the datasource instead that returns `{start, end}`?

2018-07-26 16:57 UTC, mtanda commented
Okay, I change the code :-)

2018-07-26 19:32 UTC, davkal reviewed
Almost ready:

- Please use `const { start, end } = this.getTimeRange();` within `datasource.ts` as well now when `start` and `end` are requested. Then this can be merged.
- Please add types to all functions you added/modified.

2018-07-26 19:32 UTC, davkal commented on public/app/plugins/datasource/prometheus/completer.ts
> +    let range = this.datasource.getTimeRange();
Should be `const { start, end } = this.datasource.getTimeRange();`
Also, `url` below should be `const`.

2018-07-27 02:47 UTC, mtanda commented
@davkal 
> Please add types to all functions you added/modified.
Should I add types like `session` or `pos` which provided by Ace editor?
I think set `any` type is meaningless, do you want to set more strict type?

2018-08-27 15:13 UTC, davkal commented
The types are good as is now. Thank you. Could please rebase? Then we can merge.

2018-08-27 16:34 UTC, mtanda commented
rebased.

2018-09-13 09:47 UTC, davkal approved these changes
LGTM. Thanks for your contribution!

2018-09-13 09:48 UTC, merged