Added Litre/min and milliLitre/min in Volume
grafana/grafana pull request #12282
Opened 2018-06-14 14:45 UTC by flopp999

2018-06-14 15:11 UTC, marefr requested changes

2018-06-14 15:11 UTC, marefr commented on public/app/core/utils/kbn.ts
> +        { text: 'Litre/min (l/min)', value: 'flowlpm' },
Litre/min should be after Litre/hour

2018-06-14 15:11 UTC, marefr commented on public/app/core/utils/kbn.ts
> +
You have a trailing whitespace here that made the frontend test fail. Please remove

2018-06-14 16:09 UTC, flopp999 commented
Changed made and tests are OK

2018-06-15 08:53 UTC, marefr approved these changes

2018-06-15 08:54 UTC, merged

2018-06-15 08:55 UTC, marefr commented
Thank you for contributing to Grafana!