Add new sequential color scales
grafana/grafana pull request #12405
Opened 2018-06-26 05:52 UTC by smithamax

`d3-scale-chromatic` has been updated to include some [new perceptually-uniform color schemes](https://github.com/d3/d3-scale-chromatic#sequential-multi-hue) and I'd like to use them 😁

First time contributing here so let me know if you need any more details/test etc, would be happy to do so.

2018-06-26 05:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=12405) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=12405) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=12405) it.</sub>

2018-06-27 06:36 UTC, smithamax commented on public/app/plugins/panel/heatmap/color_scale.ts
> +    (colorScheme.invert === 'light' && lightTheme);
I guess this could also be
```
colorScheme.invert === (lightTheme ? 'light' : 'dark')
```
Not sure that it's any clearer though.

2018-07-09 08:15 UTC, alexanderzobnin requested changes
Looks good, except my 2 notes. Please, let me know what do you think about it.

2018-07-10 08:04 UTC, smithamax commented on public/app/plugins/panel/heatmap/heatmap_ctrl.ts
> +  { name: 'Cubehelix', value: 'interpolateCubehelixDefault', invert: 'light' },
I was just keeping them in the same order as documented in the original lib (https://github.com/d3/d3-scale-chromatic#sequential-multi-hue), that seemed to be the existing approach. Happy to move it to the end though.

2018-07-10 08:16 UTC, alexanderzobnin commented on public/app/plugins/panel/heatmap/heatmap_ctrl.ts
> +  { name: 'Cubehelix', value: 'interpolateCubehelixDefault', invert: 'light' },
Got it, I think you're right, let's keep an original order.

2018-07-10 08:19 UTC, alexanderzobnin approved these changes

2018-07-10 09:17 UTC, merged