Karma to Jest: 3 test files
grafana/grafana pull request #12414
Opened 2018-06-26 14:13 UTC by dehrax

Ref #12224

2018-06-26 15:16 UTC, dehrax commented
Is this a case where the warning should be ignored? The variable is only used for initiating the class. The class only modifies `$scope`, which is being tested.

2018-06-26 16:00 UTC, marefr commented on public/app/plugins/panel/graph/specs/series_override_ctrl.jest.ts
> +    seriesOverridesCtrl = new SeriesOverridesCtrl($scope, {}, popoverSrv);
Guess you can just do a `new SeriesOverridesCtrl($scope, {}, popoverSrv);` here and skip the assignment.

2018-06-28 10:07 UTC, torkelo requested changes

2018-06-28 10:07 UTC, torkelo commented on public/app/plugins/panel/graph/series_overrides_ctrl.ts
>    /** @ngInject */
the   /** @ngInject */ comment needs to be above the function (or constructor) to have any effect, now it's below, so this controller will not work in an minified & optimized build

2018-06-28 11:43 UTC, merged