table: add grouping to matrix transformation
grafana/grafana pull request #12522
Opened 2018-07-06 14:06 UTC by asieraguado

Adds a new transformation that sets one group property as columns, and another as rows. (#7169)

Changes added to the closed pull request #8492:
- Allows selecting the column property; the other will be set as rows.
- The column set can be selected from the query or a template variable.

Current limitations:
- Only works with InfluxDB data source, assuming queries like: `select sum(value) from measurement where $time group by A, B`. `A` and `B` are the column/row sets.

2018-07-06 14:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=12522) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=12522) before we can accept your contribution.<br/><hr/>**Asier Aguado** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=12522) it.</sub>

2018-07-06 14:47 UTC, marefr commented
For considering reviewing/accepting this it needs to work generically for Grafana core datasources.

2018-07-06 14:48 UTC, marefr requested changes
For considering reviewing/accepting this it needs to work generically for Grafana core datasources. Please let us know if you'll need help/support fixing this.

2018-07-06 15:18 UTC, asieraguado commented
Unfortunately we don't have the resources to develop and test for all the Grafana core datasources, but we would be happy to contribute. Any help from the community would be very appreciated.

2018-08-03 08:55 UTC, closed without merging

2018-11-26 09:35 UTC, D031121 commented
Hi,

is there a chance to see this table transform to column and row feature in the next Grafana versions?
InfluxDB as datasource would be sufficient for us.

Many Thanks

2018-11-26 09:53 UTC, marefr commented
@D031121 currently this is not prioritized by core Grafana team. But contributions are always welcome. As noted in the comments this PR only targeted influxdb why we couldn't accept it. Please upvote #7169 if you want this feature.

2020-06-04 08:00 UTC, diegoscarabelli commented
I have been looking around for hours before finding this PR (closed). This feature would be very useful for whoever is trying to replicate matplotlib heatmaps which change over time. It believe it is worth supporting.