Use metric column as prefix when returning multiple value columns
grafana/grafana pull request #12679
Opened 2018-07-21 09:27 UTC by svenklemm

Ref #12727

Currently if you return a metric column and multiple value columns all value columns will be munged into the same series.
This PR changes this behaviour so that the metric column is used as prefix for the series name when multiple value columns are returned.

2018-07-24 08:56 UTC, marefr requested changes
Think MySql had this functionality, but we removed it when we refactored all the sql datasources towards being very similar. Would it be possible for you to fix this for MySQL and MSSQL as well?

Another option would be to introduce a new alias field in query editor, but probably more work? However that will allow the end user to format the alias they see fit.

A test for this new functionality would be nice. And https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/partials/query.editor.html probably needs some updates as well.

2018-07-24 16:39 UTC, torkelo commented
I wonder how big a breaking change this is

2018-07-24 17:00 UTC, marefr commented
Shouldn't be that big. Those affected of this change will probable get a better experience. 

Take the example query in test:

```
SELECT 
  $__timeEpoch(time), 
  measurement as metric, 
  "valueOne", 
  "valueTwo" 
FROM metric_values ORDER BY 1
```

Without this fix it returns 2 series named Metric A and Metric B with no possibility to know if a point comes from valueOne or valueTwo columns. With the fix it returns 4 series where you can see the difference. I would guess people stumbled upon this may have written two queries or something as a workaround, but just guessing here.

2018-07-24 17:30 UTC, svenklemm commented
@marefr I think an alias like prometheus wouldnt be such a good fit cause in prometheus you always have all the labels while in sql you only get what you ask for so the alias would be quite limited, but you can compose the metric column from multiple fields. I've added tests and updated the editor documentation.

2018-07-24 17:41 UTC, svenklemm commented
If people really want the old behaviour they can still get it by aliasing the columns to the same name like so:
```
SELECT 
  $__timeEpoch(time), 
  measurement as metric, 
  "valueOne" AS mix, 
  "valueTwo" AS mix 
FROM metric_values ORDER BY 1
```
But i think people would expect data coming from different columns be returned in separate series.

2018-07-26 11:46 UTC, marefr approved these changes

2018-07-27 16:16 UTC, svenklemm commented
@marefr i adjusted the PR and added tests and docs for mysql and mssql

2018-07-30 11:06 UTC, marefr requested changes
Looks good overall. Some minor documentation changes needed.

2018-07-30 11:06 UTC, marefr commented on docs/sources/features/datasources/mssql.md
> +If you set `Format as` to `Time series`, for use in Graph panel for example, then the query must must have a column named `time` that returns either a sql datetime or any numeric datatype representin
> If you omit the `metric` column, **tha** name 

tha should be the. 

> If you return multiple value columns and a column named `metric` then this column is used as prefix for the series name."

Please add a version note like (only available in Grafana v5.3+).

2018-07-30 11:06 UTC, marefr commented on docs/sources/features/datasources/mysql.md
> +You may return a column named `metric` that is used as metric name for the value column. If you return multiple value columns and a column named `metric` then this column is used as prefix for the se
Please add a version note like (only available in Grafana v5.3+).

2018-07-30 11:06 UTC, marefr commented on docs/sources/features/datasources/postgres.md
> +You may return a column named `metric` that is used as metric name for the value column. If you return multiple value columns and a column named `metric` then this column is used as prefix for the se
Please add a version note like (only available in Grafana v5.3+).

2018-07-30 11:56 UTC, marefr commented
Pushed some fixes. One somewhat "critical" after sql refactor which didn't allow to skip aliasing the metric column.

2018-07-30 12:42 UTC, svenklemm commented
Added version notes to the docs and fixed the typo.

2018-07-30 12:49 UTC, marefr approved these changes

2018-07-30 12:50 UTC, merged

2018-07-30 12:50 UTC, marefr commented
Thank you for contributing to Grafana!