[wip] Improve iOS and Windows 10 experience
grafana/grafana pull request #12769
Opened 2018-07-31 06:12 UTC by andig

Implements https://github.com/grafana/grafana/issues/12752

2018-07-31 06:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=12769) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=12769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=12769) it.</sub>

2018-08-01 10:18 UTC, marefr requested changes
The public/img/favicon.ico don't seem to be used.

What does a microsoft app tile look like using #2b5797 (blue)? Maybe it should be black or dark gray?

2018-08-01 14:28 UTC, andig commented
Here's the Win10 screenshot:

<img width="134" alt="unbenannt" src="https://user-images.githubusercontent.com/184815/43527852-d6a887f4-95a7-11e8-8f9d-14246bc68188.png">

@marefr please let me know if and which color you wish if not blue.

2018-08-02 10:37 UTC, torkelo commented
Thanks for contributing and making Grafana better!

2018-08-02 10:37 UTC, merged