Fixing bug in url query reader and added test cases
grafana/grafana pull request #12815
Opened 2018-08-05 20:57 UTC by tariq1890

Fixing a bug where url query strings are parsed incorrectly.

url.ParseQuery expects a query string to be passed rather than the entire URL. In the current code, one would never be able to retrieve the actual value of the first query key of the URL. This PR will fix that.

Also added a few test cases

2018-08-05 20:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=12815) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=12815) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=12815) it.</sub>

2018-08-06 08:11 UTC, marefr commented
Thanks. Would be good if you could open an issue to track this where you describe the bug, what was expected and what happened instead.

2018-08-06 19:17 UTC, tariq1890 commented
@marefr  I found this bug while trying to write test cases for that method. I have changed the code so that it passes the test cases that I have written. (Those tests will fail with the current code). 

Please let me know if my test cases are valid. Also, If you'd like me to reproduce this, I can work towards setting it up locally and running grafana to reproduce it.

2018-08-07 07:44 UTC, tariq1890 commented
So I have pointed out an issue in the usage of the url.ParseQuery (https://github.com/grafana/grafana/pull/12815/files#diff-68303a2aea932f2982a2fae85d4bf897R13)where you are passing an entire URL string when one is actually supposed to pass in only the query string. The godoc of url.ParseQuery mentions the very same thing.

Like I said before, I can definitely work towards reproducing it. I feel the unit tests here have helped uncover this potential bug. I've added enough test cases to cover and demonstrate that the change is safe.

2018-08-07 08:34 UTC, marefr commented
My point being the only code using that method is https://github.com/grafana/grafana/blob/master/pkg/api/render.go#L17 and we haven't received any bug reports for that. But you provide a good pointer and we should probably fix that.

2018-08-07 08:36 UTC, marefr requested changes
Some minor changes needed.

Validation tests are needed and appreciated

2018-08-07 08:36 UTC, marefr commented on pkg/util/url_test.go
> +func TestNewUrlQueryReader(t *testing.T) {
You're not using goconvey - please fix and/or merge with url test above with multiple    
subsequent Convey statements.

2018-08-08 01:53 UTC, tariq1890 commented
Done. Thanks for the review. This bug would not have surfaced as the default parameter is always there to be returned as backup. I reckon this issue would have been noticed only if a person is looking for a particular width of the PNG and that width wasn't used during render.

2018-08-08 07:18 UTC, marefr approved these changes

2018-08-08 07:18 UTC, merged