Karma to Jest: graph (refactor)
grafana/grafana pull request #12860
Opened 2018-08-09 14:02 UTC by dehrax

Ref #12224 
I did some refactoring to make it more testable, feedback is appreciated! Extracted link function as a class, ran all event stuff in the constructor, made variables into class properties and changed the functions into class methods.

#12809 can probably be merged after this one.

2018-08-10 09:26 UTC, daniellee requested changes
Looks good - just two small improvements that would make it even better.

2018-08-10 09:26 UTC, daniellee commented on public/app/plugins/panel/graph/graph.ts
> +    // this.data;
Should these commented out lines be removed?

2018-08-10 09:26 UTC, daniellee commented on public/app/plugins/panel/graph/graph.ts
> +    this.ctrl.events.on('panel-teardown', () => {
The event handler functions should be moved out of the constructor and extracted into methods. An example is the heatmap controller: https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/heatmap/heatmap_ctrl.ts#L128-L133

2018-08-10 09:26 UTC, daniellee commented on public/app/plugins/panel/graph/specs/graph.jest.ts
> +      ...MetricsPanelCtrl.prototype,
Elegant. I like it!

2018-08-10 13:59 UTC, dehrax commented
Changes fixed!

2018-08-13 12:18 UTC, torkelo requested changes
looks good, just the naming of the class Link that feels a bit too generic.

2018-08-13 12:18 UTC, torkelo commented on public/app/plugins/panel/graph/graph.ts
> +class Link {
Link name feels a bit undescriptive here. Maybe GraphElement?

2018-08-13 14:08 UTC, merged