Security: New config option to disable the disclosure of version info…
grafana/grafana pull request #12950
Opened 2018-08-16 19:10 UTC by frots

New config option to disable the disclosure of version information to users that have not logged in

fixes #12925

2018-09-04 08:53 UTC, bergquist requested changes
Thank you for contributing to Grafana. 

I'm rejecting this until we know how we want to solve this problem.

2018-09-08 22:04 UTC, frots commented
Hi @bergquist, that sounds sensible and is actually what the commit does. You'd only need to get rid of the configuration option, but the rest is already there.

2018-09-18 09:51 UTC, bergquist commented on pkg/api/dtos/index.go
> +	IsSignedIn              bool
This property is never assigned any value. 
You can use `User.IsSignedIn` instead.

2018-09-21 12:20 UTC, torkelo commented
Anyone who wants to view version info can just request api/health or view it in the grafanaBootData.

2018-12-19 13:25 UTC, closed without merging

2019-09-13 16:33 UTC, pgporada commented
I believe this PR should be re-opened.

2019-09-13 19:04 UTC, jprenken commented
+1