Repeating panels - Max per row
grafana/grafana pull request #12991
Opened 2018-08-21 08:49 UTC by pgiraud

Currently when using the "Repeating panels" feature, a user can choose the "min width" for the repeated panels. It can be any value from 1 to 24.

From a user point of view, it's (in my opinion) not easy to understand what "min width" means. It could make sense if at least they knew that the view is splitted into 24 columns. Which they don't. And we don't want them to know that.
I think it's easier for them to figure out what's the max number of panels they want to see on each row.

![capture du 2018-08-21 10-31-47](https://user-images.githubusercontent.com/319774/44390396-792e7800-a52d-11e8-8c23-7d6dfcfa4ff0.png)

Also with the "min width" it's possible to set nonsensical values. For example, a user may want to set "20". This means that the repeated panels will be take 20 columns and be displayed on different rows. 4 columns will be empty. Is this a desired behavior?

![capture du 2018-08-21 10-26-07](https://user-images.githubusercontent.com/319774/44390029-a62e5b00-a52c-11e8-9bf0-4759f9c4aa81.png)

With the proposed changes, the panels will always automatically fill the row (as already explained in the documentation). https://github.com/grafana/grafana/blame/48364f0111cfdaacfd4a05eaf4da98ba94a00251/docs/sources/reference/templating.md#L290

In this PR, I also made sure that the values for "Max per row" are computed from the `GRID_COLUMN_COUNT` constant.

My last concern is that it breaks compatibility because the `minSpan` property of the `PanelModel` is removed. Do we need to make sure that dashboards configuration from previous version continue to work. Or is a deprecation / update notice on the release notes enough?

If this PR is accepted, one may ask if the `vertical` direction is still relevant. Indeed, the only thing to do is to set `max per row` to *1* and panels will be arranged in a single column. I'd be happy to continue working on this and remove the `direction` option if others share my point of view.

2018-08-21 11:06 UTC, torkelo commented
I agree this is more intuitive. We would have to add dashboard schema migrations for this change as this would otherwise break thousands of dashboards. 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboard_migration.ts

2018-08-21 11:06 UTC, torkelo requested changes
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashboard_migration.ts

2018-08-21 15:02 UTC, pgiraud commented
Dashboard schema migration added.
I took the decision to migrate `minSpan` to the most relevant `maxPerRow` value. For example, if the user has chosen *10* for minSpan, this should be transformed to *2.4* but we use *2* instead to completely fill the row.

Please confirm that I changed the `schemaVersion` in the correct locations and that I didn't miss any.

2018-09-17 14:42 UTC, pgiraud commented
I just rebased the branch to match master updates. @torkelo please review.

2019-01-08 09:49 UTC, pgiraud commented
Do you think it's worth updating this PR (ie. resolve the conflicts)?

2019-01-08 11:48 UTC, torkelo commented
yes, I am sorry, this should have been merged earlier, I do like this change.

2019-01-09 10:15 UTC, pgiraud commented
@torkelo Conflicts resolved. Please give it a look.

2019-01-09 10:35 UTC, pgiraud commented
I just added a hint to help the user understand why it doesn't apply automatically.

2019-01-11 08:31 UTC, merged

2019-01-11 08:32 UTC, torkelo commented
Big thanks for this contribution, sorry that we so slow in providing feedback & merging.

2019-01-11 09:55 UTC, pgiraud commented
Thanks a lot for your confidence.

2021-05-03 01:18 UTC, kedorlaomer commented
Maybe this is just me (version 7.5.5 as tagged by docker), but the web GUI doesn't show me any other options besides (a) which variable to repeat (b) repeat direction. Even changing the `"w"` and `"h"` in the corresponding entries of `"gridPos"` doesn't help. It seems I have now way of influencing the layout of repeated panels except for having one (direction “vertical”) or four (“horizontal”) panels per row. (Should I rather open a new bug for this?)