Reopen log files after receiving a SIGHUP signal
grafana/grafana pull request #13112
Opened 2018-08-31 22:46 UTC by filewalkwithme

Implements a system signals listener in log.FileLogWriter.

After receiving a SIGHUP signal from the system, the listener will close the current log file and then open it again.

The listener will finishes after receiving a SIGINT, SIGKILL or SIGTERM signal.

Closes grafana/grafana#2497

* Link the PR to an issue for new features
* Rebase your PR if it gets out of sync with master

**REMOVE THE TEXT ABOVE BEFORE CREATING THE PULL REQUEST**

2018-09-03 09:32 UTC, torkelo requested changes
Is there a way to move the signal handling to the main file where our other signaling is handled? 

https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-server/main.go#L102

2018-09-04 00:10 UTC, filewalkwithme commented
@torkelo Sure. I did move the SIGHUP handling to the main file and also created a package level `Reload` method on `log` package, which will force all currently opened log files to be closed and opened again.

2018-09-04 08:30 UTC, torkelo approved these changes

2018-09-04 08:31 UTC, merged

2018-09-04 08:55 UTC, bergquist commented
@filewalkwithme great work! :) Thank you for contributing!