Add socket support for mysql data source
grafana/grafana pull request #13705
Opened 2018-10-17 10:09 UTC by Yukinoshita-Yukino

Currently mysql data source only supports tcp protocol as mentioned in #12342.
Add support for socket protocol.

2018-10-17 17:38 UTC, marefr requested changes
Thanks! 

Looks really good. Just have a minor change request, see comment.

2018-10-17 17:38 UTC, marefr commented on pkg/tsdb/mysql/mysql.go
> +	var protocol string
Please simplify this by initializing protocol to `tcp` and skip the else clause:

```go
protocol := "tcp"
if strings.HasPrefix(datasource.Url, "/") {
	protocol = "unix"
}
```

2018-10-17 18:08 UTC, Yukinoshita-Yukino commented
Sure, done that.

2018-10-18 07:45 UTC, marefr approved these changes
Excellent :+1:

2018-10-18 07:45 UTC, merged

2018-10-18 07:46 UTC, marefr commented
Thank you for contributing to Grafana!