Preserve suffix text when applying function suggestion
grafana/grafana pull request #13954
Opened 2018-11-03 23:47 UTC by miqh

Hello,

This pull request attempts to address #13885.

Exactly how a chosen suggestion applies is a somewhat contentious area depending on context.

Sometimes, its intuitive to replace the entire contents of the current context with the suggestion picked. A common case is typing keywords that are the subsequence contained inside a suggestion.

```
tr| -> pick "metric" -> metric|
me|tr -> pick "metric" -> metric|
```

However, for another type of suggestion like a "function", doing the same isn't particularly desirable.

```
to|metric -> pick "topk" -> topk(|) 
```

So, one workaround here is to make any "function"-like suggestion preserve any suffix text.

```
to|metric -> pick "topk" -> topk(|)metric
```

CC: @davkal

2018-11-05 11:29 UTC, davkal requested changes
While I like the fix, I think the behavior is still not right. Consider
```
to|metric -> pick "topk" -> topk(|)metric
```
Afterwards I need to fix the parens manually, which is a couple of keystrokes. If accepting the function does not complete the parens and I add them manually, they are correctly placed around the next term. This is more desirable IMO. In light of the alternate aggregation syntax (`sum by...`) we might as well not complete the parens when accepting functions for now.

2018-11-06 13:17 UTC, miqh commented
@davkal, yep, agreed—that UX would interrupt flow. :slightly_smiling_face:

What's your preference here for how to tackle omitting braces from function-like suggestions?

* Manually change every single `insertText` entry in `promql.ts`
* Have the `applyTypeahead` function strip them out when the need arises

2018-11-06 14:34 UTC, davkal commented
> Manually change every single insertText entry in promql.ts

I'd "manually" change it in `promql.ts`.

2018-11-09 13:56 UTC, davkal approved these changes

2018-11-09 13:56 UTC, merged

2018-11-09 13:57 UTC, davkal commented
This works great now. I'm a bit on the fence if the function label text should now include the parens to indicate that it's part of the function group, e.g., `sum()`, while only applying `sum`. But perhaps that's confusing.

Thank you @miqh 🎉