Read password from stdin when admin resets password
grafana/grafana pull request #14193
Opened 2018-11-26 13:14 UTC by praveensastry

Fixes #14076

2018-11-26 13:39 UTC, marefr commented
You've added Grafana as a dependency - 417 files changed?

2018-11-26 14:37 UTC, praveensastry commented
> You've added Grafana as a dependency - 417 files changed?

@marefr I updated vendor dependencies using this dep ensure -add golang.org/x/crypto/ssh/terminal and that has resulted in this. Could you please help me understand why this happened?

2018-11-26 14:52 UTC, praveensastry commented
@marefr I figured why this is happening, my forked repo is at $GOPATH/src/praveensastry/grafana and with this configuration when i update deps it's adding grafana as a dependency :(

2018-11-26 14:55 UTC, marefr commented
Cool

2018-11-26 15:35 UTC, marefr commented on pkg/cmd/grafana-cli/commands/reset_password_command.go
> +	bytePassword, err := terminal.ReadPassword(syscall.Stdin)
Will this be backward compatible to `grafana-cli admin reset-admin-password <password>`?

2018-12-03 14:28 UTC, marefr requested changes
It works as expected for the password prompt. However it doesn't work to pipe a password to the command like `echo "password" | ./bin/grafana-cli admin reset-admin-password`. Either fix pipe or introduce an option to provide password as an arg in case people have some kind of automation that requires it.

2018-12-19 09:49 UTC, bergquist commented
@praveensastry did you have a chance to work on this?

2019-02-06 13:58 UTC, marefr commented
@praveensastry Closing this due to lack of response. Just let us know if you would like to continue work on this and we'll reopen this PR. Thanks

2019-02-06 13:58 UTC, closed without merging