Fix elastic ng-inject (build issue)
grafana/grafana pull request #14195
Opened 2018-11-26 20:19 UTC by torkelo

fixes #14191

I do not understand how this has not been an issue in v5.1-5.3 as I cannot see any change in this file relating to ng inject since typescript conversion that happened v5.1

2018-11-27 08:41 UTC, marefr commented
This is really weird! Maybe related to #6367. Have you been able to reproduce  @torkelo? Otherwise I hope issue author come back with some more information since it would be very interesting to know the cause.

2018-11-27 16:21 UTC, marefr commented
After a very long and frustrating git bisect session I think I've tracked it down to the following change: https://github.com/grafana/grafana/commit/543c67a2974e1cf58c2cf210216c5f1a334a1992

Interesting to know if we have more similar problems after this change.

2018-11-27 17:10 UTC, marefr requested changes
Unfortunately this doesn't solve the problem. I have no idea why. Also confirmed that this is a problem in v5.4.0-beta1.

2018-11-27 20:03 UTC, torkelo commented
Dam, spent some time troubleshooting this and it turned down captial I in ngInject is important 😢

2018-11-28 08:18 UTC, marefr approved these changes

2018-11-28 08:19 UTC, marefr commented
So frustrating. Could swear that I did check the spelling. Good catch!

2018-11-28 08:20 UTC, merged

2018-11-28 12:34 UTC, ldktta commented
The latest version behaves perfectly :+1: 

Grafana v5.4.0-pre1 (3251153)

thank you