Prevent password reset when login form is disabled or either LDAP or Auth Proxy is enabled
grafana/grafana pull request #14232
Opened 2018-11-29 12:43 UTC by SilverFire

Hello, team! Thank you for a great tool!

I have discovered an unreliable behavior when either LDAP or Auth Proxy is enabled, or login form is disabled. In case user gets registered with SSO or LDAP, his/her account gets a random password so user is forces to authenticate with SSO next time. Before my pull request, it was possible to request password reset and obtain access to account bypassing SSO.

This pull request disabled password reset for all these cases.

2018-11-29 12:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=14232) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=14232) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=14232) it.</sub>

2018-11-29 12:58 UTC, marefr commented
Thanks. Please sign Contributor License Agreement (CLA). Please remove changelog update - we update that manually after a PR is merged. Seems like you have some go formatting issue in api/password.go - that's why the build are failing.

2018-11-29 15:17 UTC, SilverFire commented
Fixed & rebased

2018-11-30 10:38 UTC, marefr requested changes
I created an issue to track this enhancement. This is a good start but needs some further changes, see comments.

Also, would be nice to hide the "Forgot your password?" link on the login screen, code [here](https://github.com/grafana/grafana/blob/master/public/app/partials/login.html#L25).

2018-11-30 10:38 UTC, marefr commented on public/app/partials/reset_password.html
> +		<div ng-if="ldapEnabled || authProxyEnabled">
For these conditionals to work you'll need to populate those props in the controller scope [here](https://github.com/grafana/grafana/blob/master/public/app/core/controllers/reset_password_ctrl.ts#L8) similar to this [code](https://github.com/grafana/grafana/blob/master/public/app/core/controllers/login_ctrl.ts#L22).

2018-12-03 13:35 UTC, SilverFire commented
Yes, you're right. Thank you for helping with this pull-request.
I've fixed Angular side and hid "Forgot your password?" button from the login when not available.

2018-12-03 13:36 UTC, SilverFire commented
Rebased with master

2018-12-03 13:54 UTC, marefr approved these changes
Looks good :+1:

2018-12-03 14:02 UTC, merged

2018-12-03 14:02 UTC, marefr commented
Thank you for contributing to Grafana!

2024-05-15 08:34 UTC, alexmc1510 commented
Sorry for commenting a closed ticket but I am using Grafana V10.4 with LDAP auth enabled and the link "Forgot your password" is still there and the painful thing is that everytime a user click on it, becomes blocked and I need to modify directly the database to re enable. Could you clarify why the modification is not in V10.4?

2024-05-30 10:03 UTC, iegurbide commented
Experiencing the same.

Seems like the file public/app/partials/login.html where the change was merged is no longer present.