feat: #11067 prevent removing last grafana admin permissions
grafana/grafana pull request #14265
Opened 2018-12-01 23:32 UTC by danielbh

Solution for #11067 prevents removal of last grafana admin permissions.

Attached is a screenshot of what the new error message says in the UI.

<img width="1219" alt="screen shot 2018-12-01 at 6 14 32 pm" src="https://user-images.githubusercontent.com/6653234/49333948-bd063400-f596-11e8-92a2-ba959a64b8d5.png">

2018-12-01 23:50 UTC, danielbh commented
The postgres integration tests suprise me. Any thoughts on how to fix those? Thanks.

2018-12-03 11:17 UTC, danielbh commented
This PR is ready to be merged.

2018-12-03 15:03 UTC, marefr requested changes
This looks really good. Just a minor fix left, see comment.

2018-12-04 01:15 UTC, danielbh commented
ok good to go

2018-12-04 09:18 UTC, marefr approved these changes
Sweet

2018-12-04 09:20 UTC, merged

2018-12-04 09:20 UTC, marefr commented
Thank you for contributing to Grafana!