Nanosecond timestamp support postgresql
grafana/grafana pull request #14711
Opened 2019-01-02 22:04 UTC by ander26

Created a new macro for retrieving metrics with nanosecond timestamps. The name for the new metric is $__unixEpochFilterNano and it works in the same way as $__unixEpochFilter.

2019-01-02 22:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=14711) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=14711) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=14711) it.</sub>

2019-01-02 23:19 UTC, svenklemm commented
this should probably be named unixEpochNanoFilter and unixEpochNanoFrom and unixEpochNanoTo should be added as new macros as well, probably makes sense to add this to the other sql datasources too

2019-01-03 21:47 UTC, ander26 commented
Thanks @svenklemm for your response. I have made those changes and I have added them to mysql and msqql.

2019-01-04 09:39 UTC, torkelo requested changes
Would be good if these were added to the docs as well. 
https://github.com/grafana/grafana/blob/master/docs/sources/features/datasources/postgres.md

2019-01-21 09:30 UTC, ander26 commented
@torkelo You are right, documentation updated

2019-01-28 18:59 UTC, marefr approved these changes
Looks good!

2019-01-28 19:26 UTC, merged