Lazyload panels
grafana/grafana pull request #14731
Opened 2019-01-04 12:29 UTC by simPod

I tried to resurrect lazyloading.

References here https://github.com/grafana/grafana/pull/7452 https://github.com/grafana/grafana/issues/5216 https://github.com/grafana/grafana/issues/8365 https://github.com/grafana/grafana/issues/8500

What I was not very sure of is that now as `refresh()` is moved to PanelModel I had to pass DashboardModel as well. Appreciate your review!

2019-01-04 13:08 UTC, torkelo requested changes
this should not be done in panel_directive but in DashboardGrid, we need to add the CustomScrollbar to DashboardGrid, add an onScroll event to that component, and check visibility there and pass that along to panels via props. 

We do not need a dashboard setting for lazy load.

2019-01-04 13:19 UTC, simPod commented
> We do not need a dashboard setting for lazy load.

Lazy loading on small dashboard (lets consider eg. 6 graphs, each 400px high) would be really annoying. If toggle was removed there would be no way to differentiate between huge dashboards and smaller ones. I have dashboards with 1000 charts where I want to lazy load and also with 6 charts where it is not desired. IMO it's not edge case 🤔

2019-01-04 13:21 UTC, torkelo commented
but with 6 charts they would all be visible no? are the queries so slow that you want them to preload even when not visible ?

2019-01-04 13:42 UTC, simPod commented
No, they have 100% width, 400px height (6*400px + some margins between panels = 2500px window innerheight would be required).

It feels bad from user perspective. When dashboard is huge it doesn't feel that bad because in your head you somehow know it's just huge but for smaller dashboards it feels just wrong.

The queries with some backend work take let's say 1-2s each (request firing, bubbling through datasource to db and back). I can imagine even higher times, depends on infrastructure and data set size. It's hard to go below 1s per panel for not-hobby projects (graphing my home temperature etc.).

2019-01-05 00:09 UTC, ryantxu commented
I tried making lazy load feel ok, but it always felt kinda bad.  I ended up splitting out lazy loading (ie, not even making the panel body) from just the metrics query.  This seemed to work nicely

See:  https://github.com/grafana/grafana/pull/12531

2019-01-06 14:49 UTC, simPod commented
I tried to wrap it but `onScroll={() => {console.log('scrolling');}}` is not being triggered. Any ideas why?

2019-02-07 20:15 UTC, ryantxu commented
Closing this in favor of #15310

2019-02-07 20:15 UTC, closed without merging