Added PATCH verb end point for annotation op
grafana/grafana pull request #15197
Opened 2019-02-01 13:45 UTC by SamuelToh

Pull request for #12546 

I'm happy to send in another pull request for the documentation side of things once this is accepted.

2019-02-02 12:51 UTC, SamuelToh commented
Any chance someone can retrigger the CI? I'm not sure what it is failing on, not much information was provided by the failure.

Running `go test ./pkg/...` seem to work fine on my machine.
```

root@samuelt-ThinkPad-T460s:~/go/src/github.com/grafana/grafana# go test ./pkg/...
ok  	github.com/grafana/grafana/pkg/api	0.159s
?   	github.com/grafana/grafana/pkg/api/avatar	[no test files]
ok  	github.com/grafana/grafana/pkg/api/dtos	0.005s
?   	github.com/grafana/grafana/pkg/api/live	[no test files]
ok  	github.com/grafana/grafana/pkg/api/pluginproxy	0.197s
ok  	github.com/grafana/grafana/pkg/api/routing	0.014s
?   	github.com/grafana/grafana/pkg/api/static	[no test files]

```

2019-02-02 12:55 UTC, SamuelToh commented
Also just in case someone is reviewing this. The `PATCH` interface is almost the same as `UPDATE`.

You can basically `PATCH` almost any properties of an annotation, including timeEnd. Only thing you can't `patch` was going from a "isRegion" annotation to non region ones, as it involves `deleting` the 'right hand side' annotation. Not sure we should allow this or not, as `patching` generally means we only update the annotation, not involving deletion.

2019-02-04 10:01 UTC, marefr requested changes
This is looking pretty good :+1:. Only reviewed the code, not tested it out. 

Please fix according to comments.
Regarding documentation we would like that to be updated in this PR as well.

You also have a failing build due to go formatting issues. Please run `go fmt pkg/api/annotations*` to fix the problems.

2019-02-04 22:13 UTC, SamuelToh commented on pkg/api/annotations.go
> +	items, _ := repo.Find(&annotations.ItemQuery{AnnotationId: annotationID, OrgId: c.OrgId})
Thanks mate will update according tonight and send for review again

2019-02-05 02:00 UTC, SamuelToh commented on pkg/api/annotations.go
> +	items, _ := repo.Find(&annotations.ItemQuery{AnnotationId: annotationID, OrgId: c.OrgId})
@marefr All good now.

- Added doc describing new endpoint.
- Addressed review comment about the len 0 check.
- Rectified `fmt`'s formatting complain.

2019-02-05 17:58 UTC, marefr commented on pkg/api/annotations.go
> +	items, _ := repo.Find(&annotations.ItemQuery{AnnotationId: annotationID, OrgId: c.OrgId})
Seems you still have some go formatting issues, please run `go fmt pkg/api/dtos/annotations.go` to resolve those and then push the changes. Thanks

2019-02-05 18:28 UTC, marefr requested changes
Starting to look pretty solid. Would like some minor changes (see comments).

2019-02-05 20:43 UTC, SamuelToh commented on docs/sources/http_api/annotations.md
> +Updates one or more properties of an annotation that matches the specified id.
Fixed. Added a paragraph to describe what can be updated and what not.

2019-02-05 20:43 UTC, SamuelToh commented on docs/sources/http_api/annotations.md
> +**Example Request**:
fixed

2019-02-05 20:43 UTC, SamuelToh commented on pkg/api/annotations.go
> +		return Error(500, "Could not find annotation to update", err)
fixed.

2019-02-05 20:45 UTC, SamuelToh commented on pkg/api/annotations.go
> +	items, _ := repo.Find(&annotations.ItemQuery{AnnotationId: annotationID, OrgId: c.OrgId})
@marefr  Addressed all comments. I think i'm all good now.

2019-02-06 13:08 UTC, marefr approved these changes
Now I have done some manual testing as well and everything works as expected.

Awesome! Great work!

2019-02-06 13:50 UTC, merged

2019-02-06 13:50 UTC, marefr commented
Thank you for contributing to Grafana!