use authTokenService for session quotas restrictions
grafana/grafana pull request #15378
Opened 2019-02-11 20:52 UTC by bergquist

closes #15360

2019-02-11 20:55 UTC, bergquist commented on pkg/services/auth/auth_token_test.go
> +			Convey("Can count active tokens", func() {
should have tests that excludes old tokens as well.

2019-02-12 11:45 UTC, marefr requested changes
Looks good :+1: Some minor comments

2019-02-12 11:45 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	tokenMaxLifetime := time.Duration(s.Cfg.LoginMaxLifetimeDays) * 24 * time.Hour
Duplicate code which are used in `LookupToken` and almost also in token_cleanup.go. Should be able to extract some common parts.

2019-02-12 11:45 UTC, marefr commented on pkg/services/auth/auth_token.go
> +func (s *UserAuthTokenService) ActiveAuthTokenCount() (int64, error) {
A bit picky maybe but my OCD is too strong. All other methods in this service are referred to by `Token` and not `AuthToken`.

2019-02-12 14:38 UTC, merged