[WIP] Integrate React Piechart panel
grafana/grafana pull request #15511
Opened 2019-02-18 17:10 UTC by corpglory-dev

PR adds:

* Piechart component in `@grafana/ui`
* React Piechart panel

Rendering is not implemented yet

2019-02-19 14:48 UTC, torkelo commented
would be interesting to define the interface for this component:

```ts
export interface Props extends Themeable {
  height: number;
  width: number;

  unit: string;
  value: number;
  pieType: string;
  format: string;
  stat: string;
  strokeWidth: number;
}
```

this will obviously not work as it will need many "series" or rows. Question is should it take  TimeSeriesVMs and some Table model format. Or some higher level abstraction that the PieChartPanelPlugin will have to transform data into. 

like 

```
export interface PieChartDataPoint {
  value: number;
  name: string; 
  color: string;
}

export interface Props extends Themeable {
  height: number;
  width: number;
  unit: string;  
  datapoints: PieChartDataPoint[]  
}
```

2019-03-07 14:38 UTC, torkelo commented on public/app/plugins/panel/piechart/plugin.json
> +
can we add a "state": "alpha"  here? Then we can merge this to master without it being "finished" . To be able to use alpha panels you need to modify you ini file to include:

[panels]
enable_alpha = true

2019-03-07 14:39 UTC, torkelo commented
This looking like a good start! Think we could merge this soon and continue refining it other PRs. 

Please see my comment on adding a alpha state to it.

2019-03-07 14:41 UTC, torkelo commented
Can you try adding a simple storybook story for the piechart ? that would nice.  See this for reference:
https://github.com/grafana/grafana/pull/15466/files#diff-7d3f4c399bb414d9c6a2b4e3f08b2c85

2019-03-07 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=15511) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=15511) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: corpglory-dev<br/>:x: GreenGloryBot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=15511) it.</sub>

2019-03-08 08:45 UTC, torkelo commented on packages/grafana-ui/src/components/Piechart/Piechart.tsx
> +import * as d3 from 'd3';
can you import only what your using here?

2019-03-08 08:48 UTC, peterholmberg commented on packages/grafana-ui/src/components/Piechart/Piechart.tsx
> +export enum PiechartType {
Rename Piechart to PieChart

2019-03-08 08:54 UTC, peterholmberg requested changes
Since pie chart is two words, I'd like to use PieChart instead of Piechart everywhere in this PR

2019-03-11 12:08 UTC, corpglory-dev commented
@torkelo @peterholmberg thanks for the review, code is fixed

2019-03-20 18:27 UTC, torkelo commented
don't work on legend for this new piechart yet. think we can reuse a common legend component for the new graph panel hopefully

2019-03-21 07:36 UTC, merged