Fix Datasource Update to no User/Password
grafana/grafana pull request #15608
Opened 2019-02-22 13:37 UTC by Maddin-619

Until now it was not possible to update a datasource that has a database with a user and password to one without user and password. When clearing the user and passowrd input field from a already existing datasource and hit the submit button the user and password reappears in the input field. The only way was to create a new datasource without adding user and passowrd for anonymous loggin. So I chanced the SQL updated function such that all fields (also empty fileds) gets updated.

2019-02-22 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=15608) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=15608) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=15608) it.</sub>

2019-03-04 10:58 UTC, torkelo commented
This looks ok, think it makes all these calls obsolete:

https://github.com/grafana/grafana/blob/09cd173e9249d5e54cf3c304d2430f0390c68f45/pkg/services/sqlstore/datasource.go#L167

2019-03-05 12:34 UTC, bergquist requested changes

2019-03-05 12:34 UTC, bergquist commented on pkg/services/sqlstore/datasource.go
> +		affected, err := updateSession.AllCols().Omit("created").Update(ds)
Sweet! Didnt know about AllCols :) 

All Torkel mentioned the sess.UseBool calls should be removed. Confusing to solve the same problem twice.

2019-03-05 12:35 UTC, bergquist commented on pkg/services/sqlstore/datasource.go
> +		affected, err := updateSession.AllCols().Omit("created").Update(ds)
Merging this once those removes have been removed.

2019-03-05 12:42 UTC, bergquist commented on pkg/services/sqlstore/datasource.go
> +		affected, err := updateSession.AllCols().Omit("created").Update(ds)
Nevermind. I made the change myself since its so small.

2019-03-05 13:37 UTC, bergquist approved these changes

2019-03-05 13:38 UTC, merged

2019-03-10 19:00 UTC, daniellee commented
This introduced a serious bug I think for SecureJsonData fields as it overwrites the `secure_json_data` column with an empty object if the user clicks saves and test a second time after entering a new password. Investigating now and will open a new issue to revert this change.

2019-03-11 08:53 UTC, Maddin-619 commented
Sorry my bad. It was a bit confusing for me, because there are differences in the way datasources are configured. MySQL and InfluxDB store credentials in User, Password columns in plaintext. Azure Monitor and PostgreSQL stores the key/password encrypted in the secureJsonData. Maybe it's better to get rid of the plaintext password column completely and switch to secureJsonData for all Datasources to store the key/password. After that we can think about a generic solution, which makes it possible to update to no user and password.

2019-03-11 17:37 UTC, daniellee commented
@Maddin-619 yes, we definitely should switch all the datasources to use secureJsonData. It is bad, legacy code that datasources have unencrypted passwords.

This was not an obvious bug as there are only two core datasources that use this pattern. We will definitely try and come up with a solution to solve the original issue.