@grafana/ui - release docs v1
grafana/grafana pull request #15835
Opened 2019-03-06 18:33 UTC by dprokop

- Added information about development and releases of @grafana/ui
- Automatically create and push version commit when releasing @grafana/ui

2019-03-07 09:41 UTC, peterholmberg requested changes

2019-03-07 09:41 UTC, peterholmberg commented on packages/grafana-ui/README.md
> +To release new version run `npm run gui:release` script *from Grafana repository root*. The script will prepare distribution package as well as allow you to bump library version and publish new versi
_the_ distribution package

prompting instead of allow maybe?

2019-03-07 11:04 UTC, peterholmberg approved these changes

2019-03-08 08:40 UTC, torkelo approved these changes
looks good :)

2019-03-08 13:42 UTC, merged