Mobile: Switch to mobile view already at md or lower breakpoint
grafana/grafana pull request #16783
Opened 2019-04-26 08:52 UTC by torkelo

This improves Grafana for smaller screens. 

The mobile menu mode (that hides sidemenu and switches to mobile menu) breakpoint was on lower(sm) but the dashboard grid breakpoint to switch to mobile (stacked panels) view is on md. 

This PR changes to that the mobile view (hide sidemenu + mobile view) now is enabled when lower(md) ie lower than 768px same as dashboard grid. 

Also contains some minor fixes & refactorings to align responsive behavior between dashboard nav and explore.

2019-04-26 11:49 UTC, Ijin08 requested changes
Everything seemed to work fine. One thing I noticed though about having the breakpoint as less than 768. I guess the reason for it was that Ipads are 768 wide. Shouldn't the breakpoint be <= 786. Right now the side menus shows on regular Ipad.

2019-04-26 12:18 UTC, torkelo commented
great feedback @Ijin08 ! your right the breakpoint should kick in on bigger screens than the ipad in portrait. 

Tested a few different things the easiest was to just increase the md breakpoint by 1px .

2019-04-26 13:54 UTC, Ijin08 approved these changes

2019-04-26 17:16 UTC, merged

2019-09-30 06:34 UTC, adrianhewitt commented
Unsure if this is where I should mention this, but after recently updating Grafana it's hosed my work dashboard that is displayed on an iPad sitting in a dock... Guess I need to build my own theme to revert this responsive change?