Use sqlstore.WithDbSession in auth token package
grafana/grafana pull request #16785
Opened 2019-04-26 13:26 UTC by bergquist

ref https://github.com/grafana/grafana/issues/16638

2019-04-26 13:30 UTC, bergquist commented
Migrating from the old way to using `WithDbSession` I realized how bad the API is. We need to figure out a better API for this. Its very easy to write code like this
```go
var affected int64
err := srv.SQLStore.WithDbSession(ctx, func(dbSession *sqlstore.DBSession) error {
	// code

	affected, err := res.RowsAffected() 
	return err
})
```
and create an new variable in that scope instead of assigning the original one.

2019-04-26 13:48 UTC, marefr requested changes
Just to be clear this doesn't add any retries for sqlite right?

You did a very thorough work getting context in everywhere, but in auth_token.go you forget to use the provided ctx as argument to `WithDbSession` :)

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +		err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +		err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err = s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	return s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err := s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 13:48 UTC, marefr commented on pkg/services/auth/auth_token.go
> +	err := s.SQLStore.WithDbSession(context.Background(), func(dbSession *sqlstore.DBSession) error {
s/context.Background()/ctx

2019-04-26 18:48 UTC, torkelo commented
Just to understand the db locked issue and how this solves it. Was it caused, you suspect, by opening & not closing sessions? 

Wonder if it would be possible to open a session in the middleware at the start and store it in the Request context, and the pass context down to sql layer and have the withDbSession reuse session in the context object. And have the middleware close the session on request completion.

2019-04-30 05:48 UTC, bergquist commented
Fixed the `context.Background` issues and switched to using transactions (inc retries) for rotation. I was considering adding retries for all WithDbSession requests as well but Im not sure about it. It could potentially create more requests to the db if it's exhausted. 

@torkelo yesterday I didn't like that idea but I might have changed my mind. We still need some way of managing session background tasks. Let's discuss that in another issue. I think we need to improve this soon as more people will be working in the backend.

2019-04-30 12:09 UTC, marefr requested changes
Everything looks good besides some dummy code that seems to have been sneaked in, see comment.

2019-04-30 12:09 UTC, marefr commented on pkg/services/quota/quota.go
> +
Please remove this :smile:

2019-04-30 12:10 UTC, bergquist commented on pkg/services/quota/quota.go
> +
haha

2019-04-30 12:37 UTC, marefr approved these changes
:tada:

2019-04-30 12:42 UTC, merged