Fix: if current sort key is not active column, do not use for sort an…
grafana/grafana pull request #17095
Opened 2019-05-15 13:21 UTC by shavonn

…d select next available active (#16980)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2019-05-15 13:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=17095) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=17095) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=17095) it.</sub>

2019-05-15 15:20 UTC, torkelo commented
I am not sure this fixes the problem described in the issue. Hold off merging, need to investigate

2019-05-15 16:03 UTC, torkelo requested changes
This is not really fixing the problem fully and has an update call (onToggleSort) in the render path. 
Think ignoring the sort option if alignAsTable is false or legend[legend.sort] is false is best. 

There are two sorts happening (took me some time to figure out why) but think it's correct as they can be independent. 

So the logic of not sorting if alignAsTable is false or legend[legend.sort] is false needs to be done here as well. 
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L461

The reason there are 2 sort is that one controls the sort in legend, the other sort in the graph (render order), the sort in the graph only has effect if stacking is enabled.

2019-05-15 17:16 UTC, shavonn commented on public/app/plugins/panel/graph/Legend/Legend.tsx
> +          this.props.onToggleSort(property, this.props.sortDesc);
Removed this entire block in lieu of proposed solution above.

2019-05-15 22:11 UTC, daniellee commented
@shavonn after the last changes, there is a failing test: https://circleci.com/gh/grafana/grafana/100809?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

2019-05-16 19:15 UTC, torkelo approved these changes
Looks good now!

2019-05-16 19:16 UTC, merged