Build: Enables end-to-end tests in build-master workflow
grafana/grafana pull request #17268
Opened 2019-05-24 12:46 UTC by hugohaggmark

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

2019-05-24 13:57 UTC, xlson requested changes
Looks good, just need to fix the docker image name.

2019-05-24 13:57 UTC, xlson commented on .circleci/config.yml
> +        - image: grafana/grafana-dev:$CIRCLE_SHA1
```suggestion
        - image: grafana/grafana-dev:master-$CIRCLE_SHA1
```

See: https://hub.docker.com/r/grafana/grafana-dev/tags

2019-05-24 15:51 UTC, ryantxu reviewed
Looks fine to me -- but I'm guess I was requested for review by mistake? :)

2019-05-27 05:11 UTC, hugohaggmark commented on .circleci/config.yml
> +        - image: grafana/grafana-dev:$CIRCLE_SHA1
Good catch! I'll fix

2019-05-27 08:56 UTC, xlson approved these changes
LGTM!

2019-05-27 10:22 UTC, merged