convert 'login maximum inactive lifetime' to duration
grafana/grafana pull request #17555
Opened 2019-06-12 17:15 UTC by stang

**What this PR does / why we need it**:
This allows to set a `login_maximum_inactive_lifetime` that is shorter than 1 day.

**Which issue(s) this PR fixes**:
Fixes #17554

**Special notes for your reviewer**:

2019-06-12 17:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=17555) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=17555) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=17555) it.</sub>

2019-12-11 14:12 UTC, aknuds1 commented
Hi @stang - thanks for your contribution, we are interested in merging this. Can you please resolve the conflicts, and also do the following:

* Keep `login_maximum_inactive_lifetime_days` (in addition to `login_maximum_inactive_lifetime_duration`), for backwards compatibility
* For symmetry, introduce a variable `login_maximum_lifetime_duration`

2020-01-24 08:23 UTC, aknuds1 requested changes
We're interested in merging this, but would like the following changes:
* Keep login_maximum_inactive_lifetime_days (in addition to login_maximum_inactive_lifetime_duration), for backwards compatibility
* For symmetry, introduce a variable login_maximum_lifetime_duration

2020-02-19 22:07 UTC, vsenapathy commented
When is this going to be merged in?

2020-02-19 22:57 UTC, aknuds1 commented
@vsenapathy See the changes we requested above.

2020-02-19 23:33 UTC, vsenapathy commented
@stang : Can you provide an update on this. Has the requested changes been made so that this change can be merged in.

2020-04-04 00:04 UTC, closed without merging

2020-07-30 11:02 UTC, daurelio-deloitte commented
could this PR be open again?