Explore: Improves performance of Logs element by limiting re-rendering
grafana/grafana pull request #17685
Opened 2019-06-20 09:37 UTC by kaydelaney

**What this PR does / why we need it**:
Improves performance of Logs element by re-rendering only when query has finished executing or when the de-duplication strategy changes.
Needed as performance was suffering by re-rendering Logs whenever the QueryField's state changed.

**Which issue(s) this PR fixes**:
Closes #17663

**Special notes for your reviewer**:
It's possible I've missed a condition besides a query finishing execution or the de-duplication strategy changing that should prompt a re-render, but it seems to work fine from the testing I did.

2019-06-20 09:59 UTC, hugohaggmark requested changes
Looks like a good approach, I found another prop that should be checked `logsHighlighterExpressions`. This is changed whenever a user using Loki types a keyword to highlight in the logresults.

Haven't tested if that makes the performance worse again though.

2019-06-20 09:59 UTC, hugohaggmark commented on public/app/features/explore/LogsContainer.tsx
> +    return nextProps.loading !== this.props.loading || nextProps.dedupStrategy !== this.props.dedupStrategy;
Maybe include highlighterExpressions?
```suggestion
    return nextProps.loading !== this.props.loading || nextProps.dedupStrategy !== this.props.dedupStrategy || nextProps.logsHighlighterExpressions !== this.props.logsHighlighterExpressions;
```

2019-06-20 10:49 UTC, kaydelaney commented
> Looks like a good approach, I found another prop that should be checked `logsHighlighterExpressions`. This is changed whenever a user using Loki types a keyword to highlight in the logresults.
> 
> Haven't tested if that makes the performance worse again though.

Tested and it doesn't seem to affect performance (at least not noticeably), probably because `updateLogsHighlights` is debounced.

2019-06-20 11:50 UTC, hugohaggmark approved these changes
LGTM!

2019-06-20 11:56 UTC, merged

2019-06-20 16:18 UTC, marefr commented
Added this to the 6.2.5 milestone instead since I think we should take the opportunity to patch this since it makes the explore experience so much better.

2019-06-25 16:59 UTC, kylebrandt commented
Removed from 6.2.5 release because based on commit in master that is not in the patch release branch resulting in a conflict:

```
<<<<<<< HEAD
=======
  getLogRowContext = async (row: LogRowModel, options?: any) => {
    const { datasourceInstance } = this.props;

    if (datasourceInstance) {
      return datasourceInstance.getLogRowContext(row, options);
    }

    return [];
  };

  // Limit re-rendering to when a query is finished executing or when the deduplication strategy changes
  // for performance reasons.
  shouldComponentUpdate(nextProps: LogsContainerProps): boolean {
    return (
      nextProps.loading !== this.props.loading ||
      nextProps.dedupStrategy !== this.props.dedupStrategy ||
      nextProps.logsHighlighterExpressions !== this.props.logsHighlighterExpressions
    );
  }

>>>>>>> 57dadebbd... Explore: Improves performance of Logs element by limiting re-rendering (#17685)
```

2019-06-25 17:06 UTC, marefr commented
Thanks @kylebrandt :+1: