Docs: Adds section on Querying Logs for InfluxDB
grafana/grafana pull request #17726
Opened 2019-06-24 13:13 UTC by hugohaggmark

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #17715

**Special notes for your reviewer**:
First time I added documentation and images so please advise if I'm doing something in the wrong order.

2019-06-24 13:14 UTC, hugohaggmark commented
Just saw that vscode auto formatted stuff, I'll revert the commit and add new section again.

2019-06-24 14:31 UTC, kaydelaney commented on docs/sources/features/datasources/influxdb.md
> +![](/img/docs/influxdb/explore_metrics_logs_switch.png<br>
Missing a closing parentheses:
```suggestion
![](/img/docs/influxdb/explore_metrics_logs_switch.png)<br>
```

2019-06-24 14:31 UTC, kaydelaney commented on docs/sources/features/datasources/influxdb.md
> +![](/img/docs/influxdb/explore_measurements_fields_button.png<br>
See above
```suggestion
![](/img/docs/influxdb/explore_measurements_fields_button.png)<br>
```

2019-06-24 14:31 UTC, kaydelaney commented on docs/sources/features/datasources/influxdb.md
> +![](/img/docs/influxdb/explore_measurements_fields_button.png<br>
See above
```suggestion
![](/img/docs/influxdb/explore_measurements_fields_button.png)<br>
```

2019-06-24 14:32 UTC, hugohaggmark commented on docs/sources/features/datasources/influxdb.md
> +![](/img/docs/influxdb/explore_metrics_logs_switch.png<br>
Thanks @kaydelaney

2019-06-24 15:41 UTC, marefr requested changes
Think that it would be nicer to have one big screenshot that shows query field, date histogram and some log messages.

Then you can probably remove `<br>` which currently breaks apart the text.

2019-06-26 06:21 UTC, hugohaggmark commented
> Think that it would be nicer to have one big screenshot that shows query field, date histogram and some log messages.
> 
> Then you can probably remove `<br>` which currently breaks apart the text.

Thanks, could you be a bit more specific. Should I remove all the pictures replacing it with the one you suggest or are you thinking of a specific paragraph?

2019-06-26 10:51 UTC, marefr commented
Sync with @kaydelaney she has done similar changes for influx. Basically just one screenshot.

2019-06-26 16:57 UTC, marefr requested changes
Approved, but blocked by https://github.com/grafana/website/pull/217

2019-06-26 17:21 UTC, marefr approved these changes

2019-06-26 17:40 UTC, merged