prometheus rerun query on input update
grafana/grafana pull request #18147
Opened 2019-07-16 19:51 UTC by fxmiii

**What this PR does / why we need it**: When a user updates the fields for "Legend" and "Min step" the query is not re-run.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: I think this functionality at some point moved from '/public/app/plugins/datasource/prometheus/partials/query.editor.html' where this used to work by calling "ctrl.refreshMetricData()". Maybe there is a good reason not to do it anymore but I can't figure out why.

Also I fixed a small typo in a comment in the file. Maybe I should have done that in a separate PR?

Thanks

2019-08-09 14:01 UTC, davkal requested changes
The input change handlers should not trigger expensive actions like queries, since they are part of the tight update loop of react components. 
I recommend registering an `onBlur` handler on both inputs, and have that trigger the query run. AFAIK that was the original behavior (run query when leaving the field). 
Let me know if you need help doing this. @fxmiii

2019-08-12 16:33 UTC, fxmiii commented
Is this what you are looking for?

2019-08-12 16:41 UTC, fxmiii commented
I suppose it could also be smarter by only rerunning the query onBlur if the field has changed. But that also might be unnecessary complexity for little real benefit.

2019-08-14 12:52 UTC, davkal approved these changes

2019-08-14 13:15 UTC, merged