Docs: Update documentation with new SAML features
grafana/grafana pull request #18163
Opened 2019-07-17 19:42 UTC by gotjosh

**What this PR does / why we need it**:

- Updates `sample.ini` and `defaults.ini` with the mapping configuration options
- Updates the SAML documentation with the assertion mapping configuration options.

2019-07-18 15:45 UTC, alexanderzobnin approved these changes
LGTM!

2019-07-19 12:17 UTC, xlson requested changes
Great work on the docs, very comprehensive.

The SAML docs page should contain a blurb about this being an Enterprise feature, just as at the top of https://grafana.com/docs/auth/enhanced_ldap/

SAML should be mentioned on the Grafana Enterprise page with a link back to the SAML docs.

2019-07-19 12:17 UTC, xlson commented on docs/sources/auth/saml.md
> +| `certificate                | _path`   | Yes                                                                                                | Base64-encoded string or Path for the SP X.509 certific
We have a rogue `|` here that makes _path end up in the Required column and everything else pushed a column as well.

Perhaps try without the `|` (which could be considered a bit technical) and go with something like this: `certificate` or `certificate_path`

2019-07-19 12:17 UTC, xlson commented on docs/sources/auth/saml.md
> +| `eanbled`                   | No       | Whenever SAML authentication is allowed                                                            | `false`
```suggestion
| `enabled`                   | No       | Whenever SAML authentication is allowed                                                            | `false`                                                     |
```

2019-07-19 12:17 UTC, xlson commented on docs/sources/auth/saml.md
> +| `certificate                | _path`   | Yes                                                                                                | Base64-encoded string or Path for the SP X.509 certific
Same goes for the other similar cases.

2019-07-23 07:50 UTC, xlson approved these changes
Looks great!

2019-07-23 08:20 UTC, merged