Timerange: Fixes a bug where custom time ranges didn't respect UTC
grafana/grafana pull request #18217
Opened 2019-07-22 11:27 UTC by kaydelaney

**What this PR does / why we need it**:
Fixes a bug where custom time ranges didn't respect UTC

**Which issue(s) this PR fixes**:
Closes #18170

2019-07-22 12:02 UTC, kaydelaney commented
Ah, apparently this stops relative times from displaying in the time picker - it won't display as "Last 7 days" but rather the time range that refers to. Looking into it now

2019-07-23 10:45 UTC, davkal commented on packages/grafana-ui/src/components/TimePicker/TimePicker.tsx
> +    const adjustedTo = isUTC ? value.from.utc() : value.from.local();
Ooops. Should be `value.to`.

2019-07-23 10:49 UTC, davkal requested changes
Works well and seems to fix both issues.

Blocker: the range strings are reversed. Otherwise all good.

2019-07-23 12:47 UTC, kaydelaney commented on packages/grafana-ui/src/components/TimePicker/TimePicker.tsx
> +    const adjustedTo = isUTC ? value.from.utc() : value.from.local();
oh, silly mistake, will fix

2019-07-23 13:58 UTC, davkal approved these changes
All good now 🎉

2019-07-23 14:17 UTC, davkal commented
Fixes #18178 as well.

2019-07-24 10:00 UTC, merged