AzureMonitor: Azure Resource Graph
grafana/grafana pull request #18629
Opened 2019-08-19 15:31 UTC by yesoreyeram

**What this PR does / why we need it**:

Currently azure monitor datasource supports 3 different data types

* Azure monitor
* Application Insights
* Log analytics

additionally, this pull request will help to add new type of data source from **"Azure Resource Graph"**.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/17202

**Special notes for your reviewer**:

This is my first PR so feel free to suggest corrections.

2019-08-19 15:36 UTC, yesoreyeram commented
# Sample output

![image](https://user-images.githubusercontent.com/153843/63278539-5d27f880-c29f-11e9-88b9-49d514b5a354.png)

# Query Editor

![image](https://user-images.githubusercontent.com/153843/63278393-14703f80-c29f-11e9-9e13-f1bcd183868b.png)

2019-08-20 05:38 UTC, yesoreyeram commented
# Using resource graph query in variables

![image](https://user-images.githubusercontent.com/153843/63316399-a7909000-c306-11e9-96bd-6ed00b260278.png)

![image](https://user-images.githubusercontent.com/153843/63316432-c8f17c00-c306-11e9-9967-fb1d5722e706.png)

2019-08-21 17:47 UTC, yesoreyeram commented
@briangann For simplicity, It uses the same credentials as azure monitor. No seperate configuration settings added for **Azure Resource Graph**.  Do we need seperate configuration?

I see that we are already in the process of consolidating the configurations for different azure providers.

2019-08-23 03:21 UTC, briangann commented
We're unifying authentication methods in another PR. Separating the config (hopefully) should not be necessary.  The current config method is cumbersome.

Looking forward to see what this PR does :)

2019-10-18 13:33 UTC, maxilampert commented
@briangann Any update on when this gets merged?

2020-01-21 23:14 UTC, shavonn requested changes
Just these couple of changes and fix tests.

2020-01-21 23:14 UTC, shavonn commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_resource_graph/azure_resource_graph_datasource.ts
> +import { IQService } from 'angular';
We've removed the IQService from these so this should come out in the constructor and `this.$q` replace with `Promise` where ex:`return Promise.all(promises).then(results => {`

2020-01-21 23:14 UTC, shavonn commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts
> +      this.$q
Remove as arg.

2020-01-24 18:16 UTC, yesoreyeram commented
Sure @shavonn will update this next week.

2020-01-26 20:03 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=18629) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=18629) before we can accept your contribution.<br/>**16** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: ryantxu<br/>:white_check_mark: kaydelaney<br/>:white_check_mark: torkelo<br/>:white_check_mark: yesoreyeram<br/>:white_check_mark: shavonn<br/>:white_check_mark: hugohaggmark<br/>:white_check_mark: aocenas<br/>:white_check_mark: papagian<br/>:white_check_mark: sunker<br/>:white_check_mark: dprokop<br/>:white_check_mark: johntdyer<br/>:white_check_mark: ivanahuckova<br/>:white_check_mark: aknuds1<br/>:white_check_mark: marefr<br/>:white_check_mark: tskarhed<br/>:white_check_mark: xlson<br/>:x: Tobias Skarhed<br/><hr/>**Tobias Skarhed** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=18629) it.</sub>

2020-02-17 12:37 UTC, yesoreyeram commented
Git rebase messed up my PR with many changes happened in the master meanwhile. I am working on cleanup and making changes to align with master.

2020-03-03 15:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=18629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=18629) before we can accept your contribution.<br/>**16** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: shavonn<br/>:white_check_mark: hugohaggmark<br/>:white_check_mark: ryantxu<br/>:white_check_mark: yesoreyeram<br/>:white_check_mark: dprokop<br/>:white_check_mark: johntdyer<br/>:white_check_mark: torkelo<br/>:white_check_mark: papagian<br/>:white_check_mark: aknuds1<br/>:white_check_mark: sunker<br/>:white_check_mark: kaydelaney<br/>:white_check_mark: ivanahuckova<br/>:white_check_mark: tskarhed<br/>:white_check_mark: marefr<br/>:white_check_mark: aocenas<br/>:white_check_mark: xlson<br/>:x: Tobias Skarhed<br/><hr/>**Tobias Skarhed** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=18629) it.</sub>

2020-03-11 08:35 UTC, bergquist commented
Moving this to 7.0 since this PR is not ready for review.

2020-06-30 08:18 UTC, closed without merging