Azure Monitor : Query more than 10 dimensions ( Fixes #17230 )
grafana/grafana pull request #18693
Opened 2019-08-23 09:33 UTC by yesoreyeram

**What this PR does / why we need it**:

Query more than 10 dimensions in Azure Monitor API. Azure monitor pulls only 10 dimensions by default.  This PR gives ability to pull more than 10 dimension instances.

![image](https://user-images.githubusercontent.com/153843/63582621-52b47a00-c591-11e9-924d-9594fd7cb082.png)

Fixes #17230

2019-09-20 08:44 UTC, marefr commented
@yesoreyeram Could you please merge with/rebase on latest master and we'll have a look at this. Thanks

2019-09-30 09:30 UTC, yesoreyeram commented
@marefr  - I dont see any merge conflicts. Still do you want me to rebase?

> @yesoreyeram Could you please merge with/rebase on latest master and we'll have a look at this. Thanks

2019-09-30 10:04 UTC, marefr commented
@yesoreyeram we reverted a change in master that's probably why :)

2019-10-01 08:52 UTC, sunker requested changes
Great work! Just fix the minor changes that was requested and I'm ready to merge.

2019-10-01 08:52 UTC, sunker commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts
> +      const top = this.templateSrv.replace(item.top || `10`, options.scopedVars);
replace item.top || \`10\` with item.top || ''
you never want to intercept 10 as a template variable

2019-10-01 08:52 UTC, sunker commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts
> +          top: top || `10`,
replace backticks with single quotes

2019-10-01 08:52 UTC, sunker commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/query_ctrl.ts
> +      top: `10`,
single quotes

2019-10-03 14:52 UTC, sunker approved these changes

2019-10-03 14:53 UTC, merged