LDAP: Do not panic when closing the connection if it's not established
grafana/grafana pull request #18897
Opened 2019-09-04 15:42 UTC by gotjosh

Our LDAP library requires that we `Dial()` a connection to the LDAP server before we establish a connection (and therefore assign the `Connection` struct). That means if we end up attempting to call the `Close()` method before `Dial()` we end up with panicking due to the connection not being present.

I'm looking for any opinions on which of the two commits (or maybe both?) should be included. The first `7c4f498` takes a more defensive approach by verifying that we have a connection before we close it. The second `9cb2429`, makes a more "proper" use of the library in the first place. By only calling `close` if we didn't error out whilst establishing the connection. Thoughts?

I'm happy to take one or the other.

2019-09-06 08:31 UTC, xlson requested changes
We discussed this at the end of the daily yesterday. To summarize:

`Close()` should return an error if it is unable to close the connection rather than causing a fatal in the server (due to connection being nil)

2019-09-10 16:44 UTC, gotjosh commented
When @xlson and I spoke about this we had two options. Either we change the interface (and make it return an error) everywhere the connection is used or we document it somehow to make the user of the library aware it. I have decided on the latter.

I'm keen to avoid a [shotgun surgery](https://refactoring.guru/smells/shotgun-surgery) on this interface for such a simple mistake (see the changes on `multildap.go` which are the cause of the problem) hence the decision for the documentation.

2019-09-13 08:08 UTC, markelog commented on pkg/services/ldap/ldap.go
> +// Dial() sets the connection with the server for this Struct. Therefore, we require a
I would specify documentation only once, either in Dial or in package desc. I would expect our LDAP module to resemble logic of any db connector. 

So for me, that’s not really surprising, so I am bias here

2019-09-16 09:23 UTC, xlson approved these changes

2019-09-16 13:13 UTC, merged