Create STYLEGUIDE.md
grafana/grafana pull request #19190
Opened 2019-09-18 00:52 UTC by oddlittlebird

Fixes #19134

2019-09-18 04:35 UTC, bharjala requested changes
Two initial suggestions:
- Add a link to [Chicago Manual of Style](https://www.chicagomanualofstyle.org/home.html)
- Add an example for active / passive voice, similar to your example for imperative second person.
- - Add an example of sentence case, headings that start with verbs, etc. 

For new tech writers and contributors, clear, upfront examples are helpful.

2019-09-18 16:43 UTC, marcusolsson commented
I've been looking at the current images:

Preferred format: PNG
DPI: Most images are 72 DPI with some outliers

Width range: 32px – 3712px (most between 430px – 1290px)
Height range: 30px – 1854px (most between 30px – 910px)

Biggest one seems to be: https://github.com/grafana/website/blob/master/static/static/img/docs/v60/explore_split.png

For now, maybe set maximum size to 3840×2160 (4K), for high-quality screenshots?

As for the minimum size, I'm thinking 256x256. There are a handful of images smaller than that, but I'm debating whether that's too small. Here's an example: https://github.com/grafana/website/blob/master/static/static/img/docs/v60/explore_menu.png

2019-09-19 02:22 UTC, oddlittlebird commented
Applied edits.

We still lack information for how users should deal with image callouts.

I think we need to give guidelines, tell them to just take the screenshot and we will add callouts, or tell them Grafana personnel will supply updated images.

2019-09-19 14:47 UTC, marcusolsson requested changes

2019-09-19 14:47 UTC, marcusolsson commented on docs/STYLEGUIDE.md
> +* Write in the imperative second person. Examples: You can do a thing. Click the panel. Shoot the zombie.
I'd like to use a friendlier example than _shoot the zombie_, e.g. eat the cake, pet the dog.

2019-09-19 14:47 UTC, marcusolsson commented on docs/STYLEGUIDE.md
> +    Grafana opens the panel.
Maybe put this on same line:

- Not: The panel will open.
- Use: The panel opens, or, Grafana opens the panel.

... or add another Use item:

- Not: The panel will open.
- Use: The panel opens.
- Use: Grafana opens the panel.

2019-09-19 14:47 UTC, marcusolsson commented on docs/STYLEGUIDE.md
> +* Screenshots should be readible, but not too large.
readible -> readable?

2019-09-19 14:47 UTC, marcusolsson commented on docs/STYLEGUIDE.md
> +* `amtool` is never capitalized.
This is too specific, and not a Grafana term. I think we should remove it, otherwise we'd have to list a lot of these.

2019-09-19 15:34 UTC, marcusolsson commented
Also, I'm debating whether the style guide should go into https://github.com/grafana/grafana/tree/master/style_guides or whether this should be a proper page under "Contribute" in the documentation.

2019-09-19 15:36 UTC, marcusolsson commented
I think best place for now is to put it next to the other style guides in the style_guides directory, and link from the docs guide.

2019-09-20 05:11 UTC, oddlittlebird commented on docs/STYLEGUIDE.md
> +* Screenshots should be readible, but not too large.
ARGH. And that is why we have editors.

2019-09-20 08:41 UTC, marcusolsson requested changes
This is great stuff! 

One minor thing before I think we can merge this. None of the other style guides have the `-style-guide` prefix in their filename. I think we should be consistent here:

Basically rename the file to just `docs.md`.

Almost there!

2019-09-20 13:59 UTC, oddlittlebird commented
I renamed the style guides to match their titles with the exception of themes.md, since that one is the subject of a different issue.

2019-09-20 16:44 UTC, marcusolsson approved these changes
Looks great! Thanks for helping out with this! 👍

2019-09-20 16:45 UTC, merged

2019-09-20 16:46 UTC, oddlittlebird commented
My pleasure.

On Fri, Sep 20, 2019, 9:45 AM Marcus Olsson <notifications@github.com>
wrote:

> *@marcusolsson* approved this pull request.
>
> Looks great! Thanks for helping out with this! 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana/pull/19190?email_source=notifications&email_token=AMNF6KJFXBWVVFUPUZZOOF3QKT42DA5CNFSM4IXXLULKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFOIUAA#pullrequestreview-291277312>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMNF6KJYIUKCY56Z5H7XYULQKT42DANCNFSM4IXXLULA>
> .
>