Update ISSUE_TRIAGE.md
grafana/grafana pull request #19280
Opened 2019-09-22 18:52 UTC by oddlittlebird

Minor grammar edits

2019-09-22 19:49 UTC, marcusolsson requested changes
Thanks for cleaning up these documents! 👍

2019-09-22 19:49 UTC, marcusolsson commented on ISSUE_TRIAGE.md
> +** Simplified flowchart diagram of the issue triage process:
I'm not sure this is what the author intended. The asterisks are used to make this sentence bold (although maybe it should be a heading?).

2019-09-22 21:20 UTC, oddlittlebird commented
I am quite sure it is not what the author intended, but it looks to me like
it should be a heading.

The content in this document is excellent, but it needs a thorough edit and
probably to be split into two or three documents:

* Grafana triage process, high level, include internal parts for external
contributor visibility
* how you can help triage
* other TBD

Anyway, all of that should be covered by the issue you are working on. This
is just a quick fix in the meantime.

On Sun, Sep 22, 2019, 12:50 PM Marcus Olsson <notifications@github.com>
wrote:

> *@marcusolsson* requested changes on this pull request.
>
> Thanks for cleaning up these documents! 👍
> ------------------------------
>
> In ISSUE_TRIAGE.md
> <https://github.com/grafana/grafana/pull/19280#discussion_r326916477>:
>
> >  * Giving a contributor the information they need before they commit to resolving an issue.
>
>  * Lowering the issue count by preventing duplicate issues.
>
>  * Streamlining the development process by preventing duplicate discussions.
>
>  * If you don't have the knowledge or time to code, consider helping with triage. The community will thank you for saving them time by spending some of yours.
>
>
>
> -**Simplified flowchart diagram of the issue triage process:**
>
> +** Simplified flowchart diagram of the issue triage process:
>
>
> I'm not sure this is what the author intended. The asterisks are used to
> make this sentence bold (although maybe it should be a heading?).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana/pull/19280?email_source=notifications&email_token=AMNF6KN3O6EH6HPX6GRQJMDQK7EBJA5CNFSM4IZEBCFKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFQE23Q#pullrequestreview-291523950>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMNF6KNOUZG445L4FGVFVHTQK7EBJANCNFSM4IZEBCFA>
> .
>

2019-09-23 07:09 UTC, marcusolsson commented on ISSUE_TRIAGE.md
> +** Simplified flowchart diagram of the issue triage process:
Maybe `## Simplified flowchart diagram of the issue triage process`?

2019-09-24 02:08 UTC, oddlittlebird commented
Marcus - 
The heading **1. Find uncategorized issues** is where the topic got very confusing for me. It was like another topic got spliced onto the first topic. Food for thought as you go through the contribution content. 

Also "ISSUE_TRIAGE" is a bad name for this topic. I expected a list of triaged issues. Something like TRIAGE_ISSUES or a a set of three docs similar to: CONTRIBUTE_CODE, CONTRIBUTE_DOCS, CONTRIBUTE_TRIAGE, would be much better.

2019-09-24 09:55 UTC, marcusolsson requested changes
There's definitely much work to be done here. Thank you for helping out!

2019-09-24 09:55 UTC, marcusolsson commented on ISSUE_TRIAGE.md
> +** Simplified flowchart diagram of the issue triage process
This should either be:

Bold: 
`**Simplified flowchart diagram of the issue triage process**`

or

Heading:
`## Simplified flowchart diagram of the issue triage process`

2019-09-25 01:56 UTC, oddlittlebird commented
Fixed the heading.

2019-09-25 04:38 UTC, marcusolsson approved these changes

2019-09-25 04:39 UTC, merged

2019-09-25 04:39 UTC, marcusolsson commented
Thanks!