Editor: Brings up suggestions menu after clicking suggestion
grafana/grafana pull request #19359
Opened 2019-09-24 10:11 UTC by kaydelaney

**What this PR does / why we need it**:
Causes the suggestions menu to display after choosing a suggestion by clicking, matching the behavior when a suggestion is chosen by pressing enter/tab.

2019-09-24 15:43 UTC, ivanahuckova submitted a review, later dismissed
Works great. Label values are displayed as intended. 🚀🚀🚀

2019-09-25 16:00 UTC, davkal requested changes
Breaks label suggestions: `up{|}` no longer shows label key suggestions.

2019-09-30 11:00 UTC, davkal approved these changes

2019-09-30 11:00 UTC, davkal commented
Can no longer repro.

2019-09-30 11:41 UTC, merged