Update SECURITY.md
grafana/grafana pull request #19385
Opened 2019-09-25 02:50 UTC by oddlittlebird

Minor grammar edits

**Special notes for your reviewer**: This is another topic that should really be put somewhere more prominent. In particular, it would be good in the Grafana documentation so that it comes up in a search. Perhaps not the email and key, but at least instructions regarding which file in the repo to go to.

It also would not be out of place in README.md.

2019-09-25 05:21 UTC, marcusolsson requested changes

2019-09-25 05:21 UTC, marcusolsson commented on SECURITY.md
>  ------------------
When using the hash tag, we can remove these hypens.

2019-09-25 08:12 UTC, marefr commented
It is in the root to show up here: https://github.com/grafana/grafana/security/policy

2019-09-26 00:29 UTC, oddlittlebird commented
Ah, I see. I suggest at some point we add it to the official documentation. Or at least add a link to the security policy. "To report a security vulnerability, see the security policy on GitHub (link)."

2019-09-26 10:42 UTC, marcusolsson approved these changes

2019-09-26 10:42 UTC, merged

2019-09-26 10:42 UTC, marcusolsson commented
Thanks! 👍