Cloudwatch: Make it clear that role switching is not supported
grafana/grafana pull request #19706
Opened 2019-10-08 12:51 UTC by sunker

fixes #18223

2019-10-09 22:15 UTC, srclosson approved these changes

2019-10-22 07:54 UTC, marefr requested changes
Added suggestion to render a `NOTE` as seen [here](https://grafana.com/docs/features/datasources/cloudwatch/#adding-the-data-source-to-grafana). What do you think?

2019-10-22 07:54 UTC, marefr commented on docs/sources/features/datasources/cloudwatch.md
> +AWS Role Switching as described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html) it not supported at the moment.
```suggestion
> NOTE: AWS Role Switching as described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html) it not supported at the moment. 
```

2019-10-22 07:55 UTC, marefr approved these changes
LGTM

2019-10-22 09:28 UTC, daniellee approved these changes

2019-10-22 09:28 UTC, merged