Docs: Document Makefile
grafana/grafana pull request #19720
Opened 2019-10-08 22:39 UTC by marcusolsson

**What this PR does / why we need it**:

This pull request documents the Makefile and adds a `help` target for displaying help texts.

Here's an example of the information displayed when running `make`, or `make help`.

<img width="840" alt="makefile" src="https://user-images.githubusercontent.com/8396880/66438443-f2887300-ea2c-11e9-8000-b705205aa1c7.png">

2019-10-09 06:56 UTC, torkelo commented on Makefile
> +devenv: devenv-down ## Set up development environment.
> Set up development environment

This seems like something you need to do in order to develop. 
Maybe something like this:

Start optional external dependencies via docker-compose like postgres, mysql, prometheus, openldap, elasticsearch etc.

Or

Start optional services of postgres, mysql, prometheus, openldap, elasticsearch, etc (you choose)

2019-10-22 08:04 UTC, aknuds1 requested changes
I think it mainly looks useful, but I question whether it's a good idea to drop the default `make` target. @marefr What do you think?

2019-10-22 08:17 UTC, marcusolsson commented
Thanks for the feedback!

2019-10-22 10:34 UTC, marefr approved these changes
LGTM

2019-10-22 12:06 UTC, aknuds1 approved these changes
LGTM

2019-10-22 14:03 UTC, merged