do not return err when sendNotification fails
grafana/grafana pull request #19807
Opened 2019-10-14 21:37 UTC by jan25

Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #19768

**Special notes for your reviewer**:

2019-10-15 08:46 UTC, marefr requested changes
Thanks. Looks great, but have a few minor requests for changes.

2019-10-15 08:46 UTC, marefr commented on pkg/services/alerting/notifier.go
> +func (n *notificationService) SendIfNeeded(context *EvalContext) {
Please add back the return of the error. We're currently doing some other error handling refactorings which handles the error returned from this method.

2019-10-15 08:46 UTC, marefr commented on pkg/services/alerting/notifier.go
> +		n.log.Error("Failed to get alert notifiers", "error", err)
Good that you added error logging here since there's currently no handling of the error returned :+1:

2019-10-15 16:26 UTC, marefr commented
We'll probably release v6.4.3 tomorrow and if I haven't heard back from you we'll probably push the requested changes to this branch and merge the PR since we want to get it out in v6.4.3,

2019-10-15 17:39 UTC, jan25 commented
@marefr thanks for the review! Could you restart the CI? looks like circleCI server issues.

2019-10-16 07:49 UTC, marefr approved these changes
Thanks. LGTM

2019-10-16 07:55 UTC, merged

2019-10-16 07:56 UTC, marefr commented
Thank you for contributing to Grafana!

2019-10-22 11:11 UTC, marefr commented
@jan25 Totally optional, but may I ask you if you're participating in Hacktoberfest and whether you've find this issue through the hacktoberfest label? Trying to find out if new contributors are finding Grafana due to Hacktoberfest.

2019-10-22 12:42 UTC, jan25 commented
Hey @marefr ! Yes i'm participating in Hacktoberfest for first time. I'm not new to Grafana project though, I was browsing through the Grafana issues list in this repo when i came across this issue. Is Grafana linked somewhere on Hacktoberfest website/twitter? that'd be super helpful for new contributors

2019-10-22 14:12 UTC, marefr commented
@jan25 Thanks. Nice to hear. I thought Hacktoberfest site linked to GitHub global search for example filtering on opening issues labeled Hacktoberfest, see https://github.com/search?q=label%3AHacktoberfest&state=open&type=Issues. Besides this [Hacktoberfest site](https://hacktoberfest.digitalocean.com/details) gives some examples of external sites where you can find issues to work on (more beginner friendly nature). 

Again, thanks for contributing to Grafana.