Explore: Remove datasource testing on selector
grafana/grafana pull request #19910
Opened 2019-10-18 16:08 UTC by davkal

- datasource testing gets in the way of fast query iteration: switching
between datasources can take seconds
- it should not be explore's duty to test datasources in the first place
- removed the concept of datasourceError in Explore, should not be its
concern
- datasource erorrs will express themselves in query errors just fine
- connection errors are still bubbled up
- removed reconnection logic from explore, should not be its concern
- missing labels in loki are still "visible" via an empty label selector
- Loki and Prometheus treated connection errors differently than other
datasources, making sure to pass through the original error message

**Special notes for your reviewer**:
- I'd like to keep the "expensive" labels test for loki in the datasource config page itself, it just got in the way of using loki quickly in explore
- try switching between several Lokis, used to take ages

2019-10-19 05:03 UTC, hugohaggmark requested changes
Great work but I found some cases where this is not working as expected:
1. Shouldn't Prometheus metrics button be disabled when we're unable to connect to data source?
2. Shouldn't Loki labels button be disabled when we're unable to connect to data source?
3. Shouldn't Influx/Logs measurements button be disabled and an error shown when we're unable to connect to data source? This one is particular user confusing as you can't do anything at all when Explore can't connect to the Influx data source.

Something that is out of scope for this PR but it would be cool if we could test the websocket connection when we test a Loki data source and not fail the test but warn the user.

2019-10-22 08:51 UTC, davkal commented on public/app/plugins/datasource/prometheus/components/PromQueryField.tsx
> -    }
Nope, this code path only triggered during a reconnect, which is no longer possible.

2019-10-22 08:51 UTC, davkal commented
> Something that is out of scope for this PR but it would be cool if we could test the websocket connection when we test a Loki data source and not fail the test but warn the user.

done in #19555

2019-10-29 09:59 UTC, hugohaggmark approved these changes
LGTM! Works as expected and tested Influx, Loki and Prometheus. Nitpick: Thought the Loki label dropdown still looks enabled compared to Prometheus.

Loki:
![image](https://user-images.githubusercontent.com/562238/67756864-11ca5d00-fa3b-11e9-86a2-850716aa9e66.png)

Prometheus:
![image](https://user-images.githubusercontent.com/562238/67756892-1f7fe280-fa3b-11e9-9480-d810f26e259a.png)

2019-10-29 10:37 UTC, merged

2019-11-11 12:54 UTC, aocenas commented
@davkal Seems like this is fine but there are some issues with how things display:

Influx right away:
<img width="650" alt="Screenshot 2019-11-11 at 13 44 35" src="https://user-images.githubusercontent.com/1014802/68588733-84e7c080-048a-11ea-9a87-0315b7ed27bb.png">

Elastic metrics/logs has an error banner right away:
<img width="819" alt="Screenshot 2019-11-11 at 13 44 49" src="https://user-images.githubusercontent.com/1014802/68588734-84e7c080-048a-11ea-85ad-30b07df3d54b.png">
<img width="513" alt="Screenshot 2019-11-11 at 13 46 31" src="https://user-images.githubusercontent.com/1014802/68588736-85805700-048a-11ea-8fdb-506a4b62b78a.png">

Loki has error only after you try to do a query.
<img width="590" alt="Screenshot 2019-11-11 at 13 45 07" src="https://user-images.githubusercontent.com/1014802/68588735-84e7c080-048a-11ea-84d2-32562a2829f4.png">