Cloudwatch: Docs improvements
grafana/grafana pull request #20100
Opened 2019-10-30 10:42 UTC by sunker

A lot of changes will be made to the CloudWatch datasource in Grafana 6.5. This PR aims to update the CloudWatch docs file accordingly.

2019-10-31 14:28 UTC, marcusolsson submitted a review, later dismissed
Nice! I added a couple of comments

2019-10-31 14:28 UTC, marcusolsson commented on docs/sources/features/datasources/cloudwatch.md
> +AWS defines quotas, or limits, for resources, actions, and items in your AWS account. Depending on the number of queries in your dashboard and the amount of users accessing the dashboard, you may rea
`you are` -> `you're`  

[Style guide](https://docs.microsoft.com/en-us/style-guide/word-choice/use-contractions)

2019-10-31 14:28 UTC, marcusolsson commented on docs/sources/features/datasources/cloudwatch.md
> +
We should avoid multiple newlines between paragraphs. Paragraphs should be seperated by one blank line:

```
To request a quota increase, visit the [AWS Service Quotas console](https://console.aws.amazon.com/servicequotas/home?r#!/services/monitoring/quotas/L-5E141212).

Please see the AWS documentation for [Service Quotas](https://docs.aws.amazon.com/servicequotas/latest/userguide/intro.html) and [CloudWatch limits](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) for more information.
```

2019-10-31 14:48 UTC, sunker commented
Thank for feedback Marcus. I'll fix!

2019-11-22 11:44 UTC, daniellee requested changes
To test the docs locally:

1. Checkout [grafana/website](https://github.com/grafana/website) repo, switch to the `old-docs` branch, and pull the latest changes, then run `make docs-build`. This will take a few minutes.
2. In the Grafana repo:
    ```
   cd docs
   make watch
   ```
3. Open http://localhost:3004/features/datasources/cloudwatch/

2019-11-22 11:44 UTC, daniellee commented on docs/sources/features/datasources/cloudwatch.md
> +## Using the M  etric Query Editor
It looks ok when I build locally but why is there a space between M and etric here?

2019-11-22 11:44 UTC, daniellee commented on docs/sources/features/datasources/cloudwatch.md
> +You need to specify a namespace, metric, at least one stat, and at least one dimension as long as `Match Exact` is activated. In the case `Match Exact` is not activated, no dimension needs to be spec
This feels like half a sentence. I need these to do what?

2019-11-22 11:44 UTC, daniellee commented on docs/sources/features/datasources/cloudwatch.md
> +When defining dimension values based on multi-valued template variables,a search expressions is used to query for the matching metrics. This enables the use of multiple template variables in one quer
- Need a space after `template variables,`
- Should be `a search expression` (no s)

2019-11-22 11:44 UTC, daniellee commented on docs/sources/features/datasources/cloudwatch.md
> +| Query                                                                                                                         | Service          |
Formatting is also messed up here:

![image](https://user-images.githubusercontent.com/434655/69422792-e7f81380-0d24-11ea-9910-344606876fa8.png)

2019-11-22 11:44 UTC, daniellee commented on docs/sources/features/datasources/cloudwatch.md
> -      accessKey: "<your access key>"
Noted that the quotes are changed here and I think that is valid YAML but worth checking to make sure.

2019-11-22 12:30 UTC, daniellee approved these changes

2019-11-22 13:51 UTC, merged

2019-11-22 15:13 UTC, oddlittlebird commented
Dang. Got to this party just a little too late.