AuthProxy: Can now login with auth proxy and get a login token
grafana/grafana pull request #20175
Opened 2019-11-05 12:35 UTC by torkelo

Fixes #17316 

Changed so you can login using auth proxy. If you access /login and the your already logged in via auth proxy we now create an auth token so you stay logged in after redirect. 

Added example nginx config to test this scenario. 

Todo:
[ ] Unit test for this
[ ] Should we have an option for this? 
[ ] What other scenarios could cause a /login request and you're already logged in?

2019-11-05 13:21 UTC, marefr requested changes
It's a simple solution, but would suggest putting some more effort into it.

Regarding option/setting to enable this - definitely yes. I don't want to risk as a first step breaking installations due to this.

To me it would make sense to have a specific url like /auth-proxy-login instead of /login to move everything auth proxy related into that. However then we would have to add logic to disable the normal login page and custom redirect rule.

Questions:
Should something happen when auth token is rotated? 
What about using auth proxy and ldap?
What happens when logging out? User redirected to login page and gets logged in again - possible redirect loop problem?

2019-11-05 13:21 UTC, marefr commented on pkg/api/login.go
> +	if c.IsSignedIn {
Need to verify that auth proxy is enabled. Would be nice to extract this in similar manner as `tryOAuthAutoLogin`.

2019-11-05 13:21 UTC, marefr commented on pkg/api/login.go
> +		if redirectTo, _ := url.QueryUnescape(c.GetCookie("redirect_to")); len(redirectTo) > 0 {
Think this code should still execute last in this method always when logged in and by that having old `if !c.IsSignedIn {` code block before auth proxy enabled and token login. 

Like this:
- Not logged in? Return login page
  - What to do here if auth proxy is enabled? We don't want to render the login form/page right.
- Auth proxy enabled? Auth token login
- Redirect logic

2019-11-07 12:53 UTC, marefr requested changes
Works as expected :+1: Some documentation/descriptions left to make this feature understandable, see comments.

2019-11-07 12:53 UTC, marefr commented on conf/defaults.ini
> +grant_login_token = false
Not sure about "grant". How about `enable_login_tokens`?

2019-11-07 12:53 UTC, marefr commented on conf/sample.ini
> +# If you want to combine auth proxy with the normal login session token & cookie enable setting defined below.
```suggestion
# If you want to combine auth proxy with Grafana login token stored in cookie you can enable setting defined below.
```

2019-11-07 12:53 UTC, marefr commented on conf/sample.ini
> +# It will grant a login token if you supply auth proxy headers on /login request
Shouldn't this read if you only provide auth proxy headers for the /login request? Quite hard to explain all of the details in a couple of lines here. Maybe reference to check documentation instead or/and?

2019-11-07 12:53 UTC, marefr commented on devenv/docker/blocks/nginx_proxy/nginx_login_only.conf
> +events { worker_connections 1024; }
Would be good to add this to documentation as an example.

2019-11-07 12:53 UTC, marefr commented on docs/sources/auth/auth-proxy.md
> +# It will grant a login token if you supply auth proxy headers on /login request
Same comment as in default.ini/sample.ini

2019-11-07 12:53 UTC, marefr commented on docs/sources/auth/auth-proxy.md
> +## Login token & session cookie
```suggestion
## Login token and session cookie
```

2019-11-07 12:53 UTC, marefr commented on docs/sources/auth/auth-proxy.md
> +user (and redirect user). This means that only /login route needs to go through auth proxy. Use settings `login_maximum_inactive_lifetime_days`
Should explain something along the lines: In this setup the auth proxy is responsible for authenticating the user, but Grafana will keep track of the session and keep the user logged in why the auth proxy only needs to provide headers for the /login route. 

Would be good to link to `[Login and short-lived tokens](/auth/overview/#login-and-short-lived-tokens) which has all the details about it.

2019-11-07 14:21 UTC, marefr requested changes
Great. Just minor suggestions/comment left

2019-11-07 14:21 UTC, marefr commented on docs/sources/auth/auth-proxy.md
> +a login token & cookie. You only have to configure your auth proxy to provide headers for the /login route.
```suggestion
a login token and cookie. You only have to configure your auth proxy to provide headers for the /login route. 
```

2019-11-07 14:21 UTC, marefr commented on pkg/setting/setting.go
> +	AuthProxyEnableLoginToken = authProxy.Key("enable_login_token").MustBool(true)
```suggestion
	AuthProxyEnableLoginToken = authProxy.Key("enable_login_token").MustBool(false)
```

2019-11-07 14:21 UTC, marefr commented on pkg/setting/setting.go
> +	AuthProxyLDAPSyncTtl = authProxy.Key("ldap_sync_ttl").MustInt()
What did this come from?

2019-11-07 14:28 UTC, marefr requested changes
Last suggestions

2019-11-07 14:28 UTC, marefr commented on pkg/api/login_test.go
> +	setting.AuthProxyGrantLoginToken = grantLoginToken
```suggestion
	setting.AuthProxyEnableLoginToken = enableLoginToken
```

2019-11-07 14:28 UTC, marefr commented on pkg/api/login_test.go
> +func setupAuthProxyLoginTest(grantLoginToken bool) *scenarioContext {
```suggestion
func setupAuthProxyLoginTest(enableLoginToken bool) *scenarioContext {
```

2019-11-07 14:28 UTC, marefr commented on pkg/api/login.go
> +		// Assign login token to auth proxy users if grant_login_token = true
```suggestion
		// Assign login token to auth proxy users if enable_login_token = true
```

2019-11-07 16:20 UTC, marefr approved these changes
LGTM

2019-11-07 16:48 UTC, merged

2019-11-10 13:09 UTC, gershongad commented
@ torkelo do we need to upgrade grafana (currently we are using 6.2.5) in order to overcome the problem ?
could you please attach the needed nginx and grafana configuration in detail

2019-11-10 13:55 UTC, torkelo commented
Yes, this feature requires Grafana v6.5 

example nginx config:
https://github.com/grafana/grafana/blob/master/devenv/docker/blocks/nginx_proxy/nginx_login_only.conf#L31

2019-11-10 15:44 UTC, gershongad commented
@torkelo 
Thank you very much for your quick respond,
a. The latest version at grafana site is 6.4.4. Please advise  how to get version 6.5
b. Please advise how to upgrade (we are running centos 7.0)

2019-11-11 08:22 UTC, torkelo commented
6.5 is not released yet, beta out this week.

You find nightly builds of 6.5 on Grafana.com

2019-11-27 14:05 UTC, duylong commented
Great feature, but how to for alert rules ? I must, each times, use another datasource with a user for basic auth?

2019-11-27 15:35 UTC, marefr commented
@duylong not exactly sure what you're referring to. Sounds like you want to put same auth proxy in front of datasource.

2019-11-27 16:05 UTC, duylong commented
Sorry for my lack of precision.
Now, I can pass the authentication to our CAS system to access the data (maybe nothing to do with this feature). Before, I had to set up a common user (using the BasicAuth option). After a little test, I notice that I still have to keep this mechanism because the alerts need it (normal, they do not have an authentication session).

2019-12-11 13:24 UTC, gershongad commented
@torkelo As we need to integrate grafana in our web site, without asking the user to re-type a password, we want to skip the nginx basic auth username & password dialog. We want to pass the username & password as parameters of the url, or some other solution, so that the user will not have to retype his username & password. Is it possible, and could you please direct us for some php/c etc. code example

2019-12-11 13:47 UTC, torkelo commented
Url is not supported, HTTP header is

2019-12-11 14:20 UTC, gershongad commented
@torkelo sorry but i do not understand the process, should i display an href like http://user:password@server/grafana/login ??? when i enter such a url to the browser navigation bar it does not reach the destination, or should i generate a curl call from a cgi running on my server, what will be the response for such a curl call ??? i want my users be able to view grafana dashboards. please advise.

2019-12-11 14:22 UTC, torkelo commented
you need an nginx proxy that handles the single sign on with your auth system, that proxy can add the required headers for grafana

2019-12-11 15:00 UTC, gershongad commented
@torkelo We are already using the nginx proxy, but as i have mentioned the nginx basic auth pops a username & password dialog. We want to be able to skip this dialog

2019-12-11 15:15 UTC, torkelo commented
ok, well you have to use some other auth mechanism with nginx then, if you use auth proxy Grafana is not involved in the auth

2019-12-12 13:52 UTC, gershongad commented
@torkelo i am trying to use the secure_link nginx auth, but then grafana comes back without a session cookie so that the user is being thrown from his session login. i thought grafana 6.5 should overcome this issue. Please advise

2019-12-12 13:58 UTC, gershongad commented
@torkelo i have also tried proxy_set_header Authorization base64(user:password). in case it is hard coded in the nginx.conf file like proxy_set_header Authorization "Basic YWRtaW46VhN12Ud1a284MQ==" it works fine, but when i pass the "YWRtaW46VhN12Ud1a284MQ==" as a url parameter, grafana will come back without a cookie

2019-12-12 18:32 UTC, sfitts commented
We proxy access to Grafana through our server since it is where we maintain identities.  Conceptually however is it very similar.  We proxy grafana at `/grafana/`.  When we see `/grafana/login` we determine who the user is and add the appropriate header for Grafana.  At that point Grafana replies with a `FOUND` redirect to `/grafana/`.  Pre-6.x this reply also included the session cookie which the browser would then attach to all subsequent requests.  For any URI that isn't `/grafana/login` we just pass the request directly from the browser to Grafana and since it has the session cookie on it, Grafana knew who the user was (we don't add the header in those cases).

However, at this point, running 6.5.2 things aren't working.  The first part is the same, we proxy login, add the header and get the redirect.  However, there is no cookie (which I guess is intentional) and I don't see anything in the redirect which is going to help Grafana maintain the user's identity on subsequent requests.  I assumed that this fix was going to provide that, so clearly I'm missing something.

At this point, how is this supposed to work?  Assuming the header is only added to the `/login` request, how is the identity established for all subsequent requests?  TIA for any guidance.

2019-12-12 18:55 UTC, sfitts commented
OK -- found our issue.  We need to set `enable_login_token` to `true`.

2019-12-13 09:10 UTC, gershongad commented
@sfitts could you please attach the nginx.conf & grafana.ini files that you are using ?

2019-12-13 15:10 UTC, sfitts commented
As I mentioned, we're not using Nginx (we proxy the requests through a proprietary server).  However, the nginx config provided by @torkelo is equivalent to what we are doing.  The relevant section of the grafana.ini looks like:

```ini
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = false
enable_login_token = true
```

2019-12-15 13:01 UTC, gershongad commented
@sfitts i works, but i want to skip the username & password pop up, since the user already authenticated in my site. Do you know any way this can be achived ?

2019-12-15 17:58 UTC, sfitts commented
Unfortunately I'm not really an Nginx expert (since we don't use it), so I'm not sure.

2019-12-16 15:36 UTC, gershongad commented
@torkelo we like grafana very much, but we can't imagine that our users will have to go through a authentication process to view a grafana board, since they have been already authenticated when logged in to our web site. As i understand the nginx basic auth mechanism saves something like a cookie after the user has entered name & password, and in the next accesses the $remote_user is set to the user-name identified by the cookie. Is there another nginx authentication method which works in a similar way, we want to pass somehow the name&password as parameters (might be encrypted) to the grafana/login and imitate the NGINX basic auth mechanism without poping the auth dialog. Is it possible ? maybe we need to write some callback program that will imitate the basic auth mechanism. Please advise in details how this should be done, i think it is needed by many enthusiastic grafana developers.

2020-02-10 11:44 UTC, aknuds1 commented
@gershongad Don't have an answer for your question, but have you tried asking in the [Grafana community](https://community.grafana.com/)?