6.5.0-beta1 Changelog
grafana/grafana pull request #20350
Opened 2019-11-13 10:49 UTC by sunker

2019-11-13 11:04 UTC, aknuds1 approved these changes
Looks good AFAICT, apart from a formatting nit.

2019-11-13 11:05 UTC, marefr requested changes
Please wait with the merge

2019-11-13 11:22 UTC, sunker commented on CHANGELOG.md
> +
Yes!

2019-11-13 11:27 UTC, aknuds1 commented on CHANGELOG.md
> +
Thanks @sunker :)

2019-11-13 11:46 UTC, sunker commented on CHANGELOG.md
> +
Thank you! :)

2019-11-14 08:15 UTC, daniellee commented on CHANGELOG.md
> +##  ing changes
This doesn't look right

2019-11-14 08:19 UTC, daniellee commented on CHANGELOG.md
> +* **CloudWatch**: In previous versions of Grafana, there were partial support for using multi template variables as dimension values. When a multi template variables is being used for dimension value
- "there was partial support" - replace was with were
- "When a multi template variable" - drop the s

2019-11-14 09:07 UTC, daniellee approved these changes
LGTM

2019-11-14 10:28 UTC, marefr approved these changes
LGTM

2019-11-14 10:57 UTC, merged