DevEnv: updates nodejs from 10.x to 12.x and golang to 1.13 in ci-deploy dockerfile.
grafana/grafana pull request #20405
Opened 2019-11-15 08:27 UTC by Estrax

**What this PR does / why we need it**:

Updates nodejs from 10.x to the new LTS, version 12.x. Also, updates golang from 1.11 to 1.13 in ci-deploy dockerfile.

**Which issue(s) this PR fixes**:

Fixes #19668

2019-11-15 08:28 UTC, Estrax commented
cc @marefr @hugohaggmark @dprokop

2019-11-15 08:30 UTC, hugohaggmark commented
@Estrax great work, did the pre-commit hook work? And was it any help?

2019-11-15 08:34 UTC, Estrax commented
@hugohaggmark yep, worked flawlessly after reinstalling dependencies under node 12.x.
![Screenshot](https://user-images.githubusercontent.com/6322797/68928742-20c74400-078b-11ea-84b4-ccf59e1efbdf.png)

2019-11-15 08:45 UTC, hugohaggmark commented
> @hugohaggmark yep, worked flawlessly after reinstalling dependencies under node 12.x.
> ![Screenshot](https://user-images.githubusercontent.com/6322797/68928742-20c74400-078b-11ea-84b4-ccf59e1efbdf.png)

Awesome, did you change in https://github.com/grafana/grafana-build-container as well?

2019-11-15 08:50 UTC, Estrax commented
@hugohaggmark no, because based on its readme it has been moved to the core Grafana repo; so I updated https://github.com/grafana/grafana/tree/master/scripts/build/ci-build instead.

2019-11-15 08:52 UTC, hugohaggmark commented
> @hugohaggmark no, because based on its readme it has been moved to the core Grafana repo; so I updated https://github.com/grafana/grafana/tree/master/scripts/build/ci-build instead.

Ok cool, can you update the comment in the pre-commit hook then to be up to date?

2019-11-15 08:53 UTC, dprokop commented
@Estrax also fixes #20302

2019-11-15 08:59 UTC, dprokop commented
@Estrax seems like the build is failing, I think build-container image needs to be updated as well as @hugohaggmark mentioned

2019-11-15 09:01 UTC, aknuds1 approved these changes
LGTM, once the build is fixed.

2019-11-15 09:10 UTC, Estrax commented
@hugohaggmark Grafana build container updated.

2019-11-15 09:23 UTC, marefr requested changes
Looks good, but need to build and push docker images to docker hub so that we can utilize new versions when building/releasing Grafana in circleci. See comments for details. 

I think after this one is done there's also some changes needed in the enterprise repo. 

Let us know if you need help with building/pushing to docker hub or anything else.

2019-11-15 09:23 UTC, marefr commented on scripts/build/ci-build/Dockerfile
> +ENV GOVERSION=1.13.4 \
Due to changes in this file you'll need to update/increment buildcontainer version and push to docker hub, see https://github.com/grafana/grafana/blob/master/scripts/build/ci-build/build-deploy.sh circleci. When that's done you want to update all references to grafana/build-container in the repository.

2019-11-15 09:23 UTC, marefr commented on scripts/build/ci-deploy/Dockerfile
> +FROM circleci/golang:1.13
Due to changes in this file you'll need to update/increment  version and push to docker hub, see .https://github.com/grafana/grafana/blob/master/scripts/build/ci-deploy/build-deploy.sh When that's done you want to update all references to grafana/grafana-ci-deploy in the repository.

2019-11-15 09:26 UTC, marefr commented
Missed the earlier comments about build container and failing builds. I'll create an issue to track go upgrade to 1.13.4

2019-11-15 11:35 UTC, Estrax commented
@marefr updated references to `grafana/grafana-ci-build` and `grafana/grafana-ci-deploy`, however I have some issues with building those two images, looks like C++ stdlib panics.

2019-11-15 13:08 UTC, aknuds1 commented
I can't even build the grafana/build-container Docker image on master branch, due to compilation failure for the osxcross dependency. I wonder what changed :/

2019-11-15 14:56 UTC, marefr commented
Added #20413 to PR description

2019-11-18 15:27 UTC, aknuds1 commented
I've upgraded the grafana/build-container Docker image to Ubuntu 18.04 now, and also Go 1.13.4, pushed it as v1.2.12.

2019-11-20 20:02 UTC, marefr commented
@Estrax think you need to update this to get a successful build:
https://github.com/grafana/grafana/blob/2079386a7d15b572bcb7fff272f24002eab88bb5/package.json#L278

2019-11-20 20:06 UTC, Estrax commented
@marefr I think I already updated it: https://github.com/grafana/grafana/pull/20405/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

2019-11-20 20:14 UTC, marefr commented
@Estrax I see. Okay so a new build container version needs to be built and pushed to docker hub now when fixed in master and you've merged that in. Let us know if you want me or @aknuds1 to help out with this.

2019-11-20 22:52 UTC, Estrax commented
@marefr @aknuds1 built a new container and pushed it as v1.2.13.

2019-11-21 08:32 UTC, aknuds1 approved these changes
LGTM!

2019-11-21 09:52 UTC, marefr approved these changes
LGTM

2019-11-21 09:59 UTC, marefr commented
Added an issue to upgrade go in enterprise https://github.com/grafana/grafana-enterprise/issues/298

2019-11-21 14:16 UTC, merged

2019-11-24 17:43 UTC, marefr commented
Moved this to 6.6 milestone