Forms: TextArea component
grafana/grafana pull request #20484
Opened 2019-11-19 15:51 UTC by peterholmberg

**What this PR does / why we need it**:
Adds a TextArea component

**Which issue(s) this PR fixes**:
Fixes #20265 

**Special notes for your reviewer**:

2019-11-21 07:55 UTC, dprokop requested changes

2019-11-21 07:55 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/commonStyles.ts
> +  const backgroundColor = selectThemeVariant({ light: colors.white, dark: colors.gray15 }, theme.type);
Use `formInputBg` variable pls

2019-11-21 07:55 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/commonStyles.ts
> +      background-color: ${selectThemeVariant({ light: colors.gray6, dark: colors.gray10 }, theme.type)};
Use `formInputBgDisabled` variable pls

2019-11-21 07:55 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/commonStyles.ts
> +      color: ${selectThemeVariant({ light: colors.gray33, dark: colors.gray70 }, theme.type)};
Introduce new variable for this pls

2019-11-21 07:57 UTC, dprokop commented
Couple of nits, haven't run that yet. Btw `packages/grafana-ui/src/components/Forms/TextArea/TextArea.mdx` is empty, is that on purpose?

2019-11-21 07:59 UTC, peterholmberg commented on packages/grafana-ui/src/components/Forms/commonStyles.ts
> +      color: ${selectThemeVariant({ light: colors.gray33, dark: colors.gray70 }, theme.type)};
:man_facepalming:

2019-11-22 16:09 UTC, dprokop commented
@peterholmberg really sorry about late review:( 

So I have tested it and it seems like all working fine! Few notes about improvements I'm thinking about:

- Let's introduce sizing classes, similar to the one's I have introduced to Input in https://github.com/grafana/grafana/pull/20482 (sm, md,lg, auto)
- Let's sync this with input styling updates (focus primarily) introduced in https://github.com/grafana/grafana/pull/20482 . I aim to merge it on monday
- I'm thinking about auto-growing textarea that you can specify axis on which it should grow. I.e. `<Textarea grow="width|height|both" />`. It would disable the resize option on textarea and let it grow  until it reaches container's boundary. This is a nice-to-have thing, could be useful i.e in Http settings for pasting the certificates, or in sidebar panel editor where we probably want the textareas to be as small as possible when rendered. WDYT about this idea @jessover9000 @torkelo

2019-11-26 13:03 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Form.story.tsx
>                // onChange={e => setPassword(e.currentTarget.value)}
```suggestion
```

2019-11-26 13:05 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/TextArea/TextArea.tsx
> +        border: 1px solid ${borderColor};
I think we can have this in the shared input styles.

2019-11-26 13:06 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/TextArea/TextArea.tsx
> +    : selectThemeVariant({ light: colors.gray4, dark: colors.gray25 }, theme.type);
formInputBorder variables please :)

2019-11-26 13:07 UTC, dprokop approved these changes
This is looking good now :) Some nits I left comments about

2019-11-27 07:30 UTC, merged