<variables>: Add new global built-in variables
grafana/grafana pull request #20533
Opened 2019-11-20 17:59 UTC by dcastanier

**What this PR does / why we need it**:
It's an implementation of 'Add new global built-in variables #20523'

**Which issue(s) this PR fixes**:
Fixes #20523

**Special notes for your reviewer**:

2019-11-22 09:51 UTC, torkelo requested changes
Not sure I like the new time range variables. Think we can solve that with new formatting options

example: ${__from:datetime}

2019-11-22 14:45 UTC, dcastanier commented
Ok with your proposition, new version available

2019-11-22 14:47 UTC, torkelo commented
The ideas discussed here https://github.com/grafana/grafana/issues/15903 is also relevant here, need to think a bit more about this

2019-11-28 12:40 UTC, dcastanier commented
Any news about this PR ?

2019-12-03 11:54 UTC, torkelo requested changes
Think this looks ok, just one minor issue

2019-12-03 11:54 UTC, torkelo commented on public/app/features/templating/variable_srv.ts
> +        }
you do not need to do this, you can just import contextSrv

2019-12-17 17:49 UTC, dcastanier commented
Any news about this PR ?

2020-01-02 08:14 UTC, dcastanier commented
Minor update are done like requested a month ago. 
Stale tag scary me, someone could review it for merge ?
Thanks

2020-01-02 11:54 UTC, torkelo commented
Sorry, it needs a bit of a refactor (not sure how exactly) and have. It had time yet

2020-01-02 12:44 UTC, dcastanier commented
Thanks Torkelo, let me know if I can help

2020-01-16 13:28 UTC, torkelo commented
not stale!

2020-01-20 17:08 UTC, dcastanier commented
Hello Torkel, 
I have a production deployment that need this feature for end of February. 
Do you think it's possible to have a release with this PR ?

2020-01-21 14:58 UTC, dprokop commented
@dcastanier had a chance to talk with @torkelo today about this. We decided that for variable naming we would like to use the dot notation as we do with data links for example. So, `__dashboardName` would become `__dashboard.name`, and `__orgName` -> `__org.name`. This PR from @torkelo enables support for dot notation in template variables https://github.com/grafana/grafana/pull/21634

2020-01-22 09:57 UTC, dcastanier commented
Thanks for your feedback Dominik, look on the good way for `$__dashboard.name` and `$__org.name`.
For date in text format, you think to keep formatting approach like `${__from:datetime}` or use the dot notation like `$__from.text` or `$__from.format` ?

2020-01-23 08:04 UTC, dprokop commented
@dcastanier I think `__from.text` is fine. WDYT @torkelo ?

2020-01-23 11:05 UTC, dcastanier commented
I have updated this PR to follow the new dot format.
Sorry, I see that merge from trunk as drain a lot of things, I don't know how to remove it.

2020-01-23 13:54 UTC, dcastanier commented
To resolve the merge issue, I just recreate a new PR #20523, so I close this one.

2020-01-23 13:54 UTC, closed without merging