Docs: 6.5 update
grafana/grafana pull request #20617
Opened 2019-11-24 15:44 UTC by marefr

**What this PR does / why we need it**:
- Updates index page to point at What's new in 6.5
- Updates What's new in 6.5 article

2019-11-24 16:01 UTC, RichiH reviewed
Teeny-tiny change.

2019-11-25 08:38 UTC, aknuds1 requested changes
Spotted a couple of language niggles.

2019-11-25 08:38 UTC, aknuds1 commented on docs/sources/guides/whats-new-in-v6-5.md
> +Historically it has been possible to make changes to a provisioned dashboard in the Grafana UI. However, it hasn't been possible to save the changes without manual intervention. In Grafana 6.5 we int
s/Save the dashboard/save the dashboard/

2019-11-25 08:38 UTC, aknuds1 commented on docs/sources/guides/whats-new-in-v6-5.md
> +Since we announced the deprecation of PhantomJS and new [Image Renderer Plugin](https://grafana.com/grafana/plugins/grafana-image-renderer) in Grafana [6.4](/guides/whats-new-in-v6-4/#phantomjs-depre
"and the new [Image Renderer Plugin](https://grafana.com/grafana/plugins/grafana-image-renderer)"

2019-11-25 08:47 UTC, aknuds1 approved these changes
LGTM

2019-11-25 10:54 UTC, merged