support alert tags in OpsGenie notifier
grafana/grafana pull request #20810
Opened 2019-12-02 16:45 UTC by aSapien

**What this PR does / why we need it**:
Adds alert tags support to OpsGenie notifier

**Which issue(s) this PR fixes**:
Fixes #20796 

**Special notes for your reviewer**:

2019-12-02 22:16 UTC, torkelo approved these changes

2019-12-02 22:16 UTC, torkelo requested changes
Need to fix build (lint) failures

2019-12-03 08:44 UTC, aSapien commented
@torkelo lint fixed :)

2019-12-03 10:54 UTC, torkelo approved these changes

2019-12-03 10:54 UTC, merged