Forms/select
grafana/grafana pull request #21092
Opened 2019-12-13 16:27 UTC by dprokop

TODO:
- [ ] to do...

2019-12-13 16:31 UTC, dprokop commented on packages/grafana-ui/package.json
> +    "@types/react-select": "^2.0.15",
Needs fixing

2019-12-13 16:31 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.tsx
> +        Control: getControlComponent(prefix, disabled, invalid, renderControl),
Control element can be customised with `renderControl` prop

2019-12-13 16:31 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.tsx
> +        Control: getControlComponent(prefix, disabled, invalid, renderControl),
Control element can be customised with `renderControl` prop

2019-12-13 16:36 UTC, dprokop commented on packages/grafana-ui/src/components/Select/Select.tsx
> +type LegacyCommonProps<T> = Omit<SelectCommonProps<T>, 'noOptionsMessage' | 'disabled'>;
Old select uses the same interface as the new one. But there are minor changes in the new Select interface, so I'm making sure nothing breaks in the old select

2019-12-13 20:32 UTC, torkelo reviewed
This is looking great! and looks like a lot of work, not strange that this took a few days!

2019-12-19 15:06 UTC, peterholmberg reviewed
What is the need to have Forms components with forwardRef type?

2019-12-20 14:03 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +  console.log('SELECT MENU', props);
```suggestion
```

2019-12-20 14:04 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +    console.log('menu options', innerProps);
```suggestion
```

2019-12-20 14:04 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.story.tsx
> +          console.log(v);
```suggestion
```

2019-12-20 14:04 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.story.tsx
> +        console.log(v);
```suggestion
```

2019-12-20 15:39 UTC, torkelo approved these changes
Did some testing to make sure there are no regressions and found none! 

Great job on this one!

2020-01-02 14:19 UTC, peterholmberg requested changes
Left some comments and questions.

2020-01-02 14:19 UTC, peterholmberg commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +  // @ts-ignore
And this ts-ignore?

2020-01-02 14:19 UTC, peterholmberg commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +// @ts-ignore
and this?

2020-01-02 14:49 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.tsx
> +  // @ts-ignore
MultiSelect onChange property is different (accepts array) than SelectBase. It's overridden in the MultiSelectCommonProps type, but the base type of SelectBase still has the onChange definition for a single select. Hence the ts-ignore

2020-01-02 14:54 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +  // @ts-ignore
innerRef is not typed, I'll fix it

2020-01-02 14:56 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/SelectMenu.tsx
> +// @ts-ignore
to be removed

2020-01-02 14:56 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/Select.story.tsx
> +  // },
It's by default

2020-01-02 14:56 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Select/SelectBase.tsx
> +import { default as ReactSelect, Creatable, components } from '@torkelo/react-select';
yes

2020-01-02 14:56 UTC, dprokop commented on packages/grafana-ui/src/components/Forms/Button.story.tsx
> +
yes

2020-01-02 16:18 UTC, ryantxu commented
Not sure this is the right PR/place... the other feature on select that would be great is changing the order of multi-select tags.  See:
https://react-select.com/advanced

2020-01-03 10:47 UTC, peterholmberg commented on packages/grafana-ui/src/components/Forms/Select/Select.tsx
> +  // @ts-ignore
Ok

2020-01-03 10:53 UTC, peterholmberg approved these changes
Looks good now! :D

2020-01-07 08:20 UTC, merged

2020-01-13 14:45 UTC, alexanderzobnin commented on packages/grafana-ui/src/components/Button/Button.tsx
> -    <button className={cx(styles.button, className)} {...buttonProps}>
`className` isn't passed into the button anymore. Is it a bug or feature?