SQL: define primary key for tables without it
grafana/grafana pull request #21387
Opened 2020-01-07 16:18 UTC by azhiltsov

The annotation_tag and alert_rule_tag tables did not have
PRIMARY KEY defined what cause problems with migration to
MariaDB with Galera setup with
 innodb_force_primary_key=1
Or MySQL > 8.0.13 with
 sql_require_primary_key=ON

Which can manifest as follows:

MariaDB
Error 1173: This table type requires a primary key

MySQL
ERROR 3750 (HY000): Unable to create or change a table
without a primary key, when the system variable 'sql_require_primary_key' is set.

Extra reading for curious:
https://jfg-mysql.blogspot.com/2017/08/danger-no-pk-with-RBR-and-mariadb-protection.html

Fixes #12971

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-01-07 16:18 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21387) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=21387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=21387) it.</sub>

2020-01-10 11:08 UTC, marefr requested changes
This will not work when affected tables have existing data. More migrations needed to handle that.

2020-01-10 14:27 UTC, azhiltsov commented
When I am doing this on the existing table manually it works for me. 
```
mysql> alter table annotation_tag add column `id` bigint(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;
Query OK, 0 rows affected, 1 warning (0.12 sec)

mysql> desc annotation_tag
    -> ;
+---------------+------------+------+-----+---------+----------------+
| Field         | Type       | Null | Key | Default | Extra          |
+---------------+------------+------+-----+---------+----------------+
| annotation_id | bigint(20) | NO   | MUL | NULL    |                |
| tag_id        | bigint(20) | NO   |     | NULL    |                |
| id            | bigint(20) | NO   | PRI | NULL    | auto_increment |
+---------------+------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)
```

2020-01-10 14:29 UTC, marefr commented
@azhiltsov but do you have existing data/rows stored in annotation_tag?

2020-01-10 14:30 UTC, marefr commented
sqlite, postgres and mysql integration tests failing with "encrypt_datasource_passwords_test.go:16: Failed to init test database: Migration failed err: Failed to roll back transaction due to error: %!s(<nil>): Cannot add a NOT NULL column with default value NULL"

2020-01-10 14:35 UTC, marefr commented
Some additional context from earlier PR that was closed #12970

2020-01-10 14:53 UTC, azhiltsov commented
yeah. there is some:
```
mysql> select count(*) from annotation_tag;
+----------+
| count(*) |
+----------+
|      240 |
+----------+
1 row in set (0.00 sec)
```

2020-01-29 15:12 UTC, marefr commented
@azhiltsov our integration tests doesn't lie. Planning to pick this up soon, otherwise we'll close it since we're trying to keep PR's open that are in progress.

2020-02-17 16:22 UTC, closed without merging