Docs: document jaeger tracing instrumentation
grafana/grafana pull request #21392
Opened 2020-01-07 21:09 UTC by Dieterbe

jaeger instrumentation was introduced in https://github.com/grafana/grafana/pull/9213 but it was not documented yet apparently :?
I didn't run any tests!

2020-01-08 20:07 UTC, oddlittlebird requested changes
This is a good start, but it is a bit abrupt. As a user, I have questions.

**Why do I care about this?** Okay, if I use Jaeger, I guess I care. But if I don't know what Jaeger is? Perhaps give a sentence or two so the reader can get some context and decide if they want to know more.

**How do I do this?** I infer that the user needs to update grafana.ini, but you also mention API endpoints and output. 

So, here's what this should have:
Concept - Explain what you are talking about. Introduction. 
Task - What tasks is the user going to do? Enable Jaeger tracing? View trace results? These should be step-by-step instructions.
Reference - If applicable, this would be things like a list of API endpoints, buttons or fields on a panel in a reference table, defined terms, and so on.

2020-01-08 20:07 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +Grafana supports [jaeger tracing](https://www.jaegertracing.io/).
```suggestion
Grafana supports [Jaeger tracing](https://www.jaegertracing.io/).
```

2020-01-08 20:07 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +Grafana can emit jaeger traces for its http api endpoints as well as propagate jaeger trace information to datasources.
```suggestion
Grafana can emit Jaeger traces for its HTTP API endpoints and propagate Jaeger trace information to data sources. 
```

2020-01-08 20:07 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +Grafana can emit jaeger traces for its http api endpoints as well as propagate jaeger trace information to datasources.
Unclear if "its HTTP API endpoints" are Grafana's or Jaeger's. Please clarify.

2020-01-08 20:07 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +All HTTP endpoints are logged evenly. (annotations, dashboard, tags, etc)
```suggestion
All HTTP endpoints are logged evenly (annotations, dashboard, tags, and so on).
```

2020-01-08 20:07 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +Jaeger tracing is enabled in the [tracing.jaeger] section in your [grafana.ini](https://grafana.com/docs/grafana/latest/installation/configuration/#tracing-jaeger) config file.
```suggestion
Refer to [Configuration](https://grafana.com/docs/grafana/latest/installation/configuration/#tracing-jaeger) for information about enabling Jaeger tracing.
```

2020-01-08 20:08 UTC, oddlittlebird commented on docs/sources/administration/jaeger-instrumentation.md
> +# Jaeger instrumentation
When we get a better handle on the final shape of the documentation, we should revisit this title. I suspect we can come up with something more descriptive and accurate.

2020-01-09 09:01 UTC, Dieterbe commented
Can someone on the Grafana team continue this work ?

2020-01-09 20:41 UTC, oddlittlebird commented
@daniellee, see question from @Dieterbe

2020-01-10 10:01 UTC, marefr commented
Think zipkin is supported as well when configured using zipkin propagation format, https://grafana.com/docs/grafana/latest/installation/configuration/#zipkin-propagation

2020-01-20 08:24 UTC, bergquist commented
Yea we should rename this tracing support instead even thou only the jaeger client is implemented.

2020-03-13 08:37 UTC, Dieterbe commented
Don't let perfect be the enemy of good.
We have something, let's get it merged. We can always improve later.

2020-05-22 07:45 UTC, Dieterbe commented
@daniellee said he'd take care of this :)

2020-06-08 08:42 UTC, Dieterbe commented
this is starting to get painful. :'(

2020-07-09 16:46 UTC, Dieterbe commented
:hourglass: :hourglass: :hourglass: :hourglass: 

> Don't let perfect be the enemy of good.
> We have something, let's get it merged. We can always improve later.

2020-07-09 16:56 UTC, oddlittlebird approved these changes

2020-07-13 15:09 UTC, merged