ApiUser: Fix returned message when enabling,disabling and deleting a non-existing user
grafana/grafana pull request #21391
Opened 2020-01-07 18:41 UTC by dpavlos

**What this PR does / why we need it**:
- Fixes #19988
- Applies the same logic for DELETE /api/admin/users/:id call
- Adds unit tests for the case described in #19988 as well as for the delete user scenario

2020-01-09 17:41 UTC, aknuds1 requested changes
Generally looks good to me, but there are some changes I'd like to see.

2020-01-09 17:41 UTC, aknuds1 commented on pkg/api/admin_users_test.go
> +		userId := int64(0)
```suggestion
		var userId int64
```

2020-01-09 17:41 UTC, aknuds1 commented on pkg/services/sqlstore/user.go
> +
```suggestion
```

2020-01-09 17:41 UTC, aknuds1 commented on pkg/services/sqlstore/user.go
> +	} else if !has {
More idiomatic I think:
```suggestion
	}
	if !has {
```

2020-01-09 22:43 UTC, dpavlos commented
Thanks @aknuds1 for reviewing this. Do you prefer the suggested changes in one batch? I can squash the commits before merging this.

2020-01-10 08:37 UTC, aknuds1 commented
@dpavlos We squash when we merge so it isn't necessary :)

2020-01-10 08:54 UTC, aknuds1 approved these changes
LGTM

2020-01-10 09:06 UTC, marefr approved these changes
LGTM

2020-01-10 10:43 UTC, merged

2020-01-10 10:43 UTC, aknuds1 commented
Merged! Thanks very much for contributing to Grafana!