cloudwatch: Replicate SDK behaviour for WebIdentityRole
grafana/grafana pull request #21594
Opened 2020-01-18 13:29 UTC by patstrom

**What this PR does / why we need it**:

This PR replicates (most of) the behavior of `aws-sdk-go` when fetching a WebIdentityRole such as they are used in IAM roles for service account in EKS.

The reason for the "(most of)" qualifier is that this will only read the environment variables, so if e.g a `role_session_name` is configured in a configuration file somewhere it won't be picked up. I suspect this won't be much of a problem since all documentation and whatnot for EKS IAM roles for Service Accounts exclusively uses those environment variables.

As discussed in the issue the "proper" way to fix this would probably be to always use the default credentials chain unless a specific way is specified in which case *only* that way should be used.

I've tried this out in an EKS cluster with a standard setup. In other words I've created a deployment and a service account, linked them together and annotated the service account with `eks.amazonaws.com/role-arn` and I can confirm it manages to find the credentials.

**Which issue(s) this PR fixes**:

Fix #20473

2020-01-18 14:50 UTC, patstrom commented
I realized this change is probably needed in the s3uploader for images as well. Perhaps the AWS configuration should be centralized into a single pkg that both the cloudwatch executor, the image uploader and any potential future interactions can re-use?

2020-01-30 08:57 UTC, aknuds1 requested changes
I made a couple of suggestions for minor improvements. I'll see if I can test this in order to reproduce the issue.

2020-01-30 10:25 UTC, aknuds1 commented
Thanks for applying my suggestions, I'm just waiting to get access to an EKS cluster so I can test.

2020-02-01 08:41 UTC, evq commented on pkg/tsdb/cloudwatch/credentials.go
> +			webIdentityProvider(sess),
May also want `webIdentityProvider(stsSess)` below  https://github.com/grafana/grafana/blob/a78387fdc2176fe7a114958bcac91e2d4291dbf3/pkg/tsdb/cloudwatch/credentials.go#L63

2020-02-03 08:34 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21594) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=21594) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: patstrom<br/>:x: evq<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=21594) it.</sub>

2020-02-03 09:17 UTC, aknuds1 commented
Handing this over to @ryantxu since he needs to look it over too.

2020-02-10 08:52 UTC, patstrom commented
@evq you need to sign the cla.

@ryanxtu what is the status on this?

2020-02-12 17:55 UTC, evq commented
@patstrom signed

2020-02-18 13:16 UTC, iptizer commented
Is there anything I can do to speed this up a little bit? Hit me!

How I see it @aknuds1 currently has some changes requested. Can I help you testing or something?

2020-02-25 13:15 UTC, patstrom commented
I've already addressed the requested changes. Perhaps @aknuds1 needs to mark them as resolved as well?

2020-03-03 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21594) <br/>All committers have signed the CLA.

2020-03-10 13:22 UTC, aknuds1 approved these changes
LGTM, but waiting for @ryantxu's review.

2020-03-19 15:52 UTC, patstrom commented
@ryantxu What is the status on this?

2020-03-26 12:12 UTC, dnascimento commented
@ryantxu  When may you review this?

2020-04-06 18:13 UTC, chancez commented
How does this work in combination with configuring the assume role ARN for the cloudwatch datasource? Can we use the EKS service account as the source profile to assume role with the AWS IAM role specified in the datasource? I'm trying to see if once this is fixed if I can use the SA IAM role to allow assuming into a different IAM role per cloudwatch datasource so I can use a single grafana with multiple AWS accounts.

2020-04-07 03:23 UTC, dnascimento requested changes

2020-04-07 03:23 UTC, dnascimento commented on pkg/tsdb/cloudwatch/credentials.go
>  				remoteCredProvider(stsSess),
@patstromm, could you set `webIdentityProvider` before `remoteCredProvider`? It's likely that the EC2 instances have a role attached to it, so this order will prioritise the EC2 instance role over the webIdentity. It's better to try first to use the WebIdentity

2020-04-07 04:02 UTC, dnascimento commented
> How does this work in combination with configuring the assume role ARN for the cloudwatch datasource? Can we use the EKS service account as the source profile to assume role with the AWS IAM role specified in the datasource? I'm trying to see if once this is fixed if I can use the SA IAM role to allow assuming into a different IAM role per cloudwatch datasource so I can use a single grafana with multiple AWS accounts.

The EKS service account role can assume a role as well if you define the arn, the code flow is:
https://github.com/grafana/grafana/blob/42290dea178c4f721bede132be9ad2f8ba8dba81/pkg/tsdb/cloudwatch/credentials.go#L48
https://github.com/grafana/grafana/blob/42290dea178c4f721bede132be9ad2f8ba8dba81/pkg/tsdb/cloudwatch/credentials.go#L64
https://github.com/grafana/grafana/blob/42290dea178c4f721bede132be9ad2f8ba8dba81/pkg/tsdb/cloudwatch/credentials.go#L76

@patstrom I tested the code in our systems, could you address the 2 issues above so that this can be reviewed and merged?

2020-04-07 15:49 UTC, chancez commented
@dnascimento yep, I see now, looks like it should work. I'll build this locally and see if I can get it to work with multiple roles. Thanks.

2020-04-07 23:09 UTC, patstrom commented
I currently have a [WIP](https://github.com/patstrom/grafana/commit/f5ad86fc8bf17bf70eb108cf2d3ef56f7263e5c4) of the "proper" way here, where I add a `AWS SDK Default` authentication provider that does exactly what you'd expect. 

I plan to open a separate MR when it's ready (hopefully later this week).

2020-04-08 00:38 UTC, ryantxu commented
@patstrom -- the new approach looks great.  thanks for the effort

2020-04-08 12:26 UTC, aknuds1 commented
Synced your branch with Grafana master, to fix CI issues.

2020-04-08 13:05 UTC, merged

2020-04-08 13:09 UTC, aknuds1 commented
This took a while, but we finally got it merged - thank you for contributing to Grafana!

2020-04-08 14:54 UTC, patstrom commented
Cheers! :tada:

You're not getting rid of me that easily though. I just opened a [new PR](https://github.com/grafana/grafana/pull/23439) with the "proper" way to solve this that also includes some other fixes to the Cloudwatch data source executor.