Metrics: add missing objectives to summary metrics
grafana/grafana pull request #21858
Opened 2020-01-30 21:23 UTC by kogent

**What this PR does / why we need it**:
Sets the `Objectives` for summaries to the defaults previously supplied by the client library:
https://github.com/prometheus/client_golang/blob/761a2ff07c763475bff727730e823a8f4d501f36/prometheus/summary_test.go#L281
https://github.com/prometheus/client_golang/blob/761a2ff07c763475bff727730e823a8f4d501f36/prometheus/summary_test.go#L302

**Which issue(s) this PR fixes**:
Fixes #21857

**Special notes for your reviewer**:
This just restores the default objects back to the existing Summary metrics.  I think long term this would be better as histograms so that aggregating across a cluster of grafana instances would be possible.

2020-01-30 21:23 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21858) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=21858) before we can accept your contribution.<br/><hr/>**Mark Carey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=21858) it.</sub>

2020-01-31 13:54 UTC, marefr requested changes
Thanks, looks good but missing update of `http_request_duration_milliseconds`.

2020-01-31 13:55 UTC, marefr commented
Please also merge in latest master/rebase on master. Thanks

2020-01-31 18:55 UTC, kogent commented
> Thanks, looks good but missing update of `http_request_duration_milliseconds`.

Is the change on Line 131 not enough?

2020-02-01 11:29 UTC, marefr commented
@kogent sorry my bad. But if you merge with latest master you should notice that there's on metric named `LDAPUsersSyncExecutionTime` what needs update. Thanks

2020-02-05 01:27 UTC, kogent commented
i made that change yesterday. did you need anything further?

2020-02-05 10:09 UTC, marefr approved these changes
LGTM

2020-02-05 10:11 UTC, merged

2020-02-05 10:11 UTC, marefr commented
@kogent Thank you for contributing to Grafana!