Chore: Prevent login button from showing credentials in the url bar
grafana/grafana pull request #21855
Opened 2020-01-30 18:43 UTC by jrmycanady

The login buttons for the login form are of type submit. Upon click this will
submit the form to the current page and populate the URL parameters. To
prevent this the type has been changed to button which will not submit the
page.

Fixes #20719

2020-01-30 18:43 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21855) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=21855) before we can accept your contribution.<br/><hr/>**Jeremy Canady** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=21855) it.</sub>

2020-01-31 02:20 UTC, jrmycanady commented
Is it possible to get this into 6.6.1?

We consider this a large security issue due to username and passwords hitting the logs in plain text. We are currently running our own fork and would love to get off of it.

2020-01-31 08:05 UTC, daniellee requested changes
Thanks for the PR - your point about this being a security issue due to username and passwords hitting the logs in plain text is a good one. We would definitely add a fix for this issue to 6.6.1.

However, this change breaks the ability to submit the form using the keyboard as the enter key does not submit the form anymore. The user would have to tab an extra time to move the focus to the button. 

The reason for the input field values appearing in the url is that the html form is being submitted with the HTTP GET verb. A better way to solve this issue would be by adding `method="post"` to the html form tag (and keeping the button type as submit). This doesn't break the accessibility of the form and also solves the security issue.

2020-01-31 15:01 UTC, jrmycanady commented
You are totally correct. It appears I didn't replicate my change in our internal fork correctly for this pull request. Only the "Login In ..." button has the type changed to the button. For a minute I was pretty confused how our enter key was working. 

Another option would be to add disable to the "Login ..." button. 

In any case, I feel your solution is likely the best as it will prevent the form from ever sending the creds as a URL parameter. 

Would you like me to modify my pull request or simple cancel and let you guys take it from here? 

```tsx
        {!this.props.isLoggingIn ? (
            <button
              type="submit"
              aria-label={e2e.pages.Login.selectors.submit}
              className={`btn btn-large p-x-2 ${this.state.valid ? 'btn-primary' : 'btn-inverse'}`}
              onClick={this.onSubmit}
              disabled={!this.state.valid}
            >
              Log In
            </button>
          ) : (
            {/** THIS BUTTON **/}
            <button type="button" className="btn btn-large p-x-2 btn-inverse btn-loading"> 
              Logging In<span>.</span>
              <span>.</span>
              <span>.</span>
            </button>
          )}
```

2020-02-04 08:41 UTC, closed without merging

2020-02-14 12:11 UTC, daniellee commented
@jrmycanady sorry, I was too slow responding here and @tskarhed fixed it in the meantime. Thanks for reporting this and hopefully it is working better for you now.