delete redundant alias
grafana/grafana pull request #21907
Opened 2020-02-04 04:17 UTC by zhangjianweibj

fix issue: redundant alias

https://github.com/grafana/grafana/issues/21906

2020-02-04 04:18 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=21907) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=21907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=21907) it.</sub>

2020-02-04 14:43 UTC, kylebrandt requested changes
If going to change this I think we should do it everywhere, and can also be done in pkg/services/sqlstore/transactions.go ?

2020-02-04 14:55 UTC, aknuds1 requested changes
Agree with @kylebrandt that we should fix the other occurrence too. Otherwise looks good.

2020-02-05 01:21 UTC, kylebrandt approved these changes

2020-02-05 07:59 UTC, aknuds1 approved these changes
LGTM, thanks!

2020-02-05 08:00 UTC, merged