Dashboard: Fix bug with NaN in alerting
grafana/grafana pull request #22053
Opened 2020-02-09 20:57 UTC by a-melnyk

Closes #21953

**What this PR does / why we need it**: fixes issue with NaN float numbers in alerting aggregation functions (reducers)

**Which issue(s) this PR fixes**: 
Fixes #21953

2020-02-09 20:58 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22053) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=22053) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=22053) it.</sub>

2020-02-10 11:19 UTC, aknuds1 requested changes
I made some suggestions for improvement. @kylebrandt what do you think?

2020-02-10 11:19 UTC, aknuds1 commented on pkg/services/alerting/conditions/reducer.go
> +	if f.Valid && !math.IsNaN(f.Float64) {
```suggestion
	return f.Valid && !math.IsNaN(f.Float64)
```

2020-02-10 11:19 UTC, aknuds1 commented on pkg/services/alerting/conditions/reducer_test.go
> +		Convey("isValid should treat NaN as not valid", func() {
```suggestion
		Convey("isValid should treat NaN as invalid", func() {
```

2020-02-10 11:19 UTC, aknuds1 commented on pkg/services/alerting/conditions/reducer_test.go
> +		Convey("isValid should treat not vaild null.Float as not valid", func() {
```suggestion
		Convey("isValid should treat invalid null.Float as invalid", func() {
```

2020-02-10 11:19 UTC, aknuds1 commented on pkg/services/alerting/conditions/reducer_test.go
> +			So(result, ShouldEqual, false)
```suggestion
			So(result, ShouldBeFalse)
```

2020-02-10 11:19 UTC, aknuds1 commented on pkg/services/alerting/conditions/reducer_test.go
> +			So(result, ShouldEqual, false)
```suggestion
			So(result, ShouldBeFalse)
```

2020-02-10 17:01 UTC, kylebrandt commented
> I made some suggestions for improvement. @kylebrandt what do you think?

They all look good to me (I don't have permission to commit the changes).

2020-02-10 18:27 UTC, aknuds1 approved these changes
LGTM!

2020-02-11 00:28 UTC, merged