DevEnv: update frontend dependencies - jest
grafana/grafana pull request #22137
Opened 2020-02-12 23:53 UTC by Estrax

**What this PR does / why we need it**:

Updates frontend dependencies to the newest versions as of the day of submitting this PR (Feb 12 2020)

**Which issue(s) this PR fixes**:

Fixes #20574

**Special notes for your reviewer**:

Changes - more significant:
- `jest` - changes (24.8.0 -> 25.1.0): https://github.com/facebook/jest/blob/master/CHANGELOG.md

Changes - less significant:
- `jest-canvas-mock` - changes (2.1.2 -> 2.2.0): https://github.com/hustcc/jest-canvas-mock/blob/master/CHANGELOG.md
- `jest-date-mock` - changes (1.0.7 -> 1.0.8): https://github.com/hustcc/jest-date-mock/releases

2020-02-14 12:49 UTC, dprokop approved these changes

2020-02-18 08:25 UTC, mckn approved these changes
Looks good!

![well done](https://media.giphy.com/media/ZZrDTGSJXlHW9Y2khu/giphy.gif)

2020-03-10 08:51 UTC, torkelo commented
strange build error preventing merge

2020-03-11 03:08 UTC, Estrax commented
Looks like we get those errors in the other dependencies update PRs as well. Guess it's a problem with webpack package directory resolvers.

2020-03-11 03:09 UTC, Estrax commented
Looks like we get those errors in the other dependencies update PRs as well. Guess it's a problem with webpack package directory resolvers.

@hugohaggmark @dprokop can you take a look at it?

2020-03-12 06:00 UTC, hugohaggmark commented
I get the same redux-toolkit error locally, not sure why yet.

2020-03-16 18:52 UTC, torkelo commented
hm.. the updated seems to have caused new strict null check errors

2020-03-23 13:28 UTC, mckn requested changes
Looks like it no longer builds locally or at Circle CI. I get the following errors:

```
[
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx(98,51):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 98, character: 51 },
    file: '/root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx'
  },
  {
    rawMessage: "ERROR TS2345: Argument of type 'Value' is not assignable to parameter of type 'SetStateAction<Value>'.\n" +
      '  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx(114,18):\n' +
      "TS2345: Argument of type 'Value' is not assignable to parameter of type 'SetStateAction<Value>'.\n" +
      '  undefined',
    location: { line: 114, character: 18 },
    file: '/root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx'
  },
  {
    rawMessage: 'ERROR TS2769: No overload matches this call.\n  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx(158,11):\n' +
      'TS2769: No overload matches this call.\n' +
      '  undefined',
    location: { line: 158, character: 11 },
    file: '/root/project/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.\n` +
      '  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(105,37):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.\n` +
      '  undefined',
    location: { line: 105, character: 37 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value'.\n` +
      '  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(119,21):\n' +
      `TS2345: Argument of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value'.\n` +
      '  undefined',
    location: { line: 119, character: 21 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(135,45):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 135, character: 45 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(135,76):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 135, character: 76 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(151,32):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 151, character: 32 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(180,70):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 180, character: 70 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: `ERROR TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(181,44):\n' +
      `TS2345: Argument of type 'import("/root/project/packages/grafana-ui/node_modules/@types/slate/index").Value' is not assignable to parameter of type 'import("/root/project/node_modules/@types/slate-react/node_modules/@types/slate/index").Value'.`,
    location: { line: 181, character: 44 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: 'ERROR TS2769: No overload matches this call.\n  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx(199,11):\n' +
      'TS2769: No overload matches this call.\n' +
      '  undefined',
    location: { line: 199, character: 11 },
    file: '/root/project/packages/grafana-ui/src/components/QueryField/QueryField.tsx'
  },
  {
    rawMessage: "ERROR TS2322: Type '(event: Event, editor: Editor, next: Function) => any' is not assignable to type 'EventHook'.\n" +
      '  undefined',
    message: 'ERROR in /root/project/packages/grafana-ui/src/slate-plugins/braces.ts(14,5):\n' +
      " [...]

2020-03-23 13:36 UTC, Estrax commented
@mckn yes, strict-null errors stuff. Fix is in progress, not pushed yet.

2020-03-23 13:47 UTC, mckn commented
> @mckn yes, strict-null errors stuff. Fix is in progress, not pushed yet.

Awesome!! 💪

2020-03-23 13:57 UTC, Estrax commented
Hmm, after merging changes, `ci-frontend-metrics` locally returns the value being below the current threshold. Let's check it on CI. I also have a bunch of strict-null fixes in progress, so if this one passes, we'll include it in a separate PR.

2020-04-06 15:49 UTC, mckn commented
@Estrax what do you think about this one? Should we open a new PR fresh from master? Seems to be a lot of issues in this one that has do to with babel (I think).

2020-04-06 15:51 UTC, Estrax commented
@mckn Yep, will do it in approx 4hrs.

2020-04-06 15:52 UTC, mckn commented
> @mckn Yep, will do it in approx 4hrs.

No stress, I was just going through PRs that I have reviewed that not yet is merged. Let me know if I can help out in some way.

2020-05-06 05:42 UTC, closed without merging