Fix: Shows organization popup in alphabetical order
grafana/grafana pull request #22259
Opened 2020-02-18 04:28 UTC by vikkyomkar

**What this PR does / why we need it**:
organization switch popup list was sorted by OrgId, this PR sort the organizations alphabetically

**Which issue(s) this PR fixes**:
Fixes #22162 

**Special notes for your reviewer**:

2020-02-18 06:48 UTC, torkelo commented
Think it’s better if this was already sorted by the http api (and in sql query)

2020-02-19 04:22 UTC, vikkyomkar commented
@torkelo changes done as per the suggestion

2020-02-25 13:36 UTC, vikkyomkar commented
@torkelo @aknuds1 can you please review this change ?
This is similar as #22349

2020-04-02 11:52 UTC, vikkyomkar commented
Hi @torkelo  @aknuds1 This PR is pending from long time.
Can you please review it ?

2020-04-06 08:17 UTC, aknuds1 requested changes

2020-04-06 08:17 UTC, aknuds1 commented on pkg/services/sqlstore/user.go
> +	sess.OrderBy("LOWER(org.name),org.name")
Can you please revert this change? After discussing the matter internally, we've decided that it has too much of a performance impact to lowercase org.name as part of the query.

2020-04-06 08:18 UTC, aknuds1 commented
Also please merge with latest Grafana master, in order to fix the CI issues.

2020-04-06 09:47 UTC, aknuds1 approved these changes
LGTM

2020-04-06 09:49 UTC, aknuds1 commented
We discussed how to best solve this internally, and reached the compromise that we make the ordering (case insensitive primarily, case sensitive secondarily) in the API. Hope you don't mind I pushed these changes to your branch, in order to expedite the PR.

2020-04-06 09:50 UTC, marefr approved these changes
LGTM

2020-04-06 10:17 UTC, papagian approved these changes
LGTM!

2020-04-06 11:27 UTC, merged

2020-04-06 11:27 UTC, aknuds1 commented
Sorry about the long time it took to resolve the PR, but now it's merged. Thanks for contributing to Grafana!