Fix: remove trailing / in cookies' path to avoid redirect loop when running under a sub path
grafana/grafana pull request #22265
Opened 2020-02-18 12:22 UTC by consideRatio

According to the stackoverflow answer below, it is recommended to not
include a trailing / in cookies' path. By removing the trailing / for
our cookies path value, people's browsers visiting grafana will pass the
cookie not only to /grafana/ sub paths but also to /grafana sub paths.

This commit avoids the situation where a user would visit
http://localhost/grafana, get redirected to
http://localhost/grafana/login, and following login get redirected back
to http://localhost/grafana, but since the grafana_session cookie isn't
passed along get redirected back once more to
http://localhost/grafana/login.

ref: https://stackoverflow.com/questions/36131023/setting-a-slash-on-cookie-path/53784228#53784228

**What this PR does / why we need it**:
We avoid a redirect loop following a visit to `/grafana` when authentication relying on cookies are used.

**Which issue(s) this PR fixes**:
Fixes #22227

**Special notes for your reviewer**:
Thank you @marefr for helping out with https://github.com/grafana/grafana/issues/22227#issuecomment-587390063! :heart:

2020-02-18 14:45 UTC, papagian requested changes
Thank for reporting, investigating and contributing this.
Your modifications make sense however there is another case that ends up in redirect loop that is not resolved here: if you have subpath (eg `grafana`) and you request a path that starts with this subpath but it contains also other trailing characters (eg `/grafanagrafana`).

This most probably happens because of [this](https://github.com/grafana/grafana/blob/06f6a77c67c94dae7132183c3682094d4c5cd473/pkg/api/login.go#L40) validation for relative path that should check for `!strings.HasPrefix(to.Path, hs.Cfg.AppSubUrl+"/")` instead of `!strings.HasPrefix(to.Path, hs.Cfg.AppSubUrl)` but I have to investigate it a bit more.
I'll post an update as soon as I will have something new.

2020-02-18 15:32 UTC, consideRatio commented
Thanks for reviewing this PR @papagian!

I think this code block is only to validate the value of the `redirect_to` cookie. Will it matter if the `path` field of the cookie is changed? I'm struggling to grasp it all but I understand that it would impact if it is sent along with a web request to the webserver by a browser having stored the `redirect_to` cookie.

https://github.com/grafana/grafana/blob/06f6a77c67c94dae7132183c3682094d4c5cd473/pkg/api/login.go#L38-L42

## Assumption check

1. If we have `/grafana` as a path for a cookie, and we visit path `/grafana`, we _will_ pass the cookie along - right?
2. If we have `/grafana` as a path for a cookie, and we visit path `/grafana/`, we _will_ pass the cookie along - right?
3. If we have `/grafana` as a path for a cookie, and we visit path `/grafanablablabla`, we _will not_ pass the cookie along - right?

4. If we have `/grafana/` as a path for a cookie, and we visit path `/grafana`, we _will not_ pass the cookie along - right?
5. If we have `/grafana/` as a path for a cookie, and we visit path `/grafana/`, we _will_ pass the cookie along - right?
6. If we have `/grafana/` as a path for a cookie, and we visit path `/grafanablablabla`, we _will not_ pass the cookie along - right?

2020-02-18 16:06 UTC, papagian commented
> 
> ## Assumption check
> 1. If we have `/grafana` as a path for a cookie, and we visit path `/grafana`, we _will_ pass the cookie along - right?
YES
> 2. If we have `/grafana` as a path for a cookie, and we visit path `/grafana/`, we _will_ pass the cookie along - right?
YES
> 3. If we have `/grafana` as a path for a cookie, and we visit path `/grafanablablabla`, we _will not_ pass the cookie along - right?
> 4. If we have `/grafana/` as a path for a cookie, and we visit path `/grafana`, we _will not_ pass the cookie along - right?
> 5. If we have `/grafana/` as a path for a cookie, and we visit path `/grafana/`, we _will_ pass the cookie along - right?
> 6. If we have `/grafana/` as a path for a cookie, and we visit path `/grafanablablabla`, we _will not_ pass the cookie along - right?

According to [RFC 6265](https://tools.ietf.org/html/rfc6265#page-16):
```
 A request-path path-matches a given cookie-path if at least one of
   the following conditions holds:

   o  The cookie-path and the request-path are identical.

   o  The cookie-path is a prefix of the request-path, and the last
      character of the cookie-path is %x2F ("/").

   o  The cookie-path is a prefix of the request-path, and the first
      character of the request-path that is not included in the cookie-
      path is a %x2F ("/") character.
```
 but I'm afraid the behaviour of each browser (browser version) can vary for some of the more obscure cases.

2020-02-18 17:53 UTC, consideRatio commented
Then it sounds like that we should never append a trailing `/` to cookies path value unless we intend to avoid sending a cookie specifically when a path is like /grafana instead of /grafana/

I saw there was one more place where we set a cookie with a trailing slash, in login.go, and ill update that also.

I figure a path like /grafana/d/... is fine to send the cookie along to. We will do that no matter if we merge this PR or or not though.

I need to think abit more myself. I greatly appreciate the insightful references and your help to verify my assumptions! Im learning a lot of relevance!

2020-02-18 19:16 UTC, papagian commented
@consideRatio 
your help with this issue is really valuable

2020-02-18 20:29 UTC, consideRatio commented
In the end, browsers will dictate how things work, but from the standards discussed in the RFC documents linked, it seems to me like:

1. This PR will do nothing except remove a trailing `/` on a Grafana's cookie paths that wasn't just a one character `/` string.
2. This leads to an isolated behavior change that influence if cookies are passed along from the browsers making a web requests to Grafana's web server. The change is to ensure that Grafana cookies are passed along to `/grafana` as well as `/grafana/`, and not only the latter.

Having read from [RFC 6265, section 5.1.4](https://tools.ietf.org/html/rfc6265#section-5.1.4) I think this PR makes sense and I'm more at ease with seeing it merged. But, first an evaluation of why the tests fail.

2020-02-18 21:46 UTC, consideRatio commented
I updated the tests to reflect the change, they had asserted exactly how the cookies should look so I simply updated the tests expectations to reflect not having a trailing `/` in cookies' path.

2020-02-19 17:04 UTC, papagian commented
I still enter in a redirect loop for request paths like `grafanablahblah`.
The reason, as described [here](https://github.com/grafana/grafana/pull/22285#issue-376891964), is that the redirect [validation](https://github.com/grafana/grafana/blob/b251ec7385f646fc1ebf35eeca771eaef1495903/pkg/api/login.go#L40) is not correct (`/grafanablahblah` should not considered as valid).

2020-02-19 17:44 UTC, consideRatio commented
> I still enter in a redirect loop for request paths like /grafanablahblah.
The reason, as described here, is that the redirect validation is not correct (/grafanablahblah should not considered as valid).

Ah okay yes this PR only solve the isolated issue of not being considered authenticated when visiting `/grafana` instead of `/grafana/`, by allowing the cookie to be sent along to `/grafana` also and not only `/grafana/`, by configuring the path value of the cookie. This PR is only aiming to solve that specific issue. Visiting `/grafanablah` before and after this PR would be the same! This is due to having a cookie path set to `/grafana` will not mean `/grafanablah` is considered a matching cookie path, according to [this RFC, section 5.1.4](https://tools.ietf.org/html/rfc6265#section-5.1.4).

Regarding getting a redirect loop for `/grafanablah`. I wonder, what is the desired response by Grafana for a request to `/grafanablah` if Grafana has been configured to use a subpath of `/grafana`? In my mind, I think grafana should firmly say "hey, this is a wierd request I got! I'm configured to accept traffic on /grafana, but I got a request for /somethingelse! I won't even bother with fancy HTML and CSS to such nonsense!".

Also, in my deployment of Grafana, I have a proxy that only directs traffic to Grafana server if it requests `example.org/grafana` and it will not send traffic to `example.org/somethingelse` to the grafana server at all, after all - why should grafana get trafffic unrelated to it like both `/something` and `/grafanasomething` is.

## Updated summary of my understanding

#### Should cookies path value be `/grafana` or `/grafana/`?
It should be `/grafana`, without a trailing `/`. It does not lead to the cookie being passed to `/grafanablah` just because it starts with `/grafana` because the cookie passing logic by the browser, according to [this RFC, section 5.1.4](https://tools.ietf.org/html/rfc6265#section-5.1.4)

#### What to do with requests to `/grafanablah` or `/somethingelse` than the configured subpath?

I think Grafana should respond harshly to request to it that doesn't make sense, such as if the requested URL is outside the scope of what it is supposed to serve. So for example, if it is configured to run on `/grafana` subpath it should accept `/grafana`, `/grafana/`, `/grafana/anything` as something that it makes sense for it to respond to with content, 404, 302 internally etc. But, if it get a request to `/something-else` or `/grafana-anything` it should probably say it has been configured to only serve content on `/grafana` and that this request for another path doesn't make sense to it.

---

I'm learning a lot trying to think clearly about this with you! :tada: Thanks for your patience working on this and related issues @papagian!

2020-03-11 10:29 UTC, consideRatio commented
@papagian I verified that #22285 solve the key issue of getting a redirect loop! :tada:

I verified that we still make some bounces and get query params truncated in the process though, something that this PR could help us avoid.

2020-03-11 10:56 UTC, papagian commented
> @papagian I verified that #22285 solve the key issue of getting a redirect loop! 🎉
> 
> I verified that we still make some bounces and get query params truncated in the process though, something that this PR could help us avoid.

Thank you for testing it. The query parameter issue was missing from the initial issue description so I have missed it. I will create a new separate issue for this in order to be sure that we will include a fix in the next release. I will let you know as soon as it will be created so you can included it in this PR's description.

2020-03-28 16:29 UTC, consideRatio commented
@papagian and @marefr I made a final push to get this merged by summarizing the current situation as clearly as I could. I'm now grown very confident this change make sense. I also went ahead pushed it rebased on current master to ensure it works against current tests etc.

2020-03-28 19:16 UTC, consideRatio commented
The build failure is unrelated to this PR, as for example this documentation PR introducing two new lines also breaks in the same way: https://github.com/grafana/grafana/pull/23158

2020-04-01 12:28 UTC, marefr commented
@consideRatio please merge with latest master to resolve build issues. Then we'll review this again. Thanks

2020-04-01 16:26 UTC, consideRatio commented
@marefr rebased on master!

2020-04-06 10:16 UTC, marefr approved these changes
Works as expected using no proxy with or without subpath and with nginx and subpath. LGTM

2020-04-06 14:51 UTC, papagian approved these changes

2020-04-06 14:56 UTC, papagian commented
Apologies for taking us so long to evaluate this! The main reason of the delay was that it's hard to think of (and verify) all the possible cases that can be affected.

2020-04-06 14:56 UTC, merged

2020-04-06 15:46 UTC, consideRatio commented
:tada: :star2: wieee!

@papagian no worries! Thank you for working together with me on this, I learned a lot about how this works and it started with your feedback! :heart:

2020-04-07 08:58 UTC, marefr commented
@consideRatio thanks for your patience and contributing to Grafana!

2020-05-28 21:09 UTC, josharnoldmt commented
FYI - I also ran into a login problem due to this change after upgrading to grafana 7.   The problem turned out to be caused by old session cookies left in the browser from before the upgrade.    Normally, a stale session cookie gets removed during the login flow, but this wasn't working because the cookie path had changed.   As a result, users were unable to log in, and kept returning to the login page instead.

Clearing cookies would fix the problem for a particular browser, but I wanted to fix it for all my users so I changed the login_cookie_name in the configuration so that the old cookie would get ignored.   

```
[auth]
login_cookie_name = grafana_session2
```

This resolved the issue for me.

2020-05-28 21:51 UTC, consideRatio commented
Thanks @josharnoldmt for summarizing this, I followed up your insights in #23381.

2020-06-12 09:08 UTC, jayden-xie commented
@josharnoldmt I have the same issue to you, add serve_from_sub_path=true to Grafana config fix the issue for me.
cc/ @consideRatio