<Role Required> Login restriction by mapped role from GenericAuth.
grafana/grafana pull request #22383
Opened 2020-02-22 11:02 UTC by burakksglu

**What this PR does / why we need it**:

This PR adds a 'login restriction by role' functionality for Generic Auth role mapping. This way if "required_role" is enabled from config, we can allow login only for 'Admin', 'Editor' and 'Viewer' roles. If it is disabled "auto_assign_role" is still active and works.

**Which issue(s) this PR fixes**:

This PR fixes the issue of the entry of those who do not have a role. For example, if a user from Keycloak has no role for Grafana client and he tries to login the client anyway, he can still login with some role. What we want is in that situation he shouldn't be able to login that Grafana client. 

Therefore this feature adds a functionality for those who wants to restrict login by role for Generic Auth.

**Special notes for your reviewer**:

We tested this feature on a local Keycloak server and it works as intended. 

**If 'role_required' is true from sample.ini config file:**

_1- User has a Grafana role from Keycloak ( Admin/Editor/Viewer ) he can login to the client.
2- User doesn't have a Grafana role from Keycloak but has something else ( Guest,user,etc. ) he can't login to the client.
3- User doesn't have ANY role from Keycloak, he can't login to the client._ 

**If 'role_required' is false from sample.ini config file:**

_Login works as previous, if auto_assign is enable it assigns corresponding role for the user and let's the user in to client._

Since this is my first PR to Grafana community and I am not a Go expert, I do need a help on documentation and other necessary actions for this PR. 

Thanks!

2020-02-22 11:02 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=22383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=22383) it.</sub>

2020-02-26 08:14 UTC, chelnak commented
It would be cool if we could ask Grafana to validate custom roles.. for example, if my IdP is used for many other things, having `Viewer/Editor/Admin` could be confusing.. so you might want `Grafana_User` for example.. which maps to Viewer..

Is this something that is possible with the current setup?

2020-02-26 08:42 UTC, burakksglu commented
@chelnak ;

In our configuration it doesn't map to custom role. We only pass the current supported roles by default from Keycloak to Grafana which are 'Admin, 'Editor' and 'Viewer'. We have client(application) based roles to overcome this issue. When we create a new client we also create the roles in it. ('Admin', 'Editor', 'Viewer') 

It would be nice to have what you say though. So we could create a realm role with the prefix. But you can still overcome this on IdP I guess.

2020-02-26 08:46 UTC, aknuds1 requested changes
Thanks for your PR, I made some suggestions for improvement. I will need additional feedback though, from team mates with more experience in OAuth.

2020-02-26 08:46 UTC, aknuds1 commented on conf/sample.ini
> +;role_required = true
Should have the default value here shouldn't it:
```suggestion
;role_required = false
```

2020-02-26 08:46 UTC, aknuds1 commented on pkg/login/social/generic_oauth.go
> +	s.log.Debug("s.roleRequired", "s.roleRequired", s.roleRequired)
```suggestion
	s.log.Debug("Checking if role is allowed", "role", role, "s.roleRequired", s.roleRequired)
```

2020-02-26 08:46 UTC, aknuds1 commented on pkg/login/social/generic_oauth.go
> +	}
```suggestion
	}

```

2020-02-26 08:46 UTC, aknuds1 commented on pkg/login/social/generic_oauth.go
> +	return false
```suggestion

	return false
```

2020-03-02 10:44 UTC, burakksglu commented
@aknuds1 Should I wait for reviewers or commit the changes you've requested?

2020-03-03 15:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22383) <br/>All committers have signed the CLA.

2020-03-04 08:04 UTC, burakksglu commented
I've commited change requests by @aknuds1.
Sorry to bother you guys but did you have any chance to look at this PR? Any updates or thoughts? 

CC: @torkelo @daniellee @bergquist @papagian @marefr

2020-03-04 08:59 UTC, aknuds1 approved these changes
LGTM after the changes. @marefr did we come to a conclusion on merging this?

2020-03-04 10:12 UTC, marefr commented
We're going to discuss it today.

2020-03-05 14:27 UTC, aknuds1 commented
@burakksglu We are wondering if this logic, i.e. only allowing users with valid Grafana roles, could be enforced in the OAuth provider (Keycloak in your case)?

2020-03-05 15:15 UTC, burakksglu commented
@aknuds1 as far as I know that's what we are doing actually, but this PR also needed for this logic to work. 

For example we have 2 grafana clients on keycloak, each with different users and instance. Let's say I have a role on the grafana A and I tried to login to grafana B. Without this PR I can login with "Auto Assigned Role Viewer" which is not wanted in our use case.

If I don't deny role and don't give any roles from Keycloak I still can login. To my knowledge OAuth does role mapping but it only maps and it doesn't have any role deny. 

Therefore this should be handled on the application side.

2020-03-05 17:32 UTC, aknuds1 commented
@burakksglu So basically you're sure that Keycloak can't deny certain users logging into a Grafana instance? As far as I can tell that is the crux of the matter; if Keycloak can deny the undesired users, the exclusion doesn't have to happen in Grafana.

2020-03-05 17:36 UTC, burakksglu commented
> @burakksglu So basically you're sure that Keycloak can't deny certain users logging into a Grafana instance? As far as I can tell that is the crux of the matter; if Keycloak can deny the undesired users, the exclusion doesn't have to happen in Grafana.

No I don't think so. There are 2 other applications we test and they all do this in the application side.

2020-03-05 17:50 UTC, aknuds1 commented
[This SO question](https://stackoverflow.com/questions/54305880/how-can-i-restrict-client-access-to-only-one-group-of-users-in-keycloak/54374808#54374808) corresponds to your case right?

2020-03-06 06:15 UTC, burakksglu commented
> [This SO question](https://stackoverflow.com/questions/54305880/how-can-i-restrict-client-access-to-only-one-group-of-users-in-keycloak/54374808#54374808) corresponds to your case right?

I'm going to check this out let you know. Thank you for forwarding this to me. I'll try to do analysis of it.

2020-03-06 08:12 UTC, burakksglu commented
Hey @aknuds1,

We've tried and tested the given suggestions on the link you've provided. Unfortunately it doesn't work as many others stated in that topic. 

There are resource based policies that you can create on keycloak but in order to make it work both Grafana and Keycloak should have the support for it. For example Keycloak needs a resource server from Grafana, some configuration and js scripts.

After all it still might not work on the different configuration. This PR provides an application based role policy which most of the applications implemented in some way.

2020-03-06 08:30 UTC, levkar commented
Currently, anyone on the realm becomes a valid user and there is no way to stop him from logging to grafana. Is there a simple way to deny login if user doesn't have a valid role?

2020-03-06 11:19 UTC, chelnak commented
Yeah I can second this behaviour. It’s an issue when you share your IDP
with a wider org.

On Fri, 6 Mar 2020 at 08:30, Levent Karakaş <notifications@github.com>
wrote:

> Currently, anyone on the realm becomes a valid user and there is no way to
> stop him from logging to grafana. Is there a simple way to deny login if
> user doesn't have a valid role?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana/pull/22383?email_source=notifications&email_token=AA42IJVHNBZSAEKS44YQGRLRGCYA3A5CNFSM4KZQR5MKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOAQRLI#issuecomment-595658925>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA42IJSGW6BYEKDQDW4EKWTRGCYA3ANCNFSM4KZQR5MA>
> .
>

2020-03-09 17:07 UTC, aknuds1 commented
@marefr @bergquist @papagian - what are your thoughts? I don't have the most experience with OAuth.

> We've tried and tested the given suggestions on the link you've provided. Unfortunately it doesn't work as many others stated in that topic.
> 
> There are resource based policies that you can create on keycloak but in order to make it work both Grafana and Keycloak should have the support for it. For example Keycloak needs a resource server from Grafana, some configuration and js scripts.
> 
> After all it still might not work on the different configuration. This PR provides an application based role policy which most of the applications implemented in some way.

2020-03-11 14:37 UTC, bergquist commented
I think this feature request is reasonable and the current implementation is fairly isolated. The OAuth code in Grafana is what it is....

But I'm not sure we only want this for generic OAuth. Why not for all OAuth providers?
The current implementation is fairly simple but since I can see this feature grow I would like to see some tests for `IsRoleAllowed`.

2020-03-11 14:43 UTC, aknuds1 commented
Thanks for giving your 2 cents @bergquist!

2020-03-12 08:04 UTC, levkar commented
@bergquist 
it would require some effort to implement and test this in every single oauth provider supported. Some providers do not even have role capability. This PR prepares a base for this feature and it can be easily implemented in other providers as needed.

2020-03-12 09:40 UTC, bergquist commented
Related https://github.com/grafana/grafana/issues/22741

2020-03-16 08:37 UTC, levkar commented
we need your review & approval for this PR. thanks in advance!
@torkelo @daniellee @papagian @marefr @bergquist

2020-03-17 14:23 UTC, twendt commented
Wouldn't the IsRoleAllowed function have the same implementation in all providers that support roles? It only checks if the role is one of the valid grafana roles.

What about having the function in social.go and instead have an IsRoleRequired function in all providers that returns the value of the roleRequired field.

During the creation of the SocialMap in social.go the value of roleRequired could then be hard coded to false for all providers that do not support roles.

I would also suggest to use the constants from the models package models.ROLE_ADMIN, models.ROLE_EDITOR and models.ROLE_VIEWER.

2020-03-17 14:31 UTC, aknuds1 commented
In order to fix the build-pipeline status issue, please merge with latest Grafana master.

2020-03-18 06:37 UTC, burakksglu commented
@twendt : Thank you for the suggestions, I'll work on that package models and try to have the function on the social go. But just to be sure since I'm not expert on Go language, you are saying that we can have the "IsRoleAllowed" function on the social.go and override the return field based on the role availability in the oauth.go packages. I am going to work on that today.

@aknuds1 Ok, i did pulled from origin of master and tried to merge but it says I am up to date with master branch. So I am not sure about the pipeline issue. I also did git fetch.

2020-03-18 07:12 UTC, twendt commented
@bergquist @marefr Could you please also comment on my suggestions?

2020-03-18 07:27 UTC, aknuds1 commented
@burakksglu According to GitHub, your branch is 228 commits behind Grafana master. Please try again merging Grafana master into your branch and push the changes.

2020-03-18 12:02 UTC, burakksglu commented
So I've merged this branch with the master and worked on the suggestions you've made. Now the control function checks based on the models.ROLE_... constants. I have made the local test with keycloak, it's working as expected.

About the other suggestion, "hard coding the IsRoleAllowed in the social.go" I checked but couldn't figure it out. The way operation of this ' IsRoleAllowed ' function was similar to ' IsEmailAllowed '. We think that they work and should work in a similar way. If you look both of them they are actually constructed in similar way. 

Therefore I didn't make any changes on that side.

2020-03-18 12:33 UTC, aknuds1 commented
You don't need to make any more changes for now, we still need to make a decision internally with regards to including this functionality.

2020-03-20 12:46 UTC, burakksglu commented
> You don't need to make any more changes for now, we still need to make a decision internally with regards to including this functionality.

OK, thank you for your effort and time. I am looking forward to see this functionality included in Grafana. Stay safe and healty in the mean time.

2020-03-23 12:27 UTC, levkar commented
> You don't need to make any more changes for now, we still need to make a decision internally with regards to including this functionality.

thanks @aknuds1

2020-03-27 13:40 UTC, mr-yaky commented
We have the same case with Keycloak and can't restring users from login if they not contain role for Grafana on Keycloak side. So, this feature will be also very useful for us.

2020-03-30 15:31 UTC, aknuds1 commented
Thank you for making the PR and the effort you've put into it, we really appreciate it. Unfortunately we've come to the conclusion that we will have to close it for now.                                                                                                                                                                                                                                                                                                                                                                 

We're not sure that adding this feature to only generic OAuth is a good thing to do at the moment. We would rather track and gather requirements for restricting users to login if certain criterias aren't met, with all different auth types in Grafana in mind.                                                                                          
                                                                                                                                                                              
Additionally, we think that this type of functionality crosses into enterprise edition territory, so we would like to determine for example if this functionality is actually useful outside of large companies.                                                                                                                                            
                                                                                                                                                                              
We'd like to suggest that you open a feature request for the desired functionality, linking to this PR, and ask for the community to vote on it, explaining their use case and adding their specific requirements. Just because we're closing it doesn't mean we cant reopen it later.

2020-03-30 15:31 UTC, closed without merging

2020-03-30 15:52 UTC, mr-yaky commented
>We would rather track and gather requirements for restricting users to login if certain criterias aren't met, with all different auth types in Grafana in mind.
@aknuds1 can we open an issue for this then please ? It supposed to be really useful feature!

2020-03-30 15:58 UTC, levkar commented
Where do we open feature request? Issue?

2020-03-30 16:02 UTC, aknuds1 commented
@levkar @mr-yaky To make a feature request, simply create an issue in this repo, picking the "Enhancement request" template.

2020-03-31 06:25 UTC, burakksglu commented
@mr-yaky @levkar @chelnak I've created the issue for Feature Request fyi: grafana/grafana/issues/23218

2020-04-01 09:09 UTC, levkar commented
@chelnak @twendt @mr-yaky @aknuds1 please vote / thumbs up the request.

https://github.com/grafana/grafana/issues/23218