Docs: Adding a Markdown Style Guide
grafana/grafana pull request #22425
Opened 2020-02-26 01:50 UTC by RobinJoe

What this PR does / why we need it: This request builds a markdown style guide for writers documenting information about Grafana services for users.
This PR serves the need to make documentation and READMEs more consistent and maintainable.

Which issue(s) this PR fixes: This request fixes the issue grafana#19592

Fixes grafana#19592

Special notes for your reviewer:

@marcusolsson and @oddlittlebird, sorry for the delay. I've set up the style guide, and it is ready for review, or additional sections.

**What this PR does / why we need it**: This request builds a markdown style guide for writers documenting information about Grafana services for users.
This PR serves the need to make documentation and READMEs more consistent and maintainable.

**Which issue(s) this PR fixes**: This request fixes the issue grafana#19592

Fixes grafana#19592

**Special notes for your reviewer**:

@marcusolsson and @oddlittlebird, sorry for the delay. I've set up the style guide, and it is ready for review, or additional sections.

2020-02-26 01:50 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22425) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=22425) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=22425) it.</sub>

2020-02-27 16:02 UTC, oddlittlebird requested changes

2020-02-27 16:02 UTC, oddlittlebird commented on contribute/style-guides/documentation-markdown-guide.md
> +## Links and References
Per the documentation style guide, all headings should be in sentence case. Initial cap only.

2020-02-27 16:02 UTC, oddlittlebird commented on contribute/style-guides/documentation-markdown-guide.md
> +**Example** For more information on including emoji in Github Flavored Markdown, refer to the [webfx page on emoji](https://www.webfx.com/tools/emoji-cheat-sheet/) for a list of emoji.
```suggestion
**Example:** For more information on including emoji in Github Flavored Markdown, refer to the [webfx page on emoji](https://www.webfx.com/tools/emoji-cheat-sheet/) for a list of emoji.
```

2020-02-27 16:02 UTC, oddlittlebird commented on contribute/style-guides/documentation-markdown-guide.md
> +## Blockquotes
Block quotes is two words.

2020-02-27 16:02 UTC, oddlittlebird commented on contribute/style-guides/documentation-markdown-guide.md
> +Include Blockquotes inside text using right facing arrows:
```suggestion
Include block quotes inside text using right-facing arrows:
```

2020-02-27 16:02 UTC, oddlittlebird commented on contribute/style-guides/documentation-markdown-guide.md
> +to show specific syntax highlighting - for example "\```javascript" produces the following
```suggestion
to show specific syntax highlighting. For example: "\```javascript" produces the following
```

2020-03-03 11:09 UTC, RobinJoe commented
Looking at the latest commit id (https://github.com/grafana/grafana/pull/22425/commits/224ee8aff4a766ea5f5c7f183212bbc53ed6419d) the content does appear to be a PR aimed to merge into Grafana/Grafana repo. I compared it to other commits tagged with pr/external. I made the requested changes in the latest commit if that helps clarify what stage the work is up to.

2020-03-03 15:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22425) <br/>All committers have signed the CLA.

2020-03-03 17:05 UTC, oddlittlebird approved these changes

2020-03-03 17:05 UTC, oddlittlebird commented
LGTM! Thanks for contributing this resource!

2020-03-03 17:06 UTC, merged