Fix: Users list is not alphabetically ordered on Org-> User page
grafana/grafana pull request #22471
Opened 2020-02-27 12:49 UTC by vikkyomkar

What this PR does / why we need it:
Users are listed in alphabetical order by their usernames on the Org Useer page.

Which issue(s) this PR fixes:

Fixes #22371

2020-02-27 16:20 UTC, aknuds1 requested changes

2020-02-27 16:20 UTC, aknuds1 commented on pkg/services/sqlstore/org_users.go
> +	//sess.Asc("user.email", "user.login")
```suggestion
```

2020-02-27 16:22 UTC, aknuds1 commented on pkg/services/sqlstore/org_users.go
> +	sess.OrderBy("upper(user.login), upper(user.email)")
I thought the following ordering was agreed? 
```
sess.OrderBy("LOWER(u.login),u.login,LOWER(u.email),u.email")
```

2020-02-27 16:22 UTC, aknuds1 commented
Postgres integration tests are failing, any idea why?

2020-02-27 17:14 UTC, vikkyomkar commented
> Postgres integration tests are failing, any idea why?

Its failing if `OrderBy` is used, it seems
Trying to understand more about this `Postgres integration tests` failure

2020-03-05 12:48 UTC, aknuds1 commented
The tests are still failing.

2020-04-01 13:04 UTC, aknuds1 commented
I synced your branch with latest Grafana master, since we've decided to have another look at it.

2020-04-01 15:19 UTC, marefr commented
@aknuds1 I'm a bit worried using `lower()` will not be able to use any indices in database. Think the proper solution to this would be to always store/treat username and email in lowercase. We have another issue regarding that, https://github.com/grafana/grafana/issues/12549 but it's a bit tricky.

2020-04-01 15:43 UTC, aknuds1 commented
Thanks for the feedback @marefr - I haven't been able to get around to looking at this PR yet beyond syncing it with master. So what is your take wrt. this PR, is it infeasible or can we merge a modified version of it?

2020-04-02 09:36 UTC, aknuds1 commented
I'm truly sorry, but we're going to have to close this PR. The reason is that after analyzing the problem, we've come to the conclusion that ordering by login and login case insensitive has too much of a negative impact on query performance.

We think that fixing this issue will have to wait until we have been able to resolve the more fundamental issue of making usernames case insensitive.

2020-04-02 09:36 UTC, closed without merging