GraphPanel: Group series by alias for x-axes when x-axes mode is set to series
grafana/grafana pull request #22538
Opened 2020-03-03 13:46 UTC by Crewman123

GraphPanel: Also group by series option stack when x-axes mode is set to series and series stack is set

In an graph x and y Axis values should be unique so that f(x,y) always correspond to one value in the graph. This is not the case for the x-axis of GrapPanel in series mode right now, this PR will group the series assigned to x-axis by the series alias to ensure unique values for the x-axes.

Closes #22531

2020-03-03 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=22538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=22538) it.</sub>

2020-03-24 14:51 UTC, aknuds1 commented
Could you please merge this with latest Grafana master, in order to fix CI issues?

2020-03-24 20:17 UTC, torkelo requested changes
Looks good, but a unit test for this added logic / case would be good

2020-04-11 21:32 UTC, vivekdsr commented
Can you update on this?

2020-04-13 12:20 UTC, achandna commented
Can this be merged? It will solve a long pending issue from last ~3 years.

2020-05-14 10:01 UTC, vivekdsr commented
@torkelo / @Crewman123 
Because of this issue we are not able to use grafana,Could you please merge this change

2020-08-02 00:53 UTC, closed without merging