optimization debian package manager tweaks
grafana/grafana pull request #22652
Opened 2020-03-09 15:12 UTC by Rajpratik71

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-03-10 23:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=22652) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=22652) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=22652) it.</sub>

2020-03-11 17:32 UTC, oddlittlebird commented
@xlson , please review.

2020-03-16 16:09 UTC, xlson reviewed
Thanks for contribution. I'll take a look at this when I get some time over, but it's not very high on the priority list as it will take quite some time to verify that we don't depend on one of the recommended packages.

@Rajpratik71 if you want to make sure this gets reviewed and merged sooner it would be a good idea to break this apart into a few different PRs. One for the main Dockerfiles (`Dockerfile`, `packaging/docker/*`) that we use to build grafana, one for the docs and one for the ci docker containers (`scripts/build/ci-*`).

2020-04-30 17:07 UTC, aknuds1 commented
Please break this into several PRs, since it touches on too many different files (both Dockerfiles for internally used images and externally used images, and documentation).

2020-06-11 16:03 UTC, Rajpratik71 commented
@aknuds1 requesting review

2020-06-27 03:01 UTC, Rajpratik71 commented
for the failing build issue , i looked at logs , it is related to "TypeScript" which is not touched means unrelated failing builds

2020-06-29 14:42 UTC, oddlittlebird commented
Try updating the branch from master.

2020-07-01 14:10 UTC, Rajpratik71 commented
> Try updating the branch from master.

Updated to upstream . Please review . Is pending from months

2020-07-03 15:55 UTC, Rajpratik71 commented
@xlson @oddlittlebird @aknuds1  requesting review

2020-07-03 16:24 UTC, aknuds1 requested changes

2020-07-03 16:24 UTC, aknuds1 commented on .circleci/config.yml
> +        - checkout
Please revert your formatting changes.

2020-07-03 16:24 UTC, aknuds1 commented on Dockerfile.ubuntu
> +# We need font libs for phantomjs, and curl should be part of the image
Please revert this change.

2020-07-03 16:24 UTC, aknuds1 commented on scripts/build/ci-build/Dockerfile
> +    rm -rf /tmp/osxcross && \
Please revert this change.

2020-07-03 16:25 UTC, aknuds1 commented
Just a cursory review for now. In order to review in depth, I need to find the time, since I have to verify that your changes don't break things.

2020-07-04 06:11 UTC, Rajpratik71 commented on .circleci/config.yml
> +        - checkout
fixed

2020-07-04 06:11 UTC, Rajpratik71 commented on Dockerfile.ubuntu
> +# We need font libs for phantomjs, and curl should be part of the image
fixed

2020-07-04 06:11 UTC, Rajpratik71 commented on scripts/build/ci-build/Dockerfile
> +    rm -rf /tmp/osxcross && \
fixed

2020-07-04 16:40 UTC, Rajpratik71 commented
> for the failing build issue , i looked at logs , it is related to "TypeScript" which is not touched means unrelated failing builds

Again this happened after rebasing from Upstream

2020-08-13 04:17 UTC, Rajpratik71 commented
@xlson @aknuds1 @oddlittlebird  requesting review

2020-09-02 13:11 UTC, aknuds1 requested changes
We've decided that most changes from the PR should be dropped.

2020-09-02 13:11 UTC, aknuds1 commented on .circleci/config.yml
> +      - run: sudo apt-get --no-install-recommends install -y default-mysql-client
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on .circleci/config.yml
> +      - run: sudo apt-get --no-install-recommends install -y postgresql-client
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on Dockerfile.ubuntu
> +RUN apt-get update && apt-get upgrade -y && apt-get --no-install-recommends install -y ca-certificates curl
```suggestion
RUN apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends -y ca-certificates curl
```

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/blocks/multiple-openldap/admins-ldap-server.Dockerfile
> +    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/blocks/multiple-openldap/ldap-server.Dockerfile
> +    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/blocks/mysql_opendata/Dockerfile
> +RUN apt-get update && apt-get --no-install-recommends install -y wget && apt-get --no-install-recommends install -y unzip
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/blocks/openldap/Dockerfile
> +    DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends install -y \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/debtest/Dockerfile
> +RUN apt-get update && apt-get --no-install-recommends install -y vim
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on devenv/docker/ha_test/README.md
> +$ sudo apt-get --no-install-recommends install -y dnsmasq
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/installation/debian.md
> +sudo apt-get --no-install-recommends install -y software-properties-common wget
Please remove these changes.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/installation/debian.md
> +sudo apt-get --no-install-recommends install -y software-properties-common wget
Please remove these changes.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/installation/debian.md
> +sudo apt-get --no-install-recommends install grafana
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/installation/debian.md
> +sudo apt-get --no-install-recommends install -y adduser libfontconfig1
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/installation/upgrading.md
> +sudo apt-get --no-install-recommends install -y adduser libfontconfig1
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/tutorials/stack_guide_graphite.md
> +apt-get --no-install-recommends install -y \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on docs/sources/tutorials/stack_guide_graphite.md
> +`apt-get --no-install-recommends install -y supervisor`
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on packaging/docker/ubuntu.Dockerfile
> +RUN apt-get update && apt-get --no-install-recommends install -y ca-certificates curl tzdata && \
```suggestion
RUN apt-get update && apt-get install --no-install-recommends  -y ca-certificates curl tzdata && \
```

2020-09-02 13:11 UTC, aknuds1 commented on scripts/build/ci-build/Dockerfile
> +    apt-get --no-install-recommends install -yq \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on scripts/build/ci-build/Dockerfile
> +RUN apt-get --no-install-recommends install -yq                     \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on scripts/build/ci-build/Dockerfile
> +    apt-get --no-install-recommends install -yq  \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on scripts/build/ci-deploy/Dockerfile
> +    apt-get --no-install-recommends install -y createrepo expect && \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on scripts/verify-repo-update/Dockerfile.deb
> +    apt-get --no-install-recommends install -y curl                \
Please remove this change.

2020-09-02 13:11 UTC, aknuds1 commented on scripts/verify-repo-update/Dockerfile.deb
> +    apt-get --no-install-recommends install -y $PACKAGE
Please remove this change.

2020-09-02 16:42 UTC, Rajpratik71 commented
@aknuds1 removed everyone which is not needed or was duplicate. Only left with where needed.

2020-09-03 07:29 UTC, aknuds1 commented
Why have you resolved my review comments? Please do as I ask in the comments, or I will have to close the PR.

2020-09-03 08:42 UTC, aknuds1 requested changes

2020-09-03 08:42 UTC, aknuds1 commented on devenv/docker/blocks/mysql_opendata/Dockerfile
> +RUN apt-get update && apt-get --no-install-recommends install -y wget unzip
Please remove this change.

2020-09-04 07:10 UTC, aknuds1 requested changes
Please do as I ask in review comments.

2020-09-04 09:01 UTC, Rajpratik71 commented on devenv/docker/blocks/mysql_opendata/Dockerfile
> +RUN apt-get update && apt-get --no-install-recommends install -y wget unzip
done as requested

2020-09-04 09:02 UTC, closed without merging

2020-09-04 09:04 UTC, Rajpratik71 commented
removing everything leave nothing in commit , closing it .