Alerting: Use alert tags to override PD Severity setting
grafana/grafana pull request #22736
Opened 2020-03-11 19:12 UTC by AndrewBurian

**What this PR does / why we need it**: 

Uses alert tags to optionally override the `severity` in the PagerDuty event.

This gives you the ability to send events of different severity to the same service without needing a separate notification channel configured.

2020-03-11 21:40 UTC, oddlittlebird submitted a review, later dismissed

2020-03-11 21:40 UTC, oddlittlebird commented on docs/sources/alerting/notifications.md
> +**Note:** The tags `Severity`, `Class`, `Group`, and `Component` have special meaning in the [Pagerduty Common Event Format - PD-CEF](https://support.pagerduty.com/docs/pd-cef).  If an alert panel de
```suggestion
**Note:** The tags `Severity`, `Class`, `Group`, and `Component` have special meaning in the [Pagerduty Common Event Format - PD-CEF](https://support.pagerduty.com/docs/pd-cef). If an alert panel defines these tag keys, then they are transposed to the root of the event sent to Pagerduty. This means they will be available within the Pagerduty UI and Filtering tools. A Severity tag set on an alert overrides the global Severity set on the notification channel if it's a valid level.
```

2020-03-12 17:11 UTC, AndrewBurian commented
I somehow managed to remove @grafana/backend-platform from the reviewers list... My bad. Can someone re-add that?

2020-03-12 19:31 UTC, bergquist requested changes
Hi

How is this better than using different notification channels? From my perspective that would achive the same thing.

2020-03-12 19:41 UTC, AndrewBurian commented
It's both cleaner, and enables better division of responsibility.

In our use case, the notification channels are configured by the SRE team, and then consumed at the dashboard level by the engineers. We currently run 38 services, times 4 severity levels, thats crossing 150 notification channels that need to be manually added, and then searched for in the alerting panel. If a service changes or needs a new integration key, that's 4 copies of the same service that need updated.

I really like the addition of alert tags, and using that control to add things to the PagerDuty event fields for Class, Group, and Component has already been useful. Even if the configuration complexity wasn't being 4x'd without it, I would still argue that it's a good use of tags to bring that control to a more granular level per-alert rather than per-channel.

2020-03-18 07:55 UTC, bergquist requested changes
I agree that this is cleaner. This is something we want to achieve at a generic level rather then just for one alert notifier. But that's another issue :)

Could you please add more tests with different severity levels so that we test that it's based on input data. Once that is done I'll merge this.

2020-03-18 07:55 UTC, bergquist commented on pkg/services/alerting/notifiers/pagerduty_test.go
> +						{Key: "severity", Value: "warning"},
Could you please add a test using another severity as well?

2020-03-19 11:47 UTC, bergquist commented
Thanks! I'll merge this one the build passes :)

2020-03-20 07:43 UTC, bergquist commented
Depends on https://github.com/grafana/grafana/pull/22909

2020-03-23 18:32 UTC, bergquist approved these changes

2020-03-23 18:32 UTC, bergquist commented
Thank you for contributing!

2020-03-23 18:32 UTC, merged

2020-05-18 18:36 UTC, AndrewBurian commented
@oddlittlebird FYI, I think the documentation changes here are in the grafana docs under v6.7, but the code is not actually present in the v6.7.3 release, so those are out of sync. Judging by the milestone here, I think the docs aren't meant to show up until v7

2020-05-18 19:40 UTC, oddlittlebird commented
@bergquist, could you check on this?