Docs: Update export-pdf.md
grafana/grafana pull request #22767
Opened 2020-03-12 20:08 UTC by oddlittlebird

Minor edits and one question.

**Special notes for your reviewer**: Where is the PDF saved and how is the file named?

2020-03-13 09:52 UTC, alexanderzobnin requested changes

2020-03-13 09:52 UTC, alexanderzobnin commented on docs/sources/enterprise/export-pdf.md
> +1. Click the title of the dashboard that you want to export as PDF and then click **Share**.
That's not true it seems. Share modal available from share button, not dashboard title.
![Screenshot from 2020-03-13 12-51-00](https://user-images.githubusercontent.com/4932851/76609982-51e13680-6529-11ea-84b2-b58aa25b4015.png)

2020-03-13 09:52 UTC, alexanderzobnin commented on docs/sources/enterprise/export-pdf.md
> +1. On the PDF tab,sSelect the layout option for exported dashboard: **Portrait** or **Landscape**.
```suggestion
1. On the PDF tab, select the layout option for exported dashboard: **Portrait** or **Landscape**.
```

2020-03-13 15:33 UTC, alexanderzobnin commented
> **Special notes for your reviewer**: Where is the PDF saved and how is the file named?
PDF will be opened in a new tab in the browser, then you can save it from the browser. File name matches dashboard id, but I think we should fix it and use PDF title or something more human-readable.

2020-03-17 09:08 UTC, alexanderzobnin approved these changes
Looks good now!

2020-03-17 21:44 UTC, oddlittlebird commented
@alexanderzobnin , the build-pipeline is still yellow after several hours. Any idea why?

2020-03-18 15:58 UTC, merged