Fix: check if DashboardsAsConfig has unique names
grafana/grafana pull request #22898
Opened 2020-03-19 14:23 UTC by youshy

**What this PR does / why we need it**:

This PR introduces a check if an array of `*DashboardsAsConfig` has only unique names

**Which issue(s) this PR fixes**:

Fixes #20421 

(this is a clean version of #21676 which I've messed up beautifully)

@marefr :)

2020-03-20 21:18 UTC, bergquist requested changes
Looks good!

But I think we need a better way to handle this error when starting grafana. This is the error message I get when I have duplicate dashboard provisioners. 

```bash
EROR[03-20|22:12:09] Failed to provision dashboard            logger=provisioning error="Failed to create provisioner: Failed to read dashboards config: could not parse provisioning config file: dev.yaml error: dashboards name \"gdev dashboards\" is not unique"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1482ce0]

goroutine 151 [running]:
github.com/grafana/grafana/pkg/services/provisioning.(*provisioningServiceImpl).Run(0xc00053a000, 0x1de04c0, 0xc000056140, 0x0, 0x0)
        /home/carl/go/src/github.com/grafana/grafana/pkg/services/provisioning/provisioning.go:89 +0x170
main.(*Server).Run.func1(0x0, 0x0)
        /home/carl/go/src/github.com/grafana/grafana/pkg/cmd/grafana-server/server.go:129 +0x60
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000398450, 0xc000a17200)
        /home/carl/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/carl/go/src/github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66

```

2020-03-24 14:34 UTC, aknuds1 requested changes
Just saw a typo.

2020-03-24 14:34 UTC, aknuds1 commented on pkg/services/provisioning/dashboards/types.go
> +			return nil, fmt.Errorf("dashboards name %q is not unique", v.Name.Value())
```suggestion
			return nil, fmt.Errorf("dashboard name %q is not unique", v.Name.Value())
```

2020-03-25 08:54 UTC, aknuds1 approved these changes
LGTM code-wise

2020-04-07 16:05 UTC, marefr commented
@bergquist pushed a fix for handling of error when starting grafana which will make Grafana server stop.

2020-04-14 18:53 UTC, bergquist approved these changes
LGTM!

2020-04-14 18:53 UTC, bergquist commented
Thank you for contributing to Grafana! :)

2020-04-14 18:54 UTC, merged