Dashboard: Add folderFromFileStructure option to dashboard provisioning config
grafana/grafana pull request #23117
Opened 2020-03-26 15:19 UTC by nabokihms

**What this PR does / why we need it**:
This PR adds the ability to use folders structure from the filesystem to create desired folders in Grafana while dashboard provisioning. 

With this patch, you can use only one provider to provision dashboards which locate in different folders in Grafana. And also you can change the dashboard folder just by changing the folder name on the filesystem.

**Which issue(s) this PR fixes**:
Fixes #12016

**Special notes for your reviewer**:
This patch is more like proof of concept, but we are using it in some environments.

**Issue(s), that might be related to the PR**:
https://github.com/grafana/grafana/issues/15716

2020-03-26 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=23117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=23117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=23117) it.</sub>

2020-03-31 10:39 UTC, bergquist requested changes
Updating config files while iterating over files makes it very hard to reason about the code :) https://github.com/grafana/grafana/pull/23117/files#diff-21bb6cab0207495bb263495c098a22dcR111 For a POC that's fine. But to merge this I'd like to see a cleaner implementation. 

Would you be up for rewriting this a bit? :)

2020-03-31 10:55 UTC, nabokihms commented
Good point, I will work on code to make it much cleaner and more efficient.

2020-03-31 11:03 UTC, bergquist commented
For this to get merged it would also require docs, updated example config files. But that can be solved once the code is in mergeable state.

2020-03-31 21:29 UTC, nabokihms commented
After some refactoring:
* `foldersFromFilesStructure` option extraction now locates in FileReader contructor 
*  Logic for different folder creation strategies now stored in two functions: `storeDashboardsInFolder` and `storeDashboardsInFoldersFromFileStructure` (this approach looks much cleaner to me)
* No more to config file updates during iteration

I also added unit tests for the `foldersFromFilesStructure` option.
So, please take a look! :)

2020-04-02 06:36 UTC, bergquist commented
Great! It might take some time before I can review this but I'm looking forward to it! :)

2020-04-16 07:22 UTC, bergquist commented
@nabokihms This looks better :) Could you please merge master and resolve conflicts?

2020-04-16 17:49 UTC, nabokihms commented
Merge conflicts are resolved. I also fixed the code according to lint rules (as in the master).

2020-04-30 18:47 UTC, nabokihms commented
/keepalive

2020-05-14 19:58 UTC, nabokihms commented
/keepalive

2020-05-29 08:03 UTC, nabokihms commented
/keepalive

2020-06-11 19:29 UTC, dpiessens commented
@bergquist Any time to approve this? It would help us a lot with provisioning.

2020-06-16 11:26 UTC, bergquist requested changes
Once again. Thank you for the patience! :)

A few minor comments. Could you please add docs for this as well?
https://github.com/grafana/grafana/blob/master/docs/sources/administration/provisioning.md#dashboards

2020-06-16 13:34 UTC, bergquist commented
If you dont have time or just got tired of waiting for me I can make those changes myself :) It's up to you

2020-06-16 14:10 UTC, nabokihms commented
Thanks for replying and reviewing! I will make the necessary changes before tomorrow.

2020-06-16 20:39 UTC, nabokihms commented on pkg/services/provisioning/dashboards/file_reader.go
> +		log.Warn(
Returning error is ok for me. It is much stricter and it will guard users against unwanted behavior.

2020-06-16 20:39 UTC, nabokihms commented on pkg/services/provisioning/dashboards/file_reader.go
> +	if foldersFromFilesStructure && cfg.Folder != "" {
My bad. I will fix it.

2020-06-16 22:00 UTC, nabokihms commented
So, I added a small doc about the new option and fixed the code by your suggestions as promised. Thanks a lot for your time! I hope that we will do another iteration of review soon.

2020-06-17 11:15 UTC, bergquist approved these changes
LGTM 

Thank you for your patience and for contributing to Grafana!

2020-06-17 11:15 UTC, bergquist commented on docs/sources/administration/provisioning.md
> +  folder: ''
```suggestion
```

2020-06-17 11:15 UTC, bergquist commented on docs/sources/administration/provisioning.md
> +> **Note.** `folder` and `folderUid` options should be equal to "" to make `foldersFromFileStructure` works.
```suggestion
> **Note.** `folder` and `folderUid` options should be empty or missing to make `foldersFromFileStructure` works.
```

2020-06-17 11:17 UTC, bergquist commented
Seems like I can't commit my suggestions so I'll fix those issues in another PR :)

2020-06-17 11:27 UTC, bergquist requested changes
Or hmm. I just found a bug that I think should be fixed before we merge this. 

Dashboards that are in the root folders of the path should be provisioned in the "General" folders. 
Using a config as below, dashboards in `devenv/dev-dashboards` end up in a folder names `dev-dashboards`

```yaml
apiVersion: 1

providers:
  - name: 'gdev dashboards'
    type: file
    allowUiUpdates: false
    updateIntervalSeconds: 60
    options:
      path: devenv/dev-dashboards
      foldersFromFilesStructure: true
```

2020-06-17 11:43 UTC, bergquist commented
And please dont force push commits. It makes it harder to review the last changes you made :)

2020-06-17 15:06 UTC, nabokihms commented
Yes, it should be fixed for sure. I sincerely apologize for that. However, I added the fix and also covered this case by unit tests. Now there is no such problem! :)

2020-06-18 09:17 UTC, bergquist commented
I've tested this quickly and it returns errors when starting grafana the second time with dashboards in the root of the provisioned folder.

2020-06-18 09:46 UTC, nabokihms commented
Ok, there is might be some error. I will investigate the cause of this behavior. 
Sorry for wasting your time again.

2020-06-18 10:25 UTC, nabokihms commented
Now I get it. According to the documentation `General` folder is a special one.
```
The General folder (id=0) is special and is not part of the Folder API
```
So, I need to use the default folder name `""` instead of `General`.  After that `getOrCreateFolderID` function will give me correct folder id `0`. 

I will it.

2020-06-30 13:30 UTC, bergquist approved these changes
LGTM

Thank you for contributing :)

2020-06-30 13:33 UTC, merged