Add SQL region annotation examples
grafana/grafana pull request #23268
Opened 2020-04-01 22:00 UTC by adeverteuil

**What this PR does / why we need it**:

Add SQL example for region annotation queries in MySQL, PostgreSQL and MSSQL.

Also specifies this is supported from Grafana v6.6+.

I didn't test the rendered HTML output in a dev environment.

2020-04-02 20:11 UTC, oddlittlebird reviewed
LGTM, but I suggest getting a technical review from someone who knows SQL.

2020-04-03 08:21 UTC, marefr requested changes
Some suggestions to follow how we mark section to be supported in certain Grafana versions. Otherwise looks good

2020-04-03 08:21 UTC, marefr commented on docs/sources/features/datasources/mysql.md
> +From Grafana v6.6, region annotations (with a `timeend`) are supported in the MySQL plugin.
```suggestion
> Only available in Grafana v6.6+.
```

2020-04-03 08:21 UTC, marefr commented on docs/sources/features/datasources/postgres.md
> +From Grafana v6.6, region annotations (with a `timeend`) are supported in the PostgreSQL plugin.
```suggestion
> Only available in Grafana v6.6+.
```

2020-04-08 12:14 UTC, marefr approved these changes
Applied my suggestions. @oddlittlebird please approve/merge if you agree

2020-04-08 12:14 UTC, aknuds1 approved these changes
LGTM

2020-04-08 19:34 UTC, oddlittlebird commented
LGTM.

2020-04-09 00:32 UTC, merged

2020-04-09 00:33 UTC, marefr commented
Thanks @adeverteuil