Image Rendering: Remove PhantomJS support
grafana/grafana pull request #23460
Opened 2020-04-09 08:50 UTC by marefr

**What this PR does / why we need it**:
Removes PhantomJS

- [x] Remove use of PhantomJS - step 1 #23375 
- [ ] Verify docker images
- [ ] Add guards for renderer not available/installed, if needed
- [ ] Improve UX for share panel/direct linkI rendered image when there are no renderer available/installed
- [ ] Enterprise updates

**Which issue(s) this PR fixes**:
Closes #13802

**Special notes for your reviewer**:

2020-04-15 16:43 UTC, marefr commented
For reviewers,  #23375 and #23593 have already been merged into this PR. This PR adds some custom docker build fixes and breaking change and upgrading notes. Idea is to handle required UX changes in a follow up PR.

2020-04-15 17:14 UTC, oddlittlebird requested changes
Please edit the [Image rendering](https://grafana.com/docs/grafana/latest/administration/image_rendering/) topic as well.

2020-04-15 17:14 UTC, oddlittlebird commented on CHANGELOG.md
> +- **Removal of PhantomJS**: PhantomJS was deprecated in [Grafana v6.4](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#phantomjs-deprecation) and starting from Grafana v7.0.0 Phanto
```suggestion
- **Removed PhantomJS**: PhantomJS was deprecated in [Grafana v6.4](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#phantomjs-deprecation) and starting from Grafana v7.0.0, all PhantomJS support has been removed. This means that Grafana no longer ships with a built-in image renderer, and we advise you to install the [Grafana Image Renderer plugin](https://grafana.com/grafana/plugins/grafana-image-renderer).
```

2020-04-15 17:14 UTC, oddlittlebird commented on docs/sources/installation/upgrading.md
> +PhantomJS was deprecated in [Grafana v6.4](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#phantomjs-deprecation) and starting from Grafana v7.0.0 PhantomJS support have been remove
```suggestion
PhantomJS was deprecated in [Grafana v6.4](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#phantomjs-deprecation) and starting from Grafana v7.0.0, all PhantomJS support has been removed. This means that Grafana no longer ships with a built-in image renderer, and we adwise you to install the [Grafana Image Renderer plugin](https://grafana.com/grafana/plugins/grafana-image-renderer).
```

2020-04-15 19:23 UTC, oddlittlebird reviewed
LGTM!

2020-04-15 19:24 UTC, oddlittlebird approved these changes

2020-04-15 20:17 UTC, merged

2020-04-16 06:36 UTC, aknuds1 reviewed
LGTM!