Update azuread.md
grafana/grafana pull request #23465
Opened 2020-04-09 11:24 UTC by salihzett

just the docu for clarifying the setting in Azure AD.
https://github.com/grafana/grafana/issues/23358

2020-04-09 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=23465) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=23465) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=23465) it.</sub>

2020-04-09 16:33 UTC, oddlittlebird requested changes
Looks pretty good, but all UI elements that you click need to be bold, not italic. Please review the [Documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md)

2020-04-29 13:38 UTC, oddlittlebird approved these changes

2020-04-29 13:39 UTC, oddlittlebird commented
Sorry, I must have missed this the first time around. Thanks for contributing to the docs!

2020-04-29 13:39 UTC, oddlittlebird commented
@aknuds1 , can you fix the build pipeline for this?

2020-04-29 13:43 UTC, aknuds1 requested changes
There's a typo, which breaks the build.

2020-04-29 13:43 UTC, aknuds1 commented on docs/sources/auth/azuread.md
> +    - In Addtional: Click *Add optional claim*, choose Token type ID, Access and SAML and claim to *email*.
```suggestion
    - In Additional: Click *Add optional claim*, choose Token type ID, Access and SAML and claim to *email*.
```

2020-04-29 13:44 UTC, aknuds1 commented
@oddlittlebird A typo in this PR broke the build, also the CLA isn't signed.

2020-05-14 19:54 UTC, daniellee commented
@salihzett can you sign the CLA please so that we can merge this PR?

2020-06-28 00:31 UTC, closed without merging