Updated reporting docs
grafana/grafana pull request #23616
Opened 2020-04-16 13:47 UTC by jongyllen

Added a never scheduling option, tried documenting it a bit.
Image is updated in separate PR to website

2020-04-16 17:46 UTC, oddlittlebird requested changes

2020-04-16 17:46 UTC, oddlittlebird commented on docs/sources/enterprise/reporting.md
> +   * Weekly/Daily/Hourly - schedules the report to be sent on desired intervals
```suggestion
   * Weekly/Daily/Hourly - Schedules the report to be sent at the desired interval.
```

2020-04-16 17:46 UTC, oddlittlebird commented on docs/sources/enterprise/reporting.md
> +2. **Save** the report.
```suggestion
1. **Save** the report.
```

2020-04-17 07:19 UTC, xlson approved these changes

2020-04-17 14:59 UTC, oddlittlebird approved these changes

2020-04-29 07:45 UTC, jongyllen commented
This will be fixed by @sakjur in another pr

2020-04-29 07:45 UTC, closed without merging