Fixes and security patches:
grafana/grafana pull request #23749
Opened 2020-04-21 17:20 UTC by srclosson

1. Always keep the source directory, just don't package the source
2. Do not publish the SSH key for common plugin tasks.
Changed to environment variable

Fixes: #

2020-04-22 06:44 UTC, briangann approved these changes
LGTM!

2020-04-22 22:51 UTC, ryantxu requested changes

2020-04-22 22:51 UTC, ryantxu commented on packages/grafana-toolkit/src/cli/tasks/plugin.utils.ts
> -    ['git', ['rm', '-rf', 'src'], { enterprise: true }],
enterprise plugins should remove src

2020-04-23 18:56 UTC, ryantxu approved these changes
LGTM

2020-04-23 18:58 UTC, merged