Forms migration: Data/Panel link editor
grafana/grafana pull request #23778
Opened 2020-04-22 10:37 UTC by tskarhed

#22862
We might need some kind of separator for the Data links, as it is a bit unclear where one begins and the other ends.
![Screenshot from 2020-04-22 12-27-42](https://user-images.githubusercontent.com/1438972/79972150-c5198900-8495-11ea-93f4-a3cd094a1d76.png)
![Screenshot from 2020-04-22 12-28-02](https://user-images.githubusercontent.com/1438972/79972151-c5b21f80-8495-11ea-8349-16ebf53bc7af.png)

2020-04-22 10:37 UTC, tskarhed commented on packages/grafana-ui/src/components/DataLinks/DataLinkEditor.tsx
> +  onRemove?: (link: DataLink) => void;
Will making this optional have any consequences?

2020-04-22 10:38 UTC, torkelo commented
Dam think you misunderstood how the inline should work , it should not be a form. It should be unchanged. Only change the modal form

2020-04-22 10:39 UTC, tskarhed commented
Okay, gotcha!

2020-04-22 12:05 UTC, tskarhed commented
Now data links look like this in the Graph panel too!
![Screenshot from 2020-04-22 14-04-48](https://user-images.githubusercontent.com/1438972/79979733-4545eb80-84a2-11ea-9ed6-30bfe5d8d910.png)

2020-04-22 14:25 UTC, torkelo commented
Can we move the switch toggle in the bottom in the modal form? Looks a bit strange in the middle between those two big inputs

2020-04-22 16:21 UTC, tskarhed commented
I think I broke the syntax highlighting :disappointed: Going to have a look at it tomorrow

2020-04-23 06:01 UTC, dprokop commented on packages/grafana-ui/src/components/DataLinks/DataLinksEditor.tsx
> -};
Removing this fn is the reasons why syntax highlighting is not working

2020-04-23 06:01 UTC, dprokop commented on packages/grafana-ui/src/components/DataLinks/DataLinksEditor.tsx
> -    enableDatalinksPrismSyntax();
and this call is required for syntax highlighting to work

2020-04-23 09:43 UTC, dprokop approved these changes
Looks and works great! 

@aocenas can you please check if derived field links work as expected?

2020-04-23 09:44 UTC, dprokop requested changes
Some sizing issue in Elasticsearch data links:

![image](https://user-images.githubusercontent.com/2376619/80084875-c9a67600-8557-11ea-85fb-12ccb7a89dff.png)

Sorry for my bipolar approve-request changes :D

2020-04-23 12:45 UTC, tskarhed commented
Fixed!
![Screenshot from 2020-04-23 14-44-19](https://user-images.githubusercontent.com/1438972/80100964-06329b80-8571-11ea-8303-fa783971100b.png)

2020-04-24 07:25 UTC, dprokop approved these changes
Looks good now!

2020-04-24 07:26 UTC, merged

2020-04-24 10:31 UTC, aocenas commented
@dprokop sorry for late response I see you already checked but yeah don't see any issue right now.

2020-04-24 10:32 UTC, dprokop commented
@aocenas no worries, I've tested it too and it seems to work just fine