multiple changes to make document easier to read
grafana/grafana pull request #23842
Opened 2020-04-24 04:44 UTC by Mohit-Nain

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-04-24 19:48 UTC, oddlittlebird requested changes

2020-04-24 19:48 UTC, oddlittlebird commented on docs/sources/features/datasources/loki.md
> +Another way to add a label selector, is in the table section, clicking on the **Filter** button beside a label will add the label to the query expression. This even works for multiple queries and wil
```suggestion
Another way to add a label selector is in the table section. Click **Filter** beside a label to add the label to the query expression. This even works for multiple queries and will add the label selector to each query.
```

2020-04-25 09:41 UTC, aknuds1 requested changes

2020-04-25 09:41 UTC, aknuds1 commented on docs/sources/features/datasources/loki.md
> +You can use this functionality to link your tracing backend directly from your logs, or link a user profile page if a userId is present in the log line. These links will be shown in the [log details]
I think this change is wrong, the original wording should be kept.

2020-04-25 09:41 UTC, aknuds1 commented on docs/sources/features/datasources/loki.md
> +- **Regex:** A Regex pattern that runs on the log message and captures part of it as the value of the new field. Can only contain pattern to capture a single group.
```suggestion
- **Regex:** A Regex pattern that runs on the log message and captures part of it as the value of the new field. Can only contain a single capture group.
```

2020-04-26 15:33 UTC, aknuds1 requested changes

2020-04-26 15:33 UTC, aknuds1 commented on docs/sources/features/datasources/loki.md
> +You can use this functionality to link your tracing backend directly from your logs, or link a user profile page if a userId is present in the log line. These links appear in the [log details](/featu
```suggestion
You can use this functionality to link to your tracing backend directly from your logs, or link to a user profile page if a userId is present in the log line. These links appear in the [log details](/features/explore/#labels-and-parsed-fields).
```

2020-04-27 05:30 UTC, aknuds1 approved these changes
LGTM

2020-04-27 19:21 UTC, oddlittlebird approved these changes
LGTM. Thanks for improving this doc!

2020-04-27 19:21 UTC, merged