Suggesting multiple changes for better readability
grafana/grafana pull request #23843
Opened 2020-04-24 05:19 UTC by Mohit-Nain

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-04-24 14:49 UTC, oddlittlebird requested changes

2020-04-24 14:49 UTC, oddlittlebird commented on docs/sources/features/datasources/mssql.md
> +When above query is used in a graph panel the result will be two series named `Metric A` and `Metric B` with a sum of `valueTwo` plotted over `time`.
```suggestion
When the above query is used in a graph panel, the result is two series named `Metric A` and `Metric B` with a sum of `valueTwo` plotted over `time`.
```

2020-04-24 14:49 UTC, oddlittlebird commented on docs/sources/features/datasources/mssql.md
> +Stored procedures have been verified to work. However, please note that we haven't done anything special to support this so there may exist edge cases where it won't work as you would expect.
```suggestion
Stored procedures have been verified to work. However, please note that we haven't done anything special to support this, so there might be edge cases where it won't work as you would expect.
```

2020-04-24 14:49 UTC, oddlittlebird commented on docs/sources/features/datasources/mssql.md
> +We're mimicking the `$__timeGroup(time, '5m')` in the select and group by expressions and that's why there are a lot of lengthy expressions needed -
```suggestion
We're mimicking the `$__timeGroup(time, '5m')` in the select and group by expressions, and that's why there are a lot of lengthy expressions needed -
```

2020-04-27 11:50 UTC, aknuds1 approved these changes

2020-04-27 11:51 UTC, aknuds1 approved these changes

2020-04-27 19:31 UTC, oddlittlebird approved these changes
LGTM. Thanks for improving this doc!

2020-04-27 19:31 UTC, merged