Tracing: add zipkin support
grafana/grafana pull request #23887
Opened 2020-04-25 12:46 UTC by MarcelHillmann

What this PR does / why we need it:
As operator I would like to see how the Prometheus netwerk is working.

To improve this target, I implemented a Zipkin client.

2020-04-27 08:21 UTC, bergquist commented
Hi! Thank you for taking the time to contribute to Grafana. 

Wouldnt you be able to use https://grafana.com/docs/grafana/latest/installation/configuration/#zipkin-propagation to achieve the same results? We are currently swamped with work for 7.0 so response might be slow :)

2020-04-28 15:54 UTC, MarcelHillmann commented
Hi @bergquist 

that dosn't works, my backend ist ZIPKIN and not Jaeger.

Thanks
Marcel

2020-06-12 12:01 UTC, marefr requested changes
Looks good. Verified it works and that Jaeger still works as before. Need some minor changes. See comments and below

Need to update defaults.ini and sample.ini as well with similar info as you've added to documentation: 
- https://github.com/grafana/grafana/blob/master/conf/defaults.ini
- https://github.com/grafana/grafana/blob/master/conf/sample.ini

2020-06-12 12:01 UTC, marefr commented on docs/sources/installation/configuration.md
> +### tracing128bit
Would suggest renaming this to `use_128_bit_trace_ids` and update related code.

2020-06-23 13:54 UTC, marefr commented
@MarcelHillmann let us know if you're planning to address review comments and/or you'll need help. Thanks

2020-08-08 08:04 UTC, closed without merging