CloudWatch: Added AWS WAFV2 metrics
grafana/grafana pull request #24048
Opened 2020-04-29 12:14 UTC by mikkokupsu

**What this PR does / why we need it**:
Added AWS WAFV2 metrics.

**Which issue(s) this PR fixes**:
No issue.

**Special notes for your reviewer**:
AWS documentation about WAFV2 metrics is not up-to-date but these metrics and dimensions are visible in my AWS account.

2020-04-29 12:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=24048) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=24048) before we can accept your contribution.<br/><hr/>**Kupsu Mikko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=24048) it.</sub>

2020-05-15 05:44 UTC, mikkokupsu commented
@aknuds1 would you be willing to review this PR or point me to a person whom I could request a review?

2020-05-25 11:34 UTC, aknuds1 commented
@mikkokupsu We're looking at it, but our main CW expert is on leave. Hopefully we'll come to a conclusion soon.

2020-05-25 11:48 UTC, papagian requested changes
Thank you for your contribution!

According to this [document](https://docs.aws.amazon.com/waf/latest/APIReference/API_VisibilityConfig.html) I understand that the metrics/dimensions should be the same with [`AWS WAF`](https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html#waf-metrics), therefore I think that `PassedRequests` should be included in the metrics and `RuleGroup` in the dimensions.

2020-05-25 11:50 UTC, aknuds1 requested changes

2020-05-25 11:50 UTC, aknuds1 commented on pkg/tsdb/cloudwatch/metric_find_query.go
> +		"AWS/WAFV2":             {"AllowedRequest", "BlockedRequests", "CountedRequests"},
I think this should be [AllowedRequests](https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html#waf-metrics)? Also, should we include PassedRequests?
```suggestion
		"AWS/WAFV2":             {"AllowedRequests", "BlockedRequests", "CountedRequests", "PassedRequests"},
```

2020-05-25 11:50 UTC, aknuds1 commented on pkg/tsdb/cloudwatch/metric_find_query.go
> +		"AWS/WAFV2":             {"Region", "Rule", "WebACL"},
Looks to me as if [RuleGroup](https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html#waf-metrics) is among the dimensions:
```suggestion
		"AWS/WAFV2":             {"Region", "Rule", "WebACL", "RuleGroup"},
```

2020-05-25 12:00 UTC, aknuds1 commented
@mikkokupsu I've resolved the merge conflicts locally, do you want me to push the result to your fork?

2020-06-08 11:35 UTC, aknuds1 approved these changes

2020-06-08 12:04 UTC, aknuds1 commented
@papagian It look OK to you?

2020-06-09 06:50 UTC, papagian approved these changes
LGTM!

2020-06-09 06:51 UTC, merged