Fix - Elasticsearch - multi bucket script
grafana/grafana pull request #24064
Opened 2020-04-29 19:40 UTC by MarceloNunesAlves

Problem:

When you add more than one bucket script in the query it shows only one column.

<img src="https://filebin.net/9we7asyw0llyulva/problem.png?t=31w5upw4">

Solution:

In the parser when it was configurate more than one bucket it put the formula in name column. The same process in the groupby date histogram.

<img src="https://filebin.net/hwqajsnnynbn2308/solution.png?t=x242aaxo">

2020-04-29 19:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=24064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=24064) before we can accept your contribution.<br/><hr/>**Marcelo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=24064) it.</sub>

2020-04-29 21:44 UTC, MarceloNunesAlves commented
I've signed

2020-05-05 15:11 UTC, lefranchi approved these changes

2020-05-19 16:09 UTC, MarceloNunesAlves commented
I need it to be reviewed to merge. This correction is very important to someone use elasticsearch.

2020-05-22 13:11 UTC, aocenas commented
@MarceloNunesAlves thanks for the contribution and sorry for the late review. I am checking the issue with current master and I think this was already solved by updates to the data logic in Grafana. Right now what I get:

![Screenshot from 2020-05-22 15-09-21](https://user-images.githubusercontent.com/1014802/82670956-5ff4b700-9c3e-11ea-99bc-53279f0cf6a9.png)

with this transform to join all the dataframes:
![Screenshot from 2020-05-22 15-10-12](https://user-images.githubusercontent.com/1014802/82670962-6125e400-9c3e-11ea-88f6-ccf732b5d394.png)

Let me know if this also solves your usecase.

2020-05-22 13:19 UTC, MarceloNunesAlves commented
@aocenas Ok! But change Date Histogram to terms.

2020-05-22 13:51 UTC, aocenas commented
Ah right did not notice that. It would be great though if those 2 modes gave you the same column names. Seems like this part of code is responsible for interpolating the script variable names https://github.com/grafana/grafana/blob/8d81aab13d3a2ce0b292c03cacdfdf349cfe2be1/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L268-L277. All the info needed there seems to be available in the `processAggregationDocs` method so it seems feasible to extract that into separate function and reuse it there to get consistent naming.

Do you have time to try something like that?

2020-05-24 00:54 UTC, MarceloNunesAlves commented
@aocenas, 
I tried to use the field "Select field" to alias but it didn't work. In this moment I don't have time but it solution solve the problem.

2020-06-05 21:57 UTC, MarceloNunesAlves commented
Can't approve the fix?

2020-06-16 19:29 UTC, MarceloNunesAlves commented
@torkelo, could you review my commit?

2020-06-17 07:02 UTC, torkelo commented
I think @aocenas comment is correct, the same naming logic should be used for both date histogram (time series) result and table results (no date histogram)

2020-06-17 11:31 UTC, aocenas commented
@torkelo Even though fixing the naming would be ideal I think we can merge this (after adding some unit test). It fixes an issue so it adds a value as it is and reusing the code that does the naming needs some refactoring so we could do that separately.

2020-06-17 11:37 UTC, torkelo commented
ok, agree. Then it's only a test that would be good, and make sure this code is matched on the backend implementation

2020-06-30 18:29 UTC, MarceloNunesAlves commented
Hey guys, done!

2020-07-02 18:41 UTC, davkal submitted a review, later dismissed
Thanks for adding the test.

Do you mind patching https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/response_parser.go#L376 ?

2020-07-02 19:13 UTC, MarceloNunesAlves commented
Ok! Thanks @davkal

2020-07-03 21:38 UTC, MarceloNunesAlves commented
@davkal, done! tks

2020-07-06 09:51 UTC, marefr requested changes
See suggestion

2020-07-06 09:51 UTC, marefr commented on pkg/tsdb/elasticsearch/response_parser.go
> +						metricName, _ = metric.Settings.Get("script").String()
```suggestion
						metricName = metric.Settings.MustString("script")
```

2020-07-06 15:06 UTC, MarceloNunesAlves commented
@marefr, I've removed because this code didn't return what it needed.

2020-07-06 15:08 UTC, MarceloNunesAlves commented
@marefr, this problem:

![grafana_bug](https://user-images.githubusercontent.com/35287700/86608742-52db1f80-bf81-11ea-9fa3-5a64dac0e226.png)

2020-07-06 15:13 UTC, marefr commented on pkg/tsdb/elasticsearch/response_parser.go
> +						metricName, _ = metric.Settings.Get("script").String()
Sorry, this was what it should have been.

```suggestion
						metricName = metric.Settings.Get("script").MustString("")
```

2020-07-06 17:09 UTC, MarceloNunesAlves commented
@marefr, done! tks

2020-07-07 20:17 UTC, MarceloNunesAlves commented
@marefr/@davkal/@torkelo, is it ok now?

2020-07-07 23:31 UTC, marefr approved these changes
LGTM

2020-07-08 12:19 UTC, MarceloNunesAlves commented
@marefr, thank you so much!

2020-07-09 13:21 UTC, merged

2020-07-09 13:21 UTC, aocenas commented
@MarceloNunesAlves thanks again for the contribution :+1: