Update Bitcoin currency to use proper symbol, add mBTC and μBTC
grafana/grafana pull request #24182
Opened 2020-05-02 14:37 UTC by overcookedpanda

This is an update to the changes I submitted in https://github.com/grafana/grafana/pull/13125
Based on https://github.com/grafana/grafana/pull/13125#issuecomment-477138503 and https://github.com/grafana/grafana/issues/8564 :)

2020-05-16 16:13 UTC, overcookedpanda commented
Please don't mark as stale :)

2020-05-20 21:20 UTC, phemmer commented
While this may be the more accurate representation of the symbol, it does not render well on many systems. For example mine. While the old symbol is fine.
![image](https://user-images.githubusercontent.com/1826947/82498431-f8176280-9abd-11ea-8112-5b56e1953f25.png)

2020-05-21 02:18 UTC, overcookedpanda commented
Ah, I also believe that's why I used the current symbol in the first PR I submitted, but it seemed to render properly on the commit, however, I did notice the same issue inside my IDE when I was making this, but figured it would render properly in modern browsers.

![image](https://user-images.githubusercontent.com/35861207/82516016-5bfe5300-9adf-11ea-8914-a600e6f0dd6e.png)

2020-06-03 06:47 UTC, mckn commented on devenv/dev-dashboards-without-uid/panel_tests_polystat.json
> +              "text": "micro Bitcoin (mBTC)",
```suggestion
              "text": "Millibitcoin (mBTC)",
```

2020-06-03 06:52 UTC, mckn requested changes
Love the idea to add these to the code base but looks like you have mixed the units together. Please update the units to reflect this list: https://en.bitcoinwiki.org/wiki/Units

2020-06-03 06:53 UTC, mckn commented on devenv/dev-dashboards/panel-polystat/polystat_test.json
> +              "text": "milli Bitcoin (μBTC)",
```suggestion
              "text": "Micro Bitcoin (μBTC)",
```

2020-06-03 06:53 UTC, mckn commented on devenv/dev-dashboards/panel-polystat/polystat_test.json
> +              "text": "micro Bitcoin (mBTC)",
```suggestion
              "text": "Milli Bitcoin (mBTC)",
```

2020-06-03 06:54 UTC, mckn commented on packages/grafana-data/src/valueFormats/categories.ts
> +      { name: 'milli Bitcoin (B͈̎)', id: 'currencyμBTC', fn: currency('μBTC') },
```suggestion
      { name: 'Micro Bitcoin (B͈̎)', id: 'currencyμBTC', fn: currency('μBTC') },
```

2020-06-03 06:54 UTC, mckn commented on packages/grafana-data/src/valueFormats/categories.ts
> +      { name: 'milli Bitcoin (B͈̎)', id: 'currencyμBTC', fn: currency('μBTC') },
```suggestion
      { name: 'Milli Bitcoin (B͈̎)', id: 'currencymBTC', fn: currency('mBTC') },
      { name: 'Micro Bitcoin (B͈̎)', id: 'currencyμBTC', fn: currency('μBTC') },
```

2020-06-03 12:20 UTC, mckn approved these changes
Great work! LGTM. Thanks for adding this @overcookedpanda 🙏

2020-06-03 12:47 UTC, mckn commented
@overcookedpanda can you latest master into this branch so it can be merged?

2020-06-03 13:15 UTC, overcookedpanda commented
> @overcookedpanda can you latest master into this branch so it can be merged?

Done. Thank you again.

2020-06-03 13:48 UTC, mckn commented
> While this may be the more accurate representation of the symbol, it does not render well on many systems. For example mine. While the old symbol is fine.
> ![image](https://user-images.githubusercontent.com/1826947/82498431-f8176280-9abd-11ea-8112-5b56e1953f25.png)
> 
> IIRC, this discussion came up when the currency was first proposed several years ago.

Great feedback! I have verified it in Safari, Chrome and Mozilla and it seems to be rendered correct so I think we can proceed with this one.

2020-06-03 14:06 UTC, phemmer commented
> > While this may be the more accurate representation of the symbol, it does not render well on many systems. For example mine. While the old symbol is fine.
> > ![image](https://user-images.githubusercontent.com/1826947/82498431-f8176280-9abd-11ea-8112-5b56e1953f25.png)
> > IIRC, this discussion came up when the currency was first proposed several years ago.
> 
> Great feedback! I have verified it in Safari, Chrome and Mozilla and it seems to be rendered correct so I think we can proceed with this one.

That screenshot was taken from Chrome.

2020-06-03 14:40 UTC, phemmer commented
Oh, and this is what it looks like on my phone (Android 9)
![image](https://user-images.githubusercontent.com/1826947/83650643-927ba980-a586-11ea-9528-130372758849.png)

2020-06-03 15:05 UTC, overcookedpanda commented
In Chrome Version 83.0.4103.61 (Official Build) (64-bit) for Windows 10 I see the following:
![image](https://user-images.githubusercontent.com/35861207/83652835-af14e300-a580-11ea-85a6-5a79d952aacb.png)

Using Chrome Version 83.0.4103.88 on an iPhone I see the following:
![image](https://user-images.githubusercontent.com/35861207/83653724-be486080-a581-11ea-9d15-3f2391d15aa8.png)

Safari:
![image](https://user-images.githubusercontent.com/35861207/83653742-c7393200-a581-11ea-9e5a-359de7c24595.png)

2020-06-05 08:04 UTC, mckn commented
@torkelo @dprokop what to you guys think regarding the bitcoin sign?

2020-06-08 07:10 UTC, torkelo commented
Think we will have to wait a while for this one as it looks wrong for me as well (Chrome 81, Ubuntu 18)

2020-06-08 07:41 UTC, mckn commented
> Think we will have to wait a while for this one as it looks wrong for me as well (Chrome 81, Ubuntu 18)

what do you think about revering the bitcoin sign but merge the milli and micro BTC? @torkelo

2020-06-08 09:07 UTC, torkelo commented
that will work

2020-06-11 07:13 UTC, merged

2020-07-06 04:48 UTC, phemmer commented
Was doing some unicode stuff when I stumbled across the `₿` symbol. I found it odd that my browser was rendering this properly considering the recent discussion on this PR. But it appears that this is a completely different symbol than what was proposed. In fact, it seems this symbol is the "official" symbol as well (however official a decentralized currency with no owner can be), at least according to [wikipedia](https://en.wikipedia.org/wiki/Bitcoin).

Anyway, just mentioning in case you wanted to revive the issue.

2020-07-07 12:10 UTC, mckn commented
> Was doing some unicode stuff when I stumbled across the `₿` symbol. I found it odd that my browser was rendering this properly considering the recent discussion on this PR. But it appears that this is a completely different symbol than what was proposed. In fact, it seems this symbol is the "official" symbol as well (however official a decentralized currency with no owner can be), at least according to [wikipedia](https://en.wikipedia.org/wiki/Bitcoin).
> 
> Anyway, just mentioning in case you wanted to revive the issue.

Interesting, maybe something worth opening a new PR on? Not sure how much this is used and how big of an issue it is.

2020-07-07 12:32 UTC, overcookedpanda commented
> Was doing some unicode stuff when I stumbled across the `₿` symbol. I found it odd that my browser was rendering this properly considering the recent discussion on this PR. But it appears that this is a completely different symbol than what was proposed. In fact, it seems this symbol is the "official" symbol as well (however official a decentralized currency with no owner can be), at least according to [wikipedia](https://en.wikipedia.org/wiki/Bitcoin).
> 
> Anyway, just mentioning in case you wanted to revive the issue.

I confirmed that this symbol works with Brave on Linux which did not work last time, however, it seems iOS has some issue with this one, lol.

In the Mail app's preview I see the following, which looks good: 
![image](https://user-images.githubusercontent.com/35861207/86781651-c3d31380-c023-11ea-8d73-b2d073a06f63.png)

However, once I open the PR and view I see that it does not render correctly:
![image](https://user-images.githubusercontent.com/35861207/86781723-d77e7a00-c023-11ea-8c6a-62d8aaae6d22.png)

I would think it would be best to keep using the Thai Baht symbol for the time being, and just check for support later and re-visit the issue.