Correcting one of the usage in documentation
grafana/grafana pull request #24197
Opened 2020-05-03 19:06 UTC by amalkurup89

**What this PR does / why we need it**: Documentation fix

**Which issue(s) this PR fixes**: Correcting one of the usage in documentation

2020-05-04 13:00 UTC, amalkurup89 commented
@oddlittlebird Can you please review

2020-05-04 13:58 UTC, amalkurup89 commented
@aknuds1 Can you please review

2020-05-05 16:17 UTC, oddlittlebird requested changes
The original wording is confusing. Here's my suggestion, feel free to improve it if you think of something better.

2020-05-05 16:17 UTC, oddlittlebird commented on docs/sources/variables/advanced-variable-format-options.md
> +Formats multi-valued variable in custom format for OpenTSDB.
```suggestion
Formats variables with multiple values in custom format for OpenTSDB.
```

2020-05-05 17:12 UTC, amalkurup89 commented
> The original wording is confusing. Here's my suggestion, feel free to improve it if you think of something better.

Looks good to me as well. Do you have any more suggestions

2020-05-06 14:14 UTC, amalkurup89 commented
@oddlittlebird Can you please merge, if changes look good to you

2020-05-06 16:43 UTC, oddlittlebird approved these changes
LGTM. Thanks for contributing!

2020-05-06 16:43 UTC, merged