Chore: spelling - theme
grafana/grafana pull request #24434
Opened 2020-05-08 13:06 UTC by jsoref

**What this PR does / why we need it**:

This fixes a number of spelling errors.

**Special notes for your reviewer**:

Comments on file changes can be found in #24412

2020-05-22 18:19 UTC, jsoref commented
@sakjur ?

2020-06-04 14:14 UTC, dprokop requested changes
Thanks for your contribution @jsoref! Can you please remove the lines I have commented on and we should be good to go?

2020-06-04 14:14 UTC, dprokop commented on public/sass/components/_panel_graph.scss
>    -webkit-transform: translateX(-50%) translateY(-50%) rotate(-90deg);
we can remove these lines

2020-06-04 14:14 UTC, dprokop commented on public/sass/components/_panel_graph.scss
>    -webkit-transform: translateX(50%) translateY(-50%) rotate(90deg);
we can remove these lines

2020-06-04 14:48 UTC, dprokop approved these changes
Now it looks good

2020-06-05 08:53 UTC, merged