Add docs for variable interpolation in plugins
grafana/grafana pull request #24446
Opened 2020-05-08 15:22 UTC by marcusolsson

**What this PR does / why we need it**:

Adds a guide on how to interpolate template variables for panel and data source plugins.

2020-05-08 16:08 UTC, ryantxu approved these changes

2020-05-08 17:30 UTC, oddlittlebird requested changes
More great plugin content!

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +# Interpolate variables in plugins
Please update the file name to match the topic title.

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +We'll see how you can turn a string like this:
OMG, this is a GREAT thing to have in an intro.

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +Variables are placeholders for values, and can be used to create things like templated queries. For more information on variables, refer to [Templates and variables]({{< relref "../../variables/templ
```suggestion
Variables are placeholders for values and can be used to create things like templated queries and dashboard or panel links. For more information on variables, refer to [Templates and variables]({{< relref "../../variables/templates-and-variables.md" >}}).
```

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +## Panels
This heading and the next both seem very vague. Can you make them more specific? WHAT about panels? Support panel variables? Add support for variables in panels to your plugin? I really don't know what this section is about based on the headings.

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +Add `replaceVariables` to the argument list, and pass it a user-defined template string:
```suggestion
Add `replaceVariables` to the argument list, and pass it a user-defined template string.
```

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/developers/plugins/variables.md
> +Add `replaceVariables` to the argument list, and pass it a user-defined template string:
As I commented in your other PR, you can go either way with the colons as long as you are consistent in your usage.

2020-05-08 17:30 UTC, oddlittlebird commented on docs/sources/menu.yaml
> +        - name: Variables
Please make this side menu label more descriptive. Plugin variables? Variable support?

2020-05-11 14:49 UTC, oddlittlebird approved these changes

2020-05-11 21:26 UTC, merged