Docs: Updated instructions on screens for Dashboard Import
grafana/grafana pull request #24584
Opened 2020-05-12 13:35 UTC by peterholmberg

**What this PR does / why we need it**:
Import dashboard docs needed updating, also updated instructions since they seemed out of date.

**Special notes for your reviewer**:

2020-05-12 17:20 UTC, oddlittlebird requested changes

2020-05-12 17:20 UTC, oddlittlebird commented on docs/sources/reference/export_import.md
> +To import a dashboard click the + icon in the sidemenu, and click "import".
```suggestion
To import a dashboard click the + icon in the side menu, and then click **Import**. 
```

2020-05-12 17:20 UTC, oddlittlebird commented on docs/sources/reference/export_import.md
> +To import a dashboard click the + icon in the sidemenu, and click "import".
Please acquaint yourself with the [Grafana documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md)

2020-05-13 11:37 UTC, dprokop commented on docs/sources/reference/export_import.md
>  URL or paste dashboard json text directly into the text area.
```suggestion
From here you can upload a dashboard JSON file, paste a [Grafana.com](https://grafana.com) dashboard
URL or paste dashboard JSON text directly into the text area.
```

2020-05-13 11:37 UTC, dprokop approved these changes
👍

2020-05-14 12:10 UTC, merged