Correction in abbreviation
grafana/grafana pull request #24748
Opened 2020-05-15 18:47 UTC by amalkurup89

**What this PR does / why we need it**: Documentation fix

**Which issue(s) this PR fixes**: Correction in abbreviation

2020-05-15 19:55 UTC, amalkurup89 commented
@oddlittlebird Can you please review

2020-05-17 05:17 UTC, amalkurup89 commented
@oddlittlebird gentle reminder for approval 🙂

2020-05-18 19:54 UTC, oddlittlebird requested changes
Great catches! One minor change, then this is good to go.

2020-05-18 19:54 UTC, oddlittlebird commented on docs/sources/guides/whats-new-in-v5.md
> +## Dashboard model, persistent URL's and API changes
```suggestion
## Dashboard model, persistent URLs and API changes
```

2020-05-18 20:00 UTC, amalkurup89 commented
> Great catches! One minor change, then this is good to go.

@oddlittlebird  Thanks for the suggestion. I have committed it, as well

2020-05-18 20:55 UTC, oddlittlebird approved these changes
Rock and roll! Thanks for contributing to the docs!

2020-05-18 20:56 UTC, merged