Build: adding auto-generation and coverage of packages docs
grafana/grafana pull request #24876
Opened 2020-05-19 15:37 UTC by mckn

**What this PR does / why we need it**:
TBA

**Special notes for your reviewer**:
TBA

2020-06-04 14:19 UTC, dprokop commented on scripts/ci-reference-docs-metrics.sh
> +  echo -e "Wohoo! Less number of warnings compared to last build 🎉🎈🍾✨\n\nYou can lower the threshold from $WARNINGS_COUNT_LIMIT to $WARNINGS_COUNT in the:\nscripts/ci-reference-docs-metrics.sh"
👍

2020-06-04 14:24 UTC, dprokop requested changes
This is great! 💯 Can you also push the metrics to Graphite? This should happen on master only. Think you can add that to ci-frontend-metrics.sh script.

2020-06-04 14:31 UTC, aknuds1 requested changes

2020-06-04 14:31 UTC, aknuds1 commented on scripts/ci-reference-docs-metrics.sh
> +set -e
Adding `o pipefail` should ensure pipelines also fail I think if one of the steps fails.
```suggestion
set -eo pipefail
```

2020-06-04 14:31 UTC, aknuds1 commented on scripts/ci-reference-docs-metrics.sh
> +  echo -e "Wohoo! Less number of warnings compared to last build 🎉🎈🍾✨\n\nYou can lower the threshold from $WARNINGS_COUNT_LIMIT to $WARNINGS_COUNT in the:\nscripts/ci-reference-docs-metrics.sh"
```suggestion
  echo -e "Wohoo! Fewer warnings compared to last build 🎉🎈🍾✨\n\nYou can lower the threshold from $WARNINGS_COUNT_LIMIT to $WARNINGS_COUNT in the:\nscripts/ci-reference-docs-metrics.sh"
```

2020-06-15 04:20 UTC, hugohaggmark commented on scripts/ci-reference-docs-metrics.sh
> +fi
Nice touch!

2020-06-15 04:20 UTC, hugohaggmark approved these changes
Brilliant work on this! 🌟

2020-06-15 11:36 UTC, aknuds1 approved these changes
LGTM - just fixed a typo.

2020-06-15 11:36 UTC, aknuds1 commented on scripts/ci-reference-docs-metrics.sh
> +
Don't need this extra blank line.
```suggestion
```

2020-06-15 11:36 UTC, aknuds1 commented on scripts/ci-reference-docs-metrics.sh
> +  # this script needs to be run after the packages have been build and the api-extractor has completed.
```suggestion
  # this script needs to be run after the packages have been built and the api-extractor has completed.
```

2020-06-15 12:14 UTC, aknuds1 commented
Looks as if CI fails consistently: https://app.circleci.com/pipelines/github/grafana/grafana/10669/workflows/d946c5af-f6cc-4459-abe6-8bbe975e8735/jobs/467490.

2020-06-15 12:33 UTC, mckn commented
> Looks as if CI fails consistently: https://app.circleci.com/pipelines/github/grafana/grafana/10669/workflows/d946c5af-f6cc-4459-abe6-8bbe975e8735/jobs/467490.

ah, yeah! I will fix that one :)

2020-06-15 12:43 UTC, dprokop approved these changes
🎉

2020-06-16 07:33 UTC, merged