Elasticsearch: adds words highlight on logs query
grafana/grafana pull request #25057
Opened 2020-05-25 00:16 UTC by Estrax

**What this PR does / why we need it**:

Adds words highlight on logs query with Elasticsearch datasource.

**Which issue(s) this PR fixes**:

Fixes #20098

**Special notes for your reviewer**:

How to test it:
1. Open Explore
2. Select Elasticsearch Logs datasource
3. Type something in the logs query field.
4. Run query. The expression you entered is going to be highlighted in logs result.

2020-05-26 07:24 UTC, ivanahuckova reviewed
Works nicely if added just search word. Doesn't work if added query and search word (which I think would be a default case).
![image](https://user-images.githubusercontent.com/30407135/82871215-7f872a80-9f31-11ea-909f-042bad2f0741.png)

 Also it also doesn't work for Loki (we only highlight filtered expressions if I remember correctly). 
Another thing - it can be slightly confusing if we use query field for 2 different things - writing query and searching words. Maybe we could add a field for Logs queries, where you would add search words. And this would highlight text no matter what is the data source. But this plan would probably need UX.

2020-05-26 08:01 UTC, Estrax commented
@ivanahuckova 
> Also it also doesn't work for Loki (we only highlight filtered expressions if I remember correctly).

Yes, because of #24281 - we removed the old query syntax support.

> Another thing - it can be slightly confusing if we use query field for 2 different things - writing query and searching words. Maybe we could add a field for Logs queries, where you would add search words. And this would highlight text no matter what is the data source. But this plan would probably need UX.

I absolutely agree, but that's something for a separate PR. We should have an input field in the Explore Logs container that's just going to highlight results matching the expression (but shouldn't we indicate it on a graph as well?). I'll ping UX team about that.

2020-05-26 11:31 UTC, ivanahuckova commented
I think that we should add this to our feature requests list and if we agree on implementing, we should then consult with UX, as this is adding a new functionality. Also we could implement in in a way, that every datasource would handle it in the same way.

2020-05-26 11:34 UTC, ivanahuckova commented
I just found that there is actually a feature request for this: https://github.com/grafana/grafana/issues/23283

2020-05-28 09:42 UTC, aocenas commented
Yeah this won't work well and is more complex as we would have to parse the lucene query a bit as there can be things like `foo OR bar` or `field: value`.

2020-06-11 10:45 UTC, davkal requested changes
Even if we're considering to add a separate search/highlight/filter field, the highlighting of the query expression terms by default still makes sense. 
The term extraction needs to be more robust though, see https://lucene.apache.org/core/3_5_0/queryparsersyntax.html
for possible queries. I'd be fine with supporting only simple terms and boolean operators for this. This needs proper unit tests for a good set of example queries and their search term extraction.

2020-06-18 12:55 UTC, closed without merging