Docs: Update azuread.md to reflect Azure Portal Interface
grafana/grafana pull request #25420
Opened 2020-06-07 10:24 UTC by trallnag

Few months ago there was an update to the **App Registrations** page in Azure Portal (https://docs.microsoft.com/de-de/azure/active-directory/develop/app-registrations-training-guide-for-app-registrations-legacy-users). This updates the doc to fit the few minor changes:

* Sign-on url renamed to redirect url
* Endpoints overview moved
* Adding users/groups moved

2020-06-07 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=25420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=25420) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=25420) it.</sub>

2020-06-09 19:38 UTC, oddlittlebird commented
No complaints from a docs standpoint, @daniellee , please have someone review the content.

@trallnag , please resolve the conflicts.

2020-06-23 22:10 UTC, oddlittlebird commented
Go away, Stalebot!

2020-06-24 07:42 UTC, aknuds1 requested changes
Just a nit.

2020-06-24 07:42 UTC, aknuds1 commented on docs/sources/auth/azuread.md
> +1. Click on **Authentication** then **Add a platform** and pick **Web App**.
```suggestion
1. Click on **Authentication**, then **Add a platform** and pick **Web App**.
```

2020-06-24 08:29 UTC, aknuds1 commented
We need someone with Azure familiarity to review. @daniellee?

2020-07-08 17:34 UTC, oddlittlebird commented
@kylebrandt ?

2020-07-08 19:25 UTC, kylebrandt commented
note: english documentation link is https://docs.microsoft.com/en-us/azure/active-directory/develop/app-registrations-training-guide-for-app-registrations-legacy-users

2020-07-08 19:45 UTC, kylebrandt approved these changes

2020-07-08 23:30 UTC, merged