Use Header.Set and Header.Del for X-Grafana-User header
grafana/grafana pull request #25495
Opened 2020-06-09 21:44 UTC by beardhatcode

This ensures that the X-Grafana-User header can be trusted.

If the configuration enabled the setting of this header, the
server can now trust that X-Grafana-User is set/unset by Grafana.

Before this, an anonymous user could simply set the X-Grafana-User
header themselves (using the developer tool for example)

---

**What this PR does / why we need it**: 

This edit is needed to ensure that the X-Grafana-User can be trusted.

**Which issue(s) this PR fixes**:

- The one I was going to create for this issue which I came across while attempting to ensure only logged-in users could access all metrics. Non logged in users can simply spoof the header using eg. the DevTools to add the header themselves.

**Special notes for your reviewer**:

Thanks for reviewing this. There is some code duplication here, maybe this could be fixed more cleanly but I'm not familiar enough with the codebase to know where this would go.

2020-06-10 14:11 UTC, marefr approved these changes
LGTM

2020-06-10 14:19 UTC, marefr requested changes
Was too fast reviewing. Please have a look at the comment.

2020-06-11 15:46 UTC, marefr commented on pkg/api/pluginproxy/pluginproxy.go
> +		if cfg.SendUserHeader {
I know that. But looking at this now feels like a potential security problem that someone could send the X-Grafana-User from client when `SendUserHeader` is disabled. So I still would like to see this change, but I can help out with that and/or fix it in another PR. Your call.

2020-06-11 18:46 UTC, beardhatcode commented on pkg/api/pluginproxy/pluginproxy.go
> +		if cfg.SendUserHeader {
You are right, good call.

Now I always delete the header first and if logged in and the setting is enabled, the header is set.

2020-06-11 19:02 UTC, marefr approved these changes
LGTM

2020-06-11 19:15 UTC, merged

2020-06-11 19:15 UTC, marefr commented
Thank you for contributing to Grafana!