Docs: Edit plugin signature topics
grafana/grafana pull request #25491
Opened 2020-06-09 19:28 UTC by oddlittlebird

**What this PR does / why we need it**: Cleans up minor formatting and grammar issues.

Fixes #

**Special notes for your reviewer**:

2020-06-10 15:28 UTC, marefr requested changes
Looks good. Couple comments/suggestions.

2020-06-11 09:30 UTC, marefr commented on docs/sources/plugins/plugin-signature-verification.md
> +| unsigned | Plugin don't have a _MANIFEST.txt_ file. |
Sure make sense when you put it that way :)

2020-06-11 09:31 UTC, marefr approved these changes
LGTM

2020-06-11 09:40 UTC, marcusolsson approved these changes

2020-06-11 15:33 UTC, merged