CloudWatch: Added AWS MediaStore metrics and dimensions
grafana/grafana pull request #25492
Opened 2020-06-09 19:34 UTC by ilyastoli

What this PR does / why we need it:
Adding AWS MediaStore metics according to: https://docs.aws.amazon.com/mediastore/latest/ug/monitor-with-cloudwatch-metrics.html
Which issue(s) this PR fixes:
No issue

Special notes for your reviewer:
Based on AWS documentation only, I didn't tried to monitor AWS MediaStore myself

2020-06-11 15:35 UTC, ilyastoli commented
@jessabe ping

2020-06-16 18:24 UTC, ilyastoli commented
@papagian ping

2020-06-17 11:07 UTC, papagian requested changes
Thanks for your contribution.
Digging into [the documentation](https://docs.aws.amazon.com/mediastore/latest/ug/mediastore-ug.pdf) I concluded that the dimensions should be camel case.

2020-06-17 11:07 UTC, papagian commented on pkg/tsdb/cloudwatch/metric_find_query.go
> +	"AWS/MediaStore":        {"Container name", "Object group name", "Request type"},
```suggestion
	"AWS/MediaStore":        {"ContainerName", "ObjectGroupName", "RequestType"},
```

2020-06-24 07:10 UTC, ilyastoli commented on pkg/tsdb/cloudwatch/metric_find_query.go
> +	"AWS/MediaStore":        {"Container name", "Object group name", "Request type"},
@papagian are we good?

2020-06-24 08:05 UTC, papagian approved these changes

2020-06-24 08:06 UTC, merged