Docs: Add guidelines for inclusive language
grafana/grafana pull request #25533
Opened 2020-06-11 09:36 UTC by marcusolsson

**What this PR does / why we need it**:

Adds guidelines for how to avoid using charged language.

#18841

2020-06-11 09:55 UTC, daniellee approved these changes
LGTM

The tricky part is 3rd party libraries or technologies.

2020-06-11 09:58 UTC, marcusolsson commented
Agreed. I tried explaining it under Exceptions, using the Git master branch as example, but now realize that this should apply to all guidelines under Inclusive language.

2020-06-11 16:14 UTC, oddlittlebird commented on contribute/style-guides/documentation-style-guide.md
> +### Inclusive language
I think this section should be an h2 and above word usage. 

Also, periods should be inside the quotation marks in this section, not outside.

2020-06-11 16:14 UTC, oddlittlebird requested changes
Whoops, forgot to make the earlier comment a review.

2020-06-24 11:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=25533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=25533) before we can accept your contribution.<br/><hr/>**Marcus Olsson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=25533) it.</sub>

2020-07-06 10:00 UTC, marefr commented
@oddlittlebird can you fix the changes you've suggested since Marcus is on vacation?

2020-07-06 19:27 UTC, oddlittlebird commented
@marefr , will do

2020-07-06 19:34 UTC, oddlittlebird approved these changes

2020-07-06 19:59 UTC, merged