Search: support URL query params
grafana/grafana pull request #25541
Opened 2020-06-11 10:40 UTC by Clarity-89

**What this PR does / why we need it**:
Save search filters i.e. tags, sort, starred and search query to URL params. This would enable sharing the URLs for filtered search results. 

**Which issue(s) this PR fixes**:

Fixes #24379

**Special notes for your reviewer**:

2020-06-15 12:32 UTC, alexanderzobnin requested changes
Looks good! The only thing I noticed is a folder param. When you open search from the folder (by clicking at folder name in the dashboard selector), `folder:current` is adding to search and `folder=current` - to the URL params. If you open URL with `folder=current` and `query` param is empty, `folder:current` will be added to the search input. But if both `folder=current` and `query` params are specified, `query` will be used as is. For instance:
- `?query=folder:current%20prometheus&search=open&folder=current` - input will be `folder:current prometheus` and search will be invoked in the current folder
- `?query=prometheus&search=open&folder=current` - input will be `prometheus` and search will be invoked globally.

So, probably, `folder` and `query` params should be syncronized against each other?

2020-06-15 12:34 UTC, Clarity-89 commented on public/app/core/components/Select/SortPicker.tsx
> +  return !loading ? (
`FC` type expects React component or `null` as a return value, using `&&` will return `false` instead. It works with our ts config, but results in error with `nullStrictChecks` on.

2020-06-15 12:41 UTC, alexanderzobnin commented on public/app/core/components/Select/SortPicker.tsx
> +  return !loading ? (
Aha, ok, got it!

2020-06-16 07:59 UTC, alexanderzobnin approved these changes
LGTM!

2020-06-16 08:52 UTC, merged