Docs: Update jaeger.md
grafana/grafana pull request #25634
Opened 2020-06-16 16:06 UTC by oddlittlebird

**What this PR does / why we need it**: Fixes a broken link

**Which issue(s) this PR fixes**:

Fixes #25170

**Special notes for your reviewer**:

2020-06-20 10:53 UTC, ghost requested changes
Hope this fixes link if not let me know

2020-06-22 14:22 UTC, oddlittlebird commented
I do not see your suggestion.

2020-06-23 06:55 UTC, ivanahuckova commented on docs/sources/features/datasources/jaeger.md
> +You can link to Jaeger trace from logs in Loki by configuring a derived field with internal link. See the [Derived fields]({{< relref "loki.md#derived-fields" >}}) section in the [Loki data source]({
```suggestion
You can link to Jaeger trace from logs in Loki by configuring a derived field with internal link. See the [Derived fields]({{< relref "./loki.md#derived-fields" >}}) section in the [Loki data source]({{< relref "./loki.md" >}}) documentation for details.
```

2020-06-23 06:59 UTC, ivanahuckova commented on docs/sources/features/datasources/jaeger.md
> +You can link to Jaeger trace from logs in Loki by configuring a derived field with internal link. See the [Derived fields]({{< relref "loki.md#derived-fields" >}}) section in the [Loki data source]({
I think that there need to be a full path to the file that we want to link. In the current version, we were just missing `.md`.

2020-06-23 06:59 UTC, ivanahuckova reviewed
I think that there need to be a full path to the file that we want to link. In the current version, we were just missing .md.

2020-06-23 15:11 UTC, cnk2182 commented
Sorry not to good at this stuff,but iam learning. If I understand correctly I would have to agree. How do I make that happen.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
From: Ivana Huckova <notifications@github.com>
Sent: Tuesday, June 23, 2020 1:59:50 AM
To: grafana/grafana <grafana@noreply.github.com>
Cc: cnk2182 <cnk2182@outlook.com>; Comment <comment@noreply.github.com>
Subject: Re: [grafana/grafana] Docs: Update jaeger.md (#25634)


@ivanahuckova commented on this pull request.

I think that there need to be a full path to the file that we want to link. In the current version, we were just missing .md.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrafana%2Fgrafana%2Fpull%2F25634%23pullrequestreview-435493192&data=02%7C01%7C%7C62df69f7590849cc32f608d817430642%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637284923910784597&sdata=6WaWLF4TUZ7UWs9aJ13T3ShNZ1zJEai62GEL0KB%2Bf54%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUYRQN2TBMPTIJTE3AAP73RYBHGNANCNFSM4N7YM7BA&data=02%7C01%7C%7C62df69f7590849cc32f608d817430642%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637284923910794591&sdata=Z%2FmbLY95CBi3yOUiz%2FWgA8gv7fTllWPIfhylPu1851I%3D&reserved=0>.

2020-06-23 17:21 UTC, oddlittlebird commented
@ivanahuckova , why is the enterprise frontend test failing?

2020-06-23 17:57 UTC, cnk2182 commented
To say the least

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
From: Diana Payton <notifications@github.com>
Sent: Tuesday, June 23, 2020 12:21:38 PM
To: grafana/grafana <grafana@noreply.github.com>
Cc: cnk2182 <cnk2182@outlook.com>; Comment <comment@noreply.github.com>
Subject: Re: [grafana/grafana] Docs: Update jaeger.md (#25634)


@ivanahuckova<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fivanahuckova&data=02%7C01%7C%7Cf1ce3cc7df474d4cf86b08d81799e3f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637285297000321682&sdata=UhIrQ0YtHW3NuGKd6gzis8411EptMyBORLh8uOpID%2BU%3D&reserved=0> , why is the enterprise frontend test failing?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrafana%2Fgrafana%2Fpull%2F25634%23issuecomment-648301827&data=02%7C01%7C%7Cf1ce3cc7df474d4cf86b08d81799e3f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637285297000331675&sdata=vmsdLBKQpHi0ejKSi9lcMbUP%2Bagnez43Mo0aU8%2BTjgA%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPUYRQMAXLXC26EJWOLWZEDRYDQCFANCNFSM4N7YM7BA&data=02%7C01%7C%7Cf1ce3cc7df474d4cf86b08d81799e3f2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637285297000331675&sdata=yxrS4mgTS5LTBlKHfaVFdfqFGDHiVtOrI%2FyM1ckHdRg%3D&reserved=0>.

2020-06-23 18:15 UTC, ivanahuckova commented
@oddlittlebird not sure - probably some change that happened between branching off and now.  But I merged the current master and that should fix the problem. :)

2020-06-23 18:35 UTC, ivanahuckova approved these changes

2020-06-23 19:12 UTC, merged