Docs: Enterprise Vault feature
grafana/grafana pull request #25895
Opened 2020-06-29 11:57 UTC by AgnesToulet

**What this PR does / why we need it**:
Adds documentation for the Grafana Enterprise 7.1 Vault integration.

**Special notes for your reviewer**:
Replaces #25861 as Emil is away and I don't have write access to his fork.

2020-06-29 13:52 UTC, xlson approved these changes
Great work! Clear and easy to understand.

2020-06-29 13:52 UTC, xlson commented on docs/sources/administration/configuration.md
> +> For any changes to `conf/grafana.ini` (or corresponding environment variables) to take effect, you must restart Grafana for the changes to take effect.
```suggestion
> For any changes to `conf/grafana.ini` (or corresponding environment variables) to take effect, you must restart Grafana.
```

2020-06-29 17:25 UTC, oddlittlebird requested changes
Documentation edits

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/administration/configuration.md
> +There are three providers: `env`, `file` and `vault`.
```suggestion
There are three providers: `env`, `file`, and `vault`.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/_index.md
> +* [Vault integration]({{< relref "vault.md" >}}) to manage your configuration or provisionning secrets with Vault.
```suggestion
* [Vault integration]({{< relref "vault.md" >}}) to manage your configuration or provisioning secrets with Vault.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/enterprise-configuration.md
> +Vault's namespace if using Vault with multi-tenancy.
```suggestion
Vault namespace if using Vault with multi-tenancy.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/enterprise-configuration.md
> + ### lease_renewal_interval
Looks like this h3 and the next two have a space in front, invalidating the heading. Please correct.

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +For organizations managing their secrets with [Hashicorp Vault](https://www.hashicorp.com/products/vault),
This sentence does not make sense. Consider making it two sentences.

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +> Note: If you have Grafana set up for [high availability]({{< relref "../tutorials/ha_setup.md" >}}) we advise not to use dynamic secrets for provisioning files.
```suggestion
> **Note:** If you have Grafana set up for [high availability]({{< relref "../tutorials/ha_setup.md" >}}), then we advise not to use dynamic secrets for provisioning files.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +Before using Vault you need to activate it by providing a URL, authentication method (currently only token),
```suggestion
Before using Vault, you need to activate it by providing a URL, authentication method (currently only token),
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +and a token for your Vault service. Grafana will automatically renew the service token if it is renewable and
```suggestion
and a token for your Vault service. Grafana automatically renews the service token if it is renewable and
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +If you're using short-lived leases, you can also configure how often Grafana should renew the lease and for
```suggestion
If you're using short-lived leases, then you can also configure how often Grafana should renew the lease and for
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +how long. We recommend keeping the defaults here unless you run into problems.
```suggestion
how long. We recommend keeping the defaults unless you run into problems.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +
```suggestion
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +When you've configured Vault you'll need to set the configuration or provisioning files you wish to
```suggestion
After you configure Vault, you must set the configuration or provisioning files you wish to
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +The argument to Vault consists of three parts separated by a colon: the first part specifies which secrets engine
Make the three parts a bulleted list, each part with a separate bullet and treated like a separate sentence.

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +Vault's [Databases secrets engines](https://www.vaultproject.io/docs/secrets/databases) is a family of
```suggestion
The Vault [databases secrets engines](https://www.vaultproject.io/docs/secrets/databases) is a family of
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +### Examples
Please add a brief intro to this section, explaining to the reader what the examples are of and how to use them.

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +Refer to the [Provisioning]({{< relref "../administration/provisioning.md" >}}) section for more information.
```suggestion
Refer to [Provisioning]({{< relref "../administration/provisioning.md" >}}) for more information.
```

2020-06-29 17:25 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +Refer to the [Configuration]({{< relref "../administration/configuration.md" >}}) section for more information.
```suggestion
Refer to [Configuration]({{< relref "../administration/configuration.md" >}}) for more information.
```

2020-06-30 19:35 UTC, oddlittlebird commented on docs/sources/administration/configuration.md
> +> For any changes to `conf/grafana.ini` (or corresponding environment variables) to take effect, you must restart Grafana for the changes to take effect.
I agree with this edit.

2020-06-30 19:36 UTC, oddlittlebird approved these changes
A couple minor edits, then good to go!

2020-06-30 19:36 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +If you are managing your secrets with [Hashicorp Vault](https://www.hashicorp.com/products/vault), you can use them for [Configuration]({{< relref "../administration/configuration.md" >}})
```suggestion
If you manage your secrets with [Hashicorp Vault](https://www.hashicorp.com/products/vault), you can use them for [Configuration]({{< relref "../administration/configuration.md" >}})
```

2020-06-30 19:36 UTC, oddlittlebird commented on docs/sources/enterprise/vault.md
> +> Each Grafana instance is responsible for renewing its own leases. Your data sources' leases might expire when one of your Grafana servers shuts down.
```suggestion
> Each Grafana instance is responsible for renewing its own leases. Your data source leases might expire when one of your Grafana servers shuts down.
```

2020-07-01 06:40 UTC, merged