Emails: use https for links and images
grafana/grafana pull request #25957
Opened 2020-07-01 02:48 UTC by perrinjerome

**What this PR does / why we need it**:

Changes email templates to use https instead of http.

There's an image on emails, http://grafana.org/assets/img/logo_new_transparent_200x48.png which redirects to https://grafana.com/assets/img/logo_new_transparent_200x48.png . I don't think there's a good reason for this image to be http in the first place. Most email services (such as gmail) use an https proxy to serve images, but self hosted web mails do not and this cause mixed content errors while viewing emails.

There's also a link to <a href="http://docs.grafana.org/guides/gettingstarted/">Getting Started</a>  which should not be http for extra security.

**Which issue(s) this PR fixes**:

( I did not create an issue, but I can do if you believe it's needed )

2020-07-01 02:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=25957) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=25957) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=25957) it.</sub>

2020-07-01 05:43 UTC, aknuds1 commented
Please sign the CLA.

2020-07-01 06:44 UTC, perrinjerome commented
@aknuds1 I signed CLA, thanks

2020-07-16 06:54 UTC, aknuds1 commented
@perrinjerome Do you mind if I merge with master and push to your branch?

2020-07-16 06:58 UTC, perrinjerome commented
@aknuds1 no problem, go ahead. Thanks !

2020-07-16 07:02 UTC, aknuds1 commented
That seemed to help.

2020-07-16 07:02 UTC, aknuds1 commented
I'm checking with colleagues if these changes are correct BTW.

2020-07-16 07:09 UTC, papagian requested changes
Thank you for contributing! I have a small suggestion.

2020-07-16 07:09 UTC, papagian commented on emails/templates/welcome_on_signup.html
> +							If you are new to Grafana please read the <a href="https://docs.grafana.org/guides/gettingstarted/">Getting Started</a> guide.
```suggestion
							If you are new to Grafana please read the <a href="https://docs.grafana.com/guides/gettingstarted/">Getting Started</a> guide.
```

2020-07-16 07:57 UTC, perrinjerome commented
Thanks @papagian I applied the change you suggested.

I did not notice there was another redirect, I just changed http to https and saw "it seems to work", so let's suggest using https here as well.

BTW, the https://docs.grafana.com/guides/gettingstarted/ also redirects (with status code 301 and location header) to https://grafana.com/docs/grafana/latest/guides/gettingstarted/ which in turn redirects (it's not a Location header but it's in the html ) to https://grafana.com/docs/grafana/latest/getting-started/getting-started/

2020-07-16 09:00 UTC, sakjur approved these changes
😄 This looks great!

> BTW, the https://docs.grafana.com/guides/gettingstarted/ also redirects (with status code 301 and location header) to https://grafana.com/docs/grafana/latest/guides/gettingstarted/ which in turn redirects (it's not a Location header but it's in the html ) to https://grafana.com/docs/grafana/latest/getting-started/getting-started/

Thank you for letting us know 👍 Let's keep it as-is for now and I'll let our website team know about this so that they can tell us if we should keep the original URL and fix the first redirect or change it to the final URL in that chain.

2020-07-16 09:55 UTC, daniellee approved these changes
LGTM

I tested with gmail and worked for me. HTML emails are their own weird world but I couldn't find anything saying that changing to https would affect anything. Seems to be the opposite in that there is a smaller chance of it getting stuck in spam filters.

2020-07-16 09:59 UTC, papagian approved these changes

2020-07-16 10:06 UTC, aknuds1 approved these changes

2020-07-16 10:06 UTC, merged

2020-07-16 10:08 UTC, aknuds1 commented
Thank you for contributing to Grafana!

2020-07-17 00:11 UTC, perrinjerome commented
Thanks everybody ( and also to stale bot 😉 )