Issue Template: @grafana/ui component request
grafana/grafana pull request #25981
Opened 2020-07-01 14:19 UTC by tskarhed

**What this PR does / why we need it**:
Adds a new issue template with a component request for @grafana/ui. The checklist will be used to make sure that the component is at 100%

All feedback would be greatly appreciated!

**Special notes for your reviewer**:
Not sure if I did the frontmatter correctly.

2020-07-01 14:52 UTC, oddlittlebird requested changes
Good stuff

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +By using this template you will make it easeier for us to make sure that documentation and implementation stays up to date for every component in @grafana/ui
```suggestion
By using this template you will make it easier for us to make sure that documentation and implementation stays up to date for every component in @grafana/ui.
```

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> + - [ ] Is/could it be used enough to become a pattern?
```suggestion
 - [ ] Is/could it be used in more than one place in Grafana?
```

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> + Post screenshots if you have any.
I suggest moving line 19 under the checklist.

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +**Implementation** (Checklist meant for developer)
Is the "developer" here the contributing developer or the maintainer developer? I suggest making this extremely clear.

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] Props and naming follows [our style guide]()
We have several style guides that could apply to UI. Please use the style guide name as the link text.

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] Uses theme for spacing, colors etc.
```suggestion
- [ ] Uses theme for spacing, colors, and so on
```

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] It is extendable (eg. rest props are spreaded, styles with className works)
```suggestion
- [ ] It is extendable (rest props are spreaded, styles with className works, and so on)
```

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] Uses theme for spacing, colors etc.
A link to the Theming style guide might be a good idea here.

2020-07-01 14:52 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] Code exmaples for the different use cases
```suggestion
- [ ] Code examples for the different use cases
```

2020-07-03 07:23 UTC, dprokop commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] Uses theme for spacing, colors etc.
Link to theming would be awesome here :)

2020-07-03 07:23 UTC, dprokop approved these changes
Think this is a great start @tskarhed!

2020-07-06 10:04 UTC, jessover9000 reviewed
some great feedback from @oddlittlebird , other than that I think it's great :) @peterholmberg or @Clarity-89 could you take care of getting this changed up and merged?

2020-07-09 14:26 UTC, oddlittlebird requested changes

2020-07-09 14:26 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] It has a single use case
Put periods at the end of all sentences. In this case, all options.

2020-07-09 14:26 UTC, oddlittlebird commented on .github/ISSUE_TEMPLATE/4-grafana_ui_component.md
> +- [ ] It is extendable (rest rest props are spreaded, styles with className works, and so on)
```suggestion
- [ ] It is extendable (rest props are spread, styles with className works, and so on).
```

2020-07-09 14:34 UTC, oddlittlebird approved these changes
Looks good!

2020-07-09 15:00 UTC, merged