Docs: Update debian.md
grafana/grafana pull request #26100
Opened 2020-07-06 19:43 UTC by oddlittlebird

**What this PR does / why we need it**: Removes apt-get because it did not work in all cases.

**Which issue(s) this PR fixes**:

Fixes #22527

**Special notes for your reviewer**:

2020-07-07 06:45 UTC, aknuds1 commented on docs/sources/installation/debian.md
> -sudo apt-get install grafana-enterprise
Why do you want to remove instructions for installing beta versions?

2020-07-07 06:45 UTC, aknuds1 commented on docs/sources/installation/debian.md
> -sudo apt-get install grafana
Why do you want to remove instructions for installing beta versions?

2020-07-07 06:54 UTC, sakjur submitted a review, later dismissed
This PR removes the installation step entirely, in #22527 the proposed solution is to replace

```bash
sudo add-apt-repository "deb https://packages.grafana.com/enterprise/deb stable main"
```

with

```bash
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
```

rather than removing any lines in these instructions.

Lines 65-79 can be removed after that is done, since they're alternative instructions for when `add-apt-repository` fails.

2020-07-07 06:55 UTC, aknuds1 requested changes
Having read the linked issue, I think the changes in this PR are based on a misunderstanding. The current changes _remove_ instructions for installing Grafana on Debian/Ubuntu, while the linked issue says to change them slightly.

I.e., the wanted change is from `sudo add-apt-repository "deb https://packages.grafana.com/enterprise/deb stable main"` to `echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list `.

2020-07-07 06:58 UTC, aknuds1 commented
@sakjur is right. I think along with the alternate section (which will now be the main solution), we need to remove the heading "Set up repository for ARM" also, since it's just out of place.

2020-07-07 12:11 UTC, xlson commented
What @sakjur and @aknuds1 said. We want to replace the add-apt-rep line with the echo ... line and then remove the arm section as that will be exactly the same instruction as for ubuntu/debian.

2020-07-07 17:46 UTC, oddlittlebird commented
Okeydokey. I reverted the deletion and changed the one line, but I am confused about what to do with the Set up repository for ARM section. Does it stay? Does part of it get deleted? Moved?

2020-07-07 20:45 UTC, sakjur commented
@oddlittlebird You can remove the entire section, it seems to refer to the ARM version of the repo having a problem when you're using the `add-apt-repository` command (I'm guessing, the section title is a bit confusing as the instructions are not specific for ARM), so the instructions in that section are now the same as the general instructions above.

2020-07-07 22:19 UTC, oddlittlebird commented
If I remove the entire section, then we lose the echo command for the beta repository. How's this?

2020-07-08 07:02 UTC, aknuds1 requested changes
Looks better, but the same changes should be made for the enterprise section also.

2020-07-08 20:37 UTC, aknuds1 requested changes

2020-07-08 20:37 UTC, aknuds1 commented on docs/sources/installation/debian.md
> +sudo apt-get install grafana
This change should be undone
```suggestion
sudo apt-get install grafana-enterprise
```

2020-07-09 04:56 UTC, aknuds1 approved these changes
LGTM

2020-07-09 14:25 UTC, merged