Chore: Enable gocyclo linter
grafana/grafana pull request #26395
Opened 2020-07-17 08:51 UTC by aknuds1

**What this PR does / why we need it**:
Enable [gocyclo](https://github.com/fzipp/gocyclo) linter, which detects overly complex Go functions.

In my opinion, it's very useful since it prevents too long functions, which are really difficult to follow and understand (the old rule of thumb from Code Complete is that a function should generally not exceed the height of the screen more or less). Some functions become long for a reason (usually switch statements), and I've marked them with a `nolint` directive.

2020-08-25 16:54 UTC, marefr reviewed
Looks good. Added a comment. Guess this is related to the other settings PR why I only leaving a comment for now?

2020-08-25 16:54 UTC, marefr commented on pkg/tsdb/sqleng/sql_engine.go
> +func newProcessCfg(query *tsdb.Query, tsdbQuery *tsdb.TsdbQuery, rows *core.Rows) (*processCfg, error) {
Not sure I agree this gets less complex. Maybe easier for now to add `//nolint: gocyclo` to transformToTimeSeries?

2020-08-26 11:21 UTC, aknuds1 commented
@marefr I'll be reworking this PR, after having merged the settings refactoring PR. It's been split into smaller PRs and can now be brought up-to-date again.

2020-08-26 11:51 UTC, marefr requested changes
Seems to be a couple places left to fix.

2020-09-07 16:59 UTC, marefr approved these changes
LGTM, but need to resolve conflicts

2020-09-07 20:10 UTC, merged