Adds af-south-1 region to cloudwatch datasource
grafana/grafana pull request #26513
Opened 2020-07-22 08:39 UTC by ruanbekker

**What this PR does / why we need it**:

This allows you to select the `af-south-1` region using the AWS CloudWatch datasource in Grafana

**Which issue(s) this PR fixes**:

Fixes #26477 

**Special notes for your reviewer**:

Describing the AWS Region:

```
$ aws --profile prod ec2 describe-regions --filters "Name=region-name,Values=af-south-1"
{
    "Regions": [
        {
            "Endpoint": "ec2.af-south-1.amazonaws.com",
            "RegionName": "af-south-1",
            "OptInStatus": "opted-in"
        }
    ]
}
```

Listing AWS CloudWatch Metrics from that region:

```
$ aws --profile prod --region af-south-1 cloudwatch list-metrics --namespace 'AWS/EC2' --max-items 1
{
    "Metrics": [
        {
            "Namespace": "AWS/EC2",
            "MetricName": "CPUUtilization",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-00000000000000000"
                }
            ]
        }
    ],
    "NextToken": "x"
}
```

2020-07-22 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=26513) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=26513) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=26513) it.</sub>

2020-07-22 10:51 UTC, jessabe commented
Hej @ruanbekker, thanks for contributing! You might need to merge with the latest master to get Drone to pass, and then we'll have a look.

2020-07-22 11:24 UTC, aknuds1 commented
Please update the back-end tests, they fail as follows:

```
--- FAIL: TestCloudWatchMetrics (0.00s)
--
211 | --- FAIL: TestCloudWatchMetrics/When_calling_handleGetRegions (0.00s)
212 | metric_find_query_test.go:126:
213 | Error Trace:	metric_find_query_test.go:126
214 | Error:      	Not equal:
215 | expected: "ap-east-1"
216 | actual  : "af-south-1"
217 |  
218 | Diff:
219 | --- Expected
220 | +++ Actual
221 | @@ -1 +1 @@
222 | -ap-east-1
223 | +af-south-1
224 | Test:       	TestCloudWatchMetrics/When_calling_handleGetRegions
225 | metric_find_query_test.go:127:
226 | Error Trace:	metric_find_query_test.go:127
227 | Error:      	Not equal:
228 | expected: "ap-northeast-1"
229 | actual  : "ap-east-1"
230 |  
231 | Diff:
232 | --- Expected
233 | +++ Actual
234 | @@ -1 +1 @@
235 | -ap-northeast-1
236 | +ap-east-1
237 | Test:       	TestCloudWatchMetrics/When_calling_handleGetRegions
238 | metric_find_query_test.go:128:
239 | Error Trace:	metric_find_query_test.go:128
240 | Error:      	Not equal:
241 | expected: "ap-northeast-2"
242 | actual  : "ap-northeast-1"
243 |  
244 | Diff:
245 | --- Expected
246 | +++ Actual
247 | @@ -1 +1 @@
248 | -ap-northeast-2
249 | +ap-northeast-1
250 | Test:       	TestCloudWatchMetrics/When_calling_handleGetRegions
```

2020-07-22 13:59 UTC, aknuds1 requested changes
LGTM, except back-end tests need fixing.

2020-07-23 10:21 UTC, aknuds1 approved these changes

2020-07-23 11:01 UTC, papagian approved these changes
LGTM, thanks for contributing!

2020-07-23 11:02 UTC, merged