Field/Template: __field.name as field name and __field.displayName as displayName
grafana/grafana pull request #26531
Opened 2020-07-22 17:40 UTC by ryantxu

Template variables currently set `__field.name` as the display name, not the field name.  This makes it impossible to configure the display name using the field name :exploding_head: :turtle: :turtle: :turtle: 

This PR updates the syntax so that `__field.name` is simply the name and `__field.displayName` is the full rendered name

This uses a proxy object to define the behavior when values are requested, rather than when we initialize the scopedVars.  This makes it possible to support:

`__field.labels` = the string representation of the labels
`__field.labels.__values` = the string representation of the label values

With these changes, it is possible to configure the azure responses more reasonably

2020-07-22 17:46 UTC, ryantxu commented on packages/grafana-data/src/field/fieldOverrides.test.ts
> +            "value": Object {},
the real value is the proxy object

2020-07-22 18:22 UTC, kylebrandt commented
@ryantxu seems to be missing `${__field.labels.__values}` based on my manual testing and looking at the code.

2020-07-22 18:26 UTC, ryantxu commented
dooh missing git push!

2020-07-22 18:34 UTC, kylebrandt commented
It seems if you have an instance where there is a label with a key, but its value is an empty string, then field.name is displayed when it should just be empty:

![image](https://user-images.githubusercontent.com/1692624/88214465-436a0080-cc28-11ea-9ad4-da9be030b1e8.png)

2020-07-23 17:45 UTC, torkelo commented
This looks good

need to update the docs as well: https://github.com/grafana/grafana/blob/master/docs/sources/panels/field-configuration-options.md#display-name 

 Worried about potentially breaking many dashboards, wonder if we should include this in a patch release or wait for 7.2 but then we will likely break more dashboards :( 

7.1.1 is going out tomorrow, need to make sure this bug free :)

2020-07-23 17:45 UTC, torkelo commented
ah, no I see 7.1.2 milestone, that seems more reasonable

2020-07-24 14:43 UTC, torkelo commented
What is `${__field.labels.__values}` ?? that looks strange (with the double __ prefix the middle)

2020-07-24 14:45 UTC, torkelo commented on packages/grafana-data/src/field/templateProxies.ts
> +              .join(', '),
what is the use case for this? vs toString?

2020-07-24 14:50 UTC, kylebrandt commented
> What is `${__field.labels.__values}` ?? that looks strange (with the double __ prefix the middle)

This displays only the value component of each label. Mainly to be able to reproduce the default display behavior (when there is only one label, only the value is displayed).

Since one can use labels.X to access arbitrary label keys, the idea is `__values` is less likely to collide with an actual label key would (like values).

2020-07-25 13:37 UTC, torkelo commented
Can we make the root field.labels object toString default to returning the same as __values ?

2020-07-25 15:04 UTC, kylebrandt commented
> Can we make the root field.labels object toString default to returning the same as __values ?

I don't think that works out, because since labels are "k=v", one wants to be able the full label set, so it makes sense to me for labels to always do that. labels.__values is probably more often useful in the in case where there is just one label.

Started to draft this up ( https://gist.github.com/kylebrandt/f19d258e984c120506387cb2fbc2666c ) since we might be going in circles here. Can possibly work on it more Monday - also maybe better as a gdoc.

2020-08-04 18:31 UTC, oddlittlebird requested changes

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| Expression Syntax            | Example                | Renders to                        | Explanation |
```suggestion
| Expression syntax            | Example                | Renders to                        | Explanation |
```

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.displayName}`     | Same as Syntax         | `Temp {Loc="PBI", Sensor="3"}`    | Displays the field's name, and labels in `{}` if they are present. If there is only one label key in the
```suggestion
| `${__field.displayName}`     | Same as syntax         | `Temp {Loc="PBI", Sensor="3"}`    | Displays the field name, and labels in `{}` if they are present. If there is only one label key in the response, then for the label portion, Grafana displays the value of the label without the enclosing braces. |
```

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.name}`            | Same as Syntax          | `Temp`                           | Displays the name of the field (without labels) |
```suggestion
| `${__field.name}`            | Same as syntax          | `Temp`                           | Displays the name of the field (without labels). |
```

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.labels}`          | Same as Syntax          | `Loc="PBI", Sensor="3"`          | Displays the labels without the name |
```suggestion
| `${__field.labels}`          | Same as syntax          | `Loc="PBI", Sensor="3"`          | Displays the labels without the name. |
```

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.labels.X}`        | `${__field.labels.Loc}` | `PBI`                            | Displays the value of the specified label key |
```suggestion
| `${__field.labels.X}`        | `${__field.labels.Loc}` | `PBI`                            | Displays the value of the specified label key. |
```

2020-08-04 18:31 UTC, oddlittlebird commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.labels.__values}` | Same as Syntax          | `PBI, 3`                         | Displays the values of the labels separated by a comma (without label keys) |
```suggestion
| `${__field.labels.__values}` | Same as Syntax          | `PBI, 3`                         | Displays the values of the labels separated by a comma (without label keys). |
```

2020-08-04 18:34 UTC, ryantxu commented on docs/sources/panels/field-configuration-options.md
> +| `${__field.displayName}`     | Same as syntax         | `Temp {Loc="PBI", Sensor="3"}`    | Displays the field name, and labels in `{}` if they are present. If there is only one label key in the re
note:  this should eventually link to whatever is settled on in https://github.com/grafana/grafana/pull/26656

2020-08-04 19:47 UTC, oddlittlebird approved these changes

2020-08-04 19:48 UTC, oddlittlebird commented
I approved the docs. I recommend holding on merging until someone else approves the code.

2020-08-04 19:50 UTC, ryantxu commented
Discussed the [case above](https://github.com/grafana/grafana/pull/26531#issuecomment-662617026) with @kylebrandt , for now lets solve that with documentatoin.

This is only a small part of the coherent naming strategy, but I think gives good clear progress towards explicitly setting reasonable values when the default behavior is undesirable

2020-08-04 21:20 UTC, ryantxu commented
@kylebrandt / @torkelo -- i think this is ready to merge and should be included in 7.1.2

for back compatibility -- i don't have a great answer other than the longer we live with an incoherent model the harder it is to change.  I don't have a great sense of how widely used explicitly setting name vs name+labels is yet, but these changes are required to support reasonable behavior when the [automatic](https://github.com/grafana/grafana/pull/26656) one does not work

2020-08-05 04:22 UTC, merged

2020-08-10 10:14 UTC, dprokop commented on packages/grafana-data/src/field/templateProxies.ts
> +      get: (obj: Field, key: string, reciever: any) => {
@ryantxu I'm not super familiar with Proxy objects, but shouldn't the target here be the `field` passed to the `getTemplateProxyForField` function call? 🤯 Then the handler would use its first argument(`obj`) to reference the proxied object.