Docs: Sort log result documentation
grafana/grafana pull request #26898
Opened 2020-08-10 14:01 UTC by ivanahuckova

**What this PR does / why we need it**:
- This PR adds documentation to the new Sort logs order function (part of a future 7.2 release)
- Re-oders the **visualisation options** part based on how it is in UI (below)
![image](https://user-images.githubusercontent.com/30407135/89790775-b6c5aa80-db22-11ea-99c4-b6ae7b099ea5.png)

2020-08-10 14:31 UTC, oddlittlebird commented
In the Dedup field, why are all the options lowercase rather than initial cap? It seems to break the pattern we have elsewhere. Is this situation addressed in the UX design system?

2020-08-10 14:33 UTC, oddlittlebird requested changes

2020-08-10 14:33 UTC, oddlittlebird commented on docs/sources/features/explore/index.md
> +- `exact` Exact matches are done on the whole line, except for date fields.
```suggestion
- **exact -** Exact matches are done on the whole line except for date fields.
```

2020-08-10 14:33 UTC, oddlittlebird commented on docs/sources/features/explore/index.md
> +- `numbers` Matches on the line after stripping out numbers (durations, IP addresses etc.).
```suggestion
- **numbers -** Matches on the line after stripping out numbers such as durations, IP addresses, and so on.
```

2020-08-10 14:33 UTC, oddlittlebird commented on docs/sources/features/explore/index.md
> +- `signature` The most aggressive deduping - strips all letters and numbers, and matches on the remaining whitespace and punctuation.
```suggestion
- **signature -** The most aggressive deduping, this strips all letters and numbers and matches on the remaining whitespace and punctuation.
```

2020-08-10 14:33 UTC, oddlittlebird commented on docs/sources/features/explore/index.md
> +You can change the order of received logs from the default descending order (newest first) to ascending order (oldest first).
This is a great change!

2020-08-10 14:52 UTC, ivanahuckova commented
> In the Dedup field, why are all the options lowercase rather than initial cap? It seems to break the pattern we have elsewhere. Is this situation addressed in the UX design system?

Great catch @oddlittlebird!
@jessover9000 @davkal do you have any information/reasons why the dedup options are lower cased? Should we change it to keep stuff more consistent? Your thoughts?

2020-08-12 20:38 UTC, oddlittlebird requested changes
Please update the Deduping image and options text to match the new capitalization.

2020-08-13 09:03 UTC, ivanahuckova commented
> Please update the Deduping image 

We don't have image in documentation and I think there is no need for it. What do you think? 

> and options text to match the new capitalization.

Done ✅

2020-08-13 17:40 UTC, oddlittlebird approved these changes
LGTM!

2020-08-14 08:15 UTC, merged