alerting: Change alerting source panel to view instead of edit.
grafana/grafana pull request #26933
Opened 2020-08-11 16:14 UTC by hdost

This is because when a dashboard is locked from edits this will result in
an error denoting improper permissions. The same is likely in the case that
a person is only allowed view permissions.

Fixes #26931

2020-08-11 17:03 UTC, sakjur reviewed
The alerting tab isn't available when in `viewPanel` mode, so I'd suggest removing it from the URL to make sure the URL doesn't provide a false promise.

Other than that I feel like it's more useful to go for your variant than what we have now. We lose the direct link to the alerts but the link is accessible by anyone, not just people with edit perms. It seems like the correct balance.

@torkelo WDYT?

2020-08-11 17:22 UTC, hdost commented on pkg/services/alerting/eval_context.go
> +const urlFormat = "%s?tab=alert&viewPanel=%d&orgId=%d"
Yea i wasn't sure if it should stay, but that makes sense. I have updated to remove the tab param.

2020-08-14 13:19 UTC, torkelo commented
@bergquist what do you think makes the most sense here? Think either this, or continue having the link go to edit mode and have a fallback that redirects to view panel for users who do not have edit permissions

2020-08-14 13:25 UTC, aenima-x commented
> @bergquist what do you think makes the most sense here? Think either this, or continue having the link go to edit mode and have a fallback that redirects to view panel for users who do not have edit permissions

There is already a button to go to edit view.
Please add this fix, in older versions worked like this

2020-08-17 07:48 UTC, bergquist commented
The main reason users click that link is to get a better understanding of WHY it's triggered. I think the edit view offers much more details about why it triggered. Navigating from view to edit can be done by clicking the edit option in the panel menu but it's not that obvious. I think many users will navigate back to the dashboard view and loose context about which alert that triggered. 

> continue having the link go to edit mode and have a fallback that redirects to view panel for users who do not have edit permissions

I think that's the best solution but I'm not sure if the implementation would be reasonable. I assumed this would be done in the frontend? redirecting in the backend seems a bit messy IMO.

2020-08-17 13:21 UTC, hdost commented
@bergquist So then potentially would we want to instead update: https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/containers/DashboardPage.tsx#L122
instead of/after the notification adding
```
this.setState({ viewPanel: panel });
```

2020-08-28 09:26 UTC, mckn commented on public/app/features/dashboard/containers/DashboardPage.tsx
> +        }
```suggestion
        if (dashboard.canEditPanel(panel)) {
          this.setState({ editPanel: panel });
          return;
        }

        this.props.notifyApp(createErrorNotification('Permission to edit panel denied'));
        this.props.updateLocation({
          query: {
            editPanel: null,
            viewPanel: panel.id,
          },
          partial: true,
          replace: true,
        });
```

After reading the comments in the this PR I would suggest doing the following. This should work as expected and also handle the browser history correctly.

Please give it a try and say what you think 🙏

2020-08-28 09:28 UTC, mckn requested changes
I have added one small comment on how to improve this. Please give it a try and say what you think 🙏

2020-09-25 06:00 UTC, mckn commented
@hdost can I help out to get this mergeable?

2020-09-28 08:53 UTC, hdost commented on pkg/services/alerting/eval_context.go
> +const urlFormat = "%s?tab=alert&viewPanel=%d&orgId=%d"
> @bergquist what do you think makes the most sense here? Think either this, or continue having the link go to edit mode and have a fallback that redirects to view panel for users who do not have edit permissions

I guess https://github.com/grafana/grafana/pull/27378 this change was ok ? :shrug:  at least it's fixed.

2020-09-28 08:53 UTC, hdost commented
> @bergquist what do you think makes the most sense here? Think either this, or continue having the link go to edit mode and have a fallback that redirects to view panel for users who do not have edit permissions

I guess https://github.com/grafana/grafana/pull/27378 this change was ok ? :shrug:  at least it's fixed.

2020-09-28 08:53 UTC, closed without merging