Alerting: Improve PagerDuty dedup_key complicity.
grafana/grafana pull request #26972
Opened 2020-08-12 20:34 UTC by alavrovinfb

- Updated dedup_key generation scheme

 - Updated UT's

**What this PR does / why we need it**:

Changes from this PR  should avoid incorrect incidents de-duplication in PagerDuty. 

**Which issue(s) this PR fixes**:
This has been raised to fix Grafana issue [#26863 ](https://github.com/grafana/grafana/issues/26863)

Fixes #26863 

**Special notes for your reviewer**:
Currently, alerts haven't got generated UID, for this reason, I've used the corresponding dashboard UID. Since dashboard UID could be overridden by custom UID, the mentioned issue could be faced.

2020-08-12 20:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=26972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=26972) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=26972) it.</sub>

2020-08-18 14:01 UTC, aknuds1 requested changes
Haven't reviewed in depth yet, but left a suggestion for cleaner code.

2020-08-18 14:01 UTC, aknuds1 commented on pkg/services/alerting/notifiers/pagerduty.go
> +	}
```suggestion
	dashboardRef, err := evalContext.GetDashboardUID()
	if err != nil {
		pn.log.Error("Failed get dashboard reference", "error", err)
		return []byte{}, err
	}
	
	dedupKey := fmt.Sprintf("alertId-%d-%d-%d", evalContext.Rule.ID, evalContext.Rule.PanelID, dashboardRef.Uid)
	if len(dedupKey) > 255 {
		dedupKey = dedupKey[0:254]
	}
```

2020-08-18 14:13 UTC, aknuds1 reviewed
Thanks for applying my suggestion, will review more.

2020-08-18 14:19 UTC, aknuds1 commented
The build failure is because "fmt" has to be imported in pagerduty.go.

2020-08-18 14:42 UTC, alavrovinfb commented
> The build failure is because "fmt" has to be imported in pagerduty.go.

Missed import has been added.

2020-08-19 13:17 UTC, kylebrandt commented on pkg/services/alerting/eval_context.go
> +	if c.IsTestRun {
Need to look closer but I think "IsTestRun" is not for go tests, but rather when someone is using the "Test rule".

So I think when we do this, there should be a dashboard UID.

2020-08-20 09:51 UTC, marefr commented
@alavrovinfb thank you for your contribution. However, reading the issue and looking at these changes feels to me as you would end up with the same problem given you use the same dashboards in both Grafana instances which yields the same UID and panel id. 

The issue haven't received any other feedback/upvote why I would like to wait a bit and see if others having the same problem. Until then I would suggest you to investigate whether using multiple integrations or something else in Pagerduty allows you to solve your problem. 

I'm closing this for now since we're trying to only have active PR's open , but we can reopen it later should there be more activity around it or if I misunderstood something. Suggests continuing discussion in the issue.

2020-08-20 09:51 UTC, closed without merging