WIP: use "server admin" role for grafana admin
grafana/grafana pull request #27058
Opened 2020-08-18 22:49 UTC by ryantxu

Fixes #26790

Not sure this is a great idea... now that I see how much it changs!

The alternative is to make sure we clearly show "Grafana Admin" means you have access to the "Server Admin" section

2020-09-01 16:15 UTC, torkelo reviewed
This looks good except the breaking HTTP API change, is there away to make that backward compatible, otherwise might have wait for Grafana v8? or maybe is small enough of a breaking change to be ok in a minor release. 

thoughts @marefr ?

2020-09-02 19:28 UTC, marefr requested changes
Great improvement :+1: 

I agree with Torkel that breaking changes in API we probably don't want to do until v8. So I've added some suggestions to keep the API backward compatible. Haven't check documentation updates though so you may have to adjust HTTP API documentation as well. 

It was quite a lot of changes to grasp so bear in mind I may have missed something :)

2020-09-02 19:28 UTC, marefr commented on public/app/features/admin/state/actions.ts
> +    const payload = { isServerAdmin };
Suggest to keep this backward compatible until v8:

```suggestion
    const payload = { isGrafanaAdmin: isServerAdmin };
```

2020-09-02 19:28 UTC, marefr commented on public/app/features/admin/state/actions.ts
> +      const { name, surname, email, login, isServerAdmin, isDisabled, roles, teams } = response;
```suggestion
      const { name, surname, email, login, isGrafanaAdmin, isDisabled, roles, teams } = response;
```

2020-09-02 19:28 UTC, marefr commented on public/app/features/admin/state/actions.ts
> +        permissions: { isServerAdmin, isDisabled },
Suggest to keep this backward compatible until v8:

```suggestion
        permissions: { isServerAdmin: isGrafanaAdmin, isDisabled },
```

2020-09-02 19:28 UTC, marefr commented on public/app/features/admin/state/reducers.test.ts
> +  isServerAdmin: false,
```suggestion
  isGrafanaAdmin: false,
```

2020-09-02 19:28 UTC, marefr commented on public/app/types/user.ts
> +  isServerAdmin: boolean;
If this is returned from API should be reverted to be backward compatible.

2020-09-28 21:21 UTC, ryantxu commented
I'll close this for now

2020-09-28 21:21 UTC, closed without merging