Alerting: Added Zenduty Grafana integration to the Grafana notifications documentation page
grafana/grafana pull request #27069
Opened 2020-08-19 11:25 UTC by vishwa306

Signed-off-by: Vishwa Krishnakumar <vishwa306@gmail.com>

**What this PR does / why we need it**:

This PR adds a section on how to integrate Grafana with Zenduty to dispatch Grafana alerts to on-call engineering(NOC, SRE, Ops) teams and help them respond to critical Grafana alerts quickly.

**Which issue(s) this PR fixes**:
None

Fixes #

**Special notes for your reviewer**:

2020-08-19 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=27069) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=27069) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=27069) it.</sub>

2020-08-19 15:01 UTC, oddlittlebird requested changes
Please update the table of supported notifiers.

2020-08-20 09:19 UTC, vishwa306 commented
Updated the table of supported notifiers. Added Zenduty to the list.

2020-08-20 15:03 UTC, oddlittlebird approved these changes
Looks good. Thanks for contributing to the docs!

2020-08-20 15:03 UTC, merged