Alerting: Store sensitive settings encrypted for OpsGenie notifier
grafana/grafana pull request #27074
Opened 2020-08-19 13:42 UTC by wbrowne

**What this PR does / why we need it**:
We need to update all alert notifiers so that they support storing sensitive information encrypted. This PR covers OpsGenie 

**Which issue(s) this PR fixes**:
(part of) https://github.com/grafana/grafana/issues/25967

2020-08-19 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=27074) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=27074) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=27074) it.</sub>

2020-08-19 13:58 UTC, aknuds1 commented on pkg/services/alerting/notifiers/opsgenie.go
> +		<div class="gf-form gf-form--grow" ng-if="!ctrl.model.secureFields.apiKey">
The indentation is wrong here isn't it?

2020-08-19 14:02 UTC, aknuds1 commented on pkg/services/alerting/notifiers/opsgenie.go
> +              class="gf-form-input max-width-22"
Indentation it looks like.

2020-08-19 14:37 UTC, aknuds1 approved these changes
LGTM!

2020-08-19 14:38 UTC, aknuds1 commented
What's the milestone, 7.2?

2020-08-19 15:16 UTC, marefr approved these changes
Great. LGTM

2020-08-19 15:21 UTC, marefr requested changes
Oops sorry. I forgot one thing. Documentation. We've added a new column to denote what secure settings are supported here: https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings

If you could update this section that would be awesome: https://github.com/grafana/grafana/blob/master/docs/sources/administration/provisioning.md#alert-notification-opsgenie

2020-08-19 19:47 UTC, oddlittlebird approved these changes
LGTM

2020-08-20 12:40 UTC, marefr approved these changes
LGTM :+1:

2020-08-20 14:05 UTC, merged