Alerting: Store sensitive settings encrypted for Telegram notifier
grafana/grafana pull request #27122
Opened 2020-08-21 10:00 UTC by wbrowne

**What this PR does / why we need it**:
We need to update all alert notifiers so that they support storing sensitive information encrypted. This PR covers Telegram 

**Which issue(s) this PR fixes**:
(part of) https://github.com/grafana/grafana/issues/25967

2020-08-21 11:42 UTC, aknuds1 approved these changes
Looks good AFAICT.

2020-08-24 10:01 UTC, marefr commented on pkg/services/alerting/notifiers/telegram.go
>  	uploadImage := model.Settings.Get("uploadImage").MustBool()
`uploadImage` is a setting available to all notifiers, but not necessarily used/supported by all of them . Seems like this notifier still are reading setting where probably all other notifiers are using the base implementation method `NeedsImage()` instead. See example usage here: https://github.com/grafana/grafana/blob/954a2811b3f00bb5d4d0b40426bf3daedaf50215/pkg/services/alerting/notifiers/slack.go#L391

Suggest adding back the `uploadImage` to provisioning documentation.

2020-08-24 10:01 UTC, marefr commented on docs/sources/administration/provisioning.md
> -| uploadImage |
See my other comment. `uploadImage` This change needs to be reverted.

2020-08-24 10:02 UTC, marefr requested changes
See comments

2020-08-24 13:11 UTC, wbrowne commented on pkg/services/alerting/notifiers/telegram.go
>  	uploadImage := model.Settings.Get("uploadImage").MustBool()
Makes sense. Have added back the field to the docs.

This sounds like something we can tackle separately if necessary as it's also missing from the Pushover notifier

2020-08-25 09:21 UTC, marefr approved these changes
LGTM

2020-08-25 09:23 UTC, marefr commented
Just need to sync/merge with master to resolve CI problems (I think)

2020-08-25 12:35 UTC, merged