UI/ClickOutsideWrapper: Adds eventType prop for situations where mousedown is needed
grafana/grafana pull request #27221
Opened 2020-08-26 11:15 UTC by kaydelaney

**What this PR does / why we need it**:
This PR adds an `eventType` prop to `ClickOutsideWrapper`, with a default of `click`, that can be overridden if `mousedown` is needed, as in the case of `TimePickerCalendar`.
This PR should also resolve issues with the dashboard variable dropdown not behaving properly.

2020-08-26 11:20 UTC, hugohaggmark requested changes
Now when you click on a value in the OptionPicker it closes the options. It should remain opened for multi valued variables.

2020-08-26 11:24 UTC, hugohaggmark commented
> Now when you click on a value in the OptionPicker it closes the options. It should remain opened for multi valued variables.

This error is because we've switched from `window` to `document` in ClickOutsideWrapper not because of the latest changes in this PR :(

2020-08-26 12:38 UTC, kaydelaney commented
@hugohaggmark Ack. 😦 It's actually hard to find a straight answer about what the difference between events attached on `document` or `window` is - lots of conflicting info. I suppose it's better to revert to using `window` then and to figure another solution out for the lingering panel menus...

2020-08-26 12:40 UTC, hugohaggmark commented
> @hugohaggmark Ack. 😦 It's actually hard to find a straight answer about what the difference between events attached on `document` or `window` is - lots of conflicting info. I suppose it's better to revert to using `window` then and to figure another solution out for the lingering panel menus...

yeah, it could probably differ between browsers too? Maybe you could add a `parent` prop that defaults to `window` and pass `document` to solve the PanelHeader issue?

2020-08-27 04:26 UTC, hugohaggmark approved these changes
Looks good and works as expected! ⭐ 

Tested the following:
- LogRowContext
- FuncEditor in Graphite
- OptionsPicker
- TimePickerCalendar
- TimeRangePicker
- PanelHeader

2020-08-27 08:18 UTC, merged