Explore: adds a page title to Explore
grafana/grafana pull request #27402
Opened 2020-09-05 13:24 UTC by Estrax

**What this PR does / why we need it**:

Adds a page title to Explore.

**Which issue(s) this PR fixes**:

Fixes #27387 

**Special notes for your reviewer**:

1. Open Grafana.
2. Navigate to Explore.
3. Check the page title on the browsers' tab.

Probably it's gonna be worth it to use a custom `getTitleFromNavModel` method so the title is not `Explore: Explore - Grafana` - maybe we should add a datasource name there?

2020-09-05 13:37 UTC, Estrax commented
@ivanahuckova can you add relevant labels to this one? `area/frontend`, `area/explore` & `type/accessibility`. Thanks!

2020-09-14 09:48 UTC, zoltanbedi commented
Hi @Estrax, thanks for fixing this. Ivana is on vacation right now so I'm going to check your pr.

2020-09-14 10:51 UTC, zoltanbedi requested changes

2020-09-14 10:51 UTC, zoltanbedi commented on public/app/features/explore/Explore.tsx
> +import { getTitleFromNavModel } from 'app/core/selectors/navModel';
nit: I think it would make sense to import getNavModel from here as well. Or the other way around.

2020-09-14 10:51 UTC, zoltanbedi commented on public/app/features/explore/Explore.tsx
> +    const title = navModel ? getTitleFromNavModel(navModel) : '';
Can getTitleFromNavModel be falsy?

2020-09-16 07:48 UTC, torkelo reviewed
Feel like this needs a more generic solution. Like adding a title to each route: 
https://github.com/grafana/grafana/blob/master/public/app/routes/routes.ts#L227 

And handling it in the ReactContainer

2020-12-06 23:01 UTC, closed without merging