Fix: Hide long query expression on collapsed query row.
grafana/grafana pull request #27509
Opened 2020-09-10 13:09 UTC by peterholmberg

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #26708

**Special notes for your reviewer**:
![Screenshot from 2020-09-10 15-08-19](https://user-images.githubusercontent.com/946275/92733022-7bafd480-f377-11ea-8f5a-1773782e926c.png)

After 

![Screenshot from 2020-09-10 15-07-30](https://user-images.githubusercontent.com/946275/92733046-81a5b580-f377-11ea-84a1-292f32ff4f3f.png)

2020-09-14 09:38 UTC, dprokop requested changes
![image](https://user-images.githubusercontent.com/2376619/93070135-c8005a80-f67e-11ea-972e-951375ee35d0.png)


Can you please add an ellipsis to the cropped text?

2020-09-16 09:49 UTC, dprokop commented on public/app/core/components/QueryOperationRow/QueryOperationRow.tsx
> +      {actions && <div>{actionsElement}</div>}
Think there's something wrong here as the drag icon is missing

2020-09-16 09:50 UTC, dprokop commented
Ok, now it's good with the ellipsis. Think there's something wrong with the merge tho, as the drag and drop of the query rows does not work anymor.

2020-09-17 12:52 UTC, dprokop approved these changes
Works as expected. Fix tests and we are good to go:)

2020-09-18 04:25 UTC, hugohaggmark commented
@peterholmberg seems like Frontend tests are failing: https://drone.grafana.net/grafana/grafana/2861/1/10

2020-09-18 06:43 UTC, peterholmberg commented
@hugohaggmark they should be fixed in the latest commit?

2020-09-18 07:08 UTC, hugohaggmark commented
@peterholmberg try to create a new PR, seems like Drone is behaving super weirdly in this case

2020-09-18 07:10 UTC, closed without merging