Elasticsearch: Add support for custom query parameters
grafana/grafana pull request #27727
Opened 2020-09-23 11:36 UTC by Elfo404

**What this PR does / why we need it**:

Adds a configuration option for Elasticsearch datasource to allow users to append custom query parameters to the search URL
![Screenshot 2020-09-23 at 12 31 17](https://user-images.githubusercontent.com/1170767/94007032-b44ca680-fd98-11ea-8a59-733f4c1f0785.png)

**Which issue(s) this PR fixes**:

Fixes #18277 

**Special notes for your reviewer**:

2020-09-25 08:51 UTC, marefr requested changes
Looks good in general. Added some comments. 

Documentation needs update [here](https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#adding-the-data-source) and json data section [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#running-multiple-grafana-instances).

2020-09-25 08:51 UTC, marefr commented on pkg/tsdb/elasticsearch/client/client_test.go
> +					So(sc.request.URL.RawQuery, ShouldContainSubstring, "my_param=my_value")
A test including a parameter that requires URL encoding would be good to verify that it's properly URL encoded. Right now I think there's no handling of URL encoding.

2020-09-25 08:51 UTC, marefr commented on public/app/plugins/datasource/elasticsearch/configuration/ElasticDetails.tsx
> +            placeholder="Eg. my_param=my_value"
Should explain how to provide multiple parameters, maybe using an info-tooltip?

2020-09-25 08:51 UTC, marefr commented on public/app/plugins/datasource/elasticsearch/configuration/ElasticDetails.tsx
> +            label="Custom Query Parameters"
To make this explicit for search query parameters and nothing else, maybe consider naming this Custom Search Query Parameters?

2020-10-24 00:41 UTC, marefr commented
Any update here planned?

2020-10-28 10:14 UTC, Elfo404 commented
@marefr There are some pending discussions regarding the future of the ES plugin and what we want to support from the non-OSS version. I'll close this one for now and in case reopen it once we have a plan.

2020-10-28 10:14 UTC, closed without merging