Document update
grafana/grafana pull request #27785
Opened 2020-09-25 07:54 UTC by NiteshKoushik

Proper punctuations

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-09-25 17:12 UTC, oddlittlebird requested changes
Great changes! I have a couple more suggestions.

2020-09-25 17:12 UTC, oddlittlebird commented on docs/sources/features/datasources/influxdb.md
> +If you add a template variable of the type `Query` you can write an InfluxDB exploration (meta data) query. These queries can
```suggestion
If you add a template variable of the type `Query`, then you can write an InfluxDB exploration (metadata) query. These queries can
```

2020-09-25 17:12 UTC, oddlittlebird commented on docs/sources/features/datasources/influxdb.md
> +For example, you can have a variable that contains all values for tag `hostname` if you specify a query like this in the templating variable *Query* setting.
```suggestion
For example, you can have a variable that contains all values for tag `hostname` if you specify a query like this in the template variable **Query* setting.
```

2020-09-26 15:12 UTC, NiteshKoushik commented
Hello @oddlittlebird , Changes made as per the suggestion.

2020-09-28 16:27 UTC, oddlittlebird approved these changes
Excellent. Thanks for contributing to the docs!

2020-09-28 16:27 UTC, merged