Document update
grafana/grafana pull request #27783
Opened 2020-09-25 07:23 UTC by NiteshKoushik

Change in key word "to" to "two"

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-09-25 17:10 UTC, oddlittlebird requested changes
Nice catch! One more minor change, if you would. I spotted a missing period.

2020-09-25 17:10 UTC, oddlittlebird commented on docs/sources/features/datasources/elasticsearch.md
>  Query | You can leave the search query blank or specify a lucene query
```suggestion
Query | You can leave the search query blank or specify a lucene query.
```

2020-09-26 15:11 UTC, NiteshKoushik commented
Hello @oddlittlebird , Changes mad as per the suggestion.

2020-09-28 16:27 UTC, oddlittlebird approved these changes
Thanks for contributing to the docs!

2020-09-28 16:28 UTC, merged