Cloudwatch: Add support for AWS DirectConnect virtual interface metrics.
grafana/grafana pull request #28008
Opened 2020-10-02 16:53 UTC by jgulick48

**What this PR does / why we need it**:
Add support for AWS DirectConnect virtual interface metrics.

**Which issue(s) this PR fixes**:
Closes #28006

2020-10-02 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=28008) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=28008) before we can accept your contribution.<br/><hr/>**Jeremy Gulick** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=28008) it.</sub>

2020-10-05 12:00 UTC, papagian requested changes
Thank you for your contribution. Looks good but there are [some missing dimensions](https://docs.aws.amazon.com/directconnect/latest/UserGuide/monitoring-cloudwatch.html#metrics-available-dimensions) as well. You need to add `OpticalLaneNumber` and `VirtualInterfaceId` [along with](https://github.com/grafana/grafana/blob/e79dc0ef55b771713f605a98c6c7d841582caa78/pkg/tsdb/cloudwatch/metric_find_query.go#L158) `ConnectionId`.

2020-10-05 15:42 UTC, jgulick48 commented
Dimensions have been added to the AWS/DX namespace.

2020-10-05 16:17 UTC, papagian approved these changes
Thank you for your contribution!

2020-10-05 16:19 UTC, merged