Auth: Redirect to login when anonymous and different org
grafana/grafana pull request #28158
Opened 2020-10-09 23:54 UTC by marefr

**What this PR does / why we need it**:
If anonymous access is enabled for an org and there are multiple
orgs. When a non-authenticated user requests a page that requires 
user to be logged in and orgId query string is set in the request URL 
to an org that not equals the anonymous org, the user should be 
redirected to the login page.

**Which issue(s) this PR fixes**:
Fixes #26120 

**Special notes for your reviewer**:
As soon as I realized the problem described in the referenced issue I understood that it's the same problem I've experienced several times on for example play.grafana.org. That's why I took a stab at trying to resolve this.

Tried to convert tests to standard Go test library, but there's just too many changes needed for the `middlewareScenario` so suggest trying to fix that some other time.

2020-10-10 13:05 UTC, aknuds1 requested changes
Global state changes in tests should be cleaned up, to avoid potential interference with other tests.

2020-10-10 13:05 UTC, aknuds1 commented on pkg/middleware/auth_test.go
> +			setting.AnonymousOrgName = "test"
Global state changes should be cleaned up.
```suggestion
			origEnabled := setting.AnonymousEnabled
			t.Cleanup(func() {
				setting.AnonymousEnabled = origEnabled
			})
			origName := setting.AnonymousOrgName
			t.Cleanup(func() {
				setting.AnonymousOrgName = origName
			})
			setting.AnonymousEnabled = true
			setting.AnonymousOrgName = "test"
```

2020-10-10 14:14 UTC, papagian requested changes
I have tested the following scenarios and all work perfect! I only have some small suggestions.

I have two organisations (org1 and org2) and I have enabled anonymous access for org1.
- A user navigates to a dashboard in org2 and is redirected to the login page. 
- A user navigates to a dashboard in org1 and is navigated to the dashboard.
- A user navigates to a dashboard in org1 (with `forceLogin=true`) and redirected to the login page.

I have also tested without enabling  anonymous access and the the user is always redirected to the login page.

2020-10-12 16:15 UTC, marefr commented on pkg/middleware/auth.go
> +				if err == nil && orgID > 0 && orgID != c.OrgId {
I copied it from https://github.com/grafana/grafana/blob/957c88eaca0bfd666ad525ef607df4d60c4c4ea2/pkg/middleware/org_redirect.go#L19-L20

Yes, it's probably safer.

2020-10-12 16:21 UTC, aknuds1 approved these changes
LGTM

2020-10-12 21:30 UTC, marefr commented on pkg/middleware/auth.go
> +				if err == nil && orgID > 0 && orgID != c.OrgId {
I changed to int64 in both places

2020-10-13 06:09 UTC, papagian approved these changes

2020-10-13 06:47 UTC, aknuds1 commented
This needs a merge with master.

2020-10-23 14:34 UTC, merged