Elasticsearch: Use 'source' as inline script key for versions 5.6+
grafana/grafana pull request #28271
Opened 2020-10-14 21:26 UTC by fabsrc

**What this PR does / why we need it**:

Sets `source` as key for inline aggregation scripts for all ES versions 5.6+. `inline` (current key, but deprecated in version 5.6) will be used for all versions <5.6.
This should fix the deprecation warnings in the ES deprecation logs.

**Which issue(s) this PR fixes**:

Fixes #23766

**Special notes for your reviewer**:

2020-10-14 21:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=28271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=28271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=28271) it.</sub>

2020-10-15 05:56 UTC, zoltanbedi commented
Thanks for contributing @fabsrc this looks good to me. Can you confirm this @Elfo404 please?

2020-10-15 09:52 UTC, Elfo404 requested changes
Hi @fabsrc! thanks for the PR!

This looks good, but do you mind adding a test for this in `public/app/plugins/datasource/elasticsearch/specs/query_builder.test.ts` to check whether the correct key is used for both `< 5.6` and `>= 5.6`?

We are in the process of refactoring this data source and this kind of changes are hard to keep track of without failing tests :)

2020-10-15 22:21 UTC, fabsrc commented
Since this logic was outside the `ElasticQueryBuilder` there was no easy way of testing it.
I moved the logic into the `ElasticQueryBuilder#build` method now, which seems like a better place for it anyway. All the other conditional logic based on ES versions is also located there.

2020-10-16 10:51 UTC, Elfo404 commented on public/app/plugins/datasource/elasticsearch/query_builder.ts
> +      if (metric.inlineScript) {
Just to be functionally equivalent to the previous version, what do you think about adding this?

```suggestion
      const supportsInlineScript = !!queryDef.metricAggTypes.find(metricDef => metricDef.value === metric.type)
        ?.supportsInlineScript;

      if (supportsInlineScript && metric.inlineScript) {
```

the reason is that when changing metric type from the query editor we don't erase previously set properties from `settings`, which means you can set a script on a metric that supports it, then change the metric type to something that doesn't support it and the `inlineScript` would maintain the previous value. without this extra check the query builder would add `script: { 'inline/source': ...}` to every metric instead to only those that supports it.

2020-10-16 12:56 UTC, Elfo404 commented
@fabsrc I was testing this out, and i'm not sure why, but with your changes the query generated when creating alerts does not include the script. I'll try to investigate a bit more later on, but could you please double check?

2020-10-16 17:34 UTC, fabsrc commented
@Elfo404 I checked the issue with the alerts. Seems like the server side query parser uses the model (not the query from the `query_builder.ts`) to construct the ES query. And since the inline script logic does not exist there, the query is sent to ES without the inline script.

The solutions I see here would be to implement the logic on the server side as well or just go back to the previous solution and maybe add a function to `query_def.ts` which returns the inline script settings object based on the ES version.
I would prefer the latter as it adds less complexity. E.g.

```ts
export function getInlineScriptSetting(inlineScript: string, esVersion: number) {
  const keyName = esVersion < 56 ? 'inline' : 'source';
  return { [keyName]: inlineScript };
}
```

which is then called like this in the controller:

```ts
$scope.agg.settings.script = queryDef.getInlineScriptSetting(inlineScript, $scope.esVersion);
```

2020-10-20 16:17 UTC, Elfo404 commented
@fabsrc 
> The solutions I see here would be to implement the logic on the server side as well or just go back to the previous solution and maybe add a function to `query_def.ts` which returns the inline script settings object based on the ES version.
> I would prefer the latter as it adds less complexity. E.g.

I would generally agree, but this would require users to manually update all of their queries if they want the setting to be effectively applied (especially if at some point in the future the deprecated key is going to be removed) and as a general rule we would like users to actively maintain (as in fixing) their dashboards as little as possible.

So maybe in this case decoupling what we store to what is actually sent to ES would be the best way to go. What do you think?

2020-10-20 20:26 UTC, fabsrc commented
I was a bit worried about the code duplication in the frontend and the backend query builder. But if both are tested well enough, there should be no issue.

I'll try to adjust the server logic then as well.

2020-12-09 13:06 UTC, Elfo404 commented
Hi @fabsrc, any plan on picking this up? 
I'm closing the PR due to inactivity, but feel free to reopen/ping me if you have any updates.

2020-12-09 13:06 UTC, closed without merging

2020-12-10 15:08 UTC, fabsrc commented
> Hi @fabsrc, any plan on picking this up?
> I'm closing the PR due to inactivity, but feel free to reopen/ping me if you have any updates.

Aah, kind of forgot about this one.
I have some WIP for the backend changes, but still needs some tweaking.
Will reopen the PR once it's finished.