API: Query database from /api/health endpoint
grafana/grafana pull request #28349
Opened 2020-10-18 18:29 UTC by ceh

**What this PR does / why we need it**:

Query the database from the `/api/health` endpoint by issuing a `SELECT` query to check if the database is healthy, rather than just verifying the connection with `Ping`.

**Which issue(s) this PR fixes**:

Fixes #28214

**Special notes for your reviewer**:

I was a bit curious about the in-process bus, and what caching alternatives that is available, so I took a stab at fixing the issue.

What do you think of the approach @bergquist?

2020-10-19 06:16 UTC, aknuds1 requested changes
Generally looks pretty good AFAICT, with some suggestions for improvement. I think @bergquist should give feedback though since he requested the change.

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health.go
> +}
Please just inline this method, since it's too simple to extract as a separate function (doesn't outweigh the cost of the abstraction).

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health.go
> +func (hs *HTTPServer) databaseHealthyWithCache() bool {
Please inline `databaseHealthyWithCache` and rename this one to drop the WithCache suffix.
```suggestion
func (hs *HTTPServer) databaseHealthy() bool {
```

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health.go
> +	cacheKey := "db-healthy"
```suggestion
	const cacheKey = "db-healthy"
```

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health_test.go
> +	cacheKey := "db-healthy"
```suggestion
	const cacheKey = "db-healthy"
```

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health_test.go
> +	cacheKey := "db-healthy"
```suggestion
	const cacheKey = "db-healthy"
```

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/health_test.go
> +	cacheKey := "db-healthy"
```suggestion
	const cacheKey = "db-healthy"
```

2020-10-19 06:16 UTC, aknuds1 commented on pkg/api/http_server.go
> +	if !hs.databaseHealthyWithCache() {
```suggestion
	if !hs.databaseHealthy() {
```

2020-10-19 06:32 UTC, bergquist commented on pkg/api/health.go
> +	hs.CacheService.Set(cacheKey, healthy, time.Second*5)
```suggestion
	hs.CacheService.Set(cacheKey, healthy, time.Second*10)
```

2020-10-19 06:33 UTC, bergquist commented on pkg/api/health.go
> +	hs.CacheService.Set(cacheKey, healthy, time.Second*5)
I think the default value can be a bit higher. Looks good otherwise feature-wise.

2020-10-19 06:34 UTC, bergquist reviewed
Looks good feature-wise :)

2020-10-19 17:55 UTC, ceh commented
Thanks for the review @aknuds1! I've updated the PR, please take another look.

2020-10-21 08:36 UTC, papagian approved these changes
Great work! thank you for contributing.

2020-10-21 09:04 UTC, aknuds1 approved these changes
LGTM, nice one :)

2020-10-21 09:06 UTC, merged

2020-10-21 09:06 UTC, aknuds1 commented
Thanks for the contribution!