Dashboard: Fix navigation from one SoloPanelPage to another one
grafana/grafana pull request #28578
Opened 2020-10-27 18:05 UTC by hborchardt

**What this PR does / why we need it**:

The panel on the SoloPanelPage did not update after an internal navigation to another SoloPanelPage. The reason is that, because the props apparently are retained, in the `componentDidUpdate` function it was assumed that the dashboard was already fully loaded.

**Which issue(s) this PR fixes**: 

Fixes #28574 

**Special notes for your reviewer**:
I also added a test case, as there was none for the SoloPanelPage. I hope that it is helpful

2020-10-28 11:15 UTC, torkelo requested changes
Looks good except for the added snapshot test (we do not use them anymore, only painful when updating and almost never catches bugs). 

And for react component testing we are migrating to react testing-library, trying to stop using enzyme.

2020-10-28 11:31 UTC, hborchardt commented
Ha okay, I didn't know that, I copied from the DashboardPage test. I will improve it.

2020-10-28 13:34 UTC, dprokop requested changes
Looks good, echoing @torkelo request about tests :)

2020-10-28 18:05 UTC, hborchardt commented
Hopefully this test is better. I saw that doing a shallow render is discouraged in the testing-library, but it did not work for me with actually rendering a full panel in the test case and waiting for it to appear/change, so I hope you are fine with just checking that the panel arrives in the props of a mocked DashboardPage. I confirmed that the testcase was failing without my fix :)

2020-10-29 08:51 UTC, torkelo approved these changes
Looks good! 

Thanks for contributing! :heart:

2020-10-29 08:51 UTC, merged

2020-12-11 08:19 UTC, torkelo commented on public/app/features/dashboard/containers/SoloPanelPage.tsx
> +    if (!prevProps.dashboard || prevProps.dashboard.uid !== dashboard.uid) {
this can never happen, if you navigate to another dashboard there will be an unmount new SoloPage