Dashboard Schemas
grafana/grafana pull request #28793
Opened 2020-11-03 19:34 UTC by trotttrotttrott

**What this PR does / why we need it**:

Initial move of schemas from [grafana/dashboard-spec](https://github.com/grafana/dashboard-spec). Instead of copying them in their current state as OpenAPI YAML, I've converted them to [Cue](https://cuelang.org/). Cue is much more concise and can be exported as an OpenAPI document ([more info on that here](https://cuelang.org/docs/usecases/datadef/#json-schema--openapi)). It also has other interesting integrations like with [Go](https://cuelang.org/docs/integrations/go/) which may prove useful for backend validation.

This is not a complete collection of schemas. This is only to propose the use of Cue and how to organize the schemas. The `README` has more info on this.

2020-11-03 19:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=28793) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=28793) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=28793) it.</sub>

2020-11-11 06:02 UTC, aknuds1 commented
Thanks, going to have a look!

2020-11-19 08:20 UTC, aknuds1 commented
Sorry for the wait, got caught up in the meantime, trying to review again.

2020-11-19 11:01 UTC, aknuds1 approved these changes
Generally looks good as far as I can tell. Are these CUE files used to generate OpenAPI specs? How can I test them?

2020-11-19 11:01 UTC, aknuds1 commented on dashboard-schemas/Dashboard.cue
> +	// Time range for dashboard, i.e. last 6 hours, last 7 days, etc
You probably want e.g., since they are example values:
```suggestion
	// Time range for dashboard, e.g. last 6 hours, last 7 days, etc
```

2020-11-19 11:01 UTC, aknuds1 commented on dashboard-schemas/Dashboard.cue
> +		// Whether timepcker is visible or not.
```suggestion
		// Whether timepicker is visible or not.
```

2020-11-19 11:01 UTC, aknuds1 commented on dashboard-schemas/panels/Row.cue
> +	// Name of default datasource.
I think we've standardized on writing data source in two words.
```suggestion
	// Name of default data source.
```

2020-11-20 17:39 UTC, aknuds1 commented
@jdbaldry gave me this command for converting the CUE sources to OpenAPI output, but it's taking very long for some reason: `cue eval -o openapi+yaml:-  ./...`.

2020-11-20 17:58 UTC, aknuds1 requested changes
I think something must be broken since the following fails: 

```
$ cue export --out openapi -o - ./dashboard-schemas/...
expected label or ':', found 'IDENT' Organize:
    ./dashboard-schemas/transformations/Organize.cue:4:4
```

2020-11-24 03:56 UTC, trotttrotttrott commented
@aknuds1 fixed the comments per your suggestions and fixed a syntax error in `Organize.cue`. The command you mention should succeed now.

Exporting these files into an OpenAPI doc would be compatible with the code generator in [grafana/dashboard-spec](https://github.com/grafana/dashboard-spec). However, I suspect there could be a cleaner implementation of the generator [processing Cue in Go](https://cuelang.org/docs/integrations/go/#processing-cue-in-go) which I haven't yet managed to pursue. Cue appears to me to have more potential for versatility within the Grafana codebase, but my rationale is based on theory at this point. More work needs to be done for determining exactly how it will work in practice. Two big use cases being: 1) how can plugin frontends leverage these as models 2) how can the backend leverage these for validation.

2020-11-24 07:05 UTC, aknuds1 commented
@trotttrotttrott Thanks, now it works! :) I.e., I can export OpenAPI! 

```
$ cue export --out openapi -o - ./dashboard-schemas/..
{
    "openapi": "3.0.0",
    "info": {
        "title": "Generated by cue.",
        "version": "no version"
    },
[...]
}
```

2020-11-24 07:14 UTC, aknuds1 approved these changes
LGTM!

2020-11-24 07:54 UTC, merged