annotations: fetch all grafana annotations when no tags or dashboard ID is specified
grafana/grafana pull request #29033
Opened 2020-11-11 15:58 UTC by kevingessner

**What this PR does / why we need it**:

There's currently no way to have a dashboard/panel display all Grafana-stored annotations -- you can either show them just on the panel where they were created, or by tag. This changes the behavior of the Tags type with no tags specified: it now fetches all annotations, instead of none. This enables showing all annotations, instead of an otherwise unuseful behavior. 

**Special notes for your reviewer**:

I ran the go and jest tests and they pass.

2020-11-11 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=29033) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=29033) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=29033) it.</sub>

2020-11-12 05:14 UTC, hugohaggmark requested changes
@kevingessner I'm sorry, but we rarely take contributions without a feature request that has a reasonable amount of feedback/upvotes. We'll probably have a look next week.

All the best

2020-11-12 19:30 UTC, kevingessner commented
@hugohaggmark Would it be helpful if I created a feature request issue to go along with this?

2020-11-13 05:16 UTC, hugohaggmark commented
> @hugohaggmark Would it be helpful if I created a feature request issue to go along with this?

Yes, that would be a great start, still that doesn't mean we'll accept this PR. It depends on popular demand like feedback/upvotes, complexity e.t.c. Thank you

2020-11-13 15:13 UTC, kevingessner commented
I've submitted #29105 for this! Thanks for taking a look.

2020-11-30 14:34 UTC, kevingessner commented
bump -- issue is in the backlog of feature requests

2020-12-22 22:16 UTC, kevingessner commented
(bump)

2020-12-23 05:16 UTC, hugohaggmark commented
We've looked at this and having it to default to fetch all annotations is not a great experience for users that have a lot of annotations. There should be an explicit choice in the UI somehow, so users know that making this choice will cause fetching all annotations.

2021-01-07 08:36 UTC, torkelo commented
Closing this as I think fetching all annotations without any filter feels like a bad idea

2021-01-07 08:36 UTC, closed without merging