Grafana: Rename By Regex Transformer
grafana/grafana pull request #29281
Opened 2020-11-20 23:02 UTC by simianhacker

**What this PR does / why we need it**:

This PR allows users to rename metrics by using a regular expression and replacement pattern via a transformer. This is useful for when you're doing a terms aggregation in something like Elasticsearch and you want to modify the values of the terms. For example, let's say you have a terms agg on `host.name` your team is using a pattern like `web-{number}.example.com` and you only want to display `web-{number}` in the results. You would set the `Match` field to `([^.]+).example.com` and the `Replace` field. to `$1`; `web-01.example.com` would be come `web-01`.

In the screenshot below, this is transforming removing the first part of the `event.dataset` and only displaying the suffix, `system.cpu` to `cpu`.

![image](https://user-images.githubusercontent.com/41702/99857631-dc624700-2b48-11eb-9a96-8d3e2661c9a4.png)

This was originally requested in #5212 and subsequently requested in #29133. @torkelo mentioned that this should be done as a transformer in #29133.

**Which issue(s) this PR fixes**:

Fixes #5212

**Special notes for your reviewer**:

Let me know if there is a better name then `Rename by regex` or if we need to change the form layout.

2020-11-25 19:26 UTC, simianhacker commented
Is there a way to get access to the video output of the E2E tests on CI? These tests pass locally when I run `yarn e2e` but I'm unable to get the same tests to pass in CI. If you look at the commit history, I had to add `scrollIntoView()` for the transform panel to get it to pass locally but if I remove that, it fails.

2020-11-26 05:16 UTC, hugohaggmark commented
> Is there a way to get access to the video output of the E2E tests on CI? These tests pass locally when I run `yarn e2e` but I'm unable to get the same tests to pass in CI. If you look at the commit history, I had to add `scrollIntoView()` for the transform panel to get it to pass locally but if I remove that, it fails.

Hi @simianhacker we used to, but we've recently switched to Drone, so right now it isn't possible. I'll checkout your branch and have a look to see if I can figure out what is going on.
(ping @aknuds1)

2020-11-26 05:42 UTC, hugohaggmark commented
@simianhacker I pushed some changes to the e2e tests that should fix them. I hope that is Ok.

2020-11-26 06:18 UTC, simianhacker commented
Totally OK! Thank you for the help!

2020-11-27 07:21 UTC, hugohaggmark reviewed
I think this PR is off to a brilliant start, but I hesitate to approve it because this transformer only operates on the name of frames. I think we need to incorporate renaming of field names and labels too in order to make it more intuitive for all use cases.

2020-11-30 16:44 UTC, simianhacker commented
@hugohaggmark Thanks for the feedback! I will apply it to fields and labels as well similar to `Filter by name`.

2020-11-30 19:38 UTC, simianhacker commented
@hugohaggmark I think the changes I just added should work as you suggested. I read through the `getDisplayName()` code and it appears to handle the labels as well, let me know if I've misinterpreted how that works.

2020-12-01 13:41 UTC, mckn requested changes
I think this looks great! Well done.

However I am missing some documentation for this. It would be awesome if you can add some information about how to use this with some examples here: https://github.com/grafana/grafana/blob/master/docs/sources/panels/transformations/types-options.md

Also - I think adding support for selecting at what level of the data frame you want to replace the naming e.g. so you can select either field, frame or labels. But I think we can merge this PR and add support for the other types in follow up PRs.

2020-12-01 22:05 UTC, simianhacker commented
> Also - I think adding support for selecting at what level of the data frame you want to replace the naming e.g. so you can select either field, frame or labels. But I think we can merge this PR and add support for the other types in follow up PRs.

@mckn In most of the other transformers, they seem to limit the functions to just the field, frame and labels without specifying which one to apply it to; are there plans to add that functionality to those transformers? 

@hugohaggmark What's the harm in applying this to the values as well? For example, one might want to modify the values returned from a term's aggregation in a data table, like below:

![image](https://user-images.githubusercontent.com/41702/100794123-62e51700-33da-11eb-9061-314888ff80d1.png)

to something like this

![image](https://user-images.githubusercontent.com/41702/100797050-c40ee980-33de-11eb-8412-ce473be65230.png)

Or should that be a seperate transformer? "Replace values by regex" maybe? I put together a quick function that could easily accomplish this as well (for the screenshot above).

```typescript
const replaceValuesByRegex = (options: RenameByRegexTransformerOptions) => (frame: DataFrame) => {
  const regex = new RegExp(options.regex);
  const fields = frame.fields.map(field => {
    if (field.type !== 'string') {
      return field;
    }
    const values = [];
    for (let index = 0; index < field.values.length; index++) {
      const value = field.values.get(index);
      if (regex.test(value)) {
        values.push(value.replace(regex, options.renamePattern));
      } else {
        values.push(value);
      }
    }
    return { ...field, values: new ArrayVector(values) };
  });
  return { ...frame, fields };
};
```

@mckn I started working on the documentation today but I wanted to resolve these questions before I finalize it.

2020-12-02 05:12 UTC, hugohaggmark commented
@simianhacker we've recently added a transformer that filters by value, so I think adding a new one that renames by value should be ok. But I would wait a bit with that one, maybe create a feature request to gather more feedback from the community. WDYT?

2020-12-02 16:23 UTC, simianhacker commented
@hugohaggmark Sounds good, I will get the docs done and work on wrapping this one up.

2020-12-02 23:13 UTC, simianhacker commented
@hugohaggmark I added some documentation, writing is not my forté so please feel free to suggest some edits. I also created some images for the documentation but I couldn't figure out where those images are stored in the repo.

2020-12-03 06:01 UTC, hugohaggmark commented
> @hugohaggmark I added some documentation, writing is not my forté so please feel free to suggest some edits. I also created some images for the documentation but I couldn't figure out where those images are stored in the repo.

Maybe @oddlittlebird can help with the images as I really don't know how to either?

2020-12-03 15:53 UTC, achatterjee-grafana commented
@hugohaggmark, images are kept in the website repo. Diana, how will we add the images in? Thanks.

2020-12-03 20:57 UTC, oddlittlebird commented
The images are stored in a private repo. If you or Hugo can take some screenshots and then attach them here (please label them with what they are and where they should go, then a Grafana maintainer can add them to the private website repo in a separate PR.

2020-12-03 21:00 UTC, oddlittlebird commented
The addition to the docs looks good to me. Thanks for including examples!

2020-12-03 21:50 UTC, simianhacker commented
@oddlittlebird Here are the images

#### rename-by-regex-before.png

<img width="1367" alt="rename-by-regex-before" src="https://user-images.githubusercontent.com/41702/101092294-ad02ff80-3576-11eb-97d7-cc546649d0fb.png">

#### rename-by-regex-after.png

<img width="1367" alt="rename-by-regex-after" src="https://user-images.githubusercontent.com/41702/101092339-bf7d3900-3576-11eb-83a6-3edad224b255.png">

2020-12-04 08:31 UTC, osg-grafana commented
@oddlittlebird What are the guidelines for image size, width, height, and file type? I expect that we can address such questions outside of this particular PR, and this is the context in which I thought to ask this question.

2020-12-04 17:48 UTC, oddlittlebird reviewed
rename-by-regex-before-7-3.png and rename-by-regex-after-7.3.png have been merged to the website repo.

2020-12-04 17:48 UTC, oddlittlebird commented on docs/sources/panels/transformations/types-options.md
> +{{< docs-imagebox img="/img/docs/transformations/rename-by-regex-after.png" class="docs-image--no-shadow" max-width= "1100px" >}}
```suggestion
{{< docs-imagebox img="/img/docs/transformations/rename-by-regex-after-7-3.png" class="docs-image--no-shadow" max-width= "1100px" >}}
```

2020-12-04 17:48 UTC, oddlittlebird commented on docs/sources/panels/transformations/types-options.md
> +{{< docs-imagebox img="/img/docs/transformations/rename-by-regex-before.png" class="docs-image--no-shadow" max-width= "1100px" >}}
```suggestion
{{< docs-imagebox img="/img/docs/transformations/rename-by-regex-before-7-3.png" class="docs-image--no-shadow" max-width= "1100px" >}}
```

2020-12-04 17:55 UTC, oddlittlebird commented
> @oddlittlebird What are the guidelines for image size, width, height, and file type? I expect that we can address such questions outside of this particular PR, and this is the context in which I thought to ask this question.

Image guidelines are in the [Grafana documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md#images).

2020-12-04 18:51 UTC, achatterjee-grafana reviewed
Added a few comments.

2020-12-04 18:51 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/types-options.md
> +Here is an example where we are stripping the prefix from event types, in the before you can see everything is prefixed with `system.`
```suggestion
In the following example, we are stripping the prefix from event types. In the before image, you can see everything is prefixed with `system.`
```

2020-12-04 18:51 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/types-options.md
> +{{< docs-imagebox img="/img/docs/transformations/rename-by-regex-before-7-3.png" class="docs-image--no-shadow" max-width= "1100px" >}}
Why are the images named before-7-3? If we are adding new images, should we capture them from the latest build?

2020-12-09 10:30 UTC, mckn approved these changes
Awesome job on this!

2020-12-09 10:31 UTC, merged

2020-12-09 13:17 UTC, charlescva commented
Woot! 4.5 years after asking for this in issue #5212 and it's here! Great job!

2020-12-09 15:54 UTC, oddlittlebird commented
@mckn , is this going to be in 7.4? If so, then we need to add a note to the docs indicating that immediately. It will cause user confusion otherwise.

2020-12-10 09:51 UTC, mckn commented
> @mckn , is this going to be in 7.4? If so, then we need to add a note to the docs indicating that immediately. It will cause user confusion otherwise.

Yes, added in this PR: #29735. Great catch!

2021-04-05 23:20 UTC, dicer commented
> @simianhacker we've recently added a transformer that filters by value, so I think adding a new one that renames by value should be ok. But I would wait a bit with that one, maybe create a feature request to gather more feedback from the community. WDYT?

Is there a feature request or PR for this yet? Would this allow me to rename all kinds of values? I have some queries that return strings like "closed" and I would like to rename them to "0" (and "open" to "1"), so I can graph them.

2021-04-06 00:51 UTC, simianhacker commented
> Is there a feature request or PR for this yet? Would this allow me to rename all kinds of values? I have some queries that return strings like "closed" and I would like to rename them to "0" (and "open" to "1"), so I can graph them.

@dicer There isn't a feature request or PR, I had added it as part of this change but then pulled it out per the conversation above. If we implemented this for values, it would give you all the power of a find/replace regular expression. You could create one transformer that replaced all the zeros with `closed` and a second one that replaces all the ones with `open`.

2021-04-06 19:40 UTC, oddlittlebird commented
Folks, please open a new issue rather than having discussions on merged PRs.