PanelChrome: New logic less emotion based PanelChrome with no dependency on PanelModel or DashboardModel
grafana/grafana pull request #29456
Opened 2020-11-29 08:50 UTC by torkelo

This early work trying to extract the styles and visualization aspect of the panel chrome to a new component with emotion styles that has no logic or dependency on PanelModel & DashboardModel.  (Plan is to rename PanelChrome and PanelChromeAnguar to something else). 

Plan is to then experiment with new layout and styles for panel header & icons & panel links. 

super early state 
![Screenshot from 2020-11-29 09-44-34](https://user-images.githubusercontent.com/10999/100537340-e3afe180-3227-11eb-871d-19a3c5624182.png)

2021-03-17 15:22 UTC, mckn commented
![panel_chrome](https://user-images.githubusercontent.com/172951/111492431-f3065c80-873c-11eb-8986-c562bec43689.gif)

2021-03-17 15:27 UTC, torkelo reviewed
Looks good!

2021-03-17 15:27 UTC, torkelo commented on packages/grafana-ui/src/components/PanelChrome/PanelChrome.tsx
> +  const styles = getStyles(theme);
```suggestion
  const styles = useStyles(getStyles);
```

2021-03-18 09:48 UTC, mckn approved these changes
Adding a review for the "Looks good" from @torkelo

2021-03-18 10:22 UTC, peterholmberg requested changes
Very nice @mckn ! It would be nice with a story with controls too so I as a user can change behavior without changing the code.

2021-03-18 10:24 UTC, torkelo commented
I think all the behaviors are already exposed in the different examples

2021-03-18 12:21 UTC, peterholmberg approved these changes

2021-03-18 12:22 UTC, merged