3 minor changes, including updating the title TOC
grafana/grafana pull request #29501
Opened 2020-12-01 15:35 UTC by achatterjee-grafana

1. Changed topic description on TOC to "With Grafana and MS SQL Server".
2. Changed "MSSQL" in a note to "MS SQL".
3. Changed the sentence just before the image.

2020-12-01 15:38 UTC, oddlittlebird requested changes

2020-12-01 15:55 UTC, oddlittlebird commented on docs/sources/getting-started/getting-started-sql.md
> +For installations from the [grafana/grafana](https://github.com/grafana/grafana/tree/master) repository, `gdev-mssql` data source is available. Once you add this data source, the `Datasource tests -
Or a verb might be the wrong tense or a gerund. I'm not sure whether you're generating panels or showing them.

2020-12-02 02:22 UTC, achatterjee-grafana commented on docs/sources/getting-started/getting-started-sql.md
> +> **Note:** You must install Grafana 5.1+ in order to use the integrated MS SQL data source.
Will do, in separate PR.

2020-12-02 16:09 UTC, oddlittlebird approved these changes
LGTM

2020-12-02 16:19 UTC, merged