CloudWatch: namespace in search expression should be quoted if match …
grafana/grafana pull request #29563
Opened 2020-12-03 10:08 UTC by ying-jeanne

…exact is enabled #29109

**What this PR does / why we need it**: The pr is to fix problem of issue #29109 

**Which issue(s) this PR fixes**:  

Fixes #29109 

**Special notes for your reviewer**:

2020-12-03 12:57 UTC, papagian requested changes
It works fine but I have a small suggestion.

2020-12-03 12:57 UTC, papagian commented on pkg/tsdb/cloudwatch/metric_data_query_builder.go
> +		schema := fmt.Sprintf(`"%s"`, query.Namespace)
```suggestion
		schema := fmt.Sprintf("%q", query.Namespace)
```

I would just using `%q` instead that prints a double-quoted string safely escaped with Go syntax.

2020-12-04 07:47 UTC, papagian approved these changes
LGTM

2020-12-07 20:14 UTC, ying-jeanne commented
<img width="971" alt="beforechange" src="https://user-images.githubusercontent.com/74549700/101400390-22e9cc80-38d1-11eb-9316-3d57cf9bf026.PNG">
<img width="646" alt="afterchange" src="https://user-images.githubusercontent.com/74549700/101400398-254c2680-38d1-11eb-86b9-ef0191dabcc2.PNG">

the search with "" or not seems having the same meaning, compared the graph with 2 different ways, seems the same, we could also compare the response from backend regarding the data points to make sure.

2020-12-08 11:22 UTC, ying-jeanne commented
![image](https://user-images.githubusercontent.com/74549700/101477701-df827300-394f-11eb-8c80-fc1d006937d2.png)
![image](https://user-images.githubusercontent.com/74549700/101477724-e6a98100-394f-11eb-87ba-d179d4cf5088.png)

the input is configured with matrix = * and match exact turned on, in the screen copy, we can see the search expression generated are different (after change with double-quote on the namespace, before none), the search result dataframe are exactly the same, so no regression introduced.

2020-12-08 11:36 UTC, sunker approved these changes
LGTM

2020-12-08 11:37 UTC, merged