Fix doc reference
grafana/grafana pull request #29614
Opened 2020-12-04 13:02 UTC by faxm0dem

Fixes #29612

2020-12-04 13:17 UTC, osg-grafana approved these changes

2020-12-04 15:10 UTC, oddlittlebird requested changes

2020-12-04 15:10 UTC, oddlittlebird commented on docs/sources/panels/visualizations/logs-panel.md
> +For logs where a **level** label is specified, we use the value of the label to determine the log level and update color accordingly. If the log doesn't have a level label specified, we parse the log
```suggestion
For logs where a **level** label is specified, we use the value of the label to determine the log level and update color accordingly. If the log doesn't have a level label specified, we parse the log to find out if its content matches any of the supported expressions (see below for more information). The log level is always determined by the first match. If Grafana cannot determine a log level, then it is visualized with **unknown** log level.

For more information, refer to [Supported log levels and mappings of log level abbreviation and expressions]({{< relref "../../explore/#log-level/" >}}).
```

2020-12-07 18:27 UTC, oddlittlebird approved these changes

2020-12-28 16:03 UTC, achatterjee-grafana approved these changes
LGTM

2021-01-04 15:57 UTC, oddlittlebird commented
@faxm0dem , once you fix the conflicts, we can merge this.

2021-01-05 08:17 UTC, faxm0dem commented
This has been fixed meanwhile in 555d3c275d1e4dd8c377630293a8353c2306dba3

2021-01-05 14:01 UTC, achatterjee-grafana commented
@faxm0dem, I still see the conflict.

2021-01-05 14:12 UTC, faxm0dem commented
You don't understand : this has been fixed in parallel by someone else (see the referenced commit)
so this PR is no longer needed

2021-01-05 14:12 UTC, closed without merging