cloud monitoring - add backend services dashboard
grafana/grafana pull request #29758
Opened 2020-12-10 19:55 UTC by naseemkullah

**What this PR does / why we need it**:

This dashboard is based on one that I submitted to Cloud Moniroting Sample Dashboards, it is very useful to get per service golden signals.

https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/master/dashboards/networking/https-lb-backend-services-monitoring.json

cc @papagian 

Special notes:
It would be great to share with the community and build on it, we are currently in the process of replacing our Cloud Monitoring dashbaords with grafana ones. The Cloud Monitoring plugin by Grafana is great btw

2020-12-10 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=29758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=29758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=29758) it.</sub>

2020-12-11 08:10 UTC, papagian requested changes
Thank your contribution!
There is a remaining reference to `DS_GOOGLE_CLOUD MONITORING`.
Also you have to register you dashboard [in the plugin.json](https://github.com/grafana/grafana/blob/d0f52d5334d1e3623c7360d0291d29deb5d3f6eb/public/app/plugins/datasource/cloud-monitoring/plugin.json#L15) together with the others.

2020-12-11 08:10 UTC, papagian commented on public/app/plugins/datasource/cloud-monitoring/dashboards/loadBalancerBackendServices.json
> +        "datasource": "${DS_GOOGLE_CLOUD MONITORING}",
```suggestion
        "datasource": "$datasource",
```

2020-12-11 09:25 UTC, naseemkullah commented
Thanks @papagian! Corrections applied.

2020-12-11 09:38 UTC, naseemkullah commented on public/app/plugins/datasource/cloud-monitoring/dashboards/loadBalancerBackendServices.json
> +  "uid": "googlecloudhttpslbbackendservices",
BTW, would a generated hash preferred here?

2021-01-20 08:42 UTC, sunker commented
Thank you so much for contributing @naseemkullah! We ended up modifying this dashboard just a tiny bit and then put it in [this](#29930) PR alongside a few other dashboards from Googles sample dashboard repo. Hope that's okay with you. Again, thank you so much for helping out on this!

2021-01-20 08:42 UTC, closed without merging

2021-01-20 13:12 UTC, naseemkullah commented
Sounds good, thanks.