Draft: Variables: Make TextBox variable width adjustable.
grafana/grafana pull request #29794
Opened 2020-12-13 00:54 UTC by STEELBADGE

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-12-14 08:26 UTC, STEELBADGE commented
The license check seems to be a bit flaky...passed on previous commits but doesn't seem to have run on the latest one - what should I do?

2020-12-14 15:43 UTC, oddlittlebird commented on docs/sources/variables/variable-types/add-text-box-variable.md
> +1. In the **Width** field, enter the width the Text Box should be if you need slightly more or less space for your users to enter their text.
```suggestion
1. In the **Width** field, enter the text box width if you need slightly more or less space for your users to enter their text. 
```

2020-12-14 15:44 UTC, oddlittlebird commented on docs/sources/variables/variable-types/add-text-box-variable.md
> +1. In the **Width** field, enter the width the Text Box should be if you need slightly more or less space for your users to enter their text.
I recommend adding "The default width is XX." to the end of this step.

2020-12-14 15:47 UTC, oddlittlebird commented
Note to reviewers, we will need to update imag

> The license check seems to be a bit flaky...passed on previous commits but doesn't seem to have run on the latest one - what should I do?

Everything seems to be flaky atm. The license check looks fine now. If it still is problematic after this PR is reviewed, then the devs will help you troubleshoot it.

2020-12-15 06:40 UTC, torkelo commented
Is another option to make the width dynamic as you type?

2020-12-15 10:07 UTC, STEELBADGE commented
That works too - do we just need to set the grow flag on the input component to be true for that to work?

2020-12-19 15:02 UTC, torkelo commented
No there is no such support built into the Input component

2021-02-23 07:02 UTC, hugohaggmark requested changes
I think the approach where the input grows is preferable to adding more properties to the variable system.

2021-04-20 17:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=29794) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=29794) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=29794) it.</sub>

2021-10-16 00:00 UTC, anthonyalayo commented
Would it be possible to revive this? I would love to see this feature merged!

2021-11-16 08:51 UTC, closed without merging

2023-01-31 08:47 UTC, BigUV commented
@hugohaggmark Can you explain why this PR haven't been merge ?
The super small filter field is so annoying..

2023-02-28 13:41 UTC, freesinger commented
Really confused why this simple feature hadn't been taken.
And it really frustrates me even in v9.2.0

2023-08-11 18:21 UTC, juanicabanas commented
@torkelo this FR was requested [here](https://github.com/grafana/grafana/issues/29672)
what about setting this properties in <Input /> component?
minWidth={21}
width={updatedValue?.length || 21}

I wonder if this would be correct, since the Input component multiplies the width by 8

2023-08-17 12:06 UTC, torkelo commented
@juanicabanas the input should adjust to the text entered (with some max width hardcoded as percentage of screen width )