loki.md: Add example of Loki data source config
grafana/grafana pull request #29976
Opened 2020-12-24 04:39 UTC by tonychoe

**What this PR does / why we need it**:

It was little difficult to find example of setting datasourceUid for Loki-Jaeger data source referencing.

I found the answer from [issue#26087](https://github.com/grafana/grafana/issues/26087) and thought it would be good to document it.

**Which issue(s) this PR fixes**:

Document the solution in #26087

2020-12-24 04:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=29976) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=29976) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=29976) it.</sub>

2021-01-04 15:56 UTC, oddlittlebird requested changes
Nice add! I made a few suggestions to help it more closely align with our style guide.

2021-01-04 15:56 UTC, oddlittlebird commented on docs/sources/datasources/loki.md
> +      # uid should be matching with datasourceUid in dervidedFields.
```suggestion
      # UID should match the datasourceUid in dervidedFields.
```

2021-01-04 15:56 UTC, oddlittlebird commented on docs/sources/datasources/loki.md
> +Here's example of Jaeger datasource corresponding to the above example. Note Jaeger's `uid` value does match with Loki's `datasourceUid` value.
```suggestion
Here's an example of a Jaeger data source corresponding to the above example. Note that the Jaeger `uid` value does match the Loki `datasourceUid` value.
```

2021-01-05 03:47 UTC, tonychoe commented
@oddlittlebird thank you for suggestion, looks a lot cleaner. Let's release this.

2021-01-05 20:40 UTC, oddlittlebird approved these changes
Thanks for contributing to the Grafana docs!

2021-01-05 20:41 UTC, merged