use sha256 checksum instead of md5
grafana/grafana pull request #30018
Opened 2020-12-31 15:53 UTC by ying-jeanne

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #29389 

**Special notes for your reviewer**:

2020-12-31 15:54 UTC, ying-jeanne commented
I still need to test manually the plugin which is not downloaded from github, the checksum works correctly.

2020-12-31 16:11 UTC, aknuds1 reviewed
Generally LGTM, but see suggestions.

2020-12-31 16:11 UTC, aknuds1 commented on pkg/cmd/grafana-cli/services/api_client.go
> +		return errutil.Wrap("Failed to compute sha256 checksum", err)
Go errors should generally start with a lowercase letter:
```suggestion
		return errutil.Wrap("failed to compute SHA256 checksum", err)
```

2020-12-31 16:11 UTC, aknuds1 commented on pkg/cmd/grafana-cli/services/api_client.go
> +		return fmt.Errorf("expected sha256 checksum does not match the downloaded archive - please contact security@grafana.com")
```suggestion
		return fmt.Errorf("expected SHA256 checksum does not match the downloaded archive - please contact security@grafana.com")
```

2021-01-04 09:51 UTC, aknuds1 requested changes
I think we can remove MD5 references in grafana-cli now, want me to push a commit for this? Should also fix the test failure.

2021-01-04 11:53 UTC, aknuds1 approved these changes
LGTM

2021-01-04 12:27 UTC, merged