Docs to help users connect to Prometheus using SigV4
grafana/grafana pull request #30232
Opened 2021-01-12 16:39 UTC by mjseaman

**What this PR does / why we need it**:
This PR adds some documentation for connecting to Amazon Managed Service for Prometheus from the Prometheus data source. We need it to help reduce friction that AMP users currently experience when trying to connect using non-AMG Grafana.

**Which issue(s) this PR fixes**:
No issues; this is related to a request from AWS on behalf of AMP users.

Fixes #

**Special notes for your reviewer**:
Reach out @mjseaman, @bergquist or @jongyllen for background

2021-01-12 16:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=30232) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=30232) before we can accept your contribution.<br/><hr/>**Mitchel Seaman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=30232) it.</sub>

2021-01-12 16:45 UTC, mjseaman commented
@rakyll FYI

2021-01-12 18:46 UTC, achatterjee-grafana commented
This should be a separate topic in my opinion. We should not confuse folks using just Prometheus and Grafana. Also, keeping the information here will be a free advertisement for Amazon service.

@oddlittlebird and @daniellee, what do you think?

2021-01-12 18:52 UTC, oddlittlebird requested changes

2021-01-12 18:52 UTC, oddlittlebird commented on docs/sources/datasources/prometheus.md
> +The Prometheus data source works with Amazon Managed Service for Prometheus. If you are using an AWS Identity and Access Management (IAM) policy to control access to your Amazon Managed Service for P
```suggestion
The Prometheus data source works with Amazon Managed Service for Prometheus. If you are using an AWS Identity and Access Management (IAM) policy to control access to your Amazon Managed Service for Prometheus domain, then you must use AWS Signature Version 4 (AWS SigV4) to sign  all requests to that domain. For more details on AWS SigV4, refer to the [AWS documentation](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).
```

2021-01-12 18:52 UTC, oddlittlebird commented on docs/sources/datasources/prometheus.md
> +To connect the Prometheus data source to Amazon Managed Service for Prometheus using SigV4 authentication, see the AWS guide to [Set up Grafana open source or Grafana Enterprise for use with AMP](htt
```suggestion
To connect the Prometheus data source to Amazon Managed Service for Prometheus using SigV4 authentication, refer to the AWS guide to [Set up Grafana open source or Grafana Enterprise for use with AMP](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-query-standalone-grafana.html). 

> **Note:** Grafana version 7.3.5 or higher is required to use SigV4 authentication.

If you are running Grafana in an Amazon EKS cluster, follow the AWS guide to [Query using Grafana running in an Amazon EKS cluster](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-query-grafana-7.3.html).
```

2021-01-12 18:52 UTC, oddlittlebird commented
Looping in @scoren-gl for the Marketing perspective.

2021-01-12 20:51 UTC, mjseaman commented
Worth mentioning that this is likely to be a temporary addition. Eventually we will want SigV4 auth to be consistent across AWS data source plugins (Cloudwatch, Timestream, X-Ray, IoT Sitewise, etc.) and once they are consistent I agree that SigV4 should be a separate topic linked from each of them. until then, the configuration is a little different from one plugin to the next.

2021-01-12 21:12 UTC, achatterjee-grafana commented
Thanks for the clarification @mjseaman!

2021-01-12 23:12 UTC, oddlittlebird approved these changes
LGTM. Thanks for adding this, Mitch!

2021-01-13 00:00 UTC, rakyll approved these changes

2021-01-13 00:14 UTC, merged