Docs: Auditing updates
grafana/grafana pull request #30433
Opened 2021-01-20 13:42 UTC by AgnesToulet

**What this PR does / why we need it**:
Update the auditing documentation to reflect the changes we made in 7.4.

**Special notes for your reviewer**:
In a previous PR, my linter was misconfigured and did something weird with the table format. I removed this formatting in this PR's first commit. To review actual changes, click here: https://github.com/grafana/grafana/commit/adbf62aa94963c980a334648628ab682ce7b2423

Also I don't know how I should handle versionning for this content, add a version number column in the tables?

2021-01-20 13:51 UTC, osg-grafana requested changes

2021-01-20 13:51 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `action`\* | string | The request action (eg. `create`, `update`, `manage-permissions`). |
```suggestion
| `action`\* | string | The request action. For example, `create`, `update`, or `manage-permissions`. |
```

2021-01-20 13:51 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `grafanaVersion`\* | string | Grafana current version when this log is created. |
```suggestion
| `grafanaVersion`\* | string | Current version of Grafana when this log is created. |
```

2021-01-20 13:51 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `additionalData` | object | Provide additional information on the request. |
```suggestion
| `additionalData` | object | Provide additional information about the request. |
```

2021-01-20 13:51 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +- Log out (manual log out, token expired/revoked, [SAML Single Log Out]({{< saml.mld#single-logout >}})).
```suggestion
- Log out (manual log out, token expired/revoked, [SAML Single Log Out]({{< saml.md#single-logout >}})).
```

2021-01-20 13:51 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +- Log out (manual log out, token expired/revoked, [SAML Single Log Out]({{< saml.mld#single-logout >}})).
Vet for accuracy. Is this a typo?

2021-01-22 02:02 UTC, mjseaman approved these changes

2021-01-22 02:03 UTC, mjseaman commented
@osg-grafana @AgnesToulet this LGTM! good to go?

2021-01-22 10:02 UTC, osg-grafana requested changes

2021-01-22 10:02 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `additionalData` | object | Provide additional information about the request. |
```suggestion
| `additionalData` | object |  Additional information that can be provided about the request. |
```

2021-01-22 10:02 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `additionalData` | object | Provide additional information about the request. |
Changing this to passive because I am not sure who is doing what, and the structure of the rest of the entries are someone incomplete phrases.

2021-01-22 10:02 UTC, osg-grafana commented on docs/sources/enterprise/auditing.md
> +| `terminationReason` | `logout` | What causes the user to log out (manual logout, token expiration...)  |
```suggestion
| `terminationReason` | `logout` | The reason why the user logged out, such as a manual logout or a token expiring.  |     
```

2021-01-26 11:53 UTC, osg-grafana approved these changes

2021-01-26 16:57 UTC, merged

2021-01-26 18:16 UTC, oddlittlebird commented
Please make sure this doc is linked in the What's new in 7.4 topic.