Variables: Adds queryparam formatting option
grafana/grafana pull request #30858
Opened 2021-02-03 10:09 UTC by hugohaggmark

**What this PR does / why we need it**:
This PR adds the `queryparam` formatting options for variables as `${foo:queryparam}`. 
This PR also changes the default suggested variable inserted text in Data Links from `var-${name}=${value}` to `${name:queryparam}` 

**Example**
| Variable Name | Current Variable Value | Result
| --- | --- | --- |
| foo | All | var-foo=All
| foo | A | var-foo=A
| foo | B | var-foo=B
| foo | A + B | var-foo=A&var-foo=B

**Which issue(s) this PR fixes**:
Fixes #21459

**Special notes for your reviewer**:

2021-02-03 10:11 UTC, hugohaggmark commented
@oddlittlebird @achatterjee-grafana this feature is new in Grafana 7.4.1 do we need to add a note about this in the docs?

2021-02-03 11:41 UTC, torkelo approved these changes
Looks really good!

2021-02-03 15:49 UTC, oddlittlebird commented
Will it be in the release tomorrow? If so, then we should mention it in the What's New now. 

If later, will it be included in the auto-generated release notes?

2021-02-03 15:51 UTC, osg-grafana commented
> Will it be in the release tomorrow? If so, then we should mention it in the What's New now.
> 
> If later, will it be included in the auto-generated release notes?

7.4.1 is the target release version.

2021-02-03 15:52 UTC, oddlittlebird requested changes

2021-02-03 15:52 UTC, oddlittlebird commented on docs/sources/variables/advanced-variable-format-options.md
> +## Query Parameters
```suggestion
## Query parameters
```

2021-02-03 15:52 UTC, oddlittlebird commented on docs/sources/variables/advanced-variable-format-options.md
> +Formats single- and multi-valued variables into their query parameter representation like `var-foo=value1&var-foo=value2`.
```suggestion
Formats single- and multi-valued variables into their query parameter representation. Example: `var-foo=value1&var-foo=value2`
```

2021-02-03 15:53 UTC, oddlittlebird commented
> 7.4.1 is the target release version.

Yes, I saw that. Version != release date.  The questions stand.

2021-02-03 16:58 UTC, torkelo commented
> If later, will it be included in the auto-generated release notes?

yes will be part of the auto-generated release notes

2021-02-04 05:19 UTC, hugohaggmark commented on docs/sources/variables/advanced-variable-format-options.md
> +## Query Parameters
Fixed!

2021-02-04 05:19 UTC, hugohaggmark commented on docs/sources/variables/advanced-variable-format-options.md
> +Formats single- and multi-valued variables into their query parameter representation like `var-foo=value1&var-foo=value2`.
Fixed!

2021-02-04 14:33 UTC, oddlittlebird approved these changes
Looks good

2021-02-05 06:16 UTC, merged