Display global options when help is invoked for sub-commands
grafana/grafana pull request #31159
Opened 2021-02-12 08:33 UTC by dsotirakis

**What this PR does / why we need it**:

This PR is responsible for adding the feature to display global options, when dealing with a subcommand. Up until now, by running:

`$ grafana-cli plugins -h`, we had:

```
NAME:
   Grafana cli plugins - Manage plugins for grafana

USAGE:
   Grafana cli plugins command [command options] [arguments...]

COMMANDS:
     install                  install <plugin id> <plugin version (optional)>
     list-remote              list remote available plugins
     list-versions            list-versions <plugin id>
     update, upgrade          update <plugin id>
     update-all, upgrade-all  update all your installed plugins
     ls                       list all installed plugins
     uninstall, remove        uninstall <plugin id>

OPTIONS:
   --help, -h  show help
```

After this PR, running the same command, produces:

```
NAME:
   Grafana CLI plugins - Manage plugins for grafana

USAGE:
   Grafana CLI plugins command [command options] [arguments...]

COMMANDS:
   install                  install <plugin id> <plugin version (optional)>
   list-remote              list remote available plugins
   list-versions            list-versions <plugin id>
   update, upgrade          update <plugin id>
   update-all, upgrade-all  update all your installed plugins
   ls                       list all installed plugins
   uninstall, remove        uninstall <plugin id>
   help, h                  Shows a list of commands or help for one command

OPTIONS:
   --pluginsDir value       Path to the Grafana plugin directory (default: "/usr/local/var/lib/grafana/plugins") [$GF_PLUGIN_DIR]
   --repo value             URL to the plugin repository (default: "https://grafana.com/api/plugins") [$GF_PLUGIN_REPO]
   --pluginUrl value        Full url to the plugin zip file instead of downloading the plugin from grafana.com/api [$GF_PLUGIN_URL]
   --insecure               Skip TLS verification (insecure) (default: false)
   --debug                  Enable debug logging (default: false)
   --configOverrides value  Configuration options to override defaults as a string. e.g. cfg:default.paths.log=/dev/null
   --homepath value         Path to Grafana install/home path, defaults to working directory
   --config value           Path to config file
   --help, -h               show help (default: false)
```

**Which issue(s) this PR fixes**:

Fixes #21726

**Special notes for your reviewer**:

* One thing to point, is that when running sub-commands, the `GLOBAL OPTIONS` field is described as `OPTIONS`.

2021-02-12 09:07 UTC, aknuds1 commented
Read the changes, evaluating whether this is the right approach or if there's something built into the CLI framework we can rely on.

2021-02-12 09:20 UTC, dsotirakis commented
@aknuds1 I actually tried to fetch the flags from `cli.Context` but didn't work as expected. You can give it a try if you like as well.

2021-02-12 09:24 UTC, aknuds1 commented
> @aknuds1 I actually tried to fetch the flags from `cli.Context` but didn't work as expected. You can give it a try if you like as well.

Having thought about this solution, I'm skeptical of it since it assigns global options as sub-command options. What I actually want is to print global options _also_ when printing the help text for a sub-command. I'm hoping we can tweak [SubcommandHelpTemplate](https://pkg.go.dev/github.com/urfave/cli/v2#SubcommandHelpTemplate) to output also global options.

2021-02-12 10:09 UTC, aknuds1 requested changes
Requesting changes on the PR, since I don't think this is the right approach. I think the right approach is to somehow make urfave/cli print global options for sub-commands, which it doesn't currently do. Maybe it has to be patched, since I couldn't find support for getting at global flags in [SubcommandHelpTemplate](https://pkg.go.dev/github.com/urfave/cli/v2#SubcommandHelpTemplate).

2021-02-12 10:13 UTC, dsotirakis commented
> Requesting changes on the PR, since I don't think this is the right approach. I think the right approach is to somehow make urfave/cli print global options for sub-commands, which it doesn't currently do. Maybe it has to be patched, since I couldn't find support for getting at global flags in [SubcommandHelpTemplate](https://pkg.go.dev/github.com/urfave/cli/v2#SubcommandHelpTemplate).

Agree, will follow it up with urfave/cli project and I'll post the discussion

2021-02-12 13:02 UTC, dsotirakis commented
Please, follow [this issue](https://github.com/urfave/cli/issues/1243)

2021-04-20 17:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31159) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31159) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31159) it.</sub>

2021-05-20 10:09 UTC, marefr commented
@dsotirakis should we close this or are you working on it?

2021-05-20 10:11 UTC, dsotirakis commented
@marefr, saw that today, will file a PR to `urfave/cli` repo directly, so this can be closed.

2021-05-20 10:11 UTC, closed without merging