BarGuage: updates story from knobs to controls
grafana/grafana pull request #31223
Opened 2021-02-15 15:49 UTC by thisisobate

**What this PR does / why we need it**:
This PR updates story from knobs to controls
**Which issue(s) this PR fixes**:
Relates to #30182

2021-02-16 08:27 UTC, torkelo commented on packages/grafana-ui/src/components/BarGauge/BarGauge.story.tsx
> +};
These seems to be all set to the same value, you can just do 
gradientVertical.args = gradientHorizontal.args = lcdHorizontal.args

2021-02-16 14:15 UTC, peterholmberg requested changes
If you look at what Props the BarGauge has, there's no support to change any of them. We however have a lot of controls to change other things that are not directly tied to the component. I feel we should focus more on the look and feel of the actual component props rather than underlying things (like value and thresholds which is a nice plus I suppose).

2021-02-16 17:03 UTC, thisisobate commented
True...I agree with you @peterholmberg
I just added support for some useful props

2021-02-16 17:46 UTC, thisisobate commented on packages/grafana-ui/src/components/BarGauge/BarGauge.story.tsx
> +    },
So...these args are coming from the BarGauge Props.
Storybook automatically generates controls based on React components.

2021-02-18 10:46 UTC, torkelo approved these changes

2021-02-18 14:39 UTC, peterholmberg approved these changes
Very nice :ok_hand:

2021-02-18 15:03 UTC, merged

2021-02-24 05:51 UTC, hugohaggmark commented
Looking at this today and they're a lot of properties that aren't meaningful for the story like theme, field, value etc. Weren't we supposed to hide these? WDYT @torkelo?

![image](https://user-images.githubusercontent.com/562238/108954124-9697ac00-766c-11eb-82f7-888db1398785.png)

2021-02-24 06:07 UTC, torkelo commented
Yes I thought so

2021-02-24 06:11 UTC, hugohaggmark commented
I've updated the issue with my review of all migrated controls so far.