Docker: update custom image Dockerfile for install plugin from URL
grafana/grafana pull request #31234
Opened 2021-02-16 07:57 UTC by sgnsys3

**What this PR does / why we need it**:

Refer to this document: [https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins](https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins)

Installing plugins from URL is not supported when building Docker image with pre-installed plugins.

**Which issue(s) this PR fixes**:
Add install plugins from URL script when building Docker image with pre-installed plugins.

2021-02-16 07:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31234) it.</sub>

2021-02-17 07:14 UTC, aknuds1 reviewed
AFAICT, the technical changes make sense, but I'd have to hear with others to figure out if we want this. I think also documentation would have to be updated to reflect this support?

2021-02-17 09:23 UTC, marefr commented
@sgnsys3 could you please open a feature request describing the use case more detailed and why you cannot customize this in your custom built image and why it should be included in our custom image. Then reference the created issue in the PR description. Thanks

2021-02-18 04:40 UTC, sgnsys3 commented
@marefr I have created and reference issue in this PR. This is correct?

2021-03-08 09:39 UTC, marefr requested changes
Based on discussion in the issue this looks good. But the ubuntu.Dockerfile needs update as well.

2021-03-09 05:54 UTC, sgnsys3 commented
@marefr I updated ubuntu.Dockerfile.

2021-03-09 11:07 UTC, marefr approved these changes
LGTM

2021-03-09 11:15 UTC, marefr requested changes
Was a bit fast there. 
- Please merge with master to resolve CI build problems.
- Please update this [section in the documentation](https://grafana.com/docs/grafana/latest/installation/docker/#build-with-pre-installed-plugins) to denote installing plugins from other sources is supported. For reference, here's the [markdown file](https://github.com/grafana/grafana/blob/master/docs/sources/installation/docker.md#build-with-pre-installed-plugins) that needs update.

2021-03-10 15:24 UTC, oddlittlebird commented on docs/sources/installation/docker.md
> +You can build a Docker image with plugins from other sources by specifying the URL like this: `GF_INSTALL_PLUGINS=<url to plugin zip>;<plugin name>`.
```suggestion

You can build a Docker image with plugins from other sources by specifying the URL like this: `GF_INSTALL_PLUGINS=<url to plugin zip>;<plugin name>`.
```

2021-03-10 15:43 UTC, achatterjee-grafana approved these changes

2021-03-11 11:13 UTC, marefr approved these changes
LGTM

2021-03-11 11:17 UTC, merged

2021-03-11 11:17 UTC, marefr commented
Thank you for contributing to Grafana!

2021-03-11 11:20 UTC, marefr commented
Shouldn't need backport since [documentation](https://grafana.com/docs/grafana/latest/installation/docker/#build-and-run-a-docker-image-with-pre-installed-plugins) refers to this repository for building custom Docker image and the master branch is the default.