Devenv: Add gdev-influxdb2 data source
grafana/grafana pull request #31250
Opened 2021-02-16 16:34 UTC by ivanahuckova

**What this PR does / why we need it**:

We have InfluxDB v2 (Flux) devenv block that was added in https://github.com/grafana/grafana/pull/30827. This PR adds and configures the **gdev-influxdb2** data source with provisioning in `datasources.yaml` and `datasources_docker.yaml

Added to datasources_docker.yaml and tested with `make devenv sources=influxdb2,grafana grafana_version=7.4.1`:
![image](https://user-images.githubusercontent.com/30407135/108091789-550b6d80-707c-11eb-8ab3-a8a618f6c813.png)

Added to datasources.yaml and tested with `make devenv sources=influxdb2` and locally run grafana:
![image](https://user-images.githubusercontent.com/30407135/108092018-8dab4700-707c-11eb-8397-052be7f4b806.png)

2021-02-17 18:44 UTC, gabor commented
i tried it and it is working fine :+1: (at least in `make devenv=influxdb2` mode), but i cannot comment on the code-changes yet, better wait for @aocenas 's review.

2021-02-23 09:54 UTC, gabor requested changes
i think this line needs to be changed too, from "influxdb" to "influxdb2" https://github.com/grafana/grafana/blob/833446645acd3d48ea3e0db0f03b39c946634a3f/devenv/docker/blocks/influxdb2/telegraf.conf#L93

2021-02-23 10:00 UTC, ivanahuckova commented
> i think this line needs to be changed too, from "influxdb" to "influxdb2"

Good catch! Changed.

2021-02-23 13:03 UTC, aocenas approved these changes

2021-02-23 14:43 UTC, gabor approved these changes

2021-02-23 15:30 UTC, merged