Implement version sort for variables
grafana/grafana pull request #31512
Opened 2021-02-26 12:57 UTC by hasso

This implements the sorting algorithm for variables known as version sort as it's commonly used to sort version numbers. It's also very helpful if sorting network interface names, hostnames if IP addresses are used in them etc.

Fixes #7307

2021-04-20 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31512) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31512) it.</sub>

2021-07-22 10:22 UTC, ashharrison90 requested changes
hey @hasso 👋 

i wonder if we're trying to solve 2 separate use cases here. for version sorting, i think it would be more robust if we compared using the `semver` package. that way it will handle all the edge cases that this method won't quite catch. what do you think?

thanks for the contribution! 🥳

2021-07-22 10:22 UTC, ashharrison90 commented on public/app/features/variables/query/reducer.test.ts
> +      ${[{ text: '10' }, { text: null }, { text: '2' }]} | ${VariableSort.versionDesc}                     | ${[{ text: '10' }, { text: '2' }, { text: null }]}
it would be great if these tests contained some versions to better represent the use case

2021-07-22 10:22 UTC, ashharrison90 commented on public/app/features/variables/query/reducer.ts
> +      return opt.text.replace(/\d{1,15}/g, (n: number) => +n + Math.pow(10, 15));
i think `n` is a string here

2021-08-20 08:47 UTC, dprokop commented
@hasso I'm gonna close this PR now as we haven't heard from you in a while. But feel free to re-open it if you happen to jump back on it.

2021-08-20 08:47 UTC, closed without merging