InfluxDB: Region annotation support
grafana/grafana pull request #31526
Opened 2021-02-27 13:29 UTC by Komalis

**What this PR does / why we need it**:
This PR implements isRegion and timeEnd column in InfluxDB datasource according to "how to implement annotation" in order to use region annotation with InfluxDB.
It also provide a way to map the column name for isRegion and timeAnd

Fixes #

**Special notes for your reviewer**:

Hello everyone who will read this, this is my first PR, I read everything I could in order to contribute to this project in a good way!
Feel free to tell me if something is wrong with my editing. 👍

2021-02-27 13:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31526) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31526) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31526) it.</sub>

2021-03-09 13:30 UTC, gabor commented
nicely done!

i tried this and it works fine. but, it seems handling "isRegion" is not necessary, simply setting "timeEnd" is makes it work for me.

could you please try to remove the "isRegion" parts, and only have "timeEnd", and verify that it still works for your use-case? thanks.

2021-03-09 13:31 UTC, gabor requested changes
nicely done!

i tried this and it works fine. but, it seems handling `isRegion` is not necessary, simply setting `timeEnd` is enough. could you please try to remove the `isRegion` parts, and only have `timeEnd`, and verify that it still works for your use-case? thanks.

2021-03-09 13:51 UTC, Komalis commented
No problem, I'll try that! I keep you posted

2021-03-14 13:57 UTC, Komalis commented
So yes apprently you don't need the isRegion field, timeEnd is enough, I updated the PR with that done :)
Have a good day :D

2021-03-15 16:25 UTC, gabor approved these changes

2021-03-15 16:26 UTC, gabor commented
looks good! i will merge it soon. ( i will modify the title of the pull-request slightly so that it works better in the changelog)

2021-03-15 16:29 UTC, merged

2021-03-15 17:14 UTC, Komalis commented
Thank you @gabor hope it will be useful!