Docs: Add 7.5 What's New links
grafana/grafana pull request #31711
Opened 2021-03-04 22:58 UTC by oddlittlebird

Added links to updated documentation in What's new in Grafana 7.5.

Minor updates in Postgres and Azure Monitor data source topics to improve title consistency and remove outdated information.

2021-03-05 11:36 UTC, wbrowne requested changes
Since we're removing the alias here, we'll need to update the following to the correct link:

```
"grafana": {
    "whatsNewUrl": "https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-5/",
 ...
```

inside the root `package.json`. And therefore this will need to be backported to the 7.5.x  release branch so that it goes out with the beta2+stable. Looping in @Elfo404 to confirm my thinking here.

2021-03-05 12:44 UTC, Elfo404 commented
@wbrowne I'd say what you say is correct.

important: if we remove the alias we also need to make sure the link in https://grafana.com/grafana/download/7.5.0-beta1 is updated correctly (we can use `gcom` for this)

2021-03-05 13:37 UTC, osg-grafana commented on docs/sources/datasources/postgres.md
> +Grafana ships with a built-in PostgreSQL data source plugin that allows you to query and visualize data from a PostgreSQL compatible database. This topic explains options, variables, querying, and ot
```suggestion
Grafana ships with a built-in PostgreSQL data source plugin that allows you to query and visualize data from a PostgreSQL compatible database. This topic explains options, variables, querying, and other options specific to this data source. For instructions about how to add a data source to Grafana, refer to [Add a data source]({{< relref "add-a-data-source.md" >}}). Only users with the organization admin role can add data sources.
```

2021-03-05 18:02 UTC, oddlittlebird commented
I added the alias back in for now, but could someone please fix the incorrect grafana.com link?

2021-03-08 15:21 UTC, oddlittlebird commented
Could someone please approve this?

2021-03-08 15:22 UTC, achatterjee-grafana approved these changes

2021-04-13 17:43 UTC, oddlittlebird commented
@Elfo404 and @wbrowne, what is the status of this? Are we good to merge?

2021-04-13 18:35 UTC, wbrowne approved these changes
Yep, no alias change so all good @oddlittlebird!

2021-04-13 18:35 UTC, merged