Stacked Graph Rendering: render time series in consistent order
grafana/grafana pull request #31753
Opened 2021-03-07 17:29 UTC by onumossn

**What this PR does / why we need it**:
It sorts the timeseries.

We have multiple data sources in multiple data centers for redundancy. Sometimes this causes the order in which the time series are returned in the JSON to be different. This can be a problem if you are using stacking and refreshing. The order in which they are returned changes how they are stacked, which can be jarring.

2021-03-07 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31753) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31753) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31753) it.</sub>

2021-03-09 07:04 UTC, hugohaggmark commented
Hi @onumossn and thanks for opening this PR. We usually start of with an issue/need before opening a PR. Would be great if you can find or create an issue for this PR. Thank you.

2021-03-09 07:06 UTC, hugohaggmark requested changes
PR needs new tests or update existing as it currently breaks existing tests

2021-03-16 03:34 UTC, onumossn commented
Will try to get to it this weekend. Sorry been busy.

I see old issues, but nothing open. Seems to come back periodically. Might be something that gets missed cause it really seems to be an issue when stacking, and that might be easy to forget.

2022-02-01 19:02 UTC, daniellee commented
Closing this PR as it has been inactive for almost a year but please ask us to re-open it or post a new PR if you see the issue again.

2022-02-01 19:02 UTC, closed without merging