Add timeout option to datasource config
grafana/grafana pull request #31871
Opened 2021-03-10 16:47 UTC by smalukav

Fixes #3168

Add timeout to datasource JsonData, use it in DataSource.GetHttpClient and DataSource.GetHttpTransport

2021-03-10 19:51 UTC, torkelo commented
Think this looks pretty reasonable

2021-03-10 19:54 UTC, achatterjee-grafana requested changes

2021-03-10 20:20 UTC, smalukav commented on packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx
> +                  tooltip="Grafana Proxy deletes forwarded cookies by default. Specify cookies by name that should be forwarded to the data source."
If was like that before but ok :)

2021-03-10 20:22 UTC, achatterjee-grafana approved these changes
LGTM :)

2021-03-11 06:59 UTC, torkelo reviewed
@bergquist should this need anything special considerations from Grafana Cloud? Thinking that uses can override the proxy timeout could cause issues?

2021-03-25 01:39 UTC, giovannirco commented
I would love to see this merged, sometimes the database grows a lot and takes longer to finish, although I understand it starts to play the role of reporting, Grafana actually does an excellent job of showing some useful data from SQL, the only issue is that some queries takes longer and I can't control the timeout.

2021-03-26 15:16 UTC, smalukav commented
@torkelo can it be merged in 7.6 by any chance?

2021-03-26 15:30 UTC, achatterjee-grafana commented
I am not sure there will be a v7.6 version.

2021-03-26 16:08 UTC, smalukav commented
> I am not sure there will be a v7.6 version.

8.0 would also work

2021-04-07 10:13 UTC, aknuds1 approved these changes

2021-04-07 14:46 UTC, merged