Update queries.md
grafana/grafana pull request #31941
Opened 2021-03-12 13:19 UTC by castillo92

Completing some examples to allow newbie people to understand relative time and time shift time

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-03-12 13:57 UTC, achatterjee-grafana approved these changes
Looks good, developers need to chime in on syntax usage.

2021-04-20 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31941) it.</sub>

2021-06-22 13:55 UTC, geshii requested changes
typo

2021-06-22 13:55 UTC, geshii commented on docs/sources/panels/queries.md
> +| Two entire week ago | `2w/w`              |
```suggestion
| Two entire weeks ago | `2w/w`              |
```

2021-06-29 07:20 UTC, castillo92 commented
> [![CLA assistant check](https://camo.githubusercontent.com/777a078050c6b0e4f4af5f36272b0014312f4cafeea86f96c172ea30870fb940/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f7369676e6564)](https://cla-assistant.io/grafana/grafana?pullRequest=31941)
> All committers have signed the CLA.

Signed! I forgot do that

2021-07-08 10:13 UTC, ying-jeanne commented
LGTM @castillo92 you probably need to do a rebase on main to make the CI pass.

2021-07-08 10:14 UTC, ying-jeanne approved these changes

2021-07-10 13:32 UTC, castillo92 commented
> LGTM @castillo92 you probably need to do a rebase on main to make the CI pass.

Could you please explain me how to do that?

2021-07-14 16:22 UTC, merged