#31983 Changed regexp
grafana/grafana pull request #31985
Opened 2021-03-15 10:36 UTC by sbouchex

**What this PR does / why we need it**:

This PR is changing the regexp used by validate the plugin version used by the plugin-validator side-project

Fixes #31983

2021-03-15 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=31985) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=31985) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=31985) it.</sub>

2021-03-15 13:39 UTC, osg-grafana requested changes, later dismissed
Requires a technical review before merging.

2021-08-26 07:27 UTC, marcusolsson approved these changes

2021-08-26 12:55 UTC, achatterjee-grafana approved these changes

2021-08-27 12:38 UTC, closed without merging