Enterprise: Add Redis caching documentation
grafana/grafana pull request #32001
Opened 2021-03-15 16:01 UTC by kminehart

Caching using Redis was recently merged into grafana-enterprise. This documents the available configuration options for Redis.

2021-03-15 16:02 UTC, oddlittlebird commented on docs/sources/enterprise/enterprise-configuration.md
> +The full redis URL of your redis server. Example: `redis://localhost:6739/0`.
```suggestion
The full redis URL of your Redis server. Example: `redis://localhost:6739/0`.
```

2021-03-16 11:19 UTC, osg-grafana requested changes

2021-03-16 11:19 UTC, osg-grafana commented on docs/sources/enterprise/enterprise-configuration.md
> +A string that prefixes all redis keys. This value must be set if using a shared database in Redis. If `prefix` is empty, then one will not be used.
```suggestion
A string that prefixes all Redis keys. This value must be set if using a shared database in Redis. If `prefix` is empty, then one will not be used.
```

2021-03-16 14:17 UTC, osg-grafana approved these changes

2021-03-16 14:35 UTC, merged