Docs: updates developer guide with useful resources for windows setup
grafana/grafana pull request #32075
Opened 2021-03-17 16:27 UTC by thisisobate

**What this PR does / why we need it**:
This PR updates developer guide with useful resources for windows setup.
**Which issue(s) this PR fixes**:

2021-03-17 18:31 UTC, achatterjee-grafana requested changes

2021-03-17 18:31 UTC, achatterjee-grafana commented on contribute/developer-guide.md
> +If you are running Grafana on Windows 10, we recommend installing the Windows Subsystem for Linux (WSL). For installation instructions, refer to our [Grafana Setup Guide for Windows environment](http
```suggestion
If you are running Grafana on Windows 10, we recommend installing the Windows Subsystem for Linux (WSL). For installation instructions, refer to our [Grafana setup guide for Windows environment](https://grafana.com/blog/2021/03/03/how-to-set-up-a-grafana-development-environment-on-a-windows-pc-using-wsl/).
```

2021-03-18 08:29 UTC, osg-grafana approved these changes

2021-03-18 13:39 UTC, achatterjee-grafana approved these changes

2021-03-18 13:39 UTC, merged