Fix bug not update render state when adding or removing tags in dashboard settings from v7.5.x
grafana/grafana pull request #32189
Opened 2021-03-21 12:49 UTC by huynhsamha

**What this PR does / why we need it**:

I've created an issue about a bug from version 7.5.x, that when we add/remove tags in dashboard settings, the UI is not updated. 

In this PR, I've resolved this issue.

**Which issue(s) this PR fixes**: Issue #32188

Fixes #

+ Trigger rendering the new state on tags changes.

**Special notes for your reviewer**:

Demo for the bug:

**Before**

![111903395-ad1b0280-8a74-11eb-9d5b-49f2832dd29b](https://user-images.githubusercontent.com/24195776/111905431-31be4e80-8a7e-11eb-86af-5b28add9d801.gif)

**After**

![Grafana - Demo fix tags v7 5 x](https://user-images.githubusercontent.com/24195776/111905440-3a168980-8a7e-11eb-9ca5-a0924e3114d7.gif)

Please review my changes in this PR.

Many thanks to the Grafana team!

2021-03-22 11:24 UTC, zoltanbedi commented
@jackw can you check this pr please?

2021-03-22 12:01 UTC, jackw approved these changes
LGTM! 🚀

2021-03-22 13:50 UTC, achatterjee-grafana requested changes

2021-03-22 13:50 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +Sets the maximum time using a duration format (5s/5m/5ms) before timing out read of an incoming request and closing idle connections.
```suggestion
Sets the maximum time using the duration format (5s/5m/5ms) before reading of incoming request times out and idle connections close.
```

2021-03-22 13:50 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +Configures the batch size for the annotation clean-up job. This setting is used for dashboard, API, and alert annotations.
```suggestion
Configures the batch size for the annotation cleanup job. This setting is used for dashboard, API, and alert annotations.
```

2021-03-22 13:50 UTC, achatterjee-grafana commented on docs/sources/datasources/cloudwatch.md
> +In the [Grafana configuration](https://grafana.com/docs/grafana/latest/administration/configuration/#aws) there's an `AWS` section that allows you to customize the data source.
```suggestion
In the [Grafana configuration](https://grafana.com/docs/grafana/latest/administration/configuration/#aws) file, the `AWS` section allows you to customize the data source.
```

2021-03-22 13:50 UTC, achatterjee-grafana commented on docs/sources/whatsnew/whats-new-in-v7-5.md
> +Sets the maximum time using a duration format (5s/5m/5ms) before timing out read of an incoming request and closing idle connections.
```suggestion
Sets the maximum time using the duration format (5s/5m/5ms) before reading of incoming request times out and idle connections close.
```

2021-03-22 13:50 UTC, achatterjee-grafana commented
Added some copy-edit suggestions.

2021-03-22 20:37 UTC, torkelo commented
This needs a rebase ontop of master

2021-03-22 20:38 UTC, torkelo commented
Bug fixes go into master, then get's backported to release branches

2021-03-23 06:45 UTC, closed without merging

2021-03-23 06:45 UTC, torkelo commented
Can you open a PR based on master?

2021-03-23 07:49 UTC, huynhsamha commented
Hi @torkelo, I've created a new PR based on master #32241.