Doc: Document the X-Grafana-Org-Id HTTP header
grafana/grafana pull request #32478
Opened 2021-03-30 09:28 UTC by ying-jeanne

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #26769

**Special notes for your reviewer**:

2021-03-30 09:28 UTC, ying-jeanne commented
the functionality tested
![Uploading image.png…]()

2021-03-30 13:36 UTC, achatterjee-grafana requested changes
Thanks for adding this information! One minor change requested.

2021-03-30 13:36 UTC, achatterjee-grafana commented on docs/sources/http_api/auth.md
> +- **X-Grafana-Org-Id** - The org to which the created key belongs. It is optional. If it is not set, the created key would belongs to the current context org.
```suggestion
- **X-Grafana-Org-Id** - An optional property that specifies the org to which the created key belongs. If it is not set, the created key belongs to the current context org.
```

2021-04-09 11:18 UTC, ying-jeanne commented
https://grafana.com/docs/grafana/latest/http_api/auth/ in this page, add a separate subsection as Token.

2021-04-12 08:10 UTC, marefr approved these changes
LGTM, but added a suggestion. Lets see if @achatterjee-grafana agrees

2021-04-12 08:10 UTC, marefr commented on docs/sources/http_api/auth.md
> +## Header
```suggestion
## X-Grafana-Org-Id Header
```

2021-04-12 14:14 UTC, achatterjee-grafana requested changes
Cleaned up the doc content.

2021-04-12 14:14 UTC, achatterjee-grafana commented on docs/sources/http_api/auth.md
> +**X-Grafana-Org-Id** is an optional property that specifies the org to which the action is applied on. If it is not set, the created key belongs to the current context org. You could use this header
```suggestion
**X-Grafana-Org-Id**  is an optional property that specifies the organization to which the action is applied. If it is not set, the created key belongs to the current context org. Use this header in all requests except those regarding admin.
```

2021-04-20 17:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=32478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=32478) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=32478) it.</sub>

2021-04-21 15:58 UTC, achatterjee-grafana approved these changes
LGTM!

2021-04-21 16:24 UTC, merged

2021-04-21 16:28 UTC, marefr commented
@achatterjee-grafana @ying-jeanne I suppose we should backport this to v7.5.x if we want these docs to show up under the latest tag?

2021-04-21 17:11 UTC, achatterjee-grafana commented
Will do.

2021-04-21 20:04 UTC, achatterjee-grafana commented
> @achatterjee-grafana @ying-jeanne I suppose we should backport this to v7.5.x if we want these docs to show up under the latest tag?

Done!

2021-04-22 08:05 UTC, marefr commented
@achatterjee-grafana looks like you manually backported this? You could just have added the label "backport v7.5.x" and grafanabot would have opened the backport pr for you.

2021-04-22 16:13 UTC, achatterjee-grafana commented
We spoke about the backport after the merge. The doc team is using that label in other PRs.