[Alerting]: Update scheduler to evaluate rules created by the unified API
grafana/grafana pull request #32589
Opened 2021-04-01 09:49 UTC by papagian

Rules are fetched, evaluated and results are handled by the state tracker

```
DBUG[04-01|12:31:36] alert rules fetched                      logger=ngalert count=2
DBUG[04-01|12:31:36] alert rule routine started               logger=ngalert key="{orgID: 1, UID: F01iqH_Mzz}"
DBUG[04-01|12:31:36] alert rule routine started               logger=ngalert key="{orgID: 1, UID: K0JmqNlGz}"
DBUG[04-01|12:31:36] new alert rule version fetched           logger=ngalert title="prom query with SSE" key="{orgID: 1, UID: K0JmqNlGz}" version=1
{"@level":"debug","@message":"expression datasource query (seriesSet)","@timestamp":"2021-04-01T12:31:36.211955+03:00","query":"query"}
INFO[04-01|12:31:36] alert rule result                        logger=ngalert title="prom query with SSE" key="{orgID: 1, UID: K0JmqNlGz}" attempt=0 now=2021-04-01T12:31:36+0300 duration=5.000781ms instance= state=Normal
INFO[04-01|12:31:36] state tracker processing evaluation results logger=ngalert uid=K0JmqNlGz resultCount=1
DBUG[04-01|12:31:36] adding new alert state cache entry       logger=ngalert cacheId="K0JmqNlGz " state=Normal evaluatedAt="2021-04-01 12:31:36.205216 +0300 EEST m=+12.812646671"
DBUG[04-01|12:31:36] setting alert state                      logger=ngalert uid=K0JmqNlGz
DBUG[04-01|12:31:36] no state transition                      logger=ngalert cacheId="K0JmqNlGz " state=Normal
DBUG[04-01|12:31:36] returning changed states to scheduler    logger=ngalert count=0
DBUG[04-01|12:31:37] Scheduling update                        logger=alerting.scheduler ruleCount=5
DBUG[04-01|12:31:41] new alert rule version fetched           logger=ngalert title="reduced testdata query" key="{orgID: 1, UID: F01iqH_Mzz}" version=1
{"@level":"debug","@message":"expression datasource query (seriesSet)","@timestamp":"2021-04-01T12:31:41.208267+03:00","query":"A"}
INFO[04-01|12:31:41] alert rule result                        logger=ngalert title="reduced testdata query" key="{orgID: 1, UID: F01iqH_Mzz}" attempt=0 now=2021-04-01T12:31:36+0300 duration=1.219014ms instance= state=Alerting
INFO[04-01|12:31:41] state tracker processing evaluation results logger=ngalert uid=F01iqH_Mzz resultCount=1
DBUG[04-01|12:31:41] adding new alert state cache entry       logger=ngalert cacheId="F01iqH_Mzz " state=Alerting evaluatedAt="2021-04-01 12:31:36.205216 +0300 EEST m=+12.812646671"
DBUG[04-01|12:31:41] setting alert state                      logger=ngalert uid=F01iqH_Mzz
DBUG[04-01|12:31:41] no state transition                      logger=ngalert cacheId="F01iqH_Mzz " state=Alerting
DBUG[04-01|12:31:41] returning changed states to scheduler    logger=ngalert count=0
```

2021-04-01 11:03 UTC, gotjosh approved these changes

2021-04-01 11:32 UTC, papagian commented on pkg/services/ngalert/schedule/fetcher.go
>  		sch.log.Error("failed to fetch alert definitions", "now", now, "err", err)
`now` is actually the scheduler tick that can differ from the logging time (and I had it there for debugging).
https://github.com/grafana/grafana/blob/01c46fcac024b9b8d0d08f3e1ee36e8f43c11ca8/pkg/services/ngalert/schedule/schedule.go#L247
But I agree that there is not point including it in the error log.

2021-04-01 11:39 UTC, papagian commented
Now that we have introduce [AlertRule.ExecErrState](https://github.com/grafana/grafana/blob/b714cdf395d1c89eaff81b2eb4ee39298bb8dfec/pkg/services/ngalert/models/alert_rule.go#L54) I have to change this and save the error state instead of returning
https://github.com/grafana/grafana/blob/01c46fcac024b9b8d0d08f3e1ee36e8f43c11ca8/pkg/services/ngalert/schedule/schedule.go#L73-L79

2021-04-01 12:00 UTC, kylebrandt commented
Running things :-) 

I am current getting:

```
=ngalert title="prom query with SSE classic condition" key="{orgID: 1, UID: X73TOSlMz}" attempt=0 now=2021-04-01T07:55:56-0400 duration=6.019991ms instance= state=NoData
EROR[04-01|07:55:56] failed saving alert instance             logger=ngalert title="prom query with SSE classic condition" key="{orgID: 1, UID: X73TOSlMz}" attempt=0 now=2021-04-01T07:55:56-0400 instance= state=NoData error="alert instance is invalid because the state 'NoData' is invalid"
```

The Data in alert rule is:

```
[
  {
    "refId": "A",
    "queryType": "",
    "relativeTimeRange": {
      "from": 300,
      "to": 0
    },
    "model": {
      "datasource": "gdev-prometheus",
      "datasourceUid": "000000002",
      "expr": "avg (node_network_transmit_bytes_total) by (instance,device)",
      "hide": false,
      "interval": "",
      "intervalMs": 1000,
      "legendFormat": "",
      "maxDataPoints": 100,
      "refId": "A"
    }
  },
  {
    "refId": "B",
    "queryType": "",
    "relativeTimeRange": {
      "from": 0,
      "to": 0
    },
    "model": {
      "conditions": [
        {
          "evaluator": {
            "params": [
              0
            ],
            "type": "gt"
          },
          "operator": {
            "type": "and"
          },
          "query": {
            "params": [
              "A"
            ]
          },
          "reducer": {
            "params": [],
            "type": "avg"
          },
          "type": "query"
        }
      ],
      "datasource": "__expr__",
      "datasourceUid": "-100",
      "hide": false,
      "intervalMs": 1000,
      "maxDataPoints": 100,
      "refId": "B",
      "type": "classic_conditions"
    }
  }
]
```

2021-04-01 12:06 UTC, papagian commented
> Running things :-)
> 
> I am current getting `state=NoData error="alert instance is invalid because the state 'NoData' is invalid"`:

Good catch; that's happens because [InstanceStateType](https://github.com/grafana/grafana/blob/4ce0a49eac03e8f37914a84c8bfaeac573582e93/pkg/services/ngalert/models/instance.go) is missing some states. It needs to sync with eval.State
https://github.com/grafana/grafana/blob/b1cb74c0c9450449ad13dc0405cfca87ad55b6e7/pkg/services/ngalert/eval/eval.go#L68-L86
I'm fixing it

2021-04-01 14:16 UTC, kylebrandt approved these changes

2021-04-01 16:19 UTC, gotjosh requested changes
I'm going to briefly block this work as there's more we need to do here.

2021-04-03 11:42 UTC, gotjosh approved these changes

2021-04-03 17:13 UTC, merged