API: add parameters perpage and page for api api/org/users
grafana/grafana pull request #32672
Opened 2021-04-04 15:04 UTC by ying-jeanne

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #32540

**Special notes for your reviewer**:

2021-04-04 15:19 UTC, ying-jeanne commented
test result
![tempsnip](https://user-images.githubusercontent.com/74549700/113513411-e7eb6300-9569-11eb-9f38-78386f4f2ffa.png)

2021-04-04 15:50 UTC, ying-jeanne commented
**Note: To make it backward compatible, now we still do response.JSON(200, result.Users) to make the response not changed. When frontend change is made, we need to change response.JSON(200, result.Users) to response.JSON(200, result) instead.**

2021-04-06 15:47 UTC, aknuds1 requested changes
Generally looks good AFAICT, but it looks as if some things are made more complicated than they need to be.

2021-04-06 15:47 UTC, aknuds1 commented on pkg/api/org_users.go
> +func (hs *HTTPServer) GetUsers(c *models.ReqContext) (models.SearchOrgUserQueryResult, error) {
Nit, but I think it's better to simplify the return signature of the method to return the type required by the clients ([]*models.OrgUserDTO). It reduces complexity and the potential for mistakes.
```suggestion
func (hs *HTTPServer) GetUsers(c *models.ReqContext) ([]*models.OrgUserDTO, error) {
```

2021-04-06 15:47 UTC, aknuds1 commented on pkg/api/org_users.go
> +	return query.Result, err
Nothing is used from `query.Result` but the `Users` field, so best just return that.

```suggestion
	return hs.getOrgUsersHelper(query, c.SignedInUser)
```

2021-04-06 15:47 UTC, aknuds1 commented on pkg/models/org_user.go
> +	Result SearchOrgUserQueryResult
Can we remove the new result type? As you can see from my comments above, you only need to return the users.

2021-04-06 15:47 UTC, aknuds1 commented on pkg/services/sqlstore/org_test.go
> +			setting.AutoAssignOrgRole = "Viewer"
You need to clean up after changing global variables, to not bleed into other tests:
```suggestion
			origAutoAssignOrg = setting.AutoAssignOrg
			origAutoAssignOrgId := setting.AutoAssignOrgId
			origAutoAssignOrgRole := setting.AutoAssignOrgRole
			t.Cleanup(func() {
				setting.AutoAssignOrg = origAutoAssignOrg
				setting.AutoAssignOrgId = origAutoAssignOrgId
				setting.AutoAssignOrgRole = origAutoAssignOrgRole
			})
			setting.AutoAssignOrg = true
			setting.AutoAssignOrgId = 1
			setting.AutoAssignOrgRole = "Viewer"
```

2021-04-07 13:43 UTC, marefr commented
@ying-jeanne 

> To make it backward compatible, now we still do response.JSON(200, result.Users) to make the response not changed. When frontend change is made, we need to change response.JSON(200, result.Users) to response.JSON(200, result) instead.

That's why I suggested to create a new endpoint in the issue and I still believe we should do that now:
> For /api/users a new endpoint was added to not introduce a breaking change, see https://grafana.com/docs/grafana/latest/http_api/user/#search-users-with-paging. Suggest adding a new search with paging endpoint for org users as well.

2021-04-20 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=32672) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=32672) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=32672) it.</sub>

2021-05-05 12:46 UTC, closed without merging