Adding a sentence to the index to point people towards the "activate …
grafana/grafana pull request #32730
Opened 2021-04-06 20:02 UTC by 09jvilla

…license" page if they want to complete installation of their Grafana Enterprise installation. Also made a minor change to the two sentences before to make them more consistent.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-04-07 07:38 UTC, osg-grafana requested changes

2021-04-07 07:38 UTC, osg-grafana commented on docs/sources/installation/_index.md
> +Refer to [Upgrade Grafana]({{< relref "upgrading.md" >}}) for how to upgrade Grafana.
```suggestion
To upgrade Grafana, refer to [Upgrade Grafana]({{< relref "upgrading.md" >}}).
```

2021-04-07 07:38 UTC, osg-grafana commented on docs/sources/installation/_index.md
> +Refer to [Restart Grafana]({{< relref "Restart-grafana.md" >}}) for how to restart Grafana.
```suggestion
To restart Grafana, refer to [Restart Grafana]({{< relref "Restart-grafana.md" >}}).
```

2021-04-09 08:18 UTC, osg-grafana approved these changes
Approving copy changes.

2021-04-09 14:15 UTC, achatterjee-grafana approved these changes
Added more minor copy-edit suggestion. Otherwise LGTM

2021-04-09 14:15 UTC, achatterjee-grafana commented on docs/sources/installation/_index.md
> +To upgrade Grafana, refer to [Upgrade Grafana]({{< relref "upgrading.md" >}}).
```suggestion
For upgrade instructions, refer to [Upgrade Grafana]({{< relref "upgrading.md" >}}).
```

2021-04-09 14:16 UTC, achatterjee-grafana reviewed
Fixed an incorrect relref.

2021-04-09 14:16 UTC, achatterjee-grafana commented on docs/sources/installation/_index.md
> +To restart Grafana, refer to [Restart Grafana]({{< relref "Restart-grafana.md" >}}).
```suggestion
To restart Grafana, refer to [Restart Grafana]({{< relref "restart-grafana.md" >}}).
```

2021-04-09 15:21 UTC, merged