WIP: Search jaeger traces
grafana/grafana pull request #32805
Opened 2021-04-08 17:28 UTC by zoltanbedi

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #24953
Fixes #27245

2021-04-20 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=32805) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=32805) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=32805) it.</sub>

2021-04-29 19:17 UTC, achatterjee-grafana reviewed
Added some review comments.

2021-04-29 19:32 UTC, achatterjee-grafana reviewed
Another suggestion.

2021-04-29 19:32 UTC, achatterjee-grafana commented on docs/sources/datasources/jaeger.md
> +You can set up the data source via configuration files with Grafana's provisioning system. Refer to [provisioning docs page]({{< relref "../administration/provisioning/#datasources" >}}) for informat
```suggestion
You can set up the data source via configuration files with Grafana's provisioning system. Refer to [provisioning docs page]({{< relref "../administration/provisioning/#datasources" >}}) for more information on configuring various settings.
```

2021-04-29 19:55 UTC, achatterjee-grafana requested changes
Added copy edit changes.

2021-04-29 19:55 UTC, achatterjee-grafana commented on docs/sources/datasources/jaeger.md
> +1. Min Duration - Setting this field should filter traces that has higher duration than the value. Possible values are `1.2s, 100ms, 500us`.
```suggestion
1. Min Duration - Filter all traces with a duration higher than the set value. Possible values are `1.2s, 100ms, 500us`.
```

2021-04-29 19:55 UTC, achatterjee-grafana commented on docs/sources/datasources/jaeger.md
> +1. Max Duration - Setting this field should filter traces that duration are not higher than the value. Possible values are `1.2s, 100ms, 500us`.
```suggestion
1. Max Duration - Filter all traces with a duration lower than the set value. Possible values are `1.2s, 100ms, 500us`.
```

2021-04-30 13:27 UTC, achatterjee-grafana approved these changes
LGTM

2021-05-04 13:29 UTC, aocenas commented
Code looks good but there are some behavior that I think we should try to fix:
1. The limit placeholder is not seen in full so it's not clear what it means, we should probably put longer description in some info tooltip.
![Screenshot from 2021-05-04 15-21-29](https://user-images.githubusercontent.com/1014802/117010017-aaa2fe00-acec-11eb-9714-039adf37d025.png)

2. When querying logs the order is not stable and I get random traces every time. This isn't happening in jaeger ui so I assume there is either some param in the API or they sort the traces by time after they get them.
3. There seems to be some weird behavior with min/max limits but some of that is also present in Jaeger. In Jaeger if I use both min + max it seems like max is ignored. In this PR it seems like max limit is always ignored.

2021-05-04 17:09 UTC, zoltanbedi commented
> Code looks good but there are some behavior that I think we should try to fix:
> 
> 1. The limit placeholder is not seen in full so it's not clear what it means, we should probably put longer description in some info tooltip.
> 2. When querying logs the order is not stable and I get random traces every time. This isn't happening in jaeger ui so I assume there is either some param in the API or they sort the traces by time after they get them.
> 3. There seems to be some weird behavior with min/max limits but some of that is also present in Jaeger. In Jaeger if I use both min + max it seems like max is ignored. In this PR it seems like max limit is always ignored.

1. Added the placeholder text to the info tooltip instead.
2. It seems like that they sort by most recent traces so I changed it to do the same. Don't we have a field config related to sorting?
3. I couldn't reproduce this. I see the same behaviour as in the Jaeger UI.

2021-05-05 13:13 UTC, aocenas commented
> I couldn't reproduce this. I see the same behaviour as in the Jaeger UI.

hmm yes you are right, but still this seems super weird, I mean this seems like a bug in the Jaeger API but I think this will create some issues for us as people will assume it's a bug in Grafana. @hemdrup @davkal what do you think about this? From perspective of Grafana user this seems broken. Should we allow only one of mix/max at the time? Or some disclaimer?

Another small nitpick:
Would probably change the placeholder to something like `foo, bar, baz` (or some more real tags) to give an example of the syntax (delimiter) as that is more helpful there imho.
![Screenshot from 2021-05-05 15-06-40](https://user-images.githubusercontent.com/1014802/117146124-2ae06680-adb4-11eb-991d-045afe00e411.png)

2021-05-06 12:30 UTC, hemdrup commented
> Should we allow only one of mix/max at the time? Or some disclaimer?


- @aocenas Great idea on the "tag" example
- @aocenas Not sure what you mean by "only one min/mac" Do you mean multiple allowing filters like? Show me logs between 2-3s + logs between 4-5s?

2021-05-11 08:26 UTC, aocenas approved these changes
We can check the min/max issue in later PR

2021-05-11 08:38 UTC, merged