[Alerting]: Use title instead of slug for retrieving the namespace
grafana/grafana pull request #32957
Opened 2021-04-13 16:33 UTC by papagian

**What this PR does / why we need it**:
[POST /api/ruler/{Recipient}/api/v1/rules/{Namespace} ](https://grafana.github.io/alerting-api/#/ruler/RoutePostNameRulesConfig)
used to fail if the namespace contained special characters.
The reason was that we tried to retrieve the namespace from the database using the slug instead of the title.
[That was also problematic](https://github.com/grafana/grafana/pull/32747#discussion_r609530930) because there's a chance multiple namespaces with special characters would result in the same slug.
This fix queries using the folder title which [is unique](https://github.com/grafana/grafana/blob/b0c6cad637022c22a376cc3a3b1bb35a7f0a6064/pkg/services/sqlstore/migrations/dashboard_mig.go#L175) per organisation

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-04-13 21:04 UTC, davidmparrott approved these changes
LGTM 🎉

2021-04-14 05:18 UTC, domasx2 approved these changes

2021-04-14 05:33 UTC, aknuds1 requested changes
Looks good, but there are some documentation "bugs".

2021-04-14 05:33 UTC, aknuds1 commented on pkg/dashboards/ifaces.go
> +	// GetFolderByTitle retrieves a dashboard by its title and it's used by unified alerting
Nit, but I think the following reads better:
```suggestion
	// GetFolderByTitle retrieves a dashboard by its title and is used by unified alerting
```

2021-04-14 05:33 UTC, aknuds1 commented on pkg/services/sqlstore/dashboard.go
> +	// there is a unique constrain on org_id, folder_id, title
```suggestion
	// there is a unique constraint on org_id, folder_id, title
```

2021-04-14 05:33 UTC, aknuds1 commented on pkg/services/ngalert/store/alert_rule.go
>  // GetNamespaceUIDBySlug is a handler for retrieving namespace UID by its name.
This needs to be updated.
```suggestion
// GetNamespaceUIDByTitle is a handler for retrieving a namespace UID by its title.
```

2021-04-14 05:33 UTC, aknuds1 commented on pkg/services/sqlstore/dashboard.go
> +// GetDashboardByTile gets a dashboard by its title.
```suggestion
// GetDashboardByTitle gets a dashboard by its title.
```

2021-04-14 06:42 UTC, aknuds1 approved these changes

2021-04-14 09:02 UTC, merged