Elasticsearch:  Add documentation for supported Elasticsearch query transformations
grafana/grafana pull request #33072
Opened 2021-04-16 12:41 UTC by Elfo404

**What this PR does / why we need it**:

Adds a small paragraph describing  the query transformation feature in Explore

**Which issue(s) this PR fixes**:

Fixes #31323

**Special notes for your reviewer**:

2021-04-16 16:34 UTC, ivanahuckova reviewed
I would  remove note `> Only available in Grafana v6.3+.` as it is long time ago. Not sure if we want to have `(BETA)` in the heading. It was in beta 2 years ago, but I don't think it is now. So I would remove that as well.  Other than that 🤩.

2021-04-16 18:24 UTC, oddlittlebird commented
Yes, backport if it is applicably to Grafana 7.5.x.

2021-04-16 18:52 UTC, achatterjee-grafana approved these changes
Added copy edit change.

2021-04-16 18:52 UTC, achatterjee-grafana commented on docs/sources/datasources/elasticsearch.md
> +When switching from a Prometheus or Loki datasource in Explore your query will be automatically translated to an Elasticsearch log query with a correct Lucene filter.
```suggestion
When switching from a Prometheus or Loki data source in Explore, your query is automatically translated to an Elasticsearch log query with a correct Lucene filter.
```

2021-04-16 18:53 UTC, achatterjee-grafana requested changes
Approved by mistake.

2021-04-16 18:53 UTC, achatterjee-grafana commented
> I would remove note `> Only available in Grafana v6.3+.` as it is long time ago. Not sure if we want to have `(BETA)` in the heading. It was in beta 2 years ago, but I don't think it is now. So I would remove that as well. Other than that 🤩.

Agree, all we care about are v7.x and above at this point.

2021-04-18 16:09 UTC, achatterjee-grafana approved these changes
LGTM

2021-04-18 16:10 UTC, Elfo404 commented
will remove the beta notice and merge :)

2021-04-19 14:18 UTC, merged