update links in README.md
grafana/grafana pull request #33195
Opened 2021-04-20 22:38 UTC by DanCech

README.md includes links to some files which aren't included in the download packages, this PR switches those out for links to github to enhance discoverability.

We may also want to consider including some of these files in the download packages.

I also updated the slack link to https://slack.grafana.com

2021-04-20 22:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=33195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=33195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=33195) it.</sub>

2021-04-21 04:10 UTC, torkelo approved these changes

2021-04-21 07:49 UTC, RichiH requested changes, later dismissed

2021-04-21 07:49 UTC, RichiH commented on README.md
> +- Start by reading the [Contributing guide](https://github.com/grafana/grafana/blob/master/CONTRIBUTING.md).
```suggestion
- Start by reading the [Contributing guide](https://github.com/grafana/grafana/blob/HEAD/CONTRIBUTING.md).
```

Else, we break our links when we move master to main

2021-04-21 07:49 UTC, RichiH commented on README.md
> +- Learn how to set up your local environment, in our [Developer guide](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md).
```suggestion
- Learn how to set up your local environment, in our [Developer guide](https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md).
```

2021-04-21 07:49 UTC, RichiH commented on README.md
> +Grafana is distributed under [AGPL-3.0-only](LICENSE). For Apache-2.0 exceptions, see [LICENSING.md](https://github.com/grafana/grafana/blob/master/LICENSING.md).
```suggestion
Grafana is distributed under [AGPL-3.0-only](LICENSE). For Apache-2.0 exceptions, see [LICENSING.md](https://github.com/grafana/grafana/blob/HEAD/LICENSING.md).
```

2021-09-21 12:26 UTC, torkelo commented
synced this with main, thing we can merge this

2021-09-21 14:21 UTC, merged