[Alerting]: Extend quota service to optionally set limits on alerts
grafana/grafana pull request #33283
Opened 2021-04-22 16:53 UTC by papagian

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I have modified the testinfra for making authenticated requests.

2021-04-22 19:07 UTC, oddlittlebird commented
This needs a milestone.

2021-04-22 19:08 UTC, oddlittlebird reviewed
A few minor doc suggestions

2021-04-22 19:08 UTC, oddlittlebird commented on docs/sources/administration/configuration.md
> +Limit the number of alert rulles that can be entered per organization. Default is 10.
```suggestion
Limit the number of alert rules that can be entered per organization. Default is 10.
```

2021-04-22 19:11 UTC, achatterjee-grafana requested changes
Commented on a possible typo.

2021-04-22 19:11 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +### org_alert_rulle
org_alert_rule?

2021-04-22 19:13 UTC, achatterjee-grafana commented
Is this change for V8.0 and part of the new alerting feature?

2021-04-22 19:17 UTC, papagian commented
> Is this change for V8.0 and part of the new alerting feature?

yes, I've added the milestone

2021-04-22 19:44 UTC, achatterjee-grafana approved these changes

2021-04-23 13:34 UTC, papagian commented
I have fixed the issues; it's now ready for review

2021-04-23 16:57 UTC, kylebrandt approved these changes
LGTM

2021-04-26 10:27 UTC, wbrowne commented on pkg/services/sqlstore/quota.go
> +		if q.Target != "alert_rule" || query.IsNgAlertEnabled {
Looks like you're missing the use of the `ALERT_RULE_TARGET` const here and also line 199 😄

2021-04-26 10:30 UTC, wbrowne commented on pkg/middleware/quota_test.go
> +			// this schenario can only happen if the feature was enabled and later disabled
```suggestion
			// this scenario can only happen if the feature was enabled and later disabled
```

2021-04-26 10:36 UTC, wbrowne commented on pkg/services/quota/quota.go
> +	case "alert_rule": // target need to much the respective database name
Is this comment necessary to keep? I guess it should say "match" in case it should stay

2021-04-26 10:39 UTC, wbrowne commented on pkg/services/sqlstore/quota_test.go
> +			Convey("Should be able to get used zero used org alert quota when table does not exist (ngalert is not enabled - default case)", func() {
```suggestion
			Convey("Should be able to get zero used org alert quota when table does not exist (ngalert is not enabled - default case)", func() {
```

2021-04-29 09:36 UTC, wbrowne approved these changes
Looks good AFAICT!

The only thing I wonder is what the impact is on build time due to more individual integration tests (a general problem) - I haven't done any profiling really, but am curious if in some cases we'd be better to reduce re-creating the database and server. Just some food for thought for now!

2021-05-04 07:53 UTC, papagian commented
> Looks good AFAICT!
> 
> The only thing I wonder is what the impact is on build time due to more individual integration tests (a general problem) - I haven't done any profiling really, but am curious if in some cases we'd be better to reduce re-creating the database and server. Just some food for thought for now!

good point! The integration tests were indeed slow because of re-creation of the database but [we have changed it](https://github.com/grafana/grafana/pull/28265) and we just truncate the tables instead following [this](https://github.com/grafana/grafana/pull/26858#issuecomment-692661118) suggestion.

2021-05-04 16:16 UTC, merged