Collapseupdates component to use the new theme model
grafana/grafana pull request #33326
Opened 2021-04-23 14:19 UTC by thisisobate

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-04-23 16:03 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +      background: ${theme.v1.palette.blue85};
theme.palette.primary.main

2021-04-23 16:03 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +    padding: ${theme.v1.panelPadding}px;
theme.spacing(theme.components.panel.padding)

2021-04-23 16:04 UTC, torkelo requested changes
looks good, just some minor things

2021-04-27 08:55 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +    padding: ${theme.spacing(theme.components.panel.padding)}px;
```suggestion
    padding: ${theme.spacing(theme.components.panel.padding)};
```

2021-04-27 08:55 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +    margin: ${theme.spacing(4)};
```suggestion
    margin: ${theme.spacing(0.5)};
```

2021-04-27 08:55 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +    margin-top: ${theme.spacing(5)};
```suggestion
    margin-top: ${theme.spacing(0.25)};
```

2021-04-27 08:56 UTC, torkelo commented on packages/grafana-ui/src/components/Collapse/Collapse.tsx
> +    line-height: ${theme.typography.size.md};
```suggestion
    line-height: ${theme.typography.h6.lineHeight};
```

2021-04-27 08:57 UTC, torkelo requested changes
found some mistakes

2021-04-28 07:30 UTC, dprokop approved these changes

2021-04-28 08:05 UTC, dprokop approved these changes

2021-04-28 08:06 UTC, torkelo approved these changes

2021-04-28 08:07 UTC, merged