Alerting: Add optional Discord configuration for avatar url
grafana/grafana pull request #33355
Opened 2021-04-25 01:01 UTC by ChipWolf

**What this PR does / why we need it**: Similar to the Slack alert options, this exposes an avatar URL field for Discord alerts.

2021-04-25 01:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=33355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=33355) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=33355) it.</sub>

2021-04-25 01:03 UTC, ChipWolf commented
I failed to add a test, will add one.

2021-04-26 10:25 UTC, ChipWolf commented
@marefr let me know if you'd prefer any other optional config to be exposed in this PR, happy to expand the scope if required.

Counterintuitively, I was also considering a proposal to remove the majority of the Discord alerting logic in favor of Slack, given [you may append](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook) `/slack` to a Discord webhook. What are your thoughts?

2021-05-20 10:06 UTC, marefr commented
@ChipWolf thanks. We should be able to accept this. Just have to check a few things internally before coming back to reviewing this one. Until then there's some missing documentation for the Discord notifier if you're interested:
- https://github.com/grafana/grafana/blob/main/docs/sources/alerting/notifications.md
- #34000

2021-05-20 10:08 UTC, marefr commented
@ChipWolf we're currently in a migration phase why there are two instances of the discord notifier. May I ask you to sync with main branch and implement your changes in this file as well? https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/notifier/channels/discord.go

Mentioned documentation would be a really good thing to have.

2021-05-20 10:09 UTC, marefr requested changes
See earlier comments

2021-05-20 19:46 UTC, ChipWolf commented
Will do @marefr
Also see https://github.com/grafana/grafana/issues/33377

2021-05-20 21:44 UTC, achatterjee-grafana requested changes
Added some copy edit suggestions.

2021-05-20 21:44 UTC, achatterjee-grafana commented on docs/sources/alerting/notifications.md
> +
```suggestion
To set up Discord, you must create a Discord channel webhook. For instructions on how to create the channel, refer to 
[Intro to Webhooks](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) f.

```

2021-05-20 21:44 UTC, achatterjee-grafana commented on docs/sources/alerting/notifications.md
> +Avatar URL | Optionally provide a URL to an image to use as the avatar for the bot's message.
```suggestion
Avatar URL | Optionally, provide a URL to an image to use as the avatar for the bot's message.
```

2021-05-20 21:44 UTC, achatterjee-grafana commented on docs/sources/alerting/notifications.md
> +Alternatively, you may use the [Slack](#slack) notifier by appending `/slack` to a Discord webhook URL.
```suggestion
Alternately, use the [Slack](#slack) notifier by appending `/slack` to a Discord webhook URL.
```

2021-05-20 22:10 UTC, ChipWolf commented
Thanks for reminding me my English scholarship from my childhood aged like milk @achatterjee-grafana 😄

2021-05-20 22:14 UTC, achatterjee-grafana commented
> Thanks for reminding me my English scholarship from my childhood aged like milk @achatterjee-grafana 😄

You were concentrating on the technical details, no worries :)

2021-05-20 22:15 UTC, achatterjee-grafana commented
This PR needs a milestone.

2021-05-20 22:15 UTC, achatterjee-grafana approved these changes
LGTM

2021-05-25 09:14 UTC, codesome commented on pkg/services/ngalert/notifier/channels/discord.go
> +	avatarURL := model.Settings.Get("avatar_url").MustString()
For the ngalert, you will need to add this option [here](https://github.com/grafana/grafana/blob/91657dad182127bf577b449ff9d94e5bf86e592a/pkg/services/ngalert/notifier/available_channels.go#L669-L692
) and updated [this test](https://github.com/grafana/grafana/blob/91657dad182127bf577b449ff9d94e5bf86e592a/pkg/tests/api/alerting/api_available_channel_test.go) accordingly.

2021-05-25 21:28 UTC, ChipWolf commented
@codesome thanks, let me know if there's anything else

2021-05-25 21:44 UTC, marefr approved these changes
LGTM

2021-05-28 05:38 UTC, codesome approved these changes

2021-05-28 21:00 UTC, merged

2021-05-28 21:02 UTC, marefr commented
Thank you for contributing to Grafana!

Suggested for this to be backported to v8.0.x branch so that it will be included in v8.0. In normal cases I would have waited with this until 8.1, but given there's a lot of changes happening around alerting for v8.0 I thought v8.0.x is more appropriate.