Document customQueryParameters for prometheus datasource provisioning
grafana/grafana pull request #33440
Opened 2021-04-27 17:06 UTC by aecay

**What this PR does / why we need it**:

Document customQueryParameters for prometheus datasource provisioning

The customQueryParameters option was added to prometheus datasources in https://github.com/grafana/grafana/pull/19121.  This PR updates the "provisioning" documentation to contain a reference to this in the `jsonData` options for a prometheus datasource.

**Which issue(s) this PR fixes**:

none afaik -- just corrects a gap in the docs

2021-04-27 17:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=33440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=33440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=33440) it.</sub>

2021-04-27 17:20 UTC, achatterjee-grafana commented
Need developer review.

2021-04-27 17:21 UTC, achatterjee-grafana approved these changes

2021-04-27 17:22 UTC, achatterjee-grafana requested changes
Change url to URL

2021-04-27 17:22 UTC, achatterjee-grafana commented on docs/sources/administration/provisioning.md
> +| customQueryParameters   | string  | Prometheus                                                       | Query parameters to add, as a url-encoded string.
```suggestion
| customQueryParameters   | string  | Prometheus                                                       | Query parameters to add, as a URL-encoded string.                                                 |
```

2021-04-27 17:37 UTC, achatterjee-grafana commented
@aecay, you need to sign the CLA agreement. Thanks!

2021-04-28 15:27 UTC, ivanahuckova approved these changes
Looks good! Thanks for adding this @aecay!🙏 @achatterjee-grafana if you have no more comments and all looks good, I think that we can merge it. :)

2021-04-28 15:29 UTC, achatterjee-grafana approved these changes
LGTM

2021-04-28 15:30 UTC, ivanahuckova commented
There seems to be a problem with failing CI. I have restarted the CI, which might fix it.  But if not @aecay maybe you'll need to merge master.

2021-04-28 16:58 UTC, merged