Docs: Add information about Graphite/Loki integration
grafana/grafana pull request #33916
Opened 2021-05-11 11:01 UTC by ifrost

**What this PR does / why we need it**:

A follow-up to #33405. There is plenty of docs in the help section in settings so this is just to mentioned the feature in the main docs.

**Which issue(s) this PR fixes**:

Fixes: N/A

**Special notes for your reviewer**: N/A

2021-05-11 13:16 UTC, achatterjee-grafana requested changes
Added doc change request.

2021-05-11 14:27 UTC, ifrost commented on docs/sources/datasources/graphite.md
> +Please check Graphite data source settings for more details.
> Refer to the Graphite data source settings for more details.

There's a help section in data source configuration page in the application. I wanted to suggest checking it for more info and examples:

![info](https://user-images.githubusercontent.com/745532/117832366-b73bcf00-b275-11eb-99ab-dd4b657f4495.gif)

2021-05-12 15:21 UTC, achatterjee-grafana commented on docs/sources/datasources/graphite.md
> +Refer to the Graphite data source settings for more details.
```suggestion
Refer to Graphite data source documentation for more details.
```

2021-05-12 15:29 UTC, achatterjee-grafana approved these changes
LGTM

2021-05-12 15:31 UTC, merged