Docs update for request security
grafana/grafana pull request #33974
Opened 2021-05-12 08:30 UTC by jongyllen

**What this PR does / why we need it**:
Adds a link to request security in enterprise from administration/security

2021-05-12 08:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=33974) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=33974) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=33974) it.</sub>

2021-05-12 08:45 UTC, marefr approved these changes
LGTM :tada:

2021-05-12 12:14 UTC, osg-grafana requested changes

2021-05-12 12:14 UTC, osg-grafana commented on docs/sources/administration/security.md
> +> Request security is only available in Grafana Enterprise v7.4 and later versions. For more information, refer to [Request security]({{< relref "../enterprise/request-security.md" >}}) in [Grafana E
```suggestion
> **Note:** Request security is available in Grafana Enterprise v7.4 and later versions. For more information, refer to [Request security]({{< relref "../enterprise/request-security.md" >}}) in [Grafana Enterprise]({{< relref "../enterprise" >}}).
```

2021-05-12 13:07 UTC, achatterjee-grafana requested changes
Added doc change request.

2021-05-12 13:07 UTC, achatterjee-grafana commented on docs/sources/administration/security.md
> +
```suggestion
The request security configuration option allows users to limit requests from the Grafana server. It targets requests that are generated by users. For more information, refer to [Request security]({{< relref "../enterprise/request-security.md" >}}) in [Grafana Enterprise]({{< relref "../enterprise" >}}).

> **Note:** Request security is available in Grafana Enterprise v7.4 and later versions. 

```

2021-05-12 14:04 UTC, achatterjee-grafana approved these changes
LGTM

2021-05-12 14:05 UTC, achatterjee-grafana commented
Is this for 8.0? Can we add a milestone for the PR. Thank you!

2021-05-12 18:41 UTC, oddlittlebird commented on docs/sources/administration/security.md
> +## Request security
This can be read two ways depending on if a "request" is interpreted as a noun or a verb here. I suggest rewriting this so it is clearer, such as 

Configure request security
Add request security

2021-05-12 18:41 UTC, oddlittlebird commented on docs/sources/administration/security.md
> +## Request security
@mjseaman, something for you to be aware of.

2021-08-18 14:11 UTC, daniellee commented
@achatterjee-grafana @jongyllen merging this even though Diana's requested changes haven't been done. Let me know if you need me to revert.

2021-08-18 14:11 UTC, merged