add new function to write external plugin cue schema into virtual fs
grafana/grafana pull request #33985
Opened 2021-05-12 10:02 UTC by ying-jeanne

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #33899

**Special notes for your reviewer**:

2021-05-12 10:50 UTC, ying-jeanne commented on pkg/services/schemaloader/schemaloader.go
> +		files: make(map[string]*file),
this is probably not enough, regarding if we want to reuse https://github.com/grafana/grafana/blob/main/pkg/schema/load/panel.go#L72, need to have directory instead only plain files

2021-05-13 00:22 UTC, sdboyer reviewed
Review is partway done, but i looked around and [`fstest.MapFS`](https://tip.golang.org/pkg/testing/fstest/#MapFS). Is there something special about what we're doing here that requires our own fs implementation, rather than just using that one?

2021-05-13 00:22 UTC, sdboyer commented on pkg/services/schemaloader/InstanceFS.go
> +package schemaloader
filename should be `instancefs.go`

2021-05-13 00:22 UTC, sdboyer commented on pkg/services/schemaloader/InstanceFS.go
> +	"bytes"
looks like we need gofmt

2021-05-13 00:22 UTC, sdboyer commented on pkg/services/schemaloader/InstanceFS.go
> +	return fs.ModeDir | 0444
Why `0444`?

2021-05-13 00:22 UTC, sdboyer commented on pkg/services/schemaloader/instanceFS_test.go
> +package schemaloader
nit: filename should be `instancefs_test.go`

2021-05-13 00:23 UTC, sdboyer requested changes
whoops, used wrong review state

2021-06-01 09:28 UTC, marefr reviewed
Some suggestions

2021-06-01 09:28 UTC, marefr commented on pkg/services/schemaloader/schemaloader.go
> +}
```suggestion
	instanceVFS *ScueVFS
}
```

2021-06-01 09:28 UTC, marefr commented on pkg/services/schemaloader/schemaloader.go
> +	// fstest.MapFS
```suggestion
	fstest.MapFS
```

2021-06-01 09:28 UTC, marefr commented on pkg/services/schemaloader/schemaloader.go
> +	rs.baseLoadPath.InstanceCueFS.(*ScueVFS).SetInstanceFile(cueFile, content)
```suggestion
	rs.instanceVFS.SetInstanceFile(cueFile, content)
```

2021-06-01 09:28 UTC, marefr commented on pkg/services/schemaloader/schemaloader.go
> +	rs.baseLoadPath.InstanceCueFS.(*ScueVFS).RemoveInstanceFile(cueFile)
```suggestion
	rs.instanceVFS.RemoveInstanceFile(cueFile)
```

2021-06-01 09:28 UTC, marefr commented on pkg/services/schemaloader/schemaloader.go
> +	rs.baseLoadPath.InstanceCueFS.(*ScueVFS).FS.(fstest.MapFS)[rs.pluginFolder] = &fstest.MapFile{Mode: fs.ModeDir}
```suggestion
	rs.instanceVFS = &ScueVFS{
		FS: fstest.MapFS{
			rs.pluginFolder: &fstest.MapFile{Mode: fs.ModeDir},
		},
	}
	rs.baseLoadPath = load.BaseLoadPaths{
		BaseCueFS:       defaultLoadPaths.BaseCueFS,
		DistPluginCueFS: defaultLoadPaths.DistPluginCueFS,
		InstanceCueFS:   rs.instanceVFS,
	}
```

2022-01-06 14:29 UTC, closed without merging