Access control: Document global role and assignment for provisioning
grafana/grafana pull request #34739
Opened 2021-05-26 12:54 UTC by kalleep

Add documentation for grafana enterprise feature

2021-05-26 12:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=34739) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=34739) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=34739) it.</sub>

2021-06-01 13:19 UTC, donomii approved these changes

2021-06-01 13:20 UTC, gamab approved these changes
LGTM! Let's merge it to build on top of it

2021-06-01 13:32 UTC, gamab requested changes
Sorry, I retract my statement for now. Since this will conflict with https://github.com/grafana/grafana/pull/34982. Looking at what's best to do.

2021-06-01 13:51 UTC, gamab approved these changes
Discussed with @donomii. We merge it, update to main and solve resulting conflicts

2021-06-01 13:52 UTC, merged