Security: Update default CSP template and fix firefox CSP issues
grafana/grafana pull request #34836
Opened 2021-05-27 14:46 UTC by kaydelaney

**What this PR does / why we need it**:
Fixes various CSP related issues:
- Add 'strict-dynamic' back to script-src
- Add fonts.gstatic.com to font-src for roboto font
- Add ws(s)://$DOMAIN:$PORT to connect-src
- Change onEvent to on-event in angular templates to fix CSP issues in firefox.
- Add blob: to style-src

**Which issue(s) this PR fixes**:
Fixes #33323

2021-05-27 14:50 UTC, torkelo commented
Awesome! think we should not add fonts.gstatic.com  , just download the files and place them in https://github.com/grafana/grafana/tree/main/public/fonts/roboto

2021-05-27 14:58 UTC, torkelo reviewed
for ws://$DOMAIN:$PORT wss://$DOMAIN:$PORT; do we need to use domain & port? what is you use Grafana behind a proxy? think it's better to 
use ws://$ROOT_WITH_PROTOCOL  and replace that with root_url (without http or https)

2021-05-27 15:03 UTC, kaydelaney commented
> for ws://$DOMAIN:$PORT wss://$DOMAIN:$PORT; do we need to use domain & port? what is you use Grafana behind a proxy? think it's better to
> use ws://$ROOT_WITH_PROTOCOL and replace that with root_url (without http or https)

Are the values for `$(domain)` and `$(http_port)` as used in the value for `root_url` (root_url = %(protocol)s://%(domain)s:%(http_port)s/) not the same as for `cfg.Domain` and `cfg.HTTPPort`?

2021-05-27 15:20 UTC, torkelo commented
@kaydelaney no not necessarily that is just the default template, http port is what grafana server listens to, does not need to be the same as the public facing url / port (root_url)

2021-05-27 15:39 UTC, kaydelaney commented
> @kaydelaney no not necessarily that is just the default template, http port is what grafana server listens to, does not need to be the same as the public facing url / port (root_url)

Ah, right, of course. Made a change, let me know if it looks okay.

2021-05-28 06:09 UTC, torkelo approved these changes
Looks great, awesome job on this! see you found a solution to the onChange issue! 

only nit is $ROOT_URL naming in the template since it is not an URL really (missing protocol), $PUBLIC_DOMAIN_AND_PATH ?

2021-05-28 07:13 UTC, jackw approved these changes
Amazing work on this @kaydelaney. 👏👏👏

2021-05-28 08:15 UTC, dprokop approved these changes
Impressive work @kaydelaney!

2021-05-28 12:42 UTC, aknuds1 requested changes
I think name ROOT_URL is misleading, since it isn't a URL

2021-05-28 12:42 UTC, aknuds1 commented on pkg/middleware/csp.go
> +		val = strings.ReplaceAll(val, "$ROOT_URL", rootURL)
Shouldn't this be named `rootPath`/`ROOT_PATH`, since it's no longer a URL when you strip the protocol?

2021-05-28 12:49 UTC, aknuds1 approved these changes

2021-05-28 12:50 UTC, aknuds1 reviewed
`rootURL` should still be renamed to `rootPath`.

2021-05-28 12:50 UTC, aknuds1 commented on pkg/middleware/csp.go
> +		val = strings.ReplaceAll(val, "$ROOT_PATH", rootURL)
```suggestion
		rootPath := re.ReplaceAllString(cfg.AppURL, "")
		val = strings.ReplaceAll(val, "$ROOT_PATH", rootPath)
```

2021-05-28 13:47 UTC, hugohaggmark commented
Amazing work on this @kaydelaney 🎉

2021-05-28 15:01 UTC, merged

2021-06-03 09:47 UTC, hugohaggmark commented
@kaydelaney friendly reminder to add backport, approve the backport and merge it. Thank you!