Docs: Add Volta to Grafana dev setup instructions
grafana/grafana pull request #35064
Opened 2021-06-01 17:30 UTC by Elfo404

Following up on a recent discussion this PR updates the developer guide adding links to volta setup instruction.

Additionally, it fixes volta's config for all workspaces
- input datasource
- admin app

And adds it to all packages in `packages/*`.

It also changes node version to match exactly the one in `Dockerfile`.

**NOTE:**
we have some inconsistencies in our docker files.
- Our main one (`Dockerfile`) uses node `14.16.0`
- `Dockerfile.ubuntu` uses `14.15.1`
- `scripts/build/ci-e2e/Dockerfile` uses `12.19.0`

We might want to go through and review them.

Also, in the developer guide is mentioned this awesome blog post by @thisisobate: https://grafana.com/blog/2021/03/03/how-to-set-up-a-grafana-development-environment-on-a-windows-pc-using-wsl/, maybe we can update it as well?

2021-06-01 17:42 UTC, achatterjee-grafana requested changes
Added doc change request.

2021-06-01 17:42 UTC, achatterjee-grafana commented on contribute/developer-guide.md
> +- [Node.js](https://nodejs.org) (see `volta.node` property in [package.json](../package.json) for the correct version)
```suggestion
- [Node.js](https://nodejs.org) (see `volta.node` property in [package.json](../package.json) for the correct version).
```

2021-06-01 17:42 UTC, achatterjee-grafana commented on contribute/developer-guide.md
> +- [Yarn](https://yarnpkg.com) (see `volta.yarn` property in [package.json](../package.json) for the correct version)
```suggestion
- [Yarn](https://yarnpkg.com) (see `volta.yarn` property in [package.json](../package.json) for the correct version).
```

2021-06-01 17:42 UTC, achatterjee-grafana commented on contribute/developer-guide.md
> +Refer to the [Volta Getting Started Guide](https://docs.volta.sh/guide/getting-started) for setup instructions for you operating system
```suggestion
Refer to the [Volta Getting Started Guide](https://docs.volta.sh/guide/getting-started) for setup instructions for you operating system.
```

2021-06-01 17:57 UTC, oddlittlebird commented on contribute/developer-guide.md
> +Refer to the [Volta Getting Started Guide](https://docs.volta.sh/guide/getting-started) for setup instructions for you operating system.
```suggestion
Refer to the [Volta Getting Started Guide](https://docs.volta.sh/guide/getting-started) for setup instructions for your operating system.
```

2021-06-01 18:03 UTC, achatterjee-grafana approved these changes
LGTM

2021-06-01 18:10 UTC, aknuds1 approved these changes

2021-06-02 08:03 UTC, thisisobate approved these changes
LGTM! 🎉

2021-06-02 08:08 UTC, merged