access control: 1527/Correct grammar in usage-scenarios
grafana/grafana pull request #35142
Opened 2021-06-02 22:41 UTC by donomii

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #https://github.com/grafana/grafana-enterprise/issues/1527

**Special notes for your reviewer**:

2021-06-03 15:21 UTC, achatterjee-grafana requested changes

2021-08-19 19:28 UTC, daniellee commented
@achatterjee-grafana @osg-grafana is it ok to merge this?

2021-08-20 12:17 UTC, osg-grafana approved these changes
Approving for now and this will get looked at soon again.

2021-08-20 12:18 UTC, osg-grafana commented
Thanks, @donomi!

2021-08-23 09:37 UTC, merged