Caching: document memory limit settings
grafana/grafana pull request #35189
Opened 2021-06-03 13:49 UTC by kminehart

2021-06-03 13:55 UTC, achatterjee-grafana requested changes

2021-06-03 13:55 UTC, achatterjee-grafana commented on docs/sources/enterprise/enterprise-configuration.md
> +This value limits the size of a single cache value. If a cache value (or query result) is submitted that exceeds this size, then it will not be cached. To disable this limit, set this value to `0`.
```suggestion
This value limits the size of a single cache value. If a cache value (or query result) exceeds this size, then it is not cached. To disable this limit, set this value to `0`.
```

2021-06-03 13:55 UTC, achatterjee-grafana commented on docs/sources/enterprise/enterprise-configuration.md
> +The maximum size of the in-memory cache in megabytes. Once this size is reached, new cache items will be rejected. For more flexible control over cache eviction policies and size, please use the Redi
```suggestion
The maximum size of the in-memory cache in megabytes. Once this size is reached, new cache items are rejected. For more flexible control over cache eviction policies and size, use the Redis or Memcached backend. 
```

2021-06-03 14:10 UTC, achatterjee-grafana approved these changes

2021-06-04 12:57 UTC, kminehart commented
FYI I'm waiting for the corresponding PR that enables these settings to be merged first :)

2021-06-04 14:54 UTC, merged