HTTP Client: Introduce go-conntrack into http client provider
grafana/grafana pull request #35314
Opened 2021-06-07 09:36 UTC by dsotirakis

**What this PR does / why we need it**:

We introduce `go-conntrack` to be able to track http connections names/types, so we can instrument services better and also have a better connections overview.

**Which issue(s) this PR fixes**:

Fixes #35257

**Special notes for your reviewer**:

This fix is for `v7.5.x` versions - another PR will (probably?) need to be raised to include changes in the `grafana-plugin-sdk-go` repo.

2021-06-07 09:36 UTC, dsotirakis commented on pkg/server/server.go
> +		httpclientprovider.New(s.cfg, "server"),
Something better needed here

2021-06-07 10:07 UTC, marefr requested changes
See comments

2021-06-07 10:07 UTC, marefr commented on pkg/infra/httpclient/httpclientprovider/http_client_provider.go
> +			KeepAlive: 30 * time.Second,
Should take the created transport and use that, i.e. `conntrack.DialWithDialer(transport.Dial...)`

2021-06-07 10:07 UTC, marefr commented on pkg/infra/httpclient/httpclientprovider/http_client_provider.go
> +		conntrack.DialWithName(name),
How are the name used? Should probably use something similar like this? https://github.com/grafana/grafana/blob/ce513e4637e2f8fbe56bb8a8c9077bf57a798ca2/pkg/infra/httpclient/httpclientprovider/datasource_metrics_middleware.go#L65

2021-06-07 10:07 UTC, marefr commented on pkg/infra/httpclient/httpclientprovider/http_client_provider.go
> +func New(cfg *setting.Cfg, connName string) httpclient.Provider {
This is created once when Grafana starts. Think you want separate name per data source? See other comment

2021-06-07 10:08 UTC, marefr commented
Might be smarter to start with a PR targeting v7.5.x to get it out for v7.5.8 since that code is completely different than this which uses the HTTP client provider.

2021-06-08 13:20 UTC, marefr commented
@dsotirakis so now when v7.5.x is fixed I think this should be trivial to update?

2021-06-09 15:03 UTC, marefr requested changes
Looks good, but have some suggested changes

2021-06-09 15:03 UTC, marefr commented on pkg/infra/httpclient/httpclientprovider/http_client_provider.go
> +		conntrack.DialWithTracing(),
Let's skip this one for now. Still have no idea how to expose this data. Perhaps something to look into later together with adding support for conntrack to grafana server?

2021-06-09 15:21 UTC, dsotirakis commented on pkg/infra/httpclient/httpclientprovider/http_client_provider.go
> +		}),
Nice one

2021-06-09 15:27 UTC, marefr approved these changes
LGTM

2021-06-09 16:13 UTC, merged