Login: Require user to not be signed in to get request password email
grafana/grafana pull request #35421
Opened 2021-06-09 11:59 UTC by tskarhed

**What this PR does / why we need it**:
Restricts access to the reset-password-email route if you're logged in. Chances are you already know your password

**Which issue(s) this PR fixes**:
Closes #35253

2021-06-11 05:58 UTC, hugohaggmark commented
Friendly reminder to add the correct milestone and backport label if this needs to be released in a patch release. Thank you!

2021-06-14 09:48 UTC, marefr requested changes
Looks good I think. Suggested some changes.

2021-06-14 09:48 UTC, marefr commented on pkg/middleware/auth.go
> +	if c.IsSignedIn && !c.IsAnonymous {
I believe `c.IsSignedIn` is false when `c.IsAnonymous` is true according to [code](https://github.com/grafana/grafana/blob/75ff02a9fb6c06664171cde75ddf87336a9f1886/pkg/services/contexthandler/contexthandler.go#L144-L146) so think the following should be enough:

```suggestion
	if c.IsSignedIn {
```

2021-06-14 16:02 UTC, marefr approved these changes
LGTM

2021-06-14 16:02 UTC, merged