QueryField: Make editor navigable with  keyboard
grafana/grafana pull request #35490
Opened 2021-06-10 10:07 UTC by tskarhed

**What this PR does / why we need it**:
Fixes #35378

Use escape key to exit focus and you can tab to change focus unless you've already written something.

2021-06-10 10:51 UTC, kaydelaney commented on packages/grafana-ui/src/components/QueryField/QueryField.tsx
> +  onKeyDown = (event: KeyboardEvent, editor: CoreEditor, next: Function) => {
```suggestion
  onKeyDown = (keyEvent: Event, editor: CoreEditor, next: Function) => {
    const event = keyEvent as KeyboardEvent;
```
Unfortunately I think you need to do something like this to satisfy typechecks

2021-06-10 10:52 UTC, kaydelaney requested changes
Looks good and works! Do you think you could add an `aria-description` attribute informing the user what the component is and that "esc" can be pressed to escape focus?

2021-06-10 13:17 UTC, tskarhed commented
I added a tooltip, but it behaves weirdly. It should be shown on focus, but you kinda have to play around with the mouse to make it show. Any idea how to solve this?

2021-06-14 08:34 UTC, tskarhed commented
I'm currently trying to get a decent label with the escape key info working. I'm having some issues with the Tooltip, so might go for another solution there.

2021-06-14 11:37 UTC, tskarhed commented
Focus styles probably need to be added, and I temporarily used `FormValidationMessage`. This should be changed to something neutral.

2021-06-18 14:19 UTC, tskarhed commented
Okay, this looks decent. There is however a problem with the focus/blur if there is some content in the input. Not sure what to do about it.

Removed the label, to get some more UX opinions first.

2021-08-17 12:19 UTC, tskarhed commented
Closing this in favor of a future Monaco editor.

2021-08-17 12:19 UTC, closed without merging