[v8.0.x] Graph and GraphNG: makes the stories internal
grafana/grafana pull request #35499
Opened 2021-06-10 11:02 UTC by grafanabot

Backport bea874740577dc0017291300e7441b41cc0bcceb from #35491

2021-06-10 11:03 UTC, aocenas commented
As we are doing a release right now please do not merge, moving to 8.0.2

2021-06-10 11:04 UTC, aocenas requested changes
blocking this until 8.0.1 release is finished

2021-06-11 07:16 UTC, thisisobate approved these changes
LGTM!

2021-06-11 13:46 UTC, aocenas approved these changes

2021-06-11 13:46 UTC, merged