Docs: Document migration of dashboard alert permissions
grafana/grafana pull request #35559
Opened 2021-06-11 11:35 UTC by papagian

**What this PR does / why we need it**:
It updates Grafana 8 Alerts [opt-in](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/) page by providing additional information about permissions.
Also it removed warning for beta.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-06-11 17:28 UTC, pkolyvas requested changes
Made a couple of suggestions for clarity.

2021-06-11 17:28 UTC, pkolyvas commented on docs/sources/alerting/unified-alerting/opt-in.md
> +Read and write access to dashboard alerts used to be governed by the dashboard and folder permissions under they lived. Grafana 8 Alerts also live under folders and inherite their permissions. During
Small suggestion & correction:

`Read and write access to dashboard alerts in Grafana versions 7 and earlier were governed by the dashboard and folder permissions under which the the alerts were stored. In Grafana 8, alerts are also stored in folders and inherit the permissions of those folders. During the migration, dashboard alert permissions are matched to the new rules permissions as follows:`

2021-06-14 15:11 UTC, achatterjee-grafana reviewed
Added some minor change requests.

2021-06-14 15:11 UTC, achatterjee-grafana commented on docs/sources/alerting/unified-alerting/opt-in.md
> +At startup, when [the feature toggle is enabled]({{< relref "../../administration/configuration.md">}}#feature_toggles), Grafana dashboard alerting is disabled and existing dashboard alerts are migra
```suggestion
At startup, when [the feature toggle is enabled]({{< relref "../../administration/configuration.md">}}#feature_toggles), the legacy Grafana dashboard alerting is disabled and existing dashboard alerts are migrated into a format that is compatible with the Grafana 8 alerting system. You can view these migrated rules, alongside any new alerts you create after the migration, from the Alerting page of your Grafana instance.
```

2021-06-14 15:11 UTC, achatterjee-grafana commented on docs/sources/alerting/unified-alerting/opt-in.md
> +Read and write access to dashboard alerts in Grafana versions 7 and earlier were governed by the dashboard and folder permissions under which the the alerts were stored. In Grafana 8, alerts are also
```suggestion
Read and write access to dashboard alerts in Grafana versions 7 and earlier were governed by the dashboard and folder permissions under which the alerts were stored. In Grafana 8, alerts are stored in folders and inherit the permissions of those folders. During the migration, dashboard alert permissions are matched to the new rules permissions as follows:
```

2021-06-14 15:19 UTC, achatterjee-grafana approved these changes
LGTM

2021-06-15 14:39 UTC, pkolyvas approved these changes
Thank you!

2021-06-15 14:39 UTC, merged