Auth: JWT - remove all base64 paddings in JWT tokens
grafana/grafana pull request #35602
Opened 2021-06-13 21:14 UTC by gillg

**What this PR does / why we need it**:

Remove unhandled base64 paddings (= chars) by go-jose JWT lib

**Which issue(s) this PR fixes**:

Fixes #34496

**Special notes for your reviewer**:

2021-06-13 21:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=35602) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=35602) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=35602) it.</sub>

2021-06-21 05:59 UTC, gillg commented
Anyone to review ?

2021-06-29 04:31 UTC, ryantxu reviewed
This seems good -- but can we add a test token to make sure it stays supported and does not regress

2021-06-29 15:23 UTC, marefr requested changes
A test as suggested would be nice. Would probably be a bit similar to https://github.com/grafana/grafana/blob/main/pkg/services/contexthandler/contexthandler_test.go

Let us know if you need help with the tests and we can take over and/or assist you.

2021-06-29 15:30 UTC, gillg commented
> A test as suggested would be nice. Would probably be a bit similar to https://github.com/grafana/grafana/blob/main/pkg/services/contexthandler/contexthandler_test.go
> 
> Let us know if you need help with the tests and we can take over and/or assist you.

I'm definitely not against contribution for tests. I can navigate in Go code, create some new little things, but I'm definitely not familiar to create things from scratch.
I can eventualy add a scenario here : https://github.com/grafana/grafana/blob/main/pkg/services/auth/jwt/auth_test.go but I have no idea how to simulate padded token creation. For now all test tokens are generated by https://github.com/grafana/grafana/blob/c3e26657e9fb3368b1a204ea8d51bae274115a12/pkg/services/auth/jwt/signing_test.go#L13

2021-07-13 20:50 UTC, marefr commented
> I can eventualy add a scenario here : https://github.com/grafana/grafana/blob/main/pkg/services/auth/jwt/auth_test.go but I have no idea how to simulate padded token creation. For now all test tokens are generated by

@gillg after looking at this again I think it would make more sense if you could move your `sanitizeJWT` changes into the JWT AuthService, before this code:
https://github.com/grafana/grafana/blob/19f18bcecc7762bad800f3f648a0da46c3875101/pkg/services/auth/jwt/auth.go#L55

> I can eventualy add a scenario here : https://github.com/grafana/grafana/blob/main/pkg/services/auth/jwt/auth_test.go

Yes that would make sense. I guess you would use the `sign` function to generate a test token. Based on my understanding the `sign` function should return a token in the `compact JWS format`, i.e. `<protected base64 encoded>.<payload base64 encoded>.<signature base64 encoded>`. So adding a test  where `=` to the end of a generated token before calling `Verify` and verifying that `=` is removed from token and can be verified as expected. 

For additional information, I went to https://jwt.io/#debugger-io where a token was pre-filled and tried to add an `=` to the end and then the following warning was logged:
![image](https://user-images.githubusercontent.com/1668778/125522858-49dfb805-7a66-4bec-b627-915f5896ea2f.png)

Let me know if you need help or if something is unclear.

2021-07-22 17:30 UTC, gillg reviewed
I added a test and moved the sanitize function

2021-07-22 17:33 UTC, gillg commented
The build failed but it seems not related to the code. Can you relaunch it ?

2021-08-17 09:34 UTC, marefr commented
@gillg Been away on PTO. I've restarted the build. In case it fails you might need to sync with latest main changes.

2021-08-17 20:39 UTC, gillg commented
> @gillg Been away on PTO. I've restarted the build. In case it fails you might need to sync with latest main changes.

I rebased the dev, but how it's possible build always fails ?
Now ngalert tests are failing, does anyone can merge any dev ?

2021-08-18 11:53 UTC, marefr commented
Restarted it now. If that doesn't work would suggest syncing with main again.

2021-08-24 20:28 UTC, gillg commented
Any chance to be part of the next release ?

2021-10-27 16:48 UTC, marefr approved these changes
LGTM

2021-10-27 16:50 UTC, merged