Plugins: Improve wording around allow_loading_unsigned_plugins configuration
grafana/grafana pull request #35731
Opened 2021-06-15 11:02 UTC by wbrowne

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/35670

2021-06-15 11:03 UTC, marefr approved these changes
LGTM 🎉

2021-06-15 16:03 UTC, serramatutu commented
Thanks @wbrowne for fixing it and @marefr for forwarding the feedback :)

2021-06-15 16:15 UTC, wbrowne commented
No worries @serramatutu - thanks for contributing your feedback to Grafana! ❤️

2021-06-15 16:24 UTC, achatterjee-grafana requested changes
Added doc change request.

2021-06-15 16:24 UTC, achatterjee-grafana commented on conf/defaults.ini
> +# Enter a comma-separated list of plugin identifiers to identify plugins that should be loaded even if they are unsigned. Plugins with modified signatures will never be loaded.
```suggestion
# Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.
```

2021-06-15 16:24 UTC, achatterjee-grafana commented on conf/sample.ini
> +# Enter a comma-separated list of plugin identifiers to identify plugins that should be loaded even if they are unsigned. Plugins with modified signatures will never be loaded.
```suggestion
# Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.
```

2021-06-15 16:24 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +Enter a comma-separated list of plugin identifiers to identify plugins that should be loaded even if they are unsigned. Plugins with modified signatures will never be loaded.
```suggestion
Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.
```

2021-06-15 16:24 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +Please note that using this is _not_ recommended. For more information, refer to [Plugin signatures]({{< relref "../plugins/plugin-signatures.md" >}}).
```suggestion
We do _not_ recommend using this option. For more information, refer to [Plugin signatures]({{< relref "../plugins/plugin-signatures.md" >}}).
```

2021-06-15 16:30 UTC, achatterjee-grafana approved these changes

2021-06-15 16:53 UTC, merged

2023-04-10 06:58 UTC, nodakai commented
Few people would understand what's meant by "plugins with modified signatures are never loaded." At least I didn't.

It's important to use clear wording when communicating with the community, when the majority of them aren't "Grafana experts".  I'd write "If you have an invalid MANIFEST.txt in the plugin deployment directory, Grafana would not load the plugin even if `allow_loading_unsigned_plugin` is configured. Consider removing the manifest file altogether"

2023-04-11 09:45 UTC, wbrowne commented
Thanks for your feedback @nodakai.

>If you have an invalid MANIFEST.txt

"Invalid" is not specific enough in this case. The signature `Modified` status specifically refers to when there is a content mismatch between what was found in the signature and what discovered when loading the plugin. For example if someone edited a plugin file after it was signed and tried to redistribute it as the original. The signatures statuses are described in [this docs section](https://grafana.com/docs/grafana/latest/administration/plugin-management/#plugin-signatures).

>Consider removing the manifest file altogether

This is not something that we recommend. The MANIFEST.txt is used to guarantee that a user is loading the plugin that the plugin author distributed.

If you think there are improvements to be made, you can open a pull request and we can go from there.