WIP: Add alertmanager notifications tab
grafana/grafana pull request #35759
Opened 2021-06-15 14:12 UTC by nathanrodman

**What this PR does / why we need it**:

Adds a view for the notifications from Alertmanager groups.

Todo:

- [ ] Hook up ending silence endoint
- [ ] Create link for creating a silence from an alertmanager alert.
- [ ] Style changes

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-06-22 10:38 UTC, domasx2 requested changes
Found few things to improve. Also please write at least 1 test :) 

Once my my reponsive rule list PR is merged, will be able to upgrade this view as well to be mobile friendlier

2021-06-22 10:38 UTC, domasx2 commented on public/app/features/alerting/unified/AlertManagerNotifications.tsx
> +            <AmNotificationsGroup alertManagerSourceName={alertManagerSourceName || ''} key={group.id} group={group} />
it seems types are wrong, `group.id` does not exist. I suggest to stringify `group.labels` instead for `key`, they **should** be unique for each group

2021-06-22 10:38 UTC, domasx2 commented on public/app/features/alerting/unified/components/amnotifications/AmNotificationsAlertsTableRow.tsx
> +        .map(([labelKey, labelValue]) => {
```suggestion
        .filter(([labelKey]) => !(labelKey.startsWith('__') && labelKey.endsWith('__'))).map(([labelKey, labelValue]) => {
```
should filter out "internal" labels that start and end with `__`

2021-06-22 10:38 UTC, domasx2 commented on public/app/features/alerting/unified/AlertManagerNotifications.tsx
> +      {results &&
need:
* loading indicator when loading
* error message on error
* some sort of message if loaded successfully, but no groups in result

2021-06-22 10:38 UTC, domasx2 commented on public/app/features/alerting/unified/AlertManagerNotifications.tsx
> +      dispatch(fetchAlertGroupsAction(alertManagerSourceName));
should poll on interval, same as rules list

2021-06-22 18:52 UTC, nathanrodman commented on pkg/api/index.go
> +			alertChildNavs = append(alertChildNavs, &dtos.NavLink{Text: "Alertmanager", Id: "alertmanager", Url: hs.Cfg.AppSubURL + "/alerting/alertmanager", Icon: "layer-group"})
That makes sense and think Notifications works for the nav. But what about the route `/notifications`? It is already used for receivers. Maybe `/amNotifications` or `/groups`?

2021-06-23 03:09 UTC, nathanrodman commented
thanks for the great feedback @domasx2. I've incorporated the feedback and added a very basic test for rendering the groups.

2021-07-07 08:12 UTC, domasx2 approved these changes
lgtm!

2021-07-07 23:17 UTC, merged