Add cloud specific deep linking
grafana/grafana pull request #35784
Opened 2021-06-15 23:19 UTC by shuotli

**What this PR does / why we need it**:

URL to Azure Portal should be specific to cloud.
Adding `getDeepLinkRoute` so the metrics and logs can link to Azure portal according to the cloud they are in.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-06-17 06:50 UTC, kostrse requested changes
Pls move the function to credentials.ts

2021-06-17 06:50 UTC, kostrse commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/api/routes.ts
> +export function getDeepLinkRoute(azureCloud: string): string {
I would move this function to `credentials.ts` and call it `getAzurePortalUrl`.
This routes file is for plugin route definitions.

2021-06-17 06:52 UTC, kostrse commented on public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_log_analytics/azure_log_analytics_datasource.ts
> +  deepLinkUrl: string;
nit: maybe call it `azurePortalUrl` to easier undestand what is it actually, since it's just a url to Azure Portal.

2021-06-23 07:42 UTC, andresmgot approved these changes
this should be fine to be merged, right @kostrse ?

2021-06-23 07:55 UTC, kostrse commented
> this should be fine to be merged, right @kostrse ?

Yes, it's good for me!

2021-06-23 08:26 UTC, merged