SQL: use metric label as field name
grafana/grafana pull request #35839
Opened 2021-06-16 19:29 UTC by ryantxu

This is a SQL specific and back end only flavor for:
https://github.com/grafana/grafana/pull/35392

![image](https://user-images.githubusercontent.com/705951/122280691-4e5ffc00-ce9e-11eb-8eb2-e16ce2f134bc.png)

http://localhost:3000/d/JYola5qzz/datasource-tests-postgres?orgId=1&editPanel=4

2021-06-16 19:36 UTC, torkelo commented on pkg/tsdb/sqleng/sql_engine.go
> +			// Before 8x, a special metric label was used to name fields
```suggestion
			// Before 8x, a special metric column was used to name time series. The LongToWide transforms that into a metric label on the value column.
			// But that makes series name have both the value column name AND the metric name. So here we are removing the metric label here and moving it to the 
			// field name to get the same naming for the series as pre v8 
```

2021-06-16 19:37 UTC, torkelo approved these changes
This looks good to me

2021-06-17 08:07 UTC, marefr requested changes
Works in the case where you only have two fields, but not when you have more than one value fields with label metric. There's other cases when there's not a value and metric field as can be seen in [documentation](https://grafana.com/docs/grafana/latest/datasources/postgres/#time-series-queries):

The gdev dashboard has one such example for postgres unittest dashboard:
![image](https://user-images.githubusercontent.com/1668778/122356435-1797ed80-cf53-11eb-8f62-b04e07b0bb59.png)

```sql
SELECT
  $__timeGroup("time_date_time",'5m'),
  min("value_double") as "min_value",
  max("value_double") as "max_value"
FROM test_data
WHERE $__timeFilter("time_date_time")
GROUP BY time
ORDER BY time
```

This gdev dashboard shows that it resolves one panel, but not the other two:

![image](https://user-images.githubusercontent.com/1668778/122354828-a99ef680-cf51-11eb-96ad-24d126b71852.png)

For example below query generates the following frame
```sql
SELECT
  $__timeGroup("createdAt",'$summarize'),
  max(value) as "value",
  hostname as "metric"
FROM 
  grafana_metric
WHERE
  $__timeFilter("createdAt") AND
  measurement = 'cpu' AND
  hostname IN($host)
GROUP BY time, metric
ORDER BY time
```

```json
{
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "name": "results",
              "meta": {
                "executedQueryString": "SELECT\n  floor(extract(epoch from \"createdAt\")/60)*60 AS \"time\",\n  max(value) as \"value\",\n  hostname as \"metric\"\nFROM \n  grafana_metric\nWHERE\n  \"createdAt\" BETWEEN '2021-06-17T07:47:59.888Z' AND '2021-06-17T07:52:59.888Z' AND\n  measurement = 'cpu' AND\n  hostname IN('10.1.100.1','10.1.100.10','server1','server2')\nGROUP BY time, metric\nORDER BY time"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "metric": "server1"
                  }
                },
                {
                  "name": "value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "metric": "server2"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1623916080000,
                  1623916140000,
                  1623916200000,
                  1623916260000,
                  1623916320000
                ],
                [
                  101.94567116740645,
                  101.32983803008855,
                  98.24485134174023,
                  99.11082242003671,
                  98.20762076760217
                ],
                [
                  102.17495640876385,
                  101.49139611423894,
                  98.5697798472507,
                  99.34979998130595,
                  98.5910734483771
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}
```

We need to decide whether wide data frames for SQL is the way forward. To me it is because of unified alerting and multi dimensions plus v8 is a good opportunity to do breaking change as long as we have a good workaround story. Let us know if you need help from backend platform figuring out this.

2021-06-17 09:04 UTC, hugohaggmark commented
This solves this issue for me #35599

2021-06-17 13:43 UTC, torkelo commented
@marefr 

SELECT
  $__timeGroup("time_date_time",'5m'),
  min("value_double") as "min_value",
  max("value_double") as "max_value"
FROM test_data
WHERE $__timeFilter("time_date_time")
GROUP BY time
ORDER BY time 

This query did not work in v7.5 for me , what format have selected time series or table?

We need to figure out somethign soon as v8 breaks almost all time series queries

2021-06-17 13:51 UTC, torkelo commented
@marefr pushed an update that fixes it so that it works on all panels on that test dashboard, was a wrong condition that made the fix logic only apply to data frames with 2 fields

2021-06-17 13:52 UTC, marefr commented
@torkelo 

> This query did not work in v7.5 for me, what format have selected time series or table? The query is missing a metric field as well so the above code should not have any effect ?

The old logic is, if there's no metric column selected, use the names of value columns as metric :)

2021-06-17 14:05 UTC, torkelo commented
@marefr it's working now, the query below works well for me

```sql
SELECT
$__timeGroup("time_date_time",'5m'),
min("value_double") as "min_value",
max("value_double") as "max_value"
FROM test_data
WHERE $__timeFilter("time_date_time")
GROUP BY time
ORDER BY time
```

2021-06-17 14:15 UTC, torkelo commented
pushed another update that refines the logic to only be applied when the orignal query returns 3 columns (so if you have more than one value field the fixing logic wont happen). 
Updated a integration test as well

2021-06-18 00:15 UTC, marefr approved these changes
LGTM

Works great :tada:

2021-06-18 06:05 UTC, merged