[Oauth] Support tokens outside the UserInfoJson struct format
grafana/grafana pull request #35985
Opened 2021-06-21 09:50 UTC by stg-0

**What this PR does / why we need it**:

The PR https://github.com/grafana/grafana/pull/14683 introduced the possibility to obtain the user's email using jmespath, 
but if the user's attributes don't have the format expected in the UserInfoJson struct (map[string][]string), the function extractFromAPI will return an error.

In this simple PR, the data is returned without Attributes, but with rawJSON, which allows to search for the user's email using the jmespath specified by the user in email_attribute_path config.

**Which issue(s) this PR fixes**:

It might help with this one: https://github.com/grafana/grafana/issues/13549

**Special notes for your reviewer**:

The PR https://github.com/grafana/grafana/pull/14683 seems to have the use-case contemplated in the tests (generic_oauth_test.go) specifying different types of attributes.

2021-06-21 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=35985) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=35985) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=35985) it.</sub>

2021-06-22 09:15 UTC, jasiam approved these changes

2021-06-22 09:18 UTC, ddepablo-stratio approved these changes

2021-06-22 09:24 UTC, danieldepablo approved these changes

2021-06-29 14:33 UTC, marefr commented
Thanks. Please open a bug report and reference that in the PR description. Please describe the details and how to reproduce in regards to "but if the user's attributes don't have the format expected in the UserInfoJson struct (map[string][]string), the function extractFromAPI will return an error.". Very hard to understand what you're trying to solve when not seeing the problem and the change suggested looks to me strange.

2021-06-29 14:34 UTC, marefr reviewed
Thanks. Please open a bug report and reference that in the PR description. Please describe the details and how to reproduce in regards to "but if the user's attributes don't have the format expected in the UserInfoJson struct (map[string][]string), the function extractFromAPI will return an error.". Very hard to understand what you're trying to solve when not seeing the problem and the change suggested looks to me strange.

2021-07-08 09:26 UTC, marefr requested changes
To properly resolve this I suggest changing the 
https://github.com/grafana/grafana/blob/2616580bae3218c91b38a93ae2fc74ba3276462f/pkg/login/social/generic_oauth.go#L88

To 

```go
Attributes  map[string]interface{} `json:"attributes"`
``` 

With this you also have to change the following code, trying to cast it to a string array and extract the email as before.
https://github.com/grafana/grafana/blob/2616580bae3218c91b38a93ae2fc74ba3276462f/pkg/login/social/generic_oauth.go#L306

2022-04-07 02:04 UTC, closed without merging