VariableSettings: fix tool-tip hyperlink color
grafana/grafana pull request #36140
Opened 2021-06-24 16:43 UTC by tharun208

**What this PR does / why we need it**: Right now, it is difficult to recognize the tool-tip in the variable's setting `regex` field due to the missing color or indication of the hyperlink.

**Which issue(s) this PR fixes**: This PR fixed this by adding `color` to the hyperlink.

Fixes #36122

**Special notes for your reviewer**:

2021-06-29 08:10 UTC, tskarhed requested changes
I still don't think this offers enough contrast. 

![Screenshot from 2021-06-29 10-09-17](https://user-images.githubusercontent.com/1438972/123761548-333fb400-d8c2-11eb-937f-aded8e59c0cd.png)

2021-06-29 08:21 UTC, tharun208 commented
@tskarhed, can I use a different class ?. the class I referred to is used by other hyperlink

2021-06-29 08:28 UTC, tskarhed commented
> @tskarhed, can I use a different class ?. the class I referred to is used by other hyperlink

I'm not sure. Hyperlinks aren't typically used in tooltips, that's why it looks off. Maybe moving the link outside of the tooltip could be an option.

2021-06-29 09:06 UTC, tharun208 commented
> > @tskarhed, can I use a different class ?. the class I referred to is used by other hyperlink
> 
> I'm not sure. Hyperlinks aren't typically used in tooltips, that's why it looks off. Maybe moving the link outside of the tooltip could be an option.

@tskarhed, instead of the tooltip, can use `Modal`?

2021-06-29 09:34 UTC, tharun208 commented
@tskarhed found that we are using 2 different versions of `external-link-color` for the dark and white themes ( https://github.com/grafana/grafana/blob/main/public/sass/_variables.dark.generated.scss#L120). can I update it to match with the white theme external link color?

2021-06-29 10:15 UTC, Ijin08 commented
The problem with this solution is that the link color in the light theme is suppose to be accessible on light backgrounds. The tooltip background however is dark. 
I think the pr solves the wrong problem. The issue is that the tooltip is not designed with hyper links in mind. The example showed in the issue uses the inline form styles used in query editor when it should be the vertical form styles. Then the tooltip would be replaced with a description that then could use the blue link color. 
The issue would still be there if we use links in tooltips in the current query editors. But then we would have to change background color to tooltip.

2021-06-29 10:45 UTC, tharun208 commented
@Ijin08 any possible ux workaround for this ?

2021-06-30 10:29 UTC, Ijin08 commented
@tharun208 
For now this would be the best solution:
<img width="603" alt="Screenshot 2021-06-30 at 12 22 59" src="https://user-images.githubusercontent.com/23470681/123945479-7a9b7280-d99e-11eb-8515-f619cbd27e06.png">
Adding a underline to the link and using the maxContrast color for the text color.

2021-06-30 12:32 UTC, tharun208 commented
sorry for the force push 🙏

2021-06-30 12:59 UTC, torkelo commented on public/app/features/variables/query/QueryVariableEditor.tsx
> +                    `}
This needs to be fixed in https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Tooltip/_Tooltip.scss  not inline for this specific link

2021-06-30 15:55 UTC, torkelo commented on packages/grafana-ui/src/components/Tooltip/_Tooltip.scss
> +    color: #fff;
```suggestion
    color: $white;
```

2021-06-30 15:56 UTC, tharun208 commented on packages/grafana-ui/src/components/Tooltip/_Tooltip.scss
> +    color: #fff;
addressed

2021-06-30 15:57 UTC, tharun208 commented on packages/grafana-ui/src/components/Tooltip/_Tooltip.scss
> +    color: #fff;
addressed

2021-07-01 08:24 UTC, merged