<Explore>: Minor documentation update"
grafana/grafana pull request #36338
Opened 2021-07-01 08:55 UTC by w-endre

**What this PR does / why we need it**:
Resolves a conflict in the documentation. 

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:
Feel free to re-phrase the sentence.

2021-07-01 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=36338) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=36338) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=36338) it.</sub>

2021-07-01 16:04 UTC, achatterjee-grafana requested changes
The "viewers_can_edit" is mentioned in a separate topic and should be linked correctly.

2021-07-14 16:39 UTC, daniellee commented
@w-endre to be able to merge this PR, you need to sign the CLA. Let us know if you are having any problems with that.

2021-07-15 07:42 UTC, w-endre commented
> @w-endre to be able to merge this PR, you need to sign the CLA. Let us know if you are having any problems with that.

Thank you for the notification. I signed it.

2021-07-19 18:12 UTC, achatterjee-grafana approved these changes

2021-08-18 19:19 UTC, daniellee commented on docs/sources/explore/_index.md
> +In order to access Explore, you must have an editor or an administrator role, unless the [viewers_can_edit option](viewers_can_edit) is enabled.  Refer to [Organization roles]({{< relref "../permissi
Tested this locally and the link is incorrect.

```suggestion
In order to access Explore, you must have an editor or an administrator role, unless the [viewers_can_edit option]({{< relref "../administration/configuration/#viewers_can_edit" >}}) is enabled. Refer to [Organization roles]({{< relref "../permissions/organization_roles.md" >}}) for more information on what each role has access to.
```

2021-08-18 19:59 UTC, merged