Docs: Fix author email description
grafana/grafana pull request #36590
Opened 2021-07-09 05:51 UTC by dbbaughe

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-07-09 05:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=36590) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=36590) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=36590) it.</sub>

2021-07-09 07:34 UTC, marcusolsson requested changes
Good catch! 👍 

Since the `metadata.md` file is a generated file, you'd have to make the change in [plugin.schema.json](https://github.com/grafana/grafana/blob/10a942aad0498e9e9d4530d008751941bfec6511/docs/sources/developers/plugins/plugin.schema.json#L190) and then generate the metadata.md using [json-schema-docs](https://github.com/grafana/json-schema-docs).

Could you update plugin.schema.json as well?

2021-07-09 16:14 UTC, dbbaughe commented
Hey @marcusolsson,

Let me know if I used your json schema docs incorrectly...
`../json-schema-docs/json-schema-docs -schema ./docs/sources/developers/plugins/plugin.schema.json > ./docs/sources/developers/plugins/metadata.md`

It seems to have removed the notice at the top of the metadata.md docs to not edit the file (which I did not see before 😉)

2021-07-12 08:53 UTC, marcusolsson commented
Sorry about that 🙏  we need to improve the documentation for how to update the plugin schema docs.

You need to use the template to add the front matter:

```
json-schema-docs -schema ./plugin.schema.json -template ./metadata.md.tpl > metadata.md
```

2021-07-20 17:55 UTC, achatterjee-grafana commented on docs/sources/developers/plugins/metadata.md
> -
Why was the front matter deleted? Needs dev review.

2021-07-20 17:56 UTC, achatterjee-grafana reviewed
Added a question.

2021-07-20 18:12 UTC, dbbaughe commented
@marcusolsson, feel free to pick up the change. I think I should have just opened a simple GitHub issue instead :P
There was a bit more involvement than I thought around the CLA, so going to close this on my end for now.

Thanks!

2021-07-20 18:12 UTC, closed without merging