live: HA docs update for v8.1
grafana/grafana pull request #36787
Opened 2021-07-15 09:52 UTC by FZambia

**What this PR does / why we need it**:

Grafana v8.1 will include experimental support for HA setup with Redis.

**Which issue(s) this PR fixes**:

Addresses a part of https://github.com/grafana/grafana/issues/35448#issuecomment-872224175

2021-07-19 04:22 UTC, ryantxu approved these changes
LGTM

2021-07-22 13:46 UTC, achatterjee-grafana requested changes
Added some review comments.

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +The name of high-availability engine for Grafana Live. By default, it's not set. The only possible value is "redis".
```suggestion
The high availability (HA) engine name for Grafana Live. By default, it's not set. The only possible value is "redis".
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +More information in [Configure Grafana Live HA setup]({{< relref "../live/live-ha-setup.md" >}}).
```suggestion
For more information, refer to [Configure Grafana Live HA setup]({{< relref "../live/live-ha-setup.md" >}}).
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/administration/configuration.md
> +Address string of selected HA Live engine. For Redis it's a `host:port` string. Example:
```suggestion
Address string of selected the high availability (HA) Live engine. For Redis, it's a `host:port` string. Example:
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +In HA Grafana setup which involves several Grafana server instances behind a load balancer you may come across the following limitations:
```suggestion
In a high availability Grafana setup involving several Grafana server instances behind a load balancer, you can find the following limitations:
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +To eliminate these limitations Grafana v8.1 introduced an experimental Live HA engine which requires Redis to work.
```suggestion
To bypass these limitations, Grafana v8.1 has an experimental Live HA engine that requires Redis to work.
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +With Redis engine configured Grafana Live will keep its state in Redis and will use Redis PUB/SUB functionality to deliver messages to all subscribers throughout all Grafana server nodes.
```suggestion
When the Redis engine is configured, Grafana Live keeps its state in Redis and uses Redis PUB/SUB functionality to deliver messages to all subscribers throughout all Grafana server nodes.
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +- All built-in real-time notifications like dashboard changes will be delivered to all Grafana server instances and broadcasted to all subscribers.
```suggestion
- All built-in real-time notifications like dashboard changes are delivered to all Grafana server instances and broadcasted to all subscribers.
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +- Streaming from Telegraf will deliver messages to all subscribers
```suggestion
- Streaming from Telegraf delivera messages to all subscribers.
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +- A separate unidirectional stream between Grafana and backend data source will still be opened on different Grafana servers but publishing data to a channel will only deliver messages to instance su
```suggestion
- A separate unidirectional stream between Grafana and backend data source opens on different Grafana servers. Publishing data to a channel delivers messages to instance subscribers, as a result, publications from different instances on different machines do not produce duplicate data on panels.
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +> **Note:**  It's possible to use Redis Sentinel and Haproxy to achieve highly-available Redis setup. Redis nodes should be managed by [Redis Sentinel](https://redis.io/topics/sentinel) to achieve au
```suggestion
> **Note:**  It's possible to use Redis Sentinel and Haproxy to achieve a highly available Redis setup. Redis nodes should be managed by [Redis Sentinel](https://redis.io/topics/sentinel) to achieve automatic failover. Haproxy configuration example:
```

2021-07-22 13:46 UTC, achatterjee-grafana commented on docs/sources/live/live-ha-setup.md
> +> Then point Grafana Live to Haproxy address:port.
```suggestion
> Next, point Grafana Live to Haproxy address:port.
```

2021-07-23 13:45 UTC, achatterjee-grafana approved these changes
LGTM

2021-07-27 07:40 UTC, merged