Docs: add documentation regards to the new prettify function
grafana/grafana pull request #36856
Opened 2021-07-16 13:46 UTC by olbo98

**What this PR does / why we need it**:
This PR adds a short paragraph regarding the new prettify function that was added in #36324. Please comment if there's anywhere else in the docs where this information should be added.

2021-07-16 13:59 UTC, ivanahuckova commented
@olbo98 There is a separate documentation for Logs Panel as well. 🙂

2021-07-16 14:25 UTC, olbo98 commented
> @olbo98 There is a separate documentation for Logs Panel as well. 🙂

Thanks @ivanahuckova i'll go ahead and change that as well! 👍

2021-07-22 18:51 UTC, achatterjee-grafana requested changes
Added review comments.

2021-07-22 18:51 UTC, achatterjee-grafana commented on docs/sources/explore/logs-integration.md
> +Set this to true if you want to pretty print all JSON logs. This will not affect logs in any format other than JSON.
```suggestion
Set this to `true` to pretty print all JSON logs. This setting does not affect logs in any format other than JSON.
```

2021-07-22 18:51 UTC, achatterjee-grafana commented on docs/sources/panels/visualizations/logs-panel.md
> +- **Prettify JSON -** Set this to true if you want to pretty print all JSON logs. This will not affect logs in any format other than JSON.
```suggestion
- **Prettify JSON -** Set this to `true` to pretty print all JSON logs. This setting does not affect logs in any format other than JSON.
```

2021-07-26 13:26 UTC, achatterjee-grafana approved these changes
LGTM

2021-07-26 14:20 UTC, merged