Refactor resample logic
grafana/grafana pull request #36937
Opened 2021-07-20 07:06 UTC by idafurjes

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #36627

**Special notes for your reviewer**:

2021-07-20 15:06 UTC, wbrowne requested changes
Think we're still missing some pieces here. I noticed that in the current code we only check for `fill` when `qm.Format == dataQueryFormatSeries` - see here https://github.com/grafana/grafana/blob/main/pkg/tsdb/sqleng/sql_engine.go#L280

That doesn't seem correct to me (unless we're filling elsewhere) - so I think that block should be moved outside of there.

At that point we're still left with different results:

7.5.x:

![Screenshot 2021-07-20 at 16 17 49](https://user-images.githubusercontent.com/1173299/126347372-9544f17e-7bf2-4d62-9ff1-566766887873.png)


Branch:

![image](https://user-images.githubusercontent.com/1173299/126347719-1eb4c0ab-a925-4363-afe1-ad6f110a0872.png)

Also note the different column numbers, I would have expected 3 in 7.5.x too 🤔

2021-07-27 11:45 UTC, ying-jeanne commented
tested with v8 and v7.5.0 now the behavior stay the same
<img width="1078" alt="Screenshot 2021-07-27 at 13 29 04" src="https://user-images.githubusercontent.com/74549700/127148252-0c53e398-ee2c-495e-acb0-24bab482284e.png">
<img width="785" alt="Screenshot 2021-07-27 at 13 43 55" src="https://user-images.githubusercontent.com/74549700/127148258-7165fd03-d719-4c74-9725-d684ee98ceff.png">

2021-07-27 12:05 UTC, wbrowne commented on pkg/tsdb/sqleng/resample.go
> +			previousTime := currentTime.Add(-qm.Interval)
![mind blown](https://media.giphy.com/media/fnpy7E5Sm1LSOvHvu8/giphy.gif)

Can we add a comment to this? 😅

2021-07-28 09:03 UTC, wbrowne commented
@ying-jeanne Still seems like something is missing:

Branch:
![Screenshot 2021-07-28 at 10 54 09](https://user-images.githubusercontent.com/1173299/127295272-86646a99-e241-414a-804e-28e88a99d5ff.png)

(the response data stays the same no matter the time range)

7.X:
![Screenshot 2021-07-28 at 11 01 51](https://user-images.githubusercontent.com/1173299/127295301-2543a962-babd-466d-9a20-0c292f2f37c7.png)

2021-07-28 14:00 UTC, ying-jeanne approved these changes

2021-07-28 16:24 UTC, wbrowne approved these changes
Tested and it LGTM!

2021-07-29 06:38 UTC, merged