PieChart: Make pie gradient more subtle to match other charts
grafana/grafana pull request #36961
Opened 2021-07-20 17:22 UTC by nikki-kiga

Closes #36141 

#### Before PieChart and BarChart
<img width="684" alt="beforeDarkChart" src="https://user-images.githubusercontent.com/42276368/126367242-90c5303c-e8ba-4aec-abc8-87d4480c2cae.png">

#### After PieChart and BarChart
<img width="693" alt="afterDarkChart" src="https://user-images.githubusercontent.com/42276368/126367170-aa5e663d-b8f5-4327-92ca-0229f6430990.png">

#### Before PieCharts in Light Mode
<img width="1333" alt="beforeLightPies" src="https://user-images.githubusercontent.com/42276368/126367250-451b039a-e5ee-45e4-af79-10c7280148b0.png">

#### After PieCharts in Light Mode
<img width="1359" alt="afterLightPies" src="https://user-images.githubusercontent.com/42276368/126367197-0aa22acf-a44c-4a61-83bf-5e9b23822c2e.png">

2021-07-20 17:30 UTC, ryantxu commented on public/app/plugins/panel/piechart/PieChart.tsx
> +import { darken, lighten } from '@grafana/data/src/themes/colorManipulator';
```suggestion
import { colorManipulator } from '@grafana/data';
```

and then use it as `colorManipulator.lighten|darken`

When working in the `public/app/plugins/...` it does not really matter, but we should use the standard export paths when possible

2021-07-20 17:47 UTC, ryantxu approved these changes

2021-07-20 18:56 UTC, torkelo requested changes
The gradient as is is based on gradient used in stat panels , so want to preserve it to maintain consistency with stat panel. Maybe it can also be tweaked? But the hue spin is an important aspect to the gradient

2021-07-20 18:57 UTC, torkelo commented
Maybe just reduce the hue spin a bit ?

2021-07-20 22:22 UTC, nikki-kiga commented
Reduced the spin  so that it still matches the stat panel:
<img width="691" alt="reducedSpin" src="https://user-images.githubusercontent.com/42276368/126392989-ead60db7-a771-434e-b598-b2ad1fb01dce.png">

2021-07-21 06:48 UTC, torkelo approved these changes

2021-07-21 15:50 UTC, merged