LDAP: validate organization role during parsing
grafana/grafana pull request #37188
Opened 2021-07-25 17:27 UTC by krzysdabro

**What this PR does / why we need it**:
This PR adds validation of the `org_role`.
It also fixes table on LDAP page to show organization name only when both org name and role are set.

| Before | After |
|--------|-------|
| ![Before](https://user-images.githubusercontent.com/7547604/126907740-50981267-53b6-4d09-ba42-30a0a6d4b3a2.png) | ![After](https://user-images.githubusercontent.com/7547604/126907748-89b987af-3b81-444e-825c-1721d5f49c27.png) |

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

2021-07-25 17:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=37188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=37188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=37188) it.</sub>

2022-04-23 12:54 UTC, krzysdabro commented
@zoltanbedi Same as #37189. Can you reopen and review this PR?

2022-04-25 07:38 UTC, zoltanbedi commented
I can reopen but can't review this. I'll ask the team who owns this.

2022-05-03 12:14 UTC, vtorosyan commented
@Jguer would you be able to support with reviewing the changes?

2022-05-03 14:43 UTC, Jguer commented
Hey @krzysdabro , I'm reviewing this PR now, sorry it's taken some time to get this reviewed :slightly_smiling_face:

2022-05-03 15:19 UTC, Jguer commented on pkg/services/ldap/settings.go
> +				return nil, fmt.Errorf("LDAP group mapping: organization role is required")
```suggestion
			if groupMap.OrgRole == "" && groupMap.IsGrafanaAdmin == nil {
				return nil, fmt.Errorf("LDAP group mapping: organization role or grafana admin status is required")
			}
```

2022-05-03 15:20 UTC, Jguer requested changes
```
[[servers.group_mappings]]
group_dn = "cn=admins,ou=groups,dc=grafana,dc=org"
grafana_admin = true

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
```

This fix breaks this seemingly valid scenario of assigning `grafana_admin` in one block but handling org_roles in another definiton (like a wildcard)

![image](https://user-images.githubusercontent.com/8071073/166481386-aeebc838-e4e9-4a82-ad8f-0d2cd99b2791.png)

The frontend fix is completely fine and justified

@krzysdabro can you remove the `org_role` validation (alternatively it can be changed to check for either the presence of org role of instance admin as I've suggested). After this has been cleared up it should be ok to merge :+1:

2022-05-03 22:17 UTC, krzysdabro commented
Thanks for the review @Jguer! I've updated the validation according to your suggestion.

2022-05-04 06:54 UTC, Jguer approved these changes
It should be fine now :+1: , tested locally with ldap debug and everything seems to be working correctly. 

Thanks @krzysdabro for the time spent on this :slightly_smiling_face:

2022-05-04 07:35 UTC, merged