Update overview.md
grafana/grafana pull request #37260
Opened 2021-07-27 14:10 UTC by Velociraptor85

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-07-27 14:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=37260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=37260) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=37260) it.</sub>

2021-07-27 14:22 UTC, achatterjee-grafana commented
Need dev review. Tagging @marefr for his input.

2021-07-28 07:05 UTC, dsotirakis requested changes
Same changes are needed in `grafana.md` as well.

2021-07-29 16:52 UTC, achatterjee-grafana approved these changes
Approved based on dev feedback.

2021-07-29 16:54 UTC, dsotirakis approved these changes

2021-07-29 17:03 UTC, merged