docs - update publishing details, add menuTitle instructions
grafana/grafana pull request #37441
Opened 2021-08-02 09:12 UTC by robbymilo

**What this PR does / why we need it**:

- Adds instructions for using the `menuTitle` front matter param
- Updates deploy information

2021-08-04 17:56 UTC, achatterjee-grafana approved these changes
lgtm

2021-08-09 12:16 UTC, osg-grafana requested changes

2021-08-09 12:16 UTC, osg-grafana commented on docs/README.md
> +Use the front matter param `menuTitle` to specify different menu text from the page title.
```suggestion
To specify different menu text from the page title, use the front matter parameter `menuTitle`.
```

2021-08-09 12:16 UTC, osg-grafana commented on docs/README.md
> +Use the front matter param `menuTitle` to specify different menu text from the page title.
Nit: Put the _what_ before _how_.

2021-08-09 12:16 UTC, osg-grafana commented on docs/README.md
> +* A PR targeting the `main` branch will sync to the `content/docs/grafana/next` directory in the website repo, and publish to https://grafana.com/docs/grafana/next/.
```suggestion
* A PR that targets the `main` branch syncs to the `content/docs/grafana/next` directory in the `website` repository, and publishes to `https://grafana.com/docs/grafana/next/`.
```

2021-08-09 12:16 UTC, osg-grafana commented on docs/README.md
> +* A PR targeting the latest/current release branch will sync to the `content/docs/grafana/latest` directory in the website repo, and publish to https://grafana.com/docs/grafana/latest/.
```suggestion
* A PR targeting the `latest/current` release branch syncs to the `content/docs/grafana/latest` directory in the `website` repository, and publishes to `https://grafana.com/docs/grafana/latest/`.
```

2021-08-09 12:16 UTC, osg-grafana commented on docs/README.md
> +Once the sync is complete, the website will automatically publish to production - no further action is needed.
```suggestion
After the sync is complete, the website will automatically publish to production.
```
What does "the website will automatically publish to production" mean? Where is that happens?

2021-08-10 14:44 UTC, osg-grafana approved these changes

2021-08-18 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=37441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=37441) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: robbymilo<br/>:x: daniellee<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=37441) it.</sub>

2021-08-18 17:59 UTC, merged