Variables: Fix issue with empty drop downs on navigation
grafana/grafana pull request #37776
Opened 2021-08-11 04:58 UTC by hugohaggmark

**What this PR does / why we need it**:
Before we migrated to React router we did a full page refresh whenever we clicked on a panel link to the same dashboard. That meant that we would follow the "usual" path of loading variables. Now with the React router in place we don't do a full page refresh we have introduced an alternative path through the variable system to change variables on the same page.

This PR introduces a `removed` prop to the each query result of `findTemplateVarChanges` function so we can distinguish between:

-  a variable being removed from the url 
- setting the variable value to `''`

This PR also removes all the previous code from #36521

**Which issue(s) this PR fixes**:
Fixes #35471
Fixes #33525

**Special notes for your reviewer**:
I used this dashboard.json while testing

```json

{
  "__inputs": [
    {
      "name": "DS_GDEV-TESTDATA",
      "label": "gdev-testdata",
      "description": "",
      "type": "datasource",
      "pluginId": "testdata",
      "pluginName": "TestData DB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.1.0-pre"
    },
    {
      "type": "panel",
      "id": "stat",
      "name": "Stat",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "testdata",
      "name": "TestData DB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "text",
      "name": "Text",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1628657306144,
  "links": [],
  "panels": [
    {
      "datasource": "${DS_GDEV-TESTDATA}",
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "links": [],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "links": [
        {
          "title": "Reset",
          "url": "http://localhost:3000/d/${__dashboard.uid}"
        },
        {
          "title": "Reset with title",
          "url": "http://localhost:3000/d/${__dashboard.uid}/variables-and-links?orgId=1"
        },
        {
          "title": "Set prod",
          "url": "http://localhost:3000/d/${__dashboard.uid}?var-query0="
        }
      ],
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "text": {},
        "textMode": "auto"
      },
      "pluginVersion": "8.1.0-pre",
      "title": "Panel Title",
      "type": "stat"
    },
    {
      "datasource": null,
      "description": "",
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 4,
      "options": {
        "content": "dashboard uid: `${__dashboard.uid}`\n\nquery0: `$query0`\n\nquery1: `$query1`",
        "mode": "markdown"
      },
      "pluginVersion": "8.1.0-pre",
      "title": "Panel Title",
      "type": "text"
    }
  ],
  "refresh": "",
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": [
            "test"
          ],
          "value": [
            "test"
          ]
        },
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": false,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": true,
            "text": "test",
            "value": "test"
          },
          {
            "selected": false,
            "text": "stage",
            "value": "stage"
          },
          {
            "selected": false,
            "text": "prod",
            "value": "prod"
          }
        ],
        "query": "test,stage,prod",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_GDEV-TESTDATA}",
        "definition": "*",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "query1",
        "options": [],
        "query": {
          "query": "*",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Variables and links",
  "uid": "cGgI4lGnz",
  "version": 9
}

```

2021-08-11 07:19 UTC, torkelo approved these changes
Looks great!

2021-08-11 11:32 UTC, tskarhed requested changes
This scenario shouldn't set the variable to `''`
https://user-images.githubusercontent.com/1438972/129021654-3535072f-7ab0-4e19-88dd-0ffbd27c4a73.mov

2021-08-11 12:50 UTC, hugohaggmark commented
@torkelo can you reproduce the behavior @tskarhed is describing?

2021-08-11 13:17 UTC, tskarhed commented
> @tskarhed can you share that dashboard you used?

It's the same one as mentioned in this PR

2021-08-11 13:29 UTC, torkelo commented
@hugohaggmark yes I can replicate that

2021-08-13 04:40 UTC, hugohaggmark commented
I managed to repro this now and looking into what is going on, thank you for all the help @tskarhed @torkelo

2021-08-13 04:53 UTC, hugohaggmark commented
Aaaargh, I just discovered what's going on seems we have a bug in export dashboard for sharing externally because the `current` value is nuked for query variables. I've opened a new issue https://github.com/grafana/grafana/issues/37862 about this.

Compare the original json above with the one below and you'll see that the original query variable  has

```json
"current": {},
```

and the new json has:

```json
"current": {
          "selected": true,
          "text": [
            "All"
          ],
          "value": [
            "$__all"
          ]
        },
```

Could you retry using this updated json instead (overwrite existing one), thank you 🙏 

```json

{
  "__inputs": [
    {
      "name": "DS_GDEV-TESTDATA",
      "label": "gdev-testdata",
      "description": "",
      "type": "datasource",
      "pluginId": "testdata",
      "pluginName": "TestData DB"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.1.0-pre"
    },
    {
      "type": "panel",
      "id": "stat",
      "name": "Stat",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "testdata",
      "name": "TestData DB",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "text",
      "name": "Text",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1628829742286,
  "links": [],
  "panels": [
    {
      "datasource": "${DS_GDEV-TESTDATA}",
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "links": [],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "links": [
        {
          "title": "Reset",
          "url": "http://localhost:3000/d/${__dashboard.uid}"
        },
        {
          "title": "Reset with title",
          "url": "http://localhost:3000/d/${__dashboard.uid}/variables-and-links?orgId=1"
        },
        {
          "title": "Set prod",
          "url": "http://localhost:3000/d/${__dashboard.uid}?var-query0="
        }
      ],
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "text": {},
        "textMode": "auto"
      },
      "pluginVersion": "8.1.0-pre",
      "title": "Panel Title",
      "type": "stat"
    },
    {
      "datasource": null,
      "description": "",
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 4,
      "options": {
        "content": "dashboard uid: `${__dashboard.uid}`\n\nquery0: `$query0`\n\nquery1: `$query1`",
        "mode": "markdown"
      },
      "pluginVersion": "8.1.0-pre",
      "title": "Panel Title",
      "type": "text"
    }
  ],
  "refresh": "",
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": [
            "test"
          ],
          "value": [
            "test"
          ]
        },
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": false,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": true,
            "text": "test",
            "value": "test"
          },
          {
            "selected": false,
            "text": "stage",
            "value": "stage"
          },
          {
            "selected": false,
            "text": "prod",
            "value": "prod"
          }
        ],
        "query": "test,stage,prod",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "allValue": null,
        "current": {
          "selected": true,
          "text": [
            "All"
          ],
          "value": [
            "$__all"
          ]
        },
        "datasource": "${DS_GDEV-TESTDATA}",
        "definition": "*",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "name": "query1",
        "options": [],
        "query": {
          "query": "*",
          "refId": "StandardVariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Variables and links",
  "uid": "fbrMLkn7k",
  "version": 3
}

```

2021-08-13 07:03 UTC, tskarhed approved these changes
Yes, this works now. I think it is a weird place to se the default value though, it would fit better in the template variable editor.

2021-08-13 07:10 UTC, merged