Transformations: add Fields to labels
grafana/grafana pull request #37987
Opened 2021-08-17 23:30 UTC by douglaswth

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-08-17 23:40 UTC, ryantxu commented
Hymm -- when limited to timeseries, maybe this is the same as "wide to long" that we currently support in the backend :thinking: 
https://github.com/grafana/grafana-plugin-sdk-go/blob/main/data/time_series.go#L381

cc @kylebrandt

2021-08-17 23:45 UTC, ryantxu commented
Rather than adding a new transformation, should this implement "wide to long" here:
https://github.com/grafana/grafana/blob/main/public/app/core/components/TransformersUI/prepareTimeSeries/prepareTimeSeries.ts#L24

2021-08-18 16:11 UTC, ryantxu commented
@douglaswth should we move this to the "prepare timeseries" transformer -- so that does "wide to long"?

2021-08-18 17:37 UTC, douglaswth commented
@ryantxu Okay, I'll take a stab at that after I finish up the other PR.

2021-08-18 20:38 UTC, achatterjee-grafana requested changes
Added doc review.

2021-08-18 20:38 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/fields-to-labels.md
> +This transformation allows you to split time series to multiple time series based on the values of selected fields which also become label values for their respective time series. This transformation
```suggestion
This transformation allows you to split time series data into multiple time series based on the values of selected fields. These selected fields become label values for their respective time series. Selecting multiple **Label fields** as label value results in as many time series as the unique label value combinations in your input data.
This behavior of this transformation is the opposite of [Labels to fields]({{< relref "./types-options.md#labels-to-fields" >}}) transform.
```

2021-08-18 20:38 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/fields-to-labels.md
> +You may select multiple **Label fields** which will be used as label values. As a result you will get as many time series as there are unique label field combinations coming from your input data.
remove

2021-08-18 20:38 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/fields-to-labels.md
> +title = "Fields to labels"
Do we need a new topic here? Let's add this information in the "Transformation types and options" topic, as a section after https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#labels-to-fields.

2021-08-18 20:38 UTC, achatterjee-grafana commented on docs/sources/panels/transformations/fields-to-labels.md
> +Given a query result with a single time series:
```suggestion
The following table shows the query result with a single time series:
```

2021-08-29 00:58 UTC, ryantxu commented
@douglaswth should we close this in favor of https://github.com/grafana/grafana/pull/38670

2021-08-31 00:01 UTC, douglaswth commented
Closing in favor of #38670.

2021-08-31 00:01 UTC, closed without merging