packaging: systemd unit hardening
grafana/grafana pull request #38109
Opened 2021-08-20 09:55 UTC by erdnaxe

**What this PR does / why we need it**:
This increases the isolation of Grafana service on systemd systems.

**Special notes for your reviewer**:
I only tested these changes on NixOS.

2021-08-20 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=38109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=38109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=38109) it.</sub>

2021-08-20 15:47 UTC, daniellee commented
@erdnaxe  thanks for submitting your changes upstream and helping us improve our packaging. 

Could you explain the changes and the consequences of them? Are these recommendations from `systemd-analyse security` tool?

2021-08-20 17:57 UTC, erdnaxe commented
> Could you explain the changes and the consequences of them? Are these recommendations from `systemd-analyse security` tool?

Yes, these are recommendations from `systemd-analyse security` tool. Some notes:

- Only Debian systemd unit was setting `UMask` (https://github.com/grafana/grafana/commit/9e21a089d29e7952a5fe0f2f9426c3fdfd76a20f), I also apply this to rpm.
- I enable `ProtectHome` because I believe Grafana should never look in `/home/`.
- I set `ProtectSystem` to `full` which make `/usr/`, `/etc/` and `/boot/` read-only. Setting it to `strict` might introduce regressions in Grafana as I believe there is a need to write in `/var/` and it is not trivial to list all authorized folders.
- I enable `ProtectKernel*` because I don't want Grafana to collect information about the kernel.
- `NoNewPrivileges`, `LockPersonality` and `RestrictSUIDSGID` (and maybe others) might introduce regressions if Grafana needs to call a setuid/setgid executable. For example if Grafana needs to call `sendmail` then it will fail with these options enabled.
- `RestrictAddressFamilies` is restricted to IPv4/IPv6 and Unix sockets as Grafana is a web server that might also talk to local sockets.
- `PrivateUsers` is going to create a new user namespace, which might introduce regressions. Maybe we can keep it disabled in a first time. For example it is impossible to make Grafana server listen on port 80 with this option as the `CAP_NET_BIND_SERVICE` capability will not work.

These parameters help to reduce the attack surface of an attacker that would have managed to get a RCE exploit in Grafana.

2021-08-30 14:56 UTC, kminehart requested changes
Just a couple comments. I think setting RestrictAddressFamilies multiple times may overwrite it. The docs aren't clear, it seems to suggest that only happens when you set it to "". Regardless I think it'd be clearer if it was all one line since there's no deny-list stuff happening.

Other than that, I think it looks good. All of the options make sense.

> NoNewPrivileges, LockPersonality and RestrictSUIDSGID (and maybe others) might introduce regressions if Grafana needs to call a setuid/setgid executable. For example if Grafana needs to call sendmail then it will fail with these options enabled

Grafana uses https://github.com/go-mail/mail/ to send emails, which according to their documentation:

> Gomail can only send emails using an SMTP server

So that shouldn't be a problem.

The one area I can see a regression happening is in plugins. It executes plugin processes using `os/exec`.This is done by github.com/hashicorp/go-plugin. From what I can tell, setuid/setgid is not used, and the plugin processes run as the grafana user.

2021-08-30 14:56 UTC, kminehart commented on packaging/deb/systemd/grafana-server.service
> +RestrictAddressFamilies=AF_UNIX
```suggestion
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
```

> Restricts the set of socket address families accessible to the processes of this unit. Takes "none", or a **space-separated list** of address family names to allow-list, such as AF_UNIX, AF_INET or AF_INET6

2021-08-30 14:56 UTC, kminehart commented on packaging/rpm/systemd/grafana-server.service
> +RestrictAddressFamilies=AF_UNIX
```suggestion
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
```

> Restricts the set of socket address families accessible to the processes of this unit. Takes "none", or a **space-separated list** of address family names to allow-list, such as AF_UNIX, AF_INET or AF_INET6

2021-08-31 18:43 UTC, kminehart commented
Looks like there's some CI trouble. I'll see if I can figure out why that's happening.

2021-08-31 22:12 UTC, erdnaxe commented
> Looks like there's some CI trouble. I'll see if I can figure out why that's happening. Is your branch / fork up to date with `main`?

I have just updated my branch with `main`.

2021-09-01 11:49 UTC, xlson commented
@marefr do you still want me to review this PR, it looks like @kminehart have taken ownership of it?

2021-09-01 15:45 UTC, kminehart commented
@xlson up to you. I'm going to test it locally real quick and it if it works I'll approve it. Feel free to add any feedback if there's anything that sticks out for you. Or if you'd like, I can hold off on my approval until you test it locally too?

2021-09-01 16:22 UTC, marefr commented
@xlson I added you because I was added as reviewer and don't have any knowledge of this :smile: As Kevin says, up to you.

2021-09-02 03:29 UTC, kminehart approved these changes

2021-09-02 07:50 UTC, xlson commented
@kminehart I'm good, feel free to merge :)

2021-09-02 12:36 UTC, merged

2021-09-21 20:10 UTC, stephenjamieson commented
Just FYI, this does break ubuntu 18.04 installs as it's sytemd is too old.

2021-09-22 08:18 UTC, marefr commented
@stephenjamieson can you please open a new bug report/issue describing the details? Thanks

2021-09-22 16:02 UTC, stephenjamieson commented
Unfortunately, instead of debugging further I upgraded to Ubuntu 20.04, so I do not have an environment to reproduce again.

2021-09-23 13:41 UTC, kminehart commented
I tested the 8.2.0-beta1 package on ubuntu 18.04 and it seems to be working fine. It complains about some unrecognized options but I haven't had any trouble getting Grafana to start.

2021-09-23 16:37 UTC, marefr commented
Related to #30755 ?

2021-10-07 17:55 UTC, kminehart commented
I think we will backport some additional documentation in the "What's new" page as well as additional instructions for systemd users installing via rpm and deb.

I did some reading and it seems like it is in our best interest to ensure that users explicitly grant the `CAP_NET_BIND_SERVICE` setting.

2021-10-08 13:45 UTC, kminehart commented
@fauust yes unfortunately Ubuntu does not have that syscall filter group.

@henriknoerr The line that is causing the image renderer plugin to fail is the `MemoryDenyWriteExecute=true` line.

For a quick workaround, view this comment: https://github.com/grafana/grafana/issues/40187#issuecomment-938629123

2021-10-08 14:14 UTC, kminehart commented
Yeah, @nsteinmetz setting that to true causes the imagerenderer to fail. `false` is the default behavior, effectively undoing the change that causes it to fail.

This is the PR that introduced the breaking change, not the PR that will fix the issue.

2021-10-09 15:54 UTC, kminehart commented
Yeah a PR was merged yesterday to revert that option. It looks like it only affected a small amount of plugins, specifically the Image Renderer plugin.

2023-07-18 13:06 UTC, ulidtko commented
This has broken listening on port 80 too.

A systemd override like below fixed it for me.
```
$ cat /etc/systemd/system/grafana-server.service.d/grant-cap-listen80.conf 
[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
```