Docs: clarify state of Unified Alerting
grafana/grafana pull request #38603
Opened 2021-08-26 14:57 UTC by armandgrillet

Following feedback in https://github.com/grafana/grafana/issues/38055#issuecomment-906163119, this PR clarifies the fact that unified alerting is currently an opt-in feature that still contains a few bugs.

2021-08-26 15:47 UTC, achatterjee-grafana reviewed
Added comment/review.

2021-08-26 17:53 UTC, achatterjee-grafana approved these changes

2021-08-27 11:21 UTC, pkolyvas requested changes
Looks good with 1 minor language change requested.

2021-08-27 11:22 UTC, pkolyvas approved these changes

2021-08-27 13:09 UTC, merged