OAuth: add docs for disableAutoLogin param
grafana/grafana pull request #38752
Opened 2021-08-31 12:40 UTC by mckn

This PR contains docs for #28357 - `disableAutoLogin` param. It is a new PR since the #28398 never got merged.

2021-08-31 15:25 UTC, achatterjee-grafana requested changes
Thank you @mckn for adding the doc content. Added review.

2021-08-31 15:25 UTC, achatterjee-grafana commented on docs/sources/auth/overview.md
> +> **Note:** `disableAutoLogin` parameter is available in Grafana 7.4+.
```suggestion
### Avoid OAuth login

To sign in with a username and password and avoid automatic OAuth login, add the `disableAutoLogin` parameter to your login URL. 

For example:  `grafana.example.com/login?disableAutoLogin` or `grafana.example.com/login?disableAutoLogin=true`
```

2021-08-31 15:25 UTC, achatterjee-grafana commented on docs/sources/auth/overview.md
> +> **Note:** `disableAutoLogin` parameter is available in Grafana 7.4+.
We do not need the note, as it is for an older version.

2021-09-06 10:03 UTC, alexanderzobnin approved these changes

2021-09-06 14:11 UTC, achatterjee-grafana approved these changes
Added one suggestion, otherwise LGTM

2021-09-06 14:11 UTC, achatterjee-grafana commented on docs/sources/auth/overview.md
> +### Avoid OAuth login
```suggestion
### Avoid automatic OAuth login
```

2021-09-06 14:55 UTC, merged