Alerting: UI standardization and fixes
grafana/grafana pull request #38770
Opened 2021-08-31 18:05 UTC by nathanrodman

**What this PR does / why we need it**:

This PR adds some new functionality and helps standardize the UI on a few pieces
- New: adds an expand/collapse feature for rule groups
- New: adds a filter for rule type on the rules page
- Uses dynamic table on the Silences page
- Adds placeholder text for inputs in the silences form

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-09-08 11:59 UTC, domasx2 reviewed
looks good, few nits though :)

2021-09-08 11:59 UTC, domasx2 commented on public/app/features/alerting/unified/components/amroutes/AmRootRouteForm.tsx
> +                      <Input {...field} className={styles.smallInput} invalid={invalid} placeholder={'Time'} />
Maybe put default as placeholder? See `description` above for what the default is

2021-09-20 08:43 UTC, peterholmberg commented on conf/provisioning/datasources/datasourceprovisioning.yaml
> +apiVersion: 1
is this file added on purpose?

2021-09-20 15:59 UTC, nathanrodman commented on conf/provisioning/datasources/datasourceprovisioning.yaml
> +apiVersion: 1
shoot, nope. That was my Friday brain

2021-09-22 12:43 UTC, peterholmberg requested changes
Looks good! Just one issue with expand all.

2021-09-22 20:32 UTC, nathanrodman commented on public/app/features/alerting/unified/RuleList.tsx
> +              </div>
@peterholmberg that sounds like a good compromise. I also was running into performance issues when trying to expand and collapse with 1500 rules or so.

2021-09-30 07:39 UTC, peterholmberg approved these changes
Nice ✌️

2021-10-01 22:15 UTC, merged