WIP service accounts
grafana/grafana pull request #38994
Opened 2021-09-08 13:58 UTC by donomii

**What this PR does / why we need it**:
This is a WIP branch for service accounts

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise/issues/1858

**Special notes for your reviewer**:

2021-09-09 06:21 UTC, hugohaggmark requested changes, later dismissed
Left some comments about the frontend parts and also the UI needs more polish. I didn't see the `New Service Account` checkbox 
![image](https://user-images.githubusercontent.com/562238/132633433-070f71d8-c65b-4cde-a6cd-109ea1cacf4e.png)

2021-09-09 06:21 UTC, hugohaggmark commented on public/app/features/api-keys/ApiKeysForm.tsx
> +                />
nit: maybe change to more explicit boolean
```suggestion
                <input
                  name="createServiceAccount"
                  type="checkbox"
                  checked={Boolean(createServiceAccount)}
                  onChange={onCreateServiceAccountChange}
                />
```

2021-09-09 06:21 UTC, hugohaggmark commented on public/app/features/api-keys/ApiKeysPage.tsx
> +    console.log(newApiKey);
Please remove

2021-09-09 20:19 UTC, kminehart commented
@donomii I'd be happy to review this! I think a lot of what I'm looking at (in the backend) has a lot of "todo" markers. Since this is WIP, when you're ready for a review on the Go stuff, feel free to ping me!

2021-09-10 08:10 UTC, donomii commented
Thanks!

I made a mistake with Github and didn’t set the PR to draft, so it added a lot of reviewers to the PR.  Sorry about that!

It will be a couple of weeks before it’s ready for review, I’ll let everyone know when it is finished. 

> On 9. Sep 2021, at 22:19, Kevin Minehart ***@***.***> wrote:
> 
> 
> @donomii <https://github.com/donomii> I'd be happy to review this! I think a lot of what I'm looking at (in the backend) has a lot of "todo" markers. Since this is WIP, when you're ready for a review on the Go stuff, feel free to ping me!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/grafana/grafana/pull/38994#issuecomment-916408355>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABP7X2E25V4TRJOMOE7JRD3UBEJGZANCNFSM5DUZN3LQ>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-10-08 14:51 UTC, eleijonmarck reviewed
just one missing err I think

2021-10-08 15:04 UTC, eleijonmarck submitted a review, later dismissed
![accounts](https://user-images.githubusercontent.com/7727602/136579896-12073ed1-198d-4ac3-8c9e-2a8e78a9d032.gif)

2021-10-08 15:22 UTC, sakjur submitted a review, later dismissed
I _think_ this breaks API keys from the perspective of the OSS codebase. Let's hold off on merging until that's cleared out.

I'm also a bit concerned about introducing panics, we have error handling in place in each of the places where panics are being introduced and I don't think any of them should be considered runtime errors, I think we should avoid panicking because we _can_ effectively recover from these errors. (see [effective go on panics](https://golang.org/doc/effective_go#panic))

2021-10-11 14:25 UTC, IevaVasiljeva reviewed
Some questions and suggestions in comments. Feel free to ignore the nits if they don't align with your personal preferences 🙂 

I'd also love to test the changes out - what's the best way to do it? Should I call the endpoints directly or is there a nice way to test them through the UI?

2021-10-12 13:05 UTC, donomii commented
> Some questions and suggestions in comments. Feel free to ignore the nits if they don't align with your personal preferences 🙂
> 
> I'd also love to test the changes out - what's the best way to do it? Should I call the endpoints directly or is there a nice way to test them through the UI?

I removed the UI for now, but I can add that back into another branch if you are interested.  For now you can call the API and set the CreateNewServiceAccount flag to true.  You can then look at the database table to see the new service account in the apikey table

2021-10-12 13:08 UTC, donomii commented
pkg/models/user.go
	Result           User
	IsServiceAccount bool
 
Member
@IevaVasiljeva IevaVasiljeva 23 hours ago
nit: is Result User separated from the rest of the fields because it is the result of the command? If so, should IsServiceAccount bool be defined together with the rest of the attributes higher up?

This is a left over habit I have from another programming language, where it is very important to always add new fields at the end of the structure.  But because we have a monolithic program, we can add them anywhere.

2021-10-15 09:53 UTC, marefr reviewed
Added some comments/questions. In general looks good, but feels like you've might added to much code in certain places that doesn't do anything and could affect existing functionality - please make sure to guard everywhere with the feature toggle if you want to keep things as is. 

Have #16424 been considered in relation to this?

2021-10-18 12:34 UTC, gamab reviewed
I just started looking at your work, so this is unrelated with the core work but I found some mismatches in the mock :slightly_smiling_face:

2021-10-20 12:14 UTC, eleijonmarck approved these changes
LGTM! looks amazing

2021-10-20 12:36 UTC, merged