Add context to star and stats
grafana/grafana pull request #39591
Opened 2021-09-23 14:24 UTC by idafurjes

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-09-27 16:59 UTC, marefr requested changes
Looks good. Had been easier to review by separating stats and star changes in two separate PRs, but my own personal preference. Stats-changes feels inconsistent compared with stars (using sqlstore vs global `x` variable), but maybe that causing too many changes? Planning to fix that later?

Think you might want to update this as well to use context:
https://github.com/grafana/grafana/blob/58d69d10555339d2363155b8cfd560ea79f18859/pkg/api/admin.go#L25

2021-09-27 16:59 UTC, marefr commented on pkg/services/sqlstore/star.go
> +func (ss *SQLStore) GetUserStars(ctx context.Context, query *models.GetUserStarsQuery) error {
Please use `ss.WithDbSession` below instead of `x`.

2021-09-27 16:59 UTC, marefr commented on pkg/services/sqlstore/star.go
> +	return ss.WithTransactionalDbSession(ctx, func(sess *DBSession) error {
Query only reads so no need for a transaction.

```suggestion
	return ss.WithDbSession(ctx, func(sess *DBSession) error {
```

2021-09-27 17:10 UTC, idafurjes commented
I felt the PR was a bit small, that's why I added the star

2021-09-27 17:43 UTC, marefr commented
> I felt the PR was a bit small, that's why I added the star

I guess everything is relative :smile: But in general, keeping it small could allow you to get a PR reviewed/merged faster and by that maybe feeling more productive, mark that as done and move on to a different task rather than having multiple semi-small/larger PRs going on in parallel. 

Let me know when this is ready for review - still a draft.

2021-09-28 14:59 UTC, marefr approved these changes
LGTM, but build seems to have failed. I restarted it

2021-09-28 15:54 UTC, merged