Plugins Catalog: Install and show the latest compatible version of a plugin
grafana/grafana pull request #41003
Opened 2021-10-27 15:44 UTC by jackw

**What this PR does / why we need it**:
PluginDetails page prefers the version from gcom (which is always the latest) over an installed plugin version. This is rather confusing for users as they cannot easily see which version they have installed. This PR addresses this by:

- [x] if the plugin is installed use it's version else fallback to the gcom version
- [x] make it clearer in version history tab which is the currently installed version 
- [x] show the latest compatible versions version number in the header if the plugin is not installed
- [x] use the `isCompatible` flag from the GCOM API to decide if a certain plugin version is compatible or not
- [x] add & update tests 

| Before | After |
| --- | --- |
| <img width="1679" alt="Screenshot 2021-10-27 at 17 26 35" src="https://user-images.githubusercontent.com/73201/139100093-d3f0839e-4969-474e-990d-daa14258b9a6.png"> | <img width="1679" alt="Screenshot 2021-10-27 at 17 26 02" src="https://user-images.githubusercontent.com/73201/139100076-9c9bcb8f-57e3-48b4-acba-2857c523abd1.png"> |

**Which issue(s) this PR fixes**:

Fixes #40803
Fixes #41157
Fixes #37934
Fixes #41173

**Special notes for your reviewer**:

2021-10-27 18:17 UTC, marefr requested changes
Works as expected on the plugin details page/versions tab. Great work :+1: 

However, on the plugin listings page it now incorrectly shows an update of the currently installed version (I have 4.1.5 installed):
![image](https://user-images.githubusercontent.com/1668778/139123449-7070b197-8f8b-4f07-9071-c7a21689daf8.png)

2021-11-04 16:17 UTC, marefr reviewed
Dependency information seems to always come from latest version at gcom?
![image](https://user-images.githubusercontent.com/1668778/140376569-c2ff2bc2-bef8-4050-bfcc-75f7c45f653f.png)

No version to upgrade to on hover (or did you decide to remove that?):
![image](https://user-images.githubusercontent.com/1668778/140376712-4be5325c-2c79-4fe3-be3a-9811f57680b3.png)

Other than this seems to work as expected. Great work :+1: There's one more thing, but same thing on main branch so I'll bring that up outside of this.

2021-11-05 14:18 UTC, leventebalogh commented on public/app/features/plugins/admin/components/PluginDetailsHeader.tsx
> +          {plugin.installedVersion ? <span>{plugin.installedVersion}</span> : <span>{plugin.latestVersion}</span>}
Fixed in [b15a74d](https://github.com/grafana/grafana/pull/41003/commits/b15a74ddd1cd943da6c965677fd28b73a804da76) 👍

2021-11-10 15:12 UTC, marefr approved these changes
LGTM. Quite a lot of moving pieces/changes and references multiple issues. Maybe a bit risky to put out all of them in a patch release. Something to keep in mind moving forward, trying to solve one problem at a time could reduce risk and make it easier to review/test and allow certain pieces to be released in a patch and some in the next major/minor version. This is my personal opinions.

2021-11-10 15:16 UTC, marefr commented
I would really like some others taking this for a test as well, since I'm not sure I've tested all possible combinations

2021-11-11 08:34 UTC, leventebalogh commented
> Something to keep in mind moving forward, trying to solve one problem at a time could reduce risk and make it easier to review/test and allow certain pieces to be released in a patch and some in the next major/minor version. This is my personal opinions.

I absolutely agree mate, this was not just hard to review (because touching so many things) but also quite hard to test out as there are so many edge cases. I think I have managed to cover all of them, but for sure it would be cool if someone else could test it as well.

2021-11-12 10:07 UTC, merged