Alerting: fix rule editor issues with Azure Monitor data source
grafana/grafana pull request #41317
Opened 2021-11-04 15:44 UTC by domasx2

Fixes two issues with Azure Monitor data source in rule editor page:
* Eval not working due to `queryType` not being set
* Visualization crashing due to incorrect default unit being used for threshold handle scale

TODO:
- [ ]  Prevent query from being run before it is fully configured. It appears in Azure Monitor you have to select from multiple - dropdowns before query becomes runnable. Right now it will try to eval a partial query while you're clicking dropdowns, spamming some annoying errors. There's a `DatasourceAPi.filter` method that can be used to determine if query is valid, but `AlertingQueryRunner` is not using it

2021-11-08 13:53 UTC, dprokop reviewed
Don't think I have enough background to verify everything in this PR, but the viz/unit thing looks good 👍

2021-11-08 13:53 UTC, dprokop commented on public/app/features/alerting/unified/components/rule-editor/VizWrapper.tsx
> +  return data.series[0]?.fields.find((field) => field.type === 'number')?.config.unit;
Looks good

2021-11-09 09:23 UTC, andresmgot approved these changes
Thanks for fixing this! Not very familiar with this code but approving just in case.

2021-11-09 09:23 UTC, andresmgot commented on public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx
> +          queryType: item.model.queryType ?? '',
would it make sense to simply "copy" the `model` in the root object? Something like:

```
return {
  ...item,
  ...item.model,
  refId: query.refId
```

Not sure if in the future another property apart from the `queryType` will be needed.

2021-11-15 14:45 UTC, gillesdemey requested changes

2021-11-15 14:45 UTC, gillesdemey commented on public/app/features/alerting/unified/state/AlertingQueryRunner.ts
> +  async run(queries: AlertQuery[]) {
I think we should check every invocation of `AlertingQueryRunner.run()` to make sure that when `dataSourceSrv.get` throws we are not crashing the interface or make sure we have a `try..catch` mechanism here.

2021-11-15 14:49 UTC, gillesdemey commented on public/app/features/alerting/unified/state/AlertingQueryRunner.ts
> +      if (query.datasourceUid !== ExpressionDatasourceUID) {
I think we can use `!isExpressionQuery` here as that will also check for `__expr__` types?

2021-11-16 10:47 UTC, gillesdemey approved these changes

2021-11-16 13:02 UTC, merged