Add encryption algorithm to Enterprise config
grafana/grafana pull request #41412
Opened 2021-11-08 14:27 UTC by mjseaman

**What this PR does / why we need it**:
Adds docs for the existing feature: update the encryption algorithm.

**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana-enterprise/issues/2196

Fixes #

**Special notes for your reviewer**:

2021-11-08 14:51 UTC, joanlopez approved these changes
Great! 🔥

2021-11-09 11:56 UTC, undef1nd approved these changes

2021-11-09 12:43 UTC, osg-grafana commented on docs/sources/enterprise/enterprise-configuration.md
> +Encryption algorithm used to encrypt secrets stored in the database and cookies. Possible values are `aes-cfb` (default) and `aes-gcm`. AES-CFB refers to Advanced Encryption Standard in Cipher FeedBa
```suggestion
Encryption algorithm used to encrypt secrets stored in the database and cookies. Possible values are `aes-cfb` (default) and `aes-gcm`. AES-CFB stands for _Advanced Encryption Standard_ in _cipher feedback_ mode, and AES-GCM stands for _Advanced Encryption Standard_ in _Galois/Counter Mode_.
```

2021-11-09 12:44 UTC, osg-grafana requested changes
Define acronyms accurately.

2021-11-18 07:48 UTC, osg-grafana approved these changes

2021-11-18 07:48 UTC, merged