Alerting: rewire expression references when queries are updated
grafana/grafana pull request #41478
Opened 2021-11-09 13:56 UTC by gillesdemey

**What this PR does / why we need it**:

When renaming queries this PR will rewire the references properly for expressions.

**Which issue(s) this PR fixes**:

Fixes #41477

2021-11-09 14:22 UTC, kaydelaney reviewed
Nice! Maybe `queriesWithUpdatedReferences` could be factored out as a plain function and then have a test written for it to validate its behavior?

2021-11-09 14:30 UTC, peterholmberg requested changes
Super nice, but we should have a test for the function.

2021-11-09 14:30 UTC, peterholmberg commented on public/app/features/alerting/unified/components/rule-editor/QueryRows.tsx
> +  queriesWithUpdatedReferences = (queries: AlertQuery[], previousRefId: string, newRefId: string) => {
I feel as we should have a test for this.

2021-11-09 17:12 UTC, gillesdemey commented
added a unit test for `queriesWithUpdatedReferences` and abstracted that into a separate function living under `utils.ts`

2021-11-17 10:58 UTC, peterholmberg approved these changes
Woo nice

2021-11-17 11:56 UTC, merged