Toolkit: Plugin version accessible from plugin code
grafana/grafana pull request #41581
Opened 2021-11-11 04:41 UTC by kostrse

**What this PR does / why we need it**:

It's useful to have access to the plugin version from JavaScript code for things like for telemetry, UI etc.

The toolkit uses Webpack, and it's common to use Webpack to inject values into code at compile time (such as version, environment, feature flags, environment-specific endpoints etc.).

This PR updates Webpack configuration to pass version value via fake environment variable `process.env.VERSION`:

```ts
const pluginVersion = process.env.VERSION;

return (
  <p>{pluginVersion}</p>
)
```

**Special notes for your reviewer**:

`process.env.VERSION` was chosen because use of `process.env` is most common for such purposes: it's global object, not used by browsers and TypeScript has type definitions for it.

2021-11-17 09:26 UTC, mckn approved these changes
LGTM!

2021-11-17 09:39 UTC, mckn requested changes
After some more thought I'm a bit confused why this is needed. What are you trying to accomplish?

You can already get the plugin version by just importing the plugin.json from your plugin. You should get the version from the `plugin.json` in favor of the `package.json`.

Also - sine you can have multiple plugins this can't be defined in a single global variable.

2021-12-23 02:35 UTC, kostrse commented
> You can already get the plugin version by just importing the plugin.json from your plugin. You should get the version from the `plugin.json` in favor of the `package.json`.

I'm aware of this option but I don't like the fact that it bundles the whole JSON (usually a large one) just to get a single version value while it's already known at compile time.
Passing it via environment variable is clean and unobtrusive way to do it.

Plus I'm not sure whether it even works when `"version": "%VERSION%"` and I'm not sure whether it's desirable to expose  plugin.json to frontend while it's normally accessible only form backend.

2021-12-28 09:27 UTC, mckn commented
> I'm aware of this option but I don't like the fact that it bundles the whole JSON (usually a large one) just to get a single version value while it's already known at compile time. 

This is a valid argument and we can fetch it from the `grafanaBootData` instead. So maybe provide a utility function to make it easier to fetch it would be the best approach?

> Passing it via environment variable is clean and unobtrusive way to do it.

Since the frontend code is running in the browser this isn't really applicable. If it where a node processes then it would make sense. We have a global `grafanaBootData` object that can be used.
 
> Plus I'm not sure whether it even works when `"version": "%VERSION%"` and I'm not sure whether it's always desirable to expose plugin.json to frontend while it's normally accessible only form backend.

Valid point, the parts that is safe to expose is already exposed via the `grafanaBootData`.

2021-12-28 09:36 UTC, mckn commented
Maybe a `pluginMetaSrv` that could expose a function called `getVersion(pluginId: string): string | undefined`.

2022-03-03 04:38 UTC, kostrse commented
> Maybe a `pluginMetaSrv` that could expose a function called `getVersion(pluginId: string): string | undefined`.

@mckn this PR proposes stamping the version at compile time, your proposal is having version available at runtime.

I don't know which solution is better, yours just makes this PR irrelevant.

The difference is this PR is a one liner and ready to merge, runtime solution will require more involved implementation in Plugin SDK which I'm not familiar with.

2022-03-09 12:37 UTC, mckn commented
> > Maybe a `pluginMetaSrv` that could expose a function called `getVersion(pluginId: string): string | undefined`.
> 
> @mckn this PR proposes stamping of the version at compile time, your proposal is having version available at runtime.
> 
> Both solutions would work, yours just makes this PR irrelevant.
> 
> The difference is this PR is a one liner and ready to merge, runtime solution will require more involved implementation in Plugin SDK which I'm not familiar with.

We can do it compile time (and I'm fine with that) but then I would prefer to assign it to some global variable on window instead of using `process.env` which is a `nodejs` concept.

2022-03-10 04:27 UTC, kostrse commented
> > > Maybe a `pluginMetaSrv` that could expose a function called `getVersion(pluginId: string): string | undefined`.
> > 
> > 
> > @mckn this PR proposes stamping of the version at compile time, your proposal is having version available at runtime.
> > Both solutions would work, yours just makes this PR irrelevant.
> > The difference is this PR is a one liner and ready to merge, runtime solution will require more involved implementation in Plugin SDK which I'm not familiar with.
> 
> We can do it compile time (and I'm fine with that) but then I would prefer to assign it to some global variable on window instead of using `process.env` which is a `nodejs` concept.

It can be any variable, I will just explain the reasoning behind `process.env`.

`process.env` is popular in React frontend community because, as you pointed out, in browser it doesn't mean anything, Browser doesn't have it set to anything but TypeScript has builtin typings for it, so it's strongly typed, you don't need to define dedicated variable/interface yourself, and you don't risk to clash with other global variables. It's just semantic convention to have code look like it would be in nodejs. rather than real thing.

Example from React:
https://create-react-app.dev/docs/adding-custom-environment-variables/

2022-04-25 02:13 UTC, closed without merging