Access control: Load permissions from memory and database
grafana/grafana pull request #42080
Opened 2021-11-22 14:03 UTC by kalleep

Now that we have the access control database in oss we need to load permissions from both in memory structures (fixed roles) and from the database.

This pr update GetUserPermissions to load permissions from both.

2021-11-23 08:02 UTC, gamab approved these changes
LGTM!

What do you think about adding a test to `GetUserPermissions` with permissions coming from a mock `PermissionsProvider`?

2021-11-23 08:02 UTC, gamab commented on pkg/services/accesscontrol/ossaccesscontrol/ossaccesscontrol.go
> +	permissions := ac.getFixedPermissions(ctx, user)
Nit. you could provide the user's built-in role to call `ac.GetUserBuiltInRoles` once. (however that's not an expensive call)

2021-11-23 10:11 UTC, sakjur requested changes
Talked with @kalleep yesterday, let's wait with this for a bit 🙂

2021-12-15 17:00 UTC, IevaVasiljeva approved these changes
LGTM, but I couldn't make it run due to wire failing to initialize dependencies (I think permission provider is required before it's added). But I might have done something wrong there.

2021-12-15 17:00 UTC, IevaVasiljeva commented on pkg/api/common_test.go
> +	acdb "github.com/grafana/grafana/pkg/services/accesscontrol/database"
nit: we can maybe call this `accesscontroldb` instead to make it a bit more readable and consistent with how we import `accesscontrolmock` dependency?

2022-01-28 07:49 UTC, gamab commented on pkg/services/accesscontrol/ossaccesscontrol/ossaccesscontrol.go
> +			ac.log.Debug("the has already been stored in a greater version, skipping registration", "role", role.Name)
```suggestion
			ac.log.Debug("the role has already been stored in a greater version, skipping registration", "role", role.Name)
```

2022-01-28 08:17 UTC, gamab approved these changes
LGTM

2022-01-28 14:10 UTC, sakjur approved these changes
I'm happy with the changes here :+1:

2022-01-28 15:11 UTC, merged