Alerting: add settings for peer reconnection in HA mode
grafana/grafana pull request #42300
Opened 2021-11-25 13:49 UTC by JohnnyQQQQ

**What this PR does / why we need it**: 
This PR adds the ability to configure the peer reconnection settings. One can set the desired timeout and reconnect interval. This is very useful when running in an ephemeral environment like Kubernetes, where an ungraceful shutdown might happen, and you don't want to try old peers for 6 hours (which is the default). 

**Special notes for your reviewer**: This is no breaking change, as the default values stay the same.

2021-11-25 14:16 UTC, gerobinson approved these changes

2021-11-25 15:03 UTC, gotjosh requested changes
Code changes look good, I have questions about the documentation but before we delve into that... I'm always sceptical of opening up too many options to our users because we're married to them forever when that happens. 

Just to open the conversation, of "can we do it with better defaults?" do you know:

- What would these values look like when using things like deployments in k8s?
- Would the values for ^ not work for non-k8s deployments?
- If we can find answers to the two previous questions we might not need to expose these to our users and just use those as our defaults.

2021-11-25 16:27 UTC, JohnnyQQQQ commented
> Code changes look good, I have questions about the documentation but before we delve into that... I'm always sceptical of opening up too many options to our users because we're married to them forever when that happens.
> 
> Just to open the conversation, of "can we do it with better defaults?" do you know:
> 
> * What would these values look like when using things like deployments in k8s?
> * Would the values for ^ not work for non-k8s deployments?
> * If we can find answers to the two previous questions we might not need to expose these to our users and just use those as our defaults.

I think there is no way around this. 

We as a project don't own the infrastructure we are executed on. Environments and networks are widely different, so is also the way folks will do service discovery. You might have a setup with two Raspberry Pi in a local network, but you might also have a setup that spans more than one datacenter or continent using federation. So the values that would make sense vary a lot. For now, one could tweak the gossip interval but not the peer timeouts and intervals - which is a kinda unsatisfying state.

I also don't think that we are married to it. If we drop the gossip protocol, we will also drop all the surrounding configuration.

Looping back to your question:

In my personal Kubernetes setup I have 60s for the timeout and 20s for the interval, so after a loss it will be tested three times – but as mentioned above, this configuration will never be one-size fits all and I really don't see any downside in exposing this to enable a better use of such a great feature.

2021-11-26 15:03 UTC, JohnnyQQQQ commented
We want to get a better understanding of the defaults before moving on, i.e. in which case 6 hours is a sensible default value. After that, we will reevaluate our defaults.

2021-11-26 15:03 UTC, closed without merging