[v7.5.x] Settings: Fix handling
grafana/grafana pull request #42536
Opened 2021-11-30 16:19 UTC by joanlopez

**Special notes for your reviewer**:

Manual backport of https://github.com/grafana/grafana/pull/42497#issuecomment-982501981.

I did some tests and it seems to be working, but feel free to test it yourself as well.

2021-12-01 13:04 UTC, joanlopez commented on pkg/setting/setting_test.go
> -
As part of security fix we are redacting all URLs and not only database one, so it no longer makes sense to do this kind of handling specifically for database URL, I think.

2021-12-01 13:07 UTC, joanlopez commented on pkg/setting/setting_test.go
> +			So(appliedEnvOverrides, ShouldContain, "GF_DATABASE_URL=mysql://user:xxxxx@localhost:3306/database")
For the sake of security (and some other reasons), now we rely on Go standard library function to redact URLs, which uses `xxxxx` as placeholder, which I guess it's fine.

2021-12-02 10:59 UTC, undef1nd approved these changes
I've tested on a few settings and seems to work fine.

2022-01-28 14:46 UTC, xlson requested changes
I looked over my outstanding PR reviews and found this oldie. Seems to me that it still would be a good idea to try to get this merged. But, before doing that we should remove the .drone changes, I don't think there's a reason to update the pipeline scripts as a part of the backport, right?

2022-01-28 14:48 UTC, xlson approved these changes

2022-02-21 13:29 UTC, merged