Alerting: Add label and state filters to alert instance components
grafana/grafana pull request #42550
Opened 2021-11-30 23:41 UTC by JacobsonMT

**What this PR does / why we need it**:

Adds label and state filtering to all components that use AlertInstancesTable, this includes:

- Alert List panel (this panel was standardized to use AlertInstancesTable)
- Alerting / View rule
- Alerting / Alert rules
- Panel-specific alert tab

Also modifies RadioButton with optional onClick to allow for RadioButtonGroup toggling on second click

**Screenshots / gifs**:

![Peek 2021-11-30 18-01](https://user-images.githubusercontent.com/8484471/144144019-ac633d0f-c23e-4860-b620-6aef2238e87a.gif)

![Peek 2021-11-30 18-13](https://user-images.githubusercontent.com/8484471/144144024-18cd5864-b983-48cc-8941-41ef0b4802da.gif)

![Screenshot from 2021-11-30 18-28-49](https://user-images.githubusercontent.com/8484471/144145287-b7522149-b0ab-46ad-a78a-3587f0548662.png)

**Which issue(s) this PR fixes**:

Fixes #36048
Relates to #35720

2021-11-30 23:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=42550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=42550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=42550) it.</sub>

2021-11-30 23:53 UTC, JohnnyQQQQ commented
@JacobsonMT thanks for your first contribution to Grafana and welcome to the community 🚀   I did approve the drone build stage and added some folks that will review this frontend change.

2021-12-02 16:47 UTC, gillesdemey requested changes
Since this PR is quite large I'm releasing my first batch of comments; some of these are not blockers and can be improved upon in a follow-up PR.

A few blocking issues though, those are not preceded by `nit:` 💡

2021-12-02 16:53 UTC, JacobsonMT commented on public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.tsx
> +  if (!alerts.length) {
Good catch, thanks! That's what I get for not retesting after fixing pre-commit errors :)

2021-12-02 17:06 UTC, JacobsonMT commented on public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.tsx
> -  if (!isAlertingRule(promRule) || !promRule.alerts?.length) {
So, for recording rules we should not display the table/filters at all (return null)?

2021-12-02 19:33 UTC, gillesdemey commented on public/app/features/alerting/unified/components/rules/RuleDetailsMatchingInstances.tsx
> -  if (!isAlertingRule(promRule) || !promRule.alerts?.length) {
Yep exactly, that is also why the `RuleDetailsMatchingInstances` was typed as `JSX.Element | null` :v:

2021-12-02 19:37 UTC, gillesdemey commented on public/app/features/alerting/unified/utils/alertmanager.ts
> +  const matcherRegExp = /\b([\w.-]+)(=~|!=|!~|=(?="?\w))"?([^"\n,]*)"?/g;
Awesome! TIL that the `.` is literal in a character class!

As far as suggestions go I can think of the underscore (`_`) character if we aren't including that one yet, that should do it for now :)

2021-12-02 21:11 UTC, JacobsonMT commented on packages/grafana-ui/src/components/Forms/RadioButtonGroup/RadioButtonGroup.tsx
> +  onClick,
Implying adding this new "unselect an item by re-clicking it" as the default for RadioButtonGroup? I think it's a good idea, I mostly did it this way as I was a bit wary of modifying the default functionality of something used in so many places of the UI.

I'll give it a shot and see if I notice any strangeness as a result.

2021-12-02 21:28 UTC, JacobsonMT commented
Addressed all comments except for "onUnselect" as I'd like to test it a bit more locally

2021-12-13 10:36 UTC, gillesdemey approved these changes
Amazing first-time contribution, LGTM! :shipit:

2021-12-13 10:54 UTC, merged