WIP
grafana/grafana pull request #42659
Opened 2021-12-02 14:29 UTC by donomii

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1547

**Special notes for your reviewer**:

2021-12-14 11:24 UTC, eleijonmarck commented
I think these roles should be registered in the `/grafana/pkg/services/accesscontrol/roles.go`

2021-12-14 11:32 UTC, eleijonmarck commented on pkg/services/accesscontrol/ossaccesscontrol/ossaccesscontrol.go
> +	accesscontrol.InitPerms()
yea, but I am not sure that this is correct to be here

2021-12-14 11:45 UTC, eleijonmarck commented on pkg/services/accesscontrol/ossaccesscontrol/ossaccesscontrol.go
> +	accesscontrol.InitPerms()
this is just that I think something big is happening because this is initiated inside of the serviceProvider

2021-12-14 11:47 UTC, eleijonmarck approved these changes
nit: if possible, refactor out the initPerm() somewhere

personal preferences, as I thought it did a lot more than a function call away

2021-12-15 10:01 UTC, kalleep commented on pkg/services/serviceaccounts/manager/roles.go
> +			Description: "Gives access to list apikeys.",
We want to add a display name and group to each role. Also lets loop in @osg-grafana for the names / descriptions

2021-12-15 10:43 UTC, donomii commented on pkg/services/serviceaccounts/manager/roles.go
> +	ActionApikeyAddAdditionalEv = accesscontrol.EvalPermission("apikey:addadditional")
These are actions, not scopes

2021-12-15 11:02 UTC, kalleep commented on pkg/services/serviceaccounts/manager/roles.go
> +	ActionApikeyAddAdditionalEv = accesscontrol.EvalPermission("apikey:addadditional")
Well these are evaluators, and atm we only evaluate that a user has the required action?

2021-12-15 11:19 UTC, donomii commented on pkg/services/serviceaccounts/manager/roles.go
> +	ActionApikeyAddAdditionalEv = accesscontrol.EvalPermission("apikey:addadditional")
good point

2021-12-15 14:18 UTC, eleijonmarck requested changes
stale, needs to be not draft

2022-01-04 11:58 UTC, donomii commented on pkg/services/serviceaccounts/manager/roles.go
> +	ActionApikeyAddAdditionalEv accesscontrol.Evaluator
Let's do this in another ticket.

2022-01-04 11:58 UTC, eleijonmarck commented on pkg/services/serviceaccounts/manager/roles.go
> +	apikeyAdminRead = "fixed:apikey:admin:read"
edit - writer
read - reader

2022-01-04 11:59 UTC, eleijonmarck commented on pkg/services/serviceaccounts/manager/roles.go
> +	apikeyAdminRead = "fixed:apikey:admin:read"
```
	apikeyWriter = "fixed:apikey:writer"
	apikeyReader = "fixed:apikey:reader"
```

2022-01-04 14:28 UTC, eleijonmarck approved these changes
nit: is there a reason for the apikeyWriter and apikeyReader to not be public? 🤔

2022-01-04 14:37 UTC, merged