Variables: Adds user interaction reports
grafana/grafana pull request #42802
Opened 2021-12-07 05:34 UTC by hugohaggmark

**What this PR does / why we need it**:
This PR adds reporting for some variable related user interactions. One of the goals with this is to figure out how much the variable inspection is used.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2021-12-07 14:47 UTC, joshhunt approved these changes
:]

2021-12-07 15:27 UTC, ashharrison90 requested changes
lgtm, just needs the imports fixing 🙌

2021-12-07 15:27 UTC, ashharrison90 commented on public/app/features/variables/editor/VariableEditorList.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
`@grafana/runtime`

2021-12-07 15:27 UTC, ashharrison90 commented on public/app/features/variables/editor/VariableEditorListRow.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
`@grafana/runtime`

2021-12-07 15:27 UTC, ashharrison90 commented on public/app/features/variables/inspect/VariableUsagesButton.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
`@grafana/runtime`

2021-12-07 15:27 UTC, ashharrison90 commented on public/app/features/variables/inspect/VariablesDependenciesButton.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
`@grafana/runtime`

2021-12-08 04:59 UTC, hugohaggmark commented
Thanks for the feedback @ashharrison90, so sorry for the import mess 🙈

2021-12-08 07:10 UTC, hugohaggmark commented on public/app/features/variables/editor/VariableEditorList.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
Fixed!

2021-12-08 07:10 UTC, hugohaggmark commented on public/app/features/variables/editor/VariableEditorListRow.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
Fixed!

2021-12-08 07:10 UTC, hugohaggmark commented on public/app/features/variables/inspect/VariableUsagesButton.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
Fixed!

2021-12-08 07:10 UTC, hugohaggmark commented on public/app/features/variables/inspect/VariablesDependenciesButton.tsx
> +import { reportInteraction } from '../../../../../packages/grafana-runtime';
Fixed!

2021-12-08 08:58 UTC, ashharrison90 approved these changes
no worries. lgtm! 🙌

2021-12-08 09:11 UTC, merged