fix plugin sign
grafana/grafana pull request #43014
Opened 2021-12-13 07:03 UTC by dessen-xu

**What this PR does / why we need it**:

The dependency of @grafana/toolkit commander was updated to 8.x, the cmd changed.

**Which issue(s) this PR fixes**:

https://github.com/grafana/grafana/issues/42860

Fixes #

**Special notes for your reviewer**:

2021-12-13 14:43 UTC, mckn requested changes
This is great! Thanks for opening this. However the `<urls...>` added support for using the toolkit the following ways:

`grafana-toolkit plugin:sign --signatureType private --rootUrls https://example.com https://plugin.example.com`

`grafana-toolkit plugin:sign --signatureType private --rootUrls https://example.com --rootUrls https://plugin.example.com`

So if we remove the `<urls...>` it will break for everyone using it that way. Instead I suggested to add a custom option processor to support all scenarios mentioned above but also the:

`grafana-toolkit plugin:sign --signatureType private --rootUrls https://example.com,https://plugin.example.com`

2021-12-13 14:43 UTC, mckn commented on packages/grafana-toolkit/src/cli/index.ts
> +    .option('--rootUrls <type>', 'Root URLs')
```suggestion
    .option('--rootUrls <url...>', 'Root URLs', function(url: string, urls: string[]) {
      if (typeof url !== 'string') {
        return urls;
      } 
      const parts = url.split(',');
      urls.push(...parts);
      return urls;
    }, [])
```

2021-12-14 00:03 UTC, dessen-xu commented
I get it, thanks

2021-12-14 01:45 UTC, dessen-xu commented
I get it.

2021-12-14 05:03 UTC, dessen-xu commented
done

2021-12-14 10:41 UTC, mckn approved these changes
LGTM! Great work.

2021-12-14 10:43 UTC, merged

2021-12-14 11:01 UTC, dessen-xu commented
Thank you very much