Alerting: Add filters for AlertList panel
grafana/grafana pull request #43130
Opened 2021-12-15 00:44 UTC by nathanrodman

**What this PR does / why we need it**:

- Adds datasource filtering
- Converges two different alert state filters for Grafana Managed and Prometheus alert states
- Refactors filtering by label.

**Which issue(s) this PR fixes**:

Fixes #35720 

**Special notes for your reviewer**:

2021-12-15 16:37 UTC, gillesdemey commented
I just tested it locally and it seems like `dataSourceName` is always defined as `grafana` for grafana managed alerts.

Can you double check and confirm if it does correct filtering for `grafana managed` datasources?

2021-12-15 16:37 UTC, gillesdemey requested changes

2021-12-15 16:58 UTC, nathanrodman commented on public/app/plugins/panel/alertlist/AlertInstances.tsx
> +        (options.stateFilter.pending && alert.state === PromAlertingRuleState.Pending)
Yes that appears to be a holdover that can be removed

2021-12-15 18:04 UTC, nathanrodman commented
> I just tested it locally and it seems like `dataSourceName` is always defined as `grafana` for grafana managed alerts.
> 
> Can you double check and confirm if it does correct filtering for `grafana managed` datasources?

@gillesdemey You are correct. I'm wondering given that whether it should just be limited to Prometheus/Loki datasources for the datasource filter? The `<DatasourcePicker>` has a `type` prop where you can pass in a list of datasource types. So instead of limiting it to the datasources that support alerting, it could just support ds with type prometheus, loki, or grafana.

2021-12-16 12:56 UTC, gillesdemey commented
>  I'm wondering given that whether it should just be limited to Prometheus/Loki datasources for the datasource filter? 

I think that would be the best way to go forward here and get unstuck 👍

2021-12-16 13:08 UTC, gillesdemey approved these changes

2021-12-16 13:08 UTC, gillesdemey commented
Awesome, Nathan! 🚀

2021-12-16 18:17 UTC, merged