Chore: Add some e2e tests for repeating behaviour
grafana/grafana pull request #43457
Opened 2021-12-22 10:38 UTC by ashharrison90

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

For #42512

**Special notes for your reviewer**:

2021-12-22 10:41 UTC, hugohaggmark approved these changes
Hurray for the Mob 🔱

2021-12-22 14:49 UTC, sdboyer commented
I'm on vacation this week and next.

If this is what I think it is (we didn't update the schema when we made data sources into objects), it's going to take a bit of doing to get it done. If this is blocking something critical, I can see if I can find some time before the new year.

2021-12-22 14:51 UTC, ashharrison90 commented
@sdboyer no worries, it's not critical. 

_some_ errors are related to the data source object thing. but there are others that are unrelated (null values, it not recognising `timeseries`/`repeats`/`collapsed`). 🤷 

enjoy your holidays! 🎅

2021-12-22 14:52 UTC, hugohaggmark commented
Yeah enjoy your holidays @sdboyer, sorry for ping.

2021-12-22 19:12 UTC, sdboyer commented
no worries, I'll get on it when I get back then.

def concerning that stripnulls mangled it - if we've found a case where we're expecting explicit null values, we'll have more to unravel.

but, later!

2022-01-10 16:11 UTC, ashharrison90 commented
@sdboyer lemme know if you wanna pair up on looking into this 🙂

2022-01-11 15:28 UTC, sdboyer requested changes
Wonderful! thanks so much for pairing on this, and for updating the other dashboards we'd previously been testing.

Only one thing - we do need the changes to the Go test you made to only test `schemaVersion` > 32. It's unlikely we end up creating any in the future, but there's no sense in leaving ourselves a timebomb in case it does happen, or otherwise leaving that test in a state that's divergent from reality.

2022-01-11 15:28 UTC, sdboyer commented on scripts/stripnulls.sh
> +FILES=$(grep -rl '"schemaVersion": 3[01234]' devenv)
```suggestion
FILES=$(grep -rl '"schemaVersion": 3[34]' devenv)
```

2022-01-11 15:28 UTC, sdboyer commented on scripts/stripnulls.sh
> +FILES=$(grep -rl '"schemaVersion": 3[01234]' devenv)
With the changes to the schema, we're not actually supporting those older versions anymore, so might as well narrow the margin for error with the hacky shell script.

2022-01-11 16:35 UTC, sdboyer approved these changes
looks good, thank you!

2022-01-11 16:47 UTC, merged

2022-01-12 09:43 UTC, ashharrison90 commented
for future reference: the cue schema changes were fixed with a combination of running the tests using `go test -run ^TestDevenvDashboardValidity$ github.com/grafana/grafana/pkg/schema/load -count=1 -v`, and the `stripnulls` script