Login: Fix popup message to state account was blocked
grafana/grafana pull request #43578
Opened 2021-12-29 14:04 UTC by axelavargas

**What this PR does / why we need it**:

The popup message saying username or password is incorrect was being sent even when the account of the user was blocked. 

I added some conditions to make it more specific.

Before
![BeforeErrorNotCorrect](https://user-images.githubusercontent.com/239999/147679504-6c2881d7-9752-4df4-a0ba-b7e22fd4ca70.png)

After
![AfterRightMessage](https://user-images.githubusercontent.com/239999/147679581-07e65b92-6dde-4d28-8bbe-f2dc533a102a.png)

**Which issue(s) this PR fixes**:

Fixes #43531

**Special notes for your reviewer**:

I have no prior experience in Go, this is just an attempt to see if good enough 😅

2022-01-05 16:38 UTC, joshhunt commented
Might be good for @grafana/docs-squad to pass their eyes over this?

2022-01-10 07:25 UTC, hugohaggmark commented
Have we tried to replicate this without the `app_mode = development` in the ini-file? I know that responses from the backend api differ depending on that setting in the ini-file.
https://grafana.com/docs/grafana/latest/administration/configuration/#app_mode

2022-01-10 13:34 UTC, hugohaggmark commented
> > Have we tried to replicate this without the `app_mode = development` in the ini-file? I know that responses from the backend api differ depending on that setting in the ini-file. [grafana.com/docs/grafana/latest/administration/configuration/#app_mode](https://grafana.com/docs/grafana/latest/administration/configuration/#app_mode)
> 
> Hey @hugohaggmark 😄 , I did the test on the main branch without the `app_mode = development `, I encounter the same error message " invalid username or password", after I did the same test using my fix branch and the error message is consistent (a better error message)🚀

Did you change in .bra.toml file as well from dev to production? (if you run bra run or make run)

2022-01-10 13:42 UTC, axelavargas commented
> Did you change in .bra.toml file as well from dev to production? (if you run bra run or make run)

Nope, I didn't know the existence of bra.toml 😅 , testing it now

2022-01-10 13:51 UTC, axelavargas commented
> > Did you change in .bra.toml file as well from dev to production? (if you run bra run or make run)
> 
> Nope, I didn't know the existence of bra.toml sweat_smile , testing it now

Alright, I did the test and got the same result as before, with my fix branch I have the right message :)

2022-01-10 14:03 UTC, hugohaggmark commented
Sorry I'm a bit tired, so I just want to make sure, but when I change my `.bra.toml` file and `custom.ini` to use production and restart `make run` this is what I get running your branch:
![image](https://user-images.githubusercontent.com/562238/148778469-e17d96db-fce3-4525-b914-9b75be27bd38.png)

2022-01-10 14:05 UTC, axelavargas commented
> Sorry I'm a bit tired, so I just want to make sure, but when I change my `.bra.toml` file and `custom.ini` to use production and restart `make run` this is what I get running your branch: ![image](https://user-images.githubusercontent.com/562238/148778469-e17d96db-fce3-4525-b914-9b75be27bd38.png)

No worries Hugo 🤗, just to double-check you are getting this screen after trying more than 5 times with the wrong password?

2022-01-10 14:06 UTC, hugohaggmark commented
> > Sorry I'm a bit tired, so I just want to make sure, but when I change my `.bra.toml` file and `custom.ini` to use production and restart `make run` this is what I get running your branch: ![image](https://user-images.githubusercontent.com/562238/148778469-e17d96db-fce3-4525-b914-9b75be27bd38.png)
> 
> No worries Hugo 🤗, just to double-check are you getting this screen after trying more than 5 times with the wrong password?

Yes

2022-01-10 14:21 UTC, hugohaggmark commented
My bad, I didn't try enough times in a row 🙈

2022-01-10 14:28 UTC, papagian commented on pkg/api/login.go
> +			msg = "Too many consecutive incorrect login attempts for user - login for user temporarily blocked"
alternatively, you could do the following in order to use [this text](https://github.com/grafana/grafana/blob/77347a37b1741a592c46cf5ff7cd5f8d812795b3/pkg/login/auth.go#L18).
```suggestion
			msg = err.Error()
```

You can also apply the same for the other cases.

2022-01-10 14:35 UTC, papagian commented on pkg/api/login.go
> +		resp = response.Error(401, msg, err)
If the error is not any of the above cases then the message will be empty (the default string value in Go). So you need [initialise it](https://github.com/grafana/grafana/blob/547310ed1b813393ed0ae6d72789ece084bc4a4c/pkg/api/login.go#L213) to a default like `Invalid username or password`.

2022-01-10 14:43 UTC, sakjur requested changes

2022-01-10 14:43 UTC, sakjur commented on pkg/api/login.go
> +		}
Don't tell a potentially hostile user that the username isn't valid.
 https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-and-error-messages

2022-01-10 15:50 UTC, sakjur submitted a review, later dismissed
:+1: Now it looks good

2022-01-10 15:50 UTC, sakjur commented on pkg/api/login.go
> +			msg = err.Error()
You won't get a capital first letter now, if that matters to you 🙂

2022-01-10 15:58 UTC, sakjur commented
> I made some changes, but I am a bit unsure now about the whole approach, should we provide the user information about the account being locked?

That is a very good question.

It depends a little imo.

Let's say we're attacking Grafana, trying to figure out the password to the user `emil`, and failing N times, locking the user.
If we'd now start seeing "try again later" instead of "invalid credentials", does that tell us 1. that the user exists 2. if we've guessed the right password?

What we'd want, to prevent disclosure, is that the brute force protection is applied in such a way that you wouldn't gain any more information about either of those two (i.e. even guessing a user that doesn't exist should trigger the brute force protection and the brute force protection should be applied before trying to log the user in). I think, if we can make sure that's true, that this is an improvement worth making 🙂

2022-01-11 14:12 UTC, axelavargas commented
> > I made some changes, but I am a bit unsure now about the whole approach, should we provide the user information about the account being locked?
> 
> That is a very good question.
> 
> It depends a little imo.
> 
> Let's say we're attacking Grafana, trying to figure out the password to the user `emil`, and failing N times, locking the user. If we'd now start seeing "try again later" instead of "invalid credentials", does that tell us 1. that the user exists 2. if we've guessed the right password?
> 
> What we'd want, to prevent disclosure, is that the brute force protection is applied in such a way that you wouldn't gain any more information about either of those two (i.e. even guessing a user that doesn't exist should trigger the brute force protection and the brute force protection should be applied before trying to log the user in). I think, if we can make sure that's true, that this is an improvement worth making slightly_smiling_face

Hey @sakjur 👋🏾 , 🤔 I believe I am lacking important context here, do we have in place brute force protection? so far I only noticed that after x amount of attempts the user is temporarily blocked, but I am not sure if this blocked is based on time? or if we are blocking the  IP, sending emails?  I am leaning towards closing my PR and sending the relevant issue to the backend squad, it is going to be easier to make those decisions with the right context.  

Let me know what you think 😄

2022-01-12 09:38 UTC, closed without merging

2022-01-12 12:44 UTC, sakjur commented
@axelavargas I think you made a really good call to close this for now 🙂

I agree with you that context is key here, the difference between a security vulnerability and a great UX feature relies on figuring out things about other parts of the system (like you're saying)— and if that's not something you have time for at the moment, it seems like the right thing to do to not do anything at all.

Still, I hope someone picks this up, the base is reasonable after we've made sure that the error messages doesn't let you enumerate users or passwords 😄