Service Accounts: Fix issue in UserTable and ServiceAccountsTable
grafana/grafana pull request #43865
Opened 2022-01-10 16:16 UTC by kalleep

**What this PR does / why we need it**:
In https://github.com/grafana/grafana/pull/43573 changes to how showRemoveModal property is set in UserTable causes a bug where a confirmation modal is rendered for every item in the list with the last one on top.

This happens because the ConfirmModal is rendered in a loop and if we use true as value then every item will render the modal.

This pr restore previous behavior by setting the value of showRemoveModal to user login property so that only matching users model will be rendered.

2022-01-10 17:03 UTC, eleijonmarck approved these changes

2022-01-10 17:03 UTC, eleijonmarck commented
this probably fixes the bug. But we should probably fix the issue "more" permanent" or true to make it use the boolean

2022-01-10 17:04 UTC, eleijonmarck commented
@dprokop should have a look at this

2022-01-10 17:36 UTC, kalleep commented
> this probably fixes the bug. But we should probably fix the issue "more" permanent" or true to make it use the boolean

Yes, a better solution would be to move out the ConfirmModal and fix the state. I can look into it tomorrow :)

2022-01-11 08:48 UTC, dprokop commented
@kalleep @eleijonmarck  - created a PR with the alternative solution to this: https://github.com/grafana/grafana/pull/43885

It takes the ConfirmModal out of the context of a single user row. I have not updated the ServiceAccountsTable tho, so please do so. There is no boolean/string state anymore. The rendering relies on the `userToRemove: OrgUser | null` being present in the state.

2022-01-11 08:49 UTC, dprokop requested changes
@kalleep @eleijonmarck - created a PR with the alternative solution to this: #43885

It takes the ConfirmModal out of the context of a single user row. I have not updated the ServiceAccountsTable tho, so please do so. There is no boolean/string state anymore. The rendering relies on the userToRemove: OrgUser | null being present in the state.

2022-01-11 09:17 UTC, eleijonmarck commented
@dprokop great with the tests!

2022-01-11 15:21 UTC, dprokop approved these changes

2022-01-11 15:21 UTC, dprokop commented on public/app/features/serviceaccounts/ServiceAccountsTable.tsx
> +          body={`Are you sure you want to delete serviceaccount ${toRemove.login}?`}
```suggestion
          body={`Are you sure you want to delete ${toRemove.login} service account?`}
```

2022-01-11 17:51 UTC, merged