Alerting: Support the For condition for DatasourceError alerts
grafana/grafana pull request #44152
Opened 2022-01-18 13:01 UTC by grobinson-grafana

**What this PR does / why we need it**:

This pull request adds support for the `For` condition for `DatasourceError` alerts to prevent ephemeral and non-recurring errors from firing `DatasourceError` alerts.

2022-01-24 19:59 UTC, yuri-tceretian commented
1. Did you intentionally add labels `datasource_uid` and `refId` to the alert instance that is created when the error option is `Alerting`. Currently, we do that only when the option is `Error`?
2. Currently, both options `Alerting` and `Error` create an alert instance right away. I can see the benefits of making the error state obey `for` setting. However, I think it should be only applicable to option `Alerting`. In this case, we will let users that configure alert rules with long evaluation intervals (for example 1h for 3h) decouple error alerts from regular evaluations.

2022-01-31 13:12 UTC, gerobinson commented
> Did you intentionally add labels datasource_uid and refId to the alert instance that is created when the error option is Alerting. Currently, we do that only when the option is Error?

Thanks! This was an error, I have fixed it!

> Currently, both options Alerting and Error create an alert instance right away. I can see the benefits of making the error state obey for setting. However, I think it should be only applicable to option Alerting. In this case, we will let users that configure alert rules with long evaluation intervals (for example 1h for 3h) decouple error alerts from regular evaluations.

I know we discussed offline about whether we could use Alertmanager to inhibit these alerts instead of supporting the `For` condition. I will look into that and perhaps we can come back to this PR and decide whether to merge it or not!

2022-01-31 13:14 UTC, gerobinson commented
> Did you intentionally add labels datasource_uid and refId to the alert instance that is created when the error option is Alerting. Currently, we do that only when the option is Error?

Thanks! This was an error, I have fixed it!

> Currently, both options Alerting and Error create an alert instance right away. I can see the benefits of making the error state obey for setting. However, I think it should be only applicable to option Alerting. In this case, we will let users that configure alert rules with long evaluation intervals (for example 1h for 3h) decouple error alerts from regular evaluations.

I know we discussed offline about whether we could use Alertmanager to inhibit these alerts instead of supporting the `For` condition. I will look into that and perhaps we can come back to this PR and decide whether to merge it or not!

2022-02-25 12:07 UTC, gotjosh requested changes
I don't think this is right.

I'm going to start with the argument that this is very likely a breaking change e.g. users who were expecting an immediate alert would now wait more time to get it

Then, I'd say that failure to evaluate is an unexpected condition and should be a case for action. If you expect your datasource to fail intermittently then you have the option to silence the alert or control how often this notifies via a combination of `group_wait` and label selection in the Alertmanager configuration.

2022-02-25 13:26 UTC, grobinson-grafana commented
> I'm going to start with the argument that this is very likely a breaking change e.g. users who were expecting an immediate alert would now wait more time to get it

This shouldn't be a breaking change as the default value would be `0`?

> failure to evaluate is an unexpected condition and should be a case for action

We could argue that a single datapoint that exceeds a threshold is an unexpected condition and should be actioned. However, in Grafana we allow the user to configure after how long the threshold has been exceeded before an actionable event (i.e. an alert) should be fired. If and when the alert should be turned into a notification is a different question, and as mentioned is configurable in Alertmanager via `group_wait`.

The motivation for this change is that the same choice should be given to the customer for errors and missing data, not just when a threshold has been exceeded. There are a lot of cases where errors or failures are not turned into actionable events (i.e. an alert) unless persistent: packet loss in TCP or leadership election changes and peer failures in a Consul cluster. However, most of the time someone operating a network or Consul cluster would want these to become actionable if persistent, and so the argument here is that a user should be able to configure when Grafana turns HTTP 500 errors from Prometheus (i.e. due to a restart or reloading configuration) into an alert too, rather than just when the alert is turned into a notification.

2022-02-25 13:28 UTC, grobinson-grafana commented
I'm going to start with the argument that this is very likely a breaking change e.g. users who were expecting an immediate alert would now wait more time to get it

This shouldn't be a breaking change as the default value would be 0?

failure to evaluate is an unexpected condition and should be a case for action

We could argue that a single datapoint that exceeds a threshold is an unexpected condition and should be actioned. However, in Grafana we allow the user to configure after how long the threshold has been exceeded before an actionable event (i.e. an alert) should be fired. If and when the alert should be turned into a notification is a different question, and as mentioned is configurable in Alertmanager via group_wait.

The motivation for this change is that the same choice should be given to the customer for errors and missing data, not just when a threshold has been exceeded. There are a lot of cases where errors or failures are not turned into actionable events (i.e. an alert) unless persistent: packet loss in TCP or leadership election changes and peer failures in a Consul cluster. However, most of the time someone operating a network or Consul cluster would want these to become actionable if persistent, and so the argument here is that a user should be able to configure when Grafana turns HTTP 500 errors from Prometheus (i.e. due to a restart or reloading configuration) into an alert too, and not just when the alert is turned into a notification.

2022-02-25 14:09 UTC, grobinson-grafana commented
> I'm going to start with the argument that this is very likely a breaking change e.g. users who were expecting an immediate alert would now wait more time to get it

This shouldn't be a breaking change as the default value would be 0?

> failure to evaluate is an unexpected condition and should be a case for action

We could argue that a single datapoint that exceeds a threshold is an unexpected condition and should be actioned. However, in Grafana we allow the user to configure after how long the threshold has been exceeded before an actionable event (i.e. an alert) should be fired. If and when the alert should be turned into a notification is a different question, and as mentioned is configurable in Alertmanager via group_wait.

The motivation for this change is that the same choice should be given to the customer for errors and missing data, not just when a threshold has been exceeded. There are a lot of cases where errors or failures are not turned into actionable events (i.e. an alert) unless persistent: packet loss in TCP or leadership election changes and peer failures in a Consul cluster. However, most of the time someone operating a network or Consul cluster would want these to become actionable if persistent, and so the argument here is that a user should be able to configure when Grafana turns HTTP 500 errors from Prometheus (i.e. due to a restart or reloading configuration) into an alert too, and not just when the alert is turned into a notification.

2022-02-25 14:10 UTC, grobinson-grafana commented
> I'm going to start with the argument that this is very likely a breaking change e.g. users who were expecting an immediate alert would now wait more time to get it

This shouldn't be a breaking change as the default value would be 0?

> failure to evaluate is an unexpected condition and should be a case for action

We could argue that a single datapoint that exceeds a threshold is an unexpected condition and should be actioned. However, in Grafana we allow the user to configure after how long the threshold has been exceeded before an actionable event (i.e. an alert) should be fired. If and when the alert should be turned into a notification is a different question, and as mentioned is configurable in Alertmanager via group_wait.

The motivation for this change is that the same choice should be given to the customer for errors and missing data, not just when a threshold has been exceeded. There are a lot of cases where errors or failures are not turned into actionable events (i.e. an alert) unless persistent: packet loss in TCP or leadership election changes and peer failures in a Consul cluster. However, most of the time someone operating a network or Consul cluster would want these to become actionable if persistent, and so the argument here is that a user should be able to configure when Grafana turns HTTP 500 errors from Prometheus (i.e. due to a restart or reloading configuration) into an alert too, and not just when the alert is turned into a notification.

2022-02-25 14:47 UTC, gotjosh commented
> We could argue that a single datapoint that exceeds a threshold is an unexpected condition and should be actioned.

I don't see this is the same case. The user defined what the criteria that they'd like to be alerted on is; this is a failure to determine whether that criteria is met or not. 

> There are a lot of cases where errors or failures are not turned into actionable events

I agree, but we're not in control of what counts as an event; the rule definition is. If you don't care about intermittent failures in the first place, why not set the alert to `OK`?

![Screenshot 2022-02-25 at 14 38 47](https://user-images.githubusercontent.com/231583/155733865-5b73a40d-edf7-4b2f-ba98-21df0d0922ba.png)

> the argument here is that a user should be able to configure when Grafana turns HTTP 500 errors

I must be missing something because my understanding is that with a combination of:

- Your alert rule query
- the interval (every 30s), the hold (for 60s), and the time window (over 10m period)
- The `Configure no data and error handling` options
- `group_wait`

You have enough knobs to define what counts as an actionable event or not.

2022-02-25 17:20 UTC, closed without merging