Azure authentication in Prometheus backend
grafana/grafana pull request #44407
Opened 2022-01-25 04:04 UTC by kostrse

**What this PR does / why we need it**:

Re-adding back Azure authentication support to Prometheus datasource after it was rewritten from `plugin.json` routes to Go backend.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Added logic which sets Azure credentials to `opts.CustomOptions` when they configured by user.
It's a bit verbose now. I'm planning to refactor it into a more high level helper method and share it with AzureMonitor datasource in future.

The `JsonData` object was changed from a strongly-typed interface to a dynamically-typed map, so it could be passed to `azcredentials.FromDatasourceData` and reused after only single deserialization.

It would be useful to have `JsonData` in `backend.DataSourceInstanceSettings` as an already deserialized `map[string]insterface{}`, similar to DecryptedSecreJsonData. not only as a raw byte array.

Created an utility `maputil` package with helper methods to access fields from the `map[string]interface{}`.

2022-01-26 14:15 UTC, marefr requested changes
This works, but yeah it feels a bit messy moving from types to generic map. Now I think it's time to add the azure credentials configuration to grafana-plugin-sdk-go according to my earlier https://github.com/grafana/grafana/pull/39209#discussion_r783863830 to clean this up. Let us know if you need help with that.

2022-02-01 08:15 UTC, kostrse commented on pkg/tsdb/prometheus/promclient/provider.go
> +	} else if credentials != nil {
Fixed this

2022-02-01 08:20 UTC, kostrse commented
> This works, but yeah it feels a bit messy moving from types to generic map.

The generic map itself isn't that messy in my opinion, it allows different component to extract necessary information without having to know about each other (each of them may have own strongly-typed model but schema is too simple in this particular case to do that). Another question is how to access the values in a not messy way.

Is it OK to keep the helper methods which I introduced, or I can switch to `simplejson.Json` instead of the `map[string]interface{}`

> Now I think it's time to add the azure credentials configuration to grafana-plugin-sdk-go according to my earlier [#39209 (comment)](https://github.com/grafana/grafana/pull/39209#discussion_r783863830) to clean this up. Let us know if you need help with that.

I will send one more cleanup PR before adding strongly-typed configuration to `grafana-plugin-sdk-go`

2022-02-03 03:03 UTC, kostrse commented
@marefr @daniellee @jongyllen this PR fixes Azure authentication in Prometheus datasource. Would very want to have it merged and be included into Grafana 8.4 release. Otherwise we won't be able to upgrade from Grafana 8.2.

2022-02-03 11:57 UTC, marefr commented
@kostrse yes understood and we're aware of this. I'll have a new look on this during the day.

2022-02-03 15:42 UTC, marefr approved these changes
LGTM. Just need to see if the build passes, I've restarted it

> > This works, but yeah it feels a bit messy moving from types to generic map.
> 
> The generic map itself isn't that messy in my opinion, it allows different component to extract necessary information without having to know about each other (each of them may have own strongly-typed model but schema is too simple in this particular case to do that). Another question is how to access the values in a not messy way.

Since this is temporary and will change with moving things to the SDK it's fine

> Is it OK to keep the helper methods which I introduced, or I can switch to `simplejson.Json` instead of the `map[string]interface{}`

Since this is temporary and will change with moving things to the SDK, either works.

> > Now I think it's time to add the azure credentials configuration to grafana-plugin-sdk-go according to my earlier [#39209 (comment)](https://github.com/grafana/grafana/pull/39209#discussion_r783863830) to clean this up. Let us know if you need help with that.
> 
> I will send one more cleanup PR before adding strongly-typed configuration to `grafana-plugin-sdk-go`

Sounds good :+1:

2022-02-03 16:06 UTC, merged

2022-02-03 17:15 UTC, marefr commented
Thanks @kostrse