AccessControl: SQL filters for team search
grafana/grafana pull request #44557
Opened 2022-01-27 17:04 UTC by gamab

**What this PR does / why we need it**:
This PR brings accesscontrol to the GET endpoints for teams. It also filters out teams at SQL level for the search endpoint.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise/issues/2605
Fixes https://github.com/grafana/grafana-enterprise/issues/2668

**Special notes for your reviewer**:

2022-02-01 11:15 UTC, kalleep approved these changes

2022-02-01 11:15 UTC, kalleep commented on pkg/services/sqlstore/team.go
> +		countSess.Where(acWhere, acArgs...)
nice that you covered count as well!

2022-02-01 13:48 UTC, Jguer requested changes
Blocking changes with upstream epic

2022-02-02 16:10 UTC, IevaVasiljeva approved these changes
Looks good to go once we're ready to merge. Great work!

2022-02-09 14:58 UTC, Jguer approved these changes

2022-02-09 15:17 UTC, merged