fix issue where unify alerting UI was displaying 404 banner when Prometheus doesn't support ruler
grafana/grafana pull request #44571
Opened 2022-01-27 22:59 UTC by roystchiang

**What this PR does / why we need it**:

Currently Grafana relies on the backend to return a 500 to see whether or not ruler is supported. The `/rules` endpoint is also not listed on https://prometheus.io/docs/prometheus/latest/querying/api/#rules. The `/rules` page on Prometheus is actually a HTML page, and it is possible for a Prometheus-compatible backend to return 404. 

Hence, I propose that we drop the 404 banner if the service returns 404, instead of only relying on a parsing error.

**Which issue(s) this PR fixes**:

Fixes #43301

**Special notes for your reviewer**:

2022-01-27 22:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=44571) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=44571) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=44571) it.</sub>

2022-01-28 22:43 UTC, HartonWong approved these changes
I have verified that this change will drop the error bar when the endpoint doesn't support `/rules` endpoint by returning 404

2022-02-02 23:52 UTC, alvinlin123 commented
@yuri-tceretian just wondering if this PR looks ok overall?

2022-02-07 22:23 UTC, alolita commented
@yuri-tceretian we're waiting for a second review - can you please help?

2022-02-08 10:06 UTC, gillesdemey requested changes
One minor change required before this is ready to merge :shipit:

2022-02-08 10:06 UTC, gillesdemey commented on public/app/features/alerting/unified/state/actions.ts
> +          console.log(e);
This needs to be removed :)

2022-02-08 14:56 UTC, roystchiang commented on public/app/features/alerting/unified/state/actions.ts
> +          console.log(e);
oops sorry. I forgot about that.

2022-02-08 14:57 UTC, roystchiang commented
@gillesdemey could you please take a look again? thanks!

2022-02-08 18:10 UTC, gillesdemey approved these changes
LGTM; still waiting on final CI build results

2022-02-08 18:21 UTC, gillesdemey commented
Build results aren't looking too good – @roystchiang can you try rebasing with `main`?

2022-02-08 18:37 UTC, roystchiang commented
Just rebased. Thanks for taking a look :)

2022-02-08 20:03 UTC, merged

2022-02-08 20:04 UTC, gillesdemey commented
Awesome first contribution @roystchiang – thank you for your patience on getting this one merged 🙏 🎉