Neg y
grafana/grafana pull request #44774
Opened 2022-02-02 13:49 UTC by dprokop

Closes https://github.com/grafana/grafana/discussions/38202

This PR brings highly anticipated **Negative Y transform** to Time series panel, as well as **Constant transform**.

TODO:
- [ ] Old graph -> time series migration
- [ ] Documentation 

[Test dashboard.json](https://gist.github.com/dprokop/639f9f830ddf3d0591bebd9a2225058a)

Configuration UI (available **only** as an override):

![image](https://user-images.githubusercontent.com/2376619/152164843-37acdb64-9bb4-4aa9-a59a-fca0b21de60c.png)

UI indicators about series being transformed:

|  Tooltip | Legend  |
|---|---|
|![image](https://user-images.githubusercontent.com/2376619/152165085-51a18525-28c5-4389-abca-1c0c0f5bce2a.png)|![image](https://user-images.githubusercontent.com/2376619/152165137-0da3bb21-1412-4c9c-9ffd-a6173406d03b.png)<br/>![image](https://user-images.githubusercontent.com/2376619/152165247-86f586af-6355-4671-9408-7a15b1334ec1.png)|

2022-02-02 13:51 UTC, dprokop commented on public/app/plugins/panel/timeseries/config.ts
> +        name: 'Transform',
Not sure this name is clear enough, but can't think of anything else. Any suggestions are highly appreciated

2022-02-02 18:14 UTC, ryantxu reviewed
Looks good -- I am not sure about duplicate name, label, and key on the legend.   But also not sure I see a quick way to avoid it

2022-02-02 18:14 UTC, ryantxu commented on public/app/plugins/panel/state-timeline/utils.ts
> +    textToColor.set(items[i].name, items[i].color!);
:thinking: looks like name is used here.    So we can not just remove it

2022-02-02 18:15 UTC, ryantxu commented
If this is merged, is everything on the parity list supported?

2022-02-02 18:27 UTC, dprokop commented
> Looks good -- I am not sure about duplicate name, label, and key on the legend. But also not sure I see a quick way to avoid it

Don't like it neither - thrown quickly to get a quick feedback on the feat. Will revisit tomorrow morning :)

2022-02-02 18:27 UTC, dprokop commented on packages/grafana-data/src/field/overrides/processors.ts
> +  isClearable?: boolean;
Guess who added it.... ;)

2022-02-02 21:15 UTC, simPod requested changes
![image](https://user-images.githubusercontent.com/327717/152238302-976d23bc-30bc-4fc8-9ba5-c422c734792a.png)

Do we need the `(neg Y)` there? I often have like 40 series and I think that it will be a noise. Series name is IMO sufficient.

2022-02-03 03:17 UTC, nward commented
Hi @dprokop this is great work thanks for getting in to this.

The example dashboard has negative data in it - I think (at least for me!) the use case is to use positive values, but have it show below 0. This is particularly important for my use case as we select data by "highest" - if we have to translate it to negative then "highest" is no long really what we want.

One use case for this visualisation is for a network link, showing traffic either above or below 0 depending on the direction (rx vs. tx).
It is also the case that we would want to have multiple network links on the same chart, with their rx values stacked, and tx values stacked - with rx showing above 0 and tx showing below 0.

A couple of things I'm interested in / think you should include in your testing:
- 2 Series of positive value data, one positive (normal), and one negative-y (which should render below 0)
- 4 series of positive value data, 2 positive (normal), 2 negative-Y. The positive and negative stacks should be distinct, and should result in the stacked "negative-y" value rendering further below 0 than if it was not stacked. Perhaps stacks should automatically be separated based on negative/positive Y? I'm not sure of an example of when you'd want the negative-Y to be on the same stack as positive-Y, so feels like this should just be automatic - i.e. if you have a stack "a" on a positive-y value it should automatically be distinct from any series with stack "a" with negative-y.

2022-02-03 03:19 UTC, nward commented
> Do we need the `(neg Y)` there? I often have like 40 series and I think that it will be a noise. Series name is IMO sufficient.

I agree with this - I don't think this is valuable for what people use this feature for. Perhaps showing this in the label could be a default disabled option?

2022-02-03 12:50 UTC, dprokop commented
@nward @simPod  - Thanks a bunch for feedback. As of now, I have removed the transform indicators from the tooltip and the legend. 

@nward  - Me and @leeoniya have been discussing separate neg/pos y stacks a while ago. I have implemented it in the last commit. The gist is that within a single stacking group it will create a pseudo-group for the series that has negative Y transform applied and will result in a separate stack on the neg y-axis. See the screenshot in the PR description. I have also updated the test dashboard with a few more cases - feel free to test it out against this branch.

2022-02-03 12:55 UTC, dprokop commented
> Looks good -- I am not sure about duplicate name, label, and key on the legend. But also not sure I see a quick way to avoid it

@ryantxu - I have reverted this change as it was only to support to transformation indicator in legend/tooltip - according to the feedback above it seems like it might be a useless thing. We can revisit it in the future

2022-02-03 12:56 UTC, dprokop commented on packages/grafana-ui/src/components/VizLegend/VizLegend.story.tsx
> +      name: `${alphabet[i].toUpperCase()}-series`,
```suggestion
```

2022-02-03 13:02 UTC, achatterjee-grafana reviewed
Added doc review.

2022-02-03 13:02 UTC, achatterjee-grafana commented on docs/sources/visualizations/time-series/_index.md
> +Use this option to transform series values without affecting values shown in tooltip, context menu and legend.
```suggestion
Use this option to transform the series values without affecting the values shown in the tooltip, context menu, and legend.
```

2022-02-03 13:02 UTC, achatterjee-grafana commented on docs/sources/visualizations/time-series/_index.md
> +- **Negative Y transform -** Flip the results to negative values on the y axis.
```suggestion
- **Negative Y transform -** Flip the results to negative values on the Y axis.
```

2022-02-03 14:34 UTC, dprokop commented
> If this is merged, is everything on the parity list supported?

The last thing missing after this is regions support (https://github.com/grafana/grafana/issues/35486)

2022-02-03 23:55 UTC, nward commented
> @nward @simPod - Thanks a bunch for feedback. As of now, I have removed the transform indicators from the tooltip and the legend.
> 
> @nward - Me and @leeoniya have been discussing separate neg/pos y stacks a while ago. I have implemented it in the last commit. The gist is that within a single stacking group it will create a pseudo-group for the series that has negative Y transform applied and will result in a separate stack on the neg y-axis. See the screenshot in the PR description. I have also updated the test dashboard with a few more cases - feel free to test it out against this branch.

Nice work! That's really excellent. I'll see about getting this branch deployed somewhere it can talk to my real Influxdb data and see how it goes and get back to you.

2022-02-04 03:00 UTC, leeoniya commented
> If this is merged, is everything on the parity list supported?
> @ryantxu The last thing missing after this is regions support (https://github.com/grafana/grafana/issues/35486)

and maybe https://github.com/grafana/grafana/discussions/38299?

2022-02-08 10:22 UTC, zoltanbedi approved these changes
Tried it out. LGTM!

2022-02-08 10:45 UTC, oscarkilhed approved these changes

2022-02-08 15:27 UTC, merged

2023-03-30 17:12 UTC, IR31108 commented
I'm in 9.2.4 and I'm unable to do this for a time series with only one data line. It behaves the same as multiplying by -1 which is not helpful in my case. Note that the axis is in the negatives which would be misleading. Any idea why or how to fix it?

![image](https://user-images.githubusercontent.com/100949749/228913151-72f5b68d-9311-42b1-b9c3-eec00cf295d5.png)