Query History: Split data and view models
grafana/grafana pull request #44922
Opened 2022-02-04 17:02 UTC by ifrost

**What this PR does / why we need it**:

Rich History uses `RichHistoryQuery` type as a view model (e.g. in `RichHistoryCard`) and the same type is saved to local storage.

With the storage in the backend the view model will change - we will start using `datasourceUid` instead of only `datasourceName`. Also, each item will be identified with a unique id, not a timestamp as it was with local storage.

This PR moves all properties from previous `RichHistoryQuery` into a local storage specific DTO object `RichHistoryLocalStorageDTO`. New properties in `RichHistoryQuery` describe new view model that is now used in view components. This way view layer doesn't know anything about how rich history is saved, it simply expects `RichHistoryQuery` which is converted in persistence layer and saved in storage exactly how it's been before.

This way when we add backend storage we will not need to change view components. We will add a new storage provide that will return `RichHistoryQuery` view models keeping storage specific details away from the view layer.

![before](https://user-images.githubusercontent.com/745532/152570053-331d34cf-ea55-411a-be1c-00b1589d36e7.png)

![after](https://user-images.githubusercontent.com/745532/152570082-e999fdac-8a6c-47d0-892b-366996db5586.png)

**Which issue(s) this PR fixes**:

Fixes N/A

**Special notes for your reviewer**:

No changes in the behavior. To test it check if the current history loads fine, add/edit/star/remove history items and play with filtering.

2022-02-09 09:45 UTC, Elfo404 requested changes

2022-02-09 13:38 UTC, ifrost commented on public/app/features/explore/RichHistory/RichHistoryCard.test.tsx
> +    { query: 'query3', refId: 'C' } as DataQuery,
Fixed in 6abee55ed3e63df3100086cc6acd4e6127df4ce4

2022-02-09 19:12 UTC, ifrost commented on public/app/features/explore/state/history.ts
> +      nextRichHistory = await updateCommentInRichHistory(getState().explore.richHistory, id, updatedProperty as string);
Ended up splitting the logic into three separate functions in 497fc1698c4be1a89891143762a4a51ab7b26ecb

2022-02-10 09:35 UTC, Elfo404 commented on public/app/features/explore/state/history.ts
> +      nextRichHistory = await updateCommentInRichHistory(getState().explore.richHistory, id, updatedProperty as string);
way cleaner implementation imho! 👍

2022-02-10 09:56 UTC, Elfo404 approved these changes
looks good! everything seems to work as before! 🚀

2022-02-10 12:59 UTC, merged