Docs: fixes formatting in the documentation guides
grafana/grafana pull request #44953
Opened 2022-02-06 18:41 UTC by MattDodsonEnglish

**What this PR does / why we need it**:

In addition to fixing a broken markdown table, this also standardizes the structure of the documentation style guide's "Word usage" list.

- Moves guidelines for the terms "Unix" and "repository" to their own sections. 
- Makes sure all terms have a level-4 heading.
- Makes sure all terms are in alphabetical order.

**Special notes for your reviewer**:
I split "node_exporter" and "window_exporter" into two sections, so that the person looking for one of the terms can scan the list alphabetically. Since they have the same usage guidelines, the "window_exporter" section refers to the "node_exporter" section. I chose "node_exporter" as the main term because it appears more often in the `docs` directory and in Google search results.

2022-02-07 07:16 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +#### repository
@chri2547, this is already in our linter at https://github.com/grafana/technical-documentation/blob/main/linters/vale/Grafana/WordList.yml#L68.

2022-02-07 07:17 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +#### MS SQL Server
Looks like SQL Server is the correct trademark, per https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWArzw.

2022-02-07 07:19 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +#### node_exporter
@chri2547, see https://github.com/grafana/technical-documentation/issues/215.

2022-02-07 07:20 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +**Incorrect:** Node Exporter, node exporter, Windows Exporter, Windows exporter, windows exporter.
-1

2022-02-07 07:22 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +**Incorrect:** Node Exporter, node exporter, Windows Exporter, Windows exporter, windows exporter.
Change upstream in Prometheus so it is consistent. See also 
![Screenshot from 2022-02-07 08-21-55](https://user-images.githubusercontent.com/73951760/152742884-3dabdca0-e17b-4d6c-af9b-6def3cf47d6b.png)

2022-02-07 07:28 UTC, osg-grafana commented on contribute/style-guides/documentation-style-guide.md
> +#### node_exporter
Leave `windows_exporter` so that people know that it exists.

2022-02-07 07:30 UTC, osg-grafana requested changes
It looks like the trademarks for Microsoft include "SQL Server" rather than "MS SQL Server". There is some internal discussion about tools names in headings and titles, which relates to part of this PR. It is not immediately clear that a windows_exporter exists if it is removed from the section heading.

2022-02-07 07:35 UTC, osg-grafana commented
Thank you @MattDodsonEnglish for splitting up the Prometheus exporters. I revised my review comment about `windows-exportrt` upon reading your description again.

2022-02-07 19:59 UTC, MattDodsonEnglish commented
Thanks for the careful review @osg-grafana ! 

In this PR, I didn't actually add content---I just moved some items around to standardize the structure.

It seems like these issues that you've flagged are related to some internal discussion. So I should probably let somebody who's more informed make those kind of changes :-) .

For the "MS SQL" term, though, I'd be happy to change it to this if you want:

```
#### Microsoft SQL Server

Use the trademarked name, "SQL Server."
If you need to be clear that you are referring to the Microsoft product,
you can also use "Microsoft SQL Server" or "MS SQL Server."
```
I did a quick `grep` of the `docs` directory, and I think this terminology aligns with what the documentation already uses.

What do you think? I won't change anything with the other comments, though.

2022-02-08 07:06 UTC, osg-grafana commented
> Thanks for the careful review @osg-grafana !

You're welcome!

> For the "MS SQL" term, though, I'd be happy to change it to this if you want:
> 
> ```
> #### Microsoft SQL Server
> 
> Use the trademarked name, "SQL Server."
Please change this to "SQL Server" (with the period outside of the double quotes).

> If you need to be clear that you are referring to the Microsoft product,
> you can also use "Microsoft SQL Server" or "MS SQL Server."

> ... I won't change anything with the other comments, though.
+1

2022-02-08 10:28 UTC, MattDodsonEnglish commented
> Please change this to "SQL Server" (with the period outside of the double quotes).

Fixed and committed with 95f2fcf04cd3ad6fb89f15fcaf49833eb78845e0 .

Thanks @osg-grafana ! Let me know if there's anything else I should do.

2022-02-08 14:17 UTC, osg-grafana approved these changes

2022-03-10 17:45 UTC, closed without merging