Settings: Fix subsection overwrites
grafana/grafana pull request #45522
Opened 2022-02-17 13:22 UTC by joanlopez

_(Note: Do not consider the proposal as final. I'm more interested on an open discussion & feedback)_

<br/>
<br/>

**What this PR does / why we need it**:

Consider we have two sections on the settings file like:

```
[caching]
enabled = true
...
[caching.encryption]
enabled = false
```

which would express the user's desire to "enable caching" but "do not enable it with encryption".

Then, the problem is that `caching.encryption.enabled` value overwrites the `caching.enabled` value.

That happens because at time of reading the configuration file,  we call the `GetKey` method of the current section (i.e. `caching.encryption`) which, in case the key (i.e. `enabled`) does not exist yet, it initializes a new key. But, the library considers that, [if the section is a "child section" (contains a dot `.`), then the new key's section should be the parent](https://github.com/go-ini/ini/blob/main/section.go#L124). So, at time of initializing the `enabled` key for the `caching.encryption` section, it initializes a new one that points to `caching` section, therefore the value configured for `caching.enabled` gets overwritten with the value configured for `caching.encryption.enabled`.

So, in order to prevent this issue, my naive proposal is to add an extra check that verifies if the current section contains the key we're looking for (we could also add an if..else statement or similar, but as I mentioned I'm more interested on the discussion than the final code lines to deal with it) -- note there are multiple checks that are hard to perform because most of them rely on `GetKey` behavior mentioned above.

**Which issue(s) this PR fixes**:

_No issue created, directly jumped into this pull request / discussion._

**Special notes for your reviewer**:

Beyond the final way to handle this edge case (there's probably a nicer way to code it), what's suggested on this pull request represents a behavior change which could break other things. So, I'm especially interested in knowing if there are other parts that rely on the current behavior (not the suggested one but the opposite) and, if so, how we could solve this issue considering a change on the section/key name would represent a breaking change as well (if I'm not wrong).

Thanks! 🙌🏻

2022-02-17 13:27 UTC, joanlopez commented on pkg/setting/setting.go
>  			defaultKey, err := defaultSec.GetKey(key.Name())
Alternatively, we could something like:

```
var defaultKey *ini.Key
if _, exists := defaultSec.KeysHash()[key.Name()]; !exists {
  defaultKey, _ = defaultSec.NewKey(key.Name(), key.Value())
} else {
  defaultKey, _ = defaultSec.GetKey(key.Name())	
}
```

PS: With proper error handling, I guess

2022-02-21 13:54 UTC, marefr reviewed
Cannot think that we're dependent on the "child-functionality" today so should be fine. Best way to know is to change and release it since we probably don't have 100% test coverage of the setting package :+1:

2022-02-22 09:29 UTC, joanlopez commented
> Cannot think that we're dependent on the "child-functionality" today so should be fine. Best way to know is to change and release it since we probably don't have 100% test coverage of the setting package 👍

Thanks for your thoughts @marefr, I'm happy to see we're aligned! In fact, we discussed it with @xlson and reached similar conclusion: it does not look like we're relying on that parent-child behavior. However, we realized there's another part of the code (DynamicKey) that could be affected by the same issue.

So, we agreed on:

i. quickly go over all the settings to do at least a simple verification that no keys are relying on that behavior
ii. fix the same issue on DynamicKey abstraction
iii. double check the most recent settings abstraction (settings provider) don't suffer from the same issues (it shouldn't)

I plan to work on that along the week.

2022-03-16 10:10 UTC, xlson commented
It would be great to get this merged and as I remember it there's not a lot of work left, do you think you will have time to finish the last few bits here?

2022-03-16 13:58 UTC, joanlopez commented
> It would be great to get this merged and as I remember it there's not a lot of work left, do you think you will have time to finish the last few bits here?

Yeah! Sorry, I've been focused on other things plus the hackathon in the middle, but planning work on that tomorrow. So, hopefully tomorrow will be ready for a final review and merge. Thanks for reminder anyway! 😊 🙏🏻

2022-03-16 15:41 UTC, xlson commented
No worries, thanks for taking care of it.

2022-04-06 08:45 UTC, xlson commented
@joanlopez are we pushing this one to 9.0?

2022-04-06 09:10 UTC, joanlopez commented
> @joanlopez are we pushing this one to 9.0?

Looks like, yes, since we had other tasks with higher priority.
It seems this has been here for a long time and no one has complained yet, so I guess we can just push it.
In any case, we'd be able to backport the fix and release a patch if needed.

Does that make sense for you @xlson? Thanks!

2022-04-06 09:12 UTC, xlson commented
Yeah, just wanted to check.

2022-04-19 10:22 UTC, xlson requested changes
adding in this so the github bot will stop complaining about my missing review ;)

> So, we agreed on:
>
> i. quickly go over all the settings to do at least a simple verification that no keys are relying on that behavior
ii. fix the same issue on DynamicKey abstraction
iii. double check the most recent settings abstraction (settings provider) don't suffer from the same issues (it shouldn't)

2022-07-09 02:14 UTC, closed without merging