Jaeger: Show loader when search options havent yet loaded
grafana/grafana pull request #45936
Opened 2022-02-25 20:34 UTC by CatPerry

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #[35523](https://github.com/grafana/grafana/issues/35523)

**Special notes for your reviewer**:

2022-02-25 22:25 UTC, CatPerry commented
Just tagging @rdubrock on this because he's my buddy and so that he can have eyes on my code. But I'll only merge with @connorlindsey approval.

2022-02-28 16:11 UTC, connorlindsey requested changes
Looks great, just a few style changes

2022-02-28 16:11 UTC, connorlindsey commented on public/app/plugins/datasource/jaeger/components/SearchForm.test.tsx
> +import { act, render, screen, waitFor } from '@testing-library/react';
Thanks for adding tests for this - looks great!

2022-02-28 17:56 UTC, connorlindsey approved these changes
Looks great!

2022-02-28 19:06 UTC, merged