Users: clean up OrgId when all user orgs are removed
grafana/grafana pull request #46003
Opened 2022-03-01 08:10 UTC by ifrost

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #20224

**Special notes for your reviewer**:

2022-03-15 09:04 UTC, ifrost commented
@grafana/backend-platform could someone please have a look a this?

2022-03-15 14:02 UTC, papagian requested changes
Thank you for your contribution! LGTM, I only have a minor suggestion.

Also, regarding [this observed behaviour](https://github.com/grafana/grafana/issues/20224#issuecomment-579867298), when we fetch the signed in user from the database [we explicitly set the org to `-1` if it's missing](https://github.com/grafana/grafana/blob/c15ddc295cc10560bb94fe4567a9b33f61ab8496/pkg/services/sqlstore/user.go#L386) so I assume that it's intentional. In any case, I have tested removing a user with admin privileges from an org and after removal is able to login but with no privileges.

2022-04-05 07:50 UTC, ifrost commented on pkg/services/sqlstore/user.go
> +	_, err := sess.ID(userID).MustCols("org_id").Update(&user)
To make it more explicit I've created a separate function for removing an org in 489c4f36273adc488e317284d50b394a1d62e247. Would that make sense? Or should I just go with an extra bool param?

2022-04-05 07:55 UTC, papagian commented on pkg/services/sqlstore/user.go
> +	_, err := sess.ID(userID).MustCols("org_id").Update(&user)
that's even better, thank you!

2022-04-05 07:55 UTC, papagian approved these changes

2022-04-06 06:35 UTC, merged