Azure Monitor: Add feature gating for new MetricsQueryEditor with resource picker
grafana/grafana pull request #46124
Opened 2022-03-02 19:49 UTC by sarahzinger

**What this PR does / why we need it**:
We are hoping to add the Resource Picker to Metrics Queries for Azure Monitor, but this will be a bigger project over several PRs, with the potential for breaking changes, so we'd like to develop it under a feature gate if possible. This allows us to start that work 

**Which issue(s) this PR fixes**:

Fixes #46058

**Special notes for your reviewer**:

2022-03-03 08:34 UTC, sunker approved these changes
Nice!

2022-03-03 08:52 UTC, andresmgot requested changes
Nice to have this since the beginning! I think we should use [Grafana feature toggles](https://grafana.com/docs/grafana/latest/packages_api/data/featuretoggles/) for this, mostly because this can be available before or after Grafana 9 (and even if it's ready, some people may need to disable it while we fix bugs).

See here some examples: https://github.com/grafana/grafana/blob/main/pkg/services/featuremgmt/registry.go. The `RequiresDevMode` setting seems pretty neat so we can merge temporary code like this one that cannot be used in production.

2022-03-03 22:15 UTC, sarahzinger commented
@andresmgot thanks for the suggestion, very cool stuff! This is my first time using these toggles, so let me know if it looks like I'm using them right :)

2022-03-04 09:11 UTC, andresmgot approved these changes
LGTM! Just some minor comments

2022-03-04 09:11 UTC, andresmgot commented on packages/grafana-data/src/types/featureToggles.gen.ts
> +  resourcePickerForMetrics?: boolean;
lol everybody is using a different case here (camelCase, snake_case, kebab-case...). Anyway, I would put "azure" somewhere in the name so it's clear its scope.

2022-03-04 09:11 UTC, andresmgot commented on pkg/services/featuremgmt/registry.go
> +			State:       FeatureStateAlpha,
what about setting `RequiresDevMode: true` so we make sure nobody uses it before it's ready? Also we can use `FrontendOnly: true` but I am not really sure what that does.

2022-03-14 19:07 UTC, merged