Trace view search - next/prev
grafana/grafana pull request #46527
Opened 2022-03-14 11:28 UTC by joey-grafana

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-03-17 16:30 UTC, connorlindsey commented on packages/jaeger-ui-components/src/TracePageHeader/TracePageSearchBar.tsx
> +      margin-top: 8px;
Kind of hacky, but I wanted to add some margin between search bar and the container - so I added padding + margin to give spacing. Also added box-shadow/border-radius to distinguish the search bar a bit more. 

Would be cool in the future to detect when it's scrolled and apply the box-shadow then.

2022-03-17 16:31 UTC, connorlindsey approved these changes
Made a few changes to the styling and removed the clear button to use the Input's clear instead. Let me know what you think

2022-03-30 10:52 UTC, ifrost requested changes
Looks good, just left a few minor comments.

2022-03-30 10:52 UTC, ifrost commented on packages/jaeger-ui-components/src/TracePageHeader/TracePageSearchBar.tsx
> +      z-index: 5;
Would it make sense to use `${theme.zIndex....}` here?

2022-03-30 10:52 UTC, ifrost commented on packages/jaeger-ui-components/src/TracePageHeader/TracePageSearchBar.tsx
> +    suffix: suffix,
```suggestion
    suffix,
```

2022-03-30 10:52 UTC, ifrost commented on public/app/features/explore/TraceView/TraceViewContainer.tsx
> +export function transformDataFrames(frame?: DataFrame): Trace | null {
Looks like a utility function. Could we move it out from to `utils`?

2022-03-30 18:23 UTC, ifrost approved these changes
🚀

2022-03-31 08:43 UTC, merged