Plugins: Pass OAuth Token to CallResource Function
grafana/grafana pull request #47028
Opened 2022-03-29 19:54 UTC by bradenhs

**What this PR does / why we need it**:

This PR ensures there is OAuthPassThru support for the `CallResource` function in plugins in addition to the `QueryData` function. Note: This PR doesn't tackle getting the appropriate headers forwarded for additional endpoints such as `CheckHealth`. I probably won't tackle that work personally as I don't need it but I expect folks will want that as well.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/45938

Provided this general approach looks good I'd be happy to figure out how to add tests for this.

2022-04-04 16:42 UTC, wbrowne requested changes
Thanks for your contribution @bradenhs, but unfortunately this breaks the following endpoints:
- `/plugins/:pluginId/resources`
- `/api/plugins/:pluginId/resources/*`

The reason being that these have no strict dependency on a data source existing for a given plugin. This is quite confusing though as the code does pass around a `dsUID`, and it's not made clear that this can be empty. In the future, these should likely be two separate flows to avoid confusion.

I think for now though we could simply do:

```golang
...
clonedReq.URL = urlPath

if dsUID != "" {
	ds, err := hs.DataSourceCache.GetDatasourceByUID(c.Req.Context(), dsUID, c.SignedInUser, c.SkipCache)
	if err != nil && !errors.Is(err, models.ErrDataSourceNotFound) {
		handleCallResourceError(err, c)
		return
	}

	if hs.DataProxy.OAuthTokenService.IsOAuthPassThruEnabled(ds) {
		if token := hs.DataProxy.OAuthTokenService.GetCurrentOAuthToken(c.Req.Context(), c.SignedInUser); token != nil {
			clonedReq.Header.Add("Authorization", fmt.Sprintf("%s %s", token.Type(), token.AccessToken))

			idToken, ok := token.Extra("id_token").(string)
			if ok && idToken != "" {
				clonedReq.Header.Add("X-ID-Token", idToken)
			}
		}
	}
}

if err = hs.makePluginResourceRequest(c.Resp, clonedReq, pCtx); err != nil {
...
``

WDYT?

2022-04-04 18:27 UTC, bradenhs commented
Thanks @wbrowne! I made your suggested change.

2022-04-05 09:02 UTC, wbrowne requested changes
Great stuff. Just noticed a couple things!

2022-04-05 09:02 UTC, wbrowne commented on pkg/api/plugins.go
> +		if ds != nil && hs.DataProxy.OAuthTokenService.IsOAuthPassThruEnabled(ds) {
No need to `nil` check ds here as we presume it's okay when checking for `err` above

2022-04-05 09:02 UTC, wbrowne commented on pkg/api/plugins.go
> +		if err != nil && !errors.Is(err, models.ErrDataSourceNotFound) {
```suggestion
		if err != nil {
			if errors.Is(err, models.ErrDataSourceNotFound) {
				c.JsonApiErr(404, "Datasource not found", err)
				return
			}

			c.JsonApiErr(500, "Failed to get datasource", err)
			return
		}
```

2022-04-05 15:07 UTC, bradenhs commented
Thanks for the feedback! I made your suggested updates.

2022-04-05 15:40 UTC, wbrowne approved these changes
LGTM. Thanks a lot @bradenhs!

2022-04-05 15:40 UTC, merged