bugfix: fix proper type of setting maxConcurrentShardRequests
grafana/grafana pull request #47120
Opened 2022-03-31 10:24 UTC by alexandrst88

**What this PR does / why we need it**:
fix https://github.com/grafana/grafana/issues/47042
**Which issue(s) this PR fixes**:
https://github.com/grafana/grafana/issues/47042
<!--

- Automatically closes linked issue when the Pull Request is merged.

Fixes #47042

2022-03-31 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=47120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=47120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=47120) it.</sub>

2022-04-05 10:16 UTC, gabor commented
hi @alexandrst88 , thanks for the pull request.

so, the problem is:
when you create an elasticsearch datasource, and do not modify the max-concurrent-shard-requests value there, it gets stored as a json-number.
but, if you modify it (when creating the datasource, or later, when modifying the datasourcce), it gets stored as a json-string.

as you see, at a given time, the value can be a json-number or a json-string. we need to be able to read it in both formats. so i would recommend to modify the pull-request, to:
1. try to decode it as a string first
2. if it fails, try to decode it as a number
3. if that fails, use the value `256`. (in your PR an error is returned in that case, but the old version never returned an error, just used the default-value of `256`, i recommend keeping the behavior the same)

2022-04-05 10:17 UTC, gabor requested changes
nice work!

as i described in the comment above, it is possible that the value is a json-number. so, two changes are needed:

1. if the string-decode fails, try to float64-decode
2. if float64-decode fails, use the default-value (`256`), do not return an error

2022-04-07 10:21 UTC, alexandrst88 commented
@gabor could you please take a look?

2022-04-07 13:26 UTC, gabor requested changes
nice! using a type-switch makes it very readable. there are two small things to fix and it should be good to merge.

2022-04-07 13:50 UTC, alexandrst88 commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +		switch jsonData["maxConcurrentShardRequests"].(type) {
done

2022-04-07 13:50 UTC, alexandrst88 commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +			maxConcurrentShardRequests, _ = strconv.ParseInt(jsonData["maxConcurrentShardRequests"].(string), 10, 64)
done

2022-04-08 11:01 UTC, gabor requested changes
nearly done! i think you forgot to replace value with `v` in one place

2022-04-08 11:01 UTC, gabor commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +			maxConcurrentShardRequests, err = strconv.ParseFloat(jsonData["maxConcurrentShardRequests"].(string), 64)
```suggestion
			maxConcurrentShardRequests, err = strconv.ParseFloat(v, 64)
```

2022-04-08 11:01 UTC, gabor commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +			maxConcurrentShardRequests, err = strconv.ParseFloat(jsonData["maxConcurrentShardRequests"].(string), 64)
i think you forgot to replace this with `v`

2022-04-08 11:01 UTC, gabor commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +			maxConcurrentShardRequests, err = strconv.ParseFloat(jsonData["maxConcurrentShardRequests"].(string), 64)
i think you forgot to replace this with `v`

2022-04-08 13:08 UTC, alexandrst88 commented on pkg/tsdb/elasticsearch/elasticsearch.go
> +			maxConcurrentShardRequests, err = strconv.ParseFloat(jsonData["maxConcurrentShardRequests"].(string), 64)
oh, thank you! fixed.

2022-04-11 08:08 UTC, gabor approved these changes
well done!

2022-04-11 08:29 UTC, merged

2022-04-11 08:34 UTC, gabor commented
@alexandrst88 thanks for your work on this PR! it is merged now, will be available in grafana 8.5.0, and also in the next 8.4.x release.

2022-04-11 08:38 UTC, alexandrst88 commented
> @alexandrst88 thanks for your work on this PR! it is merged now, will be available in grafana 8.5.0, and also in the next 8.4.x release.

thanks for help and review!