Prometheus: Move count_values from function to aggregation
grafana/grafana pull request #47260
Opened 2022-04-04 13:01 UTC by aocenas

count_values was defined as function but it should have been an aggregation.
Contains also some changes to the aggregation factory function and moved code that is already shared with loki to /shared dir. 

Also fixes bug, where aggregations change to their `_by` variant every time user blured other param input.

2022-04-04 13:02 UTC, aocenas commented on public/app/plugins/datasource/prometheus/querybuilder/aggregations.ts
> -/**
All this code was moved to shared/operationsUtils as it is already used in loki

2022-04-04 13:03 UTC, aocenas commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +export function createAggregationOperationWithParam(
The main change is this function. Before this code was inside `createAggregationOperation` and just special cased for topK/bottomK aggregations.

2022-04-04 13:04 UTC, aocenas commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +  operations[2].params.unshift(...paramsDef.params);
Before we weren't adding params to the `without` variant for some reason so this adds it also there.

2022-04-06 08:28 UTC, ivanahuckova requested changes
Left some spell-check fixes/feedback below. Overall looks good, but it breaks Loki's topk/bottomk operations because it still probably uses `createAggregationOperation` instead of new `createAggregationOperationWithParam`. 
<img width="749" alt="image" src="https://user-images.githubusercontent.com/30407135/161930796-416bbcfb-c5ec-4c64-9566-c8df0fcc456c.png">

2022-04-06 08:28 UTC, ivanahuckova commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +function getLastLabelRemovedHandler(changeToOperartionId: string) {
```suggestion
function getLastLabelRemovedHandler(changeToOperationId: string) {
```

2022-04-06 08:28 UTC, ivanahuckova commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +function getLastLabelRemovedHandler(changeToOperartionId: string) {
replace all `changeToOperartionId` -> `changeToOperartionId `

2022-04-06 08:28 UTC, ivanahuckova commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +function getOnLabelAdddedHandler(changeToOperartionId: string) {
```suggestion
function getOnLabelAdddedHandler(changeToOperationId: string) {
```

replace all `changeToOperartionId` -> `changeToOperartionId `

2022-04-06 08:28 UTC, ivanahuckova commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +function getOnLabelAdddedHandler(changeToOperartionId: string) {
```suggestion
function getOnLabelAddedHandler(changeToOperartionId: string) {
```

2022-04-06 08:28 UTC, ivanahuckova commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +function getOnLabelAdddedHandler(changeToOperartionId: string) {
replace all 'getOnLabelAdddedHandler` -> `getOnLabelAddedHandler`

2022-04-06 11:52 UTC, aocenas commented on public/app/plugins/datasource/prometheus/querybuilder/shared/operationUtils.ts
> +    if (op.params.length === def.params.length) {
Semi-related fix. As this wasn't checked before any time this was called (like on input onBlur) the type of the operation changed.

2022-04-06 13:53 UTC, ivanahuckova requested changes
There is still an issue with Loki query builder. On main, when you select `TopK` aggregation, it adds also range function `rate`. After your change, this is not a a case anymore. 

Main: 

https://user-images.githubusercontent.com/30407135/161990851-be791db1-9445-4723-8cc0-6bc6b63b62e3.mov

Your branch: 

https://user-images.githubusercontent.com/30407135/161990883-2e7013e2-e0ff-44b5-8041-eaf35273fd30.mov

2022-04-08 12:12 UTC, ivanahuckova approved these changes
Nice, LGTM. 🙌 We probably want to backport this to 8.5.0.

2022-04-12 14:08 UTC, merged