grafana-ui: logRowContext: improve field-selection
grafana/grafana pull request #47936
Opened 2022-04-20 10:35 UTC by gabor

the LogRowContext code needs to access certain logs-related fields, like the line-field, or the timestamp-field.
but, the way it accesses them is not the same as how the logs_model accesses them. this could cause problems.
this PR changes the LogRowContext code to use the same logic as uses by logs_model:
- selecting the timestamp field, we choose the first field of type=time, as done at https://github.com/grafana/grafana/blob/main/public/app/core/logs_model.ts#L359
- selecting the line-field, we choose the first field of type=string, as done at https://github.com/grafana/grafana/blob/main/public/app/core/logs_model.ts#L358

an even better approach would be to export some standardized functions from grafana-something (grafana-data?), to do the `getTimestampField`, `getLogLineField` etc., but this small change should also help to improve the situation.

2022-04-20 10:54 UTC, ivanahuckova approved these changes
Yes!

2022-04-20 15:30 UTC, andresmgot approved these changes
Tried with CloudWatch logs and it's working for me:

![Screenshot from 2022-04-20 17-28-42](https://user-images.githubusercontent.com/4025665/164267346-4d0be273-e5fb-4c37-8499-720a5f67a060.png)

(let me know if you want me to test something more specific, that was a query with a timestamp and a string)

2022-04-21 09:47 UTC, andresmgot requested changes
Sorry, after re-testing this, it seems that it's not working for Cloudwatch. In the explore view, the "Show Context" link no longer shows related rows. After this change:

![Screenshot from 2022-04-21 10-49-55](https://user-images.githubusercontent.com/4025665/164428435-de753a23-9e4d-4846-9cd3-b68d29081953.png)

Before this change (code in `main`):

![Screenshot from 2022-04-21 10-47-51](https://user-images.githubusercontent.com/4025665/164428503-f54a9c9a-de9f-406d-af5e-1634a512f3f4.png)

2022-04-21 09:48 UTC, gabor commented
thanks @andresmgot for the testing. i will close this PR without merging it, it seems the change is not as backward-compatible as i hoped.

2022-04-21 09:48 UTC, closed without merging