Alerting: introduce ruler endpoints for proxying using the datasource…
grafana/grafana pull request #48046
Opened 2022-04-21 11:16 UTC by papagian

… UID

**What this PR does / why we need it**:
follow-up of #47829
targets #47978 (it depends on some changes introduced there; I will change the target as soon as it will be merged)
This is part of work of removing the sequential IDs from the API and store layers. For more details you can refer to [this doc](https://docs.google.com/document/d/1LN55IDeLXQEPbuIJR2l02VM5I5GJLNpOlUQDfThDKe8/edit).

More specifically, it:
* introduces new ruler endpoints that expect a `DatasourceUID` path parameter
* add new authorisation actions for the new endpoints

Example of a successful request to a known datasource UID:
```
curl -X 'GET'   'http://localhost:3000/api/ruler/uid/7DEsN5_Mk/api/v1/rules/test'   -H 'accept: application/json'   -H 'authorization: Basic YWRtaW46YWRtaW4='
{"test":[{"name":"group42","rules":[{"alert":"logs_exist","expr":"rate({cluster=\"us-central1\", job=\"loki-prod/loki-canary\"}[1m]) \u003e 0","for":"1m"}]},{"name":"group101","rules":[{"alert":"logs_exist","expr":"rate({cluster=\"us-central1\", job=\"loki-prod/loki-canary\"}[1m]) \u003e 0","for":"2m"}]}]}
```

Example of requesting an unknown datasource UID:
```
curl -X 'GET' \
  'http://localhost:3000/api/ruler/uid/unknown/api/v1/rules' \
  -H 'accept: application/json' \
  -H 'authorization: Basic YWRtaW46YWRtaW4='
{"error":"unexpected backend type (unknown)","message":"unexpected backend type (unknown)","traceID":"00000000000000000000000000000000"}
```

2022-04-25 06:27 UTC, joeblubaugh requested changes
I want to finish the discussion we're having on #47978 about the structure of the path before this is merged.

2022-05-03 08:46 UTC, gillesdemey approved these changes
LGTM, just one suggestion

2022-05-03 08:46 UTC, gillesdemey commented on pkg/services/ngalert/api/lotex_ruler_test.go
> -			name:        "with an invalid datasource ID",
Can we change this test to assert if an empty string returns an error instead? (if we don't have a similar test yet)

2022-05-05 07:10 UTC, joeblubaugh approved these changes

2022-05-05 11:58 UTC, merged