Add start time and end time parameters while querying tempo traces
grafana/grafana pull request #48068
Opened 2022-04-21 14:50 UTC by bikashmishra100

**What this PR does / why we need it**:
Recently https://github.com/grafana/tempo added start and end timestamp to /api/traces API via https://github.com/grafana/tempo/pull/1388. This is done to make the searches faster  by scanning only the blocks within the start and end time. We want to consume the parameters so that the start and end timestamps are supplied from Grafana.

**Special notes for your reviewer**:
Aligning this PR with @joe-elliott. I hope this PR satisfies the requirements that was mentioned in https://github.com/grafana/tempo/issues/1373. The timestamps will be the range of the search query given by the user.

cc: @sagarwala, @ashwinidulams

2022-04-21 14:59 UTC, joe-elliott commented
It seems like the time range is based on the same as the search. Is this true? 

My concern with this is that you can find a trace using search, but not receive the entire trace when you query by id if we make this change. If the trace overlaps either the start or end of the search range it is possible it will not be returned in its entirety. this is unlikely, but possible.

I'm wondering if we should make this configurable, defaulted to false for backwards compat?

2022-04-21 15:06 UTC, bikashmishra100 commented
Sure, making it configurable is what I can work on.

I too had this thought that if user provides a very narrow window to search for logs in case the exact time of an error is known, the entire trace may or may not fit inside the window. Unfortunately I do not have any great ideas at this moment. Does fixed buffers (which also could be configurable) e.g. 30 minutes beyond the search window make sense ?

2022-04-22 14:39 UTC, joe-elliott commented
I think a hardcoded value like `30m` would be a fine place to start, but likely this should be configurable as well. Thanks for looking into this improvement!

2022-05-19 12:17 UTC, connorlindsey commented on pkg/tsdb/tempo/tempo_test.go
>  		assert.Equal(t, 1, len(req.Header))
Would be nice to also assert that the query is formatted correctly in this test case

2022-05-19 12:18 UTC, connorlindsey requested changes
Looks good, but needs to take into account a configurable time shift

2022-05-19 12:29 UTC, bikashmishra100 commented
Apologies for not being able to work on this recently as I had to work on and mitigate a production incident. I will work on this over the weekend and update it.

2022-05-19 12:39 UTC, connorlindsey commented
@bikashmishra100 Absolutely no worries, we really appreciate you being willing to open a PR for this. If you need any help or want to pass this off for us to finish up, we can help too

2022-05-19 12:45 UTC, bikashmishra100 commented
No problem, this is a trivial thing. I would not bother you/your team. I will work on it and update here.

2022-06-20 00:57 UTC, hanjm commented
still useful

2022-06-30 13:38 UTC, hanjm commented
@connorlindsey  @bikashmishra100 I think it could use the span start time with some duration range instead of the search time, like spanStartTime-1h~spanEndtime+1h. 

i implement a tricky proxy in production, it add timestamp in traceid string (like xxxx_ts), then when we click to view trace detail,  the proxy split special traceid to traceid and timestamp, which make the performance improve fast a lot!

2022-09-13 13:47 UTC, aocenas approved these changes

2022-09-27 12:51 UTC, aocenas commented on public/app/plugins/datasource/tempo/configuration/QuerySettings.tsx
> +          tooltip="Shifts the start time of the span. Default 0 (Time units can be used here, for example: 5s, 1m, 3h)"
I think this needs a bit longer explanation and better name.

label: Time shift for start of search time range
tooltip: Shifts the start of the time range when searching by trace ID. This is needed as searching for traces can return traces that do not fully fall into the search time range. If trace is searched by trace id in the same time range it won't show up. This shift should allow for traces to fall fully into the shifter time range. The longer your traces the higher the time shift should be used. Default 30m (Time units can be used here, for example: 5s, 1m, 3h).

@joe-elliott does this make sense? Also I wonder do we need start shift? Don't we only need the end shift? Meaning does the search return traces that started before the search time range but overlap a bit? Cause I would assume we need only end range shift.

2022-09-27 12:54 UTC, aocenas commented
>If the trace overlaps either the start or end of the search range it is possible it will not be returned in its entirety. this is unlikely, but possible.

@joe-elliott to understand this: Does this mean that if you query by trace id and there is partial overlap with the trace start-end and the time range, tempo will return partial trace? So at this moment even if we use the shift, this can still happen and user won't really know that the trace is partial, is that right?

2022-10-12 15:00 UTC, empollard commented
Hi Team! I see a label on this for no-backport. We currently have  a customer waiting for this fix and it looks like we don't have an ETA for 9.3.0 yet. Would there be some way to backport this to 9.2 or 9.1.6?

Thanks!

2022-10-21 14:00 UTC, aocenas approved these changes

2022-10-21 14:35 UTC, connorlindsey approved these changes

2022-10-21 14:38 UTC, merged

2022-10-21 17:02 UTC, joe-elliott commented
> @joe-elliott to understand this: Does this mean that if you query by trace id and there is partial overlap with the trace start-end and the time range, tempo will return partial trace? So at this moment even if we use the shift, this can still happen and user won't really know that the trace is partial, is that right?

@aocenas That is correct. When specifying the start/end parameters you are instructing Tempo to search a subset of the blocks on the backend. This may result in a partial trace being returned. It will be up the operator to set the start/end time shift parameters to feel confident that all spans for a given trace will be within the window.

2022-10-21 17:05 UTC, aocenas commented
@joe-elliott is there some metadata in the response indicating that this is happening? So that we can show some warning in the UI something like "showing partial trace, widen time range to see it whole".

2022-10-21 17:22 UTC, joe-elliott commented
There is no way to know if the trace exists elsewhere except for Tempo to search for it. At which point it's basically performing the full search anyway.

This feature is for those people who have a long retention at a high volume. In this case you could set the start/end time shift to something like `1d` and vastly reduce the amount of data searched when doing a trace by id lookup. if your traces are normally only a few seconds you can feel quite comfortable that you are getting nice performance gains with an extremely low chance of returning a partial trace.