Docs: Add api keys roles, actions and scopes documentation
grafana/grafana pull request #48448
Opened 2022-04-28 15:04 UTC by kalleep

**What this PR does / why we need it**:
I noticed that api keys permissions where not documented for access control.
* Add fixed roles
* Add all available permissions
* Fix scopes for annotations

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-04-28 15:05 UTC, chri2547 approved these changes
LGTM! Ship it!

2022-04-28 16:15 UTC, achatterjee-grafana requested changes, later dismissed
Added some comments. Change all instances of api to API, unless it is part of the code. Thanks!

2022-04-28 16:15 UTC, achatterjee-grafana commented on docs/sources/enterprise/access-control/custom-role-actions-scopes.md
> +| `apikeys:create`                     | n/a                                                                                     | Create api keys
```suggestion
| `apikeys:create`                     | n/a                                                                                     | Create API keys.                                                                                                                                                                                  |
```

2022-04-28 16:15 UTC, achatterjee-grafana commented on docs/sources/enterprise/access-control/custom-role-actions-scopes.md
> +| `apikeys:read`                       | `apikeys:*`<br>`apikeys:id:*`                                                           | Read api keys
```suggestion
| `apikeys:read`                       | `apikeys:*`<br>`apikeys:id:*`                                                           | Read API keys.                                                                                                                                                                                    |
```

2022-04-28 16:15 UTC, achatterjee-grafana commented on docs/sources/enterprise/access-control/custom-role-actions-scopes.md
> +| `apikeys:delete`                     | `apikeys:*`<br>`apikeys:id:*`                                                           | Delete api keys
```suggestion
| `apikeys:delete`                     | `apikeys:*`<br>`apikeys:id:*`                                                           | Delete API keys.                                                                                                                                                                                  |
```

2022-04-28 16:15 UTC, achatterjee-grafana commented on docs/sources/enterprise/access-control/custom-role-actions-scopes.md
> +| `apikeys:*`<br>`apikeys:id:*`             | Restrict an action to a set of api keys. For example, `apikeys:*` matches any api key, `apikey:id:1` matches the api key whose id is `1`
```suggestion
| `apikeys:*`<br>`apikeys:id:*`             | Restrict an action to a set of API keys. For example, `apikeys:*` matches any API key, `apikey:id:1` matches the API key whose id is `1`.                                                                                                           |
```

2022-04-29 11:39 UTC, gamab approved these changes

2022-04-29 11:39 UTC, gamab commented on docs/sources/enterprise/access-control/rbac-fixed-basic-role-definitions.md
> +| `fixed:apikeys:writer`                 | All permissions from `fixed:apikeys:reader` and <br> `apikeys:create` <br> `apikeys:delete` for scope `apikeys:*`
Extreme nitpicking :sweat_smile: 
```suggestion
| `fixed:apikeys:reader`                 | `apikeys:read` for scope `apikeys:*`                                                                                                                                                                                                                                     | Read all api keys.                                                                                                                                                                                                                                                                    |
| `fixed:apikeys:writer`                 | All permissions from `fixed:apikeys:reader` and <br> `apikeys:create` <br> `apikeys:delete` for scope `apikeys:*`                                                                                                                                                        | Read, create, delete all api keys.                                                                                                                                                                                                                                                    |
```

2022-05-02 07:54 UTC, kalleep commented
Hey @achatterjee-grafana can you review again after new changes and unblock if its good?

2022-05-02 08:06 UTC, eleijonmarck approved these changes

2022-05-03 07:34 UTC, merged