Tracing: Add ability to write trace to metrics query
grafana/grafana pull request #48824
Opened 2022-05-06 16:55 UTC by connorlindsey

**What this PR does / why we need it**:
Lets users write the query to be run in the trace to metrics link
![image](https://user-images.githubusercontent.com/12838032/167172126-837cae4d-488c-4b8d-ac7c-6923d78b490e.png)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
I would like to use a Prometheus query field instead of a plain input in this or the next PR. Waiting for input from the metrics squad

2022-05-08 08:34 UTC, joey-grafana approved these changes
LGTM 👍

2022-05-09 08:17 UTC, brendamuir requested changes

2022-05-09 08:17 UTC, brendamuir commented on docs/sources/datasources/zipkin.md
> +This is a configuration for the experimental trace to metrics feature. Select the target Prometheus data source and enter the desired query.
```suggestion
To configure trace to metrics, select the target Prometheus data source and enter the desired query.
```

2022-05-09 08:17 UTC, brendamuir commented on docs/sources/datasources/zipkin.md
> +-- **Query -** The query which will run when navigating from a trace to the metrics data source.
```suggestion
-- **Query -** Query that runs when navigating from a trace to the metrics data source.
```

2022-05-10 23:00 UTC, connorlindsey commented
@brendamuir Thanks for the suggestions, I've applied them to the 3 sets of docs.

2022-05-11 08:35 UTC, brendamuir approved these changes

2022-05-11 14:39 UTC, merged