Transformation: Added variance and standard deviation
grafana/grafana pull request #48844
Opened 2022-05-08 12:23 UTC by selvavm

**What this PR does / why we need it**: This PR adds additional options in the Legends dropdown to display Variance (Population), Standard deviation (Population), Variance (Sample) and Standard deviation (Sample). 

**Which issue(s) this PR fixes**:  #46313

Fixes #46313

**Special notes for your reviewer**: This is my first time with Grafana development. I have implemented the calculation based on Welford's method so that we can avoid nested for loop. I have tested it and it works as expected. I have some commented code, please check them and let me know if I can delete it.

2022-05-08 12:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=48844) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=48844) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=48844) it.</sub>

2022-05-09 08:19 UTC, brendamuir requested changes

2022-05-09 08:19 UTC, brendamuir commented on docs/sources/panels/calculation-types.md
>  Refer to the following list of calculations you can perform in Grafana. You can find these calculations in the **Transform** tab and in the bar gauge, gauge, and stat visualizations.
```suggestion
You can perform the following calculations in Grafana. Navigate to the **Transform** tab and in the bar gauge, gauge, and stat visualizations.
```

2022-05-10 06:23 UTC, brendamuir approved these changes

2022-05-10 06:40 UTC, brendamuir approved these changes

2022-05-10 16:57 UTC, selvavm commented
Hi @brendamuir @axelavargas @leventebalogh @kaydelaney  @gguillotte-grafana. Is there anything else I should do to get this PR merged? Is there any concern in this feature?

2022-05-11 08:37 UTC, brendamuir commented
Fine from my point of view!

2022-05-11 13:11 UTC, achatterjee-grafana approved these changes

2022-05-11 15:59 UTC, selvavm commented
@brendamuir Great and thanks. I don’t have access to merge or add labels. So, not sure what needs to happen to proceed.

2022-05-12 00:16 UTC, merged

2022-05-27 04:57 UTC, selvavm commented
Hi @torkelo. May I know what needs to be done to include this PR? Can't you do the developer review approval?