Allow specifying LDAP timeout
grafana/grafana pull request #48870
Opened 2022-05-09 20:39 UTC by hannes-256

The default timeout is 60 seconds which is pretty long
See: https://github.com/go-ldap/ldap/blob/v2.5.1/conn.go#L107

2022-05-09 20:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=48870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=48870) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=48870) it.</sub>

2022-05-10 06:19 UTC, brendamuir requested changes

2022-05-10 06:19 UTC, brendamuir commented on docs/sources/auth/ldap.md
> +# Timeout in seconds (applies to each host specified in the 'host' entry (space separated))
```suggestion
# Timeout in seconds. Applies to each host specified in the 'host' entry (space separated).
```

2022-05-10 06:41 UTC, brendamuir approved these changes

2022-05-16 07:10 UTC, brendamuir approved these changes

2022-05-23 12:03 UTC, Jguer approved these changes
Was going to suggest unexporting the functions, with that done everything seems alright. Thanks for your contribution

2022-05-23 12:41 UTC, gamab approved these changes
Looks good. I just set the default timeout when timeout is `0` to ensure backward compatibility. :+1:

2022-07-08 06:52 UTC, Jguer commented
Merging now @hannes-256 :slightly_smiling_face: , thanks for taking the time to contribute this

2022-07-08 06:52 UTC, merged