Convert `packages/jaeger-ui-components/src/TraceTimelineViewer/SpanBar.test.js` to RTL
grafana/grafana pull request #49107
Opened 2022-05-17 17:51 UTC by xrisaD

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

2022-05-17 17:52 UTC, xrisaD commented
@ashharrison90

2022-05-18 10:01 UTC, ashharrison90 requested changes
@xrisaD thanks again for this 😄 

couple of suggestions. you'll also need to update the selector here: https://github.com/grafana/grafana/blob/main/packages/grafana-e2e-selectors/src/selectors/components.ts#L268 to be `spanBar: () => 'data-testid SpanBar--wrapper'`

in terms of the enterprise check, it's a fairly new thing we've added. i'm not sure if it works for contributions from forks 🤔 don't worry about it - it's something i'll need to look into. 👍

2022-05-18 10:01 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanBar.test.js
> +    expect(screen.getByTestId('popover').querySelectorAll('div')).toHaveLength(2);
```suggestion
    render(<SpanBar {...props} />);
    expect(screen.getAllByTestId('SpanBar--logMarker')).toHaveLength(2);
```

2022-05-18 11:05 UTC, xrisaD commented
@ashharrison90 thank you for the code review! 😄

2022-05-18 11:06 UTC, ashharrison90 approved these changes
looks great! 🥳

2022-05-18 11:17 UTC, ashharrison90 commented
@xrisaD just looking into why the e2e tests are failing... probably something silly i forgot 😅

2022-05-18 11:41 UTC, ashharrison90 commented
@xrisaD i pushed the fix directly in https://github.com/grafana/grafana/pull/49107/commits/afc80e2fbfe4bb599f0b98f54b6f7d8555ec9c6e as i was struggling to think of a nice way of explaining it. hope you don't mind 😅 

feel free to check it out 😄

2022-05-18 12:00 UTC, merged