Convert `packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/AccordianText.test.js` and `packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/TextList.test.js`  to RTL
grafana/grafana pull request #49148
Opened 2022-05-18 10:01 UTC by xrisaD

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #48253

**Special notes for your reviewer**:

2022-05-18 12:23 UTC, ashharrison90 requested changes
great start! 🙌

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/AccordianText.test.js
> +    const r = render(<AccordianText {...props} />);
i'd just move the `render` function out of the `beforeEach` and into each test. then you don't need `rerender` at all.

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/AccordianText.test.js
> +    });
let's just keep it simple:

```suggestion
    props.isOpen = true;
    render(<AccordianText {...props} />);
    warnings.forEach((warning) => {
      expect(screen.getByText(warning)).toBeInTheDocument();
    });
```

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/AccordianText.tsx
> +        data-testid="AccordianText--header"
same as before, `data-testid` is the correct format so i'd remove the `data-test-id` one and fix anything that needs fixing 🙂

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/TextList.test.js
> +    render(<TextList data={data} />);
i'd move the render out of the `beforeEach` and into each test

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/TextList.test.js
> +    expect(screen.getAllByTestId('TextList')).toHaveLength(1);
```suggestion
    expect(() => render(<TextList data={data} />)).not.toThrow();
```

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/AccordianText.test.js
> +    expect(screen).toBeDefined();
```suggestion
    expect(() => render(<AccordianText {...props} />)).not.toThrow();
```

2022-05-18 12:23 UTC, ashharrison90 commented on packages/jaeger-ui-components/src/TraceTimelineViewer/SpanDetail/TextList.tsx
> +};
can you add some info for why this new function is needed? 🤔

2022-05-18 15:15 UTC, xrisaD commented
Why I added the `getRow` function:

When we test the `TextList` component we use as `data` a list of  dicts at the `TextList.test.js`, while at the  `TextList.test.js`the warnings we are passing is a list of strings. The existing solution (return the row) worked when having a list of strings but didn't work when having a list of dicts. I was getting the following error:

` Error: Uncaught [Error: Objects are not valid as a React child (found: object with keys {key, value}). If you meant to render a collection of children, use an array instead.]`


@ashharrison90 Probably there could be a better solution?

2022-05-19 09:05 UTC, ashharrison90 requested changes
@xrisaD ah i see...

looking at the types we've defined for data in `TextList`, it should be an array of strings. so i would say we can remove the `getRow` function and change the `data` in the test file to be an array of strings instead, e.g. `const data = ['client', 'mos-def'];`

once you've done that and merged with main i think this looks great 👌

2022-05-20 07:11 UTC, xrisaD commented
@ashharrison90 ok, I made these changes ✔️ 😄

2022-05-20 09:44 UTC, ashharrison90 approved these changes
looks great! 🙌

2022-05-20 10:02 UTC, merged