ci: Depend on init-enterprise for gen-cue verify
grafana/grafana pull request #50191
Opened 2022-06-03 18:01 UTC by sdboyer

**What this PR does / why we need it**:

This makes the `verify_gen_cue_step` depend on the cloning enterprise steps in the appropriate pipelines, following the same pattern as `wire_install_step`.

(TBH, i wonder if we should make `wire_install_step` depend on `verify_gen_cue_step`...)

i feel like there was another thing we talked about doing, @dsotirakis? can't recall now :/

**Which issue(s) this PR fixes**:

No issue posted for it, but [build failures like this](https://drone.grafana.net/grafana/grafana-private-mirror/1352/5/14) are what we're aiming to fix. Those will start mattering when we cut the next release after 9.0.0.

**Special notes for your reviewer**:

2022-06-08 08:24 UTC, dsotirakis requested changes
You have to:
1. Run `make drone`
2. `make drone` will fail with an `invalid dependencies` or something, because `wire-install` depends on `verify-gen-cue`, but this step runs after `wire-install`, so it fails. What you have to do I think is to include `verify-gen-cue` in the `init_steps` inside the `*.star` files **before** `wire-install`.
Again, not sure if we have to add this dependency now.

2022-06-08 09:26 UTC, sdboyer commented on scripts/drone/steps/lib.star
> +        ],
Yeah, i'm not worried about stability of this particular makefile directive. I've run it hundreds of times, and others have as well, and the behavior is pretty straightforward.

2022-06-08 09:26 UTC, sdboyer commented
Derp, i always forget `make drone` 😠

2022-06-09 06:48 UTC, dsotirakis approved these changes
LGTM! Let's see that in action!

2022-06-09 06:48 UTC, merged