Alerting: Fix Slack notification preview
grafana/grafana pull request #50230
Opened 2022-06-06 08:15 UTC by ekrucio

**What this PR does / why we need it**:
When we're mentioning users, groups or channels the notification body is missing "text" field, which is required by Slack's Notification API -> https://api.slack.com/reference/messaging/payload .

**Which issue(s) this PR fixes**:
Fixes -> https://github.com/grafana/grafana/issues/42768

Notification with correctly displayed text -> 
<img width="366" alt="Screenshot 2022-06-05 at 20 39 47" src="https://user-images.githubusercontent.com/15233365/172122198-6cd9d8b3-1fbe-4c42-9fc5-500f62e45164.png">

2022-06-06 08:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=50230) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=50230) before we can accept your contribution.<br/><hr/>**krastan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=50230) it.</sub>

2022-06-07 02:28 UTC, joeblubaugh commented
Thanks for making this submission! I've verified on 9.0 as well and I'll set the PR so it merges into the 9.0 release.

2022-06-07 08:08 UTC, ekrucio commented
> Thanks for making this submission! I've verified on 9.0 as well and I'll set the PR so it merges into the 9.0 release.

@joeblubaugh Glad you're okay with it! Sorry but I'm not aware with your PR flow, so what're the next steps? Would we merge it soon, or I should check it frequently and rebase/fix conflicts when they arise until it's merged?

2022-06-07 08:20 UTC, joeblubaugh commented
@ekrucio I’ll do a review and then merge it if everything looks good. I was waiting for CI to pass before reviewing the submission.

2022-06-07 13:34 UTC, santihernandezc requested changes
Thanks for taking the time to fix this, I tested it and it's working fine 🚀 
I requested some changes, and the CI pipeline is failing, so check if merging `grafana:main` into your branch solves that.

2022-06-07 13:54 UTC, ekrucio commented on pkg/services/ngalert/notifier/channels/slack.go
> +		req.Text = tmpl(sn.Title)
Absolutely agree, will fix it.

2022-06-07 13:56 UTC, ekrucio commented on pkg/services/ngalert/notifier/channels/slack.go
> +	Text        string                   `json:"text"`
I agree, but my logic was that if no text is provided there would be an empty string, which the Slack API would accept and should seng a notification with only a title and body, but if we omit it, then we're back to the beggining, with the _"content could not be displayed"_ message.

2022-06-07 14:55 UTC, joeblubaugh submitted a review, later dismissed
This "request changes" is to block merges until we get to a safe point in the Grafana release process - it doesn't have anything to do with the contents of the PR, but we need to get a new branch set up so we don't accidentally add this to 9.0.0 in the middle of the final beta.

2022-06-07 16:37 UTC, santihernandezc commented on pkg/services/ngalert/notifier/channels/slack.go
> +		Text:      text,
Could you do the same for the `Text` field inside `Attachments`?

2022-06-29 10:04 UTC, grobinson-grafana commented
Hi! 👋 

Thanks for submitting this PR! An issue I have is that because Slack notifications at present use attachments, when we add a text field the text is included twice: first as text and second as an attachment with a color.

It might be better if we set `text` to `tmpl(sn.Title)`?

2022-06-29 10:07 UTC, grobinson-grafana commented
Hi! 👋

Thanks for submitting this PR to fix notifications in Slack! There is a small issue with this change in that the text is now included twice: first as text and second as an attachment with a color. This happens because Slack notifications at present use attachments, and when we add a text field both text and attachments are shown in the message. This is not the case when using the BlockKit API, but we have not updated Grafana to use BlockKit.

It might be better if we set text to tmpl(sn.Title)?

2022-06-29 10:07 UTC, grobinson-grafana commented
Hi! 👋

Thanks for submitting this PR to fix notifications in Slack!

There is a small issue with this change in that the text is now included twice: first as text and second as an attachment with a color. This happens because Slack notifications at present use attachments, and when we add a text field both text and attachments are shown in the message.

This is not the case when using the BlockKit API, but we have not updated Grafana to use BlockKit.

It might instead be better if we set text to `tmpl(sn.Title)`?

2022-06-29 10:08 UTC, grobinson-grafana commented
Hi! 👋

Thanks for submitting this PR to fix notifications in Slack!

There is a small issue with this change in that the text is now included twice: first as text and second as an attachment with a color. This happens because Slack notifications at present use attachments, and when we add a text field both text and attachments are shown in the message.

This is not the case when using the BlockKit API, but we have not updated Grafana to use BlockKit.

It might instead be better if we set text to `tmpl(sn.Title)`?

2022-07-18 10:06 UTC, grobinson-grafana commented
Closing because a duplicate of https://github.com/grafana/grafana/pull/52391.

2022-07-18 10:06 UTC, closed without merging