PublicDashboards: disable annotations
grafana/grafana pull request #50984
Opened 2022-06-16 19:14 UTC by evictorero

**What this PR does / why we need it**:
Annotations require special permissions to be retrieved, we are removing them from public dashboards v1.
This PR only removes retrieving annotations for public dashboards.

Disabling annotations for public dashboards.

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana-enterprise-partnerships-team/issues/222

2022-06-16 19:31 UTC, jalevin requested changes
This looks great!

Only feedback is that I think it would be worthwhile to add a test for when isPublic: true.

2022-06-16 19:35 UTC, torkelo requested changes
This sadly is not enough. It only addresses the default auto annotation query that every dashboard has that fetches annotations stored in Grafanas main db . 

But users can add annotation queries that target other datasources.

I can try to come up with a good place to add this condition to tomorrow

2022-06-21 16:13 UTC, evictorero commented
@torkelo thanks for taking a look at this. I reverted the last commit and added a check to the `canWork` function of the `AnnotationsWorker` to avoid fetching annotations from all datasources when the dashboard is pulic and also is being requested in _Public view mode_.  Let me know what do you think.

@jalevin removed all code and added some unit tests for this new approach

2022-06-21 19:00 UTC, torkelo approved these changes

2022-06-21 19:09 UTC, jalevin approved these changes

2022-06-23 16:09 UTC, merged