Alerting: Fix #51528 add custom title in wecom channel
grafana/grafana pull request #51529
Opened 2022-06-29 03:08 UTC by dingweiqings

**What this PR does / why we need it**:
When someone need to change  title in wecom  alert message , and this pr  support this case.

**Which issue(s) this PR fixes**:
#51528 #48159

**Special notes for your reviewer**:
I follow the code pattern about custom email subject .

2022-06-29 03:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=51529) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=51529) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=51529) it.</sub>

2022-06-29 16:17 UTC, JacobsonMT commented
Hi @dingweiqings, thanks for the contribution! This is looking good but is missing a couple pieces, namely:

1. This new `Title` field needs to be confiigurable in the Grafana UI. This can be done by adding a new field in `pkg/services/ngalert/notifier/available_channels.go`. An example can be seen here: https://github.com/grafana/grafana/pull/49742/files#diff-1a7dd1bf6b0704888c591e444fe45e45dabcf01d11d744f298fa17e18b4238d1.
2. A unit test should be added in `wecom_test.go` that tests templating this new field. An example can be seen here: https://github.com/grafana/grafana/pull/49742/files#diff-bc26976b3571e721b0327caaa80d1300fe6775a8106a232ce98063af42764a01.

Let me know if you need any help with either of these, I'll be glad to give a hand.

2022-07-03 01:37 UTC, dingweiqings commented
@JacobsonMT Do I  need to do something else work  ?

2022-07-05 21:44 UTC, JacobsonMT requested changes
Looks great! Should be good to approve/merge after addressing the two small issues I mentioned.

2022-07-05 21:44 UTC, JacobsonMT commented on pkg/services/ngalert/notifier/available_channels.go
> +				{ // New in 9.0.
```suggestion
				{ // New in 9.1.
```

NIT: Wrong version in the comment

2022-07-05 21:44 UTC, JacobsonMT commented on pkg/services/ngalert/notifier/channels/wecom_test.go
> +				"url": "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=db0e4533-aa2a-4385-8a24-2a7b6be72d20",
```suggestion
				"url": "http://localhost",
```
Let's use localhost instead a "real" url here.

2022-07-06 02:56 UTC, JacobsonMT commented on pkg/services/ngalert/notifier/available_channels.go
> +					Description:  "Templated title of the email",
Ah, one last thing, the description mentions email.

```suggestion
					Description:  "Templated title of the message",
```

2022-07-06 14:32 UTC, JacobsonMT approved these changes
LGTM! Thanks again for the contribution :rocket:

2022-07-06 15:54 UTC, merged