Plugins: InfluxDB datasource - set epoch query param value as "ms"
grafana/grafana pull request #51651
Opened 2022-06-30 17:02 UTC by itsmylife

**What this PR does / why we need it**:
Before influxdbd backend migration, all requests were done with the `epoch=ms` query param. After the migration, it was set as `epoch=s` by default. So we need to set it back to what it was. 

**Which issue(s) this PR fixes**:
 This PR changes the result precision to what it was before migration. 
About `epoch` parameter: https://docs.influxdata.com/influxdb/v2.3/reference/api/influxdb-1x/query/#epoch

Fixes https://github.com/grafana/grafana/issues/51547 (the first item in the checklist)

2022-07-06 07:38 UTC, gabor requested changes
hi @itsmylife , i don't think this change is enough.

you see, the `epoch` param controls the format of the timestamps returned from the influxdb database. the timestamps are numbers. if you switch from seconds to milliseconds, they will suddenly be 1000times larger, so the code that interprets those numbers has to change too. probably somewhere around 
https://github.com/grafana/grafana/blob/556f312b00e70c9d0c59990a034d9f34c3af7e0d/pkg/tsdb/influxdb/response_parser.go#L205-L220

2022-07-06 07:44 UTC, gabor commented
also, to clarify the past of the epoch-thing... before the influxdb-backend-migration happened:
- queries from the frontend javascript code, like explore or dashboards, were using `epoch=ms`
- alerting queries (originating from go code), were using `epoch=s`

so now, with the switch to making it a backend datasource, we have to unify these two.
(i think switching to `epoch=ms` is the right thing, just wanted to explain how the situation happened)

2022-07-06 16:25 UTC, itsmylife commented
> also, to clarify the past of the epoch-thing... before the influxdb-backend-migration happened:
> 
>     * queries from the frontend javascript code, like explore or dashboards, were using `epoch=ms`
> 
>     * alerting queries (originating from go code), were using `epoch=s`
> 
> 
> so now, with the switch to making it a backend datasource, we have to unify these two. (i think switching to `epoch=ms` is the right thing, just wanted to explain how the situation happened)

@gabor Thanks for the detailed explanation. Please check my latest commit. It handles that https://github.com/grafana/grafana/pull/51651/commits/49598f89c41095958dae67efa1cf1b6f89e59fb7

2022-07-07 06:14 UTC, gabor approved these changes
LGTM!

2022-07-07 09:14 UTC, yesoreyeram approved these changes
LGTM

2022-07-07 16:54 UTC, srclosson approved these changes
:fire:

2022-07-07 17:02 UTC, merged