Alerting: Disable /api/admin/pause-all-alerts with Unified Alerting
grafana/grafana pull request #51895
Opened 2022-07-07 12:23 UTC by joeblubaugh

/api/admin/pause-all-alerts only takes effect for legacy alerts. This
change returns a 403 if it's called when unified alerting is enabled.

Fixes #51729

2022-07-07 12:33 UTC, papagian reviewed
LGTM but I have a question

2022-07-08 01:36 UTC, joeblubaugh commented on pkg/api/alerting.go
> +	if ngalertEnabled {
I've updated this to use `setting.AlertingEnabled`.

2022-07-08 08:42 UTC, papagian commented on pkg/api/alerting.go
> +	if legacyAlertingEnabled == nil || !*legacyAlertingEnabled {
Based on the following:
https://github.com/grafana/grafana/blob/62b0a8bae6abcbd75326d3310abebcf6a78eac78/pkg/setting/setting.go#L1427-L1431

https://github.com/grafana/grafana/blob/62b0a8bae6abcbd75326d3310abebcf6a78eac78/pkg/setting/setting_unified_alerting.go#L119-L122

I think that the only case `AlertingEnabled` is `nil` is when the `alerting.enabled` cannot be parsed and in that case the new alerting is enabled.
So, I think the check should become:
```suggestion
	if legacyAlertingEnabled != nil || !*legacyAlertingEnabled {
```

2022-07-11 21:59 UTC, yuri-tceretian commented
Although I am OK with this approach, I wonder whether it would be better to just not register the endpoint at all, i.e. update code here:
https://github.com/grafana/grafana/blob/1d2aa7c69bf7db8cd4a5b7514c83ab17966f1790/pkg/api/api.go#L461-L467

2022-07-12 06:03 UTC, papagian requested changes

2022-07-12 06:05 UTC, joeblubaugh commented
@yuri-tceretian I prefer the more informative message in this case - we haven't deprecated the API in the past or provided any other advanced notice.

2022-07-12 06:08 UTC, papagian commented
> Although I am OK with this approach, I wonder whether it would be better to just not register the endpoint at all

I also like this suggestion unless we want to give better feedback to the users.
In any case I would suggest also to update [the docs](https://grafana.com/docs/grafana/latest/developers/http_api/admin/#pause-all-alerts) appropriately.

2022-07-12 07:01 UTC, papagian approved these changes

2022-07-12 07:01 UTC, merged