CloudWatch: fix log explorer context
grafana/grafana pull request #52118
Opened 2022-07-12 19:03 UTC by iwysiu

**What this PR does / why we need it**:
Fixes the bug where `show context` in explore wouldn't work if the log query region wasn't the same as the default cloudwatch region.
Also fixes a second bug where we were sending a `0` endtime to the cloudwatch api if it wasn't set on the `GetLogEventsWithContext` query.

**Which issue(s) this PR fixes**:

Fixes #41689 

**Special notes for your reviewer**:
I don't love the test I ended up adding, but there wasn't really a good way to test this. If you prefer it, I can pass the `datasourceType` and `logQueries` from `Logs.tsx` down to `LogRowContextProvider.tsx` and test it there, but it seemed messier from a code perspective.

2022-07-13 07:37 UTC, gabor requested changes, later dismissed
i understand more data is needed in `datasource.gegLogRowContext` to fix the bug, but i'd recommend not adding cloudwatch-specific attributes to a `grafana-ui` structure. would something like this be enough? https://github.com/grafana/grafana/pull/52130
we can also have a chat about this and discuss possibilities, if you prefer so 👍

2022-07-13 13:16 UTC, iwysiu commented
> i understand more data is needed in `datasource.gegLogRowContext` to fix the bug, but i'd recommend not adding cloudwatch-specific attributes to a `grafana-ui` structure. would something like this be enough? #52130 we can also have a chat about this and discuss possibilities, if you prefer so 👍

That would work! I'll pause on this until that goes in.

2022-07-13 17:59 UTC, iwysiu commented
I altered it to use that `getLogRowContext` change instead. Also, I added a Go test.

2022-07-15 15:28 UTC, iwysiu reviewed
The changes to `DataSourceWithLogsContextSupport` have been added and it's ready to be reviewed!

2022-07-18 06:28 UTC, gabor reviewed
nice work (i cannot review the cloudwatch-specific code, i'm only adding this review so that my previous request-changes-review goes away)

EDIT: aaand, apparently this is not enough. please just dismiss my request-changes review and move forward with this 😄

2022-07-18 19:05 UTC, sarahzinger approved these changes
🚀

2022-07-18 19:05 UTC, sarahzinger commented on public/app/plugins/datasource/cloudwatch/datasource.ts
> +      region: query?.region,
is there ever a situation where region is not defined? Will it still work? I could see a situation where you have to be like `query?.region || "__default"` or something like that, but I'm not 100% sure that's necessary, just a question to look into

2022-07-18 23:38 UTC, kevinwcyu approved these changes

2022-07-19 17:59 UTC, merged