logs: send more info to getLogRowContext
grafana/grafana pull request #52130
Opened 2022-07-13 06:36 UTC by gabor

work in progress

2022-07-14 06:07 UTC, gabor commented on public/app/features/explore/LogsContainer.tsx
> +      const query = (logsQueries ?? []).find((q) => q.refId === row.dataFrame.refId);
i assume there cannot be two queries with the same refId

2022-07-14 08:37 UTC, ivanahuckova approved these changes
LGTM 👍 , but do we need it in `9.0.3`? As this is not a bug fix, I wouldn't be backporting it.

2022-07-14 08:57 UTC, gabor commented
> LGTM 👍 , but do we need it in `9.0.3`? As this is not a bug fix, I wouldn't be backporting it.

i agree, but the "reason" for this change, the https://github.com/grafana/grafana/pull/52118 PR is meant to go in in 9.0.3, so it limits our options, i hope it's ok.

2022-07-14 14:55 UTC, Elfo404 requested changes
if we modify `DataSourceWithLogsContextSupport` to be 

```
export interface DataSourceWithLogsContextSupport<TQuery extends DataQuery = DataQuery> {
  /**
   * Retrieve context for a given log row
   */
  getLogRowContext: <TContextQueryOptions extends {}>(
    row: LogRowModel,
    options?: TContextQueryOptions,
    query?: TQuery
  ) => Promise<DataQueryResponse>;

  /**
   * This method can be used to show "context" button based on runtime conditions (for example row model data or plugin settings, etc.)
   */
  showContextToggle(row?: LogRowModel): boolean;
}
```
datasources implementing `DataSourceWithLogsContextSupport<LokiQuery>` (here `LokiQuery` is an example) will be limited to have
```
getLogRowContext: (row: LogRowModel, options?: RowContextOptions, query?: LokiQuery) => Promise<{ data: DataFrame[] }>
```
and can rely on Grafana doing the right thing without the need for them to do any runtime check (because in this PR query would be DataQuery).

for completeness, datasources can still implement
```
getLogRowContext: (row: LogRowModel, options?: RowContextOptions, query?: DataQuery) => Promise<{ data: DataFrame[] }>
```
even with my proposal because in `LokiQuery` extends `DataQuery`, so the type is still valid, but it would still make for a nicer API IMHO. wdyt?

2022-07-15 10:28 UTC, Elfo404 approved these changes

2022-07-15 10:43 UTC, leventebalogh approved these changes
LGTM 👍

2022-07-15 14:02 UTC, merged