Heatmap: update heatmap documentation
grafana/grafana pull request #52756
Opened 2022-07-25 18:54 UTC by ryantxu

In 9.1, we have swapped to a new heatmap panel -- this updates the docs for that panel

2022-08-19 17:24 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +This will toggle if the data is already a calculated heatmap (from the data source/transformer), or one that should be
```suggestion
This setting determines if the data is already a calculated heatmap (from the data source/transformer), or one that should be
```

2022-08-19 17:26 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Specify how the axis will be split into buckets. You can specify a time interval in the Size input, for example, the time range 1h. This will make the cells 1h wide on the X-axis.
```suggestion
This setting determines how the axis is split into buckets. You can specify a time interval in the **Size** input. For example, a time range of `1h` makes the cells 1-hour wide on the X-axis.
```

2022-08-19 17:27 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Specify how the axis will be split into buckets.
```suggestion
This setting determines how the Y-axis is split into buckets.
```

2022-08-19 17:28 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +The scale to use for the Y axis value.
```suggestion
Select one of the following Y-axis value scales:
```

2022-08-19 17:49 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Decimals configuration
```suggestion
This setting determines decimal configuration.
```

2022-08-19 17:49 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Configures the axis range
```suggestion
This setting configures the axis range.
```

2022-08-19 17:51 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +When selected, the axis will be displayed in reverse order
```suggestion
When selected, the axis appears in reverse order.
```

2022-08-19 17:52 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
>  By default, Grafana calculates cell colors based on minimum and maximum buckets values. With Min and Max you can overwrite those values. Think of a bucket value as a Z-axis and Min and Max as Z-Min a
```suggestion
By default, Grafana calculates cell colors based on minimum and maximum bucket values. With Min and Max you can overwrite those values. Consider a bucket value as a Z-axis and Min and Max as Z-Min and Z-Max, respectively.
```

2022-08-19 17:53 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +- **Start -** Minimum value using for cell color calculation. If the bucket value is less than Min, then it is mapped to the "minimum" color. Default is series min value.
```suggestion
- **Start -** Minimum value using for cell color calculation. If the bucket value is less than Min, then it is mapped to the "minimum" color. The series min value is the default value.
```

2022-08-19 18:01 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +- **End -** Maximum value using for cell color calculation. If the bucket value is greater than Max, then it is mapped to the "maximum" color. Default is series max value.
```suggestion
- **End -** Maximum value using for cell color calculation. If the bucket value is greater than Max, then it is mapped to the "maximum" color. The series max value is the default value.
```

2022-08-19 18:02 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +- **Show Histogram -** Show Y axis histogram on the tooltip. Histogram represents distribution of the bucket values for the specific timestamp.
```suggestion
- **Show Histogram -** Show a Y-axis histogram on the tooltip. A histogram represents the distribution of the bucket values for a specific timestamp.
```

2022-08-19 18:03 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Choose whether to display the heatmap legend on the visualization or not.
```suggestion
Choose whether you want to display the heatmap legend on the visualization.
```

2022-08-19 18:03 UTC, chri2547 commented on docs/sources/visualizations/heatmap.md
> +Set the color used to show exemplar data
```suggestion
Set the color used to show exemplar data.
```

2022-08-19 18:03 UTC, chri2547 requested changes
Added suggestions.

2022-08-19 18:08 UTC, chri2547 reviewed
The docs have been reviewed and are approved. Please go ahead and merge after Engr review and approval.

2022-08-22 16:34 UTC, ryantxu commented
Thanks @chri2547 -- I applied all your changes, and you double check and approve?

(Automerge is enabled)

2022-08-22 17:50 UTC, chri2547 approved these changes

2022-08-22 17:50 UTC, merged