PromQL: Add placeholder text to editor
grafana/grafana pull request #53321
Opened 2022-08-04 16:28 UTC by SethFalco

**What this PR does / why we need it**:

While learning more about Grafana through the tutorials, there was a discrepancy that, I thought, should be fixed in Grafana rather than the tutorial.

> In the **Query editor**, where it says _Enter a PromQL query_
> 
> — https://grafana.com/tutorials/grafana-fundamentals/

It does **not** say "Enter a PromQL query" there, which creates a bit of confusion in the tutorial. I can see on other editors you do, include placeholders as expected. I'm guessing it's because things like Loki are ultimately using an `Input` field, while for Prometheus you're using an instance of Monaco Editor. 

This adds a `placeholder` property, namely for the PromQL editor for querying Prometheus.

#### Before

![image](https://user-images.githubusercontent.com/22801583/182902384-eeb0a2ad-1842-46db-ae04-39aa19474ad0.png)

#### After

![image](https://user-images.githubusercontent.com/22801583/182899447-0b1dad37-06b7-4240-a910-055b83ae585a.png)

**Which issue(s) this PR fixes**:

* Fixes https://github.com/grafana/tutorials/issues/155

**Special notes for your reviewer**:

I made the styles similar to other placeholder fields, but wanted to also take the chance to propose a small change. Do you have any thoughts on making placeholders italic? I think this does a better job at demonstrating that this is a placeholder, however have not evaluated this with a larger audience.

2022-08-04 19:00 UTC, gtk-grafana requested changes
Thanks for taking the time to take a look at this, this was bothering me as well!
A couple of notes:
* Let's stick with non-italic placeholder text for now to keep things consistent across data-sources. I personally agree that the italic placeholder is more easily differentiated, but I'd want to check with the UX folks and the rest of the community before setting a new standard.
* The placeholder text added in this PR can be interacted with by the user, which is non-standard placeholder behavior (see screenshots for context). To solve this we'll want to make sure that the placeholder text is non-interactive whenever the user has focus in the editor.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/109082771/182930743-342a68b8-5ed6-4652-b47f-1636944c35cb.png">

<img width="443" alt="image" src="https://user-images.githubusercontent.com/109082771/182930641-87c7976a-f828-4733-ae29-074edc225af2.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/109082771/182930789-c7187355-1d52-4a8b-8c12-57f160de3be8.png">

Thanks again and congratulations on your first submission to Grafana!

2022-08-04 19:26 UTC, SethFalco commented
Yeah sure!

In that case we'll just have to go the full CSS approach with the marker, but that should be fine. I only avoided it at first since when reviewing this, I saw a comment suggesting the theme shouldn't be changed. ^-^'

But I wasn't familiar with `@emotion/css` until I tried to apply the opacity, so using that we should be able to achieve what you want quite easily. Thanks for pointing out the flaw!

Should be cool now, but let me know what you think!

2022-08-04 19:40 UTC, gtk-grafana commented
After your most recent push I'm unable to see the placeholder text at all :( 
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/109082771/182938396-c4a52256-a2e0-4879-96a1-bda924c93562.png">

2022-08-04 19:42 UTC, SethFalco commented
Ahh… that's what I get for rushing it…

I originally fixed and tested it then pushed.
After pushing, I realized I hard-coded the message instead of using the `placeholder` variable, so _without testing_, I just replaced it and pushed.

Forgot to add quotes, this time I've tested it locally. 🤦🏾 Sorry about that.

2022-08-04 19:59 UTC, gtk-grafana reviewed
Awesome! Yeah this is working great for me now. Let me check with someone else on the team (I'm new around here) for final approval, but this looks good to me!

2022-08-08 14:36 UTC, itsmylife reviewed
Thanks for taking the time and sending this nice PR. Would you mind adding a test `PromQueryEditorSelector.test.tsx` for whether the placeholder is in the document or not?

2022-08-08 16:06 UTC, SethFalco commented
Hmm… this one is throwing me off. Sorry. 🤔 
It seems the test library isn't doing anything when I pass the `ignore` argument.

Because the placeholder text is ultimately in the CSS (`<style>`) I need to check that. However, `script` and `style` tags are ignored by default by methods like [`getByText`](https://testing-library.com/docs/queries/bytext).

For some reason, the test code doesn't have linting, types, or code completion on my dev environment either, trying to resolve that too but not sure what's wrong. 🤔

I've tested what I want to do in the [playground](https://testing-playground.com/) and it works there, but when I move it into the Grafana source locally, it does nothing.

Any advice? ^-^'
This is the test I'm trying to add:

```ts
it('shows placeholder when code mode is set', async () => {
  renderWithProps({
    editorMode: QueryEditorMode.Code,
    expr: '',
  });

  expect(screen.getByText(/Enter a PromQL query/, {
    ignore: 'script'
  })).toBeInTheDocument();
});
```

2022-08-08 16:54 UTC, itsmylife approved these changes
I am approving it after reading your comment. You are right that is kinda tricky. Thanks for trying though. 
Happy to approve 🚀

2022-08-08 17:11 UTC, gtk-grafana approved these changes

2022-08-08 17:11 UTC, merged

2022-08-08 17:15 UTC, gtk-grafana commented
@SethFalco Thanks for all your work on this and congratulations on your first contribution to Grafana! 🎉 🎉 🎉