TablePanel: Fix vertical scrollbar
grafana/grafana pull request #53457
Opened 2022-08-09 11:19 UTC by mdvictor

**What this PR does / why we need it**:
Vertical scroll bar in table panel did not use the custom scrollbar component (it defaulted to browser scrollbar) and thus functionality was limited and not on-par with other scrollbars in Grafana.

![Screenshot 2022-08-09 at 14 17 44](https://user-images.githubusercontent.com/36818606/183634849-24069233-4b5b-495b-8b49-a45ef3c5c6ae.png)

**Which issue(s) this PR fixes**:

Fixes #52136 

**Special notes for your reviewer**:

Here is an example JsonPanel with different tables (different heights, data, pagination settings) for testing:

<details open>
<pre>
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 552,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto",
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "9.2.0-pre",
      "targets": [
        {
          "csvContent": "test1,test2,test3,test4,test5,test6,test7,test8,test9\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    },
    {
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto",
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 11,
        "x": 12,
        "y": 0
      },
      "id": 6,
      "options": {
        "footer": {
          "enablePagination": true,
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "9.2.0-pre",
      "targets": [
        {
          "csvContent": "test1,test2,test3,test4,test5,test6,test7,test8,test9\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"\n\"data1\",\"data2\",\"data3\",\"data4\",\"data5\",\"data6\",\"data7\",\"data8\",\"data9\"",
          "datasource": {
            "type": "testdata",
            "uid": "PD8C576611E62080A"
          },
          "refId": "A",
          "scenarioId": "csv_content"
        }
      ],
      "title": [...]

2022-08-09 12:04 UTC, torkelo requested changes
Sadly this breaks virtualized rendering (Provided by FixedSizeList), this is a very important performance requirement when rendering many rows. Testing this PR disables this and loading a test dashboard like  http://localhost:3000/d/U_bZIMRMk/panel-tests-react-table?orgId=1  (https://github.com/grafana/grafana/blob/main/devenv/dev-dashboards/panel-table/table_tests_new.json)  results in super slow renderings of some of the tables in that dashboard. 

To setup the devenv dashboards run setup.sh in devenv folder

2022-08-09 12:30 UTC, mdvictor commented
> Sadly this breaks virtualized rendering (Provided by FixedSizeList), this is a very important performance requirement when rendering many rows. Testing this PR disables this and loading a test dashboard like http://localhost:3000/d/U_bZIMRMk/panel-tests-react-table?orgId=1 (https://github.com/grafana/grafana/blob/main/devenv/dev-dashboards/panel-table/table_tests_new.json) results in super slow renderings of some of the tables in that dashboard.
> 
> To setup the devenv dashboards run setup.sh in devenv folder

I see, there is definitely worse performance with this. I'll look more into it the virtual rendering thing.

2022-08-18 09:16 UTC, dprokop approved these changes
As far as I see, the current solution is actually working with the virtualized list!

2022-08-18 09:16 UTC, dprokop commented on packages/grafana-ui/src/components/CustomScrollbar/CustomScrollbar.tsx
> +  onCustomScroll?: React.UIEventHandler;
```suggestion
  onScroll?: React.UIEventHandler;
```

2022-08-22 07:22 UTC, torkelo approved these changes

2022-08-22 10:41 UTC, merged