HistogramPanel: Generate .cue model
grafana/grafana pull request #53826
Opened 2022-08-17 12:25 UTC by mdvictor

**What this PR does / why we need it**:
Generate .cue model for the histogram panel. Part of epic #48761.

**Which issue(s) this PR fixes**:

Closes #53584

## TODO:

- [] Add docs for properties

2022-08-17 15:37 UTC, sdboyer requested changes
Generally good, just two things related to numeric types!

2022-08-17 15:37 UTC, sdboyer commented on public/app/plugins/panel/histogram/models.cue
> +						fillOpacity?:  int32 & >= 0 & <= 100 | *80
If these are both >= 0, why not:
```suggestion
						lineWidth?:    uint32 & <= 10 | *1
						// Controls the fill opacity of the bars.
						fillOpacity?:  uint32 & <= 100 | *80
```

2022-08-18 06:39 UTC, mdvictor commented
Thank you for the review, @sdboyer. The changes make sense. I modified as requested.

2022-08-18 09:30 UTC, sdboyer approved these changes

2022-08-18 09:51 UTC, sdboyer commented
looks great!

2022-08-18 13:19 UTC, merged