[DOC] Add APM changes and fix links
grafana/grafana pull request #53986
Opened 2022-08-19 22:40 UTC by knylander-grafana

**What this PR does / why we need it**:

Adds screenshot of the APM dashboard and fixes links from the Tempo data source page

2022-08-21 19:21 UTC, brendamuir commented on docs/sources/datasources/tempo.md
> +- [Configure the Grafana Agent](https://grafana.com/docs/tempo/latest/grafana-agent/service-graphs/#quickstart) or [Tempo/GET](https://grafana.com/docs/tempo/latest/server_side_metrics/service_graphs
Hey Kim, all looks great -- just one thing from my short time on Agent docs -- we don't use an article in front of agent -- so it's just Configure Grafana Agent.

2022-08-22 18:48 UTC, Eve832 requested changes
looks good, with one edit

2022-08-22 18:48 UTC, Eve832 commented on docs/sources/datasources/tempo.md
> +Grafana ships with built-in support for Tempo, a high volume, minimal dependency trace storage, OSS tracing solution from Grafana Labs. Add it as a data source, and you are ready to query your traces
```suggestion
Grafana ships with built-in support for Tempo, a high volume, minimal dependency trace storage, OSS tracing solution from Grafana Labs. Add it as a data source, and you are ready to query your traces in [Explore]({{< relref "../explore" >}}).
```

2022-08-22 23:40 UTC, knylander-grafana commented on docs/sources/explore/trace-integration.md
> +This section explains the elements of the Trace View dashboard.
```suggestion
This section explains the elements of the Trace View dashboard.
```

2022-08-23 00:31 UTC, knylander-grafana commented on docs/sources/datasources/tempo.md
> +Grafana ships with built-in support for Tempo, a high volume, minimal dependency trace storage, OSS tracing solution from Grafana Labs. Add it as a data source, and you are ready to query your traces
Committed the change. Thank you.

2022-08-23 14:44 UTC, Eve832 approved these changes
lgtm!

2022-08-23 14:46 UTC, merged