Loki: Remove any from public/app/plugins/datasource/loki/components/LokiOptionFields.test.tsx
grafana/grafana pull request #54239
Opened 2022-08-25 15:09 UTC by gitstart

**What this PR does / why we need it**:
Removes `any` from `LokiOptionFields.test.tsx`

**Which issue(s) this PR fixes**:

Fixes #53133

**Special notes for your reviewer**:

2022-08-25 15:20 UTC, matyax requested changes
Thank you for your contribution! I would suggest to remove `propOverrides` from `setup()`, and ensure that only attributes from `LokiOptionFieldsProps` are passed to the rendered component.

2022-08-25 15:20 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiOptionFields.test.tsx
>  const setup = (propOverrides?: LokiOptionFieldsProps) => {
This `propOverrides` is not used at all in this test, so it would be preferable to remove it.

2022-08-25 15:20 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiOptionFields.test.tsx
>      queryType,
Some of the props here, that are later spreaded to the component, don't exist in `LokiOptionFieldsProps`.

2022-08-30 09:27 UTC, matyax commented
Thank you for reiterating on this PR!

2022-09-01 12:42 UTC, gitstart commented
Hey @matyax I think this needs your approval before it can be merged

2022-09-01 12:43 UTC, matyax approved these changes

2022-09-01 12:43 UTC, matyax commented
Thanks for the reminder @gitstart

2022-09-01 13:27 UTC, gitstart commented
Thank you for approving the PR @matyax but this is still not merged. How can we get this merged? @matyax

2022-09-01 14:12 UTC, gitstart commented
> @gitstart I'm waiting for CI. Would you kindly be a little bit patient please?

Will do, sorry about this @matyax

2022-09-01 15:24 UTC, matyax commented
There's a check that's failing to run. This PR will be merged once that goes back to normal.

2022-09-02 11:44 UTC, matyax commented
@gitstart Could you please send an empty commit (`git commit --amend`) to re-trigger the failing job? Thanks.

2022-09-05 15:38 UTC, gitstart commented
@matyax PR has been updated. Please take a look 🙏

2022-09-05 16:23 UTC, matyax approved these changes

2022-09-05 16:23 UTC, matyax commented
Thank you @gitstart !

2022-09-05 16:25 UTC, merged