Correlations: Return 200 instead of 404 for empt correlation lists
grafana/grafana pull request #55242
Opened 2022-09-15 13:15 UTC by Elfo404

Fixes #54789 

Some FE changes were needed in order to handle 200 instead of 404.

additionally, some BE error messages were wrong (they got copy-pasted and didn't describe the actual error)

2022-09-19 15:28 UTC, gelicia requested changes
Doesn't handle when the correlation has the source datasource deleted. Crashes in `CorrelationsPage` trying to create the `DatasourceCell` when the value passed in is undefined. Not sure what makes sense here.

2022-09-19 17:22 UTC, gelicia approved these changes
Talked to Gio about the crash due to me having bad data and the '-- Grafana --' bug. He's going to make up issues separately.

2022-09-19 20:07 UTC, ifrost approved these changes

2022-09-20 10:13 UTC, Elfo404 commented
@gelicia created https://github.com/grafana/grafana/issues/55450 for the DS picker issue and https://github.com/grafana/grafana/issues/55451 to follow up on the bad data one.

thanks again for spotting this!

2022-09-20 10:13 UTC, merged