Elasticsearch: Rename public/app/plugins/datasource/elasticsearch/elastic_response.ts to follow convention
grafana/grafana pull request #55533
Opened 2022-09-21 01:05 UTC by mvsousa

**What this PR does / why we need it**:

Rename public/app/plugins/datasource/elasticsearch/elastic_response.ts to follow convention

**Which issue(s) this PR fixes**:

Fixes https://github.com/grafana/grafana/issues/55384

**Special notes for your reviewer**:

2022-09-22 00:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=55533) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=55533) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mvsousa<br/>:x: Marcos Sousa<br/><hr/>**Marcos Sousa** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=55533) it.</sub>

2022-09-22 09:39 UTC, matyax requested changes
There's a modified go file.

2022-09-22 09:39 UTC, matyax commented on pkg/services/ngalert/eval/evaluator_mock.go
>  }
This change is out of scope with the issue.

2022-09-22 13:58 UTC, matyax requested changes, later dismissed
Thank you for updating the PR! The CI is failing with the following error:

```
+ yarn run prettier:check

+ yarn run lint


/drone/src/public/app/plugins/datasource/elasticsearch/ElasticResponse.test.ts

  4:1  error  There should be no empty line within import group           import/order

  4:1  error  `./types` import should occur after import of `./queryDef`  import/order


✖ 2 problems (2 errors, 0 warnings)

  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

2022-09-23 00:30 UTC, mvsousa commented
> yarn run lint

@matyax 
I think I fixed, can you check ?
I ended up messing up with the main branch and requested review from a lot of people

2022-09-23 11:45 UTC, matyax commented
Some more conflicts to resolve.

2022-09-24 19:31 UTC, mvsousa commented
> Some more conflicts to resolve.

@matyax done! updated with the main branch!

2022-09-26 14:50 UTC, ivanahuckova approved these changes
Nice! Thank you for your contribution. LGTM! 🚀

2022-09-26 14:53 UTC, merged