Toolkit: Remove changelog command
grafana/grafana pull request #56073
Opened 2022-09-30 09:10 UTC by gitstart

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #56028

**Special notes for your reviewer**:

2022-09-30 09:15 UTC, gitstart commented
Hello @academo, I hope this is the expected solution for #56028. If not, happy to make any further required changes 😃

2022-09-30 13:56 UTC, academo commented
> Hello @academo, I hope this is the expected solution for #56028. If not, happy to make any further required changes smiley

even though the command is removed we also need to remove all the associated files that contained the command runner task.

2022-09-30 14:09 UTC, academo commented on packages/grafana-toolkit/src/cli/index.ts
> -import { changelogTask } from './tasks/changelog';
We also need to remove all the code associated to the command, in this case the `changelogTask` here `'./tasks/changelog'` and if there are other files associated that are only used there, delete them too.

We also want to see if there are nodejs dependencies that are used only there and nowhere else and if so, remove them from the package.json of the project.

2022-09-30 14:17 UTC, academo requested changes
Please also remove all the associated files that contained the command runner task and verify if we can remove any nodejs dependency that was only used in this command from the package.json

2022-09-30 14:59 UTC, academo commented
Also there are some betterer lines to remove https://github.com/grafana/grafana/blob/main/.betterer.results#L1112

Please make sure to install and run the pre-commit hooks

2022-10-01 01:53 UTC, gitstart commented
Thank you for the review @academo, will get back to you with required changes

2022-10-04 17:15 UTC, gitstart commented
Hi @academo! PR was updated with the changes, kindly review again

2022-10-05 12:44 UTC, academo approved these changes
Thanks for the changes and your contribution.

2022-10-05 12:44 UTC, merged