Navigation: Integrate Explore actions into topnav
grafana/grafana pull request #56381
Opened 2022-10-05 11:34 UTC by ashharrison90

**What this PR does / why we need it**:

- moves Explore actions into topnav when not split

# topnav on

https://user-images.githubusercontent.com/20999846/194050605-3b872d91-0680-46c0-9b13-355c9a162a83.mp4

# topnav off

https://user-images.githubusercontent.com/20999846/194050617-fa6e1dea-b49a-4f47-90fa-b328e01df756.mp4

**Which issue(s) this PR fixes**:

Fixes #56269 

**Special notes for your reviewer**:

2022-10-05 13:56 UTC, torkelo commented
Noticed a bug sometimes the ToolbarButton menu is shown but without anything in it 
![Screenshot from 2022-10-05 15-49-53](https://user-images.githubusercontent.com/10999/194077728-b1f66e16-a314-434b-a5fc-e3c17e3ffdb7.png)

The close split feels like something that maybe should not be collapsed into the menu first. I think its position is a bit strange in the current design. Normally a close pane action is on the upper right corner of that "pane/window". But maybe tweaking button order should be done in a separate step. 

![Screenshot from 2022-10-05 15-52-27](https://user-images.githubusercontent.com/10999/194077764-04eb0107-4f96-4ead-a12e-4971dfb8d729.png)

2022-10-05 14:55 UTC, ashharrison90 commented
have fixed the bug (i think!), but haven't moved any buttons.

lemme know if that's something we think we should do in this PR (or later, or not at all) 👍

2022-10-05 21:23 UTC, gelicia commented
I agree that the close split button shouldn't be collapsed with other options right away. 

Another thing though, we will be adding split resizing soon that will add a minimize/maximize button in the split view  so people can expand/(partially) collapse their panes. I can be sure this works with top nav as well. I will plan on collapsing it with the same logic as the "Add To Dashboard" button. If you minimize a pane, it will be 200px wide, so it will likely be collapsed all the way anyway. We also had made the panes go horizontally scrollable at 600px to try to keep the query editors from looking squished, and alongside that, made the collapsed kebab menu left justified. This was because there was no easy way to keep the toolbar outside of the horizontal scroll. You can see what I'm talking about on this branch https://github.com/grafana/grafana/tree/kristina/split-resize-3 

We're going to be reworking this so any feedback would be helpful! Feel free to add it here https://github.com/grafana/grafana/issues/56340

2022-10-06 12:29 UTC, ashharrison90 commented
@gelicia pretty sure left-aligning that menu will mean the overflow behaviour won't work correctly. thoughts on just disabling split view under 600px (or w/e the actual breakpoint is)? i can't see how it will ever really be usable at that size tbh 🤔

2022-10-07 13:08 UTC, ashharrison90 commented on public/app/features/explore/ExploreToolbar.tsx
> +    return [
thanks @ifrost that's much nicer 👍 

agreed it's a little unwieldy at the moment 😬 will be a little cleaner again once the `topnav` toggle is turned on by default 🙂

2022-10-11 08:08 UTC, ifrost requested changes
Played around with split views and live mode with/without topnav and noticed a few things:

(1) When the user switches to a data source supporting live streaming the "live" button does not show up (though there's space for it and it appears upon page refresh). This happens with `topnav=true` and `topnav=false`

| main | branch |
|------|--------|
| https://user-images.githubusercontent.com/745532/195034034-c9ccaec7-ffe2-4a95-80e2-5a6a9b88240a.mov  |  https://user-images.githubusercontent.com/745532/195034146-01e68696-c9c3-43a1-a65c-628b6c5562e5.mov |

(2) It seems we don't have borders around buttons in split view any more. Is that intended?

| main | branch |
|------|--------|
|  <img width="520" alt="Screen Shot 2022-10-11 at 10 03 18" src="https://user-images.githubusercontent.com/745532/195034264-d22e6ea3-382e-45e9-b1f1-bdf09b8071e1.png"> |  <img width="520" alt="Screen Shot 2022-10-11 at 10 03 25" src="https://user-images.githubusercontent.com/745532/195034310-970ac0b2-1ea6-401a-aac6-fba7b5cad16e.png">   |

Other than that seems to work fine! 👍

2022-10-11 10:15 UTC, ashharrison90 commented
@ifrost thanks 🙌 i've fixed the bug with `Live` not appearing

`ToolbarButton`s not having borders around them when `topnav` is enabled [was a conscious choice](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ToolbarButton/ToolbarButton.tsx#L193) and isn't a result of this PR (turning on `topnav` in main should show the same behaviour).

**but** pretty sure buttons in the top bar were the only consideration, not sure how we can handle `ToolbarButton`s being used in other places gracefully 🤔 

wdyt @torkelo?

2022-10-11 10:37 UTC, Elfo404 approved these changes
LGTM.

a side note regarding the toolbar buttons: i think it looks ok also when in split mode, but i'm wondering if its intended to be used outside of the navbar at this point, it may even be considered a breaking change, afaik bot the the trace panel and the logs panel use that component in explore (@grafana/observability-logs  @grafana/observability-traces-and-profiling  you may want to double check as well).

2022-10-11 10:53 UTC, ashharrison90 commented
@Elfo404 yep agreed, think we need to have a conversation about our expectations for where `ToolbarButton` is used / how it should look consistently. might be that the easiest thing to do is to put the `ToolbarButton` styling back to what it was and override it specifically in the top navbar components 🤔

2022-10-11 11:12 UTC, ashharrison90 commented
@ifrost @Elfo404 not sure what's going on with the `Observability Experience test code coverage` step. i don't think it's related to the changes, but you might know better than me? 🤔

2022-10-11 11:17 UTC, Elfo404 commented
@ashharrison90 ignore that, it's not required anyway :)

2022-10-11 11:19 UTC, ashharrison90 commented
ok i'll wait for @ifrost's rereview and suggest we continue the `ToolbarButton` discussion in slack? i'll post something in `#grafana-navigation` now.

2022-10-11 11:54 UTC, ifrost approved these changes
> @ifrost thanks 🙌 i've fixed the bug with `Live` not appearing

Looks good now! Thanks! 🙌

> `ToolbarButton`s not having borders around them when `topnav` is enabled [was a conscious choice](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ToolbarButton/ToolbarButton.tsx#L193) and isn't a result of this PR (turning on `topnav` in main should show the same behaviour). 
> **but** pretty sure buttons in the top bar were the only consideration, not sure how we can handle `ToolbarButton`s being used in other places gracefully 🤔

I think it looks okay, but still it's a change so just wanted to double check where is it coming from. Something to think about when we tackle https://github.com/grafana/grafana/issues/54751

2022-10-11 11:59 UTC, merged