Docs: Fix Canvas doc link and add call to action for feedback
grafana/grafana pull request #56908
Opened 2022-10-13 22:09 UTC by nmarrs

**What this PR does / why we need it**:
Fix broken link to canvas doc page on what's new in 9.2 page

Add call to action to provide feedback in a github discussion for canvas panel feedback

2022-10-13 22:20 UTC, nmarrs commented
It probably wouldn't hurt to do an edit pass of canvas docs as part of this PR as well (extending to more than just changing the word allow to enable)

2022-10-13 22:37 UTC, drew08t approved these changes
LGTM

2022-10-14 00:04 UTC, gguillotte-grafana requested changes
Suggest reverting a relref change since it's working on the live website.

2022-10-14 02:02 UTC, gguillotte-grafana approved these changes

2022-10-14 02:02 UTC, merged