docs: Refactors remaining enterprise topics, corrects relrefs
grafana/grafana pull request #57707
Opened 2022-10-26 22:01 UTC by chri2547

This PR refactors remaining enterprise topics and corrects relrefs.

2022-10-26 22:14 UTC, gguillotte-grafana requested changes
Callouts to the Cloud docs should use Markdown links instead of Hugo refs/relrefs.

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/administration/data-source-management/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/setup-grafana/configure-security/audit-grafana.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.3 and later, and [Grafana Cloud Advanced]({{< ref "/docs/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.3 and later, and [Grafana Cloud Advanced](/docs/grafana-cloud).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/setup-grafana/configure-security/configure-request-security.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.4 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/docs/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.4 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/setup-grafana/configure-security/configure-team-sync.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Advanced]({{< ref "/docs/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/administration/data-source-management/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/administration/recorded-queries/index.md
> +  - docs/grafana/latest/administration/recorded-queries/
```suggestion
  - /docs/grafana/latest/administration/recorded-queries/
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.5 and later behind the `reportVariables` feature flag, Grafana Enterprise version 8.0
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.5 and later behind the `reportVariables` feature flag, Grafana Enterprise version 8.0 and later without a feature flag, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** You can set custom report time ranges in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) 7.2+ and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >
```suggestion
> **Note:** You can set custom report time ranges in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) 7.2+ and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) 8+ with the [Grafana image renderer plugin](https://grafana.com/grafana/plugins/grafana-image-re
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) 8+ with the [Grafana image renderer plugin](/grafana/plugins/grafana-image-renderer) v3.0+, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.0 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 8.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 9.0 and later, and [Grafana Cloud Pro and Advanced]({{< relref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 9.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 9.0 and later, and [Grafana Cloud Pro and Advanced]({{< relref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 9.0 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:14 UTC, gguillotte-grafana commented on docs/sources/dashboards/create-reports/index.md
> +> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.2 and later, and [Grafana Cloud Pro and Advanced]({{< ref "/grafana-cloud" >}}).
```suggestion
> **Note:** Available in [Grafana Enterprise]({{< relref "../../introduction/grafana-enterprise/" >}}) version 7.2 and later, and [Grafana Cloud Pro and Advanced](/docs/grafana-cloud/).
```

2022-10-26 22:17 UTC, gguillotte-grafana commented
Line 20 of docs/sources/introduction/grafana-enterprise.md has a Hugo ref to `/docs/grafana-cloud/reference/enterprise-features` - the Hugo ref shortcode to the Cloud docs won't work at all, but there's also no content at https://grafana.com/docs/grafana-cloud/reference/enterprise-features and I don't know where that should point.

2022-10-26 23:14 UTC, chri2547 commented
> Line 20 of docs/sources/introduction/grafana-enterprise.md has a Hugo ref to `/docs/grafana-cloud/reference/enterprise-features` - the Hugo ref shortcode to the Cloud docs won't work at all, but there's also no content at https://grafana.com/docs/grafana-cloud/reference/enterprise-features and I don't know where that should point.

Removed that link.

2022-10-26 23:18 UTC, gguillotte-grafana reviewed
LGTM - should docs/sources/introduction/grafana-enterprise.md be docs/sources/introduction/grafana-enterprise/index.md? Not a blocking concern, but similar to what came up in the data sources refactor.

2022-10-26 23:19 UTC, gguillotte-grafana approved these changes

2022-10-27 00:59 UTC, chri2547 commented
> LGTM - should docs/sources/introduction/grafana-enterprise.md be docs/sources/introduction/grafana-enterprise/index.md? Not a blocking concern, but similar to what came up in the data sources refactor.

Yes, I still need to do that and will handle it outside of this PR. Slowly making my way through the repo.

2022-10-28 06:45 UTC, torkelo approved these changes

2022-10-28 12:13 UTC, merged