Loki: Make label browser accessible in query builder
grafana/grafana pull request #58525
Opened 2022-11-09 14:44 UTC by gwdawson

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2022-11-21 17:14 UTC, matyax requested changes
Good work! There are some minor things to adjust.

2022-11-22 15:43 UTC, matyax commented on public/app/plugins/datasource/loki/querybuilder/components/LabelBrowserModal.test.tsx
> +  });
Would also love to have a test case for `onChange` when we change the query. Feel free to drop it in another PR.

2022-11-22 15:43 UTC, matyax reviewed
Looks good! One minor adjustment and it's done.

2022-11-22 16:08 UTC, gwdawson commented on public/app/plugins/datasource/loki/querybuilder/components/LabelBrowserModal.tsx
> +    if (onChange) {
nice catch 😎

2022-11-22 16:16 UTC, matyax reviewed
One last change. Sorry I didn't see it before!

2022-11-23 14:48 UTC, matyax reviewed
![imagen](https://user-images.githubusercontent.com/1069378/203576357-87152d76-58a7-478e-bb59-2f202eca6a2d.png)

🙏

2022-11-23 14:48 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx
> +              placeholder={'Enter a label name'}
I misinterpreted the explanation of this field, so `Enter a label value` was correct. Feel free to apply the suggestion from here.

```suggestion
              placeholder={'Enter a label value'}
```

![imagen](https://user-images.githubusercontent.com/1069378/203571103-c755d939-a16d-471f-9a97-eb37cefc13d7.png)

2022-11-23 14:48 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx
>              {selectedLabels.map((label) => (
While testing, my Loki instance went offline, so I had pre-fetched labels, but then it failed to make further requests.

With that, I saw that we display 2 messages that now are broken:

![Message 1](https://user-images.githubusercontent.com/1069378/203574920-3a8163ca-425b-4935-9c8f-802995109484.png)
![Message 2](https://user-images.githubusercontent.com/1069378/203574943-44b1299b-cdcf-42b9-ae3d-90b550b08858.png)

We need to adjust that.

To reproduce it, load the page with your Loki docker image on, and then turn it off to interact with the component.

I think moving it above the buttons would be acceptable.

![imagen](https://user-images.githubusercontent.com/1069378/203576236-a1d23b8c-4ea3-4cfe-a2e1-65f585e68416.png)

2022-11-23 14:50 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx
>              {selectedLabels.map((label) => (
Also I don't know what does "facetting" mean in that context at all.

2022-11-23 15:05 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiLabelBrowser.tsx
>              {selectedLabels.map((label) => (
After https://raintank-corp.slack.com/archives/C03PMJLVC67/p1669214990835099 I'd suggest rename "Facetting" with "Loading" please. Thanks!

2022-11-23 16:42 UTC, matyax approved these changes
GJ!

2022-11-23 16:48 UTC, merged

2022-11-24 12:32 UTC, matyax commented on public/app/plugins/datasource/loki/querybuilder/components/LabelBrowserModal.test.tsx
> +  });
This would be a good candidate for a follow-up task.

2022-11-24 14:03 UTC, ivanahuckova reviewed
I left couple of feedback bellow. Also I remember that we talked about making it wider - slightly smaller than full screen, but taking advantage of the full screen size. Is there a reason you decided not to make it larger, now when we have modal and space?

2022-11-24 14:07 UTC, ivanahuckova commented on public/app/plugins/datasource/loki/components/LokiQueryEditor.tsx
> +  const onClickChooserButton = () => {
`onClickChooserButton` -> `onClickLabelBrowserButton`

2022-11-24 15:51 UTC, gwdawson commented
@ivanahuckova i like these suggestions! i'll make a pr for these changes.

> Also I remember that we talked about making it wider - slightly smaller than full screen, but taking advantage of the full screen size. Is there a reason you decided not to make it larger

https://github.com/grafana/grafana/pull/58525#discussion_r1028306646 - I wasn't sure how this will effect any of the other modals that already exist. my plan was to take a look to see if theres a way to increase the size for only a specific modal, in this case the label browser. if you think i would be better to just increase the size for all of them please let me know.