Replace fmt without arg with errors. Small cleanup
grafana/grafana pull request #58600
Opened 2022-11-10 17:42 UTC by sashamelentyev

2022-11-29 13:06 UTC, marefr requested changes

2022-11-29 18:07 UTC, sashamelentyev commented on pkg/api/playlist_play.go
> +		switch item.Type {
Done

2022-12-01 19:43 UTC, marefr approved these changes
LGTM

2022-12-01 19:51 UTC, merged

2022-12-01 19:51 UTC, marefr commented
@sashamelentyev thank you for contributing to Grafana