SSE/QueryData: Copy Headers and User
grafana/grafana pull request #58897
Opened 2022-11-17 12:45 UTC by kylebrandt

Copies the User and Headers from the request through expressions.

possibly fixes #58793 and https://github.com/grafana/azure-data-explorer-datasource/issues/513

**Special notes for your reviewer**:
only first header value per header key is kept

2022-11-17 14:38 UTC, kylebrandt commented
@kostrse Any chance you can try this branch and see if solves the issues you have with passthrough auth?

2022-11-18 07:28 UTC, kostrse commented
@kylebrandt Thanks, I'm doing testing and will reply back once I'm done.

2022-11-18 09:27 UTC, marefr approved these changes
LGTM, added a suggestion

Seems a bit related to https://github.com/grafana/grafana/pull/58132 - need to make sure SSE is considered there.

2022-11-22 18:47 UTC, taleena commented
@marefr @papagian looks like this is good to go, but is blocked? Would it also be possible to port this to 9.1, 9.2?

2022-11-23 04:40 UTC, kostrse commented
@kylebrandt to repro in ADX

You will need to run Grafana with AAD OAuth configuration, logged in as an AAD user.

You don't need valid credentials for ADX to repro the missing `X-ID-Token` since the code fails before the actual authentication request.

1. Save an ADX datasource with OBO checked.
2. Attach with debugger to ADX backend.
3. Set breakpoint to line 108 of `auth.go` ([here](https://github.com/grafana/azure-data-explorer-datasource/blob/ba4ca9cf75374cd9468f0129c2584dd32cc8b3a5/pkg/azuredx/azureauth/auth.go#L108))
4. Create a new dashboard a a new panel
5. Run query "A"
6. You will hit breakpoint in `QueryData` func and the `req.Headers` will have `X-ID-Token`.
7. Continue
8. Add math exression "B" (e.g. A + 1)
9. You will hit the same breakpoint again but this time `X-ID-Token` will be missing.

The difference is whether math expression is present or not.

2022-11-23 04:40 UTC, kostrse commented
cc @andresmgot

2022-11-23 14:32 UTC, marefr requested changes, later dismissed
Had a look again. Think there's some wrong assumptions being made in regards to incoming HTTP headers.

2022-11-23 14:32 UTC, marefr commented on pkg/services/query/query.go
> +	}
This code feels wrong to me. We don't forward all HTTP headers to `QueryData` today so why do we need to do it for SSE?

2022-11-23 14:36 UTC, marefr commented
> @marefr @papagian looks like this is good to go, but is blocked? Would it also be possible to port this to 9.1, 9.2 (with a slight preference to 9.2)?

9.2 sure, but not 9.1 since only security fixes would go into it. Would ask @kylebrandt since he's the author of this PR.

2022-11-23 14:43 UTC, marefr commented
To support X-ID-Token in SSE we should reuse the following code for SSE: 
https://github.com/grafana/grafana/blob/c9286ff79464de3e368b3ca95b215a6d674d8437/pkg/services/query/query.go#L201-L231

I would suggest to add this to this PR and get it merged and backported for 9.2.x and v9.3.x before merging https://github.com/grafana/grafana/pull/58132 which is targeted for 9.4.x and changes a lot of things :smile: Given @kylebrandt is OOO until next week I might have to try picking this up so that I can get my other PRs merged, https://github.com/grafana/grafana/pull/58132, https://github.com/grafana/grafana/pull/58646

2022-11-24 02:43 UTC, kostrse commented
@marefr OK, now it doesn't even attempt to call QueryData :)

```
Object
status:500
statusText:"Internal Server Error"
data:Object
error:"assignment to entry in nil map - C:/Users/user1/scoop/apps/go/current/src/runtime/map_faststr.go:205 (0x140015999)
	mapassign_faststr: panic(plainError(\"assignment to entry in nil map\"))
D:/Dev/grafana/pkg/expr/service/nodes.go:235 (0x141f60ba4)
	(*DSNode).Execute: req.Headers[\"Authorization\"] = fmt.Sprintf(\"%s %s\", token.Type(), token.AccessToken)
D:/Dev/grafana/pkg/expr/service/graph.go:54 (0x141f5e4c9)
	(*DataPipeline).execute: res, err := node.Execute(c, now, vars, s)
D:/Dev/grafana/pkg/expr/service/service.go:78 (0x141f637e8)
	(*Service).ExecutePipeline: vars, err := intPipeline.execute(ctx, now, s)
D:/Dev/grafana/pkg/expr/service/service.go:118 (0x141f63b87)
	(*Service).TransformData: responses, err := s.ExecutePipeline(ctx, now, pipeline)
D:/Dev/grafana/pkg/services/query/query.go:167 (0x1419cd5b1)
	(*Service).handleExpressions: qdr, err := s.expressionService.TransformData(ctx, time.Now(), &exprReq) // use time now because all queries have absolute time range
D:/Dev/grafana/pkg/services/query/query.go:89 (0x1419cccb1)
	(*Service).QueryData: return s.handleExpressions(ctx, user, parsedReq)
D:/Dev/grafana/pkg/api/metrics.go:57 (0x141dd358e)
	(*HTTPServer).QueryMetricsV2: resp, err := hs.queryDataService.QueryData(c.Req.Context(), c.SignedInUser, c.SkipCache, reqDTO)
D:/Dev/grafana/pkg/api/routing/routing.go:17 (0x14138a081)
	Wrap.func1: if res := handler(c); res != nil {
D:/Dev/grafana/pkg/api/response/web_hack.go:40 (0x140ddb735)
	wrap_handler.func3: handle(reqCtx(w, r))
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:135 (0x140d8d134)
	mwFromHandler.func1.1: h.ServeHTTP(mrw, r)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/services/contexthandler/contexthandler.go:186 (0x141372681)
	(*ContextHandler).Middleware.func1: next.ServeHTTP(w, r)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/render.go:44 (0x140d8dcf5)
	Renderer.func1.1: next.ServeHTTP(rw, req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/macaron.go:141 (0x140d8d1db)
	mwFromHandler.func1.1: next.ServeHTTP(ctx.Resp, ctx.Req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/middleware/csrf/csrf.go:64 (0x141ad0d45)
	(*CSRF).Middleware.func1.1: next.ServeHTTP(w, r)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/middleware/recovery.go:171 (0x141384a21)
	Recovery.func1.1: next.ServeHTTP(w, req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/middleware/logger.go:40 (0x14138241c)
	Logger.func1.1: next.ServeHTTP(rw, r)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/middleware/request_metrics.go:58 (0x141385829)
	RequestMetrics.func1.1: next.ServeHTTP(w, r)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/middleware/request_tracing.go:88 (0x141386f7a)
	RequestTracing.func1.1: next.ServeHTTP(w, req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2109 (0x140341b0e)
	HandlerFunc.ServeHTTP: f(w, r)
D:/Dev/grafana/pkg/web/context.go:49 (0x140d8babd)
	(*Context).run: h.ServeHTTP(ctx.Resp, ctx.Req)
D:/Dev/grafana/pkg/web/router.go:155 (0x140d8f26d)
	(*Router).Handle.func1: c.run()
D:/Dev/grafana/pkg/web/router.go:211 (0x140d8fed5)
	(*Router).ServeHTTP: leaf.handle(rw, req, nil)
D:/Dev/grafana/pkg/web/macaron.go:167 (0x140d8d650)
	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:2947 (0x140344f0b)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
C:/Users/user1/scoop/apps/go/current/src/net/http/server.go:1991 (0x1403405e6)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
C:/Users/user1/scoop/apps/go/current/src/runtime/asm_amd64.s:1594 (0x140071340)
	goexit: BYTE	$0x90	// NOP
"
message:"Internal Server Error - Check the Grafana server logs for the detailed error message."
config:Object
url:"api/ds/query?expression=true"
method:"POST"
data:Object
requestId:"Q118"
hideFromInspector:false
headers:Object
retry:0
message:"Internal Server Error - Check the Grafana server logs for the detailed error message."
```

2022-11-24 03:38 UTC, kostrse commented
Repro:
1. Add `"oauthPassThru": true` to JsonData (any datasource, e.g. Prometheus)
2. Add math expression to panel
3. QueryData won't be executed and Internal Server Error will be shown.

2022-11-24 09:32 UTC, papagian commented
> @marefr @papagian looks like this is good to go, but is blocked? Would it also be possible to port this to 9.1, 9.2 (with a slight preference to 9.2)?

I don't think it's blocked by me; I'm assigned as a reviewer on behalf of the backend platform
but I'm afraid that I'm not a lot in sync with the latest changes regarding expressions & query-ring datasources .
However, if you still think that my review would be beneficial let me know.

2022-11-25 10:43 UTC, kostrse commented
@marefr Now it seems to be working fine.
Tested with several internal and external datasources.

2022-11-28 11:46 UTC, wbrowne approved these changes
LGTM

2022-11-28 12:40 UTC, merged