Alerting: Improve rule validation to check if rule uses backend datasources
grafana/grafana pull request #58986
Opened 2022-11-18 17:04 UTC by yuri-tceretian

**What is this feature?**
Grafana supports frontend-only data sources. Although UI filters out those data sources from the list of available data sources on the rule editor page, API accepts rules that use those data sources, and the error 
```
Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable.
```
occurs in either the query preview phase or during the execution phase. 

This PR improves rule query validation to check whether the datasource(s) mentioned in the alert query have a backend query component. This will make API reject requests that mentioned frontend-only datasources with error 

```
failed to validate condition of alert rule TEST: datasource refID A is not a backend datasource
```

**Which issue(s) does this PR fix?**:
Fixes https://github.com/grafana/grafana/issues/51583

**Special notes for your reviewer**:

2022-12-07 16:24 UTC, alexmobo approved these changes
LGTM

2022-12-07 17:35 UTC, grobinson-grafana requested changes

2022-12-07 17:35 UTC, grobinson-grafana commented on pkg/services/ngalert/eval/eval.go
> +var ErrNotABackendDatasource = errors.New("")
Should this have an error message?

2022-12-08 09:37 UTC, grobinson-grafana approved these changes

2022-12-08 09:37 UTC, grobinson-grafana commented
Looks good to me!

2022-12-08 09:44 UTC, merged