LDAP: Make LDAP attribute mapping case-insensitive
grafana/grafana pull request #58992
Opened 2022-11-18 20:14 UTC by markkrj

Make Grafana's LDAP attribute mapping case-insensitive.
I did a lot of LDAP integrations and never came against this issue, so I think this might be the most common behavior.
Even tools like `ldapsearch` and `ldp.exe` do not care about attribute's letter case.

fix: #11300
fix: #58991

2022-11-18 20:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=58992) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=58992) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=58992) it.</sub>

2022-11-21 13:14 UTC, mgyongyosi requested changes

2022-11-21 13:14 UTC, mgyongyosi commented on pkg/services/ldap/helpers.go
> +			fmt.Println(len(attr.Values))
Could you please remove this line?

2022-11-21 14:07 UTC, markkrj commented on pkg/services/ldap/helpers.go
> +			fmt.Println(len(attr.Values))
Done 😅

2022-11-21 15:17 UTC, mgyongyosi commented on pkg/services/ldap/helpers.go
> +	"fmt"
```suggestion
```

2022-11-22 08:57 UTC, mgyongyosi approved these changes
LGTM. I think it shouldn't cause any problem/breaking change, because the current rule (case-sensitivity) is stricter.

fyi @Jguer

2022-11-22 09:19 UTC, Jguer approved these changes

2022-11-22 12:47 UTC, merged

2022-11-22 12:49 UTC, mgyongyosi commented
Thank you @markkrj for this PR! 🙇  It has been merged. 🎉