Logs: Add callback option onScroll
grafana/grafana pull request #59051
Opened 2022-11-21 14:44 UTC by 2Steaks

**What is this feature?**
Scroll events emitted by the LogsPanel.

**Why do we need this feature?**
The k6 team would like to load logs as the user scrolls rather than using buttons

**Who is this feature for?**
Initially, it would be for k6 load-test users

https://user-images.githubusercontent.com/4395376/203081584-8fbcba31-718a-4de6-a3db-6c4c6e4826c1.mov

2022-11-22 07:11 UTC, leventebalogh requested changes
I think the need is definitely valid and I also like what it enables us to do, however I have a feeling that we might need  to approach it slightly differently. 

One of my concerns is that `PanelProps.options` is usually reserved for custom options that can be configured by the user, and introducing a callback there can create a pattern that causes confusion. 

We should probably try to create a more generic and straightforward support for listening to events like these on a panel. Will have a quick discussion about this with the @grafana/plugins-platform team and get back! 🙏

2022-11-22 14:03 UTC, mckn commented
> I think the need is definitely valid and I also like what it enables us to do, however I have a feeling that we might need to approach it slightly differently.
> 
> One of my concerns is that `PanelProps.options` is usually reserved for custom options that can be configured by the user, and introducing a callback there can create a pattern that causes confusion.
> 
> We should probably try to create a more generic and straightforward support for listening to events like these on a panel. I will spawn a quick discussion about this with the @grafana/plugins-platform team and get back! 🙏

This is great! 

However, I agree with what @leventebalogh says. The requirement is valid but we should probably find a better way to pass this kind of callbacks. We will spend some time trying to provide an alternative solution and get back to you.

2022-11-23 21:08 UTC, mckn commented
Another alternative that might be worth investigating is to move the responsibility of scrolling to outside of the panel. So in the context of panels in dashboards the "PanelChrome" would be responsible for scrolling. In this context you would add a CustomScroll component around the PanelRenderer and would then be able to manage the scrolling in that way.

@torkelo @grafana/dashboards-squad would this even be a possible solution?

2022-12-07 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=59051) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=59051) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=59051) it.</sub>

2023-02-05 02:03 UTC, closed without merging