Dashboard: Making a dashboard editable does not allow resizing of panels
grafana/grafana pull request #59255
Opened 2022-11-23 21:45 UTC by polibb

**What is this feature?**

When `dashboard.meta.canEdit`/`canSave` is updated ([here](https://github.com/grafana/grafana/blob/polibb/rerender-dashboard-grid-when-editable-set/public/app/features/dashboard/components/DashboardSettings/DashboardSettings.tsx#L207)) the `DashboardGrid` should be rerendered in order to rerender `ReactGridLayout` with correct `isDraggable={true}` and `isResizable={true}` props.
It does not rerender because the dashboard prop defies the immutability principle and the object is the same. So, as the quickest/cleanest current solution, we can pass the `dashboard.meta.canEdit` value directly as it is not an object. 

**Why do we need this feature?**

When a read-only dashboard is set to "Make Editable" from its settings, the user can go back to the dashboard. The dashboard should now be editable and for the most part it is, except the Grid layout does not re-render, so it does not allow the resizing of panels as it should. 

**Which issue(s) does this PR fix?**:

Escalation https://github.com/grafana/support-escalations/issues/4493. 

Fixes #

**Special notes for your reviewer**:

2022-11-24 08:39 UTC, ivanortegaalba commented on public/app/features/dashboard/containers/DashboardPage.tsx
> +            isEditable={!!dashboard.meta.canEdit}
Probably you can use the model-getter to make sure we can abstract the logic behind editing a dashboard.
```suggestion
            isEditable={dashboard.canEditDashboard()}
```

2022-11-24 08:40 UTC, ivanortegaalba requested changes
I'm not 100% sure, but I think we need to use the model.canEditDashboard() to also check the `canMakeEditable` boolean in the dashboard model
```js
canEditDashboard() {
  return Boolean(this.meta.canEdit || this.meta.canMakeEditable);
}
```

2022-11-24 09:16 UTC, polibb commented
> I'm not 100% sure, but I think we need to use the model.canEditDashboard() to also check the canMakeEditable boolean in the dashboard model

> ```
> canEditDashboard() {
>   return Boolean(this.meta.canEdit || this.meta.canMakeEditable);
> }
> ```

@ivanortegaalba that's a good suggestion - to use the model's getters, but in this case it would not work because when a dashboard is read-only and it is opened, the `canMakeEditable` prop of the dashboard model is `true` because you can make it editable in the settings. 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/13227501/203744207-a3e00f2f-04e8-4d09-9af9-b230971388e7.png">

2022-12-01 10:01 UTC, ivanortegaalba approved these changes
👍 After the double check, you're right, we cannot rely on that getter. LTGM

2022-12-07 10:46 UTC, merged