Alerting: Rename Message templates to Notification templates
grafana/grafana pull request #59477
Opened 2022-11-29 11:26 UTC by grobinson-grafana

**What is this feature?**

This commit renames "Message templates" to "Notification templates" in the user interface as it suggests that these templates cannot be used to template anything other than the message. However, message templates are much more general and can be used to template other fields too such as the subject of an email, or the title of a Slack message.

**Why do we need this feature?**

I think that changing "Message templates" to "Notification templates" is much better at describing what the templates do, and will help avoid confusion in the documentation when using "Message templates" to template fields other than the message.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2022-11-29 15:39 UTC, armandgrillet requested changes
I believe we need changes in `./docs/sources/alerting/manage-notifications/create-message-template.md` and the API reference on top of this.

2022-12-01 07:58 UTC, brendamuir approved these changes

2022-12-12 06:22 UTC, alexmobo approved these changes
LGTM

2023-01-03 11:20 UTC, jtheory commented
I think this is a good idea!

Checking against our G Ops glossary here: https://docs.google.com/document/d/1RYXX_uLRvqbfZeZcLlR_S4DkCQ2twRBXFiu_gwgkTyY/edit#heading=h.f4h7k04rvaq7

OnCall also has templates but they're parsing with them; I'm not sure if they have notification templates.

@alyssawada FYI, in case there are other related terms in OnCall we should be checking?

We want to get to consistent wording across G Ops (and OnCall + Alerting both do notifications).

2023-01-18 16:06 UTC, armandgrillet approved these changes

2023-01-18 17:26 UTC, merged