Chore: Refactor the root of the `packages/jaeger-ui-components/src/TraceTimelineViewer` folder to TS
grafana/grafana pull request #59748
Opened 2022-12-02 18:48 UTC by CrypticSignal

This PR refactors all JS files in the root of the `packages/jaeger-ui-components/src/TraceTimelineViewer` folder to TypeScript.
#54027

2022-12-05 12:26 UTC, joshhunt commented on packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.test.tsx
> +    (props.setTrace as jest.Mock).mockReset();
instead of `as jest.Mock` you should be able to do `jest.mocked(props.setTrace)`, FYI.

2022-12-05 12:50 UTC, joshhunt commented on packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.test.tsx
> +    (props.setTrace as jest.Mock).mockReset();
It's up to you. They're functionally identical, but _personally_ I believe it's worth, in new code, to limit our use of problematic patterns (`as` type assertions) to set the right example for others.

2022-12-29 14:53 UTC, adrapereira requested changes

2023-01-03 14:10 UTC, CrypticSignal commented on packages/jaeger-ui-components/src/TraceTimelineViewer/VirtualizedTraceView.test.tsx
> +            } as unknown as SpanBarRowProps)}
I don’t think I should change type `SpanBarRowProps` to make properties optional as this is a type that I didn't create and I'm assuming there must be a reason why these properties are not optional.

2023-01-03 14:12 UTC, adrapereira approved these changes

2023-01-03 15:45 UTC, merged