ISSUE_TRIAGE.md: update
grafana/grafana pull request #60299
Opened 2022-12-14 11:19 UTC by tonypowa

- added current bug issue template bullet points to # Bug reports subsection
- updated enhancement requests' subsection by adding info regarding GH discussions
- added link to WCAG criteria in Accessibility issues subsection
- linked Support requests' subsection  to section  # 3 Categorizing an issue/#support-requests subsection

2022-12-14 14:58 UTC, natellium commented
Looking good, just a couple of comments :)

2022-12-16 09:17 UTC, natellium requested changes
It's looking good, left a couple of suggestions

2022-12-16 09:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=60299) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=60299) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=60299) it.</sub>

2022-12-16 09:55 UTC, tonypowa commented on ISSUE_TRIAGE.md
> +This is a mix between a bug report and enhancement request but focused on accessibility issues to help make Grafana improve keyboard navigation, screen-reader support and being accessible to everyone
Thanks for the suggestions. Let me know if the new proposal works :)

2022-12-16 17:45 UTC, mellieA reviewed
What do you think about adding a table for the bot actions in automation? 

It looks like the current version has a link to this page: 
![Screenshot 2022-12-16 at 10 45 22 AM](https://user-images.githubusercontent.com/18175287/208157744-70137273-d37d-48fe-81c4-1f918ae0a4cb.png)

2022-12-16 17:58 UTC, mellieA reviewed
*Investigation of issues* section: 
The new label specific to triage in place of `needs investigation` is [`triage/needs-confirmation`](https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aopen+label%3Atriage%2Fneeds-confirmation)

2022-12-21 09:35 UTC, tonypowa commented
@natellium  I think I am done updating the whole document. Awaiting your review 😸

2022-12-21 13:00 UTC, natellium requested changes
👍 Good updates, left a couple of comments. The flow chart doesn't make sense tho, I'd suggest spending some time understanding what the new flow is and mapping it from scratch.

2022-12-22 13:09 UTC, tonypowa commented on ISSUE_TRIAGE.md
> +Comment commands:
Yeah, let's keep it less busy. Agreed !

2023-01-11 10:19 UTC, tonypowa commented
@natellium resolved pending comments. Hope it is good to go! :)

2023-01-11 12:04 UTC, natellium approved these changes
LGTM, good work! :)

2023-01-19 09:45 UTC, jdbaldry commented
Thanks for the PR. I'm not sure that I'm in the best position to review this document as I don't actively triage issues in this repository. If you'd still like me to take a look, ping me and I'll make sure to do so :)

2023-01-19 17:21 UTC, merged