Plugins: Automatically forward plugin request HTTP headers in outgoing HTTP requests
grafana/grafana pull request #60417
Opened 2022-12-15 18:34 UTC by marefr

**What is this feature?**
Automatically forward core plugin request HTTP headers in outgoing HTTP requests.

Details:
- Introduces constants for the `FromAlert` alerting header and `X-Cache-Skip` header.
- FromAlert plugin request header is forwarded in outgoing HTTP requests in its canonical form, `Fromalert`.

**Why do we need this feature?**
Core datasource plugin authors don't have to specifically handle forwarding of HTTP headers if not having custom needs.

**Who is this feature for?**
Core datasource plugin authors

**Which issue(s) does this PR fix?**:
Fixes #57065 

**Special notes for your reviewer**:

2022-12-15 19:03 UTC, marefr commented
@alexweav adding you as reviewer since you made the change to enable Loki forwarding of `Fromalert` HTTP header in outgoing HTTP request, ref https://github.com/grafana/grafana/pull/56896

2022-12-16 07:51 UTC, gabor reviewed
the Loki changes are ok 👍

2022-12-16 08:08 UTC, gabor commented
@marefr i did some testing for Loki+CallResource, and it seems the `Cookie` header that's sent from the browser to the grafana-server  (so basically the grafana-session-id) , is sent to the Loki database. shouldn't we remove the `Cookie` header there?

2022-12-16 08:17 UTC, marefr commented
> @marefr i did some testing for Loki+CallResource, and it seems the `Cookie` header that's sent from the browser to the grafana-server (so basically the grafana-session-id) , is sent to the Loki database. shouldn't we remove the `Cookie` header there?

@gabor thanks. Interesting. Cookies should only be forwarded if configured in the datasource settings, but the  grafana-session-id should never be forwarded. I'll look into it

2022-12-16 09:03 UTC, svennergr commented
> the Loki changes are ok 👍

Just to be completely sure, I checked if compressing (`Accept-Encoding`) and forward OAuth identity (including `X-ID-Token`) is working in Loki. LGTM - great stuff @marefr!

2022-12-16 10:00 UTC, marefr commented
@gabor pushed a fix for forwarding of cookies. Really good find, thanks. Also found that User-Agent is not properly set and is now fixed as well. 

Planning to add some more validation to the backendplugin integration tests just to be sure. One odd thing I found for Prometheus query data is that it has a header `Accept-Encoding: gzip` set, but I can't understand right now where or how that is set :confused:

2022-12-16 10:06 UTC, svennergr commented
> One odd thing I found for Prometheus query data is that it has a header `Accept-Encoding: gzip` set, but I can't understand right now where or how that is set 😕

Might very well be the auto compression of Go's http transport. It's enabled as long as you don't set `DisableCompression` in https://pkg.go.dev/net/http#Transport.

2022-12-16 10:30 UTC, xnyo requested changes
Awesome! :clap::clap::clap::clap:
Left some comments for a docstring change:

2022-12-16 11:43 UTC, kostrse commented
No regressions with Azure auth

2022-12-16 13:38 UTC, marefr commented on pkg/services/pluginsintegration/clientmiddleware/user_header_middleware.go
> -	ctx = sdkhttpclient.WithContextualMiddleware(ctx, middlewares...)
Fixed

2022-12-16 13:43 UTC, xnyo approved these changes
LGTM! :rocket:

2022-12-16 17:00 UTC, itsmylife approved these changes
🎉

2022-12-21 12:25 UTC, merged