Fix dashboard legend switch for new panels, break for old ones
grafana/grafana pull request #60754
Opened 2022-12-25 21:19 UTC by bobrik

**What is this feature?**

This feature fixes whole dashboard legend toggle via `d` `l`. It existed for a long time, but it seems to only work for old panels (think Graph). This PR makes it work for new ones (think Timeseries).

In #52241 @alyssabull broke `p` `l` (panel level toggle) for old panels, but fixed it for new ones. I'm bringing the same change to the dashboard level toggle. I'm not sure if old panels were meant to be broken.

**Why do we need this feature?**

It exists in keyboard shortcuts, so it needs to be working.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

See also: #49005.

2023-01-25 02:08 UTC, bobrik commented
We have this applied internally. I left a comment on #52241 to hopefully get some attention.

2023-01-27 09:05 UTC, dprokop requested changes
@bobrik thanks for opening this PR!

> I'm not sure if old panels were meant to be broken.

No, they were not meant to be broken.

 Your change indeed fixes the issue for the new panels, but can you also make sure this works for the old ones?

2023-03-02 14:11 UTC, dprokop commented
@bobrik just a friendly ping here. Let us know if you could wrap up this PR any time soon.

2023-03-03 04:03 UTC, bobrik commented
I can't add any old Graph panels in my instance:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/89186/222628450-aa37d53b-3112-4e01-8c67-b80858743500.png">

If anyone has capacity to work on this, please feel free to take over.

2023-03-03 04:03 UTC, closed without merging