Glue: Hide run queries button in Correlations Page
grafana/grafana pull request #61039
Opened 2023-01-05 13:02 UTC by ifrost

…ometheus editors

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2023-01-05 14:11 UTC, ivanahuckova approved these changes
LGTM 🙂

2023-01-05 15:02 UTC, ifrost commented
Big question to @grafana/dashboards-squad, @grafana/observability-logs and @grafana/observability-metrics - why do we have a "Run Queries" button inside the editor? Would it be possible to break the API in the future and stop providing "runQuery()" handler so the running always happens outside of the editor (related to https://github.com/grafana/grafana/issues/51979)

2023-01-05 15:12 UTC, matyax commented
@ifrost the button doesn't need to be there, but the `onRunQuery` prop is shared with the Label Browser, Query Editor, and Query Builder. I can only see the Label Editor being factored out of the component, but the Editor and Builder need it. In the case of the Editor, for example, it's used for the `cmd + shift` and the `unblur` query running behavior.

2023-01-05 15:15 UTC, gtk-grafana commented
@ifrost That's a good question, right now there's plenty of usage with `runQuery` within the plugins, so this would require some investigation on a per-datasource basis. Influx doesn't look too bad, but prometheus makes a lot of custom calls to that function.

2023-01-05 15:21 UTC, svennergr commented
> Big question to @grafana/dashboards-squad, @grafana/observability-logs and @grafana/observability-metrics - why do we have a "Run Queries" button inside the editor?

Don't know if that answers your question, but I think it's mostly for editing dashboard panels, where you don't have an other `Run Queries` button.

2023-01-05 16:57 UTC, gelicia approved these changes
LGTM

2023-01-05 23:27 UTC, Elfo404 requested changes

2023-01-05 23:27 UTC, Elfo404 commented on public/app/plugins/datasource/loki/components/LokiQueryEditor.test.tsx
> +}
let's use more semantic selectors:
```suggestion
function expectRunQueriesButton() {
  expect(screen.getByRole('button', { name: /run queries/i })).toBeInTheDocument();
}

function expectNoRunQueriesButton() {
  expect(screen.queryByRole('button', { name: /run queries/i })).not.toBeInTheDocument();
}
```

2023-01-05 23:27 UTC, Elfo404 commented on public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryEditorSelector.test.tsx
> +
same as the other comment:
```suggestion
let's use more semantic selectors:
```suggestion
function expectRunQueriesButton() {
  expect(screen.getByRole('button', { name: /run queries/i })).toBeInTheDocument();
}

function expectNoRunQueriesButton() {
  expect(screen.queryByRole('button', { name: /run queries/i })).not.toBeInTheDocument();
}
```
```

2023-01-09 13:35 UTC, Elfo404 approved these changes

2023-01-12 20:14 UTC, merged