tracing: Support multiple OTel propagators
grafana/grafana pull request #61199
Opened 2023-01-09 22:38 UTC by hairyhenderson

**What is this feature?**

Adds support for setting multiple OTel propagators.

**Why do we need this feature?**

When migrating from Jaeger to W3C propagation with OTel, it's helpful to be support both propagation formats simultaneously, so as not to break any traces.

**Who is this feature for?**

Anyone operating and monitoring Grafana

**Which issue(s) does this PR fix?**:

Fixes #61198 

**Special notes for your reviewer**:

Signed-off-by: Dave Henderson <dave.henderson@grafana.com>

2023-03-14 12:05 UTC, bboreham commented
I want to use this change; I'm going to see if I can fix the tests.

2023-03-14 15:43 UTC, hairyhenderson commented
Thanks @bboreham 🙇‍♂️ - I got pulled away to other things and couldn't focus on this 😞 (and then it turned out I don't actually need this). Let me know if you need anything from me!

2023-03-14 16:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=61199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=61199) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hairyhenderson<br/>:x: bboreham<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=61199) it.</sub>

2023-03-14 16:47 UTC, hairyhenderson commented
I'll rebase if this passes!

2023-03-14 20:42 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/_index.md
> +The propagation specifies the text map propagation format. The values `jaeger` and `w3c` are supported. Specify multiple values separated by a comma (`,`) to support multiple formats (like `"jaeger,w
```suggestion
The propagation specifies the text map propagation format. The values `jaeger` and `w3c` are supported. Add a comma (`,`) between values to specify multiple formats (for example,  `"jaeger,w3c"`). The default value is `w3c`.
```

2023-03-14 20:42 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/_index.md
> +The propagation specifies the text map propagation format. The values `jaeger` and `w3c` are supported. Specify multiple values separated by a comma (`,`) to support multiple formats (like `"jaeger,w
```suggestion
The propagation specifies the text map propagation format. The values `jaeger` and `w3c` are supported. Add a comma (`,`) between values to specify multiple formats (for example,  `"jaeger,w3c"`). The default value is `w3c`.
```

2023-03-14 20:44 UTC, hairyhenderson commented on docs/sources/setup-grafana/configure-grafana/_index.md
> +The propagation specifies the text map propagation format. The values `jaeger` and `w3c` are supported. Specify multiple values separated by a comma (`,`) to support multiple formats (like `"jaeger,w
thanks - that's better!

2023-03-14 20:44 UTC, chri2547 requested changes
Docs suggestions added. Please make sure I didn't change the technical meaning. Please request re-review when you are done. Thanks!

2023-03-14 20:46 UTC, chri2547 reviewed
Docs look good, thank you! I approve (soft approve).

2023-03-14 20:47 UTC, hairyhenderson commented
@chri2547 can you un-request changes? this is still blocked by https://github.com/grafana/grafana/pull/61199#pullrequestreview-1340251207

2023-03-14 20:50 UTC, chri2547 approved these changes

2023-03-14 21:10 UTC, hairyhenderson commented
CI is failing with:

```
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

(I guess this is from https://github.com/grafana/grafana/pull/61199/commits/3d448b6abf7b4306980f8c6a80c975a2418ca399)  I'll take a look tomorrow

2023-03-21 12:14 UTC, marefr commented
@hairyhenderson sync with main should do the trick I believe.

2023-03-21 12:15 UTC, hairyhenderson commented
@marefr yup - was trying to commit, but the precommit hook was broken:

```
file:///Users/hairyhenderson/go/src/github.com/grafana/grafana/.yarn/cache/lint-staged-npm-13.1.2-6f136d35c9-f854ad5c88.zip/node_modules/lint-staged/lib/index.js:113
    if (runAllError?.ctx?.errors) {
                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I think I've got it now.

2023-03-21 12:18 UTC, hairyhenderson commented
> Today I realised there is an existing function `TraceIDFromContext()` which might be used to do the same thing I did with `TradeIDString()`. This probably needs someone with context on the tracing package to weigh in.

Given that `TraceIDFromContext` requires a context, and `TraceIDString` is only used in tests, IMO it's fine as-is.

2023-03-21 13:02 UTC, hairyhenderson commented
> Given that `TraceIDFromContext` requires a context, and `TraceIDString` is only used in tests, IMO it's fine as-is.

I spoke too soon - we have a context indeed, so using `tracing.TraceIDFromContext` is simpler - I've made that change!

2023-03-27 15:41 UTC, marefr approved these changes
LGTM

2023-03-27 18:56 UTC, merged