(prometheus) adhoc filter support
grafana/grafana pull request #6138
Opened 2016-09-28 10:26 UTC by mtanda

https://github.com/grafana/grafana/issues/6038

2016-09-28 10:37 UTC, torkelo requested changes

2016-09-28 10:37 UTC, torkelo commented on public/app/features/templating/templateSrv.js
> +        var adhocVar = _.find(self._adhocVariables, function(v) {
this should not be here, the filter should be added to the query automatically in the datasource query code (see elasticsearch or InfluxDB for example)

2016-09-28 10:37 UTC, torkelo commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
I do not think this global label keys option is a good idea. 
Think the proper solution is to
1) Add a metric/measurement input option the Ad Hoc Filter Variable options (that can limit the tag keys), will be optional for ES/InfluxDB but requrired for Prometheus. 

2) Wait until Prometheus implements a way to get all keys

2016-09-28 10:42 UTC, mtanda commented on public/app/features/templating/templateSrv.js
> +        var adhocVar = _.find(self._adhocVariables, function(v) {
Okay, I'll check it.

2016-09-28 10:43 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
1) is good choice for me. I'll try it.

2016-09-28 12:18 UTC, mtanda commented on public/app/features/templating/templateSrv.js
> +        var adhocVar = _.find(self._adhocVariables, function(v) {
Fixed this.

2016-09-28 12:20 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
@torkelo I can't find the "metric/measurement input option" in template variable editor. Would you tell me where the option is exist?

2016-09-28 12:20 UTC, torkelo commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
there is no such option yet, has be added

2016-09-29 06:34 UTC, bergquist commented
ref https://github.com/prometheus/prometheus/issues/2038

2016-09-29 09:56 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
I change to gather label keys from query response.
User don't need to set label key manually.

2016-09-29 10:06 UTC, torkelo commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
how is that possible? dont you need a metric name for a query?

2016-09-29 10:20 UTC, torkelo commented
>Please see this query.
It is normal case, all metrics in query doesn't have some of labels.
The method_code:http_errors:rate5m has code labels, but method:http_requests:rate5m is not.

This feature is not built for that case then. For that case you can use normal query variable. The Ad hoc filters is for exploratory dashboards where you can filter all data by ad hoc key/value pair.s

2016-09-29 10:37 UTC, mtanda commented
hmm, it is quiet useful if we can build filter part in adhoc filter UI.
But, I understand why you don't want to embed template variable in query expression.
User should start to make adhoc filter without opening query editor.

The query doesn't have "on" or "ignoring" clause, it is safe to add filter part to all metrics.
And, if there are "on" or "ignoring" clause, the adhoc filter shouldn't show label key in "ignoring" clause or something.

The query parser provide such information, it is possible to adhoc filter support in Prometheus.

2016-09-29 10:46 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
If it is OK to show all label keys in UI, no need to metric name.

If user start to edit adhoc filter, the dashboard might have some graph panel, and datasource plugin already receive query response.
Gathering label keys in the response, and provide label keys to adhoc filter UI is good choice, I think.
The label keys in query response is mostly usable in the dashboard.

2016-09-29 10:51 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
I reconsider about the possibility to get all label keys from query response.
And it is NO. Some of the label keys can get from response.
But, if the query use "count" or aggregate function, the labels which metrics has, is not appeared in query response...

Gathering label keys from response could improve coverage of label keys.
But, need to input box too. I'll add it.

2016-10-03 12:14 UTC, mtanda commented
I misunderstand about this part.
```
All job="node" is filter part.
So it is meaningless to find first "{".
```

To use adhoc filter, don't need to add adhoc filter for all PromQL filter part.
Add first one is enough, other metrics automatically follow first one's filter.
Some of query, the metrics order is important (like "group_left" or "group_right"), but it can be rewritable, it's OK.

2016-10-03 12:56 UTC, mtanda commented
https://prometheus.io/docs/querying/operators/#arithmetic-binary-operators
> Between two instant vectors, a binary arithmetic operator is applied to each entry in the left-hand-side vector and its matching element in the right hand vector. The result is propagated into the result vector and the metric name is dropped. Entries for which no matching entry in the right-hand vector can be found are not part of the result.

2016-10-04 14:42 UTC, mtanda commented on public/app/plugins/datasource/prometheus/partials/config.html
> +		<input type="text" class="gf-form-input max-width-18" ng-model='ctrl.current.jsonData.labelKeys' placeholder="job,instance"></input>
Added "metric" input box.

2016-10-04 14:43 UTC, mtanda commented
This PR is ready to re-review.

2016-12-12 20:31 UTC, filippog commented
Hi, has there been any progress on this feature?
It seems a really useful feature to be able to ad-hoc explore prometheus dashboards too

2016-12-13 00:55 UTC, mtanda commented
I wait for Prometheus query editor refinement.
https://github.com/grafana/grafana/pull/6138#commitcomment-19208398

When it is ready, I'll fix conflict.

2016-12-13 18:21 UTC, filippog commented
> I wait for Prometheus query editor refinement.
> #6138 (comment)
> 
> When it is ready, I'll fix conflict.

Thanks @mtanda ! I can't find a specific GH issue for that, is there one open already I could follow?

2016-12-14 00:21 UTC, mtanda commented
@filippog I didn't create GH issue.
If you create the issue with describing your use case, it is greatly helpful :-)

2016-12-16 20:17 UTC, filippog commented
> If you create the issue with describing your use case, it is greatly helpful :-)

re-reading this issue it looks like my use case is exactly like yours, thanks!

2017-04-25 09:45 UTC, torkelo commented
closing this for now as Prometheus api does not currently support the required api, and it could be better implemented after we have new query editor & model

2017-04-25 09:45 UTC, closed without merging