Chore: Update `CODEOWNERS` for edge to dataviz
grafana/grafana pull request #62408
Opened 2023-01-27 23:13 UTC by nmarrs

Update the codeowners file with rename of edge squad to dataviz

2023-01-27 23:17 UTC, nmarrs commented on .github/CODEOWNERS
> +/devenv/jsonnet/ @grafana/dataviz-squad
Not sure if dataviz should keep this vs. hand off to someone else (i.e. maybe to Todd in @grafana/multitenancy-squad)?

2023-01-27 23:17 UTC, nmarrs commented on .github/CODEOWNERS
> +/public/app/features/comments/ @grafana/dataviz-squad
Same comment here - I think this is from an experimental feature Alexander worked on - so not sure we should keep this

2023-01-27 23:17 UTC, nmarrs commented on .github/CODEOWNERS
> +/public/app/features/query-library/ @grafana/dataviz-squad
Not sure about keeping ownership on this as well

2023-01-27 23:19 UTC, nmarrs commented
It appears that new @grafana/dataviz-squad will first need to be approved to be under the [Grafana Team](https://github.com/orgs/grafana/teams/grafana-team) so that it is recognized / has proper access

2023-02-06 16:47 UTC, tolzhabayev commented
@nmarrs please rebase on the main to fix the codeowners validation error (it needs to include these changes https://github.com/grafana/grafana/pull/62689)
![SCR-20230206-opl](https://user-images.githubusercontent.com/580672/217032691-9ead7977-3e33-4c94-be9b-2244158a3884.png)

2023-02-06 16:48 UTC, tolzhabayev requested changes
please rebase first

2023-02-11 00:27 UTC, closed without merging

2023-02-11 00:27 UTC, nmarrs commented
Closing as addressed by https://github.com/grafana/grafana/pull/63200