API: fix docs of users API (#62365)
grafana/grafana pull request #62816
Opened 2023-02-02 18:41 UTC by bla2ej

**What is this feature?**

Updates Users API documentation to explain API Tokens behavior.

**Why do we need this feature?**

Documentation does not include info similar to Admin API about API Tokens. This caused rising the issue.

**Who is this feature for?**

Developers.

**Which issue(s) does this PR fix?**:

Fixes #62365

**Special notes for your reviewer**:

2023-02-07 14:46 UTC, Eve832 requested changes

2023-02-23 17:37 UTC, bla2ej commented on docs/sources/developers/http_api/user.md
> +user must have the Grafana Admin permission. (The default admin user is called `admin` and has permission to use this API.)
Should I do anything more?

2023-05-25 11:19 UTC, tonypowa commented
👋 @grafana/docs-squad 

whenever possible, could you please review the pull request and provide feedback to the author?

thank you

2023-07-28 14:03 UTC, Eve832 approved these changes

2023-07-28 14:03 UTC, merged