Docs: Add 'tenant_id' for Loki clients (Auditing & Analytics)
grafana/grafana pull request #63098
Opened 2023-02-08 13:43 UTC by joanlopez

**What is this feature?**

Docs update according to https://github.com/grafana/grafana/pull/60866 and https://github.com/grafana/grafana-enterprise/pull/4276

**Why do we need this feature?**

Keep docs updated

**Who is this feature for?**

Auditing & Usage Insights users

**Which issue(s) does this PR fix?**:

N/A

**Special notes for your reviewer**:

Does that sound enough? @mjseaman Any idea?

I'm wondering if I should create the corresponding [What's new?](https://github.com/grafana/grafana/tree/main/docs/sources/whatsnew) for `v9.4`? 
Is it created manually just right before the stable release? It sounds suspicious that it doesn't exist yet.

2023-02-08 20:57 UTC, mjseaman commented
@joanlopez my only small suggestion would be to link to the Loki docs that describe tenants, if those exist.

2023-02-20 16:33 UTC, mjseaman commented on docs/sources/setup-grafana/configure-grafana/enterprise-configuration/index.md
> +Set the tenant id for Loki communications. Disabled by default. Mandatory to interact with Loki running in multi-tenant mode.
```suggestion
Set the tenant id for Loki communications. Disabled by default. Mandatory to interact with Loki running in [multi-tenant mode](https://grafana.com/docs/loki/latest/operations/multi-tenancy/).
```

2023-02-21 17:06 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/enterprise-configuration/index.md
> +Set the tenant id for Loki communications. Disabled by default. Mandatory to interact with Loki running in multi-tenant mode.
Links to docs in other repos follows this convention: [link text](/docs/repo/version/folder/file/).

I'll make that suggestion. Just wanted y'all to know.

2023-02-21 17:11 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/audit-grafana.md
> +# Set the tenant id for Loki communications. Disabled by default.
```suggestion
# Set the tenant ID for Loki communications, which is disabled by default.
```

2023-02-21 17:12 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/audit-grafana.md
> +# Mandatory to interact with Loki running in multi-tenant mode.
```suggestion
# The tenant ID is required to interact with Loki running in multi-tenant mode.
```

2023-02-22 13:18 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/export-logs.md
> +# Mandatory to interact with Loki running in multi-tenant mode.
```suggestion
# The tenant ID is required to interact with Loki running in multi-tenant mode.
```

2023-02-22 13:20 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/export-logs.md
> +# Set the tenant id for Loki communications. Disabled by default.
```suggestion
# Set the tenant ID for Loki communication, which is disabled by default.
```

2023-02-22 13:23 UTC, chri2547 requested changes
some minor suggestions. Thank you for the contribution!

2023-03-27 14:59 UTC, joanlopez commented
> @joanlopez my only small suggestion would be to link to the Loki docs that describe tenants, if those exist.

> some minor suggestions. Thank you for the contribution!

Apologies for having this forgotten for weeks, finally applied the feedback, thanks for your suggestions & contributions! 

> Just wanted y'all to know.

Awesome, thanks for clarifying it! 

💟

2023-03-27 18:36 UTC, chri2547 approved these changes
Thank you for the contribution!

2023-03-27 20:44 UTC, merged