K8s: Proof of Concept
grafana/grafana pull request #63223
Opened 2023-02-09 20:28 UTC by toddtreece

This is the main feature branch that all other K8s PoC related PRs merge into.

2023-02-09 21:00 UTC, ryantxu requested changes
adding a request changes note to block merging

2023-03-29 18:01 UTC, ryantxu commented on Makefile
> +GO = CGO_CFLAGS="-DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_USE_ALLOCA=1" go
required for kine... but not ideal

2023-04-10 18:01 UTC, toddtreece commented
@ryantxu requested that this be split into two branches:
* #66218 
* #66219 

closing in favor of those PRs

2023-04-10 18:01 UTC, closed without merging

2023-04-11 06:51 UTC, DanCech commented
it may make things easier to follow if we keep this PR open and use k8s-proof-of-concept as the base for the other 2 PRs, vs having the approach-specific code mixed in with the base PoC code.  Might also help keep approach-agnostic changes separate since they can be pushed here then merged into the other 2 branches.