Prometheus: Metric encyclopedia
grafana/grafana pull request #63423
Opened 2023-02-19 15:45 UTC by bohandley

WIP 

**What is this feature?**
This feature adds a new way of exploring and selecting a metric in the Prometheus query builder (not implemented for the code editor). This is a modal that displays paginated and filterable metrics with metadata. A fuzzy search can be used to select text in metric metadata. Users can filter by type and functions associated with the metric.

**Why do we need this feature?**
The G10 Getting Started: Prometheus research uncovered a need for beginning users to be able to explore their metrics in a meaningful way. This paginated modal also solves the issue of displaying millions of metrics in the frontend.

**Who is this feature for?**
This feature is for beginning Prom users, intermediate users, users of the Prom query builder, and customers with millions of metrics.

### Tasks

#### Testing/Validation
- [ ] Feature Tracking (rudderstack event) and testing
- [ ] Merge to main under feature flag
  - [ ] deploy to metrics grafana instance 
- [ ] User Interviews

#### Implementation
- [x] Implement Feature toggle 
- [x] Create modal
- [x] Load metrics and metadata
- [ ] Add tests
- [ ] Paginate
  - [ ] slice metrics 
  - [ ] page select or page number buttons 
  - [ ] include alphabetical pagination navigation (A|B|...|Z)
  - [ ] user selects # metrics displayed per page
- [ ] Filter by type
- [ ] Filter by function
- [ ] Filter by labels
- [ ] Filter by fuzzy search
- [ ] Test with millions of metrics
  - [ ] Loading gif 
- [ ] Fix issue with metrics that are missing metadata
  - [ ] display missing metadata
  - [ ] include with other metrics filters on type/function as additional unknown

**Special notes for your reviewer**:
This is a work in progress. First we will implement the functionality then we will work with UX to make it look good :)

2023-02-27 14:16 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/feature-toggles/index.md
> +| `prometheusMetricEncyclopedia`     | Replace the Prometheus builder editor metric select with a paginated and filterable component
```suggestion
| `prometheusMetricEncyclopedia`     | Replaces the Prometheus query builder metric select option with a paginated and filterable component                                                                                |
```

2023-02-27 14:17 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/feature-toggles/index.md
> +| `prometheusMetricEncyclopedia`     | Replace the Prometheus builder editor metric select with a paginated and filterable component
@bohandley , please review my suggestion to ensure I haven't changed the technical meaning of the content. Thank you!

2023-02-27 14:18 UTC, chri2547 requested changes
A suggestion. Please ping me for a re-review and then I'll approve. Thank you very much for the contribution!

2023-02-27 21:44 UTC, bohandley commented
> @bohandley So after testing this using ops-cortex-dev on the main branch and on your branch, the biggest problem I'm seeing is that the new explore encyclopedia is much slower to show valid results to the user for the same queries, and also it looks as though searches are blocking the main thread, so for long searches the user can type many characters into the search, and then slowly watch as the results update, and then eventually the chars they entered into the search box will show up. This is a more frustrating UX for slow datasources, the current metric dropdown might take a while to query the API and return results, but the user's text input shows up without delay, and loading indicators are visible.

Yes! Thank you for the pointer to the ops-cortex-dev. There's definitely some things I can do to have it not block the main thread and speed up showing valid results. Thank you for pointing this out!

> 
> Connect to the ops-cortex-dev instance (https://grafana-dev.com/orgs/raintank/hosted-metrics/9960) and make any search and you should see what I mean.
> 
> Also when the modal opens can we automatically focus the metric search input so the user can start typing with the same number of clicks as the current implementation? Otherwise they need to open the encyclopedia, and then find the metric search box before they can start entering text.

Can do! I can reduce the number of clicks for sure.

> 
> This is just my cursory notes, I'll need some more time to dig into this further.

Thank you @gtk-grafana!!! I appreciate the feedback :)

2023-03-01 21:03 UTC, bohandley commented
UX updates @mary-sitzenstatter @catherineymgui @evandandrea 

- [ ] Add button to open model and show selected metric with a tag
- [ ] Shift "page / # per page" closer to the results list.
  - [ ] "# of results per page"
  - [ ] Add "results" header to list.
  - [ ] Pagination on bottom, as results list
- [ ] Add more padding between fields.
- [ ] update "search" label to browse
- [ ] add groupings: Browse, filter, pagination

- [ ] Research: What are the general search and filter patterns within Grafana? reach out to  @amy-super 
  - [ ] Does the user have an idea or not of what to search?
  - [ ] How do new users go about exploring?
  - [ ] Recommendations or clues of searching and filtering in grafana
- [ ] Remove functions, they are not part of the work flow and the suggestions exist in query hints and kick start your query
- [ ] Sign up for next week UX session :slightly_smiling_face:
- [ ] Let Mary and Catherine know which one I sign up for

2023-03-05 02:36 UTC, bohandley commented
Next up:
- [ ] Give users the option to search on the backend
- [ ] focus on browser input on opening modal

2023-03-07 13:51 UTC, chri2547 approved these changes
Docs look great, approved!

2023-03-07 18:41 UTC, merged

2023-03-07 18:41 UTC, gtk-grafana commented
In general, I love this, and I think the UX of the encyclopedia is pretty well flushed out for an initial release, but the other changes to the editor UI are confusing to me as a user.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/109082771/223517867-39020136-a1b8-4a88-a61b-360b5b4063e6.png">
It's not obvious to me that the metric encyclopedia is the first thing I should do to build a query. I'm not exactly sure what the solution here is, maybe something as simple as literally numbering metric,label,values as 1,2,3

<img width="624" alt="image" src="https://user-images.githubusercontent.com/109082771/223518177-37b02ac8-098b-49e1-b8d4-c7de2a20aac5.png">
Also when it's scrunched up the layout changes

<img width="218" alt="image" src="https://user-images.githubusercontent.com/109082771/223517058-49d19c1a-7b28-44e4-806b-85401f71d841.png">
The hover/focused state for these should have a more obvious visual indication that clicking will remove it, I like the good use of title text, but an "X" svg that appears on hover would help visually reinforce the action.
Also generally the selected green metric is the only thing with color on the page, so it becomes the focus of the page, I'd want to mute it down a bit

Also the hint is unaligned, not sure if that's on main or not tho.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/109082771/223518735-5a497edd-9b5d-4419-b070-ff030a56dce9.png">

2023-03-07 20:17 UTC, gtk-grafana commented
I liked the UI team's feedback to change the layout of the results, the current UI uses up a lot of space:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/109082771/223539249-47dbe188-6137-46e5-85c6-0d06469b5aa2.png">
<img width="806" alt="image" src="https://user-images.githubusercontent.com/109082771/223539488-547d2bf6-79f0-4b4d-a067-44bde3b2c52f.png">

Maybe we move the primary action up into the row with the text:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/109082771/223540248-7e3588c1-af51-4a93-afd5-ff5b026c6eda.png">
And then allow a secondary action of opening the metadata?

More tinkering with padding, but I only made one example button, so use your imagination! 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/109082771/223541043-d905816b-7974-461e-b087-6564eeb4d8f6.png">

https://user-images.githubusercontent.com/109082771/223542493-27316d79-f110-4650-a67f-7f76caffab1c.mov

Just a few thoughts and ideas

2023-03-07 20:30 UTC, gtk-grafana commented
So I like that this fits nicely in one row, but maybe there's a way to add some small text labels without taking up too much space? 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/109082771/223545002-8cf62580-3e3c-4507-a6d6-fa9913edc903.png">

2023-03-07 20:47 UTC, gtk-grafana commented
Something else I just thought of, is that I'm a little worried about giving users whiplash with the default behavior of this component: it was initially searching on the client, and then on the backend, and now on the client with the option of backend. I also am not sure that backend search is the best functionality for most users, so I think this is a good change, but we might want to find a way to make the differentiation as clear as possible. And maybe think about letting users set the default value? Might be annoying to have to change every time if the default doesn't work for your use case. 

Pro feature: regex works on both be/fe searches 🎉 🎉 🎉 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/109082771/223547761-5c1b36c6-c083-4b59-8999-95b6770306be.png">

2023-03-07 22:38 UTC, bohandley commented
> Something else I just thought of, is that I'm a little worried about giving users whiplash with the default behavior of this component: it was initially searching on the client, and then on the backend, and now on the client with the option of backend. I also am not sure that backend search is the best functionality for most users, so I think this is a good change, but we might want to find a way to make the differentiation as clear as possible. And maybe think about letting users set the default value? Might be annoying to have to change every time if the default doesn't work for your use case.
> 
> Pro feature: regex works on both be/fe searches 🎉 🎉 🎉 <img alt="image" width="788" src="https://user-images.githubusercontent.com/109082771/223547761-5c1b36c6-c083-4b59-8999-95b6770306be.png"> <img alt="image" width="764" src="https://user-images.githubusercontent.com/109082771/223548952-05cc7d12-ec37-4283-a2cd-51b06582c28a.png">

I agree, more differentiation is good and adding a configuration to have it stick, FE or BE search. We can do this!

Also, I know regex works in the backend, but the frontend too? Whoo-hoo! That may be behavior of uFuzzy though? @leeoniya I am using uFuzzy for this fuzzy search so I know it accepts a lot of variation in the needle, does it accept regex too?

2023-03-08 22:04 UTC, bohandley commented
Feedback from @galen and UX team to be implemented in M.E. Part II

- [ ] add feedback option for users to complete a form and opt in for an interview
- [ ] Order components top to bottom, M.E., labels, operations, give numbers like the Metrics Browser for Code
- [ ] Differentiate backend search and allow it to stay once user has selected it
- [ ] Add `X` to explicitly show removing the selected metric
- [ ] Show results in table, no more expanding
- [ ] Wider modal, more real estate
- [ ] Select button on right inline row
- [ ] Sticky results page select and # of results at bottom of modal
- [ ] [pagination component](https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-pagination--with-pages) that is in Storybook
- [ ] Label the switches
- [ ] Rename to Metric Browser
- [ ] Limit users to display