Docs: Add Private Data Source Connect docs
grafana/grafana pull request #63469
Opened 2023-02-20 17:26 UTC by mjseaman

Add documentation for private data source connect, available in Cloud Pro and Advanced in closed preview

**What is this feature?**

Add documentation for private data source connect, available in Cloud Pro and Advanced in closed preview. These docs should be public, but not indexed or searchable. 

**Who is this feature for?**

Closed preview customers, who will all be given a link to the docs.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2023-02-20 22:02 UTC, chaudyg commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect.md
> +        docker run --rm --name pdc-agent -v $(pwd):/etc/keys grafana/pdc-agent:latest -i /etc/keys/${SLUG} ${SLUG}@host.docker.internal -p 2222 -o BatchMode=yes -o UserKnownHostsFile=/etc/keys/known_
```suggestion
        docker run --rm --name pdc-agent -v $(pwd):/etc/keys grafana/pdc-agent:latest -i /etc/keys/${SLUG} ${SLUG}@${PDC_GATEWAY} -p 22 -o BatchMode=yes -o UserKnownHostsFile=/etc/keys/known_hosts -o CertificateFile=/etc/keys/${SLUG}-cert.pub -R 0 -v
```

2023-02-20 22:02 UTC, chaudyg commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect.md
> +        - -p 2222: The docker container port
```suggestion
        - -p 22: The port to connect to
```

2023-02-22 13:10 UTC, chri2547 requested changes
One small change to image. Thank you!

2023-02-23 14:02 UTC, chri2547 approved these changes
Great stuff! Thank you!

2023-02-23 14:20 UTC, chaudyg commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +     - ${PDC_GATEWAY}: The URL of the private data source connect in Grafana Cloud. The Grafana team will give you this URL. The URL follows the format `grafana-private-datasource-connect-&lt;cluster
```suggestion
     - ${PDC_GATEWAY}: The URL of the private data source connect in Grafana Cloud. The Grafana team will give you this URL. The URL follows the format `private-datasource-connect-<cluster>.grafana.net`
```

2023-02-23 14:24 UTC, merged