Fixes #63133
grafana/grafana pull request #63478
Opened 2023-02-21 02:57 UTC by MTLChrisLEE

**What is this feature?**

Returns 200 with "Already starred dashboard!" instead of an internal server error.

**Why do we need this feature?**

The status code and the error message are misleading.

**Who is this feature for?**

For users who call POST /api/user/stars/dashboard/{:id} or /api/user/stars/dashboard/uid/{:dashboardUID} without Grafana UI

Fixes #63133

**Special notes for your reviewer**:
This is my first PR for Grafana.
I tried to find and add tests for this api. I failed to find where the corresponding tests are.
Please, let me know where they are. Thanks.
Also, if you find a message is not good enough, feel free to leave a comment.
Thanks!

2023-02-21 02:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=63478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=63478) before we can accept your contribution.<br/><hr/>**sanghyuk lee** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=63478) it.</sub>

2023-04-05 11:46 UTC, papagian requested changes
Thank you for your contribution!

I still get 500 status code (with a better error message):

```
curl -XPOST -v http://admin:admin@localhost:3000/api/user/stars/dashboard/30
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
* Server auth using Basic with user 'admin'
> POST /api/user/stars/dashboard/30 HTTP/1.1
> Host: localhost:3000
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.87.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Cache-Control: no-store
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-Xss-Protection: 1; mode=block
< Date: Wed, 05 Apr 2023 11:38:16 GMT
< Content-Length: 91
< 
* Connection #0 to host localhost left intact
{"error":"dashboard was already starred","message":"Failed to star dashboard","traceID":""
```

I think you still have to handle `star.ErrDashboardAlreadyStarred` and return a different status code here:
https://github.com/grafana/grafana/blob/c9288868f44cf520ef144967ca3674225a8f6a3f/pkg/services/star/api/api.go#L135
and here:
https://github.com/grafana/grafana/blob/c9288868f44cf520ef144967ca3674225a8f6a3f/pkg/services/star/api/api.go#L103


Also, I think that is better instead of `http.StatusOK` response in case of a already starred dashboard to return `http.StatusNotModified`

2023-04-05 11:46 UTC, papagian commented on pkg/services/star/model.go
> +	ErrDashboardAlreadyStarred = errors.New("dashboard was already starred")
nit
I would suggest declaring this as `github.com/grafana/grafana/pkg/util/errutil.Error` as suggested [here](https://github.com/grafana/grafana/blob/main/contribute/backend/errors.md#declaring-errors)

2023-04-06 02:32 UTC, MTLChrisLEE commented
Hi @papagian ,

Thank you for the review.

Actually, I was not sure about which status should be returned. 
When I was fixing the issue, I looked at other services and I found that queryHistory has quite similar request/response.

https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/api.go#L160
https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/database.go#L205
https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/models.go#L12

I think it's better to keep the consistency. But, it's really up to you. I don't mind changing it to other status.

What do you think?

2023-05-02 09:54 UTC, papagian commented
> Hi @papagian ,
> 
> Thank you for the review.
> 
> Actually, I was not sure about which status should be returned. When I was fixing the issue, I looked at other services and I found that queryHistory has quite similar request/response.
> 
> https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/api.go#L160 https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/database.go#L205 https://github.com/grafana/grafana/blob/main/pkg/services/queryhistory/models.go#L12
> 
> I think it's better to keep the consistency. But, it's really up to you. I don't mind changing it to other status.
> 
> What do you think?

no strong opinions but it seems better to me, since we fix the status to return the more appropriate one rather than trying to conform to whatever the query history returns.

2023-05-07 18:16 UTC, MTLChrisLEE commented
Hi @papagian 

Sorry for the late reply. I just updated my PR.
I agree. If the query history behavior/response is not _exemplary_, yes,we should return a different status.
However, if we are returning a http.StatusOK, then I don't think we need another message.

If the message is something like "The dashboard is **already** starred"
I think the message is bit misleading.

What do you think about returning the successful message as like it was the first time that the user was starring the dashboard

2023-05-11 08:37 UTC, papagian approved these changes
thank you for your contribution

2023-05-11 08:37 UTC, merged