Add link to building backend datasource
grafana/grafana pull request #63535
Opened 2023-02-21 22:22 UTC by katebrenner

**What is this feature?**

Update the docs for building a new data source by adding a link to the tutorial for building a backend datasource

**Why do we need this feature?**

This is helpful context for creating a new datasource - it is not clear that the guide is not inclusive of backend datasource

**Who is this feature for?**

first time plugin developers

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2023-02-21 22:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=63535) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=63535) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=63535) it.</sub>

2023-03-23 17:18 UTC, Eve832 requested changes
Thanks Kate!

2023-03-23 17:18 UTC, Eve832 commented on docs/sources/tutorials/build-a-data-source-plugin/index.md
> +Note there is a separate guide for [creating backend plugins](/docs/grafana/latest/tutorials/build-a-data-source-backend-plugin)
```suggestion
To learn how to create a backend data source plugin, see [Build a data source backend plugin](/docs/grafana/latest/tutorials/build-a-data-source-backend-plugin)
```

2023-04-25 09:30 UTC, osg-grafana commented on docs/sources/tutorials/build-a-data-source-plugin/index.md
> +To learn how to create a backend data source plugin, see [Build a data source backend plugin](/docs/grafana/latest/tutorials/build-a-data-source-backend-plugin)
```suggestion
To learn how to create a backend data source plugin, see [Build a data source backend plugin](/docs/grafana/latest/tutorials/build-a-data-source-backend-plugin).
```

2023-04-25 09:34 UTC, osg-grafana commented
@Eve832, as triager this week I added this to the team project and put into In review.

2023-04-25 13:39 UTC, Eve832 approved these changes

2023-04-25 18:19 UTC, merged