LDAP: Allow setting minimum TLS version and accepted ciphers
grafana/grafana pull request #63646
Opened 2023-02-23 14:32 UTC by Jguer

- Update LDAP library and use go module path
- Fixes https://github.com/grafana/grafana/issues/58908

---

Note to reviewers:

I tried to ensure it fails open and sets the defaults of the crypto lib if no specifics are mentioned

2023-02-23 16:51 UTC, chri2547 commented on conf/ldap.toml
> +# full list of supported ciphers and TLS versions: https://go.dev/src/crypto/tls/cipher_suites.go
```suggestion
# For a complete list of supported ciphers and TLS versions, refer to: https://go.dev/src/crypto/tls/cipher_suites.go
```

2023-02-23 16:53 UTC, chri2547 commented on conf/ldap.toml
> +# Minimum TLS version allowed (default if empty, Accepted values are TLS1.1, TLS1.2, TLS1.3)
```suggestion
# This is the minimum TLS version allowed. By default, this setting is empty. Accepted values are: TLS1.1, TLS1.2, TLS1.3.
```

2023-02-23 17:37 UTC, chri2547 commented on conf/ldap.toml
> +# Accepted TLS Ciphers (default if empty, ex value: ["TLS_AES_256_GCM_SHA384"])
```suggestion
# The value of an accepted TLS cipher. By default, this value is empty. Example value: ["TLS_AES_256_GCM_SHA384"])
```

2023-02-23 17:38 UTC, chri2547 requested changes
Added some suggestions, please review to ensure I haven't changed the technical meaning of the content. Please re-request a review so I can approve. Thank you for the contribution.

2023-02-24 10:20 UTC, kalleep commented on pkg/services/ldap/settings.go
> +	return ids, fmt.Errorf("unknown ciphers: %v", missing)
Otherwise we would always log an error when tsl ciphers has been configured, even if they are all valid

2023-02-24 11:52 UTC, Jguer commented on pkg/services/ldap/settings.go
> +	return ids, fmt.Errorf("unknown ciphers: %v", missing)
distraction, thanks

2023-02-24 13:53 UTC, alexanderzobnin approved these changes

2023-02-24 18:55 UTC, chri2547 approved these changes
LGTM! Thank you!!

2023-02-28 11:12 UTC, mgyongyosi approved these changes
LGTM!

### Test setup
OpenLDAP cipher suites: `SECURE256:-VERS-DTLS-ALL:-VERS-TLS-ALL:-SHA1:-AES-256-GCM:-AES-256-CCM:-AES-256-CBC:+VERS-TLS1.2` -> means only `CHACHA20-POLY1305` cipher is supported

### Results
`tls_min_version` works correctly.

`tls_ciphers` tests:
```toml
tls_ciphers = ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_AES_256_GCM_SHA384"] # Works as expected -> User CANNOT login with LDAP
tls_ciphers = ["TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"] # Works as expected -> User CAN login with LDAP
tls_ciphers = [] # Works as expected -> User CAN login with LDAP
```

2023-02-28 11:13 UTC, merged