Docs: sync plugin JSON info in the different files (first part)
grafana/grafana pull request #63750
Opened 2023-02-24 16:48 UTC by andresmgot

**What is this feature?**

My goal here is:

 - Check plugin.json docs and see if the descriptions are still accurate or if they need more detail.
 - Check that plugindef.cue and plugin.schema.json are in sync. Having the same description and options, in the same order. This will help with eventual automation.

So far, I have only reviewed the mandatory fields and `$schema` but rather than keep adding things to a big PR, it's better to review these little by little.

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Ref #63614

**Special notes for your reviewer**:

2023-03-03 13:48 UTC, wbrowne commented on docs/sources/developers/plugins/metadata.md
> +| `$schema`            | string                        | No       | Schema definition for the plugin.json file. Used to verify the validy it.
```suggestion
| `$schema`            | string                        | No       | Schema definition for the plugin.json file. Used primarily for schema validation.                                                                                                                                                                                                                                                                                                                           |
```

2023-03-03 14:56 UTC, wbrowne approved these changes

2023-03-03 19:10 UTC, josmperez commented on docs/sources/developers/plugins/metadata.md
> +| `id`                 | string                        | **Yes**  | Unique name of the plugin. If the plugin is published on grafana.com, then the plugin id should follow the Grafana naming conventio
change id to ID or `id`

2023-03-03 19:16 UTC, josmperez commented on pkg/plugins/plugindef/plugindef.cue
> +				// Metadata about the plugin.
Style nit: In blocks below, periods not needed at line ends unless they close a complete sentence.

2023-03-03 19:17 UTC, josmperez requested changes
Style suggestions.

2023-03-06 17:16 UTC, josmperez approved these changes

2023-03-07 08:14 UTC, merged