Add user_agent config in dataproxy
grafana/grafana pull request #63769
Opened 2023-02-25 00:23 UTC by zhichli

Fix #63767

2023-02-27 14:34 UTC, chri2547 commented on docs/sources/setup-grafana/configure-grafana/_index.md
> +Sets a custom value for `User-Agent` header for outgoing data proxy requests. If empty, default value will be `Grafana/<BuildVersion>` (e.g. `Grafana/9.0.0`).
```suggestion
Sets a custom value for the `User-Agent` header for outgoing data proxy requests. If empty, the default value is `Grafana/<BuildVersion>` (for example `Grafana/9.0.0`).
```

2023-02-27 14:35 UTC, chri2547 reviewed
Added a suggestion for you. Thank you for the contribution!

2023-02-27 19:18 UTC, zhichli commented on docs/sources/setup-grafana/configure-grafana/_index.md
> +Sets a custom value for `User-Agent` header for outgoing data proxy requests. If empty, default value will be `Grafana/<BuildVersion>` (e.g. `Grafana/9.0.0`).
Thanks for the suggestion! Addressed.

2023-02-28 06:25 UTC, marefr requested changes
Thanks. Looks great. A test failure needs to be fixed

2023-02-28 06:25 UTC, marefr commented on pkg/tsdb/azuremonitor/resourcegraph/azure-resource-graph-datasource.go
> -	req.Header.Set("User-Agent", fmt.Sprintf("Grafana/%s", setting.BuildVersion))
You seem to have a failed test due to this change

2023-02-28 13:08 UTC, marefr approved these changes
LGTM

2023-02-28 13:10 UTC, merged

2023-02-28 13:10 UTC, marefr commented
Thank you for contributing to Grafana