Add documentation for private data source connect using kubernetes
grafana/grafana pull request #63863
Opened 2023-02-28 13:19 UTC by chaudyg

Add kubernetes deployment documentation for private data source connect, available in Cloud Pro and Advanced in closed preview. 

**What is this feature?**

Add kubernetes deployment documentation for private data source connect, available in Cloud Pro and Advanced in closed preview. These docs should be public, but not indexed or searchable. 

**Who is this feature for?**

Closed preview customers, who will all be given a link to the docs.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

I think this is a reasonable place to put these docs, but this feature is only available in Grafana Cloud, so I wonder if this doc should go into Grafana Cloud documentation...

2023-02-28 14:38 UTC, chri2547 commented
@chaudyg - yes, these docs belong in the Cloud repo. Thank you for asking about that.

2023-02-28 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=63863) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=63863) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mjseaman<br/>:x: chaudyg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=63863) it.</sub>

2023-02-28 16:16 UTC, mjseaman commented
Added k8s to the list of options and made it option #1. Otherwise LGTM!

2023-02-28 16:42 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +   There are three options for connecting: using Kubernetes, SSH, or the PDC Agent Docker image.
```suggestion
   There are three connecting options: Kubernetes, SSH, or the PDC Agent Docker image.
```

2023-02-28 16:43 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +     Create a kubernetes secret with the private key, and the certificate and known_hosts file Grafana Labs provided to you.
```suggestion
     Create a Kubernetes secret with the private key and the certificate and known_hosts file Grafana Labs provided.
```

2023-02-28 16:43 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +     Generate a kubernetes deployment to deploy the agent.
```suggestion
     Generate a Kubernetes deployment to deploy the agent.
```

2023-02-28 16:44 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +     The environment variables used in the previous commands are as follows:
```suggestion
     The following list contains the environment variables used in the previous commands:
```

2023-02-28 16:45 UTC, chri2547 commented on docs/sources/setup-grafana/configure-security/configure-private-datasource-connect/index.md
> +     - ${NAMESPACE}: The kubernetes namespace for the pdc-agent.
```suggestion
     - ${NAMESPACE}: The Kubernetes namespace for the pdc-agent.
```

2023-02-28 16:45 UTC, chri2547 requested changes, later dismissed
Added suggestions, thank you!

2023-03-01 08:41 UTC, dafydd-t approved these changes
LGTM!

2023-03-01 09:27 UTC, merged