Packaging: Make database dependencies optional on systemd
grafana/grafana pull request #63905
Opened 2023-02-28 22:26 UTC by rgnvldr

DB should not be a requirement as it can be externally hosted. Per https://www.freedesktop.org/software/systemd/man/systemd.unit.html making it be an optional dependency.

2023-03-02 06:10 UTC, DanCech approved these changes
lgtm

2023-03-03 11:40 UTC, MichaIng commented
There is not dependency currently, why do you think it would be? What is done here is a bad idea. It means all database services are forced to start when installed, even if not used by Grafana. This breaks possible admin purposes.

2023-03-03 11:40 UTC, MichaIng requested changes
There is no dependency currently, why do you think it would be? What is done here is a bad idea. It means all database services are forced to start when installed, even if disabled and not used by Grafana. This breaks possible admin purposes.

2023-03-07 03:37 UTC, DanCech commented
I'm not a systemd expert, but after reading through the documentation I tend to agree with you @MichaIng , initially it seemed as though `After=` implied a dependency but re-reading I see what it just controls startup order when multiple services are started within the same systemd transaction.  As you point out, adding `Wants=` will force the system to start the named services when grafana is started if they are installed, which doesn't seem to match the intent of this PR per the description.

@rgnvldr can you elaborate on the rationale behind adding `Wants=`? It seems like the intent was to have a weaker dependency relationship while the actual effect will be to create a stronger one.

2023-03-07 12:12 UTC, MichaIng commented
Exactly, `Before=`/`After=` do not imply any dependency, ordering only. `Wants=`/`Requires=`/`Requisite=` add dependencies, but no ordering.

2023-03-08 17:45 UTC, DanCech requested changes
Thanks @MichaIng I'm going to close this for now, @rgnvldr feel free to re-open if needed.

2023-03-08 17:45 UTC, closed without merging