[InProgress]: Added Pagerduty basic alerting
grafana/grafana pull request #6424
Opened 2016-10-29 05:24 UTC by utkarshcmu

Partially resolves #6291 

Screenshot:

<img width="743" alt="screen shot 2016-10-28 at 10 03 11 pm" src="https://cloud.githubusercontent.com/assets/1019609/19827387/1a026aaa-9d5d-11e6-85e6-9c6c1037f6ec.png">

2016-11-01 07:24 UTC, utkarshcmu commented
PR ready for review/merge!

2016-11-01 09:39 UTC, bergquist commented on pkg/metrics/metrics.go
> -	M_Instance_Start                     Counter
Seems like a tabs vs space issue. What editor are you using? Any chance you can find a plugin for editorconfig? https://github.com/grafana/grafana/blob/master/.editorconfig http://editorconfig.org/

2016-11-01 09:48 UTC, bergquist commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
I've never integrated with pagerduty. But it shouldn't it send notifications for ok as well?

2016-11-01 09:52 UTC, utkarshcmu commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
Pagerduty can handle alert acknowledgement and resolution on its own. Alerts just need to be triggered from an external source.

2016-11-01 09:55 UTC, bergquist commented on pkg/metrics/metrics.go
> -	M_Instance_Start                     Counter
ofc! Sorry about that :)

2016-11-01 10:02 UTC, bergquist commented
This might take some time to review since I have to setup a pagerduty account for testing.

2016-11-01 10:03 UTC, utkarshcmu commented on pkg/metrics/metrics.go
> -	M_Instance_Start                     Counter
No worries. :)

2016-11-01 15:05 UTC, utkarshcmu commented
Blocked by #6420

2016-11-01 15:49 UTC, arodland commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
@utkarshcmu sending OK is better if possible. There's a reason why they provide it in the API. "Your monitoring tools should send PagerDuty a `resolve` event when the problem that caused the original trigger is fixed."

2016-11-01 17:32 UTC, bergquist commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
Perhaps it should be optional. I guess some organisation will require a human to set it as resolved.

2016-11-01 22:51 UTC, utkarshcmu commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
I will keep it optional in the config

2016-11-02 20:52 UTC, utkarshcmu commented on pkg/services/alerting/notifiers/pagerduty.go
> +	alertingStates := make([]m.AlertStateType, 0)
@arodland Storing event Id of the incident will take some more effort in PagerDuty support. Will add the feature of resolving in the next version of the support. For now when we merge this PR, Grafana will be able to Trigger an incident in PagerDuty and from there on PagerDuty can take care of the incident.

2016-11-02 22:18 UTC, utkarshcmu commented
Ready for Review/Merge.

2016-11-03 06:33 UTC, utkarshcmu commented
Blocked on #6444 now!

2016-11-04 21:14 UTC, sofixa commented
Just a feature request, could you make the PagerDuty url optional for the people running PagerDuty-compatible software(like OpenDuty)?

2016-11-07 07:38 UTC, utkarshcmu commented
@sofixa Integration Key field is mandatory. There is no url field for PagerDuty settings.

2016-11-07 07:55 UTC, sofixa commented
@utkarshcmu ,  i meant, could you add it as a field/parameter, so that people who use compatible software can use your alerter out-of the box?

2016-11-07 14:19 UTC, bergquist commented
Since https://github.com/grafana/grafana/pull/6489 have been merged we dont have a state for execution_alerts anymore. So please remove that filter. I will review this once that is fixed so hopefully this can be merge before we release 4.0 beta.

2016-11-07 14:19 UTC, bergquist requested changes
Since #6489 have been merged we dont have a state for execution_alerts anymore. So please remove that filter. I will review this once that is fixed so hopefully this can be merge before we release 4.0 beta.

2016-11-07 15:29 UTC, utkarshcmu commented
@bergquist Great work on #6489 , I have removed the ExecError state. Please review/merge. Thanks!

2016-11-08 06:17 UTC, bergquist commented
Id like an option for auto resolving the pagerduty status when going back to ok. I can understand organizations that don't want to auto resolve alerts but we some do. Including us internally :)

2016-11-08 06:39 UTC, utkarshcmu commented
@bergquist For auto resolving the pagerduty incident , I will need to store the eventId in the db. Let me see where I can do that in the db.

2016-11-08 06:45 UTC, bergquist commented
@utkarshcmu oh. Lets postpone that for now.

2016-11-08 06:51 UTC, merged

2016-11-08 06:51 UTC, bergquist commented
Great work!

2016-11-08 07:56 UTC, utkarshcmu commented
@sofixa Created an issue to track support for OpenDuty - #6504

2017-03-30 17:39 UTC, playqdrew commented
@utkarshcmu  -- Thanks for the work on this! Very nice. 

I am having an issue when alerts are sent to PagerDuty versus Slack. Some information seems to be missing. Here is an example in Slack:

![image](https://cloud.githubusercontent.com/assets/19480476/24517945/056259de-1535-11e7-998d-d8145acdd98f.png)

Versus what shows for the same alerts in PagerDuty:

{
  "client": "Grafana",
  "client_url": "https://xxx/dashboard/db/prd-tg-overview?fullscreen&edit&tab=alert&panelId=3&orgId=1",
  "description": "PRD TG-Vital Request Timings - ",
  "event_type": "trigger",
  "incident_key": "alertId-16",
  "service_key": "xxx"
}

Notice how the whole description about how this was an influxdb at capacity error is missing from PagerDuty?