fix: allow `{}` type in `VariableWithOptions.current `
grafana/grafana pull request #64358
Opened 2023-03-07 22:08 UTC by simPod

**What is this feature?**

Type fix

**Why do we need this feature?**

I've created a variable like this

<img width="560" alt="image" src="https://user-images.githubusercontent.com/327717/223564428-2e1bf4e5-7a8f-47b7-b8ee-f42243ff0247.png">

And then when I `console.log` it, we can see that `current` property is `{}`

<img width="576" alt="image" src="https://user-images.githubusercontent.com/327717/223564604-0156f592-4b9c-4b08-8dcc-364bad9b7c7e.png">

**Who is this feature for?**

Type consumers

2023-04-07 11:57 UTC, simPod commented
Meh

2023-05-08 07:07 UTC, simPod commented
.

2023-05-29 07:15 UTC, dprokop commented
@ivanortegaalba you've been working on schematizing variable types, how did you solve it in that PR?

2023-05-29 08:58 UTC, ivanortegaalba commented
@dprokop This case was not contemplated in [the PR](https://github.com/grafana/grafana/pull/62142/files#diff-abdfd6a9318ae27ef245c1da7557b327ca1e4e6a10ee220b76e162c6865eeb28R255).

Trying to reproduce when current is created as an empty object. If this is a valid default value, we should add it in the type.

2023-05-29 09:08 UTC, ivanortegaalba commented
I doubled checked, and actually `current: {}` is the default value for any variable with options it is created for a dashboard. 

This is the default variable created when custom:
```json
  "templating": {
    "list": [
      {
        "current": {},
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "query0",
        "options": [],
        "query": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
```

2023-05-29 09:18 UTC, ivanortegaalba requested changes
Hi @simPod, thank you so much for your contribution.

The type change is valid. The default value for a `VariableWithOptions` is an empty object when no options are declared.

However, we should adapt the runtime code to avoid type errors, since the runtime code is assuming it will always be a `VariableOption`.

Can you please run `yarn typecheck` locally and fix the type errors? Thank you!

2023-06-16 12:30 UTC, ivanortegaalba approved these changes
Thank you @simPod for applying the suggested changes and sorry for the delay.

All the changes are good to go. So LGTM.

2023-06-16 12:31 UTC, merged