Explore: Align multiple log volumes
grafana/grafana pull request #64356
Opened 2023-03-07 21:03 UTC by ifrost

This PR aligns log volumes histogram to use the same values on Y and X axes:

| before | after | 
|----|----|
| <img width="1524" alt="Screenshot 2023-03-07 at 22 00 10" src="https://user-images.githubusercontent.com/745532/223551687-f6ff5206-2013-4ada-8d7f-e38ef5237626.png"> | <img width="1527" alt="Screenshot 2023-03-07 at 21 58 26" src="https://user-images.githubusercontent.com/745532/223551763-8054e49c-f74f-4eee-a4ed-02beda4d801d.png"> |

There are also a few more changes included:
* supplementaryQueries.ts util function was unified so we don't need extra `ifs`
* helper functions for log volume where moved from `grafana-data/types` to `features/logs/utils`

2023-03-08 14:36 UTC, ifrost commented
> Possible breaking changes

Helper functions for log volume were moved from `grafana-data/types` to `features/logs/utils`. These were recently added in https://github.com/grafana/grafana/pull/63036, not released, hence they can be ignored as breaking changes.

2023-03-20 12:27 UTC, ivanahuckova requested changes
Left some comments bellow. I also discovered new issue this PR creates - the zooming in logs volume does not work anymore. 

https://user-images.githubusercontent.com/30407135/226338635-e05e4ade-b20e-43c9-b01c-912c554ebed1.mov

2023-03-21 09:20 UTC, Elfo404 approved these changes
seems to work as expected, i agree with ivana that naming may be a bit better, so if you could check that it'd be great, otherwise lgtm

2023-03-21 09:20 UTC, Elfo404 commented on public/app/features/explore/Graph/ExploreGraph.tsx
> +  maximum?: number;
+1

2023-03-21 14:57 UTC, ifrost commented on public/app/features/explore/Graph/ExploreGraph.tsx
> +  maximum?: number;
Updated in f41a5f00d652737b20de5dc9e21b1e6fdafbc50a

2023-03-21 14:57 UTC, ifrost commented on public/app/features/logs/utils.ts
> +    if (dataFrameRange) {
This was all wrong 😱  Updated in c0fc6f10ee1d4eebda917a84977fdf4a10101bf7

2023-03-21 18:34 UTC, gelicia approved these changes
I think you need to add `reuseWhenZoomingIn` here https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/supplementaryQueries.ts#L94 

but other than that, it looks good! Great work!

Tested with gdev-loki and test data on the logs scenario. Time range "last 5 minutes" shows logs volume data for both, with the same x and y scales.

2023-03-22 10:43 UTC, ifrost commented
There's also a change in the behavior of limited log volume. With this change in place, it will always be displayed with the selected range, not narrowed down to the results even if there's only one limited log volume visible (with and without mixed DS). 

@grafana/observability-logs I feel this actually makes everything more predictable, but do you think it's okay to make this change? Or should we have a special check - if there's only a limited log volume => change the visible range of the log volume to start with the first logline?

2023-03-28 07:58 UTC, ifrost commented
Converting back to draft as we want https://github.com/grafana/grafana/pull/65392 to be merged first.

2023-04-04 09:17 UTC, ifrost commented
Reopening for review (since https://github.com/grafana/grafana/pull/65392 got merged).

cc @grafana/observability-logs

2023-04-06 14:02 UTC, ivanahuckova reviewed
1 small nit UX issue I noticed - when you zoom in and `FullRange` logs volume does not receive data, the order of panels switched. Is there a way we can guarantee order of the volumes when zooming in?
 
https://user-images.githubusercontent.com/30407135/230400817-9a3c64b5-cf60-4aef-ad8f-aef20cfe5ba2.mov

2023-04-07 07:31 UTC, ifrost commented
> 1 small nit UX issue I noticed - when you zoom in and `FullRange` logs volume does not receive data, the order of panels switched. Is there a way we can guarantee order of the volumes when zooming in?

Added a50a9d984217374eae91a90815045690da836654 to sort volumes by data source name

2023-04-07 07:43 UTC, ifrost commented on public/app/features/explore/utils/supplementaryQueries.ts
> +              reuseWhenZoomingIn: false,
Good idea! Changed in e8abd9495dc11fa02890cccf0b453cd3300cf93b

2023-04-11 07:51 UTC, ivanahuckova approved these changes
LGTM!

2023-04-11 08:05 UTC, merged