Prometheus: Feedback link for metric encyclopedia
grafana/grafana pull request #64576
Opened 2023-03-09 23:55 UTC by bohandley

This adds a feedback link for the metric encyclopedia. We will be asking UX, SEs, SREs and community members to review it under the feature flag.

2023-03-10 21:04 UTC, gtk-grafana requested changes
Some weirdness with the filters I mentioned on slack, everything else is working good.

2023-03-10 23:19 UTC, bohandley commented on public/app/plugins/datasource/prometheus/querybuilder/components/MetricEncyclopediaModal.tsx
> +        if ((keepMetric || !fuzzySearchQuery) && letterSearch && !skipLetterSearch) {
@gtk-grafana I need to come up with a set of rules for the filtering. That will make it easier to keep track of the order of things. For now, it's 1) fuzzy search, 2) alphabet, 3) filter types. I also need to consider the metrics that don't have metadata, they are not filtered out by type unless the switch is on to filter them.

2023-03-10 23:21 UTC, bohandley commented
> Some weirdness with the filters I mentioned on slack, everything else is working good.

Made the change!

2023-03-13 04:54 UTC, leeoniya commented
i'm getting 472 results for "prom" and 1067 results for "prome"? :thinking: 

![image](https://user-images.githubusercontent.com/43234/224611107-d496d04b-e114-4380-9637-cb1d6a9efc28.png)
![image](https://user-images.githubusercontent.com/43234/224611243-fa56ed66-47a1-455c-abb7-0d8b3e2160fc.png)

2023-03-13 16:40 UTC, bohandley commented
> i'm getting 472 results for "prom" and 1067 results for "prome"? 🤔
> 
> ![image](https://user-images.githubusercontent.com/43234/224611107-d496d04b-e114-4380-9637-cb1d6a9efc28.png) ![image](https://user-images.githubusercontent.com/43234/224611243-fa56ed66-47a1-455c-abb7-0d8b3e2160fc.png)

@leeoniya I believe this is because uFuzzy sees prome as a mispelling of process and so includes those results as well. My understanding of uFuzzy is that it returns results for close spellings

"prom" -> prometheus

but         
                 -> prometheus
"prome" 
                 -> process

2023-03-13 17:33 UTC, bohandley commented
Filters are still broken. I need to fix those.

2023-03-13 20:17 UTC, bohandley commented
> ah, that makes sense, we just need to do better with sorting by relevance.
> 
> `uf.filter(haystack, query);` does no sorting, we gotta switch to the `uf.search()` API.

So we can sort results based on the uFuzzy search api. Currently results are sorted alphabetically. I can add an item to the epic to add sorting rules
1) alphabetically
2) uFuzzy sort relevance

2023-03-14 20:20 UTC, gtk-grafana approved these changes
Now the metrics free text field and the type filters interact as I expect, but I'm still seeing some confusing behavior with the filters.

I assume that within the type filter, that each category is additive, but when I select all categories, I do not get the same value as no categories. Maybe there are some values without any category? I think it's that there are a bunch of values without metadata and I see that you added some UI for that. 

I propose we remove the toggle for excluding metadata, and instead add another category of "no metadata" or "uncategorized" or something within the filter element, and make sure that they don't show up when the other filters are displayed, otherwise I see all the result numbers that aren't adding up and perceive that the UI is broken, or hiding something from me.

That said, this issue already exists in the main branch, so I won't let this block merge, as this brings much needed improvements to the feature!

2023-03-14 20:33 UTC, bohandley commented
> Now the metrics free text field and the type filters interact as I expect, but I'm still seeing some confusing behavior with the filters.
> 
> I assume that within the type filter, that each category is additive, but when I select all categories, I do not get the same value as no categories. Maybe there are some values without any category? I think it's that there are a bunch of values without metadata and I see that you added some UI for that.
> 
> I propose we remove the toggle for excluding metadata, and instead add another category of "no metadata" or "uncategorized" or something within the filter element, and make sure that they don't show up when the other filters are displayed, otherwise I see all the result numbers that aren't adding up and perceive that the UI is broken, or hiding something from me.
> 
> That said, this issue already exists in the main branch, so I won't let this block merge, as this brings much needed improvements to the feature!

There are a bunch of metrics with no type or description at all! I will look further into this behavior though. I am always including metrics with no type because I believe an admin could have created a metric without a type, an SRE could know they need a counter, they look it up with the counter type selected, and because it was never given metadata it won't show up. I can see this as being weird though.

I'll look into the results adding up too!

Thank you @gtk-grafana, your reviews are excellent! 🎉

2023-03-14 20:36 UTC, merged