Docs: Add documentation on how to debug backend plugins
grafana/grafana pull request #64814
Opened 2023-03-15 14:11 UTC by xnyo

**What is this feature?**

Documentation for the changes made by https://github.com/grafana/grafana-plugin-sdk-go/pull/621.

Adds instructions on how to debug backend plugins from Visual Studio Code, GoLand or other IDEs.

**Why do we need this feature?**

To make users aware of the new backend debug mode added to the sdk

**Who is this feature for?**

Backend plugin developers

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer**:

2023-03-17 08:38 UTC, andresmgot reviewed
Good content! I have some minor comments.

2023-03-17 08:38 UTC, andresmgot commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Make sure you are using the latest version of `grafana-plugin-sdk-go`
maybe worth mentioning first to  `cd ` in the plugin folder

2023-03-17 08:38 UTC, andresmgot commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +(if you re-run the configuration, the plugin will be automatically reloaded in Grafana).
```suggestion
> Note: If you re-run the configuration, the plugin will be automatically reloaded in Grafana).
```

2023-03-17 08:38 UTC, andresmgot commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Start Grafana
```suggestion
1. Start Grafana, if it's not already running
```

2023-03-17 08:38 UTC, andresmgot commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +- If the backend plugin does not serve requests after turning off debug mode, you can force reset the standalone mode by deleting the files `standalone.txt` and `pid.txt` alongside the executable, th
I think this is `dist/standalone.txt` and `dist/pid.txt`?

2023-03-17 08:39 UTC, mckn approved these changes
Added one small nit but this looks great!

![](https://media.giphy.com/media/T9SzftdKiHZTzmfluU/giphy.gif)

2023-03-17 08:39 UTC, mckn commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +You can run a backend plugin and attach a debugger to it directly from your IDE. This allows you to set breakpoints and debug your backend plugin directly from your IDE of choice.
```suggestion
You can run a backend plugin and attach a debugger to it, which allows you to set breakpoints and debug your backend plugin directly from your IDE of choice.
```
Small nit to make it less repetitive

2023-03-17 09:17 UTC, xnyo commented
Thanks for the feedback :smile:  I have addressed the changes

2023-03-17 10:31 UTC, andresmgot approved these changes
LGTM! but maybe wait for a review from @josmperez to get docs team thoughts on this

2023-03-17 17:57 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +> The following method only works with a local Grafana instance and does not work with Docker for the time being.
```suggestion
> Note: The following method only works with a local Grafana instance and currently doesn't work with Docker.
```

2023-03-17 17:59 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. `cd` into your plugin's folder
```suggestion
1. Go to your plugin's folder.
```

2023-03-17 17:59 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +   - If not, you can update it to the latest version with:
```suggestion
   - If not, update it to the latest version:
```

2023-03-17 18:01 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +Now that your plugin is ready to run, follow the instructions bellow for your IDE of choice
```suggestion
Now that your plugin is ready to run, follow the instructions bellow for your IDE of choice.
```

2023-03-17 18:02 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Place the following file inside `.vscode/launch.json`, in your plugin's folder, if it's not already present:
```suggestion
1.  If it's not already present, go to your plugin's folder and place the following file inside `.vscode/launch.json`:
```

2023-03-17 18:02 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Press `F5` to run your plugin in debug mode
```suggestion
1. Press `F5` to run your plugin in debug mode.
```

2023-03-17 18:03 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Start Grafana, if it's not already running
```suggestion
1. Start Grafana, if it's not already running.
```

2023-03-17 18:03 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +> If you re-run the configuration, the plugin will be automatically reloaded in Grafana.
```suggestion
> If you re-run the configuration, Grafana will automatically reload the plugin.
```

2023-03-17 18:04 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Run the config (with or without the debugger)
```suggestion
1. Run the config (with or without the debugger).
```

2023-03-17 18:04 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Start Grafana, if it's not already running
```suggestion
1. Start Grafana, if it's not already running.
```

2023-03-17 18:04 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +> If you re-run the configuration, the plugin will be automatically reloaded in Grafana.
```suggestion
> If you re-run the configuration, Grafana will automatically reload the plugin.
```

2023-03-17 18:05 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Build the executable with debug flags
```suggestion
1. Build the executable with debug flags.
```

2023-03-17 18:05 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Run the plugin's executable (inside `dist`) with `-standalone -debug` flags
```suggestion
1. Run the plugin's executable (inside `dist`) with `-standalone -debug` flags.
```

2023-03-17 18:05 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +1. Attach a debugger to the process
```suggestion
1. Attach a debugger to the process.
```

2023-03-17 18:06 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +> If you re-run the plugin executable, it will be automatically reloaded in Grafana.
```suggestion
> If you re-run the plugin executable, Grafana will automatically reload it. 
```

2023-03-17 18:06 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +- All logs will be printed in the plugin's stdout rather than in Grafana logs
```suggestion
- All logs are printed in the plugin's `stdout` rather than in Grafana logs.
```

2023-03-17 18:07 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +- If the backend plugin does not serve requests after turning off debug mode, you can force reset the standalone mode by deleting the files `dist/standalone.txt` and `dist/pid.txt` alongside the exec
```suggestion
- If the backend plugin doesn't serve requests after turning off debug mode, you can force reset the standalone mode. To do so, delete the files `dist/standalone.txt` and `dist/pid.txt` alongside the executable file, and then restart Grafana.
```

2023-03-17 18:08 UTC, josmperez commented on docs/sources/developers/plugins/development-with-local-grafana.md
> +- We currently do not support debugging backend plugins running inside Docker
```suggestion
- We currently do not support debugging backend plugins running inside Docker.
```

2023-03-17 18:08 UTC, josmperez requested changes
Edits for Grafana style guidelines.

2023-03-20 10:38 UTC, xnyo commented
Thanks for the review @josmperez ! I have addressed the changes, could you please check again? Thanks :smile:

2023-03-20 22:00 UTC, josmperez approved these changes

2023-03-21 09:03 UTC, merged