[Docs] - Add Warning about Version Downgrade and Alerting to Grafana …
grafana/grafana pull request #64896
Opened 2023-03-16 12:26 UTC by SeamusGrafana

…v9.4 Upgrade Instructions

Add Warning about Version Downgrade and Alerting to Grafana v9.4 Upgrade Instructions

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer**:

2023-03-16 12:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=64896) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=64896) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=64896) it.</sub>

2023-03-20 13:51 UTC, chri2547 commented on docs/sources/upgrade-guide/upgrade-v9.4/index.md
> +> Note: The upgrade to Grafana v9.4 makes changes to the Grafana Database for Grafana Alerting that are backwards incompatible, as such once upgraded to v9.4 of Grafana, your Grafana instance should
```suggestion
The upgrade to Grafana v9.4 includes changes to the Grafana database for Grafana alerting that are not backward compatible. As a result, when you upgrade to Grafana v9.4, do not downgrade your Grafana instance to an earlier version. Doing so might cause issues with managing your Grafana alerts.
```

2023-03-20 13:51 UTC, chri2547 commented on docs/sources/upgrade-guide/upgrade-v9.4/index.md
>  There are no additional upgrade steps to complete for this version of Grafana.
```suggestion
```

2023-03-20 13:53 UTC, chri2547 requested changes
Added suggestions. This is a really important piece of information and perfect for the technical notes section of the upgrade guide! Thank you very much for your contribution. After you've made the changes, please ping me for re-review.

2023-03-20 13:55 UTC, chri2547 approved these changes
LGTM, thank you!

2023-03-20 13:55 UTC, SeamusGrafana commented
> Added suggestions. This is a really important piece of information and perfect for the technical notes section of the upgrade guide! Thank you very much for your contribution. After you've made the changes, please ping me for re-review.

Hi @chri2547 

Thanks for the review, changes accepted and committed.

2023-03-20 15:12 UTC, chri2547 commented
> > Added suggestions. This is a really important piece of information and perfect for the technical notes section of the upgrade guide! Thank you very much for your contribution. After you've made the changes, please ping me for re-review.
> 
> Hi @chri2547
> 
> Thanks for the review, changes accepted and committed.

@SeamusGrafana , looks like you need to run prettier. Do you know how to do that? Then we can mergel

2023-03-20 16:05 UTC, merged