[feat] Add scroll handlers to the Select component
grafana/grafana pull request #65069
Opened 2023-03-20 17:08 UTC by 2Steaks

### What is this feature?

Adds support for menu scroll events

https://user-images.githubusercontent.com/4395376/226413792-87f57488-c6cd-4894-9c9a-77928d26b45a.mov

### Why do we need this feature?

The k6 plugin uses paginated data to populate a select dropdown menu with test comparison options, we would like to progressively load in additional options as the user scrolls the menu.

https://user-images.githubusercontent.com/4395376/226414795-7ba83d7d-3f1d-4071-b074-e6649f772446.mov

2023-03-20 17:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=65069) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=65069) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=65069) it.</sub>

2023-03-21 10:24 UTC, tskarhed requested changes
The Select component has historically been a bit messy, so I want someone else to also give some feedback on this.

2023-03-21 10:24 UTC, tskarhed commented on packages/grafana-ui/src/components/Select/SelectBase.tsx
> +    captureMenuScroll,
```suggestion
    captureMenuScroll: onMenuScrollToBottom || onMenuScrollToTop,
```
Maybe do this, so we don't have to expose the extra `captureMenuScroll` prop. If you have any reason for not doing this, please do tell! :slightly_smiling_face:

2023-03-21 10:24 UTC, tskarhed commented on packages/grafana-ui/src/components/Select/types.ts
> +  onMenuScrollToTop?: (event: WheelEvent | TouchEvent) => void;
I know a lot of props aren't documented for this component, but could you maybe add some docstrings to these props?

2023-03-21 10:24 UTC, tskarhed commented on packages/grafana-ui/src/components/Select/types.ts
> +  captureMenuScroll?: boolean;
```suggestion
```
With the changes above

2023-03-21 10:24 UTC, tskarhed commented on packages/grafana-ui/src/components/Select/SelectBase.tsx
> +  captureMenuScroll = false,
```suggestion
```

2023-05-05 14:32 UTC, tskarhed approved these changes
Sorry for not getting to this sooner! LGTM! :+1:

2023-06-09 09:38 UTC, tskarhed commented
@2Steaks Do you want to go ahead and merge this?

2023-06-09 14:47 UTC, 2Steaks commented
> @2Steaks Do you want to go ahead and merge this?

@tskarhed it seems I am not an authorised user so I can't merge it.

2023-06-12 12:52 UTC, merged