Alerting: Fix DashboardUID typo in json provisioning api
grafana/grafana pull request #65143
Opened 2023-03-21 23:31 UTC by JacobsonMT

The json tag for DashboardUID was incorrectly set to dasboardUid in the provisioning api. This change fixes the typo while keeping backwards compatibility.

Also adds alerting-squad as CODEOWNER for services/provisioning/alerting.

2023-03-22 08:04 UTC, JohnnyQQQQ commented on pkg/services/provisioning/alerting/file/rules_types.go
> +// UnmarshalJSON supports the grandfathered typo dashboardUid. This should be removed in V2.
Can we add a TODO here, so that we remove it as a breaking change eventually?

2023-03-27 21:48 UTC, alexweav commented on pkg/services/provisioning/alerting/file/rules_types.go
> +	}
```suggestion
	if rule.DashboardUID.Value() == "" {
		rule.DashboardUID = t.DasboardUID
	}
```
logically equivalent

2023-03-27 21:48 UTC, alexweav commented on pkg/services/provisioning/alerting/file/rules_types.go
> +	}
```suggestion
	if rule.DashboardUID.Value() == "" {
		rule.DashboardUID = t.DasboardUID
	}
```

2023-03-27 21:48 UTC, alexweav commented on pkg/services/provisioning/alerting/file/rules_types.go
> +// support in YAML as well since we use yaml.UnmarshalYAML when parsing. This should be removed in V2.
I might be missing something - is there somewhere we call UnmarshalYAML outside of reading a yaml file?

2023-03-27 21:48 UTC, alexweav commented
Nice catch!

2023-03-31 16:22 UTC, yuri-tceretian approved these changes
LGTM

2023-06-08 09:24 UTC, grobinson-grafana requested changes, later dismissed

2023-06-08 09:24 UTC, grobinson-grafana commented on pkg/services/provisioning/alerting/rules_types.go
> +	if err := yaml.Unmarshal(b, &t); err != nil {
Yaml in `UnmarshalJSON`?

2023-07-14 10:43 UTC, tolzhabayev commented
The `@grafana/alerting-squad-backend` does not seem to exist or is it private / hidden group?

2024-09-12 17:22 UTC, yuri-tceretian approved these changes
LGTM 🎉

2024-09-12 17:44 UTC, merged