Service accounts, 2nd Bullet, Remove "…everything from "
grafana/grafana pull request #65743
Opened 2023-03-31 19:13 UTC by daviddryder

…everything from"

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.
- [ ] There are no known compatibility issues with older supported versions of Grafana, or plugins.
- [ ] It passes the [Hosted Grafana feature readiness review](https://docs.google.com/document/d/1QL9Ly8KnXzpb6ISbg49pTODRO5mhA5tkkfIZVX6pqQU/edit) for observability, scalability, performance, and security.

2023-03-31 19:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=65743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=65743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=65743) it.</sub>

2023-09-08 22:59 UTC, GrafanaWriter requested changes

2023-09-08 22:59 UTC, GrafanaWriter commented on docs/sources/administration/service-accounts/index.md
> +1. **Admin**: User or a team with this permission will be able from **Edit** permission, as well as manage user and team permissions for a service account.
@daviddryder - I'm not sure this update improves the sentence (though I agree it wasn't clear prior); the phrase "will be able from **Edit** permission" doesn't make sense - can you take another look?

cc @chri2547 for follow up as I am seeing this only now and don't want to miss David's response.

2023-09-09 01:02 UTC, daviddryder commented
This reads better "A user or a team with this permission can view, edit,
enable and disable a service account, and add or delete service account
tokens."

On Fri, Sep 8, 2023 at 3:59 PM Fiona Artiaga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/sources/administration/service-accounts/index.md
> <https://github.com/grafana/grafana/pull/65743#discussion_r1320408952>:
>
> > @@ -136,7 +136,7 @@ To control what and who can do with the service account you can assign permissio
>  You can assign on of the following permissions to a specific user or a team:
>
>  1. **Edit**: A user or a team with this permission can view, edit, enable and disable a service account, and add or delete service account tokens.
> -1. **Admin**: User or a team with this permission will be able to everything from **Edit** permission, as well as manage user and team permissions for a service account.
> +1. **Admin**: User or a team with this permission will be able from **Edit** permission, as well as manage user and team permissions for a service account.
>
> @daviddryder <https://github.com/daviddryder> - I'm not sure this update
> improves the sentence (though I agree it wasn't clear prior); the phrase
> "will be able from *Edit* permission" doesn't make sense - can you take
> another look?
>
> cc @chri2547 <https://github.com/chri2547> for follow up as I am seeing
> this only now and don't want to miss David's response.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana/pull/65743#pullrequestreview-1618493561>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVIYIXZNKZC2YKVOIQIZYPTXZOPMVANCNFSM6AAAAAAWPA63LU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-23 01:47 UTC, closed without merging