Explore: run test datasource default selection when mounted
grafana/grafana pull request #65864
Opened 2023-04-03 16:16 UTC by gelicia

**What is this feature?**

When the test datasource is selected, the query editor comes pre-populated with options where it can run without being changed. Because no changes can be made to the form for it to be a valid query, running "Run Queries" without editing anything is seen as an empty query and skipped. This updates the test data query editor on mount so the component picks up the default value.

**Why do we need this feature?**

Because opening the test datasource and finding the run query button to be non-responsive is a bad experience.

**Which issue(s) does this PR fix?**:

Fixes #65426

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-04-03 18:28 UTC, gelicia commented on e2e/various-suite/explore.spec.ts
> +    e2e.components.QueryHistory.queryText().should('have.length', 4).should('contain', 'csv_metric_values');
I dont like this, could be different based on different default values, will make more robust

2023-04-05 09:36 UTC, Elfo404 requested changes
tested it and i think the same can be achieved by adding

```ts
getDefaultQuery(): Partial<TestData> {
    return {
      scenarioId: TestDataQueryType.RandomWalk,
      seriesCount: 1,
    };
  }
```
to `public/app/plugins/datasource/testdata/datasource.ts`.

The however refers to `-- Grafana --` datasource, so adding
```ts
  getDefaultQuery(): Partial<GrafanaQuery> {
    return {
      queryType: GrafanaQueryType.RandomWalk,
    };
  }
```
to `public/app/plugins/datasource/grafana/datasource.ts` would fix the issue also for that DS.

2023-04-05 12:21 UTC, gelicia commented
> tested it and i think the same can be achieved by adding

@Elfo404 both an objectively better solution and on the right datasource (😅 ) thank you so much!

2023-04-05 12:59 UTC, Elfo404 approved these changes

2023-04-05 14:08 UTC, merged