TimePicker: Fixes issues with "Recently used absolute ranges" section
grafana/grafana pull request #66281
Opened 2023-04-11 13:28 UTC by JoaoSilvaGrafana

**What is this feature?**

Someone raised an issue where the "Recently used absolute ranges" was giving them nonsensical values for what they have selected:

![229301082-4512ba23-a1b4-407c-beb9-b0c961a28c14](https://user-images.githubusercontent.com/100691367/231175984-f5b4be35-effb-4983-a558-b9d9a1907936.png)

This led us to realise that if you have any other date format than the default one (for instance by setting `full_date = DD-MM-YYYY HH:mm:ss` in the `custom.ini` file) this will happen. Because the format that we save in local storage for this section is still 'YYYY-MM-DD', so it is trying to read a date in that format with the configured one, hence the nonsensical numbers. To fix this we pass in the default date format in order to tell the date parser that that is the format of the current date.

While investigating this we also found an issue with the timezone. Similarly to above, it was assuming that the value stored in local storage is in the selected timezone but it is already in 'utc', so we have to pass that to the parser as well.

**Why do we need this feature?**

To be more confident that the Time picker history section works correctly.

**Who is this feature for?**

Anyone that uses the history section of the time picker

**Which issue(s) does this PR fix?**:

Fixes #65756

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-04-11 16:11 UTC, tskarhed commented on public/app/core/components/TimePicker/TimePickerWithHistory.tsx
> +  // The history is saved in UTC and with the default date format, so we need to pass those values to the convertRawToRange
Great comment! :+1:

2023-04-11 16:15 UTC, tskarhed requested changes
Some tests that cover both the format and timezone correctness would be preferred. Maybe we can try to do that together?

2023-04-12 14:27 UTC, JoaoSilvaGrafana reviewed
Nice job with the tests! Just some comment changes, otherwise lgtm!

2023-04-12 14:53 UTC, tskarhed commented
I am just trying to finish up with two test cases for TestPickerWithHistory. Good to have it covered, and I get some more test writing exercise :stuck_out_tongue:

2023-04-13 08:55 UTC, tskarhed approved these changes

2023-04-13 10:24 UTC, JoaoSilvaGrafana commented on public/app/core/components/TimePicker/TimePickerWithHistory.test.tsx
> +    //systemDateFormats.useBrowserLocale();
```suggestion
```

2023-04-17 15:19 UTC, merged