Variables: Add support for `$__timezone` template variable
grafana/grafana pull request #66785
Opened 2023-04-18 15:43 UTC by VictorColomb

### What is this feature?

This PR adds a new `$__timezone` variables, replaced by the currently selected time zone by the template server (in queries, labels, etc.)

### Why do we need this feature?

 Use case: Using the Postgres datasource, it allows using functions such as `DATE_TRUNC` to manipulate datetimes in the correct timezone server-side. Example: `DATE_TRUNC('month', TIMEZONE('$__timezone', my_datetime_column))`. See #38159.

Bonus use case: Synchronizing time zones between Grafana and the [clock-panel plugin](https://github.com/grafana/clock-panel).

### Who is this feature for?

All Grafana OSS & Enterprise users.

### Which issue(s) does this PR fix?

Not an issue, but:

Fixes #38159

### Special notes for your reviewer:

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-04-18 16:14 UTC, VictorColomb commented on public/app/features/explore/state/time.test.ts
> +      expect(mockTemplateSrv.updateTimeRange).toBeCalledWith(MOCK_TIME_RANGE, undefined);
FYI, with `defaultTimeZone` from `@grafana/schema`, my first rewrite of this test was as follows. It failed.

```js
expect(mockTemplateSrv.updateTimeRange).toBeCalledWith(MOCK_TIME_RANGE, defaultTimeZone);
```

2023-04-18 17:06 UTC, torkelo requested changes
This should be implemented as a macro (like __data, __value, __url_time_range) 

https://github.com/grafana/grafana/blob/main/public/app/features/templating/macroRegistry.ts

We will turn all the global vars like __user, __dashboard and __org into macros

2023-04-24 14:12 UTC, torkelo commented
Looks good, now we just need to add a section here https://github.com/grafana/grafana/blob/main/docs/sources/dashboards/variables/add-template-variables/index.md#__rate_interval

2023-04-25 15:28 UTC, imatwawana reviewed
Hi @VictorColomb, thanks for the contribution! I've made some wording suggestions and left a question.

2023-04-25 15:28 UTC, imatwawana commented on docs/sources/dashboards/variables/add-template-variables/index.md
> +The `$__timezone` variable returns the currently selected time zone, either `utc` or an entry of the IANA time zone database (e.g. `America/New_York`).
We avoid Latin abbreviations.
```suggestion
The `$__timezone` variable returns the currently selected time zone, either `utc` or an entry of the IANA time zone database (for example, `America/New_York`).
```

2023-04-25 15:28 UTC, imatwawana commented on docs/sources/dashboards/variables/add-template-variables/index.md
> +If the currently selected time zone is _Browser Time_, your browser time zone will be guessed.
```suggestion
If the currently selected time zone is _Browser Time_, Grafana will try to determine your browser time zone.
```

2023-04-25 15:28 UTC, imatwawana commented on docs/sources/dashboards/variables/add-template-variables/index.md
> +The `$__timezone` variable returns the currently selected time zone, either `utc` or an entry of the IANA time zone database (e.g. `America/New_York`).
Is there any specific reason that _UTC_ isn't capitalized on line 320?

2023-04-25 19:40 UTC, imatwawana approved these changes
Docs LGTM!

2023-04-28 06:22 UTC, torkelo approved these changes

2023-05-09 13:21 UTC, merged