Docs: Update backend plugin forward of headers
grafana/grafana pull request #67913
Opened 2023-05-05 13:14 UTC by marefr

**What is this feature?**

Updates backend plugin documentation in regards to automatic forwarding of HTTP headers based on https://github.com/grafana/grafana-plugin-sdk-go/pull/679 changes and breaking changes explained in https://github.com/grafana/grafana-plugin-sdk-go/releases/tag/v0.161.0.

**Why do we need this feature?**

Plugin authors need latest information.

**Who is this feature for?**

Plugin authors.

**Special notes for your reviewer:**

Please check that:
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-05-05 13:20 UTC, xnyo approved these changes
LGTM!

2023-05-05 13:32 UTC, wbrowne approved these changes
Probably better to have @josmperez do a final sign off on this, but LGTM!

2023-05-05 13:32 UTC, wbrowne commented on docs/sources/developers/plugins/add-authentication-for-data-source-plugins.md
> +To get Grafana to forward the headers, create a HTTP client using the [Grafana Plugin SDK](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/backend/httpclient) and set the `ForwardHTTPHead
```suggestion
To get Grafana to forward the headers, create a HTTP client using the [Grafana Plugin SDK](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/backend/httpclient) and set the `ForwardHTTPHeaders` option to `true` (by default it's set to `false`). This package exposes request information which can be subsequently forwarded downstream and/or used directly within the plugin.
```

2023-05-05 17:03 UTC, josmperez commented on docs/sources/developers/plugins/add-authentication-for-data-source-plugins.md
> +To get Grafana to forward the headers, create a HTTP client using the [Grafana Plugin SDK](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/backend/httpclient) and set the `ForwardHTTPHead
```suggestion
To get Grafana to forward the headers, create a HTTP client using the [Grafana plugin SDK for Go](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/backend/httpclient) and set the `ForwardHTTPHeaders` option to `true` (by default, it's set to `false`). This package exposes request information which can be subsequently forwarded downstream and/or used directly within the plugin.
```

2023-05-05 17:04 UTC, josmperez requested changes
Minor style nit. LGTM.

2023-05-08 19:11 UTC, josmperez approved these changes

2023-05-09 09:47 UTC, merged