Derived Fields: Refactor legacy form components and display duplicated name errror
grafana/grafana pull request #68015
Opened 2023-05-08 14:45 UTC by matyax

Follow up of https://github.com/grafana/grafana/pull/67220  . Here, we refactor the form to use non-legacy components, and we display the name error in a more nicely way, as part of https://github.com/grafana/grafana/issues/65294

Also fixed a bug where the data source and internal bug would not be saved if the user did not select a data source.

https://user-images.githubusercontent.com/1069378/236854850-6b23e2c2-191e-4b09-9eda-055b1287d7e2.mov

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/52598

Part of https://github.com/grafana/grafana/issues/65294

**Special notes for your reviewer:**

Before:
<img width="994" alt="Before" src="https://user-images.githubusercontent.com/1069378/236855109-20b1611b-2abc-4a39-9836-d499b11473de.png">

After:
<img width="988" alt="After" src="https://user-images.githubusercontent.com/1069378/236855136-5d0dfbf9-658b-4cfc-8acd-64e4d29e3c63.png">

2023-05-08 18:12 UTC, matyax commented
FYI @catherineymgui

2023-05-08 18:13 UTC, matyax commented
FYI @catherineymgui @josiahg

2023-05-11 11:09 UTC, gabor commented on public/app/plugins/datasource/loki/configuration/DerivedField.tsx
> +              const checked = e.currentTarget.checked;
nitpick: if you want to you can write it this way too, but it's as you prefer.

```suggestion
              const { checked } = e.currentTarget;
```

2023-05-11 11:40 UTC, gabor requested changes
code is fine 👍 ,
there's one thing that did not work for me. the regular-expression does not get saved for me.

1. create a derived field, assign it a name, enter something in the regex-field
2. press [save&test]
3. reload the page
4. the field's name is correct, but the regex-field is empty

2023-05-15 10:40 UTC, gabor approved these changes
LGTM 👍

2023-05-15 10:48 UTC, merged