Tempo: Integrate scoped tags API
grafana/grafana pull request #68106
Opened 2023-05-09 14:26 UTC by joey-grafana

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-05-09 15:09 UTC, joey-grafana commented on public/app/plugins/datasource/tempo/traceql/autocomplete.ts
> -    tags.forEach((t) => (this.tags[t] = new Set<string>()));
Not sure why we were setting each tag to an empty set before. Guessing it's from an older implementation that has since been updated

2023-05-09 15:09 UTC, joey-grafana commented on public/app/plugins/datasource/tempo/language_provider.ts
> -
This code is no longer used.

2023-05-10 10:01 UTC, adrapereira requested changes
Thanks for looking into this! I propose moving the logic to a Tags class to avoid duplicating code across the code base and keeping the fallback logic centralised.

2023-05-11 08:04 UTC, joey-grafana commented on public/app/plugins/datasource/tempo/SearchTraceQLEditor/utils.ts
> +};
Ahh yes this is a great suggestion :)

2023-05-11 08:04 UTC, joey-grafana commented on public/app/plugins/datasource/tempo/SearchTraceQLEditor/utils.ts
> +};
I pushed changes!

2023-05-16 12:12 UTC, adrapereira approved these changes
Thank you for the changes, LGTM!

2023-05-17 06:50 UTC, merged