Alerting: update state manager to change all current states in the case when Error\NoData is executed as Ok\Nomal
grafana/grafana pull request #68142
Opened 2023-05-09 19:37 UTC by yuri-tceretian

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-08-09 17:16 UTC, JacobsonMT commented
Instead of copying the tests, what do you think about something like this:

```GO
func TestProcessEvalResults_StateTransitions(t *testing.T) {
	t.Run("Without applyNoDataAndErrorToAllStates", func(t *testing.T) {
		stateTransitions(t, false)
	})
	t.Run("With applyNoDataAndErrorToAllStates", func(t *testing.T) {
		stateTransitions(t, true)
	})
}

func stateTransitions(t *testing.T, applyNoDataAndErrorToAllStates bool) {
...
}
```

Then making the differences explicit based on the value of `applyNoDataAndErrorToAllStates`.

I think this will make the PR much simpler to read and the tests should be less at risk of drift between feature flag true and false.

2023-08-09 20:04 UTC, yuri-tceretian commented on pkg/services/ngalert/state/manager.go
> +	// TODO yuri. Remove it when correct Error result with labels is provided
Can't remove it in this PR because it breaks execution of Error as Error.

2023-08-09 23:07 UTC, JacobsonMT approved these changes
LGTM, great job :rocket: 

![image](https://github.com/grafana/grafana/assets/8484471/1489b729-5a44-46c4-aa4b-4f8f755b01aa)

2023-08-10 20:36 UTC, grobinson-grafana requested changes
I see this change is behind a feature flag, which is great! However, I'm requesting changes not because I want actual changes to be done to the code, but instead I want to ask a question before we add this to `main`.

tl;dr the question:

I understand the sentimental of this change is to make all states for a rule consistent when either No Data or an error occurs. Where this concerns me is that for some of our larger customers this can create massive alert storms. If their datasource is down, it could be 10,000s of alerts firing at once, perhaps 100,000s. If their grouping is generous, a number of contact points will also fail (such as email) as the email will be too large. I'm not sure about others such as Slack or Pagerduty.

I'm not sure this is the right feature to add moving forward, but I can support having it behind a feature flag for experimentation.

@yuri-tceretian and @JacobsonMT, could you share your opinions on what I've said above?

2023-08-14 21:55 UTC, grobinson-grafana approved these changes

2023-08-14 21:55 UTC, grobinson-grafana commented
I tested a number of scenarios and seem to work as expected!

2023-08-15 14:27 UTC, merged