CI: Add release verify pipeline
grafana/grafana pull request #68756
Opened 2023-05-20 22:12 UTC by kminehart

2023-05-22 06:12 UTC, zerok requested changes

2023-05-22 06:12 UTC, zerok commented on scripts/release-artifacts.sh
Would `verify-release-artifacts.sh` be perhaps a better name here?

2023-05-22 06:12 UTC, zerok commented on scripts/release-artifacts.sh
> +ERSION="${VERSION#*v}"
`ERSION`? ^_^

2023-05-22 12:38 UTC, kminehart commented on scripts/release-artifacts.sh
> +ERSION="${VERSION#*v}"
It's version without the v!

2023-05-22 13:10 UTC, kminehart commented on scripts/release-artifacts.sh
I made it 'list-release-artifacts.sh' since that's technically what it does. Then you can pipe to xargs to do something with each of them (like gsutil stat).

2023-05-23 08:01 UTC, zerok approved these changes

2023-05-23 08:01 UTC, merged