Tracing: Upgrade tracing data source configuration editors
grafana/grafana pull request #68764
Opened 2023-05-22 08:52 UTC by joey-grafana

**What is this feature?**

Upgrades configuration editors in Tempo/Jaeger/Zipkin.

**Why do we need this feature?**

A lot of great work has gone into designing new configuration editors. This PR works that into our Tempo/Jaeger/Zipkin data sources.

**Who is this feature for?**

Users of Tempo/Jaeger/Zipkin.

**Special notes for your reviewer:**

https://github.com/grafana/grafana/assets/90795735/2770c42e-07f7-4479-83e1-1127534187ec

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-05-23 20:46 UTC, catherineymgui commented
1. In JIRA — we added a max width so that the arrows on the collapsable sections aren't showing all the way to the right of the page (esp on larger browser sizes)
2.  For the additional settings section — the idea is that we don't need additional horizontal dividers between the subsections (just 24px padding b/w them)
3. All the link outs to the settings could be more specific (“Learn more about <name of setting>” — so like Learn more about trace to logs, learn more about node graph" etc?)

Also just fyi, the auth component and description component are available.

2023-05-25 12:09 UTC, joey-grafana commented
Thanks for the feedback, all comments addressed.

2023-05-31 15:17 UTC, cletter7 requested changes

2023-05-31 15:17 UTC, cletter7 commented on public/app/features/explore/TraceView/components/settings/SpanBarSettings.tsx
> +import { NodeGraphSettings } from 'app/core/components/NodeGraphSettings';
This is unused now, we can remove it.

2023-06-01 08:17 UTC, cletter7 approved these changes

2023-06-01 13:29 UTC, aocenas approved these changes

2023-06-01 14:52 UTC, merged