Docs: Contribution guidelines for updating Drone pipelines
grafana/grafana pull request #69530
Opened 2023-06-05 07:43 UTC by tskarhed

**What is this feature?**

Documentation for 

**Why do we need this feature?**

Easier to get started with pipeline development, and reduces questions to grafana-delivery

**Who is this feature for?**

Grafana contributors who wants to create new pipeline steps

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-06-05 08:15 UTC, zerok approved these changes
Thank you :)

2023-06-05 08:15 UTC, zerok commented on contribute/drone-pipeline.md
> +- Set environment variables `DRONE_SERVER` and `DRONE_TOKEN`, which can be found on your [Drone account](https://drone.grafana.net/account). These are used to verify that onyl Grafana employees can m
```suggestion
- Set environment variables `DRONE_SERVER` and `DRONE_TOKEN`, which can be found on your [Drone account](https://drone.grafana.net/account). These are used to verify that only Grafana employees can make changes to the pipelines.
```

2023-06-05 08:15 UTC, zerok commented on contribute/drone-pipeline.md
> +- Run `make drone` after making changes to the Starlark files. This builds the `.done.yml` file.
```suggestion
- Run `make drone` after making changes to the Starlark files. This builds the `.drone.yml` file.
```

2023-06-05 08:15 UTC, zerok requested changes
Just found some minor typos :)

2023-06-05 08:49 UTC, tskarhed commented on contribute/drone-pipeline.md
> +- Set environment variables `DRONE_SERVER` and `DRONE_TOKEN`, which can be found on your [Drone account](https://drone.grafana.net/account). These are used to verify that onyl Grafana employees can m
I should read what I write :facepalm:

2023-06-05 08:53 UTC, zerok approved these changes

2023-06-06 07:19 UTC, tskarhed commented
@grafana/docs-grafana Any input here?

2023-06-14 08:40 UTC, merged