Prometheus: Metrics explorer add docs and image
grafana/grafana pull request #69965
Opened 2023-06-12 20:21 UTC by bohandley

**What is this?**
This is a pr to add documentation for the metrics explorer in the query builder docs.

**Why do we need this feature?**
The metrics explorer is being turned on by default in v10.1 and part of the roll out is to add documentation about the feature.

**Who is this feature for?**
The metrics explorer is for prometheus users with beginning and intermediate experience who want to explore their metrics.

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-06-27 21:05 UTC, gtk-grafana approved these changes

2023-06-28 20:09 UTC, lwandz13 requested changes
just a couple suggestions :-)

2023-06-28 20:09 UTC, lwandz13 commented on docs/sources/datasources/prometheus/query-editor/index.md
> +When you click **Metrics browser** in code mode, it displays all available metrics and labels.
```suggestion
When you click **Metrics browser** in `Code` mode, it displays all available metrics and labels.
```

2023-06-28 20:49 UTC, bohandley commented on docs/sources/datasources/prometheus/query-editor/index.md
> +{{< figure src="/static/img/docs/prometheus/metrics-explorer-option.png" max-width="500px" class="docs-image--no-shadow" caption="Metrics explorer" >}}
No, I think this was from a first version. This is a step in how to get to the metrics explorer through the metric select but according to the writer's toolkit we are not supposed to show a secondary navigation item (the option in the select to open the modal).

2023-06-28 20:53 UTC, bohandley commented on docs/sources/datasources/prometheus/query-editor/index.md
> +{{< figure src="/static/img/docs/prometheus/metrics-explorer-option.png" max-width="500px" class="docs-image--no-shadow" caption="Metrics explorer" >}}
Removed!

2023-06-29 14:51 UTC, lwandz13 approved these changes

2023-06-29 14:54 UTC, merged