Update Transform Data :docs:
grafana/grafana pull request #71013
Opened 2023-07-02 16:27 UTC by jasuade

**What is this feature?**

 Review of the Transform Data page on [Grafana Public Documentation ](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/).

The original content has been reviewed and is still relevant. However, there are numerous new transformation that has not been included. This PR serves as a template to create these new sections but I need development input to put adequate examples.

Missing Transformations:
- Create heatmap
- Extract fields
- Field lookup
- Grouping to matrix
- Histogram
- Join by labels

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-07-04 16:08 UTC, imatwawana requested changes
@jasuade - This is a fantastic start! Thank you so much for adding all of these missing transformations. I've made a number of formatting suggestions to make the updates more consistent with the existing content and to make the additions easier to scan. I've also left some questions in spots where I'm not clear on the meaning. The rest of the edits are just minor spelling/grammar/style things. Request a review from me again when you've addressed this feedback and I'll take another look.

2023-07-04 16:08 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Use this transformation to generate a histogram based on the input data. You can select the bucket size as the distance between the lowest item in the bucket (xMin) and the highest item in the bucket
we should have a description of 
```suggestion
Use this transformation to generate a histogram based on the input data. 

- **Bucket size** - The distance between the lowest item in the bucket (xMin) and the highest item in the bucket (xMax).
- **Bucket offset** - The offset for non-zero based buckets.
- **Combine series** - Create a histogram using all the available series.

```

2023-07-04 16:08 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +
```suggestion
```

2023-07-04 16:08 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +### Join by Labels
```suggestion
### Join by labels
```

2023-07-04 16:08 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Select the label to `Join` by between the labels available or common accross all time series, and the `Value` name for the output result.
When you say "the labels available or common across all time series" - are these the same thing or two different sets of labels?
```suggestion

- **Join** - Select the label to join by between the labels available or common across all time series.
- **Value** - The name for the output result. 
```

2023-07-10 15:57 UTC, imatwawana approved these changes
I've suggested some small edits that I missed before, but this looks great!

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +
```suggestion
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Use this transformation to prepare histogram data to be visualized over time. Similar to the [Heatmap panel] ({{< relref "../visualizations/heatmap" >}}), this transformation allows you to convert hi
fixing link
```suggestion
Use this transformation to prepare histogram data to be visualized over time. Similar to the [Heatmap panel]({{< relref "../../visualizations/heatmap" >}}), this transformation allows you to convert histogram metrics to buckets over time.
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +- **Symlog** - A symmetrical logarithmic scale - Use a base 2 or base 10; allows negative values
```suggestion
- **Logarithmic** - Use a base 2 or base 10.
- **Symlog** - A symmetrical logarithmic scale. Use a base 2 or base 10; allows negative values.
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +  - **Auto** To discover fields automatically
```suggestion
  - **JSON** -  To parse JSON content from the source.
  - **Key+value parse** -  To parse content in the format `a=b` or `c:d` from the source.
  - **Auto** - To discover fields automatically.
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +- **Replace all fields** -  (Optional) Select this option if you want to hide all other fields and display only your calculated field in the visualization.
```suggestion
- **Replace all fields** -  Optional: Select this option if you want to hide all other fields and display only your calculated field in the visualization.
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +- **Lookup** - Select from **Countries**, **USA States**, and **Airports**)
```suggestion
- **Lookup** - Select from **Countries**, **USA States**, and **Airports**.
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Use this transformation to combine three fields, that will be used as input for the **Column**, **Row**, and **Cell value** fields, from the query output and generate a matrix. This matrix will be ca
```suggestion
Use this transformation to combine three fields—that will be used as input for the **Column**, **Row**, and **Cell value** fields—from the query output, and generate a matrix. This matrix will be calculated as follows:
```

2023-07-10 15:57 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +time series results into a single wide table with a shared Label field.
```suggestion
time series results into a single wide table with a shared **Label** field.
```

2023-07-10 15:57 UTC, imatwawana commented
> Thank you @imatwawana ! I added the changes. Regarding the backporting, I would need also Eng. input on that, I know most of them were already in 9.5.x for sure, but I am not sure how far back are all of them, I will try to check on the What's New and Change log to get the exact version where they were included. But I may need double check by engineering.

I might be able to figure this out. I'll circle back.

2023-07-10 16:06 UTC, imatwawana commented
I was able to confirm in my local that these changes were all present in v9.4 so that's how far we'll backport this.

2023-07-11 10:50 UTC, jasuade commented
Super! I would still ping the Metrics team to take a look at this (I think they are in charge of Transformation isn't they?)

2023-07-11 14:43 UTC, imatwawana reviewed
@LudoVio - I've made some suggestions to make the examples a more consistent with the existing examples on this page.

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +You could prepare the data to be used by a [Time series panel]({{< relref "../../visualizations/time-series" >}}) with this config:
```suggestion
You could prepare the data to be used by a [Time series panel]({{< relref "../../visualizations/time-series" >}}) with this configuration:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +For example, if we have this data:
changing to preferred second person 
```suggestion
For example, if you have this data:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +| timestamp           | json_data     |
capitalizing the column headers where appropriate to be consistent with existing tables on this page
```suggestion
| Timestamp           | json_data     |
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +| timestamp           | my_value |
```suggestion
| Timestamp           | my_value |
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +This will output:
```suggestion
This will generate the following output:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +With this config:
```suggestion
With this configuration:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +| location  | id  | name     | lng         | lat       | values |
```suggestion
| Location  | ID  | Name     | Lng         | Lat       | Values |
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +We will get this output:
```suggestion
You'll get the following output:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Serie 2:
```suggestion
Series 2:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +Serie 1:
```suggestion
Series 1:
```

2023-07-11 14:43 UTC, imatwawana commented on docs/sources/panels-visualizations/query-transform-data/transform-data/index.md
> +| location  | values |
```suggestion
| Location  | Values |
```

2023-07-17 16:54 UTC, imatwawana commented
@jasuade & @LudoVio - This looks good. Shall I merge it?

2023-07-18 07:43 UTC, jasuade commented
LGTM!

2023-07-18 14:07 UTC, merged