Segment Story Component: Removed any type from Segment story component
grafana/grafana pull request #71043
Opened 2023-07-04 13:38 UTC by RoxanaAnamariaTurc

**What is this feature?**
Updated the Segment Component from storybook by removing the any types.

**Why do we need this feature?**

To ensure the component is typed and less prone to errors.

**Who is this feature for?**

Everyone

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-07-04 15:34 UTC, ashharrison90 requested changes
lots of suggestions but they basically all stem from the one change to `toOption`

shout if anything doesn't make sense 👍

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
> +  const [value, setValue] = useState<SelectableValue>(options[0]);
```suggestion
  const [value, setValue] = useState<SelectableValue<string | number>>(options[0]);
```

you'll also need to remove the destructuring in the `onChange`, e.g.
```tsx
        onChange={(value) => {
          setValue(value);
          action('Segment value changed')(value);
        }}
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
> +const CustomLabelComponent = ({ value }: SelectableValue) => <div className="gf-form-label">custom({value})</div>;
```suggestion
const CustomLabelComponent = ({ value }: SelectableValue<string | number>) => <div className="gf-form-label">custom({value})</div>;
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
> +  const [value, setValue] = useState<SelectableValue>(options[0]);
```suggestion
  const [value, setValue] = useState<SelectableValue<string | number>>(groupedOptions[0].options[0]);
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
> +const SegmentFrame = ({ options, children }: { options: Object[]; children: React.ReactNode }) => (
```suggestion
const SegmentFrame = ({ options, children }: { options: Array<SelectableValue<string | number>>; children: React.ReactNode }) => (
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
> +  const [value, setValue] = useState<string | number | undefined>('Option1');
```suggestion
  const [value, setValue] = useState<string | undefined>('Option1');
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
>      <SegmentFrame options={options}>
```suggestion
    <SegmentFrame options={groupedOptions}>
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
>      <SegmentFrame options={options}>
```suggestion
    <SegmentFrame options={groupedOptions}>
```

2023-07-04 15:34 UTC, ashharrison90 commented on packages/grafana-ui/src/components/Segment/Segment.story.tsx
>      <SegmentFrame options={options}>
```suggestion
    <SegmentFrame options={groupedOptions}>
```

2023-07-04 16:21 UTC, RoxanaAnamariaTurc commented on packages/grafana-data/src/types/select.ts
> +export interface SelectableValue<T> {
Thank you for the suggestions , I made the changes now :)

2023-07-05 08:02 UTC, ashharrison90 approved these changes
lgtm 🙌

2023-07-05 08:27 UTC, merged