Loki: Improve query cache hits
grafana/grafana pull request #71384
Opened 2023-07-11 15:41 UTC by gwdawson

**What is this feature?**
this takes the first steps towards our goal of trying to improve cache hits in loki

changes in this pr:

1. reorder selectors before running loki queries
2. trim queries of whitespace

> NOTE: THE QUERY DOES NOT CHANGE FOR THE USER, TO SEE THE REFLECTED CHANGE YOU WILL HAVE TO CHECK THE NETWORK TAB

```
input query:
{b_label="second", c_label="third", a_label="first"}

---

executed query:
{a_label="first", b_label="second", c_label="third"}
```

```
input query:
rate(  
    {b_label="second", a_label="first"}
  |=""
   |logfmt 
           |label=""
           [1s]        
) 

---

exectued query:
rate(
{a_label="first", b_label="second"}
|=""
|logfmt
|label=""
[1s]
)

```

**Which issue(s) does this PR fix?**:
Fixes #65994

2023-07-12 12:12 UTC, matyax reviewed
Great work! both in the implementation and the PR title and description.
Left some comments and, as always, no test, no quest.

![imagen](https://github.com/grafana/grafana/assets/1069378/ac34b1be-2df9-4b49-a95c-e2de8fd39c30)

2023-07-12 12:12 UTC, matyax commented on public/app/plugins/datasource/loki/datasource.ts
> +
I would move all this to `queryUtils` and just call a function from there, so we don't keep piling up code in the datasource.

2023-07-12 12:12 UTC, matyax commented on public/app/plugins/datasource/loki/queryUtils.ts
> +      return 0;
We could shorten this a little bit like:

```suggestion
      if (!labelNameA || !labelNameB) {
        return 0;
      }

      if (labelNameA < labelNameB) {
        return -1;
      }

      return (labelNameA > labelNameB) ? 1 : 0;
```

2023-07-14 05:47 UTC, gabor commented
nice work 👍 . do you think there could be any complications for the user? (for example, Loki returns an error-message saying let' say error at position 10, but that position is now different because of reorder & trim?) i'm not saying such situation could happen, i just wonder.

2023-07-14 07:42 UTC, matyax commented
> say error at position 10

Ouch, yes. That is a really good point. It would be extremely confusing.

2023-07-14 09:07 UTC, ivanahuckova commented
I see in the linked issue that 
`investigate if it would be worth sorting labels before queries are executed` is checked out. I am wondering if we have any summary, because I can think of couple of places where this would complicate things for us:

- error messages coming from Loki with errors such as`error at position X` would be inaccurate
- in inspect query, you would have incorrect/different query than what you have written
- every time there is an issue/escalation related to querying, we would have to consider repositioned query

And I personally don't know, if there are many/significant amount of queries that have the same timestamps and labels and they are just reordered. I don't see this happening in dashboards at all, as the queries are saved. And in Explore I would expect that users have often different absolute timestamps. So I would like to see some data that this is actually an issue before we move on as I think this could really complicate things for debugging in the future.

2023-07-14 09:08 UTC, ivanahuckova requested changes
I see in the linked issue that `investigate if it would be worth sorting labels before queries are executed` is checked out. I am wondering if we have any summary, because I can think of couple of places where this would complicate things for us:

- error messages coming from Loki with errors such as `error at position X` would be inaccurate
- in inspect query, you would have incorrect/different query than what you have written
- every time there is an issue/escalation related to querying, we would have to consider repositioned query

And I personally don't know, if there are many/significant amount of queries that have the same timestamps and labels and they are just reordered. I don't see this happening in dashboards at all, as the queries are saved. And in Explore I would expect that users have often different absolute timestamps. So I would like to see some data that this is actually an issue before we move on as I think this could really complicate things for debugging in the future.

2023-07-14 09:46 UTC, gwdawson commented
i spoke with @gabor about this before, the `investigate ...` was an oversight on my side thinking it wouldn't change much but as pointed out there are some pretty serious side affects to this.

i will put this on hold for now and we can discuss this more in mondays weekly.

2023-07-20 13:13 UTC, closed without merging