Explore: Moved 'handles open/close splits in UI and URL' test to the spec folder
grafana/grafana pull request #71674
Opened 2023-07-14 17:03 UTC by harisrozajac

This was the last task in https://github.com/grafana/grafana/issues/54777.

It moves the open/close split related logic from `ExplorePage.test.tsx` to a separate file in spec folder. The remaining thing to do would be to create some unit tests for `ExplorePage.tsx`. The task for that is here: https://github.com/grafana/grafana/issues/54777

Fixes: https://github.com/grafana/grafana/issues/54775

2023-07-14 18:08 UTC, gelicia requested changes
The description for this test still refers solely to the component, when we will want it to reflect it's component-agnostic like the other tests in the `spec` folder.

2023-07-14 19:48 UTC, harisrozajac commented
> The description for this test still refers solely to the component, when we will want it to reflect it's component-agnostic like the other tests in the `spec` folder.

@gelicia Ah that makes sense. I wondered about that. I've made the update 👍

2023-07-17 13:10 UTC, gelicia commented on public/app/features/explore/spec/split.test.tsx
> +  // TODO: the following tests are using the compact format, we should use the current format instead
For more about the difference between compact and non-compact, see https://docs.google.com/document/d/1YYljgT52u30AbmlKpFjl4s0MC6fZg2SnPIyAAn0aQks/edit#heading=h.5sybau7waq2q 

I feel like this shouldn't take that long and will be easy enough to clean up, but feel free to ignore this.

2023-07-17 13:11 UTC, gelicia approved these changes

2023-07-17 15:01 UTC, harisrozajac commented on public/app/features/explore/spec/split.test.tsx
> +  // TODO: the following tests are using the compact format, we should use the current format instead
@gelicia thank you for the docs, I've updated this to use non-compact format

2023-07-17 15:51 UTC, gelicia commented on public/app/features/explore/spec/split.test.tsx
> +  // TODO: the following tests are using the compact format, we should use the current format instead
This looks great, and for the other part of this comment, compact tests are handled in their migrator file https://github.com/grafana/grafana/blob/main/public/app/features/explore/hooks/useStateSync/migrators/v0.test.ts#L64 (thanks @Elfo404 !)  so we're all set I think :D

2023-07-18 13:47 UTC, merged