Schemas: minor updates from the k8s branch
grafana/grafana pull request #71688
Opened 2023-07-14 21:03 UTC by ryantxu

This PR updates a few minor issues that are resolved in the k8s api-server branch:

1. allows null value on Dashbaord ID -- while not totally accurate, this happens in practice and this compromise is fine for now
2. adds CookiePreferences to the preferences object (still behind feature flag)
3. changes the version in generated golang resource wrappers.  k8s is not happy with a dot "." in the version number, so we are hardcoding to "v0-alpha" for now

2023-07-14 21:03 UTC, ryantxu commented on kinds/dashboard/dashboard_kind.cue
> +			id?: int64 | null // TODO eliminate this null option
^^ the most meaningful change in this PR

2023-07-17 16:54 UTC, sdboyer requested changes

2023-07-17 16:58 UTC, ryantxu commented on pkg/codegen/jenny_go_resources.go
> -		Version:          sch.Version().String(),
yes please.  the only real goal is getting "." out of the version since agregated api servers won't work with that

2023-07-17 17:35 UTC, sdboyer commented on pkg/codegen/jenny_go_resources.go
> -		Version:          sch.Version().String(),
all set 👍🏻

2023-07-18 09:33 UTC, sdboyer approved these changes

2023-07-21 16:17 UTC, merged