PostgreSQL: bump lib/pq to latest version
grafana/grafana pull request #72416
Opened 2023-07-27 03:50 UTC by nhudson

**What is this feature?**

Update `lib/pq` to the latest version 

**Why do we need this feature?**

With the current version of `lib/pq`, connections to a PostgreSQL database that use SNI routing will fail.  

**Who is this feature for?**

This is for anyone who is attempting to connect Grafana to a PostgreSQL database backend which sits behind a router that is routing the traffic with SNI.

**Which issue(s) does this PR fix?**:

Fixes #

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-07-27 03:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=72416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=72416) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=72416) it.</sub>

2023-07-29 13:45 UTC, zserge approved these changes

2023-08-14 20:01 UTC, mildwonkey commented
Hey @nhudson - thank you for opening this, and sorry for the delay since @zserge approved it. If you can fix the `go.sum` conflicts I'll get this merged; you can also let me know if you'd rather I fix that - I can push a commit if you don't have time right now. Thanks again!

2023-08-14 20:25 UTC, nhudson commented
> Hey @nhudson - thank you for opening this, and sorry for the delay since @zserge approved it. If you can fix the `go.sum` conflicts I'll get this merged; you can also let me know if you'd rather I fix that - I can push a commit if you don't have time right now. Thanks again!

Thanks for the heads up!  I can get to it tomorrow if that's good?

2023-08-15 15:20 UTC, nhudson commented
@mildwonkey @zserge I have fixed the conflicts, but Drone is failing and I am not really sure how to fix it.  Do one you of mind looking at it for me?

2023-08-15 15:35 UTC, mildwonkey commented on go.mod
> +require github.com/blang/semver/v4 v4.0.0
I'm not sure where this dependency is coming from - I recreated this PR locally and it's not showing up. Do you have any ideas, or are you able to remove it?

2023-08-15 15:37 UTC, mildwonkey requested changes
The only failure we need to address is the modowners, and removing the extraneous semver import in go.mod should take care of that.

2023-08-15 16:21 UTC, mildwonkey approved these changes

2023-08-15 16:57 UTC, nhudson commented
@mildwonkey I don't know what the new failures are from.  Is this something that I should investigate?

2023-08-15 17:02 UTC, mildwonkey commented
thanks for sticking with this @nhudson - I appreciate the extra hoops you had to jump through! You should be all good - I will follow up on that last failing check, but I'm reasonably optimistic that it's not a blocker 


(I'm technically positive it's not a blocker because it is not a required check, but I'm still going to double check 😁 )

2023-08-15 17:04 UTC, mildwonkey commented
and we're confirmed (in internal slack) - thanks again @nhudson !

2023-08-15 17:04 UTC, merged