Dashboard embed/edit view
grafana/grafana pull request #72448
Opened 2023-07-27 12:53 UTC by Clarity-89

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-08-14 16:31 UTC, polibb approved these changes
`isEmbedded` to the dashboard model seems kinda generic, but it's true - special case for the differently rendered dashboard UI. I guess it will serve even better purpose in the future, when we need to handle this special case with even more care and allow more functionalities 😊🙏.

Thank you for setting this up so well it's easy to add to it in cases like this!

2023-08-14 16:54 UTC, torkelo reviewed
When was this EmbeddedDashboaerdPage added???

and what is it for??

2023-08-14 17:15 UTC, torkelo commented
found https://github.com/grafana/grafana/pull/69596 (added some comments to it)

2023-08-14 17:18 UTC, torkelo requested changes
I don't think having to maintain two dashboard pages and two different dashboard edit handlers is a good idea. 

Having a stripped down "stupid" read-only dashboard view that loads a json from anywhere and has no editing, and is for iframing, image capture etc could maybe make sense (but we have kiosk modes for that).

2023-08-14 17:20 UTC, torkelo commented
But if this is just for a POC / user test then maybe, as long as it never is seen as prod code, and something scenes dashboards needs to support (we are rewriting core dashboards in scenes)

2023-08-15 04:56 UTC, Clarity-89 commented
> I am not sure having to maintain two dashboard pages and two different dashboard panel edit state handling code is a good idea.
> 
> Having a stripped down "stupid" read-only dashboard view that loads a json from anywhere and has no editing, and is for iframing, image capture etc could maybe make sense (but we have kiosk modes for that).

We need a custom page that can handle rendering dashboard from JSON and custom save logic, it doesn't looks like kiosk mode fits that use case. Are there any other options?

2023-08-15 06:07 UTC, Clarity-89 commented
@torkelo would adding an embed kiosk mode work? That way we could keep this new functionality inside the current dashboard logic. I can try a quick POC to see how that could work.

2023-08-16 04:08 UTC, nulldoot2k commented
suggest for version 9.
Feature: Kiosk=embedded
https://github.com/grafana/grafana/pull/65754
thanks 
![image](https://github.com/grafana/grafana/assets/83489434/04386f21-43a5-41ef-a325-dd4d4aae3dc6)

2023-08-28 06:21 UTC, Clarity-89 commented
Closing this for now.

2023-08-28 06:21 UTC, closed without merging