Chore: Rename Victorops to Splunk OnCall
grafana/grafana pull request #72462
Opened 2023-07-27 15:58 UTC by chauchausoup

**What is this feature?**

This PR will rename VictorOps to Splunk OnCall as per the issue description. 

**Why do we need this feature?**

To have appropriate naming.

**Who is this feature for?**

This feature is for every end user.

**Which issue(s) does this PR fix?**:

Fixes #47632

**Special notes for your reviewer:**
This comment in issue section https://github.com/grafana/grafana/issues/47632#issuecomment-1653263284 needs to be answered for the proper implementation of the rename. It seems that the PR section is getting communication so I have raised a PR with a simple visual level fix of the problem. Upon answering the above given questions on the specific issue section I can add few commits on this PR if we need a complete rename here.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-09-04 13:31 UTC, grobinson-grafana requested changes
Thanks for your contribution! Just a couple of small changes please.

2023-09-04 13:31 UTC, grobinson-grafana commented on docs/sources/old-alerting/notifications.md
> +### Splunk OnCall
Old alerting is deprecated, so please revert the changes in this file.

2023-09-04 13:31 UTC, grobinson-grafana commented on pkg/services/ngalert/notifier/channels_config/available_channels.go
> +			Name:        "Splunk OnCall",
Please don't revert the changes here though as `ngalert` is the new Grafana Alerting.

2023-09-04 13:32 UTC, grobinson-grafana commented on pkg/services/alerting/notifiers/victorops.go
>  		Factory:     NewVictoropsNotifier,
We should also rename the code https://github.com/grafana/alerting/tree/main/receivers/victorops and the functions that are used here.

2023-09-17 07:43 UTC, closed without merging

2023-10-05 04:25 UTC, chauchausoup commented
@grobinson-grafana I have closed the PR due to some internal git merge issue from my side. Sorry for that.

What might be an effective migration plan here ? Editing the on going VictorOps or rolling out parallel clone VictorOps and changing the clone accordingly ?

In the mean time as per your suggestion above, I am setting up a new PR as 
https://github.com/grafana/grafana/pull/75786
and also on /alerting as 
https://github.com/grafana/alerting/pull/126

But it seems that /alerting talks with prometheus fro api_keys so I guess we need to untouch those fields and let them be victorOps or should raise a PR in prometheus too ?

All these operations might need many steps so I recommend I will step by step raising unit PRs and tag you on each ?

First I will start with, `.md files -->> UI fields -->> API endpoints -->> alerting repo -->> prometheus repo`

Let me know you thoughts.