AzureMonitor: Check to see if response is nil to prevent panic
grafana/grafana pull request #72705
Opened 2023-08-02 02:02 UTC by bossinc

This will prevent panics from happening when there is no response. 
https://github.com/grafana/support-escalations/issues/6911

2023-08-02 09:44 UTC, aangelisc reviewed
Is the problem that `res` is `nil` or that `res.Body` is? Looking at the logs the issue is on line 232 (which is 274 here) so maybe we should be checking both?

2023-08-02 09:50 UTC, aangelisc approved these changes

2023-08-02 09:55 UTC, aangelisc requested changes
Ok I'm retracting my initial review because I'm an idiot. If `res` is `nil` that means that `err` is not `nil`. So we can move the return into the error handling condition above rather than having a separate condition. We can also fix the log statement on 267 as it seems the interpolation isn't working so the true underlying API error is hidden in the logs 😊

2023-08-03 10:13 UTC, aangelisc commented on pkg/tsdb/azuremonitor/metrics/azuremonitor-datasource.go
> +		dataResponse.Error = err
I think we should just log the error here at this point and continue with the query, wdyt?

2023-08-03 13:28 UTC, aangelisc approved these changes

2023-08-03 14:44 UTC, asimpson approved these changes
Like this approach, nice work :trophy:

2023-08-03 21:48 UTC, merged