sign-plugin-docs: information of usage of a new token has been added to the docs
grafana/grafana pull request #72912
Opened 2023-08-04 12:09 UTC by Ukochka

The signing package should first try to read a new env variable called GRAFANA_ACCESS_POLICY_TOKEN and use it for signing purposes

We need to change documentation to show how to get this new GRAFANA_ACCESS_POLICY_TOKEN and how to use it

Fixes #328

**Special notes for your reviewer:**

I have uploaded screenshots to https://admin.grafana.com/upload/static/img/docs/plugins/

2023-08-04 13:43 UTC, Eve832 commented
Hey @Ukochka can you please sign the CLA? We can't merge without it.

2023-08-04 13:50 UTC, Eve832 requested changes

2023-08-04 13:50 UTC, Eve832 commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +1. Login into your account and navigate to "My Account" -> Security-> Access Policies. And click "Create access pilicy"
```suggestion
1. Login into your account and navigate to **My Account > Security > Access Policies**. Click **Create access policy**.
```

2023-08-04 13:50 UTC, Eve832 commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +   Realm: has to be your-org-name (all-stacks)\
```suggestion
   Realm: has to be your-org-name (all-stacks)
   
```

2023-08-04 13:50 UTC, Eve832 commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +1. Once policy created, create a new tocker by clicking "Create token" button.\
```suggestion
1. Click **Create token** to create a new token.
```

2023-08-04 13:50 UTC, Eve832 commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +   Click "Create" and Copy the token
```suggestion

   The expiration date field is optional, though you should change tokens periodically for increased security.

   {{< figure src="/static/img/docs/plugins/create-access-policy-token.png" class="docs-image--no-shadow" max-width="650px" >}}

1. Click **Create** and save a copy of the token somewhere secure for future reference. 
```

2023-08-04 23:06 UTC, josmperez commented
I concur with Eve's suggestions. Otherwise, looks good.

2023-08-07 07:26 UTC, Ukochka commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +1. Login into your account and navigate to "My Account" -> Security-> Access Policies. And click "Create access pilicy"
Done! Thank you!

2023-08-07 07:26 UTC, Ukochka commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +   Realm: has to be your-org-name (all-stacks)\
Done! Thank you!

2023-08-07 07:26 UTC, Ukochka commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +1. Once policy created, create a new tocker by clicking "Create token" button.\
Done! Thank you!

2023-08-07 07:26 UTC, Ukochka commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +   Click "Create" and Copy the token
Done! Thank you!

2023-08-07 09:43 UTC, academo commented on docs/sources/developers/plugins/publish-a-plugin/sign-a-plugin.md
> +To verify ownership of your plugin, generate access token that you'll use every time you need to sign a new version of your plugin.
`generate access token` -> `generate an access token`

2023-08-07 10:27 UTC, tolzhabayev commented
@Ukochka due to how our documentation works ([gh actions](https://github.com/grafana/grafana/blob/main/.github/workflows/publish-technical-documentation-release.yml)), you have to backport this PR to 10.0.x by adding a `backport 10.0.x` label to it. After the merge grafanabot will create a backport PR and link it here. You can approve and merge the backport PR yourself (no need for additional approvals). 

Once merged into main the doc changes will be available at: 
- https://grafana.com/docs/grafana/next/developers/plugins/publish-a-plugin/sign-a-plugin/

Once backport is merged at:
- https://grafana.com/docs/grafana/latest/developers/plugins/publish-a-plugin/sign-a-plugin/

Both might take a while to sync and publish.

2023-08-07 14:02 UTC, Eve832 approved these changes

2023-08-07 14:10 UTC, merged