Docs: Fix broken links to create-plugin docs
grafana/grafana pull request #72965
Opened 2023-08-04 23:33 UTC by josmperez

On the plugin-tools repo, the path to create-plugin docs has changed to https://grafana.github.io/plugin-tools/docs/get-started/. Fixing links.

2023-08-08 23:00 UTC, clayton-cornell approved these changes
Looks OK to me. All links work

2023-08-09 07:05 UTC, academo approved these changes

2023-08-09 10:01 UTC, sympatheticmoose requested changes
Still a broken link for the migration guide:
- Line 364 in the breaking-changes doc

Also the [CHANGELOG](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) includes links to both getting started and migration guide, we should likely update this too just in case.

2023-08-09 17:41 UTC, josmperez commented
@sympatheticmoose - At grafana/contribute/breaking-changes-guide.md, there is no line 364. At 107, there's "5. Update the [migration guide](../docs/sources/developers/plugins/migration-guide.md) with your instructions". Is this your concern?

I've searched the Grafana repo for links to the migration guide on https://grafana.github.io/plugin-tools/ and didn't find any.

2023-08-09 19:02 UTC, sympatheticmoose approved these changes
@josmperez still missing updates to the changelog but not blocking

2023-08-09 19:53 UTC, merged

2023-08-10 09:00 UTC, sympatheticmoose commented
@josmperez just ignore the backport to 9.5, we don't need it