Alerting hipchat
grafana/grafana pull request #7374
Opened 2017-01-26 15:06 UTC by jregovic

https://github.com/grafana/grafana/issues/6451

Adds an alert notification using the HipChat v2 room API.
Messages go to the v2/room/ROOMID/notification?auth_token=AUTHTOKEN endpoint

2017-01-26 15:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=7374) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=7374) before we can accept your contribution.<br/>**28** out of **29** committers have signed the CLA.<br/><br/>:white_check_mark: bergquist<br/>:white_check_mark: torkelo<br/>:white_check_mark: utkarshcmu<br/>:white_check_mark: DanCech<br/>:white_check_mark: mtanda<br/>:white_check_mark: vitaliyf<br/>:white_check_mark: simnv<br/>:white_check_mark: vaibhavinbayarea<br/>:white_check_mark: Ricky-N<br/>:white_check_mark: leonoff<br/>:white_check_mark: mekalz<br/>:white_check_mark: theisenmark<br/>:white_check_mark: jaxxstorm<br/>:white_check_mark: andrewhowdencom<br/>:white_check_mark: xginn8<br/>:white_check_mark: adrianlzt<br/>:white_check_mark: tomasv<br/>:white_check_mark: connection-reset<br/>:white_check_mark: huydx<br/>:white_check_mark: smalik03<br/>:white_check_mark: rrickardt<br/>:white_check_mark: oliverpool<br/>:white_check_mark: lpic10<br/>:white_check_mark: FFalcon<br/>:white_check_mark: chrisbenti<br/>:white_check_mark: ctide<br/>:white_check_mark: Tepa00<br/>:white_check_mark: ryantxu<br/>:x: James Regovich<hr/>**James Regovich** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-01-26 15:15 UTC, torkelo commented
this needs rebase :)

2017-01-27 07:47 UTC, bergquist commented
master have now been merged into grafana/alerting_hipchat.

Please rebase your changes from grafana/alerting_hipchat if you want to target alerting_hipchat.

2017-01-28 07:31 UTC, torkelo commented
what is the alerting_hipchat branch?

2017-01-28 23:00 UTC, jregovic commented
alerting_hipchat is the branch created for https://github.com/grafana/grafana/issues/6451. My changes add the hook to HipChat.

2017-01-30 06:46 UTC, bergquist commented
@torkelo it was requested the make collaboration easier. 

This PR still need to rebase against the `alerting_hipchat` branch.

2017-01-30 21:44 UTC, jregovic commented
I'm pretty sure I've rebased this correctly. Am I missing something?

2017-02-02 08:09 UTC, bergquist requested changes
The commit author have to be the same as the github user. Otherwise you cannot sign the CLA which is required before we merge any PR

2017-02-02 08:09 UTC, bergquist commented on pkg/services/alerting/notifiers/hipchat_test.go
> +				So(hipchatNotifier.RommId, ShouldEqual, "")
Typo. This doesn't compile.

2017-02-06 22:40 UTC, jregovic commented on pkg/services/alerting/notifiers/hipchat_test.go
> +				So(hipchatNotifier.RommId, ShouldEqual, "")
fixed.

2017-02-07 16:09 UTC, bergquist commented
This is starting to get out of hand :) I suggest you move the code for the alerting notifier to a new branch and create a new pull request that targets the master branch. 

The hipchat branch was created to make collaboeration with others easier but since its only you working on it its much easier to just target the master branch.

Closing this since 97 files changes is way to much to review. But please open a new pull request!

2017-02-07 16:09 UTC, closed without merging