Currency: Add Malaysian Ringgit (RM)
grafana/grafana pull request #74073
Opened 2023-08-30 07:52 UTC by skangmy

Why is this component needed:
The addition of the Malaysian Ringgit (RM) as a currency formatting option is needed to facilitate users in Malaysia or those dealing with the Malaysian Ringgit in their data visualizations. 

[x] Is/could it be used in more than one place in Grafana?

Where is/could it be used?:
The Malaysian Ringgit (RM) formatting option could be used anywhere in Grafana where currency formatting options are provided.

[x] It has a single use case.
[x] It is/could be used in multiple places.

Thanks!

2023-08-30 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=74073) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=74073) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=74073) it.</sub>

2023-09-01 14:32 UTC, L-M-K-B requested changes
Hi @skangmy,
I just checked your changes and they look good to me. 
Unfortunately some checks are failing. In order fix the one about breaking changes please remove the reformatting. The other one is likely to break for external PRs so we should be fine here.

2023-09-02 08:21 UTC, skangmy commented
Hi @L-M-K-B 

I have removed the reformatting as suggested. 

Thanks!

2023-09-04 10:14 UTC, L-M-K-B approved these changes
Thanks @skangmy for contributing to Grafana. 
Your changes are good to go now and I'll take care merging them.

2023-09-04 10:15 UTC, merged