Plugins: Move filter back to
grafana/grafana pull request #74147
Opened 2023-08-31 00:26 UTC by ryantxu

In https://github.com/grafana/grafana/pull/41317 (two years ago! 😬). the filterQuery api was moved to the root datasource api level.  However it is only executed within DataSourceWithBackend

In https://github.com/grafana/grafana/pull/74116 -- the proposal is to execute this in the panel query runner.

It is easy to argue that either approach is a breaking change -- executing somethign that was previously not executed, or a possible type error while developing.  The 2nd seems safer to me

2023-08-31 12:06 UTC, academo requested changes
Even if we put this here by mistake it is still a breaking change, specially if had been here for such a long time.

We should follow the deprecation process.

2023-08-31 12:33 UTC, oshirohugo commented
Just one comment about the docs and usage with `DataSourceWithBackend`

2023-09-01 07:07 UTC, academo approved these changes

2023-09-01 08:30 UTC, oshirohugo approved these changes

2023-09-05 22:34 UTC, merged