Internationalization: Mark up PlaylistEditPage for translations
grafana/grafana pull request #74455
Opened 2023-09-06 14:25 UTC by khushijain21

**What is this feature?**

i18n markup for Playlist edit page

**Which issue(s) does this PR fix?**:
This PR fixes https://github.com/grafana/grafana/issues/74366

2023-09-06 14:28 UTC, khushijain21 commented
Hello, this is my first PR in i18n, let me know if any corrections required

2023-09-06 14:46 UTC, ashharrison90 requested changes
hi @khushijain21 👋 

great start! left some comments to nudge you in the right direction 😉

2023-09-06 14:46 UTC, ashharrison90 commented on public/app/features/playlist/PlaylistEditPage.tsx
> +    text: t('playlist-edit.text', 'Edit playlist'),
```suggestion
    text: t('playlist-edit.title', 'Edit playlist'),
```

2023-09-06 14:46 UTC, ashharrison90 commented on public/app/features/playlist/PlaylistEditPage.tsx
> +        )}
we don't want to wrap the whole `PlaylistForm` in `Trans`, instead we need to go into this file and wrap the individual text items. you can refer to the [checklist in the issue](https://github.com/grafana/grafana/issues/74366) to find which text items need translating

2023-09-07 12:27 UTC, ashharrison90 reviewed
couple of tweaks, otherwise lgtm 🥳

2023-09-07 12:27 UTC, ashharrison90 commented on public/app/features/playlist/PlaylistEditPage.tsx
> +      'playlist-edit.subTitle',
```suggestion
      'playlist-edit.sub-title',
```

2023-09-07 12:27 UTC, ashharrison90 commented on public/app/features/playlist/PlaylistEditPage.tsx
> +            <Trans i18nKey="playlist-edit.errorPrefix">Error loading playlist:</Trans>
```suggestion
            <Trans i18nKey="playlist-edit.error-prefix">Error loading playlist:</Trans>
```
(i realise `errorPrefix` was originally my suggestion, apologies for not suggesting in kebab-case)

2023-09-07 12:27 UTC, ashharrison90 commented on public/app/features/playlist/PlaylistForm.tsx
think we could nest all these under the `playlist-edit` key, so `playlist-form.name-label` would become `playlist-edit.form.name-label`. same comment about making sure these are all in kebab case

2023-09-08 03:01 UTC, ashharrison90 reviewed
just need to update the `addTitle`/`addTag` keys to be kebab case (`add-title-label`, `add-tag-label`, `add-tag-placeholder`) and rerun `yarn i18n:extract`/`yarn i18n:pseudo` and this will be good to merge 👍

2023-09-12 14:24 UTC, ashharrison90 commented
@khushijain21 do you need any further guidance in this PR? 🙂

2023-09-13 08:51 UTC, ashharrison90 approved these changes
looks great! thanks for the contribution @khushijain21 🥳

2023-09-13 09:02 UTC, merged