Logpanel
grafana/grafana pull request #74633
Opened 2023-09-09 07:29 UTC by siddhikhapare

**What is this feature?**

Mark up Logs Panel for translations

**Why do we need this feature?**

Using translation for log panels allows to internationalize and localize the text and messages within  log-related components.

**Who is this feature for?**

For all

**Which issue(s) does this PR fix?**:

Fixes #74305 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-09-11 08:42 UTC, ivanahuckova reviewed
Thanks for your contribution! 🚀 🧡 Before we proceed with the review, would you mind removing the modification made in `public/app/plugins/datasource/influxdb/components/editor/query/influxql/visual/TagsSection.tsx`? We'd like to keep the changes in this pull request confined to the log panel components only.

2023-09-11 18:36 UTC, siddhikhapare commented
@ivanahuckova Sure. I will update it.

2023-09-12 16:56 UTC, matyax requested changes
Thank you for your contribution @siddhikhapare !

There seem to be a few things to change and fix, and also to revert. Please double check that your PR follows what's defined in https://github.com/grafana/grafana/blob/main/contribute/internationalization.md , and if possible double check with a local Grafana instance that the changes are not creating visual bugs.

Here you can find instructions to set up a local Grafana development instance. https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md

2023-09-12 18:06 UTC, siddhikhapare commented on public/app/features/explore/Logs/LogsMetaRow.tsx
> +        <Menu.Item label={t('logs-meta-row.txt-label', 'txt')} onClick={() => downloadLogs(DownloadFormat.Text)} />
@matyax Thanks for your feedback. I am going to add JSON translations. I am working on it. I want to ask that how to translate other languages for logs? I added locally in en (US) format. I used this: https://github.com/grafana/grafana/blob/813ebf988d354bf23e981e00c9c8458995774c21/contribute/internationalization.md

2023-09-12 18:12 UTC, siddhikhapare commented on public/app/features/explore/Logs/LiveLogs.tsx
> -              <span>
@matyax I will update it.

2023-09-12 18:16 UTC, siddhikhapare commented on public/app/features/explore/Logs/LogsMetaRow.tsx
> +      const tooltipContent = t(
@matyax I will remove it.

2023-09-13 08:43 UTC, matyax commented on public/app/plugins/datasource/influxdb/components/editor/query/influxql/visual/TagsSection.tsx
> -          if (value === undefined) {
Just revert the changes 👍

2023-09-22 05:29 UTC, siddhikhapare commented
@matyax @ivanahuckova I found error regarding memory limit while running yarn start in my VM so I have created new setup and  new PR related this log panel issue. https://github.com/grafana/grafana/pull/75262  I value your opinion, so please review this when you can. I will close this PR. Thank you. ![images](https://live.staticflickr.com/65535/53203831812_dae956be03_o.png)

2023-09-22 08:56 UTC, closed without merging

2023-09-22 08:57 UTC, matyax commented
Sounds good @siddhikhapare !