allow setting basic auth headers for prometheus datasource
grafana/grafana pull request #7466
Opened 2017-02-06 14:26 UTC by hagen1778

#6799

2017-02-06 14:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=7466) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=7466) before we can accept your contribution.<br/><hr/>**r.khavronenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-02-06 14:30 UTC, bergquist commented
@hagen1778 the git commit auth have to match your github account. Otherwise you cannot sign the CLA.

2017-02-07 09:19 UTC, bergquist requested changes

2017-02-07 09:19 UTC, bergquist commented on pkg/tsdb/prometheus/prometheus.go
> +	return http.DefaultTransport.RoundTrip(req)
I think the correct thing here would be to call `bat.Transport.Round()` rather then `http.DefaultTransport`.

2017-02-07 09:59 UTC, hagen1778 commented on pkg/tsdb/prometheus/prometheus.go
> +	return http.DefaultTransport.RoundTrip(req)
you are absolutely right

2017-02-07 10:18 UTC, bergquist approved these changes

2017-02-07 10:18 UTC, merged

2017-02-07 10:18 UTC, bergquist commented
Great! Thank you for contributing! :)