Add postgreSQL Flexible Server Monitoring Dashboard
grafana/grafana pull request #74953
Opened 2023-09-14 21:58 UTC by JohnJMartins

**What is this feature?**

This PR adds a dedicated and pre-made dashboard to be embedded in the Azure Monitor data source that is dedicated to monitoring metrics of a PostgreSQL Flexible Server. Along with some basic and varied metric panels at the top of the dashboard that provide insight into total storage, usage, read and write metrics, etc, the dashboard also provides dedicated sections with more in-depth metrics; these include Resource Consumption, Autovacuum metrics, PgBouncer metrics, Enhanced metrics, and Hisotrical metrics. Allmetrics are emitted once every minute and stored for up to 93 days.

**Why do we need this feature?**

This makes it possible and easier for users to keep tabs on metrics for their PostgreSQL Flexible Server usage.

Fixes #

**Special notes for your reviewer:**

2023-09-18 10:48 UTC, aangelisc requested changes
Thank you for the contribution @JohnJMartins! I've requested some changes based on some typos/terminology.

It also seems as if some of the panel rows do not span full-width, do you think you'd be able to adjust them to be full-width (no big deal if this isn't feasible).

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +          "content": "# Azure Database for PostgreSQL Flexible Server - Monitoring Dashboard\r\n#### - Each metric is emitted at a 1-minute interval and has up to 93 days of history.\r\n#### - For co
```suggestion
          "content": "# Azure Database for PostgreSQL Flexible Server - Monitoring Dashboard\r\n#### - Each metric is emitted at a 1-minute interval and has up to 93 days of history.\r\n#### - For a complete list of metrics, refer to [Azure PostgreSQL Monitoring Metrics](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-monitoring)",
```

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +        "description": "Number of total transactions that executed in this database.",
```suggestion
        "description": "Number of total transactions executed in this database.",
```

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +          "content": "#### **NOTE**: While metrics are stored for 93 days, you can only query (in the Metrics tile) for a maximum of 30 days' worth of data on any single chart. If you see a blank cha
```suggestion
          "content": "#### **NOTE**: While metrics are stored for 93 days, you can only query (in the Metrics tile) for a maximum of 30 days worth of data on any single chart. If you see a blank chart or your chart displays only part of metric data, verify that the difference between start and end dates in the time picker doesn't exceed the 30-day interval. After you've selected a 30-day interval, you can pan the chart to view the full retention window.",
```

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +            "description": "Overall state of the back ends",
```suggestion
            "description": "Overall state of the backends",
```

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +            "description": "Sessions by the type of event for which the back end is waiting",
```suggestion
            "description": "Sessions by the type of event for which the backend is waiting",
```

2023-09-18 10:48 UTC, aangelisc commented on public/app/plugins/datasource/azuremonitor/dashboards/postgresFlexibleServer.json
> +            "description": "Indicates if the database is up or not in last 30 days",
```suggestion
            "description": "Indicates if the database is up or not in the last 30 days",
```

2023-09-19 16:36 UTC, JohnJMartins commented
> Thank you for the contribution @JohnJMartins! I've requested some changes based on some typos/terminology.
> 
> It also seems as if some of the panel rows do not span full-width, do you think you'd be able to adjust them to be full-width (no big deal if this isn't feasible).

Hi Andreas, it is not very feasible to have the panel widths extended for this dashboard so I have foregone that change, but I have fixed the issues mentioned in other comments. Please let me know if there is anything else you need me to do!

2023-09-21 10:28 UTC, aangelisc approved these changes
Thank you for updating @JohnJMartins. LGTM!

2023-09-21 10:44 UTC, merged