Security/fix init.d quoting
grafana/grafana pull request #7504
Opened 2017-02-09 08:19 UTC by RichiH

2017-02-09 08:47 UTC, torkelo commented
this looks great! thank you! 

Trying to google why `${VARNAME}` is preferable, nothing relating to security. 

Only that it allows for interpolation like `"${foo}bar"` .  

My impression about the securty issue was that daemon command line options should be quoted, not seeing that change.

2017-02-10 07:51 UTC, RichiH commented
This is approaching a state it can be merged in. Please be advised that I didn't test the script as I don't use init.d any more.

For safety, I am summoning @mirabilos to review what I did.

2017-02-10 11:16 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +DEFAULT=/etc/default/${NAME}
useless

2017-02-10 11:20 UTC, mirabilos requested changes
after some comments, I stopped… this is going nowhere

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +WORK_DIR=${GRAFANA_HOME}
useless

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +CONF_FILE=${CONF_DIR}/grafana.ini
useless

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +DAEMON=/usr/sbin/${NAME}
both useless

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +if [ ! -x ${DAEMON} ]; then
useless **and** does not quote, i.e. insecure

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
>  fi
useless change (was secure before)

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
useless

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +	pid=`pidofproc -p ${PID_FILE} grafana`
useless; also, as long as accent gravis-style command substitution is used, this cannot ever be secured; something like…

    pid=$(pidofproc -p "$PID_FILE" grafana)

… would work.

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +	mkdir -p "${LOG_DIR}" "${DATA_DIR}" && chown "${GRAFANA_USER}":"${GRAFANA_GROUP}" "${LOG_DIR}" "${DATA_DIR}"
useless *and* makes the whole thing *much* harder to read

2017-02-10 11:20 UTC, mirabilos commented on packaging/deb/init.d/grafana-server
> +set -u
OUCH! **WHY?**

2017-02-10 11:23 UTC, RichiH commented
@mirabilos I think you reviewed partial commits and not the final state.

2017-04-07 10:16 UTC, torkelo commented
Since you did not test it I am unsure I can merge this :(

2017-05-17 08:47 UTC, torkelo commented
closing this as contains so many changes that feels unrelated to security and tricky to test all changes

2017-05-17 08:47 UTC, closed without merging