BrowseDashboards: Enable new browse dashboards UI by default
grafana/grafana pull request #75822
Opened 2023-10-02 12:52 UTC by joshhunt

> [!NOTE]  
> FYI - we should only merge this once we're enabled newBrowseDashboards for 100% of Cloud.

**What is this feature?**

Enables the new Browse Dashboards UI by default.

Apart from the easier to use and more performant UI, this change removes the 'General' folder from the frontend, and instead lists dashboards at the root level of the view, after folders. This is because the General folder was never a "real" folder, and so there were lots of inconsistencies with it - it couldn't be renamed or deleted. Permissions could not be managed on it, and alerts could not be stored within the General folder.

**Which issue(s) does this PR fix?**:

Fixes #

2023-10-02 13:02 UTC, ashharrison90 approved these changes
looks great! 🙌

2023-10-02 13:03 UTC, ashharrison90 requested changes
actually i lied, need to rerun the feature toggle tests to regen the documentation correctly 👍

2023-10-02 13:03 UTC, ashharrison90 approved these changes
but then it looks great 😄

2023-10-04 09:12 UTC, ashharrison90 approved these changes
cool 👍

2023-10-05 10:14 UTC, merged

2023-10-27 13:01 UTC, ChrisJBurns commented
Just wanted to add for awareness, that this broke some of our permissions for viewing dashboards. We'd created some dashboards that were being applied into the General folder by default, and because it had `grafana-editor` permissions, non admins could see the dashboards. Now the dashboards are in root, only admins have permissions to see them.