Toggletip: Add support to programmatically close it
grafana/grafana pull request #75846
Opened 2023-10-02 20:00 UTC by adela-almasan

As part of the WIP DashGPT project, we needed to be able to close the `Toggletip` after clicking a button. I've added some changes to reflect that functionality, I'd appreciate feedback. Being optional, I don't believe the change should be disruptive of the current functionality.

https://github.com/grafana/grafana/assets/88068998/9b9dc4ea-15e6-4641-a10c-6f20f14bb9ee

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-02 20:37 UTC, nmarrs approved these changes
LGTM

2023-10-03 15:00 UTC, ashharrison90 requested changes
don't think we would want to do this via an effect. have started a discussion in slack to figure out the best way of handling this 👍

2023-10-03 15:12 UTC, ashharrison90 reviewed
so looking at the [documentation for toggletip](https://internal-ops-us-east-0.grafana.net/design-system/Components/toggletip) i _think_ we'd recommend against putting this kind of stuff in a `Toggletip` altogether. one of the main `don't`s is:
> Do not use to surface actions to users

if we were to add something like this, i think we'd want to do it in the form of a `show` prop similar to `Tooltip` whereby you manually handle the visible state outside of the `Toggletip` component.

2023-10-03 15:14 UTC, staton-hyse11 commented
This seems like a misuse of the `toggletip` component. The use case shows a user having a dialogue with the system, which would point to a modal being more appropriate. Toggletips should not be vehicles for users to configure, edit, or select data on a page. They are primarily used for providing contextual information and/or linking to documentation that will help users gain more information about their task at hand, not really for managing a task themself — if that makes sense. I'm happy to chat through this more if you want.

2023-10-03 15:32 UTC, ivanortegaalba commented
The usage of toogletip here is to take references of leaders in generative AI in the market. Here is an example of Grammarly:
![Captura de pantalla 2023-10-03 a las 17 32 10](https://github.com/grafana/grafana/assets/5699976/0791bcd1-a5c8-4442-8d02-98f80869b3a9)



This "popover" appears to assist you in generating something on a specific input. Opening a modal completely removes the user from the context, and disturbs a lot of the experience. Actually, you create an experience itself about improving a text, where the main task for the user is to autogenerate and refine the result with some feedback.

![image](https://github.com/grafana/grafana/assets/5699976/c701edcf-c341-497f-a88f-d780b154fb35)

2023-10-03 16:26 UTC, torkelo commented
If we are to use this component with forms inside it's a popover and we should use the popover background (primary) like all our other popovers

2023-10-03 16:29 UTC, torkelo commented
For popover reference, TimeRangePicker, ColorPickerPopover can't think of others right now.

2023-10-03 16:48 UTC, staton-hyse11 commented
After discussing with @ivanortegaalba, this use case makes sense for the toggletip. 

We'll look to create a generic popover component in the future to help with use-cases like this and align with the proper background color and as the other popovers use.

2023-10-04 14:25 UTC, ashharrison90 requested changes
> if we were to add something like this, which i think does have value, i think we'd want to do it in the form of a `show` prop similar to `Tooltip` whereby you manually handle the visible state outside of the `Toggletip` component.

this comment still applies ☝️

2023-10-04 16:24 UTC, ivanortegaalba commented
I pushed an update with the new prop @ashharrison90. It should be fine now

2023-10-05 05:55 UTC, nmarrs commented
@ashharrison90 given recent changes / addressing the `show` prop feedback are you comfortable removing (or with us removing) your request for changes on this PR? Thanks!

2023-10-05 06:40 UTC, ashharrison90 approved these changes
lgtm 👍

2023-10-05 06:58 UTC, merged

2023-10-05 16:07 UTC, adela-almasan commented
@torkelo yes - first step here https://github.com/grafana/grafana/pull/76069. I've just added a "custom" theme with the styling we want (primary background) - I think it's less invasive than allowing custom styling and I'm not sure if that's something we want to support right now. cc @ashharrison90