Text component fast path
grafana/grafana pull request #76167
Opened 2023-10-08 02:27 UTC by chauchausoup

**What is this feature?**

Fixes useEffect and Observer calls when not needed.

**Why do we need this feature?**

Make Text component fast.

**Who is this feature for?**

UI 

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/76050

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-09 10:05 UTC, L-M-K-B reviewed
Hi @chauchausoup, Thank you so much for contributing to Grafana again! 
I had a look at your changes and left a couple of comments directly in the code. 
I also ask you to move `getTextStyles` to the end of the file since we try to keep a consistent format for our ui components.

2023-10-09 10:05 UTC, L-M-K-B commented on packages/grafana-ui/src/components/Text/Text.tsx
> +          ref: internalRef,
According to the original code this should be undefined. Is there a reason why you changed it?

2023-10-09 10:07 UTC, L-M-K-B commented
@joshhunt Since you opened the issue I would like your opinion on whether this PR provides all required changes you envisioned.

2023-10-09 15:53 UTC, L-M-K-B requested changes

2023-10-09 15:53 UTC, L-M-K-B commented on packages/grafana-ui/src/components/Text/Text.tsx
>      useImperativeHandle<HTMLElement | null, HTMLElement | null>(ref, () => internalRef.current);
`internalRef` and `useImperativeHandle` is no longer needed here. The ref from `React.forwardRef` can be passed directly to `createElement()` and `TruncatedText`. Instead the `internalRef`/`useImperativeHandle` needs to moved and used in `TruncatedText`.

2023-10-09 15:53 UTC, L-M-K-B commented on packages/grafana-ui/src/components/Text/Text.tsx
> -    // and it should be wrapped in a parent element that is the one that will show the tooltip
This comment should be preserved in the TruncatedText component.

2023-10-10 10:40 UTC, chauchausoup commented
Hello @L-M-K-B 
Thanks for your review.
I have tried to cover most of your comment on this recent commits. 
Here I have decoupled a separate `TruncatedText` component in terms of component tree and in terms of parameters its depending with the parent `Text` component. 
Let me know if any changes needs to be made on the PR.

2023-10-18 16:12 UTC, L-M-K-B reviewed
You are nearly there. There are only two small changes left.
Additionally I need to ask you to get the latest version of main from the Grafana repo and rebase your feature branch. We did some changes and the tests in our build pipeline will fail otherwise.

2023-10-31 06:19 UTC, chauchausoup commented
@L-M-K-B just made the changes. Let me know.

2023-11-01 09:48 UTC, L-M-K-B approved these changes

2023-11-01 13:23 UTC, L-M-K-B commented
Hi @chauchausoup, Thanks a lot for your support. Unfortunately e2e tests in our [CI pipeline](https://drone.grafana.net/grafana/grafana/144244/1/1) are still failing. That's why I need to ask you to merge the current version of main again.

2023-11-02 11:23 UTC, merged