Plugins: Chore: Renamed instrumentation middleware to metrics middleware
grafana/grafana pull request #76186
Opened 2023-10-09 12:22 UTC by xnyo

**What is this feature?**

- Renames the `InstrumentationMiddleware` to `MetricsMiddleware`
- Moves the contextual logger from the `Instrumentation/Metrics middleware` to the `LoggerMiddleware`

**Why do we need this feature?**

Better naming and consistency.

**Who is this feature for?**

Plugins platform.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-09 13:44 UTC, wbrowne approved these changes
LGTM

2023-10-09 13:44 UTC, wbrowne commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +func loggerParams(pCtx backend.PluginContext) []any {
Nit: Would move these functions down below to have the primary method up top

2023-10-09 13:47 UTC, xnyo commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +func loggerParams(pCtx backend.PluginContext) []any {
Done! :smile:

2023-10-09 13:47 UTC, wbrowne approved these changes

2023-10-10 06:44 UTC, andresmgot approved these changes

2023-10-10 09:37 UTC, marefr requested changes
LGTM, but need to make sure `instrumentContext` is always included

2023-10-10 09:37 UTC, marefr commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +	ctx = instrumentContext(ctx, endpoint, pluginCtx)
I think this one should be added even if `cfg.PluginLogBackendRequests` is false. At least that's how it worked before if not mistaken. So maybe `instrumentContext` needs to be its own middleware?

2023-10-10 09:37 UTC, marefr commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +	m.logger.Info("Plugin Request Completed", params...)
Nit. Using `m.Logger.FromContext(ctx)` would automatically give you traceId. However it would also include all params from `instrumentContext` so maybe not optimal. Maybe something to revisit later.

2023-10-10 14:09 UTC, xnyo commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +	ctx = instrumentContext(ctx, endpoint, pluginCtx)
Yes, good spot. I will look into that :+1:

2023-10-11 09:13 UTC, xnyo commented
@marefr Following your review I have done the following changes:
- Added support for `FromContext` in the plugins logger, so we can do:
```go
m.logger.FromContext(ctx).Info(...)
```

- Moved adding the contextual contextual logger into a separate middleware (`ContextualLoggerMiddleware`), which is executed before the `LoggerMiddleware` and regardless of `cfg.PluginLogBackendRequests`

2023-10-11 09:42 UTC, marefr approved these changes
LGTM with some comments

2023-10-11 09:45 UTC, andresmgot commented
The second item of https://github.com/grafana/grafana/issues/73115 should be done after this PR, right? just for tracking it

2023-10-11 10:00 UTC, xnyo commented on pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go
> +	if traceID := tracing.TraceIDFromContext(ctx, false); traceID != "" {
:+1: fixed!

2023-10-11 10:08 UTC, xnyo commented on pkg/plugins/log/logger.go
> +	concreteInfraLogger, ok := d.l.FromContext(ctx).(*log.ConcreteLogger)
I agree it looks weird, but I couldn't find a way around it.

https://github.com/grafana/grafana/blob/7e01dde7621808dfb7a1cc1c30ca631d163a3ad4/pkg/infra/log/log.go#L203

`FromContext` returns a pkg/infra `Logger` interface, but if I replace this method with:

```go
func (d *grafanaInfraLogWrapper) FromContext(ctx context.Context) Logger {
	return d.l.FromContext(ctx)
}
``` 

it doesn't compile:

```
Cannot use 'd.l.FromContext(ctx)' (type "github.com/grafana/grafana/pkg/infra/log".Logger) as the type "github.com/grafana/grafana/pkg/plugins/log".Logger Type does not implement 'Logger' as some methods are missing: New(ctx ...any) Logger
```

This is because the pkg/infra `Logger` has this signature for `New`:

https://github.com/grafana/grafana/blob/025b2f3011821bb7e6ab4781e252f3a1ecd19130/pkg/infra/log/interface.go#L17

But the plugins logger returns a `Logger` interface instead:

https://github.com/grafana/grafana/blob/605af9af8e0671fb7053361de2017b4dd1dd610d/pkg/plugins/log/ifaces.go#L8

So the two interfaces are not compatible

I tried changing the pkg/infra interface so it returns a `Logger` interface rather than a `*ConcreteLogger`, but I got type errors all over the place so I think we can eventually do it as a follow-up work

2023-10-11 10:42 UTC, merged

2023-10-11 13:34 UTC, marefr commented on pkg/plugins/log/logger.go
> +	concreteInfraLogger, ok := d.l.FromContext(ctx).(*log.ConcreteLogger)
Hmm okay

2026-04-10 00:44 UTC, mfeuerstein reviewed
## PR Review — approved

Reviewed 8 files. 0 high-severity issues found. Verdict: approved.

### `pkg/services/pluginsintegration/clientmiddleware/metrics_middleware_test.go` (low)

- Reviewed pkg/services/pluginsintegration/clientmiddleware/metrics_middleware_test.go — looks good

### `pkg/plugins/log/fake.go` (low)

- Reviewed pkg/plugins/log/fake.go — looks good

### `pkg/plugins/log/ifaces.go` (low)

- Reviewed pkg/plugins/log/ifaces.go — looks good

### `pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go` (low)

- Reviewed pkg/services/pluginsintegration/clientmiddleware/logger_middleware.go — looks good

### `pkg/services/pluginsintegration/pluginsintegration.go` (low)

- Reviewed pkg/services/pluginsintegration/pluginsintegration.go — looks good

### `pkg/plugins/log/logger.go` (low)

- Reviewed pkg/plugins/log/logger.go — looks good

### `pkg/services/pluginsintegration/clientmiddleware/metrics_middleware.go` (low)

- Reviewed pkg/services/pluginsintegration/clientmiddleware/metrics_middleware.go — looks good

### `pkg/services/pluginsintegration/clientmiddleware/contextual_logger_middleware.go` (low)

- Reviewed pkg/services/pluginsintegration/clientmiddleware/contextual_logger_middleware.go — looks good