Transformations: Move debug to drawer
grafana/grafana pull request #76281
Opened 2023-10-10 15:35 UTC by codeincarnate

**What is this feature?**

This PR moves the transformation debug interface into a Drawer component for better usability. 

<img width="761" alt="Screenshot 2023-10-10 at 10 33 52 PM" src="https://github.com/grafana/grafana/assets/199847/fca4ef61-cf60-4b4a-8e8c-a9412ebdf90d">

**Why do we need this feature?**

Current transformation debug interface is inline and takes up a large amount of space within an already space constrained interface.

**Which issue(s) does this PR fix?**:

Fixes #74206

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-11 06:53 UTC, mdvictor requested changes
Works great overall! The debug tooltip seems to not hide after closing the drawer though. Not sure how to tackle that tho

https://github.com/grafana/grafana/assets/36818606/3e99ceb0-4695-4b06-b164-e48beaaec6d6

2023-10-11 06:53 UTC, mdvictor commented on public/app/features/dashboard/components/TransformationsEditor/TransformationOperationRow.tsx
> -          disabled={!isOpen}
I think with the removal of this we can also remove the arg in `renderActions` since `isOpen` is now unused.

2023-10-11 14:46 UTC, codeincarnate commented
Nice catch and what and odd issue! I'll see what is going on with the tooltip.

2023-10-13 03:41 UTC, codeincarnate commented
@mdvictor I've been looking into it and I think that the issue with the debug tooltip is broader between tooltip/drawer interaction. I think that's enough to receive it's own PR honestly. WDYT?

2023-10-13 04:10 UTC, codeincarnate commented
Actually saw an issue similar to this where putting a fix broke datalinks 😱. I think we very much want to avoid that outcome and make sure we address the tooltip issue overall 😄

2023-10-13 05:20 UTC, mdvictor commented
Sounds like a good plan, I agree!

2023-10-13 05:20 UTC, mdvictor approved these changes

2023-10-13 06:54 UTC, oscarkilhed approved these changes
Was using the debug extensively yesterday, and this would definitely have helped!

2023-10-27 15:30 UTC, merged