Chore: Remove LegacyForms and gf-form from ElasticSearch DataLink Page
grafana/grafana pull request #76397
Opened 2023-10-12 01:05 UTC by Ciggzy1312

**What is this feature?**

This PR removes all the `gf-form` references and LegacyForm components from the Elastic Search DataLink Page. Below are the images that reflect the change in the UI

The change in width in the input bars is due to the Input component only accepting a number as width instead of a percentage(string). If there is any way to fix that let me know, will follow up with the required changes

**Before UI**
![Screenshot from 2023-10-12 06-13-08](https://github.com/grafana/grafana/assets/65884232/b3c38921-4b27-4382-8dde-fe056725427b)

**After UI**
![Screenshot from 2023-10-12 06-11-26](https://github.com/grafana/grafana/assets/65884232/d4b64444-baa6-4ed6-9d48-379ca0931de0)

**Why do we need this feature?**

Tech Debt

**Who is this feature for?**

Devs

**Which issue(s) does this PR fix?**:

Related to #65513 and #76107 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-13 13:03 UTC, matyax approved these changes
Looks good! Thank you for your contribution!

2023-10-13 13:04 UTC, matyax requested changes
Looks like the test public/app/plugins/datasource/elasticsearch/configuration/DataLinks.test.tsx needs to be updated.

2023-10-14 04:06 UTC, Ciggzy1312 commented
@matyax made the changes

2023-10-16 09:19 UTC, matyax approved these changes

2023-10-16 09:19 UTC, matyax commented
Thank you @Ciggzy1312 , great work!

2023-10-16 10:18 UTC, matyax commented
@Ciggzy1312 Can you maybe merge or rebase main to your branch to see if we can get the CI to succeed?

2023-10-16 10:27 UTC, merged