Docs: add Cloud what's new items to 10.2 what's new
grafana/grafana pull request #76642
Opened 2023-10-16 16:17 UTC by imatwawana

Adds relevant items from _What's new in Grafana Cloud_ to _What's new in Grafana 10.2_ draft PR

Note for reviewers: This PR is just intended to confirm that you want your item added to the 10.2 What's new. If you don't, please let me know.

2023-10-16 16:23 UTC, imatwawana commented
@alexweav - I've tagged you re: the **Grafana OnCall integration for Alerting** item since Brenda is away.

2023-10-16 16:28 UTC, shelldandy approved these changes
I see some todos in there but everything else specially for data sources lgtm

2023-10-16 17:23 UTC, 09jvilla requested changes
Happy to have "Tempo data source: "Aggregate By" Search option to compute RED metrics over spans aggregated by attribute" in the What's New, but I suggested a few changes to make sure that the content was more open source in focus. Please check my links though - I just copy pasted the public URLs rather than trying to use relrefs.

2023-10-16 17:23 UTC, 09jvilla commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +This feature is disabled by default. To enable it, file contact Grafana Support.
```suggestion
This feature is disabled by default. To enable it, use the `metricsSummary` [experimental feature toggle](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/feature-toggles/#experimental-feature-toggles).
```

2023-10-16 17:23 UTC, 09jvilla commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +We've added an **Aggregate By** option to the [TraceQL query editor](https://grafana.com/docs/grafana/<GRAFANA_VERSION>/datasources/tempo/query-editor/traceql-search/#write-traceql-queries-using-sear
```suggestion
We've added an **Aggregate By** option to the [TraceQL query editor](https://grafana.com/docs/grafana/<GRAFANA_VERSION>/datasources/tempo/query-editor/traceql-search/#write-traceql-queries-using-search) to leverage Tempo's [metrics summary API](https://grafana.com/docs/tempo/latest/api_docs/metrics-summary/). You can calculate RED metrics (total span count, percent erroring spans, and latency information) for spans of `kind=server` received in the last hour that match your filter criteria, grouped by whatever attributes you specify.
```

2023-10-16 18:58 UTC, imatwawana commented
> Happy to have "Tempo data source: "Aggregate By" Search option to compute RED metrics over spans aggregated by attribute" in the What's New, but I suggested a few changes to make sure that the content was more open source in focus. Please check my links though - I just copy pasted the public URLs rather than trying to use relrefs.

Those updates look great. Committed!

2023-10-16 19:03 UTC, 09jvilla commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +This feature is disabled by default. To enable it, use the `metricsSummary` [experimental feature toggle](https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/feature-toggles/#experi
@imatwawana -- note that my link has a "next" in there. I'm not sure that's correct.

2023-10-16 19:04 UTC, 09jvilla approved these changes
Approving conditional on this one comment being addressed:
https://github.com/grafana/grafana/pull/76642/files#r1361154597

2023-10-17 08:07 UTC, fabrizio-grafana approved these changes

2023-10-17 14:01 UTC, ktw4071 approved these changes
Looks good for Datadog. Thank you!

2023-10-17 14:01 UTC, alexweav approved these changes

2023-10-17 14:02 UTC, kylebrandt approved these changes

2023-10-17 14:15 UTC, joshhunt approved these changes
🚀

2023-10-17 14:15 UTC, joshhunt commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +### New browse dashboards
Copied across the latest changes for new Browse Dashboards https://github.com/grafana/grafana/pull/76567 👍🏻

2023-10-17 14:40 UTC, harisrozajac commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +Introducing Content Outline in Grafana **Explore**. We recognized the challenges of complex mixed queries, as well as, lengthy logs and traces results, leading to time-consuming navigation and the lo
```suggestion
Introducing Content Outline in Grafana **Explore**. We recognized the challenges of complex mixed queries, lengthy logs and traces results, leading to time-consuming navigation and the loss of context. Content outline is our first step towards seamless navigation from log lines to traces and back to queries ensuring quicker searches while preserving context. Experience efficient, contextual investigations with this update in Grafana Explore. To learn more, refer to the [Content outline documentation](https://grafana.com/docs/grafana/<GRAFANA_VERSION>/explore/#content-outline), as well as the following video demo.
```

2023-10-17 14:43 UTC, evictorero commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +_Generally Available in Grafana Enterprise_
Not only on Enterprise, this will be GA in OSS as well.

2023-10-17 14:48 UTC, imatwawana commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +_Generally Available in Grafana Enterprise_
```suggestion
_Generally Available in Grafana Open Source and Enterprise_
```

2023-10-17 15:06 UTC, harisrozajac commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +Introducing Content Outline in Grafana **Explore**. We recognized that complex mixed queries, as well was lengthy logs and traces results led to to time-consuming navigation and the loss of context.
```suggestion
Introducing Content Outline in Grafana **Explore**. We recognized that complex mixed queries, as well as lengthy logs and traces results led to to time-consuming navigation and the loss of context. Content outline is our first step towards seamless navigation from log lines to traces and back to queries ensuring quicker searches while preserving context. Experience efficient, contextual investigations with this update in Grafana Explore. To learn more, refer to the [Content outline documentation](https://grafana.com/docs/grafana/<GRAFANA_VERSION>/explore/#content-outline), as well as the following video demo.
```

2023-10-17 15:53 UTC, imatwawana commented on docs/sources/whatsnew/whats-new-in-v10-2.md
> +Introducing Content Outline in Grafana **Explore**. We recognized that complex mixed queries, as well was lengthy logs and traces results led to to time-consuming navigation and the loss of context.
Thanks for the catch!

2023-10-17 16:07 UTC, merged