Rename label in TraceQL builder
grafana/grafana pull request #76685
Opened 2023-10-17 12:29 UTC by siddhikhapare

**What is this feature?**

Rename "Duration" to "Span Duration" in the TraceQL builder

**Why do we need this feature?**

Many customers have said they often can't remember if the "Duration" field in the builder filters by trace duration or span duration. Even though there's a helpful tooltip, some users might not want to hover over it.

**Who is this feature for?**

Users

**Which issue(s) does this PR fix?**:

Fixes #76656 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-17 13:12 UTC, adrapereira requested changes

2023-10-17 19:16 UTC, siddhikhapare commented on public/app/features/explore/TraceView/components/TracePageHeader/SpanFilters/SpanFilters.tsx
>              tooltip="Filter by duration. Accepted units are ns, us, ms, s, m, h"
@adrapereira I added it. Thank you for your feedback.

2023-10-17 19:49 UTC, adrapereira approved these changes
LGTM! Thank you!

2023-10-18 07:55 UTC, fabrizio-grafana approved these changes

2023-10-20 09:35 UTC, merged