Documentation: Update Hubot Integration documentation
grafana/grafana pull request #76925
Opened 2023-10-22 02:55 UTC by stephenyeargin

**What is this feature?**

The script package has improved over the years to allow for direct uploading to Slack, etc. This PR updates the documentation to reflect that.

**Why do we need this feature?**

The current documentation says that S3 is required. That is no longer the case.

**Who is this feature for?**

Any user interested in integrating Grafana with Hubot.

**Which issue(s) does this PR fix?**:

None at this time.

**Special notes for your reviewer:**

I would consider this a rather minor improvement.

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-10-22 02:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=76925) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=76925) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=76925) it.</sub>

2023-10-24 19:45 UTC, Eve832 commented
Hey @lwandz13 this is actually for the Hubot data source plugin, can you help push this through? Looks like you'll have to run prettier and attach the required labels

2023-10-24 21:12 UTC, lwandz13 commented
@stephenyeargin What versions of Grafana does this impact?  Just 10.x?

2023-10-24 21:55 UTC, stephenyeargin commented
@lwandz13 The Hubot package will work as far back as v5, accounting for some behavior changes in the v8 API. 😄

2023-10-27 21:13 UTC, lwandz13 requested changes

2023-10-27 21:13 UTC, lwandz13 commented on docs/sources/tutorials/integrate-hubot/index.md
> +This guide will show you how to install and configure the [`hubot-grafana`](https://github.com/stephenyeargin/hubot-grafana) plugin. This plugin allows you to tell hubot to render any dashboard or gr
```suggestion
This guide shows you how to install and configure the [Hubot-Grafana](https://github.com/stephenyeargin/hubot-grafana) plugin. This plugin allows you to tell Hubot to render any dashboard or graph right from a channel in Slack, Basecamp, or any other supported Hubot adapter. The bot will respond with an image of the graph and a link that will take you to the graph.
```

2023-10-27 21:13 UTC, lwandz13 commented on docs/sources/tutorials/integrate-hubot/index.md
> +## Install `hubot-grafana` script
```suggestion
## Install the Hubot-Grafana script 
```

2023-10-27 21:13 UTC, lwandz13 commented on docs/sources/tutorials/integrate-hubot/index.md
> +### Image Uploading
```suggestion
### Image uploading
```

2023-10-27 21:13 UTC, lwandz13 commented on docs/sources/tutorials/integrate-hubot/index.md
> +The `hubot-grafana` plugin requires two environment variables to be set in order to work properly.
```suggestion
The Hubot-Grafana plugin requires two environment variables to be set in order to work properly. 
```

2023-10-30 22:36 UTC, lwandz13 approved these changes
Looks good!  Thank you for contributing!

2023-11-02 13:50 UTC, merged