ShareModal: Implement panel embed tab for scenes
grafana/grafana pull request #77062
Opened 2023-10-24 14:53 UTC by kaydelaney

Implements the panel embed tab for scenes.
See #75526

2023-10-26 10:58 UTC, dprokop requested changes

2023-10-26 12:15 UTC, torkelo commented on public/app/features/dashboard-scene/sharing/SharePanelEmbedTab.tsx
> +  const { uid: dashUid } = dash.useState();
you don't need to use useState here, the uid will not change while this modal is open

2023-11-06 13:10 UTC, kaydelaney commented on public/app/features/dashboard/components/ShareModal/utils.ts
> +  let soloUrl = buildSoloUrl(useCurrentTimeRange, dashboardUid, selectedTheme, panel, range);
oops, thanks for pointing this out! hopefully fixed with the last commit

2023-11-06 16:26 UTC, dprokop approved these changes

2023-11-07 09:19 UTC, merged