feat(public-dashboards): add i18n support
grafana/grafana pull request #77674
Opened 2023-11-05 07:08 UTC by hainenber

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-11-05 07:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=77674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=77674) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=77674) it.</sub>

2023-11-07 21:59 UTC, lucychen-grafana commented
@hainenber, testing your branch in locally and found an issue with missing text under the acknowledgment section. Can you confirm it is same for you? 
![image](https://github.com/grafana/grafana/assets/140550297/d8b236da-ac0d-497e-a218-f306c9086f8a)

2023-11-08 04:09 UTC, lucychen-grafana requested changes
Really good job on adding i18n support, left a couple of comments. Also there are a couple of .tsx files under [ConfigPublicDashboard](https://github.com/grafana/grafana/tree/main/public/app/features/dashboard/components/ShareModal/SharePublicDashboard/ConfigPublicDashboard) missed that also needs to be marked up for translation as part of this story (config modal). 
![image](https://github.com/grafana/grafana/assets/140550297/b7efdf68-ac69-48cd-90b9-a3518be20afe)

2023-11-08 15:30 UTC, hainenber commented on public/app/features/admin/UserListPublicDashboardPage/DashboardsListModalButton.tsx
> +      title={t('dashboard-list-modal-button.mode.public-dashboard.modal-title', 'Public dashboards')}
Thanks! I've fixed in latest commit

2023-11-08 15:45 UTC, hainenber commented on public/app/features/admin/UserListPublicDashboardPage/DashboardsListModalButton.tsx
> +      title={t('dashboard-list-modal-button.mode.public-dashboard.modal-title', 'Public dashboards')}
Thanks for the review! I've fixed this in latest commit. PTAL when you have time

2023-11-08 17:37 UTC, hainenber commented
> @hainenber, testing your branch in locally and found an issue with missing text under the acknowledgment section. Can you confirm it is same for you?

Yes, I managed to fix this in latest commit. PTAL when you have time!

2023-11-10 20:59 UTC, lucychen-grafana reviewed
Can you please also make the changes to [DeletePublicDashboardModal ](https://github.com/grafana/grafana/blob/main/public/app/features/manage-dashboards/components/PublicDashboardListTable/DeletePublicDashboardModal.tsx). Also the [tab title](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/ShareModal/ShareModal.tsx#L61).  Sorry I missed this from previous review

2023-11-10 21:19 UTC, lucychen-grafana commented
> > @hainenber, testing your branch in locally and found an issue with missing text under the acknowledgment section. Can you confirm it is same for you?
> 
> Yes, I managed to fix this in latest commit. PTAL when you have time!

I still have the missing text...which commit fixed it?

2023-11-11 13:05 UTC, hainenber commented
> Can you please also make the changes to [DeletePublicDashboardModal ](https://github.com/grafana/grafana/blob/main/public/app/features/manage-dashboards/components/PublicDashboardListTable/DeletePublicDashboardModal.tsx). Also the [tab title](https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/ShareModal/ShareModal.tsx#L61). Sorry I missed this from previous review

Done! All of them have been marked up with i18n :D. PTAL again

2023-11-11 13:07 UTC, hainenber commented
> > > @hainenber, testing your branch in locally and found an issue with missing text under the acknowledgment section. Can you confirm it is same for you?
> > 
> > 
> > Yes, I managed to fix this in latest commit. PTAL when you have time!
> 
> I still have the missing text...which commit fixed it?

My fault for not pushing the changes :(. It's this [commit](https://github.com/grafana/grafana/pull/77674/commits/3a7a839f9bd5bc6d155572e20aecbfeb6a929b77). It's good on my side, pls help checking if it is like that on your side too. Thanks!

2023-12-19 15:12 UTC, lucychen-grafana commented
Going to finish the work in https://github.com/grafana/grafana/pull/79659

2023-12-19 15:16 UTC, hainenber commented
Go ahead, this has been stale for way too long. I'll close this one off.

2023-12-19 15:17 UTC, closed without merging