InfluxDB: Add support for `>=` and `<=` comparison operators to IQL Query Builder
grafana/grafana pull request #77917
Opened 2023-11-09 10:30 UTC by btasker

**What is this feature?**

Adds support to the InfluxQL Query Editor for the `>=` and `<=` comparison operators

**Why do we need this feature?**

To simplify queries against numeric fields

**Who is this feature for?**

InfluxQL Query Builder users who wish to include WHERE conditions using greater/less than or equal to

**Which issue(s) does this PR fix?**:

Fixes #77916

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-11-09 10:35 UTC, btasker commented
@itsmylife this should be ready for review

2023-11-11 11:56 UTC, itsmylife reviewed
This looks good. Thanks a lot. Would you mind adding some unit tests for this?

2023-11-13 11:21 UTC, btasker commented
Whoops, yes - added

2023-11-14 15:24 UTC, itsmylife commented
There is a unit test failing in `queryUtils`. Could you please take a look at this?
Also a linting error:
```
src/public/app/plugins/datasource/influxdb/influx_query_model.ts
  166:78  error  Expected '!==' and instead saw '!='  eqeqeq
```

2023-11-14 15:38 UTC, itsmylife commented on public/app/plugins/datasource/influxdb/influx_query_model.ts
> +      if ((!operator.startsWith('>') && !operator.startsWith('<')) || operator === '<>') {
👍

2023-11-14 16:52 UTC, bohandley approved these changes
LGTM!

2023-11-14 17:22 UTC, gtk-grafana requested changes
Code looks good but I'm seeing a bug with the inclusivity of the comparison operators. I currently have the `influxdbBackendMigration` feature flag enabled
<img width="1309" alt="image" src="https://github.com/grafana/grafana/assets/109082771/5c5d09e6-1063-409a-a7d7-73de402f0e01">
It looks as though the `<` and `>` operators are inclusive, but not entirely?
<img width="1042" alt="image" src="https://github.com/grafana/grafana/assets/109082771/1750ca91-109a-462f-a6e4-0e1aabe96023">

Also it looks as though the `<=` and `>=` operators aren't entirely inclusive? I would expect `2 >= 2 <= 2 === true`
<img width="1322" alt="image" src="https://github.com/grafana/grafana/assets/109082771/af50dc97-67a8-44ac-a48b-3428858b3668">

@ismail Something we might want to address (in another issue/PR), would be to smooth out the UI in the query builder with custom input.
<img width="722" alt="image" src="https://github.com/grafana/grafana/assets/109082771/a3108a0f-e3df-40a7-bf0e-f30783262ef1">. 
When you're searching against a numeric field we should have better support for custom input, instead of always seeing the "No options found" even if you'd already inserted a custom input.

Another nit that should be addressed in another issue is always getting `<>` as the first suggestion when you type `<` or `>` is annoying. It should be at the bottom, or not included in the dropdown as a suggestion as we already have `!=`
<img width="281" alt="image" src="https://github.com/grafana/grafana/assets/109082771/730636c2-76c4-4c2f-bbe0-36bec932f3a6">

2023-11-14 17:27 UTC, gtk-grafana approved these changes
Actually nevermind! This is already a "problem" on main, so I'm actually fine with merging this in as is. This is a problem with floats, and the rounding of them in the viz. If I compare against the actual values returned by influx, and not what is visualized, this works as expected!

2023-11-14 17:38 UTC, gtk-grafana commented
@btasker no that was a mistake, and I had also left an aggregation in my query which was giving me slighly different values each query 🤦 . After checking against values that aren't changing each query, it works as expected.
Sorry about the false alarm, and thanks again for the great work!

2023-11-14 20:55 UTC, ismail commented
@gtk-grafana You want @itsmylife ;)

2023-11-15 11:21 UTC, itsmylife approved these changes
🚀

2023-11-15 11:21 UTC, merged