Alerting: Add a new plugin for jira service management
grafana/grafana pull request #78275
Opened 2023-11-16 13:43 UTC by akyuznurettin

**What is this feature?**

This PR includes some doc changes for a new alerting plugin: jsm

**Why do we need this feature?**

As Atlassian team, we are implementing some Opsgenie features in Jira Service Management. That is why, we are adding this plugin into Grafana.

**Who is this feature for?**

Jira Service Management customers

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-11-16 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=78275) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=78275) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: akyuznurettin<br/>:x: zekihan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=78275) it.</sub>

2023-11-20 18:04 UTC, chri2547 commented on docs/sources/introduction/_index.md
> +If you're using Grafana Alerting, then you can have alerts sent through a number of different alert notifiers, including PagerDuty, SMS, email, VictorOps, OpsGenie, Jira Service Management or Slack.
```suggestion
Grafana Alerting can send alerts through several different alert notifiers, including PagerDuty, SMS, email, VictorOps, OpsGenie, Jira Service Management, or Slack.
```

2023-11-20 18:05 UTC, chri2547 reviewed
Added a suggestion. @brendamuir will review the alerting specific topics. I reviewed admin and intro. Thank you!

2023-11-22 17:36 UTC, grobinson-grafana requested changes

2023-11-22 17:36 UTC, grobinson-grafana commented on pkg/services/alerting/notifiers/jsm.go
Hi! 👋 I'm afraid this is legacy alerting, which is deprecated and will be removed in Grafana 11. You probably want to update [grafana/alerting](https://github.com/grafana/alerting) instead.

2024-04-10 01:47 UTC, closed without merging