Docs: adds info on location for mute timings
grafana/grafana pull request #78462
Opened 2023-11-21 12:29 UTC by brendamuir

support for locations was missing in the docs - added it in to address https://github.com/grafana/support-escalations/issues/8313

2023-11-21 14:20 UTC, chri2547 commented on docs/sources/alerting/manage-notifications/mute-timings.md
> +A time interval is a specific duration when alerts are suppressed from firing. The duration typically consists of a specific time range along with days of a week, month, or year.
```suggestion
A time interval is a specific duration during which alerts are suppressed. The duration typically consists of a specific time range and the days of the week, month, or year.
```

2023-11-21 14:22 UTC, chri2547 commented on docs/sources/alerting/manage-notifications/mute-timings.md
> +All fields are lists, and at least one list element must be satisfied to match the field. Fields also support ranges using `:` (ex: `monday:thursday`).
```suggestion
All fields are lists; to match the field, at least one list element must be satisfied. Fields also support ranges using `:` (e.g., `monday:thursday`).
```

2023-11-21 14:23 UTC, chri2547 requested changes
a few suggestions

2023-11-22 09:37 UTC, gillesdemey approved these changes
LGTM from my side!

2023-11-27 12:41 UTC, brendamuir commented
Also adds a note in response to: https://github.com/grafana/support-escalations/issues/7418

2023-11-27 13:11 UTC, gillesdemey approved these changes

2023-11-27 13:22 UTC, chri2547 approved these changes

2023-11-27 13:30 UTC, merged