GettingStarted: Put steps in one big carousel
grafana/grafana pull request #78493
Opened 2023-11-21 16:49 UTC by joshhunt

Updates the default dashboard Getting Started panel to put all steps in one big scrollable carousel, with little page buttons.

Fixes an issue made more noticable by docked nav where at certain breakpoints the cards are clipped and unable to scroll.

Part of https://github.com/grafana/grafana/issues/78451

https://github.com/grafana/grafana/assets/46142/bc48d993-ac1b-470b-844f-4c1fd23cc382

2023-11-21 16:49 UTC, joshhunt commented
/deploy-to-hg

2023-11-28 11:16 UTC, joshhunt commented
/deploy-to-hg

2023-11-28 11:59 UTC, joshhunt commented
/deploy-to-hg

2023-11-28 15:44 UTC, ashharrison90 approved these changes
couple of nits, otherwise lgtm 👍 

great job 🙌

2023-11-28 15:44 UTC, ashharrison90 commented on public/app/plugins/panel/gettingstarted/components/Carousel.tsx
> +        // paddingRight: theme.spacing(nextPrevGutter),
commented code (not needed?)

2023-11-28 15:50 UTC, ashharrison90 requested changes
actually i lied, this feels a little funky

https://github.com/grafana/grafana/assets/20999846/77524553-1ca5-4230-90e1-7d17847fc200

steps to repro:
- drag screen smaller than full width of the basic carousel
- click the arrow to go back to basic

feels like it should fully scroll left?

2024-01-02 10:28 UTC, closed without merging

2024-01-02 10:29 UTC, joshhunt commented
I was a bit too ambitious with this change - it's too large, causes too many issues that need resolving. Instead we'll prepare a fix for the exact issue reported.