Chore: use errutil for pluginRepo errors
grafana/grafana pull request #78647
Opened 2023-11-24 14:05 UTC by gamab

**What is this feature?**

At some point while working on https://github.com/grafana/grafana/pull/78211 I rewrote the `pluginrepo`'s error to use `errutil` (since i had to do the same error check for my function fetching the plugin.json from grafana.com).
Now there isn't much value in it since we removed this extra call.  But in case this is something you want I figured let's not loose that work. If it's not something you want, just close the issue :slightly_smiling_face: 

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-11-24 14:14 UTC, gamab commented on pkg/plugins/repo/errors.go
> +	ErrChecksumMismatchBase = errutil.NewBase(errutil.StatusInternal, "plugin.checksumMismatch").
Maybe 422 would be better suited.

2023-11-24 15:11 UTC, andresmgot reviewed
It makes sense to me, letting @marefr to do an additional review since he's been working more with errors

2023-11-24 15:17 UTC, gamab commented on pkg/util/errutil/status.go
> +	// StatusConflict means that the server cannot fulfilling the request
```suggestion
	// StatusConflict means that the server cannot fulfill the request
```

2023-11-30 10:35 UTC, marefr requested changes
Looks great. Just some minor suggestions

2023-11-30 10:35 UTC, marefr commented on pkg/plugins/repo/errors.go
> +	ErrVersionNotFoundBase = errutil.NewBase(errutil.StatusNotFound, "plugin.versionNotFound").
```suggestion
	ErrVersionNotFoundBase = errutil.NotFound("plugin.versionNotFound").
```

2023-11-30 13:20 UTC, marefr approved these changes
LGTM

2023-11-30 14:49 UTC, merged