MySQL: Update documentation around timezone
grafana/grafana pull request #79213
Opened 2023-12-07 12:15 UTC by zoltanbedi

This PR adds a key sentence to the mysql timezone option to make it clear what to do when the database is set to somehting else other than UTC.

**Which issue(s) does this PR fix?**:

Fixes #75825

2023-12-07 12:40 UTC, gabor approved these changes
i think this is a good change.

but in the future i think we could improve it in two directions:
1. maybe literally start the description with something like "you nearly always want to leave this at 00:00" ...
2. (this may be hard).. somehow rewrite the whole text and explain to the user how to set the number based on different scenarios.

2023-12-07 16:03 UTC, lwandz13 commented on docs/sources/datasources/mysql/_index.md
> +| **Session Timezone**          | Specifies the time zone used in the database session, such as `Europe/Berlin` or `+02:00`. Required if the timezone of the database (or the host of the database) is
```suggestion
| **Session Timezone**          | Specifies the timezone used in the database session, such as `Europe/Berlin` or `+02:00`. Required if the timezone of the database (or the host of the database) is set to something other than UTC. Set this to `+00:00` so Grafana can handle times properly. Set the value used in the session with `SET time_zone='...'`. If you leave this field empty, the timezone will not be updated. For more information, see [ MySQL Server Time Zone Support](https://dev.mysql.com/doc/en/time-zone-support.html).                                                                                                                                           |
```

2023-12-07 16:03 UTC, lwandz13 requested changes, later dismissed
Minor nits

2024-01-04 09:05 UTC, jdbaldry commented on docs/sources/datasources/mysql/_index.md
> +| **Session Timezone**          | Specifies the timezone used in the database session, such as `Europe/Berlin` or `+02:00`. Required if the timezone of the database (or the host of the database) is s
I know this partially reverts a previous suggestion but we should prefer "refer to" over "see" (https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#links-and-references).

I also imagine it is going to break `prettier` so feel free to incorporate however you choose.

```suggestion
| **Session Timezone**          | Specifies the timezone used in the database session, such as `Europe/Berlin` or `+02:00`. Required if the timezone of the database (or the host of the database) is set to something other than UTC. Set this to `+00:00` so Grafana can handle times properly. Set the value used in the session with `SET time_zone='...'`. If you leave this field empty, the timezone will not be updated. For more information, refer to [MySQL Server Time Zone Support](https://dev.mysql.com/doc/en/time-zone-support.html).                                                                                                                                          |
```

2024-01-04 09:06 UTC, jdbaldry approved these changes
Approving to unblock but please consider incorporating the suggestion.

2024-01-04 10:28 UTC, merged