Chore: set @grafana/platform-cat as owner of kind-registry related scripts
grafana/grafana pull request #79304
Opened 2023-12-11 11:09 UTC by K-Phoen

This PR updates the ownership of the kind-registry related GitHub actions, since they're exclusively relied on by cog and grok - both of which owned by @grafana/platform-cat

2023-12-11 11:12 UTC, undef1nd approved these changes

2023-12-11 11:14 UTC, spinillos approved these changes

2023-12-11 11:17 UTC, Duologic requested changes
I think this needs to be more nuanced, there are many things that `grafana-as-code` did that do not fall under `platform-cat`, for example moving away from Thema and Cuetsy is not part of Platform, this should be handled within the Grafana department.

2023-12-11 12:29 UTC, K-Phoen commented
@Duologic fair point :)

I updated the PR to update the ownership of the kind-registry related GitHub actions, since they're exclusively relied on by cog and grok (AFAIK).

2023-12-11 12:31 UTC, Duologic approved these changes

2023-12-18 10:51 UTC, tolzhabayev approved these changes

2024-01-08 12:41 UTC, papagian approved these changes

2024-01-08 13:00 UTC, merged