Re-add arm32 builds
grafana/grafana pull request #79496
Opened 2023-12-14 09:11 UTC by mdvictor

**What is this feature?**

Re-enables `armv6` and `armv7` builds for PR, main and downstream pipelines.

**Why do we need this feature?**

Re-enable arm32 builds

Part of https://github.com/grafana/grafana-delivery/issues/370

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-12-14 10:02 UTC, tolzhabayev requested changes
This will not work yet as is, go has to be in version `1.21.4+` (as the bug was fixed only in `1.21.4+`) so I would rather wait with this PR until we have this merged https://github.com/grafana/grafana/pull/79329

2023-12-15 12:06 UTC, mdvictor commented
@tolzhabayev I believe this can continue now?

2023-12-15 13:22 UTC, dsotirakis approved these changes

2023-12-15 13:28 UTC, tolzhabayev reviewed
yes, the version is updated now.

2023-12-15 14:56 UTC, merged