Update data_source.md - to add a mandatory argument required in the datasource query api request body
grafana/grafana pull request #79832
Opened 2023-12-22 11:27 UTC by Keetmalin

This adds a mandatory value required in the request body when querying the datasource API

**What is this feature?**

Updating the HTTP_API Docs for developers

**Why do we need this feature?**

This enables the proper usage of this specific API. (Which is the `query datasource api`). If we try this API without the suggested change in this PR, this API throws an error.

**Who is this feature for?**

All developers using the Grafana Datasource Query API

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2023-12-22 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=79832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=79832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=79832) it.</sub>

2024-01-09 19:57 UTC, Eve832 commented
Hi @Keetmalin, thank you for your contribution, can you please sign the CLA?

2024-01-09 19:58 UTC, Eve832 commented
@josmperez can you please confirm the accuracy of this change or add a reviewer that can?

2024-01-10 19:40 UTC, svennergr requested changes

2024-01-10 19:40 UTC, svennergr commented on docs/sources/developers/http_api/data_source.md
> +         "expr": "kube_pod_info{container="example"}",
Hi @Keetmalin,

this example is a query for the test datasource and the CSV Metric Values scenario, like this: https://play.grafana.org/goto/hnIh4jFSR?orgId=1

Thus, the `expr` property is not needed here.

```suggestion
```

2024-01-10 19:40 UTC, svennergr commented on docs/sources/developers/http_api/data_source.md
> +- **queries.expr** – Specifies the expression or query that needs to run against the datasource.
```suggestion
```

Same as above.

2024-02-26 15:45 UTC, josmperez commented
Hi @Keetmalin - Could you please resolve the comment by @svennergr so that this PR can move along?

2024-05-18 01:48 UTC, closed without merging