Added Descope as an OAuth2 provider
grafana/grafana pull request #80050
Opened 2024-01-04 22:27 UTC by gaokevin1

Added docs for customers of ours that have asked us how to use Descope with Grafana. We wanted to make sure they can easily find these docs on both our website and Grafana's.

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-04 22:35 UTC, gaokevin1 commented
@chri2547 I don't believe this needs to be part of the changelog, but I'm not able to add the label to my PR. Could you do that for me to pass the checks above?

2024-01-05 09:43 UTC, IevaVasiljeva approved these changes
Left some small comments, but otherwise looks good. Thank you for the contribution, we appreciate it!

2024-01-05 09:43 UTC, IevaVasiljeva commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   api_url = "https://api.descope.com/oauth2/v1/userinfo
nit:
```suggestion
   api_url = https://api.descope.com/oauth2/v1/userinfo
```

2024-01-05 09:43 UTC, IevaVasiljeva commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   auto_login = true
nit: I'd keep this to the default value of `false`, and then the user can choose if they want to enable auto login for this integration or not.
```suggestion
   auto_login = false
```

2024-01-23 18:52 UTC, gaokevin1 commented
Hi @IevaVasiljeva, sorry I missed your comments. I made the changes you requested, thank you for approving my PR so quickly. If you could merge this now, that would be great!

2024-01-23 22:09 UTC, lwandz13 requested changes

2024-01-23 22:09 UTC, lwandz13 commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   > **Note:** You can get your Client ID (Descope Project ID) under [Project Settings](https://app.descope.com/settings/project). Your Client Secret (Descope Access Key) can be generated under [Acce
{{% admonition type="note" %}}
You can get your Client ID (Descope Project ID) under [Project Settings](https://app.descope.com/settings/project). Your Client Secret (Descope Access Key) can be generated under [Access Keys](https://app.descope.com/accesskeys).
{{% /admonition %}}

2024-01-23 22:09 UTC, lwandz13 commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +1. Create an Descope Project [here](https://app.descope.com/gettingStarted), and go through the Getting Started Wizard to configure your authentication. You can skip step if you already have Descope
```suggestion
1. Create a Descope Project [here](https://app.descope.com/gettingStarted), and go through the Getting Started Wizard to configure your authentication. You can skip step if you already have Descope project set up.
```

2024-01-23 22:31 UTC, lwandz13 approved these changes
Thanks for your submission @gaokevin1 !!

2024-01-23 22:52 UTC, gaokevin1 commented
@lwandz13 are you going to merge this once all of the checks pass?

2024-01-23 23:06 UTC, lwandz13 commented
@gaokevin1  I need to checkout your branch to run a command, but am having issues.  I'll merge this once I can run that command.

2024-01-24 14:56 UTC, merged