docs: specify HAProxy rewrite considering `serve_from_sub_path` setting
grafana/grafana pull request #80062
Opened 2024-01-05 10:24 UTC by simPod

**What is this feature?**

Updates HAProxy docs

**Why do we need this feature?**

When investigating why bumping SystemJs broke rendering plugin integration I realised I have to use `serve_from_sub_path` set to `true` which requires having no rewrite in proxy server.

**Who is this feature for?**

HAProxy users

**Which issue(s) does this PR fix?**:

Related to https://github.com/grafana/grafana/issues/76180

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-09 20:11 UTC, Eve832 commented
Added folks from the dev team for review, as I am not qualified.

2024-01-23 20:21 UTC, GrafanaWriter commented
@moxious - Can your team take a look and review, please?

2024-01-23 22:35 UTC, josmperez commented
@wbrowne - Looking at https://github.com/grafana/grafana/issues/76180, it appears that the issue this doc was intended to resolve was not reproducable and the perosn who reported the issue found a workaround. Can you confirm that we can close this doc issue?

2024-01-24 08:39 UTC, simPod commented
@josmperez read the issue more carefully please.

If you use serve from subpath, you should not handle serving from subpath in your proxy.

In the issue I have removed subpath rewrite from my nginx. I also did the same with my grafana installations where I use haproxy and I have reflected those changes in the PR.

Compare it to nginx docs where the case is specified. It is missing in haproxy docs now.

2024-01-24 11:43 UTC, wbrowne commented
> @josmperez read the issue more carefully please.
> 
> If you use serve from subpath, you should not handle serving from subpath in your proxy.
> 
> In the issue I have removed subpath rewrite from my nginx. I also did the same with my grafana installations where I use haproxy and I have reflected those changes in the PR.
> 
> Compare it to nginx docs where the case is specified. It is missing in haproxy docs now.

I think this makes sense to do 👍 It may also be worth adding a note of:

>"If you use serve from subpath, you should not handle serving from subpath in your proxy."

somewhere at the top where it specifies the config sample. WDYT?

2024-01-24 15:43 UTC, wbrowne commented
Sorry I more meant at the top of the doc @simPod. @josmperez and I can work together to figure out what makes sense there and get this in a mergeable state.

2024-01-25 09:22 UTC, simPod commented
I've added something to start with. Waiting for input.

2024-01-25 10:23 UTC, wbrowne approved these changes
LGTM. Will let @josmperez have the final look.

Edit: Or @grafana/backend-platform who I believe would be the SMEs here

2024-01-25 20:18 UTC, josmperez approved these changes
Requires a few stylistic changes, but otherwise LGTM in regard to Grafana style. I haven't confirmed the technical accuracy of this PR.

2024-01-25 20:18 UTC, josmperez commented on docs/sources/tutorials/run-grafana-behind-a-proxy/index.md
>  - Include the sub path at the end of the `root_url`.
```suggestion
1. Include the sub path at the end of the `root_url`.
```

2024-01-25 20:18 UTC, josmperez commented on docs/sources/tutorials/run-grafana-behind-a-proxy/index.md
> +- Set `serve_from_sub_path` to `true`, **OR** let proxy rewrite the path for you (see proxy config examples bellow).
```suggestion
1. Set `serve_from_sub_path` to `true`. Or, let proxy rewrite the path for you (refer to examples bellow).
```

2024-01-25 20:18 UTC, josmperez commented on docs/sources/tutorials/run-grafana-behind-a-proxy/index.md
> +If your Grafana configuration does not set `server.serve_from_sub_path` to `true` then you need to add a rewrite rule to `backend grafana_backend` block:
```suggestion
If your Grafana configuration doen't set `server.serve_from_sub_path` to `true`, then you must add a rewrite rule to the `backend grafana_backend` block:
```

2024-01-27 10:31 UTC, simPod commented on docs/sources/tutorials/run-grafana-behind-a-proxy/index.md
> +If your Grafana configuration doen't set `server.serve_from_sub_path` to `true`, then you must add a rewrite rule to the `backend grafana_backend` block:
```suggestion
If your Grafana configuration doesn't set `server.serve_from_sub_path` to `true`, then you must add a rewrite rule to the `backend grafana_backend` block:
```

2024-01-29 15:30 UTC, wbrowne requested changes
Just found a typo. Other than that, LGTM!

2024-01-29 15:30 UTC, wbrowne commented on docs/sources/tutorials/run-grafana-behind-a-proxy/index.md
> +1. Set `serve_from_sub_path` to `true`. Or, let proxy rewrite the path for you (refer to examples bellow).
```suggestion
1. Set `serve_from_sub_path` to `true`. Or, let proxy rewrite the path for you (refer to examples below).
```

2024-01-29 17:29 UTC, wbrowne approved these changes

2024-01-29 23:30 UTC, merged