Chore: Remove gf-form from datasource/loki
grafana/grafana pull request #80117
Opened 2024-01-08 05:00 UTC by khushijain21

Part of #65513 

![image](https://github.com/grafana/grafana/assets/57278642/ca2cddd1-d19a-4ed6-b101-430c657c18c5)

2024-01-09 11:22 UTC, matyax commented on public/app/plugins/datasource/cloud-monitoring/components/AnnotationsHelp.tsx
> -    <div className="gf-form grafana-info-box alert-info">
This is not from the Loki data source, so maybe either revert the change or update the PR title and description please. Thank you!

2024-01-09 11:53 UTC, matyax requested changes
These changes are breaking the query field when you resize it.

2024-01-09 11:53 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiQueryField.tsx
> +        <InlineFieldRow data-testid={this.props['data-testid']}>
This change is breaking the query editor when you resize it.

![imagen](https://github.com/grafana/grafana/assets/1069378/03633980-af29-4858-aaa4-8c64f90a7178)

![imagen](https://github.com/grafana/grafana/assets/1069378/8330c638-91d5-43dd-88cd-8cfd10136e19)

2024-01-09 11:56 UTC, matyax commented
Thank you so much for the contribution @khushijain21 ! Changes to the Loki Query Field component have the potential of breaking the UI in multiple places, so any change requires a very thorough testing. We can continue iterating, or you have the option to skip changes in that file.

2024-01-22 11:23 UTC, matyax commented
Thanks for following this up @khushijain21 ! We will be reviewing as soon as we have capacity.

2024-02-21 10:52 UTC, matyax commented on public/app/plugins/datasource/loki/components/AnnotationsQueryEditor.tsx
> -      <div className="gf-form-group">
![imagen](https://github.com/grafana/grafana/assets/1069378/62b2752c-3118-4fbd-bb37-632772fdffec)

2024-02-21 10:54 UTC, matyax commented on public/app/plugins/datasource/loki/components/LokiOptionFields.tsx
> +    <Stack alignItems="flex-start" gap={0.5} aria-label="Loki extra field">
![imagen](https://github.com/grafana/grafana/assets/1069378/8df8a238-1602-448a-937a-3bed0d3d7850)

2024-02-21 10:56 UTC, matyax commented on public/app/plugins/datasource/cloud-monitoring/components/AnnotationsHelp.tsx
> +    <div className="grafana-info-box alert-info">
![imagen](https://github.com/grafana/grafana/assets/1069378/cbf366c8-649b-48db-8066-482f3c5fa91b)

2024-02-21 10:56 UTC, matyax approved these changes

2024-02-21 11:00 UTC, matyax commented
Thanks for your contribution @khushijain21 . If I may suggest, whenever you make a UI change, please add a few screenshots (ideally before/after) to make reviewing easier, I would appreciate that a lot.

2024-02-21 11:18 UTC, khushijain21 commented
> Thanks for your contribution @khushijain21 . If I may suggest, whenever you make a UI change, please add a few screenshots (ideally before/after) to make reviewing easier, I would appreciate that a lot.

Hello @matyax. Yes right. Will keep that in mind next time

2024-02-21 12:12 UTC, matyax commented
@khushijain21 Would you mind merging the latest main to this branch please?

2024-02-21 14:37 UTC, merged