Grafana: Replace magic number with const var to response status
grafana/grafana pull request #80132
Opened 2024-01-08 11:29 UTC by rlaisqls

The http package's const variable and the magic number card are being mixed when the code indicates the status.

For the prevention of misrepresentation and uniformity, it would be better to use it only as a const variable. Therefore, I have worked on PR for this.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-08 11:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=80132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=80132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=80132) it.</sub>

2024-01-08 12:49 UTC, papagian requested changes
thank you for your contribution! I have spotted some inconsistencies

2024-01-08 12:49 UTC, papagian commented on pkg/services/dashboardimport/api/api.go
> +		return response.Error(http.StatusInternalServerError, "Quota reached", nil)
```suggestion
		return response.Error(http.StatusForbidden, "Quota reached", nil)
```

2024-01-08 12:49 UTC, papagian commented on pkg/services/libraryelements/api.go
> +		return response.Error(http.StatusUnauthorized, dashboards.ErrFolderAccessDenied.Error(), err)
```suggestion
		return response.Error(http.StatusForbidden, dashboards.ErrFolderAccessDenied.Error(), err)
```

2024-01-08 14:32 UTC, rlaisqls commented
I'm sorry I missed something... :( I fixed it now

2024-01-09 09:49 UTC, papagian approved these changes

2024-01-12 09:33 UTC, IevaVasiljeva approved these changes
I've skimmed over the changes, and it looks good to me! Thanks for the refactor!

Are we happy to merge this now @papagian?

2024-01-12 09:36 UTC, papagian commented
> Are we happy to merge this now @papagian?

thanks for checking! there are some missing imports that cause the CI to fail: we need to fix them before merging

2024-01-12 09:38 UTC, IevaVasiljeva commented
Yup, you're right @papagian, was just about to message about it - looks like you need to import the `http` package in `routing.go` @rlaisqls 
```pkg/api/routing/routing.go:11:25: undefined: http```

2024-02-27 16:39 UTC, merged