Azure cloud settings from Grafana Azure SDK
grafana/grafana pull request #80187
Opened 2024-01-09 07:24 UTC by kostrse

This PR demonstrates use of Azure cloud settings from the Grafana Azure SDK.

See https://github.com/grafana/grafana-azure-sdk-go/pull/78.

2024-01-18 19:06 UTC, aangelisc requested changes
I think we only need the backend changes here for now. I'd much prefer to define the appropriate settings in the frontend SDK also to avoid adding them to the Grafana config.

2024-01-18 20:58 UTC, kostrse commented on pkg/api/dtos/frontend_settings.go
> +	Clouds                  []FrontendSettingsAzureCloudDTO `json:"clouds"`
This is not the full cloud configuration, just list of IDs and display names ([here](https://github.com/grafana/grafana/blob/fc0742a0bc48c7abae759eb9a144cfb8988a97ed/pkg/api/dtos/frontend_settings.go#L59-L62)).
And it's being loaded once upon initialization.

Also the same structures will be removed from datasources.

2024-01-18 20:59 UTC, kostrse commented
> I think we only need the backend changes here for now. I'd much prefer to define the appropriate settings in the frontend SDK also to avoid adding them to the Grafana config.

Could you please propose a solution, how frontend would be able to know list of clouds?

2024-01-19 10:37 UTC, aangelisc commented
> Could you please propose a solution, how frontend SDK would be able to know list of clouds?

@kostrse they should be hardcoded. Whilst this will lead to additional maintenance as we will have the list of clouds in two places, it removes an unnecessary piece of data from the Grafana settings. As these constants are specific to Azure data sources the rest of Grafana does not need to be aware of them.

The Azure cloud configuration doesn't change frequently enough where this would be a substantial maintenance burden.

2024-03-29 20:20 UTC, kostrse commented
This PR was pas a prototype, it has been replaced by:
* #83460
* #85415

2024-03-29 20:20 UTC, closed without merging