tag filtering query
grafana/grafana pull request #8021
Opened 2017-04-03 16:28 UTC by InformatiQ

https://github.com/grafana/grafana/issues/4824
by using filtering the tags in the sql query we ensure that the issue of 'LIMIT 1000' does not affect the result (much)
it will still only show less 1000 (unique)dashboards in the case where the tag has 1000+ dashboards

2017-04-03 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=8021) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=8021) before we can accept your contribution.<br/><hr/>**Ramez Hanna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=8021) it.</sub>

2017-04-03 19:41 UTC, torkelo commented on pkg/services/sqlstore/dashboard.go
> +    sql.WriteString(" GROUP BY dashboard.slug HAVING COUNT(dashboard.slug) = ?")
what is this doing here? And wont this require aggregation functions for fields in the select clause, and cause issue with the tag outer join so we do not get all the tags any more?

2017-04-04 14:34 UTC, InformatiQ commented on pkg/services/sqlstore/dashboard.go
> +    sql.WriteString(" GROUP BY dashboard.slug HAVING COUNT(dashboard.slug) = ?")
True, i missed that. I'll give it another shot

2017-04-06 13:07 UTC, InformatiQ commented
could someone look help explain why th etests are failing?

2017-04-07 08:23 UTC, iksaif commented
@InformatiQ  I believe it fails because you need to run gofmt on your files

2017-04-07 08:24 UTC, torkelo commented
could you write down the complete SQL query the code generates depending on different factors? There has be a clearner way to do this. I know we have to have sub queries to do the tag join & filter, but the way it's built here looks unnecessarily complex

2017-04-07 08:25 UTC, iksaif requested changes
Did you check that it works on PostgreSQL and sqlite too ?

2017-04-07 08:25 UTC, iksaif commented on pkg/services/search/handlers.go
> +	//if len(query.Tags) > 0 {
Just remove the code

2017-04-07 08:25 UTC, iksaif commented on pkg/services/sqlstore/dashboard.go
> +  // SELECT x.id, x.title, x.slug, dashboard_tag.term from (SELECT dashboard.id, dashboard.title, dashboard.slug FROM dashboard LEFT OUTER JOIN dashboard_tag on dashboard.id = dashboard_tag.dashboard
Remove this, or add a sentence to explain why it is here.

2017-04-07 08:25 UTC, iksaif commented on pkg/services/sqlstore/dashboard.go
> +		sql.WriteString(`)GROUP BY dashboard.slug HAVING COUNT(dashboard.slug) >= ?) as dashboard
) GROUP BY

2017-04-07 09:25 UTC, InformatiQ commented
The change is only related to tags
if the tags are specified in the query list the query becomes this

SELECT dashboard.id, dashboard.title, dashboard.slug, dashboard_tag.term 
FROM 
    ( SELECT dashboard.id, dashboard.title, dashboard.slug, dashboard_tag.term 
      FROM dashboard 
      LEFT OUTER JOIN dashboard_tag 
          ON dashboard_tag.dashboard_id = dashboard.id 
      WHERE dashboard.org_id=1 
          AND dashboard_tag.term IN ( tags ) 
      GROUP BY dashboard.slug 
      HAVING COUNT(dashboard.slug) >= len(tags)
     ) as dashboard 
INNER JOIN dashboard_tag on dashboard.id = dashboard_tag.dashboard_id 
ORDER BY dashboard.title ASC 
LIMIT 1000;

Else it remains as it was before

2017-04-07 09:28 UTC, InformatiQ commented on pkg/services/sqlstore/dashboard.go
> +		sql.WriteString(`)GROUP BY dashboard.slug HAVING COUNT(dashboard.slug) >= ?) as dashboard
i am closing an earlier parenthese

2017-04-07 09:45 UTC, iksaif commented on pkg/services/sqlstore/dashboard.go
> +		sql.WriteString(`)GROUP BY dashboard.slug HAVING COUNT(dashboard.slug) >= ?) as dashboard
I meant that you should add a space here

2017-04-07 11:58 UTC, daniellee commented
Run `gofmt -s -d ./pkg` to see what gofmt is complaining about.

2017-04-07 12:49 UTC, InformatiQ commented
tested with mysql and sqlite

2017-04-07 15:39 UTC, eddawley commented
I believe this query will fail in postgresql since the subselect is pulling columns not in GROUP BY.  This is non-ANSI compliant behavior that is allowed in mysql/sqlite but I don't think in postgres.  Also the join should be an INNER JOIN.

You'll probably need to go with something like:

```
SELECT dashboard.id, dashboard.title, dashboard.slug, dashboard_tag.term
FROM
( SELECT dashboard.id
FROM dashboard
INNER JOIN dashboard_tag
ON dashboard_tag.dashboard_id = dashboard.id
WHERE dashboard.org_id=1
AND dashboard_tag.term IN ( tags )
GROUP BY dashboard.id
HAVING COUNT(dashboard.id) >= len(tags)
) as ids
INNER JOIN dashboard ON ids.id = dashboard.id
INNER JOIN dashboard_tag on dashboard.id = dashboard_tag.dashboard_id
ORDER BY dashboard.title ASC
LIMIT 1000;
```

2017-04-10 12:30 UTC, InformatiQ commented
I could use some help with the failing test

2017-04-10 12:49 UTC, iksaif commented
```
  * /home/ubuntu/.go_workspace/src/github.com/grafana/grafana/pkg/services/search/handlers_test.go 
  Line 54:
  Expected: '2'
  Actual:   '6'
  (Should be equal)
```

Could you try outputing the results to see what's wrong ?

2017-04-10 14:53 UTC, InformatiQ commented
it actually makes sense to fail.
prior to my patch the tag filtering was hapenning in the code i removed from pkg/services/search/handlers.go 
so now the test is returning the full Hit:List as we are not doing the filtering here

2017-04-10 15:38 UTC, eddawley commented on pkg/services/sqlstore/dashboard.go
> +							WHERE dashboard_tag.term IN (`)
This query is now performing a logical OR on the tags whereas the original one was doing and AND (ie all tags were required).  Search in grafana appears to be ANDs so I think this is incorrect now.

2017-04-10 15:41 UTC, InformatiQ commented on pkg/services/sqlstore/dashboard.go
> +							WHERE dashboard_tag.term IN (`)
the AND is done doing an OR and counting the occurences (see line 150) 
ROUP BY dashboard.id HAVING COUNT(dashboard.slug) >= ?)

2017-04-10 15:49 UTC, eddawley commented on pkg/services/sqlstore/dashboard.go
> +							WHERE dashboard_tag.term IN (`)
Sorry, my mistake.  My quick look just missed that part.

2017-04-12 10:15 UTC, InformatiQ commented
@torkelo is it better now?

2017-04-12 11:08 UTC, iksaif commented
Looks good to me :).

2017-04-28 11:32 UTC, iksaif approved these changes

2017-04-28 11:32 UTC, iksaif commented
@torkelo / @eddawley  what do you think ?

2017-04-28 13:16 UTC, torkelo commented
Is it tested on MySQL porstgtand sqlite? If so this is mergable :)

2017-05-09 15:02 UTC, InformatiQ commented
now it should work on the 3 DBs

2017-05-09 17:22 UTC, torkelo commented
@daniellee think we should look at merging this tomorrow, as it will otherwise cause big melee conflicts with your dashboardnl folders work

2017-05-10 08:13 UTC, daniellee commented
Will merge this after the 4.3.0 release this week so that it will be included in the 4.4.0 release. Looking forward to that merge conflict on the dashboard_folders branch :smiley:

2017-05-31 11:07 UTC, Thib17 commented
Hello @daniellee, since 4.3.0 is released, could we merge this PR ?

2017-06-05 14:55 UTC, daniellee commented
@Thib17 It is in the milestone for 4.4.0 so I will be looking at merging this in the next week or two. I have to test it on all the databases first and see how much it conflicts with coming changes (the search ux is being redone and we are introducing a folders for dashboards).

2017-07-20 11:28 UTC, InformatiQ commented
@daniellee any update on when this is getting merged? i see it is in the 5.0 milestone
could you give an estimate of the time?

2017-07-20 11:55 UTC, torkelo commented
It's already in develop branch, but that branch needs a bit more work before we can merge, maybe mid to late August

2017-08-08 13:00 UTC, torkelo commented
parts of this PR was taken and merged manually with the changes in the develop branch, the search SQL was changed alot with the addition of dashboard folders & permission checks. 

Anyway, closing this. The deveop branch will be merged to master hopefully with in 3-4 weeks.

2017-08-08 13:00 UTC, closed without merging

2017-11-08 08:50 UTC, iksaif commented
What's up with this ? Looks like the bug is still present in the latest version (and this makes search more or less unusable as soon as you have more than 1000 dashboards)