Documentation: Add minimal doc for using own CA
grafana/grafana pull request #80271
Opened 2024-01-10 09:57 UTC by faxm0dem

It's not clear how to advertise the CA chain as there doesn't seem to be an option to use a trusted bundle. It seems to be possible (tested with grafana 9) to concatenate the server certificate with the bundle in the same file.

2024-01-10 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=80271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=80271) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=80271) it.</sub>

2024-01-17 16:13 UTC, chri2547 commented on docs/sources/setup-grafana/set-up-https.md
> +If you want to use your own CA or your organization's and make sure the full chain is advertized by Grafana, make sure your `cert_file` contains your signed certificate followed by the full CA bundle
```suggestion
If you want to use your own CA or your organization's and ensure Grafana advertises the full chain, ensure your `cert_file` contains your signed certificate followed by the full CA bundle chain.
```

2024-01-17 16:25 UTC, chri2547 requested changes
Made a wording suggestion. Thank you for the contribution!

2024-02-28 09:33 UTC, faxm0dem commented
Ping for review/merge, thanks

2024-04-01 14:46 UTC, faxm0dem commented
ping

2024-04-22 18:57 UTC, moxious approved these changes

2024-04-22 18:58 UTC, moxious commented
@chri2547 mergeable from my POV - I corrected backport labels, assuming build is green, go.

2024-05-27 13:32 UTC, faxm0dem commented
ping

2024-06-27 06:39 UTC, faxm0dem commented
Okay folks, sorry to say this but I'm gonna just stop pushing this every month.
Apparently it's not possible for an external dev to improve your documentation. 

Cheers

2024-08-11 01:58 UTC, closed without merging