Alerting: Escape path parameters
grafana/grafana pull request #80504
Opened 2024-01-13 05:06 UTC by SvenKirschbaum

**What is this feature?**

Namespaces and groups of rules in Mimir can contain slashes in their name, which are currently not escaped when loading their configuration, which results in their detailed view being inaccessible in Grafana, as the API request returns 404. This PR ensures that path Parameters are always correctly escaped.

**Which issue(s) does this PR fix?**:

Fixes #76628

**Special notes for your reviewer:**

I am quite unsure whether I have chosen the best way to create the test cases, since I had to do some minor refactoring to make the functions testable in isolation. Would appreciate feedback on this.

2024-01-13 05:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=80504) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=80504) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=80504) it.</sub>

2024-01-25 09:00 UTC, konrad147 commented
/deploy-to-hg

2024-02-02 10:40 UTC, JohnnyQQQQ requested changes
Thanks for the contribution.

You can simplify the tests a bit. Right now you are interfacing the whole proxy and also adding private functions to a public interface.

You can just interface the function that you need for testing e.g. 

```
type requester interface {
	withReq(ctx *contextmodel.ReqContext, method string, u *url.URL, body io.Reader, extractor func(*response.NormalResponse) (any, error), headers map[string]string) response.Response
}
```

Than by default just use the normal proxy to do it

```
type requester interface {
	withReq(ctx *contextmodel.ReqContext, method string, u *url.URL, body io.Reader, extractor func(*response.NormalResponse) (any, error), headers map[string]string) response.Response
}

type LotexRuler struct {
	log log.Logger
	*AlertingProxy
	requester requester
}

func NewLotexRuler(proxy *AlertingProxy, log log.Logger) *LotexRuler {
	return &LotexRuler{
		log:           log,
		AlertingProxy: proxy,
		requester: proxy,
	}
}
```

When testing, you can manually build it and inject a function that asserts your code that is under test.

2024-02-03 22:55 UTC, SvenKirschbaum commented
Thanks for taking a look @JohnnyQQQQ

I adapted the implementation of the tests accordingly.

2024-02-15 12:34 UTC, JohnnyQQQQ commented on pkg/services/ngalert/api/lotex_ruler.go
> +type requester interface {
```suggestion
// The requester is primarily used for testing purposes, allowing us to inject a different implementation of withReq.
type requester interface {
```

2024-02-15 12:35 UTC, JohnnyQQQQ approved these changes
LGTM, thanks for taking care of this, great first contribution 👍

2024-02-15 13:51 UTC, JohnnyQQQQ commented
@SvenKirschbaum if you rebase the build should pass and we can merge.

2024-02-15 18:01 UTC, SvenKirschbaum commented
> @SvenKirschbaum if you rebase the build should pass and we can merge.

Done

2024-02-16 08:43 UTC, merged