Release: Remove latest.json and replace with api call to grafana.com
grafana/grafana pull request #80537
Opened 2024-01-15 11:03 UTC by ashharrison90

**What is this feature?**

- removes `latest.json`
- updates `updatechecker` to call grafana.com to get the latest stable version

**Why do we need this feature?**

- removes the need for manually updating latest.json

**Who is this feature for?**

- grafana release devs

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/48625
For https://github.com/grafana/grafana-delivery/issues/83

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-15 12:08 UTC, matyax approved these changes

2024-01-15 12:13 UTC, zerok requested changes

2024-01-15 12:13 UTC, zerok commented on latest.json
Removing this file right now might leed to some issues in existing installations. IMO this needs  to be deprecated first and only removed after a couple of releases that have the new mechanism in place. The new mechanism will also have to be backported to all supported minor versions 🙂

2024-01-15 13:33 UTC, zerok approved these changes

2024-01-16 11:19 UTC, merged

2024-01-18 18:55 UTC, aangelisc commented
There are references to this file in the Grafana org that'll need to be updated based on this change: https://github.com/search?q=org%3Agrafana%20latest.json&type=code

2024-01-19 07:32 UTC, zerok commented
I've added a ticket to the repository that looks most pressing right now. All the others should not be critical imo. This file has been around far longer than I thought 😄