InfluxDB: Use grafana timeout value for flux queries
grafana/grafana pull request #81252
Opened 2024-01-25 11:40 UTC by itsmylife

**What is this feature?**

Use grafana timeout configuration for flux query calls

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/grafana/issues/29457

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-25 12:12 UTC, marefr requested changes

2024-01-25 12:12 UTC, marefr commented on pkg/tsdb/influxdb/influxdb.go
> +func ProvideService(cfg *setting.Cfg, httpClient httpclient.Provider, features featuremgmt.FeatureToggles) *Service {
You shouldn't use this as a dependency. Rather I think you should read the timeout value from HTTP options retrieved in newInstanceSettings?

2024-01-25 15:23 UTC, marefr approved these changes
LGTM

2024-01-25 16:05 UTC, merged

2024-01-26 07:51 UTC, lars20070 commented
Thanks for the fix! :+1: