feat: datatrails: include metric prefix filter
grafana/grafana pull request #81316
Opened 2024-01-25 22:40 UTC by darrenjaneczek

**What is this feature?**

A category tree is derived from all metric names that fit the current metric search criteria, populating a prefix filter Cascader component.

![image](https://github.com/grafana/grafana/assets/38694490/c36b15a9-0322-4301-9b20-fa69543c9678)

This cascader components allows the user to browse through the remaining metrics through the name-based hierarchy, and select a prefix filter to further narrow down the displayed results.

If the search terms are changed to something too restrictive, an error message will appear:
![image](https://github.com/grafana/grafana/assets/38694490/b2c1a17f-0458-42c5-996f-7d1f5eb6ca60)

**Which issue(s) does this PR fix?**:

- Resolves #79597 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-01-26 17:24 UTC, darrenjaneczek commented
# TODO
- [ ] Have the state be stored and updated with trail history nodes when they are created and restored

2024-01-30 13:40 UTC, darrenjaneczek commented
(working on conflicts. please stand by)

2024-01-30 14:16 UTC, darrenjaneczek commented
> The cascader search doesn't work for me locally, it's supposed to filter the cascader options based on what we write in the input right?

Unfortunately not. The component doesn't seem to perform the search (or doesn't find results). 
So instead, I enabled the ability for the user to enter a custom value because I was unable to just disable typing..

I am planning to revisit the component itself to get a better idea of what's going on with it, and add a few features relevant to this.

2024-01-31 04:34 UTC, darrenjaneczek commented
> The cascader search doesn't work for me locally, it's supposed to filter the cascader options based on what we write in the input right?

I found a way to fix the Cascader to work closer to the way we expect.
- https://github.com/grafana/grafana/pull/81316/commits/a91a0b3fcb5b67a99da431e798c2ee93ec746556

2024-01-31 13:51 UTC, adrapereira requested changes
This is a great change! It greatly improves the navigation of the available metrics.
Left a couple of comments around where to store the intermediate lists of metrics.

Also found that the UI hangs while searching with the latest PR, it would be nice if we could debounce the search call somehow but I won't block this PR with it.

2024-01-31 14:25 UTC, darrenjaneczek commented on public/app/features/trails/MetricSelectScene.tsx
> +  metricsAfterFilter?: string[];
If they are in state, I can trust React will be using the current values when I call *.useState().

I had experienced subtle bugs previously of things not updating when accessing object properties.

I would have to verify if it works fine as class variables. Perhaps we can explore that after merge.

2024-01-31 14:33 UTC, adrapereira approved these changes

2024-01-31 14:33 UTC, merged