K8s/Folders: Add all features to k8s endpoints
grafana/grafana pull request #81858
Opened 2024-02-05 05:50 UTC by ryantxu

This exposes everything currently accessible under `/api/folders/...` in the k8s backed group.

Next up -- a frontend feature toggle to use this endpoint rather than /api/folders

2024-02-05 05:52 UTC, ryantxu commented on pkg/registry/apis/folders/sub_move.go
> +		f, err := r.service.Move(ctx, &folder.MoveFolderCommand{
I am not sure we need this syntax sugar on top of a regular PATCH updating the folder 🤔 

https://github.com/grafana/grafana/blob/31dd3f8fa887ec46d801f623356cbd6c7b4c437d/pkg/registry/apis/folders/legacy_storage.go#L225

ya, i'll remove it

2024-02-05 05:54 UTC, ryantxu commented on pkg/registry/apis/folders/register.go
> -	storage[resourceInfo.StoragePath("children")] = &subChildrenREST{b.folderSvc}
children was the same as List (with a folder specified)

2024-02-05 08:53 UTC, papagian reviewed
I'm trying to test it but I cannot see the k8s APIs in the swagger editor even though I have set `grafanaAPIServer` and `grafanaAPIServerWithExperimentalAPIs` as suggested in #78091
do you happen to know why?

2024-02-05 08:53 UTC, papagian commented on pkg/registry/apis/folders/sub_access.go
> +	}
currently we don't need this given the folder service `Get()` [checks the access to the folder](https://github.com/grafana/grafana/blob/ec5bc7c4ab5396ee68f8851de50957a8f578e783/pkg/services/folder/folderimpl/folder.go#L204)
however, probably in the future we will

2024-02-05 16:05 UTC, ryantxu commented
@papagian -- I'm running with:
```
app_mode = development 

[feature_toggles]
grafanaAPIServerWithExperimentalAPIs = true
```

And then look here:
http://localhost:3000/swagger?urls.primaryName=folder.grafana.app%2Fv0alpha1
http://localhost:3000/openapi/v3/apis/folder.grafana.app/v0alpha1

<img width="1095" alt="image" src="https://github.com/grafana/grafana/assets/705951/1cf7c715-90ba-453f-b763-87fb73d125e9">

2024-02-05 17:05 UTC, papagian requested changes
I have tested and `counts` sub-resource works as expected that for the `access` need to set also the `OrgID`

2024-02-05 17:05 UTC, papagian commented on pkg/registry/apis/folders/sub_access.go
> +		UID:          &name,
without setting the `OrgID` it fails with `folder not found`:
```suggestion
		UID:          &name,
		OrgID:        ns.OrgID,
```

2024-02-06 09:11 UTC, papagian approved these changes
The present changes LGTM

I have noticed an swagger issue with the update endpoint: it does not set the `Content-Type` as a result the request fails:
<img width="1308" alt="Screenshot 2024-02-06 at 11 00 04 AM" src="https://github.com/grafana/grafana/assets/1632407/b0b09ed3-fc40-4155-9011-fd906ac6b729">

also, when I try it by setting the `Content-Type` properly it fails with a different error (not sure why):

```shell
% curl -X 'PUT' \
  'http://admin:admin@localhost:3000/apis/folder.grafana.app/v0alpha1/namespaces/default/folders/gen-783b1d42-71bb-4e27-a897-e221175bfdb7' \
  -H 'Content-Type: application/json' \
  -H 'accept: application/json' \
  -H 'Content-Type: */*' \
  -d '{
  "apiVersion": "folder.grafana.app/v0alpha1",
  "kind": "Folder",
  "metadata": {},
  "spec": {
   "title": "updated folder"
  }
}'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the name of the object (gen-783b1d42-71bb-4e27-a897-e221175bfdb7 based on URL) was undeterminable: name must be provided",
  "reason": "BadRequest",
  "code": 400
}% 
``` 



</p>
</details>

2024-02-06 15:09 UTC, ryantxu commented
Have you tried only sending one content type?  I bet the second one is confusing things
``` 
  -H 'Content-Type: application/json' \
  -H 'Content-Type: */*' \
```

2024-02-06 15:09 UTC, merged