VizTooltips: Use global portal
grafana/grafana pull request #81986
Opened 2024-02-06 16:08 UTC by leeoniya

this refactors `newVizTooltips` to use a global portal for tooltips and annotation editor/infotip. this fixes a number of tricky z-index issues with portalling tooltips into the panels, especially with shared tooltips, but also with the panel resize-handle in each panel appearing on top of the tooltips.

this also removes the condition to use old tooltips for dashboards with shared tooltip mode. the new behavior is to always use Multi/All mode for tooltips in synced panels.

there will be a follow-up PR to revert previous z-index changes we did in dashboards and scenes that were needed for panel-local portalling:

1. descending z-index:
  - https://github.com/grafana/grafana/pull/75328
  - https://github.com/grafana/grafana/pull/76675
  - https://github.com/grafana/scenes/issues/366
2. boostZIndex (LayoutContext):
  - https://github.com/grafana/grafana/pull/80116
  - https://github.com/grafana/scenes/pull/530

we could potentially revert https://github.com/grafana/grafana/pull/75499, but i think that can stay in place.

2024-02-21 13:45 UTC, torkelo approved these changes
@leeoniya tested this and works great and now is above the resize handle :) 

And the performance for the shared tooltip mode seems really good  (all move very smoothly)

2024-02-23 04:36 UTC, codeincarnate commented
Getting an error with this enabled in certain conditions in which it appears to be causing some overflow causing the global scrollbar to flicker. See screen recording:

https://github.com/grafana/grafana/assets/199847/b5cecc2a-31a0-4545-a9d3-38746a6fab06

2024-02-23 04:36 UTC, codeincarnate requested changes
See comment with video :confounded:

2024-02-23 04:36 UTC, codeincarnate commented on public/app/core/components/TimelineChart/timeline.ts
> +    qt.get(cx, 0, uPlot.pxRatio, 1e4, (o) => {
Would be nice to have a short comment explaining this chunk

2024-02-23 06:58 UTC, leeoniya commented on packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin2.tsx
> +  if (portalRoot.current == null) {
i prefer to use `== null` in all cases unless i need to discern between null and undefined, which is basically never.

2024-02-23 07:06 UTC, leeoniya commented
> Getting an error with this enabled in certain conditions

what error are you getting?

the occasional flicker is known, but i want to leave the fix for later as it's not a 1-liner - i think we need to render the tooltip initially with `visibility: hidden`, then check viewport overlap and re-render again with `visibility: visible` after adjusting position...or something. not sure exactly yet but dont want to hold up this pr on it.

2024-02-23 17:41 UTC, codeincarnate approved these changes
No worries on the error then, it can be in a follow up PR

2024-02-23 21:19 UTC, adela-almasan approved these changes
⭐

2024-02-23 22:18 UTC, merged