Viz: Fix loading bar shifts text
grafana/grafana pull request #82218
Opened 2024-02-09 00:51 UTC by ZuperZee

**What is this feature?**

Fixes an issue when loading bar renders it shifts text.

Notice the red text above the bar graph as it's the most noticeable in the gif below.
Before:
![before-fix-loading-bar-text-blur](https://github.com/grafana/grafana/assets/39485579/84840cb9-ca7b-4a95-92d7-a3cc346d44dc)

After:
![fix-loading-bar-text-blur](https://github.com/grafana/grafana/assets/39485579/f4d4092c-a199-4bb2-8c69-cfd3db9b61d0)

**Why do we need this feature?**

Stops the shifting of text.
The shifting of text almost looks blurry, which makes it harder to read.

**Who is this feature for?**

Most would probably not notice, as it's pretty obscure and only seems to happen on Chromium based browsers.
It happens for any panel with some colored text (usually red-ish).

The main group would be those who uses https://github.com/gapitio/gapit-htmlgraphics-panel, as it's was very visible on SVG text elements.

**Which issue(s) does this PR fix?**:

Fixes #82214

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-03-06 09:41 UTC, torkelo commented
@ZuperZee I am unable to replicate this, using bar gauge that looks like this with a slow query the text above the bars is unaffected by the loading state 
 
![Screenshot 2024-03-06 at 10 40 48](https://github.com/grafana/grafana/assets/10999/400c09af-124d-4b01-890c-f60bcb28119f)

2024-03-06 10:04 UTC, ZuperZee commented
@torkelo which browser did you try it on? I've been able to replicate this on Windows and Linux/Ubuntu with Chrome, Edge, and Brave browsers.
The bug is not in Firefox.

2024-03-11 15:35 UTC, torkelo commented
@ZuperZee a few people have tested on osx and windows with chrome and Edge without being able to replicate.

2024-03-25 21:53 UTC, codeincarnate requested changes
I've tried this out and was unfortunately couldn't really see any substantial difference. Do you have a test case dashboard available? That would help us determine what's going on in this case 😄

2024-03-25 22:04 UTC, ZuperZee commented
Issue https://github.com/grafana/grafana/issues/82214 has a panel JSON that you can use.
I'll create a dashboard tomorrow with a few more examples. There is some very noticeable line shifting when using SVG paths that I can make tomorrow. (It's a little late now :D).

I'll add it to the issue page (it might be more appropriate) and @ you there when I'm finished with the examples.

2024-04-04 05:34 UTC, ZuperZee commented
@codeincarnate @torkelo, just to let you know, I did add a few more dashboards to the issue: https://github.com/grafana/grafana/issues/82214#issuecomment-2020304134.
If it helps, I could also get more people to record it. I can also hop on a call or something to showcase the issue.

2024-04-04 22:19 UTC, codeincarnate commented
Hey @ZuperZee thanks for the extra info. I'll be taking a look again either tomorrow or early next week 😄

2024-04-17 21:07 UTC, ZuperZee commented
Closing as it's fixed by a different PR.
Info in the issue: https://github.com/grafana/grafana/issues/82214#issuecomment-2062325984

2024-04-17 21:07 UTC, closed without merging