Provisioning datasources auto deletion
grafana/grafana pull request #83034
Opened 2024-02-18 16:36 UTC by mikelv92

**What is this feature?**

This PR makes it possible to delete a provisioned datasource by simply deleting it from the provisioning yaml file, or by deleting the yaml file.

**Why do we need this feature?**

Currently, you have to manually add a section to delete data sources, this should all happen automatically. 

**Who is this feature for?**

This feature is for users that provision datasources in yaml files and want to delete them automatically.

**Which issue(s) does this PR fix?**:

Fixes #12875

**Special notes for your reviewer:**

Steps to test it:
- Create a provisioned datasource
- Start grafana: The datasource will show up in the list of datasources
- Delete the datasource from the yaml file or delete the provisioning yaml file
- Restart grafana: The datasource should also be deleted

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-03-20 10:00 UTC, mikelv92 commented
@wbrowne @andresmgot @oshirohugo @papagian @diegommm @yangkb09 Could you please review this PR? :) Or maybe it is no longer needed?

2024-03-20 12:41 UTC, andresmgot commented
@grafana/backend-platform can correct me if I am wrong but I don't think we want to do this anymore. This would unexpectedly start deleting datasources from many instances with no path to recover them. My +1 would be to keep the current behavior and _only_ delete datasources that are explicitly marked for deletion.

2024-03-22 10:47 UTC, bjornfor commented
> This would unexpectedly start deleting datasources from many instances with no path to recover them. 

Who provisions from a _temporary_ file? In my setups, the provisioning file is the single source of truth, and it's in git.

And I've been waiting for this fix for years.

2024-03-22 11:33 UTC, andresmgot commented
> Who provisions from a _temporary_ file? In my setups, the provisioning file is the single source of truth, and it's in git.

I understand your use case but there is also the use case of people creating datasources through provisioning files that don't  expect them to be deleted when provisioning other datasources from a file that happens to be in the same path.

If we want to move forward with this, the default behavior should remain as it is, to avoid breaking changes. My suggestion is to include a new parameter (e.g. `prune`), that if enabled, will delete the datasources if they no longer appear:

```yml
apiVersion: 1

prune: true
datasources:
  - name: PostgreSQL
    type: postgres
    ...
```

2024-03-27 08:21 UTC, mikelv92 commented
@andresmgot Could you please review again if you have time? 🙂

2024-04-01 12:03 UTC, andresmgot reviewed
Thanks @mikelv92. I have done a first round of review but we would need to get more CODEOWNERs eyes here.

2024-04-01 12:03 UTC, andresmgot commented on pkg/services/provisioning/datasources/datasources.go
> +			willExistAfterProvisioning[key] = false
You are not using the provision path in order to differ if a datasource should be deleted or not. I don't think it's actually needed. You can just use `is_prunable` and remove `provisionedFrom` from the model. A datasource marked to be pruned can be deleted whenever it does not appear anymore, regardless of the provision file path.

2024-04-01 12:03 UTC, andresmgot commented on pkg/services/sqlstore/migrations/datasource_mig.go
> +		Name: "is_prunable", Type: DB_Bool, Nullable: false, Default: "0",
I believe this could be nullable.

2024-04-02 06:26 UTC, mikelv92 commented
Thanks for the review @andresmgot . I made the changes according to your comments :)

2024-04-02 14:11 UTC, andresmgot reviewed
Thanks, one comment here. Also, you have some[ lint issues](https://drone.grafana.net/grafana/grafana/170083/2/6) (you can run the check with `make lint-go`).

2024-04-03 06:07 UTC, mikelv92 commented on pkg/services/datasources/service/store.go
> +			IsPrunable: 	 cmd.IsPrunable,
Thanks! I added it

2024-04-03 06:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=83034) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=83034) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mikelv92<br/>:x: Mikel Vuka<br/><hr/>**Mikel Vuka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=83034) it.</sub>

2024-04-03 11:12 UTC, andresmgot reviewed
LGTM with a comment, thanks!

2024-04-03 11:12 UTC, andresmgot commented on pkg/services/datasources/models.go
> +	IsPrunable        bool              `xorm:"is_prunable"`
this needs to be ignored for swagger (as for example, `BasicAuthPassword`)

2024-04-03 19:10 UTC, marefr requested changes
Thanks. Some minor things left, see comments. In addition, would be nice if you can update the [documentation](https://github.com/grafana/grafana/blob/main/docs/sources/administration/provisioning/index.md#data-sources) as well.

2024-04-05 10:03 UTC, andresmgot reviewed
Some documentation comments here, thanks!

2024-04-05 10:03 UTC, andresmgot commented on docs/sources/administration/provisioning/index.md
> +> This `prune` parameter is available only in apiVersion 1
It's more relevant to specify the Grafana version. Also the format is different:

```suggestion
{{% admonition type="note" %}}
The `prune` parameter is available in Grafana v11.1 and higher.
{{% /admonition %}}
```

2024-04-05 10:03 UTC, andresmgot commented on pkg/services/datasources/models.go
> +	IsPrunable      bool
You also need to add the comment  `swagger:ignore` here and in `UpdateDataSourceCommand`

2024-04-05 12:55 UTC, jdbaldry reviewed
I have limited suggestions for the Go code to comments and variable naming consistency rather and haven't actually reviewed the code.

2024-04-05 12:55 UTC, jdbaldry commented on docs/sources/administration/provisioning/index.md
> +prune: true
```suggestion
# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true
```

2024-04-05 12:55 UTC, jdbaldry commented on pkg/services/datasources/datasources.go
> +	// GetPrunableProvisionedDataSources gets all provisioned datasources that can be pruned.
```suggestion
	// GetPrunableProvisionedDataSources gets all provisioned data sources that can be pruned.
```

2024-04-05 12:55 UTC, jdbaldry commented on pkg/services/datasources/fakes/fake_datasource_service.go
> +	}
nit: consistent with the two word data source in `s.DataSources`

```suggestion
	for _, dataSource := range s.DataSources {
		if dataSource.IsPrunable {
			dataSources = append(dataSources, dataSource)
		}
	}
```

2024-04-05 12:55 UTC, jdbaldry commented on pkg/services/datasources/service/store.go
> +// GetPrunableProvisionedDataSources returns all datasources that can be pruned
```suggestion
// GetPrunableProvisionedDataSources returns all data sources that can be pruned
```

2024-04-05 12:55 UTC, jdbaldry commented on pkg/services/datasources/service/store_test.go
> +		t.Run("Get prunable datasources", func(t *testing.T) {
```suggestion
		t.Run("Get prunable data sources", func(t *testing.T) {
```

2024-04-05 12:55 UTC, jdbaldry commented on pkg/services/provisioning/datasources/config_reader_test.go
> +	t.Run("Delete datasources when removing them from provision files", func(t *testing.T) {
```suggestion
	t.Run("Delete data sources when removing them from provision files", func(t *testing.T) {
```

2024-04-08 08:38 UTC, andresmgot approved these changes
LGTM! Thanks

2024-04-08 08:41 UTC, jdbaldry approved these changes
docs LGTM

2024-04-08 09:43 UTC, marefr approved these changes
LGTM

2024-04-08 09:45 UTC, merged