AzureMonitor: Update docs for current user authentication
grafana/grafana pull request #83440
Opened 2024-02-26 19:50 UTC by aangelisc

Updates documentation to provide additional detail on current user authentication in Azure Monitor.

Part of https://github.com/grafana/grafana/pull/81918

2024-02-27 04:17 UTC, taleena reviewed
Sent a few suggestions questions via Slack, otherwise looks good, can approve after reading through that. 👍

2024-02-27 15:43 UTC, taleena approved these changes
Changes reviewed, additions look good, thank you!

2024-03-06 14:30 UTC, adamyeats approved these changes

2024-03-06 14:39 UTC, lwandz13 requested changes, later dismissed

2024-03-06 14:39 UTC, lwandz13 commented on docs/sources/datasources/azure-monitor/_index.md
> +**Note: The `oauthPassThru` property is required for current user authentication to function. Additionally, `disableGrafanaCache` is necessary to ensure cached responses to resources users do not hav
```suggestion
{{< admonition type="note" >}}
The `oauthPassThru` property is required for current user authentication to function. Additionally, `disableGrafanaCache` is necessary to ensure cached responses to resources users do not have access to in Azure are not returned.
{{< /admonition >}}
```

2024-03-06 14:39 UTC, lwandz13 commented on docs/sources/datasources/azure-monitor/_index.md
> +**Note: Cloud names for current user authentication differ from the above. The public cloud name is `AzureCloud`, the Chinese national cloud name is `AzureChinaCloud`, and the US Government cloud nam
```suggestion
{{< admonition type="note" >}}
Cloud names for current user authentication differ from the above. The public cloud name is `AzureCloud`, the Chinese national cloud name is `AzureChinaCloud`, and the US Government cloud name is `AzureUSGovernment`.
{{< /admonition >}}
```

2024-03-06 14:39 UTC, lwandz13 commented on docs/sources/datasources/azure-monitor/_index.md
> +**Note: This feature is experimental and subject to change or removal. Aspects of Grafana may not work as expected when using this authentication method.**
```suggestion
{{< admonition type="note" >}}
This feature is experimental and subject to change or removal. Aspects of Grafana may not work as expected when using this authentication method.
{{< /admonition >}}
```

2024-03-06 14:39 UTC, lwandz13 commented on docs/sources/datasources/azure-monitor/_index.md
> +**Note: To configure fallback service credentials the [feature toggle][configure-grafana-feature-toggles] `idForwarding` must be set to `true` and `user_identity_fallback_credentials_enabled` must be
```suggestion
{{< admonition type="note" >}}
To configure fallback service credentials the [feature toggle][configure-grafana-feature-toggles] `idForwarding` must be set to `true` and `user_identity_fallback_credentials_enabled` must be enabled in the [Azure configuration section][configure-grafana-azure] (enabled by default when `user_identity_enabled` is set to `true`).
{{< /admonition >}}
```

2024-03-12 14:36 UTC, merged