InfluxDB: add configuration option for enabling insecure gRPC connections
grafana/grafana pull request #83834
Opened 2024-03-04 14:45 UTC by jmickey

**What is this feature?**

Adds an option in the `SQL` query language configuration for InfluxDB to skip TLS security on gRPC connections for Flight SQL.

**Why do we need this feature?**

InfluxData offers a Kubernetes deployment of V3 called "Clustered", when deployed alongside Grafana and using AWS LoadBalancers to terminate TLS attempting to connect to the cluster service endpoint for InfluxDB fails due to a lack of TLS connection when using the "SQL" Query Language type.

**Who is this feature for?**

InfluxDB v3 Clustered users.

**Which issue(s) does this PR fix?**:

Fixes #83732

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-03-04 14:51 UTC, jdbaldry reviewed
Docs look fine to me.

2024-03-11 09:41 UTC, itsmylife requested changes
Thanks for the PR. It looks great. 
Just a few nits. 
After that it is good to go.

2024-03-11 09:41 UTC, itsmylife commented on public/app/plugins/datasource/influxdb/components/editor/config/InfluxSQLConfig.tsx
> +      <Field horizontal label={<InlineLabel width={WIDTH_SHORT}>Insecure gRPC</InlineLabel>} className={styles.horizontalField}>
```suggestion
      <Field horizontal label={<InlineLabel width={WIDTH_SHORT}>Insecure Connection</InlineLabel>} className={styles.horizontalField}>
```

2024-03-11 09:41 UTC, itsmylife commented on public/app/plugins/datasource/influxdb/components/editor/config/InfluxSQLConfig.tsx
> +          value={jsonData.insecureGrpc}
```suggestion
          value={jsonData.insecureGrpc ?? false}
```

2024-03-11 09:41 UTC, itsmylife commented on docs/sources/datasources/influxdb/_index.md
> +| **Insecure gRPC** | Disable gRPC TLS security.                                                                                                                                 |
```suggestion
| **Insecure Connection** | Disable gRPC TLS security.                                                                                                                                 |
```

2024-03-11 21:32 UTC, jmickey commented
@itsmylife thanks for the review! I've applied the suggestions you made. Much appreciated

2024-03-11 22:05 UTC, itsmylife commented
Could you please run 

- `yarn run prettier:checkDocs` 
- `yarn run prettier:write`

and commit the changes you'll get?

2024-03-12 02:00 UTC, jmickey commented
Done!

2024-03-12 11:09 UTC, itsmylife commented
There was a problem in `main`. That was causing one test to fail always. We've fixed it. Could you please pull the latest `main` and merge into your branch? And then hopefully I will be able to merge this one. Thanks for that tin advance!

2024-03-12 11:09 UTC, itsmylife approved these changes

2024-03-12 12:13 UTC, jmickey commented
No problem! Rebased now.

2024-03-12 12:36 UTC, merged

2024-05-31 14:01 UTC, hiltontj commented
It is not clear to me whether this was released with `11.0.0`. I do _not_ see it on the [release page](https://github.com/grafana/grafana/releases/tag/v11.0.0) for the `v11.0.0` tag, but I do see the changes on the version associated with the `v11.0.0` tag.

2024-06-03 21:24 UTC, itsmylife commented
@hiltontj This is released in `v11.0.0` but somehow in the release page it wasn't mentioned. I am not sure what happened there bu this is in `v11.0.0`. Let me know if there is something else and I'd be happy to help.