Plugin Extensions: Add prop types to component extensions
grafana/grafana pull request #84295
Opened 2024-03-12 14:40 UTC by leventebalogh

### What changed?

- Updated the `getPluginComponentExtensions()` function to receive the component prop types as a generic _(this makes it easier to define extension points with proper typing)_
- Removed the `context` option from the same function _(The contextual information can be passed to the component as props, so we decided to remove this additional option to make the setup less confusing.)_

```ts
// Before
// ---------------------------------
const { extensions } = getPluginComponentExtensions({ extensionPointId });

({ extensions.map(extension => {
  const Component = extension.component as React.ComponentType<{
    foo: string;
  }>;
})})

// After
// ---------------------------------
const { extensions } = getPluginComponentExtensions<{ foo: string }>({ extensionPointId });
```

2024-03-12 20:12 UTC, darrenjaneczek approved these changes
:+1:

2024-03-12 20:37 UTC, darrenjaneczek commented on packages/grafana-runtime/src/services/pluginExtensions/getPluginExtensions.ts
> +// This getter doesn't support the `context` option (contextual information can be passed in as component props)
```suggestion
// This getter doesn't support the `context` option (contextual information can be passed in as component props)
```

whitespace

2024-03-12 21:22 UTC, darrenjaneczek requested changes
Additional type declaration work may need to be done on `configureExtensionComponent`.

```ts
  configureExtensionComponent<Context extends object>(
    extension: Omit<PluginExtensionComponentConfig<Context>, 'type'>
  ) {
    this._extensionConfigs.push({
      ...extension,
      type: PluginExtensionTypes.component,
    } as PluginExtensionComponentConfig);

    return this;
  }
```

and/or the `PluginExtensionComponentConfig` type:

```ts
export type PluginExtensionComponentConfig<Context extends object = object> = {
  type: PluginExtensionTypes.component;
  title: string;
  description: string;

  // The React component that will be rendered as the extension
  // (This component receives the context as a prop when it is rendered. You can just return `null` from the component to hide for certain contexts)
  component: React.ComponentType<{
    context?: Context;
  }>;

  // The unique identifier of the Extension Point
  // (Core Grafana extension point ids are available in the `PluginExtensionPoints` enum)
  extensionPointId: string;
};
```

2024-03-13 07:01 UTC, leventebalogh commented
Very good point, thanks for testing it out @darrenjaneczek 🙌
I will have a look at it and get the typing fixed.

2024-03-14 22:59 UTC, darrenjaneczek approved these changes
The type errors go away after a slight additional change:
- 37e502e

I think the 'levitate breaking change' may be a misfire.

2024-03-18 13:07 UTC, leventebalogh commented
Thanks @darrenjaneczek, I think that fix is legit 👏 I have updated the betterer configs, hopefully they will be fine now.

**Levitate breaking change**
 It's complaining because we have changed the type of the generic for `configureExtensionComponent()`, however I don't think it should break anything, as the props objects should satisfy the previous type declaration of the generic (`object`).

2024-03-18 13:09 UTC, mckn approved these changes
LGTM!

2024-03-18 13:14 UTC, merged