Scenes: Enable live now feature
grafana/grafana pull request #84399
Opened 2024-03-13 17:01 UTC by kaydelaney

Enables the live now feature on scenes dashboards and allows for toggling it on/off in dashboard settings.

2024-03-13 17:27 UTC, ivanortegaalba reviewed
Let's add some tests here! But looks good so far!

2024-03-13 17:27 UTC, ivanortegaalba commented on public/app/features/dashboard-scene/settings/GeneralSettingsEditView.tsx
> +    return sceneGraph.findObject(this._dashboard, (s) => s instanceof behaviors.LiveNowTimer) as behaviors.LiveNowTimer;
I really dislike this from TS :( 

We can avoid casting here if we contemplate the behavior could be `undefined` and in `onLiveNowChange` we check if it is an instance of `behaviors.LiveNowTimer`.

2024-03-13 17:27 UTC, ivanortegaalba commented on public/app/features/dashboard-scene/settings/GeneralSettingsEditView.tsx
> +    }
```suggestion
      const liveNow = this.getLiveNowTimer();
      if(liveNow instanceof behaviors.LiveNowTimer){
            enable ? liveNow.enable() : liveNow.disable();
      } else {
          throw new Error('Live now timer cannot be found.')
      }
    }
```

2024-03-14 15:58 UTC, dprokop requested changes
I think read-only wise this works great, but the live now option is not detected and persisted when changed.

2024-03-21 11:34 UTC, dprokop approved these changes
LGTM

2024-03-21 14:11 UTC, ivanortegaalba approved these changes
💯

2024-03-21 16:57 UTC, merged