Auth: add Dex example to generic OAuth2 documentation
grafana/grafana pull request #84744
Opened 2024-03-19 14:20 UTC by fredrikekre

This patch adds an example configuration for setting up generic OAuth2 authentication using [Dex IdP](https://dexidp.io/).

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-03-19 14:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=84744) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=84744) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=84744) it.</sub>

2024-03-19 18:50 UTC, lwandz13 requested changes

2024-03-19 18:50 UTC, lwandz13 commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   Note that, unlike many other OAuth2 providers, Dex doesn't provide `<client secret>`.
```suggestion
{{< admonition type="note" >}}
Unlike many other OAuth2 providers, Dex doesn't provide `<client secret>`.  Instead, the secret can be generated with `openssl rand -hex 20`.
{{< /admonition >}}
```

2024-03-19 18:50 UTC, lwandz13 commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   Instead the secret can be generated with, for example, `openssl rand -hex 20`.
Delete this, it's added as part of the admonition shortcode

2024-03-19 18:50 UTC, lwandz13 commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   where `<dex base uri>` corresponds to the `issuer: ` configuration in Dex (e.g. the Dex
```suggestion
<dex base uri>` corresponds to the `issuer: ` configuration in Dex (e.g. the Dex
```

2024-03-20 11:52 UTC, fredrikekre commented on docs/sources/setup-grafana/configure-security/configure-authentication/generic-oauth/index.md
> +   Note that, unlike many other OAuth2 providers, Dex doesn't provide `<client secret>`.
`{{% admonition type="note" %}}` I guess?

2024-03-20 11:55 UTC, fredrikekre commented
Thanks for the review. I spent some time figuring this configuration out and thought it could be useful for others too.

Btw, is is possible to build the docs locally to get a preview?

2024-03-28 20:35 UTC, lwandz13 approved these changes

2024-03-28 20:36 UTC, merged

2024-03-29 13:35 UTC, dmihai commented
FYI I tested the OAuth2 flow added in this PR against a Dex instance running locally. It worked as expected, great job!