Add Microsoft Teams notifier
grafana/grafana pull request #8533
Opened 2017-06-03 22:36 UTC by anthu

Add Microsoft Teams notifier

Although Microsoft Teams is able to receive E-Mails to channels, they got parsed as plain text. This feature is making use of the incoming webhook and creates a rich card.

Example alert:
http://imgur.com/a/o30ZQ

Fixes #8523

2017-06-08 05:02 UTC, torkelo commented
It does not look like it includes the image. Can that be added?

2017-06-08 05:28 UTC, anthu commented
Sure :)

2017-06-19 23:45 UTC, torkelo commented
There is image url added to the message, does teams support that? 

For reference slack:
https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/slack.go#L125

2017-06-20 04:40 UTC, anthu commented
Yes, it does:
```
"sections":[
  "images": [
    {
      "image": "http://connectorsdemo.azurewebsites.net/images/MicrosoftSurface_024_Cafe_OH-06315_VS_R1c.jpg",
      "title": "This is the image's alternate text"
    }
  ]
]
```
(see [Message Card Playground](https://messagecardplayground.azurewebsites.net))
I will try to fix it today.

2017-06-22 21:10 UTC, anthu commented
For some reason `heroImage` is not rendering in Teams. I have to investigate, what's going on.

Maybe someone of you will see the problem. The `images` notation above is working fine. But I think `heroImage` should be the way to go.

2017-06-24 16:23 UTC, lareeth commented
I am waiting for @anthu to check my pull request as it should fix this

2017-07-04 12:38 UTC, daniellee commented
@anthu the build is failing. Waiting for your fix and moving this to the 5.0 milestone instead.

2017-07-04 12:41 UTC, anthu commented
@daniellee unfortunately the Office 365 Card reference is out of date and the heroImage linked above is not supported anymore.

2017-07-10 08:30 UTC, nmat commented
any news regarding this? would be a very good feature that I am missing at the moment. :)

2017-07-10 10:37 UTC, daniellee commented
@nmat I'm not sure. Looks like it is not fully working.

@anthu can this be fixed?

2017-07-13 20:33 UTC, anthu commented
Thanks for bringing this up.

I'm waiting for response: https://github.com/OfficeDev/Microsoft-teams-docs/issues/202

2017-07-13 21:04 UTC, anthu commented
As `heroImage` is not working for me, I inserted the simple `image` which seems to be quite small 👎 

<img width="833" alt="screenshot 2017-07-13 23 00 20" src="https://user-images.githubusercontent.com/760387/28187514-4fa8fee8-681f-11e7-808d-8642f23b96f9.png">

2017-08-09 21:57 UTC, nmat commented
could this be done in 2 different stages?

first stage: implement the alerting (without the image provided but a link)

second stage: work on getting the image in the message (as a future improvement?)

IMO just having the alert showing up in general is good enough to start with since other details can come later on. However this might need a vote or something.

2017-09-15 08:18 UTC, bergquist requested changes
We could dd support for teams without images. That's not a blocker but it improves the experience.
But first conflicts have to be solved.

2017-09-15 08:18 UTC, bergquist commented on pkg/metrics/metrics.go
> +	M_Alerting_Notification_Sent_Teams = RegCounter("alerting.notifications_sent", "type", "teams")
This is not needed anymore. We measure it at another layer now.

2017-09-15 08:18 UTC, bergquist commented on pkg/services/alerting/notifiers/teams.go
> +	metrics.M_Alerting_Notification_Sent_Teams.Inc(1)
Remove this as well.

2017-10-30 00:15 UTC, kendtimothy commented
@anthu @bergquist do we have any update on this? :)

2017-10-30 10:15 UTC, anthu commented
@kendtimothy: Ouh - thanks for the reminder! I'll rebase and fix the change requests.

2017-11-02 11:34 UTC, anthu commented
@bergquist Could you have a look?

2017-11-14 10:06 UTC, bergquist approved these changes

2017-11-14 10:07 UTC, bergquist commented
Merge this https://github.com/grafana/grafana/commit/fd2451823b14bb6636b84d49dd5a9b3886546d2b

Not sure why github doesnt close this PR :)

Will be available in 4.7 or 5.0 depending on if we do 4.7 :)

2017-11-14 10:07 UTC, closed without merging

2018-08-21 12:11 UTC, stefanes commented
Documentation (or at least a mention in the "All supported..." list) for this seems to be missing from here: http://docs.grafana.org/alerting/notifications/

2018-08-21 12:39 UTC, marefr commented
@stefanes thanks for making us aware of this. Would you mind contribute a PR for this? This file needs an update: https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md#all-supported-notifier