Scope: Add basic integration tests
grafana/grafana pull request #85351
Opened 2024-03-28 12:43 UTC by ryantxu

This adds two sample files for scopes and a simple integration test

2024-03-28 12:48 UTC, ryantxu commented on pkg/apis/scope/v0alpha1/register.go
> -	metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
When we register the internal version, this fails with the error:
```
Double registration of different types for scope.grafana.app/__internal, Kind=WatchEvent: old=k8s.io/apimachinery/pkg/apis/meta/v1.InternalEvent, new=k8s.io/apimachinery/pkg/apis/meta/v1.WatchEvent in scheme "pkg/runtime/scheme.go:100
```

it does not appear to be used, so maybe we just remove it?

2024-03-28 13:28 UTC, ryantxu commented
@kylebrandt -- here is a VERY basic test, but at least lets us see what valid examples should look like.  Not implemented in this test is actually calling the filtering -- I think we can merge this, then see if you can add more to it.

@toddtreece -- what are your thought on typed clients?  This uses untyped/dynamic -- ok for a sanity check, but pretty difficult for more complex tests

2024-03-28 13:29 UTC, ryantxu commented on pkg/tests/apis/scopes/scopes_test.go
> +		found, err := scopeDashboardBindingClient.Resource.List(ctx, metav1.ListOptions{})
@kylebrandt -- would be good to exercise ListOptions with the fieldSelectors we are implementing

2024-03-29 12:05 UTC, kylebrandt commented
I don't think this should still be green after merging in main, since that has the change of `[]Dashboard` to `Dashboard`. So the tests need to be checking for something else I think - in the past when doing this (malformed typed) manually over http api, this would have returned a Warning HTTP header in the response.

2024-03-29 12:33 UTC, kylebrandt requested changes
I think we need to see the tests fail (or expect warning?) when there are incorrect specs submitted, right now it seems to pass when it shouldn't.

2024-03-29 13:10 UTC, kylebrandt commented
Ah, the `CreationOptions` has options for this:

e.g. `metav1.CreateOptions{FieldValidation: "Strict"}`

```
    /home/kbrandt/go/github.com/grafana/grafana/pkg/tests/apis/scopes/scopes_test.go:123:
        	Error Trace:	/home/kbrandt/go/github.com/grafana/grafana/pkg/tests/apis/scopes/scopes_test.go:123
        	Error:      	Received unexpected error:
        	            	ScopeDashboardBinding in version "v0alpha1" cannot be handled as a ScopeDashboardBinding: strict decoding error: unknown field "spec.dashboards"
        	Test:       	TestIntegrationScopes/Check_create_and_list
```

2024-03-29 13:19 UTC, kylebrandt approved these changes

2024-03-29 13:52 UTC, toddtreece commented on pkg/tests/apis/scopes/scopes_test.go
> +		require.Len(t, found.Items, 1)
it looks like there's a duplicate error check. is it worth adding a test for the contents of the list?
```suggestion
		require.Len(t, found.Items, 1)
		require.Equal(t,
			"example2",
			mustNestedString(found.Items[0], "metadata", "name"),
		)
```

2024-03-29 14:00 UTC, toddtreece approved these changes

2024-03-29 14:12 UTC, merged