Access control: Use ResolveIdentity() for authorizing in org
grafana/grafana pull request #85549
Opened 2024-04-03 15:57 UTC by alexanderzobnin

**What is this feature?**

This PR removes hacky `makeTmpUser()` func for getting user identity in specific org with `ResolveIdentity()` from authn service.

**Why do we need this feature?**

We need to simplify authorization in org other than user is logged in.

**Which issue(s) does this PR fix?**:

Fixes https://github.com/grafana/identity-access-team/issues/619

2024-04-08 12:43 UTC, kalleep approved these changes
LGTM, I think it would be good if @gamab also took a look at this one. He has found some fixed some issues around it in the past so just want to make sure we don't have any regressions

2024-04-09 10:43 UTC, IevaVasiljeva reviewed
From reading through it looks good. Only some very small nits (mostly to do with import ordering), feel free to ignore those.

I'll do some testing before approving.

2024-04-09 10:43 UTC, IevaVasiljeva commented on pkg/api/org_test.go
> +	"github.com/grafana/grafana/pkg/services/authn/authntest"
Nit: import ordering

2024-04-09 10:43 UTC, IevaVasiljeva commented on pkg/api/plugins_test.go
> +	"github.com/grafana/grafana-plugin-sdk-go/backend"
Nit: import ordering

2024-04-09 10:43 UTC, IevaVasiljeva commented on pkg/services/accesscontrol/middleware.go
> +					deny(c, nil, fmt.Errorf("failed to authenticate user in target org: %w", err))
Nit: maybe `failed to authorize user in target org` would be more accurate.

2024-04-09 11:55 UTC, IevaVasiljeva requested changes
I just tested this for several scenarios, and it allows users with Admin rights in a single org to have Admin permissions globally. Eg, as an org Admin user I can create or edit global roles. I think it's because [FetchSyncedUserHook](https://github.com/grafana/grafana/blob/9c292d2c3f771c24e393ae08dcd5a26b5405f7c0/pkg/services/authn/authnimpl/sync/user_sync.go#L124-L135) overwrites the org ID in the identity to be the org ID of the current signed in user (I _think_ it's because of [this conditional](https://github.com/grafana/grafana/blob/9c292d2c3f771c24e393ae08dcd5a26b5405f7c0/pkg/services/user/userimpl/store.go#L392-L395)).

Repro steps:
* create an org Admin user;
* try to create a global role with this org Admin user - this should fail, but it doesn't.

Other scenarios that I tested and that worked as expected:
* when _single_organization_ is set, org Admin user can update basic role;
* when _single_organization_ is set, a service account with Admin role can update basic role;
* when _single_organization_ is not set, a service account with Admin role cannot update basic role;
* user who is an Admin in one org and has lower perms in another org can't use the Admin perms in this other org;
* service account cannot do anything in an org that it doesn't belong to.

2024-04-10 09:27 UTC, IevaVasiljeva approved these changes
I've tested again together with changes in https://github.com/grafana/grafana/pull/85835, and I think everything works as expected.

Test scenarios covered:
* org admin or SA with org admin permissions can create a role in the org where they are an admin;
* org admin or SA with org admin permissions cannot create a role in the global org or a different org where they are not admins;
* viewer + server admin can create a role in the global org;
* org admin or SA with org admin permissions can create a role in the global org if `single_organization` is set to true;
* org admin or SA with org admin permissions can not create a role in another org where they are not admins when `single_organization` is set to true.

One scenario that is a bit weird:
* viewer + server admin can create a role in the org where the user is just a viewer. I don't remember how we treated this scenario in the past - I think this is expected 🤔

2024-04-10 09:27 UTC, IevaVasiljeva commented
Great job on this @alexanderzobnin and @kalleep 🥇 🎉

2024-04-10 10:42 UTC, merged