API keys: Disabling of API keys endpoints
grafana/grafana pull request #85550
Opened 2024-04-03 15:58 UTC by eleijonmarck

**What is this feature?**

This PR removes the API key endpoints from Grafana API keys in favor of Service account tokens. For more information see the epic: #53567.

**Why do we need this feature?**
This is a step of making Grafana to only use service accounts and service account tokens as part of our way to making a unified machine access experience in Grafana.

**Which issue(s) does this PR fix?**:
#53567

2024-04-03 16:01 UTC, kalleep reviewed
Great! You need to add breaking change label to this pr

2024-04-03 22:19 UTC, vtorosyan requested changes
Can we please hold on from merging this change? I think we need a bit more due diligence to understand the impact and provide guidance for users when anything breaks before cutting off the write path.

2024-05-06 13:27 UTC, eleijonmarck commented on pkg/api/apikey.go
> -	query := apikey.GetApiKeysQuery{OrgID: c.SignedInUser.GetOrgID(), User: c.SignedInUser, IncludeExpired: c.QueryBool("includeExpired")}
@Jguer asking you, do you think we should disable the listing of APIkeys?

2024-05-07 09:57 UTC, eleijonmarck commented
without the terraform PR we are redirecting to service account token directly for terraform and we would get a message saying:

```tf
│ Error: status: 400, body: {"message":"Service Account ID is invalid","traceID":""}
│
│   with grafana_api_key.foo,
│   on apikeys.tf line 1, in resource "grafana_api_key" "foo":
│    1: resource "grafana_api_key" "foo" {
```

2024-05-10 12:22 UTC, vtorosyan commented
I am still a bit hesitant to remove the POST endpoint with appropriate announcement with a good notice. 

What about having a blog post sharing timeline for full sunsetting of the API keys so that users have time for migration and the breaking change?

2024-05-13 09:21 UTC, eleijonmarck commented
> I am still a bit hesitant to remove the POST endpoint with appropriate announcement with a good notice.
> 
> What about having a blog post sharing timeline for full sunsetting of the API keys so that users have time for migration and the breaking change?

Let's bring this up as a topic for the deprecation, also to understand where we would put this into priority.

2024-06-21 12:11 UTC, Jguer commented
Closing as unplanned for now

2024-08-20 15:01 UTC, closed without merging