Prometheus: Add hints for native histograms
grafana/grafana pull request #87017
Opened 2024-04-28 21:45 UTC by bohandley

**What is this feature?**

When a user selects a native histogram, a hint or hints should be provided indicating they have selected a native histogram and providing functions for that metric.

This PR provides hints that allow a user to add 6 functions to the query builder from a native histogram hint

```
histogram_avg(rate(${expression}[$__rate_interval]))
histogram_fraction(0,0.2,rate(${expression}[$__rate_interval]))
histogram_count(rate(${expression}[$__rate_interval]))
histogram_sum(rate(${expression}[$__rate_interval]))
histogram_stddev(rate(${expression}[$__rate_interval]))
histogram_stdvar(rate(${expression}[$__rate_interval]))
```

<img width="638" alt="Screenshot 2024-04-28 at 10 28 21 PM" src="https://github.com/grafana/grafana/assets/25674746/ab26d484-565a-40cd-82ba-ee9283f19a0e">

The code editor can only show one hint at a time so until we refactor that, we show that the metric is a native histogram and provide the hint to use histogram_avg with the rate function.

<img width="775" alt="Screenshot 2024-04-28 at 9 01 34 PM" src="https://github.com/grafana/grafana/assets/25674746/f21d4c9e-289f-4a19-a6f2-750fff88043d">

Fixes https://github.com/grafana/grafana/issues/86388

**Why do we need this feature?**

Native histograms are being released in Mimir in the next month and this is part of the [GA strategy](https://github.com/grafana/observability-metrics-squad/issues/142).

**Who is this feature for?**

For users who have enabled native histograms.

**Special notes for your reviewer:**

TESTING!!!!!!

1. Use this [repository](https://github.com/laupse/prometheus-native-histograms) which creates native histograms BUT MAKE SURE YOU UPDATE THE FOLLOWING
  - use Prometheus version 2.51.0 int he docker compose file or you won't be able to test all the functions

```
services:
  prometheus:
    image: prom/prometheus:v2.51.0
```
  - update the docker compose Grafana image to use the tag v11.1.0-69868 or later you will have a bad time because you'll need the new parser if you switch between query builder and code editor. 
  - If you don't want to update the grafana image just run Grafana locally with main and create a data source from the prometheus-native-histogram prometheus datasource or add this datasource yaml file.

```
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus-native-histogram
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: prometheus
    # <string> url
    url: http://prometheus:9090
```

2. Now you should have a data source that has a native histogram. The native histogram is named `rpc_durations_native_histogram_seconds`.

3. When you select this in the query builder you will get six query hints (6 functions).
4. When you select this metric in the code editor you will get one hint because the code editor only displays one hint. We need to fix that or create an issue to fix this.

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-05-14 09:18 UTC, itsmylife commented
A hint: 
Please make sure you disable `promQLScope` feature flag.

2024-05-14 09:21 UTC, itsmylife requested changes
Even I add a the recommended histogram function it keeps suggesting me to add the histogram functions. 

<img width="1020" alt="image" src="https://github.com/grafana/grafana/assets/820946/668ff80d-155c-4c1d-becf-24f80e935156">

Also layout is not the same with your image on my machine. I think some stuff has been changed in time.

2024-05-14 17:57 UTC, NWRichmond reviewed
I'm also encountering some issues:

https://github.com/grafana/grafana/assets/5732000/c4d570f4-1f24-4092-b429-f157b3519773

2024-05-15 17:51 UTC, zhehao-grafana commented
Thanks, Ismail and Nick, for the review! Can I assume Brenden will be the one fixing these issues when he returns?

2024-05-22 20:48 UTC, NWRichmond commented
Hi @zhehao-grafana! Yes, I believe @bohandley will be handling the updates to this PR.

2024-05-30 18:35 UTC, bohandley commented
@itsmylife and @NWRichmond thank you for the reviews!

I have made the fix for removing the hints when a native histogram hint is selected. See video below. Because we are removing the hints, we don;t need to change the css so I reverted the css changes and it looks good.

I am updating the video in description with this current video


https://github.com/grafana/grafana/assets/25674746/f4dd441b-7674-40d5-aaf1-95676a872680

2024-05-31 11:39 UTC, itsmylife commented
@bohandley Changes looks good. It fixes the issues I mentioned. Thank you. But I have new things :) 

1. In the code mode it only suggests adding `histogram_avg()` function. Should we suggest all possibilities or just one?
2. After having the query in the code mode with a histogram function added, let's say `histogram_avg()`, I switched to builder mode. Then I decided to use some other function so I remove the `histogram_avg()` only. At this point my query is `rate(rpc_durations_native_histogram_seconds[$__rate_interval])`. Then it suggests me all the functions. Which is 👍 . Then if I add `histogram_sum` the query becomes pretty weird. Like this: `histogram_sum(rate(rate(rpc_durations_native_histogram_seconds[$__rate_interval])[$__rate_interval])[$__rate_interval]))`. So it adds rate function once more. And it adds it with a wrong `Range` value. Please see the image below.
![image](https://github.com/grafana/grafana/assets/820946/8b475186-0be8-4d4d-a39e-c7b327e7dd7f)

2024-05-31 13:24 UTC, bohandley commented
@itsmylife thank you!

> 1.  In the code mode it only suggests adding histogram_avg() function. Should we suggest all possibilities or just one?

This is a nice to have addition to hints, but is not necessary for pushing native histograms forward at the moment. I will create an issue to allow the code mode to handle multiple hints.

> 2. After having the query in the code mode with a histogram function added, let's say histogram_avg(), I switched to builder mode. Then I decided to use some other function so I remove the histogram_avg() only. At this point my query is rate(rpc_durations_native_histogram_seconds[$__rate_interval]). Then it suggests me all the functions. Which is 👍 . Then if I add histogram_sum the query becomes pretty weird. Like this: histogram_sum(rate(rate(rpc_durations_native_histogram_seconds[$__rate_interval])[$__rate_interval])[$__rate_interval])). So it adds rate function once more. And it adds it with a wrong Range value. Please see the image below.

I'll make a fix for this 👍🏻 . The hints behave by looking for a single metric to make a hint suggestion, so all functions in a hint are added assuming there are no other functions present. Other hints handle this by not offering hints when additional functions are present in the query. Good catch!

2024-05-31 15:02 UTC, bohandley commented
Issue for multiple hints here!

https://github.com/grafana/grafana/issues/88564

This is a good first issue!

2024-05-31 17:31 UTC, NWRichmond approved these changes
I appreciate the updates and the helpful code comments. Nicely done, @bohandley!

https://github.com/grafana/grafana/assets/5732000/deb514df-c0ba-486f-a35d-89e8202c45ec

2024-05-31 17:31 UTC, NWRichmond commented on packages/grafana-prometheus/src/query_hints.test.ts
> +    expect(JSON.stringify(hints)).toContain('ADD_HISTOGRAM_AVG');
nit: we could do a little less work here by `JSON.stringify`ing once:

```suggestion
    const hintsString = JSON.stringify(hints);
    expect(hintsString).toContain('ADD_HISTOGRAM_AVG');
    expect(hintsString).toContain('ADD_HISTOGRAM_COUNT');
    expect(hintsString).toContain('ADD_HISTOGRAM_SUM');
    expect(hintsString).toContain('ADD_HISTOGRAM_FRACTION');
    expect(hintsString).toContain('ADD_HISTOGRAM_AVG');
```

2024-06-03 21:01 UTC, itsmylife commented
Sorry for being problem maker :) But there is still a problem. Please check the video:

https://github.com/grafana/grafana/assets/820946/9cb5e6c8-316a-44e4-94b3-d589e2bff6d8

- If there is `rate()` function applied no hints is being shown
- if there is no histogram function applied hints are overflowed

2024-06-03 21:10 UTC, zhehao-grafana commented
> Sorry for being problem maker :) But there is still a problem. Please check the video:
> 
>  Screen.Recording.2024-06-03.at.22.58.04.mov 
> * If there is `rate()` function applied no hints is being shown
> * if there is no histogram function applied hints are overflowed

@itsmylife Regarding the first issue [If there is `rate()` function applied no hints is being shown], it is also true for the classic histogram. I don't know whether hints were designed in this way [for example, is hints only applied at the first layer not with a layer in between]

![Screenshot by Dropbox Capture](https://github.com/grafana/grafana/assets/143556099/bb7300d6-fdb4-4c06-b672-640da8cc87cf)

2024-06-03 21:14 UTC, itsmylife commented
@zhehao-grafana I missed that. Thank you. In that case, I think the PR is just fine. I'll approve it.

2024-06-03 21:14 UTC, itsmylife approved these changes

2024-06-03 21:59 UTC, merged