SCSS: remove some low hanging dead fruit
grafana/grafana pull request #87260
Opened 2024-05-02 16:17 UTC by ashharrison90

**What is this feature?**

- removes some old SCSS
  - as far as i can tell, this is all unused. @torkelo maybe you know better? 🙏 

**Why do we need this feature?**

- SCSS is dead to us 🔪 

**Who is this feature for?**

- grafana devs

**Which issue(s) does this PR fix?**:

For https://github.com/grafana/grafana/issues/64129

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-05-06 11:42 UTC, tskarhed commented
Verify that the removal of these files do not affect deployments. https://github.com/grafana/hosted-grafana/pull/2291/files

2024-05-07 11:45 UTC, tskarhed commented
/deploy-to-hg

2024-05-07 12:00 UTC, tskarhed requested changes

2024-05-07 12:06 UTC, ashharrison90 commented on public/sass/components/_json_explorer.scss
> -  }
nice spot, will restore this one 👍

2024-05-07 12:09 UTC, ashharrison90 commented
/deploy-to-hg

2024-05-07 12:09 UTC, ashharrison90 commented on public/sass/components/_json_explorer.scss
> -  }
meh, it's no different to the other 100 scss files in that regard 😂

2024-05-07 12:10 UTC, tskarhed approved these changes
When merging this, just keep an eye out for issues with deployments. Even better if we can inform is this breaks stuff.

2024-05-07 14:26 UTC, merged