plugin metadata schema: allow multiple infixed dash-separated words in plugin id
grafana/grafana pull request #87399
Opened 2024-05-06 17:29 UTC by darrenjaneczek

**What is this feature?**

Allows schema to accept multiple dash-separated words in the plugin id.

Currently, if you have a plugin id that happens to have more than two dash-separated words before the suffix, the schema will generate a warning.

e.g., `grafana-my-verbose-plugin-app`

![image](https://github.com/grafana/grafana/assets/38694490/99a6432c-283b-461e-9b91-f9501326dc21)

On hover:
![image](https://github.com/grafana/grafana/assets/38694490/c8628fbf-7a1c-4aba-a46e-62482cf83b63)

**Why do we need this feature?**

Since various plugins already have more dash-separations in their id than the current regular expression allows, they will not generate warnings with this new regular expression.
Despite the warning, there does not appear to be a technical reason to restrict the plugin id.

**Who is this feature for?**

Plugin developers with additional `-` separators in their plugin ids.

**Notes**

The former regular expression would allow: `my-app` and `my-simple-app`, due to the use of `?`.
The new regular expression deliberately retains this, assuming it was intentional, by using `*`.
The difference is that this now allows `my-somewhat-longer-named-app`.

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-05-07 06:02 UTC, ryantxu commented
This seems OK to me -- a few of the plugins already have more slashes, so I don't think it is a real constraint

```
      "slug": "grafana-azure-monitor-datasource",
      "slug": "aws-datasource-provisioner-app",
      "slug": "grafana-iot-sitewise-datasource",
      "slug": "grafana-iot-twinmaker-app",
      "slug": "grafana-azure-data-explorer-datasource",
      "slug": "camptocamp-prometheus-alertmanager-datasource",
```

@marefr

2024-05-14 19:51 UTC, darrenjaneczek commented
@ryantxu 
> This seems OK to me -- a few of the plugins already have more slashes, so I don't think it is a real constraint

Do you know any plugins have only one single dash?
e.g., `john.app`, `john.datasource`, etc?

As written in [original comment](https://github.com/grafana/grafana/pull/87399#issue-2281375947):
> The former regular expression would allow: my-app and my-simple-app, due to the use of ?.
> The new regular expression deliberately retains this, assuming it was intentional, by using *.

2024-05-15 07:30 UTC, ryantxu commented
Yes -- when the org and name are the same like:
https://grafana.com/grafana/plugins/redis-datasource/

2024-05-15 08:00 UTC, tolzhabayev requested changes
We want to discuss this internally as the team to see if we want to adjust the format or not. 

The past outlier / exceptions are not a reason enough for us to change the id - only if it makes sense for us to support properly everywhere AND is beneficial (for the future plugins) we should change it.

We will get back to you on this.

2024-05-31 14:39 UTC, darrenjaneczek commented
@tolzhabayev

We were wondering if there were any updates on this topic.

2024-06-04 10:32 UTC, tolzhabayev commented
@darrenjaneczek here is what we came up with https://github.com/grafana/grafana/pull/88673

2024-06-05 17:47 UTC, josmperez approved these changes
No changes needed from a documentation standpoint. LGTM.

2024-06-14 22:07 UTC, diegommm commented
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

2024-06-20 18:14 UTC, darrenjaneczek commented
Closed in favor of https://github.com/grafana/grafana/pull/88673

2024-06-20 18:14 UTC, closed without merging