add catchpoint to plugin list
grafana/grafana pull request #87438
Opened 2024-05-07 13:18 UTC by ktw4071

**What is this feature?**
Adding Catchpoint plugin to the plugin list

**Why do we need this feature?**
New enterprise datasource
**Who is this feature for?**
datasource users

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes # https://github.com/grafana/plugins-private/issues/2002

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-05-07 15:56 UTC, scottlepp approved these changes

2024-05-07 15:58 UTC, cletter7 requested changes
LGTM, just preventing it from accidental merging before the plugin is released.

2024-05-15 15:23 UTC, chri2547 approved these changes

2024-06-12 13:38 UTC, cletter7 approved these changes

2024-06-12 14:05 UTC, merged