[v11.0.x] Chore: Upgrade go to 1.20.10
grafana/grafana pull request #87472
Opened 2024-05-07 20:46 UTC by stephaniehingtgen

Manual backport of https://github.com/grafana/grafana/pull/87463

Upgrades go to 1.20.10

2024-05-07 21:15 UTC, kminehart approved these changes

2024-05-07 21:29 UTC, baldm0mma approved these changes
LGTM

2024-05-08 13:29 UTC, ashharrison90 requested changes
think this needs resigning with drone (`make drone`) before merging

2024-05-08 15:00 UTC, ashharrison90 approved these changes
lgtm

2024-05-08 15:05 UTC, merged