Alerting: support the Grafana operator as export format provider
grafana/grafana pull request #87954
Opened 2024-05-16 08:50 UTC by theSuess

**What is this feature?**

This PR adds a new export provider for the [grafana-operator](https://github.com/grafana/grafana-operator) to the alerting export drawer.

**Why do we need this feature?**

Configuring alerting rules as-code is very complex. To alleviate this, many users utilize the `Modify Export` functionality. The YAML export is mostly compatible but requires further modification to be imported as an operator resource. Due to differences in serialization, it also causes CD solutions to trigger changes when there are none.

**Who is this feature for?**

Users wishing to export their alerting resources as code and use them with the Operator

**Which issue(s) does this PR fix?**:

Implements https://github.com/grafana/grafana-operator/issues/1492

**Special notes for your reviewer:**

Since the operator does _not_ (yet) support Notification Policies & Mute Timings, I've added a way to filter for supported export providers.

Please check that:
- [X] It works as expected from a user's perspective.
- [X] If this is a pre-GA feature, it is behind a feature toggle.
- [X] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-05-16 08:58 UTC, theSuess commented on pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go
> +	IsPaused             bool                                 `json:"isPaused,omitempty" yaml:"isPaused,omitempty" hcl:"is_paused"`
The OpenAPI Spec has this as not required (= the generated go client has it as `omitempty`) so I'm reflecting the change here

2024-05-16 08:58 UTC, theSuess commented on pkg/services/ngalert/api/tooling/definitions/provisioning_alert_rules.go
> +	ToSeconds   int64 `json:"to,omitempty" yaml:"to,omitempty" hcl:"to"`
The OpenAPI Spec has this as not required (= the generated go client has it as `omitempty`) so I'm reflecting the change here

2024-05-16 08:58 UTC, theSuess commented on public/app/features/alerting/unified/components/export/providers.ts
> +              for: rule.for.endsWith('m') ? rule.for + '0s' : rule.for,
This prevents the change noticed in https://github.com/grafana/grafana-operator/issues/1492

2024-06-14 21:59 UTC, diegommm commented
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

2024-06-20 07:58 UTC, dcharbonnier requested changes
few changes on typing that prevent the use of any and should fix the ci here https://drone.grafana.net/grafana/grafana/178252/1/4

2024-06-20 07:58 UTC, dcharbonnier commented on public/app/features/alerting/unified/components/export/providers.ts
> +    const out: any[] = [];
Drone does not like the any
```suggestion
    const out: Record<string, unknown>[] = [];
```

2024-06-20 07:58 UTC, dcharbonnier commented on public/app/features/alerting/unified/components/export/providers.ts
> +      console.log(resource);
```suggestion
```

2024-06-20 07:58 UTC, dcharbonnier commented on public/app/features/alerting/unified/components/export/providers.ts
> +    const parsed = loadAll(raw) as Array<{ kind: string }>;
```suggestion
    const parsed = loadAll(raw) as  Record<string, unknown> & { kind: string }[];
```

2024-06-20 07:58 UTC, dcharbonnier commented on public/app/features/alerting/unified/components/export/providers.ts
> +        const r = resource as any;
creating this variable with an any type should be unnecessary after the piping changes above

2024-06-20 07:58 UTC, dcharbonnier commented on public/app/features/alerting/unified/components/export/providers.ts
> +        const r = resource as any;
creating this variable with an any type should be unnecessary after the piping changes above

2024-08-04 01:57 UTC, closed without merging

2024-10-07 06:57 UTC, DrDJIng commented
I noticed this has been closed. Is this still planned for the 11.2.x milestone?

2024-12-20 08:41 UTC, mfcmaestro commented
@theSuess Do you have any information if this PR is planned to be released?
Thanks!