Tempo: Add toggle for streaming
grafana/grafana pull request #88685
Opened 2024-06-04 12:06 UTC by fabrizio-grafana

Currently, we have the `traceQlStreaming` feature toggle. We know that we can't simply get rid of it, because streaming is not supported for all customers at the moment.
This PR proposed to add a data source configuration option to enable/disable streaming instead of using the feature toggle. The feature toggle will be removed in a future PR.

Open points:
- [ ] How to handle the migration from the feature toggle to the configuration option

2024-06-06 10:39 UTC, adrapereira requested changes

2024-06-06 12:59 UTC, adrapereira reviewed
Code looks good but do you mind pulling the changes and testing locally @joey-grafana ?

2024-06-12 11:01 UTC, fabrizio-grafana commented on public/app/plugins/datasource/tempo/datasource.ts
> +          if (this.streamingEnablement?.search && config.liveEnabled) {
This is what I wanted to discuss yesterday. We can discuss it in today's standup.

2024-06-12 11:03 UTC, fabrizio-grafana commented on public/app/plugins/datasource/tempo/configuration/StreamingSection.tsx
> +    <ConfigSection title="Streaming" description="Enable streaming for different Tempo features." isCollapsible={false}>
GTM to add the description. As for marking this as a beta, I think streaming is not a beta feature anymore, or am I wrong?

2024-06-12 11:05 UTC, fabrizio-grafana commented on public/app/plugins/datasource/tempo/datasource.ts
>              subQueries.push(this.handleStreamingSearch(options, traceqlSearchTargets, queryValueFromFilters));
Yeah maybe we could use that to either enable or disable streaming by default when the toggle is not set (`undefined/null`), which will be the case for all customers when we merge this. I'll have a look at this!

2024-06-13 09:02 UTC, joey-grafana commented on public/app/plugins/datasource/tempo/configuration/StreamingSection.tsx
> +    <ConfigSection title="Streaming" description="Enable streaming for different Tempo features." isCollapsible={false}>
Ahh sorry yeah it is GA. I had though when we add a new toggle like this it should be marked as beta but honestly I think it's ok and we can leave as is.

2024-06-14 21:35 UTC, diegommm commented
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

2024-07-09 16:43 UTC, adrapereira approved these changes

2024-07-09 16:44 UTC, merged

2024-07-26 20:04 UTC, 09jvilla commented
@fabrizio-grafana @adrapereira -- Can you all clarify how the datasource level feature toggle interacts with the grafana-level feature toggle? 

In other words, if `traceQLStreaming=true` but I've set up the configuration for tempo datasource 1234 to have streaming off, does the `traceQLStreaming=true` override that? Or does the datasource-level configuration take precent? If `traceQLStreaming=false` but tempo datasource 3456 has streaming set to on, does that mean results will be streamed? Or will they not? 

I'm assuming that the 2 toggles (the one at the grafana-level and the one at the per-datasource level) will co-exist for at least one release (e.g., Grafana 11.2) before the grafana-level toggle is removed, which means we should [document](https://github.com/grafana/tempo-squad/issues/459) which takes precedence over the other. But if that's not the case, please correct!

2024-07-29 21:36 UTC, 09jvilla commented
> At the moment both need to be enabled for streaming to work, we'll remove the feature toggle soon.

My expectation is that you'd mark the `traceQLStreaming` toggle as deprecated in Grafana 11.2 and then remove it in Grafana 11.3. Is that the right expectation? 

If so, what we'd need to do is:

- Ensure that the Grafana 11.2 docs mark `traceQLStreaming` toggle as deprecated.
- Add documentation in the Grafana 11.2 docs under the "Tempo datasource" pages that describes the new datasource-level streaming toggle. 
- Clarify in the Grafana 11.2 docs how these two toggles interact. Specifically, for streaming to work for a particular tempo datasource, both `traceQLStreaming` must be set to `true` for the Grafana and the datasource must be set to allow streaming. If the datasource allows streaming but `traceQLStreaming=false`, no streaming will occur. If the datasource has streaming disabled and `traceQLStreaming=true`, no streaming will for that datasource.
- In the Grafana 11.3 docs, remove all references to the  `traceQLStreaming` feature toggle.

2024-07-29 21:36 UTC, 09jvilla commented
@knylander-grafana , let me know if the above makes sense to you.

2024-07-29 21:36 UTC, 09jvilla commented
Let me know if the above sounds good, and if so, Kim and I will get it done. :)

2024-08-01 13:57 UTC, 09jvilla commented
> Our goal is to make this migration painless by setting the config automatically for users. I haven't found how exactly but I believe that it's possible.

The "setting the config automatically for users" would only be relevant for Grafana Cloud users, correct? Those running self-managed Grafanas would have to make this change manually, right? 

> I'm not 100% sure what the usual process is when migrating from a feature toggle to a datasource config, but your proposal sounds good.
Cool. Unless something changes, let's plan on this for now. With Grafana 11.2 slated for release to self-managed users at the end of August, this gives us a few weeks to get the docs in order to reflect this plan. Right now this means that Cloud users who already have access to this toggle don't have any docs on it, but I think this is okay since we plan to handle a lot of this on their behalf.

2024-08-01 22:24 UTC, knylander-grafana commented
Doc PR: https://github.com/grafana/grafana/pull/91432

2024-08-02 03:14 UTC, 09jvilla commented
> This PR https://github.com/grafana/grafana/pull/91340 should take care of the migration for non-provisioned datasources for both Grafana Cloud and OSS. Provisioned datasources will be handled in another way but users won't have to do anything.

That's awesome! So you detect if the Grafana has the `traceQLStreaming` toggle set to true, and if it set, you automagically set all the Tempo data sources in that Grafana to have streaming set to true at the Tempo data source config level. 

I'm assuming that the user could then choose to override that down the line? E.g., The automation set tempo ds1 , ds2, and ds3 to have streaming set to true because it detected traceQLStreaming=true in my Grafana, but then I decided that I wanted to switch tempo ds2 to actually have streaming off, while leaving it on for ds1 and ds3. Am I correct that this would work?

2024-08-04 20:46 UTC, 09jvilla commented
Sweet - thanks for the explanation, Andre!