Users: Add config option to control how often last_seen is updated
grafana/grafana pull request #88721
Opened 2024-06-04 17:25 UTC by parambath92

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-06-04 17:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=88721) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=88721) before we can accept your contribution.<br/><hr/>**Rajguru** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=88721) it.</sub>

2024-06-04 20:18 UTC, kalleep requested changes
Thanks for contributing! Left a few comments

2024-06-04 20:18 UTC, kalleep commented on pkg/setting/setting.go
> +	if cfg.UserInviteMaxLifetime < time.Minute*5 {
```suggestion
	if cfg.UserLastSeenUpdateInterval < time.Minute*5 {
```

2024-06-04 20:18 UTC, kalleep commented on pkg/setting/setting.go
> +	cfg.UserLastSeenUpdateInterval = userLastSeenUpdateIntervalDuration
```suggestion
	cfg.UserLastSeenUpdateInterval, err = gtime.ParseDuration(valueAsString(users, "last_seen_update_interval", "15m"))
	if err != nil {
		return err
	}
```

2024-06-04 20:18 UTC, kalleep commented on pkg/setting/setting.go
> +		return errors.New("the minimum supported value for the `last_seen_update_interval` configuration is 5m (5 minutes)")
Instead of returning an error here we should emit an warning log and set the minimum value

2024-06-04 20:18 UTC, kalleep commented on pkg/services/user/userimpl/user.go
> +func (s *Service) shouldUpdateLastSeen(cfg *setting.Cfg,t time.Time) bool {
No need to have cfg as a parameter

2024-06-04 20:20 UTC, kalleep commented
Also please update the pr description to reflect what we are adding in this pr

2024-06-05 10:58 UTC, parambath92 commented
> Also please update the pr description to reflect what we are adding in this pr

Addressed the review comments and updated the PR description.

2024-06-05 12:20 UTC, kalleep commented on pkg/setting/setting.go
> +		cfg.UserLastSeenUpdateInterval = 5
```suggestion
		cfg.UserLastSeenUpdateInterval = time.Minute*5
```

2024-06-05 14:23 UTC, kalleep reviewed
Great, could you also update https://github.com/grafana/grafana/blob/f28905f8c41e0ffbcc163becccbfaef764a12a05/docs/sources/setup-grafana/configure-grafana/_index.md#users with the new option. You use the comment you added to ini files as the description. 

Also it seems like you have committed as different users. To resolve it could you follow the instructions [provided](https://github.com/grafana/grafana/pull/88721#issuecomment-2148051143)

2024-06-05 19:18 UTC, parambath92 commented
> Great, could you also update https://github.com/grafana/grafana/blob/f28905f8c41e0ffbcc163becccbfaef764a12a05/docs/sources/setup-grafana/configure-grafana/_index.md#users with the new option. You use the comment you added to ini files as the description.
> I already added that [here](https://github.com/grafana/grafana/pull/88721/files#diff-6366694fe7537e1e6d38c770c59ef921706f184ced97ec76132de83fc44fc2cbR895-R900). Can you please validate ?
> Also it seems like you have committed as different users. To resolve it could you follow the instructions [provided](https://github.com/grafana/grafana/pull/88721#issuecomment-2148051143)
This is done

2024-06-06 09:51 UTC, kalleep commented
Great, there is a failing test `TestUpdateLastSeenAt`, to fix that you just have to set `UserLastSeenUpdateInterval`.
There is also a lint issue, Just format `setting.go` and then we should be able to merge this, to verify that the issue is resolved you can run `make lint-go`

2024-06-06 14:22 UTC, chri2547 reviewed
Docs look fine, approved. I'll rely on dev for formal approval to merge. Thank you for the contribution!

2024-06-14 21:38 UTC, diegommm commented
Hi! Greetings from the Release Guild. Just letting you know I'm updating your PR's milestone to [11.2.x](https://github.com/grafana/grafana/milestone/529). If you need to see your changes in a previous version, please consider adding a backport label.

Thank you!

2024-06-18 03:59 UTC, parambath92 commented
Hi @kalleep , Sorry for coming back late on this. Can you please let me know where to set `UserLastSeenUpdateInterval`?

2024-06-18 06:24 UTC, kalleep commented
@parambath92 you need to set it here https://github.com/grafana/grafana/blob/main/pkg/services/user/userimpl/user_test.go#L223, so something smaller than 20 min and bigger than 1 min for the test to work

2024-06-18 08:55 UTC, kalleep commented on pkg/services/user/userimpl/user_test.go
> +	userService.cfg.UserLastSeenUpdateInterval = 5
```suggestion
	userService.cfg.UserLastSeenUpdateInterval = 5*time.Minute

```

2024-06-20 14:51 UTC, Jguer commented on pkg/setting/setting.go
> +	if cfg.UserLastSeenUpdateInterval < time.Minute*5 {
Hey @parambath92 can we add a limit to this update interval to 1h? I'm afraid some auditing features will misbehave if the interval is too large

2024-06-24 07:16 UTC, Jguer approved these changes

2024-06-24 13:46 UTC, kalleep commented
@parambath92 There is a unrelated test failure. Could you try to  merge latest main and so we can see if that is fixed?

2024-06-24 14:07 UTC, parambath92 commented
> @parambath92 There is a unrelated test failure. Could you try to merge latest main and so we can see if that is fixed?

I merged the latest main to my fork branch. But looks like it failed again with different error.

2024-06-24 14:15 UTC, kalleep commented
Yes I can see that. I triggered a rerun to see if this was something flaky. If it still fails I will take some time tomorrow and figure out what the issue is so we can get this merged

2024-06-24 14:54 UTC, kalleep approved these changes
Now it is good to go. Thanks for the contribution and sorry for all the messiness with the ci

2024-06-24 14:54 UTC, merged