Repurpose wrong datasource UID feature flag
grafana/grafana pull request #89363
Opened 2024-06-18 14:42 UTC by andresmgot

**What is this feature?**

We don't need to fix wrong UIDs at the Grafana level so repurposing the feature flag to hard-fail instead.

2024-06-18 16:09 UTC, marefr requested changes
Looks good just some minor things

2024-06-18 16:09 UTC, marefr commented on pkg/services/datasources/service/store.go
> +			if ss.features != nil && ss.features.IsEnabled(ctx, featuremgmt.FlagFailWrongDSUID) {
Might want to use an errutil error so that the HTTP status becomes 4xx instead of 500, maybe 400 bad request?

2024-06-19 07:51 UTC, tolzhabayev commented
Cant comment directly on the right line - not sure why but:

var validUIDReplacer is unused now.

2024-06-20 07:40 UTC, marefr approved these changes

2024-06-20 10:56 UTC, merged