get rid of `Layout.tsx` including `HorizontalGroup` and `VerticalGroup`
grafana/grafana pull request #89376
Opened 2024-06-18 17:39 UTC by ArtistBanda

**What is this feature?**

This change removes usage of deprecated components `HorizontalGroup` and `VericalGroup` in `Layout.tsx` and instead use `Stack`

**Why do we need this feature?**

To remove the usage of deprecated components

**Who is this feature for?**

Grafana devs

**Which issue(s) does this PR fix?**:

Fixes #86872

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-06-18 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=89376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=89376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=89376) it.</sub>

2024-06-24 12:55 UTC, itsmylife approved these changes
LGTM 🚀 
Thanks for the contribution

2024-06-24 12:57 UTC, itsmylife requested changes
A small nit above with the label. The rest is good 🤟

2024-06-24 12:59 UTC, itsmylife commented
Also, looks like CI asks you to run `npm run betterer` in the root of the project and commit the results.

2024-06-24 17:59 UTC, ArtistBanda commented on public/app/plugins/datasource/influxdb/components/editor/query/influxql/code/RawInfluxQLEditor.tsx
> +        <InlineField htmlFor={selectElementId} label="Alias by">
Did the change!

2024-06-24 18:04 UTC, itsmylife approved these changes
LGTM

2024-06-24 18:38 UTC, itsmylife commented on public/app/plugins/datasource/influxdb/components/editor/query/influxql/code/RawInfluxQLEditor.tsx
> +        <InlineField htmlFor={aliasElementId} label="Format as">
```suggestion
        <InlineField htmlFor={selectElementId} label="Format as">
```

2024-06-24 18:38 UTC, itsmylife commented on public/app/plugins/datasource/influxdb/components/editor/query/influxql/code/RawInfluxQLEditor.tsx
> +        <InlineField htmlFor={aliasElementId} label="Format as">
Without this tests will keep failing

2024-06-24 18:59 UTC, merged

2024-06-24 19:01 UTC, ArtistBanda commented
Thanks for reviewing @itsmylife . Will pick something else now. If you have some suggestions please let me know. Thanks!

2024-06-25 07:46 UTC, itsmylife commented
@ArtistBanda Thanks again for the contribution. You can check this list and pick something https://github.com/grafana/grafana/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22