Andrew/mssql decouple
grafana/grafana pull request #89597
Opened 2024-06-24 05:19 UTC by bossinc

Used Gabor's findings on MySQL for this PR.

Gabor's PRs:
https://github.com/grafana/grafana/pull/86168
https://github.com/grafana/grafana/pull/86308
https://github.com/grafana/grafana/pull/87330

2024-06-24 05:20 UTC, bossinc commented on pkg/tsdb/mssql/standalone/main.go
> +	cfg := setting.NewCfg()
I am not 100% sure this is good enough.

2024-06-24 05:20 UTC, bossinc commented on pkg/tsdb/mssql/standalone/main.go
> +	//"github.com/grafana/grafana/pkg/setting"
```suggestion
```

2024-06-26 17:11 UTC, asimpson commented
/deploy-to-hg

2024-06-26 18:09 UTC, bossinc commented
/deploy-to-hg

2024-06-26 18:17 UTC, bossinc commented
/deploy-to-hg

2024-07-11 15:10 UTC, asimpson requested changes
Looks good, just one question from me.

2024-07-29 19:00 UTC, asimpson approved these changes
LGTM :rocket: Just need to get Drone to pass :crossed_fingers:

2024-08-26 20:09 UTC, merged