Folders: Fix folder pagination for cloud instances with many folders
grafana/grafana pull request #90008
Opened 2024-07-03 16:16 UTC by IevaVasiljeva

**What is this feature?**

Filter k6 folder out during the SQL query rather than during post processing to ensure that the correct number of results is always returned and that frontend keeps fetching folders until the end of the folder list is reached.

**Why do we need this feature?**

Filtering out the k6 folder after the results were fetched meant that we're returning one less result to the frontend, which the frontend interprets as reaching the end of the folder list.

We want to keep hiding the k6 folder, as we don't want users to store dashboards or alerts in it, accidentally delete it etc.

**Who is this feature for?**

HG users

**Special notes for your reviewer:**

I've tested this with:
* users and service accounts (service accounts should keep seeing the k6 folder)
* with over 100 root level folders (to ensure that pagination works correctly)

2024-07-03 19:07 UTC, DanCech approved these changes
Looks reasonable

2024-07-04 07:44 UTC, d14c approved these changes

2024-07-04 07:47 UTC, papagian commented
/deploy-to-hg

2024-07-04 11:17 UTC, papagian requested changes, later dismissed
I think that the query does not exclude nested folders under the excluded folder and dashboards living under them

2024-07-04 15:59 UTC, d14c commented on pkg/services/sqlstore/searchstore/filters.go
> +	filter := "dashboard.uid != ? AND (dashboard.folder_uid != ? OR dashboard.folder_uid IS NULL)"
@papagian as already discussed in slack, they should be only level of nesting in k6-app case, the addtional dashbaords have been used at some point as paceholders to alert the customers that the paremt folder is managed by k6-app and should not be deleted. Now that folders are hidden, those dushboards are not needed anymore. We have disabled provisioning dummy dashbaords in production and we will start deleting existing ones to remove any confusion.

2024-07-05 10:18 UTC, IevaVasiljeva commented on pkg/services/sqlstore/searchstore/filters.go
> +	filter := "dashboard.uid != ? AND (dashboard.folder_uid != ? OR dashboard.folder_uid IS NULL)"
Regarding org ID filter - it gets applied through a separate filter ([this one](https://github.com/grafana/grafana/blob/254610dce52073754d1cf52a6c0539f2f25f7b9b/pkg/services/sqlstore/searchstore/filters.go#L37-L43)), so I think that should be enough? We don't append org ID for any of the other UID filters (eg, `DashboardIDFilter` and `DashboardFilter`).

2024-07-05 10:18 UTC, IevaVasiljeva commented on pkg/services/folder/folderimpl/sqlstore.go
> +		if q.SignedInUser == nil || q.SignedInUser.GetID().Namespace() != identity.NamespaceServiceAccount {
Thanks for pointing it out! I'll keep this in mind for future PRs, and am also happy to rework this in the future if needed.

2024-07-05 10:19 UTC, merged