Change comment style for InfluxDb flux
grafana/grafana pull request #90160
Opened 2024-07-06 14:45 UTC by ArtistBanda

…  for influxDb

**What is this feature?**

This is feature is to change influxDb flux to have comment token as `//` instead of `--` in the code editor.

**Why do we need this feature?**

Incorrect comment token is not useful as it breaks the query as per the requirement

**Who is this feature for?**

Users using influxDB as source with flux code editor

**Which issue(s) does this PR fix?**:

Fixes #87021

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-07-31 12:49 UTC, itsmylife commented
Hi @ArtistBanda Thanks for the contribution and your patience. It looks nice but when we comment the line the color of the line is not changing. So it doesn't give the right feedback. I'd expect it will be with the color of the comment lines. Could you please also check that?

2024-08-03 18:04 UTC, ArtistBanda commented
> Hi @ArtistBanda Thanks for the contribution and your patience. It looks nice but when we comment the line the color of the line is not changing. So it doesn't give the right feedback. I'd expect it will be with the color of the comment lines. Could you please also check that?

Hi @itsmylife, I think we need to setup [monarch](https://microsoft.github.io/monaco-editor/monarch.html) for this. I am not sure if [Monaco Editor API](https://microsoft.github.io/monaco-editor/typedoc/index.html) has configuration for comment code color.

2024-08-15 22:17 UTC, itsmylife commented
> > Hi @ArtistBanda Thanks for the contribution and your patience. It looks nice but when we comment the line the color of the line is not changing. So it doesn't give the right feedback. I'd expect it will be with the color of the comment lines. Could you please also check that?
> 
> Hi @itsmylife, I think we need to setup [monarch](https://microsoft.github.io/monaco-editor/monarch.html) for this. I am not sure if [Monaco Editor API](https://microsoft.github.io/monaco-editor/typedoc/index.html) has configuration for comment code color.

In that case, I'd say let's skip monarch. I want to get feedback from @catherineymgui and @grafana/partner-datasources . Do you think this change will be good enough visually or should we search for colored feedback too?

2024-08-16 14:17 UTC, catherineymgui commented
I wonder if we should keep both methods of commenting so users who are already used to `--` don't get confused why their comments don't work anymore.

Also, yes I think we need to keep the colour since there's coloured comments in influx rn?

2025-05-20 23:06 UTC, bossinc approved these changes

2025-05-20 23:06 UTC, bossinc commented
Thank you for your contribution @ArtistBanda ! This got lost in the shuffle. Merging it now

2025-05-22 10:39 UTC, aangelisc requested changes
I'm not sure we want to use this vs adding support for Flux entirely.

The [Influx UI repository](https://github.com/influxdata/ui/tree/master/src/languageSupport/languages) does have language definitions..

2025-07-06 02:16 UTC, closed without merging