docs: updated table panel visualization
grafana/grafana pull request #90310
Opened 2024-07-10 21:30 UTC by srperf

**What is this feature?**

Updates to the table panel docs to include:

- modified a bit the description and reordered the beginning
- added a section mentioning the behavior when multiple data sets are present and added an image
- added a note on how to define max and minimums when using gauges as note. Looking forward for feedback on the best way to present this
- Transformed a section on Annotations and Alerts into a note. Looking forward to feedback on this change.

**Why do we need this feature?**

These changes will help users to understand better tables, some features that were not explained and flow better modifying some format.

**Who is this feature for?**

All Grafana users looking for docs on Table visualizations

**Which issue(s) does this PR fix?**:

None

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [x] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-07-11 15:06 UTC, imatwawana reviewed
Thanks for these additions! For now I've focused my review on wording, but I'm going to do a structural review when I've had some more time to think.

2024-07-11 15:06 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +The table visualization itself provides multiple functions.
```suggestion
The table visualization provides multiple functions.
```

2024-07-11 15:06 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +The table panel visualization will display a dropdown list at the bottom if the data queried contains multiple data sets.
```suggestion
If the data queried contains multiple data sets, a table displays a drop-down list at the bottom, so you can select the data set you want to visualize.
```

2024-07-11 15:06 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +![Table Panel with multiple data sets](/media/docs/grafana/panels-visualizations/TablePanelMultiSet.png 'Table Panel with multiple data sets')
Only alt text is required. FYI, please take a look at the [image naming guidelines](https://grafana.com/docs/writers-toolkit/write/image-guidelines/#media-asset-file-naming-conventions) for future reference. But don't worry about updating it for this PR.
```suggestion
![Table Panel with multiple data sets](/media/docs/grafana/panels-visualizations/TablePanelMultiSet.png)
```

2024-07-11 15:06 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +The maximum and minimum values of the Gauges will be configured automatically from the smallest and largest values in your whole data set. If you don't want the max/min values to be pulled from the w
```suggestion
The maximum and minimum values of the gauges are configured automatically from the smallest and largest values in your whole data set. If you don't want the max/min values to be pulled from the whole data set, you can configure them for each column with field overrides.
```

2024-07-11 17:37 UTC, srperf commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +- **Diverse Cell Types**: Elevate your data display with a variety of cell types, including: Colored text and backgrounds, Gauges, JSON, Images, Sparklines, and multiple combinations.
Agreed, I was unsure of adding this part myself and now more that you pint out the marketing sound 😛 
If it doesn't make much sense we could remove it completely.

2024-07-15 20:46 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +- **Diverse Cell Types**: Elevate your data display with a variety of cell types, including: Colored text and backgrounds, Gauges, JSON, Images, Sparklines, and multiple combinations.
Yeah, giving it more thought, I don't think this fits here. Let's take it out.
```suggestion
```

2024-07-15 20:50 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +{{% /admonition %}}
A heading must be followed by some body text. I'm okay with making this a note, but it should either be a note without a heading or plain text with a heading. Do you think people need this information enough to keep a heading? If not, then we should remove the heading and leave it as a note. Also just updating the format of the admonition.
```suggestion
{{< admonition type="note" >}}
Annotations and alerts are not currently supported for tables.
{{< /admonition >}}
```

2024-07-15 20:51 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +The table visualization provides multiple functions.
I'd like to not add this heading as my plan is to eventually move all the configuration options under a new H2 to group them better. That will make all of these other tasks and features a bit more prominent.
```suggestion
```

2024-07-15 20:51 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +### Sort column
```suggestion
## Sort column
```

2024-07-15 20:52 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +### Data set selector
```suggestion
## Data set selector
```

2024-07-15 20:53 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +{{% /admonition %}}
```suggestion
{{< admonition type="note" >}}
The maximum and minimum values of the gauges are configured automatically from the smallest and largest values in your whole data set. If you don't want the max/min values to be pulled from the whole data set, you can configure them for each column with field overrides.
{{< /admonition >}}
```

2024-07-15 20:54 UTC, imatwawana requested changes
I've reviewed the structure of the page and made some further suggestions for edits.

2024-07-16 13:35 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
```suggestion
```

2024-07-16 13:36 UTC, imatwawana commented on docs/sources/panels-visualizations/visualizations/table/index.md
> +![Table Panel with multiple data sets](/media/docs/grafana/panels-visualizations/TablePanelMultiSet.png)
```suggestion
![Table visualization with multiple data sets](/media/docs/grafana/panels-visualizations/TablePanelMultiSet.png)
```

2024-07-16 13:36 UTC, imatwawana approved these changes

2024-07-16 13:37 UTC, imatwawana commented
Thanks for making those changes!

2024-07-16 13:49 UTC, merged