Jaeger: Call search query with query range (#88156)
grafana/grafana pull request #90320
Opened 2024-07-11 08:51 UTC by EgorKluch

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-07-11 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=90320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=90320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=90320) it.</sub>

2024-07-11 10:48 UTC, orloffv commented
@fabrizio-grafana @joey-grafana Can you see this pr that fixes a critical bug?

2024-07-11 12:51 UTC, fabrizio-grafana commented
@orloffv I'm not working on the Jaeger plugin anymore, but I'm checking who is the new owner.

2024-07-11 13:05 UTC, fabrizio-grafana commented
Redirected to @grafana/oss-big-tent. Team, let me know if you need help with this!

2024-07-12 10:08 UTC, ivanahuckova requested changes
LGTM, but tests are failing so youu'll need to fix that first. I have added some suggestions bellow.

2024-07-12 10:08 UTC, ivanahuckova commented on public/app/plugins/datasource/jaeger/datasource.test.ts
> +  const defaultSearchRangeParams = `start=${Number(defaultQuery.range.from) * 1000}&end=${Number(defaultQuery.range.to) * 1000}`;
The tests are failing, you'll need to move `defaultQuery` up in the file. I'd suggest putting it just bellow `export const backendSr...`

2024-07-12 10:08 UTC, ivanahuckova commented on public/app/plugins/datasource/jaeger/datasource.test.ts
> +
```suggestion
  it('uses default range when no range is provided for search query,', async () => {
    const mock = setupFetchMock({ data: [testResponse] });
    const ds = new JaegerDatasource(defaultSettings);
    const query = {
      ...defaultQuery,
      targets: [{ queryType: 'search', refId: 'a', service: 'jaeger-query', operation: ALL_OPERATIONS_KEY }],
      // set range to undefined to test default range
      range: undefined,
    } as unknown as DataQueryRequest<JaegerQuery>;

    ds.query(query);
    expect(mock).toHaveBeenCalledWith({
      // Check that query has time range from 6 hours ago to now (default range)
      url: `${defaultSettings.url}/api/traces?service=jaeger-query&start=1704085200000000&end=2&lookback=custom`,
    });
  });
```

We shouldn't use `@ts-ignore` and we don't need to do stringify/parse the default query. We can just:

```
    const query = {
      ...defaultQuery,
      targets: [{ queryType: 'search', refId: 'a', service: 'jaeger-query', operation: ALL_OPERATIONS_KEY }],
      // Check that query has time range from 6 hours ago to now (default range)
      range: undefined,
    } as unknown as DataQueryRequest<JaegerQuery>;
```

2024-07-30 12:05 UTC, ivanahuckova approved these changes

2024-07-30 12:13 UTC, ivanahuckova commented
Hi @EgorKluch! Thank you so much for pointing out this bug and creating fix. I went ahead and added a commit that fixes the failing test and merged the PR. It is going to be part of the next 11.2 release.

2024-07-30 12:27 UTC, merged