Alerting: Use alerting API server for contact points list
grafana/grafana pull request #91073
Opened 2024-07-26 16:18 UTC by tomratcliffe

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

2024-07-31 11:05 UTC, konrad147 approved these changes

2024-07-31 11:06 UTC, konrad147 requested changes, later dismissed
WIP

2024-08-05 09:51 UTC, gillesdemey commented on public/app/features/alerting/unified/components/contact-points/useContactPoints.tsx
> +};
They will not; though there are ways to type this in TypeScript with [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) :D

2024-08-05 11:10 UTC, gillesdemey approved these changes
🚀 only a few nits

2024-08-05 11:19 UTC, konrad147 commented on public/app/features/alerting/unified/components/contact-points/useContactPoints.tsx
> +};
So I wonder if it might be better to split these into separate hooks with proper types? wdyt?

2024-08-05 12:39 UTC, tomratcliffe commented on public/app/features/alerting/unified/components/contact-points/useContactPoints.tsx
> +const useGetGrafanaContactPoints = ({ skip }: { skip?: boolean } = {}) => {
Done :+1:

2024-08-05 12:42 UTC, konrad147 approved these changes
LGTM!

2024-08-05 13:01 UTC, merged