WIP: Graphite: Explore UI fixes
grafana/grafana pull request #91192
Opened 2024-07-30 12:11 UTC by bucko909

Contains a number of bugfixes/improvements to the Graphite metric selection UI.

Fixes #91176

2024-07-30 12:28 UTC, bucko909 commented
Please see #91176 for more info. I've fixed only some of the issues, and need advice/help on the remainder.

2024-08-21 10:46 UTC, bucko909 commented
@JoaoSilvaGrafana Sorry, just picking a random assignee as I'm a bit stuck as to why this hasn't moved. Do I need to prod this somehow to get it moved forwards?

2024-08-21 10:52 UTC, bucko909 commented
Oh, seems like the ticket moved just 2 hours ago. I guess this is doing something, then?

2024-08-21 13:49 UTC, JoaoSilvaGrafana commented
Hey @bucko909 , sorry I completely missed this 😓 
I would say we should be skeptical of adding new props to `grafana-ui` components, we don't want to have them become too bloated and working different everywhere, for example after this change, some `Segment` will have the create option at the top and others at the bottom.
@tskarhed is working on building a new Select component, I am not sure if we have discussed having a create option or not and if that would show up at the top or bottom. This should be consistent across Grafana and if we want it at the top it should be at the top for every select. Would be interesting to get his input here 😄

2024-08-21 16:24 UTC, bucko909 commented
Note I'm not too bothered about the top/bottom-ness of the custom option, just that it should be the default to make the UI easier to use. It especially should be the default when it comes with a tip of "Hit enter to add"!

2024-10-01 19:16 UTC, joshhunt requested changes
Hi @bucko909 - thanks for the contribution.

This PR has been tricky for us to review because it loaded a few too many changes into one PR, so I'm going to close it for now.

If you're still keen to get some of these changes in, I would recommended submitting seperate PRs for each 'change'. Importantly, changes to Graphite logic must be seperate from `@grafana/ui` changes so we can get the two through independently.

I hope I don't discourage you from making future contributions, but I think this is the least fuss way to get changes though 👍

2024-10-01 19:16 UTC, joshhunt commented on packages/grafana-ui/src/components/Select/SelectBase.tsx
> +  }
This is a great change. It doesn't even need to be dependant on `createOptionPosition` - the message should just be changed to "Select to add"

2024-10-01 19:16 UTC, closed without merging