Encode row variables as URL components
grafana/grafana pull request #9162
Opened 2017-09-04 11:56 UTC by KCala

I've discovered an issue with the clickable cell link functionality 
https://github.com/grafana/grafana/pull/8738

When the link to another dashboard was generated, using variables from other rows they were not URL encoded properly, rendering the links unusable (not encoded quote marks were direct cause of the problem). This PR fixes this issue.

2017-09-04 11:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=9162) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=9162) before we can accept your contribution.<br/><hr/>**Kamil Cała** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=9162) it.</sub>

2017-09-07 08:15 UTC, torkelo commented
instead of encoding in the scoped vars you can pass an encoding function callback to the templateSrv.replace function here: https://github.com/KCala/grafana/blob/023bce4ef5b2814116d6b62bb1748dcb9f149043/public/app/plugins/panel/table/renderer.ts#L181 

For example try pass in function like  templateSrv.relace(str, scopedVars, function(value) {
return encodeURIComponent(value)
});

2017-10-04 19:02 UTC, torkelo commented
please sign CLA

2017-10-06 15:32 UTC, KCala commented
I have signed the CLI already and it says so on CLI assistant page. Not sure why the check on this GitHub page says I didn't

2017-10-13 20:18 UTC, josephholsten commented
@KCala when you committed this change, you did not use the same email in your commit's author field as you use in your github account. We cannot know that the person who authored the commit is the same person who signed the CLA without those being identical.

2017-11-10 17:16 UTC, danielfariati commented
I'm having the exact same problem described here.
I'd really appreciate if you fixed the CLA problem for this to be merged, @KCala.

2017-11-15 15:29 UTC, KCala commented
Sorry for taking so long. I've added the email used for this commit to my GitHub account and now everything seems to be in order.

2017-11-16 16:13 UTC, bergquist requested changes
@KCala great!

But I would still prefer the solution @torkelo mentioned. Making sure the values are encoding should be a render responsibility. Other users of the scope var might not be interested in the encoded version.

2017-12-05 10:40 UTC, torkelo commented
closing this due lack of updates, will reopen if changes are made.

2017-12-05 10:40 UTC, closed without merging

2018-02-09 15:33 UTC, Aceman87 commented
Has this been fixed elsewhere, any progress? I believe this is still an issue as quote marks in cell values still break links.

2018-02-11 14:33 UTC, bergquist commented
@Aceman87 In 5.0 and going forward Grafana does not support rows. So this won't be fixed.