A11y: Buttons in profile/sessions do not provide tooltips
grafana/grafana pull request #91858
Opened 2024-08-13 20:41 UTC by AbdessamadEnabih

What is this feature?
This feature adds a tooltip to a specific button in the sessions section of the application. The tooltip provides additional context for the button, enhancing its accessibility and usability.

Why do we need this feature?
Improving accessibility (A11y) is a priority for our application. By adding a tooltip to this button, we make the function of the button clearer, especially for users relying on assistive technologies, contributing to a more inclusive user experience.

Which issue(s) does this PR fix?
This PR addresses the lack of a tooltip on one specific button in the sessions section, ensuring that its purpose is easily understood by all users.

Fixes [#91836](https://github.com/grafana/grafana/issues/91836)

2024-08-13 20:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=91858) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=91858) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=91858) it.</sub>

2024-08-14 08:47 UTC, tskarhed reviewed
Great! Thank you! Just fix the comment I left and we're good to go! :)

2024-08-14 08:47 UTC, tskarhed commented on public/app/features/profile/UserSessions.tsx
> +                        tooltip={'Revoke user session'}
```suggestion
                        tooltip={t('user-session.revoke', 'Revoke user session')}
```
You could use the same approach as for the aria-label. This enables translations for the string.

2024-08-14 21:11 UTC, AbdessamadEnabih commented
Thank you for the review,  I fixed it.

2024-08-15 07:52 UTC, tskarhed approved these changes

2024-08-15 10:27 UTC, ashharrison90 requested changes, later dismissed
hey @AbdessamadEnabih 👋 

2 suggestions:
- let's name the key something like `profile.user-session.revoke-tooltip`
- once you've done that, you'll need to run `make i18n-extract` to extract the translations and commit those changes (you should see changes to `en/grafana.json` and `pseudo-LOCALE/grafana.json`

then we're good to go 🥳

2024-08-15 10:52 UTC, ashharrison90 approved these changes
lgtm 👍

2024-08-15 15:24 UTC, merged