Add basic logs enabled check
grafana/grafana pull request #92324
Opened 2024-08-22 16:55 UTC by alyssabull

This PR adds a check to ensure that if a user has Basic Logs disabled it will not complete the query.

2024-08-26 15:23 UTC, bossinc approved these changes

2024-08-27 18:51 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/utils.go
> +		return false, fmt.Errorf("basic Logs queries are disabled for this workspace")
```suggestion
		return false, fmt.Errorf("basic Logs queries are disabled for this data source")
```

2024-08-27 19:18 UTC, aangelisc requested changes
Nice work, just need to change which flag we're validating (and perhaps add a supporting test).

2024-09-06 18:04 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/utils.go
> +		return false, fmt.Errorf("basic logs queries are not enabled")
```suggestion
		return false, fmt.Errorf("basic logs queries are disabled for this data source")
```

2024-09-06 18:07 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/azure-log-analytics-datasource_test.go
> +		setBasicLogsEnabled    bool
I think you need to set this value on the `dsInfo` in order to appropriately use it.

2024-09-09 14:20 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/utils.go
> +		return false, fmt.Errorf("basic logs queries may only be run against Log Analytics workspaces")
```suggestion
		return false, errorsource.DownstreamError(fmt.Errorf("basic logs queries may only be run against Log Analytics workspaces"))
```

2024-09-09 14:21 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/utils.go
> +	if !basicLogsEnabled {
I'd suggest updating the error on the next line to reflect the actual problem 😊

2024-09-09 14:58 UTC, aangelisc commented on pkg/tsdb/azuremonitor/loganalytics/utils.go
> +		return false, errorsource.DownstreamError(fmt.Errorf("basic Logs queries are disabled for this workspace"), false)
```suggestion
		return false, errorsource.DownstreamError(fmt.Errorf("basic Logs queries are disabled for this data source"), false)
```

2024-09-09 14:58 UTC, aangelisc approved these changes
LGTM, nice work @alyssabull!

2024-09-09 19:35 UTC, merged