PanelEdit: Edit the source panel, refactor out VizPanelManager, simplify
grafana/grafana pull request #93045
Opened 2024-09-06 14:00 UTC by torkelo

* [x] Edit & render source panel. Radically simplifies and removes a lot of complex code in multiple locations 
* [x] Make the different components of PanelEditor more standalone (ie they no longer reference VizPanelManager but handle things that are relevant themselves). PanelOptionsPane handles changing panel plugin, PanelDataQueriesTab handles loading/changing data source, updating queries etc. 
* [x] Remove VizPanelManager. it serves no purpose and adds complexity, spread out the logic in it where it was called from
* [x] Discard restores original state 
* [ ] Save from panel edit should reset original state (that is set when you discard). 
* [x] Repeat options work 
* [ ] Repeat options that should display conditionally (when variable is setI)
* [x] Panel inspector works (now without any special panel edit logic)
* [x] Save work (now without any special panel edit logic)
* [ ] Update PanelEditor tests
* [ ] Move VizPanelManager tests to where the logic was moved
* [ ] Update DataPlane tests 
* [ ] Make library panel editing work 
* [ ] Make library panel editing of repeat options work

2024-09-07 07:33 UTC, torkelo commented on public/app/features/dashboard-scene/panel-edit/PanelDataPane/DataProviderSharer.tsx
> +export class DataProviderSharer extends SceneObjectBase<DataProviderSharerState> implements SceneDataProvider {
this is a util data provider (that we maybe should add to scenes lib), that allow one scene object to share the data from another. Used by the table view to share the data from the original panel

2024-09-09 09:45 UTC, torkelo commented
The only thing not working exactly like before is when you edit a repeated panel, your editing the "template" panel, not one of the repeats so you get no local variable (scoped var), so the variable has all the values. So depending on your query this could lead to issues but it also feels more correct, your editing a panel that you are repeating based on a variable, so while in panel edit it will have all values. 

I see two options
* A. Keep as is in this PR, if the variable you repeat by has multiple values it will have multiple values in panel edit
* B. We could change the variable when you go into panel edit to only a single value (if multiple valued) and restore the value when leaving panel edit 

for panels inside repeated rows it just works as the panel being rendered is the panel inside the first row so has a local scoped variable. The problem is repeated panels inside DashboardGridItem where you edit state.body not the first state.repeatedPanels[0]

2024-09-09 13:19 UTC, torkelo commented
Just fixed the above mentioned issue by adding the same variable scope as the first repeated panel to the state.body VizPanel of a DashbordGridItem (the template panel)

2024-09-11 11:33 UTC, kaydelaney commented
Amazing work on this! Tested out the PR but it seems like discard panel changes doesn't seem to be working:

https://github.com/user-attachments/assets/e796f256-2a4d-4d3e-bb4f-6bb24452513f

2024-09-11 13:58 UTC, kaydelaney reviewed
Looks good! Just some small nits, feel free to ignore.

2024-09-11 14:05 UTC, torkelo commented
@kaydelaney thanks for the review! and for finding the discard issue, had not tested discarding query runner changes, only VizPanel level state. fixed (and added test for it).

2024-09-12 07:58 UTC, dprokop reviewed
Code looks good, a small nit comment only.

I found a bug tho. Try the attached dashboard. Edit second panel - change viz type, and discard changes. Runtime error occurs, seems like panel options change is buggy with this PR.


<details>
<summary>dash json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 2512,
  "links": [],
  "panels": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "fdloj1mdh4jcwe"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisBorderShow": false,
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "barWidthFactor": 0.6,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "links": [
            {
              "title": "Filter",
              "url": "http://localhost:3000/d/bdmh0z3p3pf5sa/filters-demo?var-query0=code%7C%3D%7C${__field.labels.code}"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 16,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "pluginVersion": "11.3.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "fdloj1mdh4jcwe"
          },
          "disableTextWrap": false,
          "editorMode": "builder",
          "expr": "rate(prometheus_http_requests_total{code=~\"500|503|400\"}[$__rate_interval])",
          "fullMetaSearch": false,
          "hide": false,
          "includeNullMetadata": false,
          "instant": false,
          "legendFormat": "__auto",
          "range": true,
          "refId": "A",
          "useBackend": false
        }
      ],
      "title": "filter applicable",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "prometheus",
        "uid": "fdloj1mdh4jcwe"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "links": [
            {
              "title": "Filter",
              "url": "http://localhost:3000/d/bdmh0z3p3pf5sa/filters-demo?var-query0=code%7C%3D%7C${__field.labels.code}"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 16,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 3,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "percentChangeColorMode": "standard",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showPercentChange": false,
        "textMode": "auto",
        "wideLayout": true
      },
      "pluginVersion": "11.3.0-pre",
      "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "fdloj1mdh4jcwe"
          },
          "disableTextWrap": false,
          "editorMode": "builder",
          "expr": "rate(prometheus_http_requests_total{code=~\"500|503|400\"}[$__rate_interval])",
          "fullMetaSearch": false,
          "hide": false,
          "includeNullMetadata": false,
          "instant": false,
          "legendFormat": "__auto",
          "range": true,
          "refId": "A",
          "useBackend": false
        }
      ],
      "title": "filter applicable",
      "type": "stat"
    }
  ],
  "preload": false,
  "schemaVersion": 39,
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "text": "",
          "value": ""
        },
        "name": "query2",
        "options": [],
        "query": "",
        "refresh": 1,
        "regex": "",
        "type": "query"
      },
      {
        "current": {
          "text": [
            ""
          ],
          "value": [
            ""
          ]
        },
        "name": "GroupBy",
        "type": "groupby"
      },
      {
        "baseFilters": [],
        "datasource": {
          "type": "prometheus",
          "uid": "fdloj1mdh4jcwe"
        },
        "filters": [
          {
            "condition": "",
            "key": "handler",
            "keyLabel": "handler",
            "operator": "!=|",
            "value": "/-/quit",
            "valueLabels": [
              "/-/quit",
              "/-/ready",
              "/-/reload",
              "/alerting/",
              "/alerts",
              "/admin",
              "/api/alert-notifiers",
              "/alerting/*",
              "/api/datasources/proxy/uid/:uid/*",
              "/api/ds/query",
              "/api/health",
              "/api/user/preferences",
              "/api/short-urls",
              "/api/v1/series",
              "/api/frontend/settings/",
              "/-/healthy",
              "/api/frontend/assets",
              "/dashboards/",
              "/consoles/*filepath",
              "/api/v1/admin/tsdb/clean_tombstones",
              "/api/folders/",
              "/favicon.ico",
              "/api/user/password/send-reset-email"
            ],
            "values": [
              "/-/quit",
              "/-/ready",
              "/-/reload",
              "/alerting/",
              "/alerts",
              "/admin",
              "/api/alert-notifiers",
              "/alerting/*",
              "/api/datasources/proxy/uid/:uid/*",
              "/api/ds/query",
              "/api/health",
              "/api/user/preferences",
              "/api/short-urls",
              "/api/v1/series",
              "/api/frontend/settings/",
              "/-/healthy",
              "/api/frontend/assets",
              "/dashboards/",
              "/consoles/*filepath",
              "/api/v1/admin/tsdb/clean_tombstones",
              "/api/folders/",
              "/favicon.ico",
              "/api/user/password/send [...]

2024-09-12 09:22 UTC, bfmatei reviewed
I didn't get the chance to test this thoroughly, but the code itself looks good.

2024-09-12 10:05 UTC, torkelo commented
> Testing this more, seems like discard doesn't work in many cases. I.e. add panel -> change panel title -> discard -> runtime error

@dprokop unable to replicate, discard always works for me. strange, is there something else on the dashboard you have?

2024-09-12 10:09 UTC, torkelo commented
@dprokop ah, I missed you had a new panel. I can replicate it there. 

will fix, something wrong with the isNewPanel logic

2024-09-12 11:42 UTC, torkelo commented
@dprokop Pushed another update to make discard even more rebust for some new edge cases. 

To solve those I added a new loading (initalization) phase to PanelEditor so that it waits for the panel plugin to load before initializing options pane and setting the original state discard will discard to. This is needed for full page reload of panels that auto migrate from angular to react or just panels with option migrations. The trick is for PanelEditor to wait until plugin is loaded before it set the state discard will discard to.

this waiting for plugin to load before initializing is great and was something I wanted to add anyway as it will help going into panel edit directly (full pag reload) for lib panels, we can remove the wait for lib panel to load in DashboardUrlSync (but will do that in a a follow-up PR).

2024-09-12 11:43 UTC, torkelo commented
added a new unit tests to PanelEditor for the waiting / init phase and made all those test async so they wait for the plugin to load

2024-09-13 08:20 UTC, torkelo commented on public/app/features/dashboard-scene/panel-edit/PanelDataPane/DataProviderSharer.tsx
> +export class DataProviderSharer extends SceneObjectBase<DataProviderSharerState> implements SceneDataProvider {
@dprokop https://github.com/grafana/scenes/pull/903

2024-09-24 14:59 UTC, mdvictor commented
I think there is an issue with repeated panels here. If you edit a repeated panel and go back to the dashboard the changes aren't saved:

https://github.com/user-attachments/assets/36bde1cb-8550-4929-8166-0e9bd6e8a226

2024-09-24 15:02 UTC, kaydelaney approved these changes
Amazing work! Looks good, and couldn't find any issues with manual testing

2024-09-24 15:06 UTC, kaydelaney requested changes
Oops, looks like I approved too early - seems like Oscar found some issues

2024-09-24 15:06 UTC, oscarkilhed reviewed
https://github.com/user-attachments/assets/e51f48fa-5c4d-4f38-b58a-9dc340154bba


https://github.com/user-attachments/assets/2ff284cc-020b-4638-93e9-fa0d7fb3617b

Found these issues where stat and gauge panel does not update for all options. The update is visible once some other option changes.

2024-09-24 15:11 UTC, kaydelaney commented
Checked the issues @oscarkilhed pointed out against main and I was able to reproduce both, so I don't think they're caused by this PR.

2024-09-24 15:12 UTC, kaydelaney approved these changes
Reapproving! LGTM!

2024-09-24 15:13 UTC, merged