Change from Apps to "More Apps"
grafana/grafana pull request #93454
Opened 2024-09-18 20:30 UTC by timlevett

**What is this feature?**

This is a label change for the "other" bucket of apps in the menu.

**Why do we need this feature?**

Right now in Grafana Cloud there is both "Apps" and "Applications", by prefixing Apps with More it signifies that this is an other bucket, and not application observability.

**Who is this feature for?**

Detail oriented users.

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

2024-09-18 20:31 UTC, timlevett commented
/deploy-to-hg

2024-09-23 15:14 UTC, timlevett commented
/deploy-to-hg

2024-09-25 09:24 UTC, ashharrison90 requested changes
you don't need to directly edit the translation files. see the internationalisation documentation [here](https://github.com/grafana/grafana/blob/main/contribute/internationalization.md). instead:
- edit the translation [here](https://github.com/grafana/grafana/blob/timlevett/more-apps/public/app/core/utils/navBarItem-translations.ts#L141)
- run `make i18n-extract`

edit: forgot to add, i don't really have a strong opinion on the naming either way 🤷

2024-09-25 09:24 UTC, ashharrison90 commented on pkg/services/navtree/navtreeimpl/applinks.go
> +				Text:       "More Apps",
this should be sentence case: `More apps`

2024-09-25 10:34 UTC, joshhunt reviewed
pushed up:
 - changed case to `More apps`
 - removed manual changes from translations (that happens in a workflow outside of the PR)
 - ran i18n-extract to get everything all good :)

2024-09-25 10:45 UTC, ashharrison90 approved these changes
lgtm 👍

2024-09-25 12:35 UTC, uxdmitryn commented
LGTM 👍

2024-10-01 10:31 UTC, merged