Support tls config for webhook receiver
grafana/grafana pull request #93513
Opened 2024-09-19 23:49 UTC by titolins

Takes advantage of https://github.com/grafana/grafana/pull/92331, applying basically the same logic from mqtt receivers into webhook to fix #9548.

## Related PR's
- https://github.com/grafana/alerting/pull/247

2024-09-19 23:50 UTC, titolins commented on go.mod
> +replace github.com/grafana/alerting => /Users/titolins/dev/alerting
Leaving this here just as a reminder to update alerting once https://github.com/grafana/alerting/pull/247 has been merged

2024-09-20 10:37 UTC, fayzal-g approved these changes
LGTM, just a couple nits

2024-09-20 10:37 UTC, fayzal-g requested changes
Removing previous approval, as it needs the PR from grafana/alerting to go in first. Will re-review once that's done

2024-09-20 11:26 UTC, titolins commented on .github/CODEOWNERS
> +/devenv/docker/blocks/caddy_tls/ @grafana/alerting-backend
Ah, my bad - hadn't noticed that. Fixed now 👍

2024-10-17 09:43 UTC, brendamuir commented
docs lgtm

2024-10-22 10:08 UTC, fayzal-g approved these changes
Small typo in the doc but lgtm!

2024-10-22 10:44 UTC, merged