Update script to make it use OpsGenie's REST API
grafana/grafana pull request #9399
Opened 2017-10-02 13:48 UTC by cglrkn

The script is making API calls to the deprecated OpsGenie Web API, we updated the script to make it use new OpsGenie's REST API.

2017-10-02 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=9399) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=9399) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=9399) it.</sub>

2017-10-03 07:21 UTC, bergquist requested changes
Looks good. Just want some minor adjustments for building the url for closing the alert

2017-10-03 07:21 UTC, bergquist commented on pkg/services/alerting/notifiers/opsgenie.go
> +		Url:        fmt.Sprintf("%s/%s/close?identifierType=alias", opsgenieAlertURL,"alertId-"+strconv.FormatInt(evalContext.Rule.Id, 10)),
I think the string can be replaced with `fmt.Sprintf("%s/alertId-%d", opsgenieAlertURL, evalContext.Rule.Id)`

2017-10-03 12:15 UTC, cglrkn commented
I updated the code according to your request. However, we need to put /close?identifierType=alias to make a successful request. Thus, I build the first part as you suggested and added /close?identifierType=alias at the end.

2017-10-04 07:09 UTC, bergquist approved these changes

2017-10-04 07:10 UTC, bergquist commented
@cglrkn Oh thanks for spotting that! :)

Thank you for contributing to Grafana

2017-10-04 07:12 UTC, bergquist requested changes

2017-10-04 07:12 UTC, bergquist commented on pkg/services/alerting/notifiers/opsgenie.go
> +		Url:        fmt.Sprintf("%s/alertId-%d/close?identifierType=alias", opsgenieAlertURL, evalContext.Rule.Id)
The line is missing a comma at the end. otherwise it wont compile

2017-10-04 07:13 UTC, bergquist commented
@cglrkn Oh thanks for spotting that! :)

Still a minor change needed for this PR to compile. Will merge once its fixed.

2017-10-04 07:19 UTC, cglrkn commented
Added the comma, sorry for missing that.

2017-10-04 14:01 UTC, bergquist commented
No worries! 

The build is still failing. Seems like some formatting issue. Please run `gofmt -w ./pkg` in the grafana root folder.

2017-10-05 05:43 UTC, cglrkn commented
I run the command. Thanks! @bergquist

2017-10-05 07:55 UTC, bergquist approved these changes

2017-10-05 07:56 UTC, bergquist commented
@cglrkn Awesome! thank you for contributing to Grafana! :)

2017-10-05 07:56 UTC, merged