Prometheus: Fix query editor crash in response to invalid query
grafana/grafana pull request #94421
Opened 2024-10-08 15:07 UTC by devluisrodrigues

**What is this feature?**

This feature improves error handling in Grafana's Prometheus explorer, preventing crashes from invalid queries by providing feedback. It adds optional chaining to handle missing values. Integration tests are also added to prevent future issues.

**Why do we need this feature?**

We need this feature to fix the open issue where Grafana crashes when handling invalid Prometheus queries. Instead of crashing, the editor should provide feedback on query errors.

**Who is this feature for?**

This feature is for Grafana users, especially developers and engineers working with Prometheus queries in the Explore section.

**Which issue(s) does this PR fix?**:

Fixes #94219 

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

2024-10-08 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=94421) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=94421) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=94421) it.</sub>

2024-10-10 21:45 UTC, NWRichmond requested changes
Thanks for this contribution, @devluisrodrigues!

A few suggestions:
- Let's only use optional chaining where required
- Please ensure that any new or changed tests pass
- With respect to testing, the guidance in https://github.com/grafana/grafana/issues/94219#issue-2564245262 is:
> A higher-level integration test in `packages/grafana-prometheus/src/querybuilder/operationUtils.test.ts` could help to guard against future regressions.

What we mean by "a higher-level integration test" is a test of a function that calls `renderParams` (either directly or indirectly). We want to test for the expected behavior (a problematic query doesn't crash the [Query Editor in Code Mode](https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/#code-mode)) instead of unit testing the `renderParams` function. Please let me know if I can help clarify this further :). If a higher-level integration test is too cumbersome, I think we'd prefer to accept this PR without new tests than with a unit test of `renderParams`.

2024-10-11 00:57 UTC, devluisrodrigues commented on packages/grafana-prometheus/src/querybuilder/operationUtils.test.ts
Perfect, I misunderstood the testing part and got a little lost. I'll remove the unit test for renderParams. Thank you for your time! :)

2024-10-11 01:09 UTC, devluisrodrigues commented on packages/grafana-prometheus/src/querybuilder/operationUtils.test.ts
Sorry for the missing imports, I got a little confused with my local repository. Initially, I was hesitant to add unnecessary code, but I made a mistake and forgot to add the imports at the beginning. Sorry for that. Anyway, as you mentioned preferring the PR without the unit tests, I’ve just committed a change to remove them.

2024-10-11 01:12 UTC, devluisrodrigues commented
Hey @NWRichmond, thank you very much for taking the time to review my contribution and provide feedback.

I’ve just committed the changes you suggested, and I believe all the necessary adjustments have been made in this PR.

I’ll now do my best to simulate a high-level test.

2024-10-11 01:26 UTC, devluisrodrigues commented on packages/grafana-prometheus/src/querybuilder/operationUtils.ts
> +    const paramDef = def?.params?.[index];
Okay, thank you for the explanation. I'll remove the unnecessary chaining operations.

2024-10-18 11:00 UTC, devluisrodrigues commented
Hey @NWRichmond, I just built the application and tested the error:
![Screenshot from 2024-10-18 07-58-08](https://github.com/user-attachments/assets/9416e0bd-64a1-4a82-ac76-061333124375)

It's working as expected!
If you need anything else, feel free to ask! :)

2024-10-28 15:46 UTC, NWRichmond commented
Thank you for the updates! I'll review them this week :)

2024-11-01 19:25 UTC, NWRichmond approved these changes
Thanks for the updates, @devluisrodrigues, and thanks for contributing to Grafana!

Approving now, but let's wait to merge this until next week.

2024-11-04 16:11 UTC, NWRichmond commented
Hi @devluisrodrigues! If you could please sign the Contributor License Agreement, the rest of the CI/CD checks should work: https://cla-assistant.io/grafana/grafana?pullRequest=94421

2024-11-04 16:33 UTC, devluisrodrigues commented
> Hi @devluisrodrigues! If you could please sign the [Contributor License Agreement](https://github.com/grafana/grafana/pull/94421#issuecomment-2400117648), the rest of the CI/CD checks should work: https://cla-assistant.io/grafana/grafana?pullRequest=94421

oh sorry, about that. I just signed the License!

2024-11-04 17:20 UTC, devluisrodrigues commented
Sorry @NWRichmond, I pressed by mistake the request review button.

2024-11-05 15:29 UTC, merged