WIP - Alerting: `Add example` dropdown in the Edit notification template view
grafana/grafana pull request #94711
Opened 2024-10-15 09:43 UTC by ppcano

Fixes https://github.com/grafana/grafana/issues/93686 -> ` Alerting UI: Display common examples of notification templates`  

![add-examples_1](https://github.com/user-attachments/assets/897c2139-5001-4bff-bc75-ca692d4e9288)

This PR should be merged after https://github.com/grafana/grafana/pull/94069,  which brings updates to the templating documentation.

2024-10-17 11:43 UTC, brendamuir commented
@ppcano i see the generic "alerts" here - do we wnat to be more specific and use alert instance so we are consistent?

2024-10-17 14:25 UTC, ppcano commented
> do we wnat to be more specific and use alert instance so we are consistent?

@brendamuir, this has been a recurring issue, even across the docs. It seems the discussion and decision are still ongoing.

At the moment, I lean toward using the term "alert" for two reasons:
1 - the name of the template variable is `.Alerts` 
2 - the documentation uses the term "alerts" as well:

<img width="1041" alt="Screenshot 2024-10-17 at 16 20 09" src="https://github.com/user-attachments/assets/6fa2907c-317f-43c1-a837-612e34a14c99">

2024-10-23 09:46 UTC, soniaAguilarPeiron approved these changes
Nice one! 🚀

2024-10-23 10:18 UTC, gillesdemey requested changes

2024-10-23 10:18 UTC, gillesdemey commented on public/app/features/alerting/unified/components/receivers/TemplateForm.tsx
> +                                        url="https://grafana.com/docs/grafana/latest/alerting/configure-notifications/template-notifications/examples/"
This one seems to 404 for me; @ppcano can we update this before merging?

2024-10-23 13:01 UTC, gillesdemey approved these changes

2024-10-23 13:01 UTC, merged