OAuth: Refactor OAuthToken service to make it easier to use the new external sessions
grafana/grafana pull request #96667
Opened 2024-11-19 11:24 UTC by mgyongyosi

**What is this feature?**

- Introduces a new interface called `user.SessionAwareIdentityRequester` and extends the user.Identity struct to return the current `SessionToken` which contains information about the ExternalSession.
- Replaces `*login.UserAuth` parameters with `user.SessionAwareIdentityRequester` (this is also required for integrating the improved session handling)

This is a precursor for https://github.com/grafana/grafana/pull/96655 and most of these changes are already in that PR, but decided to split it to make it easier to review.

**Why do we need this feature?**
Make it easier to replace the current AuthInfo based solution with ExternalSession.

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Relates to https://github.com/grafana/identity-access-team/issues/927
Relates to https://github.com/grafana/grafana/pull/96655

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

2024-11-19 12:19 UTC, linoman approved these changes

2024-11-19 12:34 UTC, dmihai approved these changes

2024-11-19 14:14 UTC, kalleep requested changes
I don't think we should extend / add more to requester interface. This will cause us more troubles in the future. Lets talk a bit about other possible solutions

2024-11-21 09:23 UTC, kalleep approved these changes

2024-11-21 13:36 UTC, merged