Scopes: Move URL values from selector to facade
grafana/grafana pull request #96842
Opened 2024-11-21 13:56 UTC by bfmatei

**What is this feature?**

This PR moves the URL values sync from the selector to the facade.

**Why do we need this feature?**

This is needed because there was an additional `URLSyncManager` created only for the purpose of scopes. However, given that the facade is consumed by scenes that are enrolled into a `URLSyncManager`, there is no need for the former.

From a technical point of view:
- removed the additional `URLSyncManager`
- moved the URL sync mechanism from the scopes selector scene into the scopes facade

This fixes a couple of issues with scopes persistence between page navigations within the same session as well as removes a nasty workaround (the additional `URLSyncManager`).

**Who is this feature for?**

-

**Which issue(s) does this PR fix?**:

-

**Special notes for your reviewer:**

Please check that:
- [x] It works as expected from a user's perspective.
- [x] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

2024-11-25 09:29 UTC, mdvictor requested changes
I think there is a problem with this current refactor, the scopes aren't maintained at all on page reload now. Setting a scope on a dashboard sets the url correctly, but on page reload the scope is entirely removed.

2024-11-25 11:19 UTC, bfmatei commented
Thanks @mdvictor . I fixed the issue, can you have a look again over it?

2024-11-25 15:36 UTC, mdvictor commented
Yeah, looks good, persists url state on refresh. 

https://github.com/user-attachments/assets/18d442f6-999f-4133-a12a-039542b44e6b


This is a bit nitty, but scope names are pulled in lowercase from the url and then immediately turned upper case on refresh, which looks a bit weird.

2024-11-25 16:24 UTC, bfmatei commented
This is the actual behavior currently on `main` as well. The rationale is that the scopes need to be read before having their details pulled from backend.

2024-11-25 16:24 UTC, bfmatei commented
This is the actual behavior currently on `main` as well. The rationale is that the scopes need to be read before having their details pulled from backend.

2024-11-26 14:41 UTC, mdvictor approved these changes
I understand now, thank you!

LGTM!

2024-11-26 14:43 UTC, merged