First draft of a Prometheus 2.0 Stats dashboard
grafana/grafana pull request #9762
Opened 2017-11-01 21:34 UTC by cboggs

Here's a first stab at a Prometheus 2.0 default dashboard, as per #9759.

2017-11-01 21:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana?pullRequest=9762) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana?pullRequest=9762) before we can accept your contribution.<br/><hr/>**Cody Boggs** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana?pullRequest=9762) it.</sub>

2017-11-01 21:38 UTC, cboggs commented
CLA is signed, just waiting for the box to flip to green. :-)

2017-11-02 06:53 UTC, bergquist commented
Please add the email address you used in the git commit to your github account. That's how the CLA bot matches commit with the list of contributors.

2017-11-02 14:23 UTC, cboggs commented
Ok, added and confirmed it seems. Sorry for the confusion - had an old (inaccessible) email address in my local config that I forgot about. :-)

I amended and tried to squash and force push to my branch, but it didn't get remove the old user. Can re-open if that works better?

2017-11-06 07:49 UTC, Gouthamve commented
Hi, so I am just imported this dashboard and as someone who has not run Prometheus in serious environments in a long-time, I don't think I'm the right person either. A few comments though:

Not sure if its right, but importing it is throwing an error. Somehow the datasource is not being set right throwing: `Datasource named ${DS_LOCAL-P8S} was not found`

Also, the templating is broken. I think instead of picking `localhost`, it is picking `localhost:9090` which breaks the `$node.*` by not selecting `node_exporter` metrics. Also the templating assumes `node_exporter` is running and I am not sure including those metrics in a Prometheus default dashboard is right.

My small server's snapshot: https://snapshot.raintank.io/dashboard/snapshot/0mspq3nfItd0sNoZ7kZ03rIVUeKkLybO

2017-11-06 08:03 UTC, gouthamve reviewed
Few minor nits

2017-11-06 08:03 UTC, Gouthamve commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +              "expr": "node_memory_Mapped{instance=~'[[node]].*'}",
`$node` was used above.

2017-11-06 08:03 UTC, Gouthamve commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +              "expr": "sum by (mode)(irate(node_cpu{mode='user', instance=~'[[node]].*', _ftio=\"\"}[5m]))",
`_ftio`?

2017-11-06 10:00 UTC, tinytub reviewed
after imported and try

2017-11-06 10:00 UTC, tinytub commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +        "regex": "",
node template maybe could use a regex like `"regex": "(.*):\\d+",`,
prometheus exporter path and node_exporter exporter path always with  diffrent port, will cause `instance=~'[[node]].*'` can not get right node address

2017-11-06 14:13 UTC, cboggs commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +              "expr": "sum by (mode)(irate(node_cpu{mode='user', instance=~'[[node]].*', _ftio=\"\"}[5m]))",
Oops, missed some copy/paste queries.

2017-11-06 14:15 UTC, cboggs commented
Agreed that assuming node_exporter presence is probably not wise for a built-in. Will adjust to remove it and it should simplify things considerably.

2017-11-06 15:35 UTC, cboggs commented
@gouthamve, @tinytub, I believe I've cleaned it up a bit. Should be working better now, re-tested with a clean local Prometheus + Grafana. Let me know if you see other changes to be made, thanks for the feedback!

2017-11-13 09:33 UTC, danielmarbach commented
There is also https://grafana.com/dashboards/3662

2017-11-14 11:31 UTC, Gouthamve commented
@cboggs This imports cleanly :) One nit:
* `scrape_duration_seconds` is the metric for scrape duration and not `prometheus_target_interval_length_seconds`

A suggestion:
* Showing the number of rule_iterations and missed_iterations would also help.

2017-11-14 16:22 UTC, cboggs commented
@Gouthamve, done and done! Not sure where I picked up the `prometheus_target_interval_length_seconds` - good catch! Thanks for the inputs. :-)

2017-11-16 16:02 UTC, bergquist commented
@Gouthamve @cboggs anything else you want to add before I merge this? :)

2017-11-16 17:33 UTC, cboggs commented
@bergquist unless @Gouthamve has any suggestions, I'm happy with it. :-)

2017-11-16 18:45 UTC, gouthamve requested changes
Well, another minor nit with the legend format :P 

Other than that :+1: Once that is fixed, you can merge without waiting for my review :)

2017-11-16 18:45 UTC, Gouthamve commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +              "legendFormat": "{{quantile}}",
Legend format wrong

2017-11-16 18:45 UTC, Gouthamve commented on public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json
> +              "expr": "max(scrape_duration_seconds{job=\"prometheus\"})",
Can this be over all jobs? Like `topk(5, max(scrape_duration_seconds) by (job))`

If that is the case then legend should be: `{{job}}`

2017-11-20 16:57 UTC, cboggs commented
Excellent, I didn't pay attention to the fact that `scrape_duration_seconds` was broken up per target. :+1: Updated @Gouthamve and @bergquist. 

Thanks again!

2017-11-21 09:13 UTC, bergquist commented
Merged by https://github.com/grafana/grafana/commit/14b8bd35ed76f35bc4fe7596204cd9b30ef98d24

Not sure why github dont flag this as merged.

2017-11-21 09:13 UTC, closed without merging