pie chart orgnize field
grafana/grafana pull request #97713
Opened 2024-12-10 03:53 UTC by yincongcyincong

Fixes #97626

2025-01-06 15:47 UTC, gelicia requested changes
Is there a way we could conditionally remove this sort?

2025-01-07 07:08 UTC, yincongcyincong commented
> Is there a way we could conditionally remove this sort?

@gelicia thanks for your review. i modified code to check if use specific transformation or not. please take a look.

2025-01-15 02:36 UTC, yincongcyincong commented
@godfreyhe does this pr have some progression?  please take a look, thanks

2025-01-17 02:19 UTC, yincongcyincong commented
@gelicia could you please tell me there are some progression in this pr.  thanks.

2025-10-09 11:38 UTC, closed without merging