SecretService: Feature branch
grafana/grafana pull request #97837
Opened 2024-12-12 11:43 UTC by dana-axinte

**What is this feature?**

[Add a brief description of what the feature or update does.]

**Why do we need this feature?**

[Add a description of the problem the feature is trying to solve.]

**Who is this feature for?**

[Add information on what kind of user the feature is for.]

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

Please check that:
- [ ] It works as expected from a user's perspective.
- [ ] If this is a pre-GA feature, it is behind a feature toggle.
- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/contribute/release-notes/#how-to-determine-if-content-belongs-in-whats-new), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/contribute/release-notes/) doc.

2024-12-13 13:05 UTC, PoorlyDefinedBehaviour commented
/deploy-to-hg

2024-12-16 14:33 UTC, PoorlyDefinedBehaviour commented
/deploy-to-hg

2024-12-16 14:57 UTC, macabu commented
/deploy-to-hg

2025-02-19 09:57 UTC, jdbaldry commented on docs/sources/setup-grafana/configure-grafana/feature-toggles/index.md
> +| `secretsManagementAppPlatform`              | Enable the secrets management API and services under app platform
Looks like this is an off-by-one error that should actually be reported on the next line.

2025-03-19 10:19 UTC, macabu requested changes
To avoid accidental clicks/merging to main

2025-08-04 06:24 UTC, closed without merging