Panel Legend: median value disappear
grafana/grafana pull request #98184
Opened 2024-12-18 12:27 UTC by yincongcyincong

Fixes #98140
![image](https://github.com/user-attachments/assets/7c928531-de44-4924-982e-619550ea6660)

2024-12-23 08:20 UTC, yincongcyincong commented
@leeoniya bro, could you please take a look this pr? thanks

2025-01-09 12:49 UTC, yincongcyincong commented
@Develer bro, could you please take a look this pr. thanks

2025-01-09 14:43 UTC, gelicia commented
I am unable to recreate your issue - can you provide any other replication steps to reliably replicate it, preferably using the [testdata datasource](https://grafana.com/docs/grafana/latest/datasources/testdata/)?

2025-01-09 16:34 UTC, gelicia requested changes
Hello, thank you for this PR! After some discussion, we decided we don't want this calculation to be implicitly calculated as part of the standard set, but calculated on demand instead. Could you change the option to follow the pattern used by other non-standard reducers? See something like [distinctCount](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/transformations/fieldReducer.ts#L383) for what that looks like. If youd like, I can take care of it. Thank you!

2025-01-10 01:46 UTC, yincongcyincong commented
@gelicia i modified the code. please take a look. thanks.

2025-01-10 14:38 UTC, gelicia requested changes

2025-01-10 14:38 UTC, gelicia commented on packages/grafana-data/src/transformations/fieldReducer.ts
> +  let numbers: any[] = [];
I think we should be doing the same type checking as was there previously - avoiding `any` to have this be `number` and then ensuring the value is a number before it's added to the median. Sort will have weird behaviors if this is mixed as strings and numbers. 

Just trying to have it match the go equivalent here https://github.com/grafana/grafana/pull/91119/files#diff-a86ecb852faf2c362cd80fb9ac99614fc92dd6ffe3a1bc870a3618437b176254R103  - I think after we ensure the values are numbers, we're good on that.

2025-01-13 02:03 UTC, yincongcyincong commented on packages/grafana-data/src/transformations/fieldReducer.ts
> +  let numbers: any[] = [];
thanks for your review. i modifed the code. please take a look.

2025-01-14 01:55 UTC, yincongcyincong commented
@gelicia  i modified the code. please take a look. thanks.

2025-01-14 18:46 UTC, gelicia approved these changes
Took out an explicit type check to rely on typescript instead. Thank you for your contribution!

2025-01-14 20:14 UTC, gelicia commented
@yincongcyincong Hello, the code for this is looking good. I'll be doublechecking everything passes and being sure its in a couple unit tests, but then I can merge it :) Thank you for your contribution!

2025-01-14 21:38 UTC, merged