POC/Provisioning: Add legacy exporting (do not merge)
grafana/grafana pull request #98342
Opened 2024-12-21 14:10 UTC by ryantxu

WIP...

Adding this just for reference -- enough has changed that we should not use it directly without some more attention.  

But it kinda works still..

From:
* https://github.com/grafana/grafana/pull/68940/files
* https://github.com/grafana/grafana/tree/3fb89bd53761b6196b3f97f28ba234b1238ac68b/pkg/services/export

2025-01-16 09:53 UTC, MissingRoberto requested changes
partial review. Pending `legacy` package.

2025-01-16 09:53 UTC, MissingRoberto commented on pkg/apis/provisioning/v0alpha1/jobs.go
> +type ExportOptions struct {
(likely not in this PR). What about given the option to pick the branch so that users can open a PR for this change? 

The system will create the branch out of the default branch, commit the necessary changes and push it to the remote. 
Once the job is completed, the user is present with an option to open a pull request.

2025-01-16 09:53 UTC, MissingRoberto commented on pkg/server/wire.go
> +	provisioninglegacy "github.com/grafana/grafana/pkg/registry/apis/provisioning/jobs/legacy"
I know the words have different meaning but legacy is usually interpreted as `deprecated`. What was your intent on calling it legacy?

2025-01-16 09:53 UTC, MissingRoberto commented on public/app/features/provisioning/ExportToRepository.tsx
> +import { useEffect } from 'react';
I would have imagined a much simpler frontend change for this first iteration. 

I would: 
- Add a button `Export` in the Repository Page above the sections. This button will be disabled if there is an ongoing export job. You could also create the alert in this chunk. 
- In the existing `Recent Events`, users can see the status already of the job. So it will be a noop.

2025-01-16 09:53 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/worker.go
> +		if job.Spec.Export != nil && job.Spec.Export.History {
A couple of points on this one: 
- JobWorker should remain as lean as possible because it already has a lot of the wiring and selection on which type of job and what to call. 
- The Export logic should be condensed in a single spot where the actual logic is implemented. This comment is a code smell`// Uses k8s API against the configured folder`. I would plug the `LegacyExporter` into the replicator as well and the export options in the signature of that `Export` method and handle the cases there.

2025-01-16 10:40 UTC, MissingRoberto requested changes
partial review. Testing now

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	fmt.Printf("USERS: %+v\n", users)
let's remove any `fmt` once it's out draft :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	err = helper.add(commitOptions{
hi there! :P

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	if false {
**offline discussion**: to be deleted together with data sources

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	if true {
we can remove this one as it's always the case :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	// 1. Get users
it does only 1 think here :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	// Nested folder
what is this part for?

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/service.go
> +	// 1. Get users
you can also remove the comment here. It's clear enough with the code.

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/commit_helper.go
> +	"github.com/go-git/go-git/v5"
Same as we did for github, we probably should move everything `git` related to a `git` folder. That would keep the `legacy` and `git` code separate which will use or reuse for a multi-tenant world :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/commit_helper.go
> +			fmt.Printf("STATUS: %+v\n", status)
we can remove this comment :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/types.go
> +type userInfo struct {
`userInfo` can be moved to the `git` package :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/types.go
> +type folderInfo struct {
[style] This can be moved to `export_folders.go` and this file removed. It's only used there.

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/export_ds.go
> +package legacy
**offline discussion**: to be removed as datasources are not planned to be supported in the MVP.

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/export_folders.go
> +	fmt.Printf("QUERY: %s (%d)\b", query, helper.orgID)
fmt prints :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/export_dash.go
> +	// // Should root files be at the root or in a subfolder called "general"?
They should be at the configured folder within the Github repository (e.g. grafana) :)

2025-01-16 10:40 UTC, MissingRoberto commented on pkg/registry/apis/provisioning/jobs/legacy/export_dash.go
> +			fmt.Printf("COMMIT: %d // %s (%d)\n", count, fpath, row.Version)
more prints

2025-01-16 11:17 UTC, ryantxu commented on pkg/server/wire.go
> +	provisioninglegacy "github.com/grafana/grafana/pkg/registry/apis/provisioning/jobs/legacy"
Ideally we can get everything from unified storage/target architecture.  This package uses all the internal raw commands and will not work (easily) in a multi-tenant world 😬 

intention is to make sure it is clear that the stuff in that folder should be replaced (although not yet really possible)

2025-01-16 11:27 UTC, MissingRoberto commented
# First test

A couple of issues: 

- Job fails with error but the git history and the folder seems to be present: 
```
{"action":"export","export":{"history":true}}{"state":"error","started":1737026410891,"finished":1737026411336,"errors":["cannot create empty commit: clean working tree"]}
```
- Git history is not too clear with only `Version: 1` message. I guess we should also add the dashboard / folder in question. 
```
commit f911b05e92c6581c6ea2e8d0927093210f8e0d8a (HEAD -> main)
Author: admin <admin@unknown.org>
Date:   Tue Jan 14 11:16:33 2025 +0100

    Version: 1

commit beb07d321ac8f92d32573ff3598751bfb6ddceb7
Author: admin <admin@unknown.org>
Date:   Tue Jan 14 11:16:32 2025 +0100

    Version: 1

commit 8ca5b117cce1404b25d8efd32a8a5fd97a4f7cd1
Author: admin <admin@unknown.org>
Date:   Tue Jan 14 11:16:31 2025 +0100

    Version: 1

commit 6c4eb8a9d8ee459272dd278df54ab79486dfa41b
Author: admin <admin@unknown.org>
Date:   Tue Jan 14 11:16:31 2025 +0100

    Version: 1

commit e1724f3a7a053a8f3d0fe9b996149b7d43a481e7
Author: admin <admin@unknown.org>
Date:   Tue Jan 14 11:16:31 2025 +0100

    Version: 1

commit be381435367296452fd2bcb2af71a77fc62afb7a
Author: admin <admin@unknown.org>
Date:   Mon Jan 13 17:00:36 2025 +0100

    adding UID alias structure

commit 0b71d383d5d0f51a426469e8370b5cda4fb3ee35
Author: admin <admin@unknown.org>
Date:   Mon Jan 13 17:00:36 2025 +0100

    Exported folder structure

```
- Dashboards are not in the corresponding folders: 

```bash
.
├── dashboards
│   ├── Attempt
│   │   └── __folder.json
│   ├── Other
│   │   └── __folder.json
│   ├── Some folder
│   │   └── __folder.json
│   ├── forth-dashboard-dashboard.json
│   ├── nested
│   │   └── __folder.json
│   ├── one-dashboard-dashboard.json
│   ├── sample3-dashboard-dashboard.json
│   ├── second-dashboard-dashboard.json
│   ├── some-folder
│   │   └── __folder.json
│   └── third-dashboard-dashboard.json
├── hello.txt
├── root-alias.json
└── root-ids.json

7 directories, 13 files

```

2025-01-16 13:26 UTC, ryantxu commented on public/app/features/provisioning/ExportToRepository.tsx
> +import { useEffect } from 'react';
I'm not totally sure -- I am not sure we want an "export" shown anywhere except the initial setup wizard.  The goal here was to have *something* that can watch the single export job that would eventually end up in the wizard.

2025-01-21 10:58 UTC, MissingRoberto commented
(I am not sure if you merged the right things to the branch)

2025-02-13 11:25 UTC, ryantxu commented
Now supported via https://github.com/grafana/grafana/pull/100481

2025-02-13 11:25 UTC, closed without merging