Annotation: timeEnd not work
grafana/grafana pull request #98375
Opened 2024-12-26 02:34 UTC by yincongcyincong

Fixes #98099

2025-01-03 01:57 UTC, yincongcyincong commented
@aangelisc bro, could you please take a look this pr? thanks.

2025-01-03 09:39 UTC, yesoreyeram reviewed
LGTM. Can we use `strings.EqualFold` instead? 

https://pkg.go.dev/strings#EqualFold

2025-01-03 10:58 UTC, yincongcyincong commented
@yesoreyeram thanks for your review, i modified the code ,please take a look

2025-01-06 06:56 UTC, yincongcyincong commented
@yesoreyeram bro, could you please merge this pr into master? thanks

2025-01-17 12:47 UTC, yesoreyeram approved these changes

2025-01-17 13:27 UTC, yesoreyeram requested changes
rebase please

2025-01-20 01:52 UTC, yincongcyincong commented
> rebase please

@yesoreyeram thanks for your infoming, i merge master into this branch, please take a look.

2025-01-20 10:02 UTC, yesoreyeram approved these changes

2025-01-20 10:04 UTC, merged